### ISSUE TITLE
[CCE][NodePool] Initial nodes are provisioned into same AZ but AZ = random is given

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#1010]
# Terraform Version
```bash
$ terraform version
Terraform v0.15.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.23.
```
# Affected Resource(s)
- opentelekomcloud_cce_node_pool_v3

# Terraform Configuration Files
```hcl
variable "cluster_id" {}
variable "ssh_key" {}
variable "availability_zone" {}

resource "opentelekomcloud_cce_node_pool_v3" "node_pool_1" {
  cluster_id         = var.cluster_id
  name               = "opentelekomcloud-cce-node-pool_test"
  os                 = "CentOS 7.7"
  flavor             = "s2.xlarge.2"
  initial_node_count = 2
  availability_zone  = "random"
  key_pair           = var.ssh_key

  scale_enable             = true
  min_node_count           = 3
  max_node_count           = 9
  scale_down_cooldown_time = 100
  priority                 = 1

  root_volume {
    size       = 40
    volumetype = "SSD"
  }
  data_volumes {
    size       = 100
    volumetype = "SSD"
  }
}
```

# Debug Output/Panic Output

# Steps to Reproduce
1. `terraform apply`

# Expected Behavior
NodePool should be crated and the initial nodes should be distributed into all availability zones.

# Actual Behavior
The Initial node count (3+) are provisoned into the same availability zone.
![image](https://user-images.githubusercontent.com/3042152/116026110-492ac180-a652-11eb-800e-423ec855d0a2.png)

![image](https://user-images.githubusercontent.com/3042152/116026178-711a2500-a652-11eb-9289-6b3ac1351b3e.png)

# Important Factoids
When creating via UI, its the same issue...
So its more likely a platform then a TF provider issue but idk.

**Comment by lego963** [comment]
Internal incident: https://jira.tsi-dev.otc-service.com/browse/OCS-3726

**Comment by lego963** [comment]
@Moep90 ticket is resolved and `RandomAZ` works as expected. 
```
Random AZ allocation: The system will use a hash algorithm to select a default AZ based on your universally unique identifier (UUID).
```
Random AZ means that platform choose where all nodes/ecs will be located. 
As it's not clear CCE doc, it will be updated.

**Comment by Unichron** [comment]
@lego963 That's not how it seems to work. Each time I scale up the nodes they are placed in different AZ, which is good because roughly that's how you want a nodepool to behave with a randomized AZ setting (imho). Problem is that ALL of the nodes in the same scale up are placed in the same AZ. This means that if I only scale up 1 by 1 then I'll have a balanced nodepool, but if I scale up by more than 1 then I'll end up with an imbalanced nodepool.

**Comment by lego963** [comment]
@vladimirhasko can you support here please?

**Comment by vladimirhasko** [comment]
hello,
we have raised internal demand request (DM-2141) to R&D to clarify this behavior and eventually to fix it.

**Comment by Unichron** [comment]
FYI in the console when you create a nodepool the tooltip for Random AZ also states this:
```Nodes are randomly and evenly distributed in different Availability Zones, with higher reliability```

**Comment by lego963** [comment]
UPD: Demand request: https://jira.tsi-dev.otc-service.com/browse/DM-2141
