### ISSUE TITLE
opentelekomcloud_vpc_subnet_v1 id is counterintuitive 

### ISSUE THREAD

**Issue by DanielHabenicht** [opentelekomcloud/terraform-provider-opentelekomcloud#1013]
# Affected Resource(s)

Please list the resources as a list, for example:
- opentelekomcloud_vpc_subnet_v1 

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_vpc_subnet_v1" "cce_cluster_subnet" {
  name   = "${var.root_name}-subnet"
  vpc_id = var.vpc_id
  cidr   = var.subnet_cidr
  gateway_ip = var.vpc_gateway_ip
}

# Creating other resources would lead to the following intuitive approach:
resource "opentelekomcloud_lb_loadbalancer_v2" "cce_cluster_lb" {
  name          = "${var.root_name}-loadbalancer"
  vip_subnet_id = opentelekomcloud_vpc_subnet_v1.cce_cluster_subnet.id
}
```

# Steps to Reproduce
1. `terraform apply`

`cce_cluster_subnet.id` == `var.vpc_id` but should actually be `subnet_id` (which is available via `cce_cluster_subnet.subnet_id`. 

# Expected Behavior
The ID of the resource should actually be the ID of the resource instead of the one of "parent". 

The "parent" VPC should be available as another variable. 

# Important Factoids
This leads to failing deployments with LoadBalancers (because it expects a subnet), but with CCE Cluster deployments it does not fail but just accepts the whole network. This might lead to flawed network setups. (resources deployed in the wrong subnet), which might even lead to security issues as sensitive resources might be deployed in insensitive networks. 

# References
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_loadbalancer_v2

**Comment by DanielHabenicht** [comment]
Nevermind, seems like I copied one ID wrong and got confused.

**Comment by DanielHabenicht** [comment]
Still kind of confusing with the names, in `cce_cluster` an attribute named `subnet_id` is fed the value of `opentelekomcloud_vpc_subnet_v1.example_subnet.id` but also it has the attribute `opentelekomcloud_vpc_subnet_v1.example_subnet.subnet_id`.

**Comment by lego963** [comment]
@DanielHabenicht `id` of the `vpc_subnet_v1` is `network_id`. [Here](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/discussions/1008) is described `vpc_subnet_v1`. `subnet_id`/`network_id` is confusing, but we will try to fix it in future releases. [Here](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/967#issuecomment-816514956) is described.

**Comment by outcatcher** [comment]
There is again this `subnet`/`network`, `subnet`/`vpc` mess :disappointed: . I would rename `subnet_id` to `network_id` in the cluster, but there is `vpc_id` there too. 

On the other hand, I suppose we can really move from `subnet_id` and `vpc_id` to `network_id` only. Also, we can add `network_id` attribute to the subnet (the same `id`, but more understandable in this case). This topic was already raised in https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1007.

@DanielHabenicht does that sound like a good idea for you?

**Comment by outcatcher** [comment]
`network_id` will be added to `vpc_subnet_v1`: #1014

**Comment by DanielHabenicht** [comment]
well `network_id` is only used for subnets, right? I would rather be over specific using `subnet_network_id` and banning unspecific values like `network_id` or `subnet_id`. (in other resources attributes, e.g. cce)

Before I create another issue: There is no way to set the type (Public/Private) of an [ElasticLoadBalancer](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_loadbalancer_v2) via Terraform currently?
Also the old providers `opentelekomcloud_elb_loadbalancer` aren't working anymore?

**Comment by outcatcher** [comment]
>I would rather be over specific using subnet_network_id and banning unspecific values like network_id or subnet_id. (in other resources attributes, e.g. cce)

For that, we have to make a decision about the naming convention for all resources. Currently, there is a huge mess with OpenStack and non-OpenStack resources and their fields which is caused by the difference between Neutron and VPC (VPC = router, VPC subnet = network + subnet, if I'm correct). In case we move to OpenStack naming, there will be problems with different names on the console and in the provider. In the OTC itself, there is no single naming approach, each API has different attributes.

**Comment by outcatcher** [comment]
>Before I create another issue: There is no way to set the type (Public/Private) of an ElasticLoadBalancer via Terraform currently?

API [doc](https://docs.otc.t-systems.com/api/elb/en-us_topic_0096561535.html) says:
```
This API is used to create a private network load balancer. After the load balancer is created, its information is returned such as load balancer ID, IP address, and subnet ID.

To create a public network load balancer, you also need to call the API for assigning a floating IP address and associate this IP address to the port bound to the IP address of the private network load balancer.
```
So all v2 load balancers seem to be considered private until floating IP is assigned.

>Also the old providers opentelekomcloud_elb_loadbalancer aren't working anymore?

In the API documentation it's deprecated, but not deleted yet.

**Comment by DanielHabenicht** [comment]
> > Before I create another issue: There is no way to set the type (Public/Private) of an ElasticLoadBalancer via Terraform currently?
> 
> API [doc](https://docs.otc.t-systems.com/api/elb/en-us_topic_0096561535.html) says:
> 
> ```
> This API is used to create a private network load balancer. After the load balancer is created, its information is returned such as load balancer ID, IP address, and subnet ID.
> 
> To create a public network load balancer, you also need to call the API for assigning a floating IP address and associate this IP address to the port bound to the IP address of the private network load balancer.
> ```
> 
> So all v2 load balancers seem to be considered private until floating IP is assigned.

So will I have to use the API or should I create an issue?

> > Also the old providers opentelekomcloud_elb_loadbalancer aren't working anymore?
> 
> In the API documentation it's deprecated, but not deleted yet.

In the terraform Documentation it is not mentioned: https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/elb_backend

**Comment by outcatcher** [comment]
>In the terraform Documentation it is not mentioned:

It's also not mentioned in the API doc, user guide mentions both classic and elastic LB:
https://docs.otc.t-systems.com/usermanual/elb/en-us_elb_01_0007.html

On the console, there is the following message:
```
Classic load balancers are no longer provided. Create elastic load balancers instead.
Elastic load balancers provide comprehensive Layer 7 load balancing and better forwarding performance than classic load balancers. Learn more
```

After consulting with the internal QA team:
API is still working, existing LBs are still running, but creation via the console is impossible.

Will create an issue for resources deprecation.


>So will I have to use the API or should I create an issue?

Please use ELBv2 API

**Comment by outcatcher** [comment]
Internal issue for classic LB documentation: https://jira.tsi-dev.otc-service.com/browse/ONS-5244

**Comment by DanielHabenicht** [comment]
> Will create an issue for resources deprecation.

Thanks.

> >So will I have to use the API or should I create an issue?
> 
> Please use ELBv2 API

ELBv2 has no type, so only internal Load balancers can be created. Should i create an issue for adding the type and public IP parameters like in the classic Ressource?

**Comment by gtema** [comment]
guys, you need to be extra careful (and planning in advance):
- ELBv1 - deprecated and disabled
- ELBv2 - current, only present in DE region
- ELBv3 - new, present only in NL. In the long run will replace and "simulate" v2 API

**Comment by outcatcher** [comment]
>ELBv2 has no type, so only internal Load balancers can be created. Should i create an issue for adding the type and public IP parameters like in the classic Ressource?

I suppose we should just add an example of creating public ELBv2. With assigning floating IP to ELB local IP.

**Comment by DanielHabenicht** [comment]
> > ELBv2 has no type, so only internal Load balancers can be created. Should i create an issue for adding the type and public IP parameters like in the classic Ressource?
> 
> I suppose we should just add an example of creating public ELBv2. With assigning floating IP to ELB local IP.

That will not work, because it will throw an error, as the external IP is not in the subnet (but subnet is required).
(`"IP address 80.158.7.246 is not a valid IP for the specified subnet."` / `The argument "vip_subnet_id" is required, but no definition was found.`)


> guys, you need to be extra careful (and planning in advance):
> 
> * ELBv1 - deprecated and disabled
> * ELBv2 - current, only present in DE region
> * ELBv3 - new, present only in NL. In the long run will replace and "simulate" v2 API

Is there a roadmap?

**Comment by outcatcher** [comment]
>That will not work, because it will throw an error, as the external IP is not in the subnet (but subnet is required).

I've checked it using the following configuration:
```hcl
resource "opentelekomcloud_lb_loadbalancer_v2" "lb" {
  vip_subnet_id = var.subnet_id
}

resource "opentelekomcloud_networking_floatingip_v2" "ip" {}

resource "opentelekomcloud_networking_floatingip_associate_v2" "associate" {
  floating_ip = opentelekomcloud_networking_floatingip_v2.ip.address
  port_id     = opentelekomcloud_lb_loadbalancer_v2.lb.vip_port_id
}

```

**Comment by DanielHabenicht** [comment]
> > That will not work, because it will throw an error, as the external IP is not in the subnet (but subnet is required).
> 
> I've checked it using the following configuration:
> 
> ```terraform
> resource "opentelekomcloud_lb_loadbalancer_v2" "lb" {
>   vip_subnet_id = var.subnet_id
> }
> 
> resource "opentelekomcloud_networking_floatingip_v2" "ip" {}
> 
> resource "opentelekomcloud_networking_floatingip_associate_v2" "associate" {
>   floating_ip = opentelekomcloud_networking_floatingip_v2.ip.address
>   port_id     = opentelekomcloud_lb_loadbalancer_v2.lb.vip_port_id
> }
> ```

Thanks that's working! I tried tried it this way first (which errored): 
```hcl
resource "opentelekomcloud_vpc_eip_v1" "cce_cluster_public_eip" {
  publicip {
    type = "5_bgp"
  }
  bandwidth {
    name        = "${var.root_name}-cce-cluster-public-bandwidth"
    size        = var.cce_cluster_eip_bandwidth_size
    share_type  = "PER"
    charge_mode = "traffic"
  }
}

resource "opentelekomcloud_lb_loadbalancer_v2" "cce_cluster_lb" {
  name = "${var.root_name}-cce-cluster-loadbalancer"
  vip_subnet_id = opentelekomcloud_vpc_subnet_v1.cce_cluster_subnet.subnet_id
  vip_address = opentelekomcloud_vpc_eip_v1.cce_cluster_public_eip.publicip[0].ip_address
}
```

But this is working: 
```hcl
resource "opentelekomcloud_vpc_eip_v1" "cce_cluster_public_eip" {
  publicip {
    type = "5_bgp"
  }
  bandwidth {
    name        = "${var.ROOT_NAME}-cce-cluster-public-bandwidth"
    size        = 5
    share_type  = "PER"
    charge_mode = "traffic"
  }
}

# Load Balancer for public network traffic acccess
resource "opentelekomcloud_lb_loadbalancer_v2" "cce_cluster_lb" {
  name = "${var.ROOT_NAME}-cce-cluster-loadbalancer"
  vip_subnet_id = var.subnet_id
}

resource "opentelekomcloud_networking_floatingip_associate_v2" "associate" {
  floating_ip = opentelekomcloud_vpc_eip_v1.cce_cluster_public_eip.publicip[0].ip_address
  port_id     = opentelekomcloud_lb_loadbalancer_v2.cce_cluster_lb.vip_port_id
}
```
