### ISSUE TITLE
[V2] Use `OpenStack` naming for arguments

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/terraform-provider-opentelekomcloud#1017]
# Description of the enhancement
Currently, there is a huge mess with OTC-based naming (VPC, subnet, etc.) and OpenStack-based naming (router, network, subnet, etc.). We need to get rid of this ambiguity. I suppose, sticking to the OpenStack naming is more correct in this case.

**Comment by Aloento** [comment]
sticking to the OpenStack naming is more correct in this case.
