### ISSUE TITLE
[ELB][Security] Security Groups do not affect Loadbalancer

### ISSUE THREAD

**Issue by CSchmidtDD** [opentelekomcloud/terraform-provider-opentelekomcloud#1019]
Hi everyone,

we are experiencing a quite significant security-related problem with the enhanced loadbalancer.
The added security-group is not being applied to the loadbalancer itself and the following routing to the backend server group.

We have put the ELB into a separate Subnet (web) and SecGroup and are expecting that the settings from the secgroup-Web are being applied, but they do not.

Context: The backend-server-group utilized another subnet and other security-groups

# Terraform Version
0.13.6
# Affected Resource(s)
- opentelekomcloud_lb_loadbalancer_v2
- opentelekomcloud_networking_secgroup_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_lb_loadbalancer_v2" "lb_main" {
  provider = opentelekomcloud.customer
  name                = "elb-${var.project}"
  vip_address         = var.lb_ip
  vip_subnet_id       = opentelekomcloud_vpc_subnet_v1.net_web.subnet_id
  security_group_ids  = [
    opentelekomcloud_networking_secgroup_v2.sec_web.id 
  ]
  depends_on          = [
    opentelekomcloud_networking_secgroup_v2.sec_web
  ]
}

resource "opentelekomcloud_lb_listener_v2" "lb_https_listener" {
  provider = opentelekomcloud.customer
  name                      = "listener_${opentelekomcloud_lb_loadbalancer_v2.lb_main.name}_https"
  protocol                  = "TERMINATED_HTTPS"
  protocol_port             = var.lb_https_port
  tls_ciphers_policy        = "tls-1-2"
  http2_enable              = true
  loadbalancer_id           = opentelekomcloud_lb_loadbalancer_v2.lb_main.id
  default_tls_container_ref = opentelekomcloud_lb_certificate_v2.certificate_external.id
  sni_container_refs = [ 
    opentelekomcloud_lb_certificate_v2.certificate_external.id,
    opentelekomcloud_lb_certificate_v2.certificate_internal.id
   ]
}

resource "opentelekomcloud_lb_member_v2" "lb_https_member" {
  provider = opentelekomcloud.customer
  # iterate host instances
  count       = var.instance_count
  address       = opentelekomcloud_compute_instance_v2.instance_app[count.index].network[0].fixed_ip_v4
  protocol_port = var.lb_http_port
  pool_id       = opentelekomcloud_lb_pool_v2.lb_https_pool.id
  subnet_id     = opentelekomcloud_vpc_subnet_v1.net_app.subnet_id
}

resource "opentelekomcloud_networking_secgroup_v2" "sec_web" {
  provider = opentelekomcloud.customer
  name                  = "sec_web_${var.env}"
  description           = "Web Zone access"
  delete_default_rules  = true
}

resource "opentelekomcloud_networking_secgroup_rule_v2" "sec_web_rule_1" {
  provider = opentelekomcloud.customer
  description       = "HTTPS Access from Special IP"
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
  port_range_min    = 443
  port_range_max    = 443
  remote_ip_prefix  = "Special-IP/32"
  security_group_id = opentelekomcloud_networking_secgroup_v2.sec_web.id
}
```

# Debug Output/Panic Output
Plan & Apply works flawlessly, functionality is affected

# Steps to Reproduce
1. `terraform apply`
2. Check if IP is accessible from the special IP - OK
3. Check if I can access from anywhere else - I CAN - NOT OK

# Expected Behavior
It should not be possible to access the IP from any other address than the specified rule allowes

# Actual Behavior
The Settings of the given securitygroup is not taken into effect

# Important Factoids
- provider version 1.23.7
- Instances in App-Subnet and under App-SecGroup (in BSG)
- ELB in Web-Subnet and Web-SecGroup
- not very notable restrictions other than that

# References
no references

**Comment by gtema** [comment]
note: if I understand you correctly
LB is a so to say haproxy instance. SG on the VMs are only regulating incoming traffic, but are not really covering what passed already through the "reverse proxy" (they only get connections from LB itself). This is design of the LB. If you need to apply some additional rules you might need to go down to iptables/firewalld in the VM itself. It is currently not possible to do it otherwise.

In any way this is the platform issue, and not the TF

**Comment by CSchmidtDD** [comment]
Hey @gtema, let me try and explain the idea behind our setup in a small graphic.

Context:
User -HTTPS- ELB -HTTP- BSG
SecGroups:
Internet -HTTPS- Sec-Web -HTTP- Sec-App
Subnets:
Internet -HTTPS- Net-Web -HTTP- Net-App

- ELB (SecWeb / NetWeb)
- Instances in BSG (SecApp / NetApp)

If I understand correctly, a security group should limit inboudn and outbound connections through the set up rules. If I add a security-group to any product, it should work as intended.

The documentation of the option "security_group_ids" [here](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_loadbalancer_v2) says:
> security_group_ids - (Optional) A list of security group IDs to apply to the loadbalancer. The security groups must be specified  by ID and not name (as opposed to how they are configured with the Compute Instance).

This is not true right now from our perspective, what do you think?

I suppose this needs to be escalated to the provider itself (OTC) via a ticket (from me) and then closed as it is answered there and if the functionality is intended but completely useless?

**Comment by gtema** [comment]
that may be indeed a documentation bug in TF - API doesn't support setting SG on the v2 LB

**Comment by outcatcher** [comment]
@gtema Current implementation assigns security groups to the network port used by the load balancer.

**Comment by gtema** [comment]
ugh, totally "undocumented" stuff. I am from the service pov this is not guaranteed to really work. 
What may be used to some extend to allow filtering is whitelist (https://docs.otc.t-systems.com/api/elb/elb_zq_bm_0001.html)

Bad thing is that you can not really check this from UI. It's only something API specific and you MUST know that.

**Comment by outcatcher** [comment]
This `security_group_ids` argument was inherited from the openstack provider. So I assume it to work in the OpenStack, at least.

>from the service pov this is not guaranteed to really work.

Why won't security groups work with network port?

**Comment by gtema** [comment]
The issue is that in that concrete case we are not really running OpenStack, but something OpenStack compatible, so there is no real guarantee it works as you would expect.
Not that I state - it doesn't work. I just say - it is not guaranteed to work.

**Comment by outcatcher** [comment]
Not sure if we really can raise an internal ticket ― this doesn't seem to be described in the documentation.
I suppose we should mark `security_group_ids` as deprecated for the resource then argument and create a new `opentelekomcloud_lb_whitelist_v2` resource.

**Comment by CSchmidtDD** [comment]
Hey all.
Thank you for the high-value input on this matter!

**My key take-away here:**
To solve the brainclump we had with restricting access to the ELB from certain IP-addresses, a security group is not the answer.
More likely the usage and activation of **opentelekomcloud_lb_whitelist_v2** would deliver the correct expectation here.

Thanks for taking my issue into account.

**Comment by outcatcher** [comment]
Sorry for invalid reply. `opentelekomcloud_lb_whitelist_v2` alredy exist:
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_whitelist_v2

**Comment by outcatcher** [comment]
@CSchmidtDD please check if `opentelekomcloud_lb_whitelist_v2` resource matches your needs.
