### ISSUE TITLE
Provide data sources for opentelekomcloud_vpc_eip_v1

### ISSUE THREAD

**Issue by DanielHabenicht** [opentelekomcloud/terraform-provider-opentelekomcloud#1022]
# Description of the enhancement
It would be nice if terraform [data sources](https://www.terraform.io/docs/language/data-sources/index.html) would be supported for `opentelekomcloud_vpc_eip_v1`. This way more advanced configurations which consist of multiple moving parts could be achieved more easily. 

Example: 

For a consistent deployment a static IP should (almost) never be destroyed. 
Currently there are to options: 
- Either created manually before terraform deployment and manually provide the ip address 
- or create it via terraform and the manually remove it from the state

With `data sources` one could create the IP (or other one time resources) with one terraform deployment and the create another deployment which references the previously created resources by selecting its name.

```hcl
data "opentelekomcloud_vpc_eip_v1" "lb" {
  name = "${var.ROOT_NAME}-cce-cluster-public-ip"
}
```
Thus one can control the one time resources with terraform instead of having any manually steps in-between.

**Comment by lego963** [comment]
@DanielHabenicht we have data-sources for some services. Do you want to have `data-source/opentelekomcloud_vpc_eip_v1`?

**Comment by DanielHabenicht** [comment]
yes, that would be nice. I can change the title.

**Comment by DanielHabenicht** [comment]
Hi again, @lego963 @outcatcher 
The now implemented feature only supplies minor advantages. All the arguments supplied to the data source are not known before the deployment or aren't unique: 

![image](https://user-images.githubusercontent.com/13590797/117636690-5a5eec80-b181-11eb-9017-d6d812a6701e.png)

Which means I have to somehow retrieve one of the fields and supply them to my second deployment.
But what I wanted to achieve is rather to use one unique value through all deployments to retrieve the according resource during the deployment of each terraform script. (that's why is used `name` although its not a value of `opentelekomcloud_vpc_eip_v1`) E.g.: 

Deployment one: 
```hcl
resource "opentelekomcloud_vpc_eip_v1" "public_eip_lb" {
  publicip {
    type = "5_bgp"
  }
  bandwidth {
    name        = "${var.ROOT_NAME}-public-eip-lb-bandwidth"
    size        = var.BANDWITH_SIZE
    share_type  = "PER"
    charge_mode = "traffic"
  }
  tags = [
    {
      key   = "key-to-retrieve-ressource-in-terraform"
      value = "resource-name-i-want-to-use-everywhere"
    }
  ]
}
```

Deployment two:
```hcl
data "opentelekomcloud_vpc_eip_v1" "lb" {
  tags = [
    {
      key   = "key-to-retrieve-ressource-in-terraform"
      value = "resource-name-i-want-to-use-everywhere"
    }
  ]
}
# and do something with it
```

I would therefore suggest to add tags as query argument to the datasource. 

Should I open another issue?
