### ISSUE TITLE
Add ability import all resources

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#1023]
# In the following I describe on which resources I failed to import them into a new state
For some reasons I need to import my existing resources as much as possible.
Therefore I test it for all of them and extend the list accordlingly....

- [x] VPC `opentelekomcloud_vpc_v1`
- [x] VPC Subnet `opentelekomcloud_vpc_subnet_v1`
- [x] Keypair `opentelekomcloud_compute_keypair_v2` 
- [x] CCE Master `opentelekomcloud_cce_cluster_v3`
- [x] DNS-Zone `opentelekomcloud_dns_zone_v2` 
- [x] SecGroups `opentelekomcloud_networking_secgroup_v2`
- [x] SecGroup Rules `opentelekomcloud_networking_secgroup_rule_v2`
- [ ] RDS instance `opentelekomcloud_rds_instance_v3`
- [ ] ECS `opentelekomcloud_compute_instance_v2`

## RDS
After running:

```hcl
$ terraform import module.rds.opentelekomcloud_rds_instance_v3.this xyxyxyxyxyxyxyxxyxyxyxyxyxyx
module.rds.opentelekomcloud_rds_instance_v3.this: Importing from ID "xyxyxyxyxyxyxyxxyxyxyxyxyxyx"...
module.rds.opentelekomcloud_rds_instance_v3.this: Import prepared!
  Prepared opentelekomcloud_rds_instance_v3 for import
module.rds.opentelekomcloud_rds_instance_v3.this: Refreshing state... [id=xyxyxyxyxyxyxyxxyxyxyxyxyxyx]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
but running it again results in 
```hcl
$ terraform plan -target module.rds
module.rds.opentelekomcloud_rds_instance_v3.this must be replaced
-/+ resource "opentelekomcloud_rds_instance_v3" "this" {
      + availability_zone   = [
          + "eu-de-02",
          + "eu-de-01",
        ] # forces replacement
      ~ created             = "2020-10-15T14:57:11+0000" -> (known after apply)
      ~ id                  = "xyxyxyxyxyxyxyxxyxyxyxyxyxyx" -> (known after apply)
        name                = "postgres-rds"
      ~ nodes               = [
          - {
              - availability_zone = "eu-de-02"
              - id                = "xxxxxxxxxxxxxxxxxxxxxxx"
              - name              = "postgres-rds_node0"
              - role              = "master"
              - status            = "ACTIVE"
            },
          - {
              - availability_zone = "eu-de-01"
              - id                = "yyyyyyyyyyyyyyyyyyyyy"
              - name              = "postgres-rds_node1"
              - role              = "slave"
              - status            = "ACTIVE"
            },
       ] -> (known after apply)

      [....]



    }

```

## ECS
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/compute_instance_v2
```
module.modulename.opentelekomcloud_compute_instance_v2.ecs_instance[0]: Importing from ID "xxxxx-yyyy-zzz"...
╷
│ Error: resource opentelekomcloud_compute_instance_v2 doesn't support import
```
## SecGroup Rules
This maybe not related to import itself...but worth mentioning it...
#1028 
```
-/+ resource "opentelekomcloud_networking_secgroup_rule_v2" "rules" {
      + description       = "Security Group Rule managed by Terraform" # forces replacement

```

**Comment by outcatcher** [comment]
Some resources really lack attributes that can be read from the API. Please describe exact resources you want to import.
I assume this issue to be about `compute_instance_v2`.

**Comment by Moep90** [comment]
@outcatcher Sure, I'll update while doing it :-)

**Comment by outcatcher** [comment]
RDS: For import, we're limited to fields returned by the GET request. Querying RDS instance doesn't return `availability_zone` for the instance in the response ― only `availability_zone` for each node. I suppose we will need an internal issue for that.

**Comment by outcatcher** [comment]
I will move RDS import to a stand-alone issue, so we will be able to track internal issue progress.

**Comment by Moep90** [comment]
@outcatcher can we somehow push the ECS data source?
We're in desperate need of it currently...

**Comment by outcatcher** [comment]
@Moep90 data source or ECS import? No problem, we will include the required into today's release.

**Comment by Moep90** [comment]
@outcatcher sorry for the confusion, import of course :face_with_head_bandage:

**Comment by outcatcher** [comment]
Will be part of today release
@Moep90  Also, `opentelekomcloud_ecs_instance_v1` already supported importing.

**Comment by Moep90** [comment]
@outcatcher is this compatible with `opentelekomcloud_compute_instance_v2` when imported with `opentelekomcloud_ecs_instance_v1`?

**Comment by outcatcher** [comment]
Both ECSv1 and Computev2 (OpenStack-compatible) APIs provide access to the same instances. Though attributes and arguments of the resources have differences.

**Comment by Moep90** [comment]
hm this doesnt work as expected.
When having a VPC with multiple subnets in it, I get the following:

The network looks like:
```hcl
resource "opentelekomcloud_vpc_v1" "vpc_v1" {
  name = var.vpc_name
  cidr = var.vpc_cidr
}

resource "opentelekomcloud_vpc_subnet_v1" "subnet_1" {
  name   = var.subnet_name_1
  cidr   = var.subnet_cidr_1
  vpc_id = opentelekomcloud_vpc_v1.vpc_v1.id

  gateway_ip    = var.subnet_gateway_ip_1
  ntp_addresses = "10.100.0.33,10.100.0.34"
}

resource "opentelekomcloud_vpc_subnet_v1" "subnet_2" {
  name   = var.subnet_name_2
  cidr   = var.subnet_cidr_2
  vpc_id = opentelekomcloud_vpc_v1.vpc_v1.id

  gateway_ip    = var.subnet_gateway_ip_2
  ntp_addresses = "10.100.0.33,10.100.0.34"
}

resource "opentelekomcloud_vpc_subnet_v1" "subnet_3" {
  name   = var.subnet_name_3
  cidr   = var.subnet_cidr_3
  vpc_id = opentelekomcloud_vpc_v1.vpc_v1.id

  gateway_ip    = var.subnet_gateway_ip_3
  ntp_addresses = "10.100.0.33,10.100.0.34"
}
```
The instance looks like:
I double checked that the Instances is (for real) only connected to ONE network...
```hcl
resource "opentelekomcloud_compute_instance_v2" "ecs_instance" {
  name      = "boot-from-volume"
  flavor_id = var.flavor_id
  key_pair  = var.key_pair
  image_id  = var.image_id

  network {
    id        = opentelekomcloud_vpc_subnet_v1.subnet_2.id
    fixed_ip_v4 = "<fixed_ip_v4>"
  }

}
```


```bash
$ terraform import opentelekomcloud_compute_instance_v2.ecs_instance xxxxxxxxxxxxxxx-yyyyyyyyyyyyyyy
opentelekomcloud_compute_instance_v2.ecs_instance: Importing from ID "xxxxxxxxxxxxxxx-yyyyyyyyyyyyyyy"...
opentelekomcloud_compute_instance_v2.ecs_instance: Import prepared!
  Prepared opentelekomcloud_compute_instance_v2 for import
opentelekomcloud_compute_instance_v2.ecs_instance: Refreshing state... [id=xxxxxxxxxxxxxxx-yyyyyyyyyyyyyyy]

Error: Error trying to get network information from the Network API: More than one network found for name <ID of the VPC>
```
