### ISSUE TITLE
[ELB][Listener] persistence should be disabled when set to null

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#1027]
# Terraform Version
```
Terraform v0.15.0
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.23.8
```

# Affected Resource(s)
- opentelekomcloud_lb_pool_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_lb_pool_v2" "pool_1" {
  protocol    = "HTTP"
  lb_method   = "ROUND_ROBIN"
  listener_id = "xxxxxxxxxxxxxxyyyyyyyyyyyyyyy"

  persistence {
    type        = null
    cookie_name = null
  }
}
```

# Debug Output/Panic Output
```hcl
│ Error: "persistence.0.type": required field is not set
│ 
│   on .terraform/modules/elb-01/main.tf line 72, in resource "opentelekomcloud_lb_pool_v2" "this":
│   72: resource "opentelekomcloud_lb_pool_v2" "this" {
```

# Steps to Reproduce
1. `terraform apply`

# Expected Behavior
Persistence set to `null` it will be ignored

# Actual Behavior
```hcl
│ Error: Only 'SOURCE_IP', 'HTTP_COOKIE', and 'APP_COOKIE' are supported values for 'persistence'
│ 
│   on .terraform/modules/elb-01/main.tf line 72, in resource "opentelekomcloud_lb_pool_v2" "this":
│   72: resource "opentelekomcloud_lb_pool_v2" "this" {

```

# Important Factoids
- There is already a hint on persistence, but omit it is not suitable for a reusable module

**Comment by lego963** [comment]
@Moep90 these `security_groups` are returned from `vip_port_id`. As I can see, `port` for loadbalancer is created with `security_ group`

**Comment by Moep90** [comment]
This is not about the secgroup. Its about the persistente block..

**Comment by lego963** [comment]
@Moep90 sorry, wrong issue. I will look on it

**Comment by lego963** [comment]
@Moep90 let me clarify, do you want to use this resource with 
```
  persistence {
    type        = null
    cookie_name = null
  }
```
?


UPD1: If you omit `persistence` block in tf it will create with `null`? Why do you need to specify this `persistence`?

**Comment by Moep90** [comment]
When building a module, I want to have all options available within the module. 
Therefore I need to have the option to specify persistence if required. So I cannot omit the persistence block.
