### ISSUE TITLE
[ELB][SecurityGroup] SG always change

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#1038]
# Terraform Version
```
$ terraform --version
Terraform v0.15.0
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.23.9
```

# Affected Resource(s)

- opentelekomcloud_lb_loadbalancer_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_lb_loadbalancer_v2" "this" {
  count = var.create_lb ? 1 : 0

  name                  = "name"
  vip_subnet_id         = var.subnet_id
  description           = var.description
  tenant_id             = var.tenant_id
  vip_address           = var.vip_address
  admin_state_up        = var.admin_state_up
  loadbalancer_provider = var.loadbalancer_provider
  security_group_ids    = null

}
```

# Debug Output/Panic Output
```gcl
  # elb.opentelekomcloud_lb_loadbalancer_v2.this[0] will be updated in-place
  ~ resource "opentelekomcloud_lb_loadbalancer_v2" "this" {
        id                    = "xxxxxxxx-yyyyyyyy-zzzz"
        name                  = "elb"
      ~ security_group_ids    = [
          - "zzzzzz-yyyy-4d5f-9c14-xxxxxxxxxx",
        ]
        # (8 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

```
# Workaround 
1. data query the default SG and attach it to the ELB (changing the default SG could lead to unwanted behavior)
2. Add SG + rules and attach to ELB
3. ignore_changes (appends by default to the default SG...) (changing the default SG could lead to unwanted behavior)
```hcl
resource "opentelekomcloud_lb_loadbalancer_v2" "this" {
  count = var.create_lb ? 1 : 0

  name                  = "name"
  vip_subnet_id         = var.subnet_id
  description           = var.description
  tenant_id             = var.tenant_id
  vip_address           = var.vip_address
  admin_state_up        = var.admin_state_up
  loadbalancer_provider = var.loadbalancer_provider
  security_group_ids    = null


  lifecycle {
    ignore_changes = [
      security_group_ids
    ]
  }
}
```

# Steps to Reproduce
1. `terraform apply`

# Expected Behavior
The ELB will not be changed on every run

# Actual Behavior
When providing null to the secGroup -> the platform seams to assign some sort of a default.

# Factoides
This is for sure platform related, the RDS HA has this issue with its name as well.

# References
#1019

**Comment by lego963** [comment]
@Moep90 these security_groups are returned from `vip_port_id`. As I can see, port for loadbalancer is created with `default` security_group.

**Comment by outcatcher** [comment]
SG are broken for OTC ELBv2 (and their support is not really defined in the documentation):
https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1019#issuecomment-827537749

Please use [`opentelekomcloud_lb_whitelist_v2`](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_whitelist_v2) instead for controlling LB access.

**Comment by outcatcher** [comment]
SG removal is scheduled for later release: https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1061

If no update is wanted for the SG, `security_group_ids` should not be set.
Whitelist to be used otherwise.
