### ISSUE TITLE
Terraform wants to re-sort DNS entries and fails

### ISSUE THREAD

**Issue by patricktoelle** [opentelekomcloud/terraform-provider-opentelekomcloud#104]
### Terraform Version
Terraform v0.11.7
+ provider.opentelekomcloud v1.1.0

### Affected Resource(s)
opentelekomcloud_dns_recordset_v2

### Terraform Configuration Files
```hcl
resource "opentelekomcloud_dns_recordset_v2" "swarm" {
  zone_id = "${opentelekomcloud_dns_zone_v2.infrastructure.id}"
  name    = "swarm.${opentelekomcloud_dns_zone_v2.infrastructure.name}"
  ttl     = 300
  type    = "A"
  records = ["${module.swarm.floating_ipv4}"]

  lifecycle {
    ignore_changes = ["id", "region"]
  }
}
```

### Expected Behavior

DNS entries of `module.swarm.floating_ipv4` should not be altered, if no IP changes.

### Actual Behavior

DNS entries would get resorted at run, run fails.

```
      records.0:  "x.x.x.x" => "y.y.y.y"
      records.1:  "y.y.y.y" => "x.x.x.x"
```

```
* opentelekomcloud_dns_recordset_v2.swarm: Error updating OpenTelekomCloud DNS  record set: Invalid request due to incorrect syntax or missing required parameters.
```
Full gist at: https://gist.github.com/patricktoelle/f8a82b644608fb1afca9515e0b777ce4

DNS records were created by terraform. If I delete them from OTC console, they get created correctly, but on next run, same resorting and failing.

Do you have any idea how to solve it or may you need some more information to reproduce?

**Comment by niuzhenguo** [comment]
Sorry for the delay, will address this soon!
