### ISSUE TITLE
[CCE][NODEPOOL]  resource opentelekomcloud_cce_node_pool_v3 doesn't support import

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#1040]
# Description of the enhancement
While trying to import a CCE-Nodepool I noticed that it is not possible to be imported..

# Resource
- `opentelekomcloud_cce_node_pool_v3`

```hcl
terraform import opentelekomcloud_cce_node_pool_v3.this xxxxxxxxxxyyyyyyyyyyyyyyyyyyy
 Error: resource opentelekomcloud_cce_node_pool_v3 doesn't support import
```

# Reference
#1023

**Comment by lego963** [comment]
@Moep90 we can't it implement, because for quering `cce_node_pool` we need `cluster_id`
