### ISSUE TITLE
[VPC][PORT] Disabling port security is not supported

### ISSUE THREAD

**Issue by arnaud-mey** [opentelekomcloud/terraform-provider-opentelekomcloud#1043]
# Affected Resource(s)
- opentelekomcloud_networking_port_v2

#Terraform Version

Terraform v0.14.9
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.23.8

I'm trying to disable port_security (Source/Destination Check) for port resources but it seems that disabling it is not supported by the terraform module. It can be disabled in the web gui though and via the openstack api. 

Is there a way to disable port security?

**Comment by lego963** [comment]
@arnaud-mey we will implement this enhancement :)
