### ISSUE TITLE
Deletion of last VPC fails

### ISSUE THREAD

**Issue by DanielHabenicht** [opentelekomcloud/terraform-provider-opentelekomcloud#1050]
# Terraform Version
```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.3
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.23.9

Your version of Terraform is out of date! The latest version
is 0.15.3. You can update by downloading from https://www.terraform.io/downloads.html
```
# Affected Resource(s)
- opentelekomcloud_vpc_v1

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_vpc_v1" "test_vpc" {
  name   = "${var.ROOT_NAME}-vpc"
  cidr   = "172.16.0.0/16"
  shared = true
}
```

# Debug Output/Panic Output
```bash
Error: Error deleting OpenTelekomCloud Vpc: Expected HTTP response code [202 204] when accessing [DELETE https://vpc.eu-de.otc.t-systems.com/v1/c80b0ba7e2f44c5d96a4929a6fe2870c/vpcs/75ed9e2f-5a62-46c6-8153-a861a53279ee], but got 409 instead
{"code":"VPC.0108","message":"{\"NeutronError\":{\"message\":\"Router is used not allow deleted\",\"type\":\"RouterInUse\",\"detail\":\"\"}}"}
```

# Steps to Reproduce
Use an empty OTC Account:

1. Create a EIP by hand
1. `terraform apply`
2. `terraform delete`

# Expected Behavior
I would expect that creating a resource and deleting it works without errors. 

# Actual Behavior
Errors.

# Important Factoids
The Console is failing with a different one (but the IP was not referenced with the vpc), but I have seen this one too: `This is the last VPC. Delete the Route Table before you delete this VPC.`

![image](https://user-images.githubusercontent.com/13590797/117642720-ebd15d00-b187-11eb-9e58-71b11cac49fe.png)

BTW: 
Is the usage of `opentelekomcloud_vpc_v1` discouraged or at least is the use of `opentelekomcloud_networking_network_v2` encouraged? I have not tried it with the newer version yet.

**Comment by lego963** [comment]
@DanielHabenicht it's strange and I cant reproduce same behaviour

**Comment by DanielHabenicht** [comment]
I will try to make a better reproduction on Monday.

**Comment by outcatcher** [comment]
@DanielHabenicht Have you tried to reproduce that? Please check if there are resources not managed by the terraform in your case.

**Comment by outcatcher** [comment]
Please comment if this issue is still needed

**Comment by DanielHabenicht** [comment]
Finally found out. 
It seems to be that EIPs that are associated with an Load Balancer (which in turn is associated with a subnet) will hinder the subnet from being deleted after the Load Balancer gets deleted. 

```tf
# Load Balancer for public network traffic acccess
resource "opentelekomcloud_lb_loadbalancer_v2" "cce_cluster_lb" {
  name          = "${var.root_name}-cce-cluster-loadbalancer"
  vip_subnet_id = opentelekomcloud_vpc_subnet_v1.cce_cluster_subnet.subnet_id
}

resource "opentelekomcloud_networking_floatingip_associate_v2" "associate" {
  floating_ip = var.public_ip
  port_id     = opentelekomcloud_lb_loadbalancer_v2.cce_cluster_lb.vip_port_id
}
```

**Comment by DanielHabenicht** [comment]
Come across it again. 
Following Reproduction: 
Empty OTC Account
1. Create a EIP with another script or by hand. 
2. Create a VPC as shown initially (with terraform)
3. Try deleting the VPC as shown initially (with terraform)

Seems like EIP can't exist without a VPC once a VPC was created. Because creating a EIP without a VPC works fine. 
This also happens when I do it completely manually.

**Comment by gtema** [comment]
This is not a TF issue, but a platform. The same might happen if you i.e. create VPC using TF and attach NATGW to it per hand. Same also happens for the security groups.

**Comment by DanielHabenicht** [comment]
@gtema have you raised it with the support team? If not I might do it.

**Comment by gtema** [comment]
@DanielHabenicht, nope, I haven't.

**Comment by DanielHabenicht** [comment]
@outcatcher can you raise it with the support if you also think that this is a weird behavior? They are not writing back to me. :/

**Comment by outcatcher** [comment]
Internal incident created:
https://jira.tsi-dev.otc-service.com/browse/ONS-5750
