### ISSUE TITLE
Provide a way to remove auto-installed addons on cce creation

### ISSUE THREAD

**Issue by Unichron** [opentelekomcloud/terraform-provider-opentelekomcloud#1056]
Currently when you create a CCE cluster the coredns and everest addons are installed automatically. There is no automated way to either override these or adopt them to the terraform code.

To solve this it would be nice to implement some support for this:
1. Extend the cce resource with the option to remove the auto-installed addons (preferable)
2. Extend the cce_addon resource to support importing (less nice solution because you still need to manually import them, but resource import is generally a nice feature to have anyway)

**Comment by outcatcher** [comment]
Let's start with import implementation. And then add the `skip_addons` argument (to be further discussed).
