### ISSUE TITLE
Why can't the disk size for as_configuration be lower than 40GB?

### ISSUE THREAD

**Issue by grafburg** [opentelekomcloud/terraform-provider-opentelekomcloud#1083]
Hello,

I wonder why the SYS disk size needs to be at least 40GB for the as_configuration ressource?

Documentation:
> The `disk` block supports:
> 
> * `size` - (Required) The disk size. The unit is GB. The system disk size ranges from 40 to 32768,
>   and the data disk size ranges from 10 to 32768.

[Code:](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/ece1e609c2e12ff4b5a3215a272000a35b7605bd/opentelekomcloud/services/as/resource_opentelekomcloud_as_configuration_v1.go#L415)
> ```go
> if diskType == "SYS" {
> 			if size < 40 || size > 32768 {
> 				mErr = multierror.Append(mErr, fmt.Errorf("for system disk size should be [40, 32768]"))
> 			}
> 		}
> ```

**Comment by lego963** [comment]
@mbdotnet we can't create "SYS" with <5gb. Only 6 Gigs is possible. I will create internal incident
