### ISSUE TITLE
opentelekomcloud_rds_instance_v3 does not have an attribute named "user_name"

### ISSUE THREAD

**Issue by hcantzler** [opentelekomcloud/terraform-provider-opentelekomcloud#1091]
The documentation page for opentelekomcloud_rds_instance_v3 mentions an attribute named "user_name". When trying to output it, I get an error message.

https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/rds_instance_v3

## TF code
```hcl
resource "opentelekomcloud_rds_instance_v3" "database" {
  name              = "dLS-${var.env}-rds"
  availability_zone = ["eu-de-01"]

  db {
    password = random_string.database_admin_password.result
    type     = var.rds_db_type
    version  = var.rds_db_version
  }

  security_group_id = opentelekomcloud_networking_secgroup_v2.database_sg.id
  subnet_id         = opentelekomcloud_vpc_subnet_v1.subnet_database.id
  vpc_id            = opentelekomcloud_vpc_v1.network.id
  flavor            = var.rds_flavor

  volume {
    type = var.rds_volume_type
    size = var.rds_volume_size
  }

  backup_strategy {
    start_time = "04:00-05:00"
    keep_days  = 14
  }
}

output "database_admin_user_name" {
  value = opentelekomcloud_rds_instance_v3.database.user_name
}
```

## TF error message

```
Error: Unsupported attribute

  on outputs.tf line 18, in output "database_admin_user_name":
  18:   value = opentelekomcloud_rds_instance_v3.database.user_name

This object has no argument, nested block, or exported attribute named
"user_name".
```

**Comment by outcatcher** [comment]
The `user_name` is read-only attribute of the `opentelekomcloud_rds_instance_v3` (it's located not in _argument_ but in _attributes_ section). It can't be set via API: https://docs.otc.t-systems.com/api/rds/rds_01_0002.html. It's read after the creation: https://docs.otc.t-systems.com/api/rds/rds_01_0004.html#rds_01_0004__table2058713718267

**Comment by hcantzler** [comment]
Yes, "user_name" is an attribute. This is what I am saying. I am not trying to set it. I am trying to output it and get an error. I should be able to output a read-only attribute, right?

output "database_admin_user_name" {
value = opentelekomcloud_rds_instance_v3.database.user_name
}

**Comment by outcatcher** [comment]
Sorry then, I've got it wrong. What version of the provider do you use?

**Comment by hcantzler** [comment]
I am using the following versions:
Terraform v0.14.6
provider registry.terraform.io/hashicorp/random v3.1.0
provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.23.12

Maybe helpful, these are the database parameters that I use for provisioning:
rds_db_type = "PostgreSQL"
rds_db_version = "11"
rds_flavor = "rds.pg.c2.medium"
rds_volume_type = "ULTRAHIGH"
rds_volume_size = 100

**Comment by outcatcher** [comment]
This seems to be a format issue in the documentation:
![image](https://user-images.githubusercontent.com/8591561/120155552-9eca2f00-c1f9-11eb-91ca-e345ad4f3e91.png)
`user_name` should have more padding to make clear it's is sub-attribute of `db`. You should be able to access it with `opentelekomcloud_rds_instance_v3.database.db.0.user_name`.

**Comment by hcantzler** [comment]
Yes, using a "db" block with user_name inside works for me. Thank you!
