### ISSUE TITLE
No way for configuring the WAF TLS settings

### ISSUE THREAD

**Issue by hcantzler** [opentelekomcloud/terraform-provider-opentelekomcloud#1092]
I setup the WAF opentelekomcloud_waf_domain_v1. I don't how I can configure the WAF domain TLS settings using terraform. I am able to configure the TLS ciphersuite manually in the portal, but there is no functionality for doing it with terraform it seems.

https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/waf_domain_v1

**Comment by outcatcher** [comment]
@hcantzler `waf_domain_v1` provides `certificate_id` argument and `server.client_protocol`, which can be set to `HTTPS`. Is there something else missing? It's basically all that supported from API: https://docs.otc.t-systems.com/api/waf/waf_02_0013.html

**Comment by hcantzler** [comment]
If I look at the WAF domain configuration screen on the portal, I am able to see configuration options for changing the TLS Configuration and setting up a custom Alarm Page. I don't know about the APIs under the hood, but supposedly there must be some kind of API to configure these things. So, perhaps it would be a good enhancement to allow configuration of WAF TSL and alarm page settings via Terraform. Otherwise, I need to do it manually.

The WAF IP Address Range is also accessible on the WAF domain configuration screen. Perhaps, this could be accessible via Terraform as well.

**Comment by outcatcher** [comment]
@hcantzler We need to investigate what WAF itself provides to provide you with more details :slightly_smiling_face:

**Comment by lego963** [comment]
We don't have API in doc for this change for now.
Internal incident: https://jira.tsi-dev.otc-service.com/browse/OTCSEC-2007
