### ISSUE TITLE
Allow more configurations on `rds_read_replica_v3`

### ISSUE THREAD

**Issue by rbange** [opentelekomcloud/terraform-provider-opentelekomcloud#1099]
We are trying to use the `rds_read_replica_v3` feature introduced in 1.23.11, but are confused by the usage of the resource.

Why are the replicas structured into groups? This does not really reflect the handling in the OTC web console.

# Description of the enhancement

Also, it would be nice to have  a comparable handling as `rds_instance_v3` which allows to configure a separate `sec_group`, `subnet`, `vps` or `public_ip`

**Comment by outcatcher** [comment]
@rbange What do you mean by "Why are the replicas structured into groups?"?

**Comment by rbange** [comment]
The documentation (https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/rds_read_replica_v3#id) specifies the `rds_read_replica_v3.id` as the `ID of the read replica group`. Whereas the OTC web console does not show any kind of grouping of read replica instances. Is this a documentation issue or did we interpreted this description wrong?

**Comment by outcatcher** [comment]
This is just a misprint in the documentation, to be fixed.

**Comment by outcatcher** [comment]
After some testing: it seems, VPC, subnet, and security group can't be set for the replica ― service just ignores those values.

Also, the API documentation example also doesn't include those fields:
```json
{
	"name": "rds-instance-rep2",
	"replica_of_id": "afdsad-fds-fdsagin01",
	"flavor_ref": "rds.mysql.s1.large.rr",
	"volume": {
		"type": "ULTRAHIGH",
		"size": 100
	},
	"disk_encryption_id": "2gfdsh-844a-4023-a776-fc5c5fb71fb4",
	"region": "eu-de",
	"availability_zone": "eu-de-01"
}
```

I will clarify this additionally internally.

**Comment by outcatcher** [comment]
@rbange 
The setting of the security group, VPC, and subnet are not supported for the read replica:
https://docs.otc.t-systems.com/api/rds/rds_01_0002.html (Table 3)

**Comment by rbange** [comment]
Thats unfortunate, but setting a public IP will be helpful too. Thanks!

**Comment by Aloento** [comment]
These features are not currently supported on our platform and we will consider adding them at some point in the future.
