### ISSUE TITLE
Add OBS lifecycle policies

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud/terraform-provider-opentelekomcloud#1114]
Would you please add the OBS lifecycle policies to the terraform provider please?

Sample here: https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-configuration-examples.html#lifecycle-config-conceptual-ex7
This section provides examples of S3 Lifecycle configuration. Each example shows how you can specify the XML in each of the example scenarios.

This might help as well:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/DeletingObjectVersions.html

**Comment by outcatcher** [comment]
@robert1x2 
Using simple lifecycle rules is described at:
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/obs_bucket#using-object-lifecycle

`ExpiredObjectDeleteMarker` doesn't seem to be working. Sent request with the following configuration:
```xml
<LifecycleConfiguration>
    <Rule>
        <Prefix>logs</Prefix>
        <Status>Enabled</Status>
        <Expiration>
            <ExpiredObjectDeleteMarker>true</ExpiredObjectDeleteMarker>
        </Expiration>
        <NoncurrentVersionExpiration>
            <NoncurrentDays>30</NoncurrentDays>
        </NoncurrentVersionExpiration>
    </Rule>
</LifecycleConfiguration>
```
and got err 400 with the body `The XML you provided was not well-formed or did not validate against our published schema`

**Comment by outcatcher** [comment]
Internal update: `ExpiredObjectDeleteMarker` is not implemented yet, but planned to be implemented in the future.

**Comment by outcatcher** [comment]
Internal DM: https://jira.tsi-dev.otc-service.com/browse/DM-2624

**Comment by artem-lifshits** [comment]
Hello @robert1x2 `ExpiredObjectDeleteMarker` is working now, please check.
