### ISSUE TITLE
[AS] information about the group LB limits is invalid  

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/terraform-provider-opentelekomcloud#1115]
There is the following statement in the documentation:
```
lb_listener_id - (Optional) The ELB listener IDs. The system supports up to three ELB listeners, the IDs of which are separated using a comma (,). This parameter is alternative to lbaas_listeners.
```
But it's not limited to three ELB listeners, actually. Four and five are also possible. This to be updated with exact experimentally found value.

Reference: https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/as_group_v1#lb_listener_id

**Comment by lego963** [comment]
This field should be `Deprecated`, because according to the [hc](https://docs.otc.t-systems.com/en-us/api/as/as_06_0101.html) it's working with `classic load balancers` which are out-of-date

**Comment by outcatcher** [comment]
This issue corresponds for both `lb_listener_id` and `lbass_listener_id`
