### ISSUE TITLE
Cannot create resources in other region

### ISSUE THREAD

**Issue by iitsDelbruegger** [opentelekomcloud/terraform-provider-opentelekomcloud#1121]
I have an eu-de tenant with multiple regions and projects in these regions.
![grafik](https://user-images.githubusercontent.com/56017849/121852531-e9ff3a00-ccef-11eb-8eeb-69a6cf2c533a.png)
If I want to create resources in eu-nl or one of the sub-projects via Terraform, I get the error "The  location constraint is incompatible for the region specific endpoint this request was sent to." or other errors for more complex configurations.

# Terraform Version
- Terraform: 0.14.8
- OTC Provider: 1.23.12

# Affected Resource(s)
All resources seem to be affected, but the minimal example below uses a simple OBS bucket.

# Terraform Configuration Files
```hcl
terraform {
  required_version = "v0.14.8"
  required_providers {
    opentelekomcloud = {
      source  = "opentelekomcloud/opentelekomcloud"
      version = "1.23.12"
    }
  }
}
provider "opentelekomcloud" {
  auth_url    = "https://iam.eu-de.otc.t-systems.com/v3"
  domain_name = "OTC-EU-DE-YYYYYYYYYYYYYYYYYYY"
  tenant_name = "eu-nl"
}
resource "opentelekomcloud_obs_bucket" "b" {
  bucket = "my-tf-test-bucket"
  acl    = "private"
}

```

# Debug Output/Panic Output
https://gist.github.com/iitsDelbruegger/6d9f9b5204be88bf1cb5b93109652fc1

# Steps to Reproduce
1. `terraform apply`
2. yes

# Expected Behavior
The OBS Bucket should be created in eu-nl project.

# Actual Behavior
Apply fails with the error above.

# Important Factoids
none

# References
I did not find any other issues linked to having multiple regions.

**Comment by outcatcher** [comment]
It seems, buckets created in `eu-nl` have to have a `region` argument. Empty one considered to be invalid. To be fixed in the provider.
