### ISSUE TITLE
[ECS] Plattform change image_name

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#1141]
# Terraform Version
```
Terraform v1.0.0
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.24.1
```

# Affected Resource(s)
- opentelekomcloud_compute_instance_v2
- opentelekomcloud_images_image_v2

# Terraform Configuration Files
variables.tf
```hcl
variable "ecs_image_name" {
  type    = string
  default = "Standard_Debian_10_latest"
}
```

```hcl
resource "opentelekomcloud_compute_instance_v2" "ecs_instance" {
[...]
  image_name      = var.ecs_image_name
[...]
}
```

# Debug Output/Panic Output
```
~ image_name          = "Standard_Debian_10_20210426_1129" -> "Standard_Debian_10_latest" # forces replacement
```

When trying to find this image:
data.tf
```hcl
data "opentelekomcloud_images_image_v2" "debian" {
  name        = "Standard_Debian_10_20210426_1129"
  most_recent = true
}
```

```hcl
│ Error: your query returned no results. Please change your search criteria and try again
│ 
│   with data.opentelekomcloud_images_image_v2.debian,
│   on ecs.tf line 1, in data "opentelekomcloud_images_image_v2" "debian":
│    1: data "opentelekomcloud_images_image_v2" "debian" {
```

## Workaround
Adding this to the ECS resource:
```hcl
  lifecycle {
    ignore_changes = [
      image_name
    ]
  }
```

# Steps to Reproduce
1. `terraform apply`

# Expected Behavior
The OTC should respond with the image I used to build these ECS `image_name = Standard_Debian_10_latest`

# Actual Behavior
It forces a replacemen since terraform gets the change between the OTC-DB image and my provided one.

# Important Factoids
...must be a recent plattform change... #ImageFactory

**Comment by outcatcher** [comment]
This is caused by reading the image name. When there is a new image release, the platform changes previous image names to `_previous` and then to date-postfixed. I suppose we shouldn't read the image name at all.

**Comment by Moep90** [comment]
> This is caused by reading the image name. When there is a new image release, the platform changes previous image names to `_previous` and then to date-postfixed. I suppose we shouldn't read the image name at all.

yeah but this must be a pretty new "feature" by OTC.
Since we didnt had such an issue for multiple years.

Previously it was enoguh to just ignore the `block_device[0].uuid` not not force a replacement
