### ISSUE TITLE
CES monitoring dashboard and panels

### ISSUE THREAD

**Issue by canaykin** [opentelekomcloud/terraform-provider-opentelekomcloud#1142]
We would like to use Cloud Eye to create dashboards and monitoring panels for our infrastructure on OTC. We are using Terraform to provision and manage the infrastructures and have nearly identical subprojects for different stages of our project. As such we can benefit greatly from automating the CES resource creation via Terraform as well.

Currently the only resource that can be created with OTC Terraform provider is alarm rule `opentelekomcloud_ces_alarmrule` . It would be really useful to have Terraform resources for monitoring panels and graphs within these panels.

**Comment by lego963** [comment]
Internal incident: https://jira.tsi-dev.otc-service.com/browse/XAAS-8620
We don't have any documented API :(

**Comment by artem-lifshits** [comment]
Updated demand: https://jira.tsi-dev.otc-service.com/browse/OTCPR-7201

**Comment by artem-lifshits** [comment]
Please contact customer support with this demand and reopen the ticket if feature becomes available via API.
Thanks.
