### ISSUE TITLE
CSS size can not be increased without replacement

### ISSUE THREAD

**Issue by canaykin** [opentelekomcloud/terraform-provider-opentelekomcloud#1148]
# Terraform Version

v0.14.8

# Provider Version

v1.24.1

# Affected Resource(s)

opentelekomcloud_css_cluster_v1

# Terraform Configuration Files
```hcl
data "opentelekomcloud_css_flavor_v1" "elasticsearch_flavor" {
  min_cpu = var.elasticsearch_config.min_cpu
  min_ram = var.elasticsearch_config.min_ram
}

resource "opentelekomcloud_css_cluster_v1" "elasticsearch_cluster" {
  name            = "${var.prefix}-elasticsearch"
  expect_node_num = var.elasticsearch_config.expected_node_num
  node_config {
    availability_zone = var.availability_zone
    flavor            = data.opentelekomcloud_css_flavor_v1.elasticsearch_flavor.name
    network_info {
      security_group_id = opentelekomcloud_networking_secgroup_v2.elasticsearch_sg.id
      network_id        = var.network_id
      vpc_id            = var.vpc_id
    }
    volume {
      volume_type    = var.elasticsearch_config.storage_type
      size           = var.elasticsearch_config.storage_size
      encryption_key = var.elasticsearch_kms_key
    }
  }
}
```

# Terraform Output

```
+/- resource "opentelekomcloud_css_cluster_v1" "elasticsearch_cluster" {
      ~ created          = "2021-05-04T16:12:53" -> (known after apply)
      ~ enable_authority = false -> (known after apply)
      ~ enable_https     = false -> (known after apply)
      ~ endpoint         = "172.16.9.133:9200" -> (known after apply)
      ~ id               = "36494cf5-fb79-4574-9cf8-aed88009c673" -> (known after apply)
        name             = "nmcloud-dev3-elasticsearch"
      ~ nodes            = [
          - {
              - id   = "7f7096f0-e5ad-4bfa-984b-2baeb42ac265"
              - name = "nmcloud-dev3-elasticsearch-ess-esn-1-1"
              - type = "ess"
            },
        ] -> (known after apply)
      ~ updated          = "2021-05-04T16:12:53" -> (known after apply)
        # (1 unchanged attribute hidden)
      ~ datastore {
          ~ type    = "elasticsearch" -> (known after apply)
          ~ version = "7.6.2" -> (known after apply)
        }
      ~ node_config {
            # (2 unchanged attributes hidden)
          ~ volume {
              ~ size           = 40 -> 400 # forces replacement
                # (2 unchanged attributes hidden)
            }
            # (1 unchanged block hidden)
        }
    }
```

# Steps to Reproduce

1. Increase the node_config.volume.size parameter
2. `terraform apply`
OR
1. Increase the CSS volume manually using OTC console
2. Increase the node_config.volume.size parameter to match the value from 1. step
3. `terraform apply`

# Expected Behavior

The size increase should be applied on the resource without recreation, similar to how the CSS behaves on OTC console. 

# Actual Behavior

Terraform destroys and recreates the resource instead of a live update
Even if the size is manually updated via OTC console, Terraform does not update the change to its state and forces a replacement unless the state is manually manipulated with `terraform state pull/push`.

**Comment by outcatcher** [comment]
API doesn't support changing node volume size. The only operation supported with CSS cluster is changing node count:
https://docs.otc.t-systems.com/api/css/css_03_0008.html

**Comment by canaykin** [comment]
Actually, it does:
https://docs.otc.t-systems.com/api/css/css_03_0038.html
This was initially designed to be used with special nodes but currently accepts `ess` as a valid parameter. Tried it via UI and confirmed the request as following:
```
curl 'https://console.otc.t-systems.com/elasticsearch/rest/usearch/v1.0/797516106b03487285b43d291cf64c8c/clusters/36494cf5-fb79-4574-9cf8-aed88009c673/enlarge' \
  -H 'Connection: keep-alive' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
  -H 'cf2-cftk: ' \
  -H 'cftk: 5N2P-<EDITED>-5CDQ' \
  -H 'X-Language: en-us' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'AgencyId: e70f3a<EDITED>b56' \
  -H 'Content-Type: application/json; charset=UTF-8' \
  -H 'region: eu-de' \
  -H 'Accept: */*' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36' \
  -H 'ProjectName: eu-de_03dev-nmcloud' \
  -H 'DNT: 1' \
  -H 'Origin: https://console.otc.t-systems.com' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://console.otc.t-systems.com/elasticsearch/?agencyId=e70f3a<EDITED>56&region=eu-de_03dev-nmcloud&locale=en-us' \
  -H 'Accept-Language: tr-TR,tr;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6' \
  -H $'Cookie: third-party-access=""; browserCheckResult=A; ttf=1119963052; \u0021Proxy\u0021proxysecurity_preferences=Fe26.2**320b4a<EDITED>_XDfg; SID=Set2; popup_max_time=60; x-framework-ob=TSI; agencyID=e70f3a<EDITED>56; DBS_SID=Set2; DBS_agencyID=e70f3a7331c441b8aa1a9e026b40fb56; locale=en-us; J_SESSION_ID=a205<EDITED>6fae1; cftk=5N2P-3M63-<EDITED>-5CDQ; DBS_J_SESSION_ID=5d<EDITED>80; DBS_cftk=MCFQ-<EDITED>-9GPM; recentServices=["css","sfs","ecm","rds","ces","elb"]; cfLatestRecordTimestamp=1624373587415' \
  --data-raw '{"grow":[{"type":"ess","nodesize":0,"disksize":50}]}' \
  --compressed
```
Basicly, the API allows this payload to scale the volume of existing nodes:
```
{"grow":[{"type":"ess","nodesize":0,"disksize":50}]}
```

**Comment by gtema** [comment]
The only thing I would ask (@outcatcher, @lego963) is to ensure with XaaS guys whether this is really ok and is not a "bug".

1) scale-out doesn't automatically mean change of current cluster
2) "In addition, you can expand the instance storage capacity for a cluster for up to six times." (from docs) is a weird warning that also doesn't automatically play good
3) UI functionality usually can not be used as a reliable reference since it uses different API

**Comment by canaykin** [comment]
I will see if I can replicate the same behaviour via direct API calls tomorrow and give you an update. I also noticed some weird, undocumented limitations such as only certain values for increment are allowed:
 `{"grow":[{"type":"ess","nodesize":0,"disksize":10}]}` for example gets refused with 400 BadRequest

Meanwhile the second issue is that when the resource is modified on both the infrastructure (via console) and in Terraform HCL code, Terraform state refresh does not update the node size and a plan/apply forces the recreation even though a change is not needed. 

In a similar situation (RDS password update for example) Terraform accepts updates and does not require a recreation, whereas a direct modification from Terraform would force a recreation of the RDS instance. As such, I believe one of these behaviours is not intended.

**Comment by outcatcher** [comment]
Provider capabilities are restricted to the functions provided by the API. Refreshing resource instances depends on API read operations and updating existing instance depends on API update operations.

In the case of RDS password ― it is never read, as it's not returned by any operation ― from the API it can only be set during the instance creation. We don't read this value, so the password considered to be changed only if you change it in the terraform configuration.

On the other hand, if something was changed not via terraform and returned from the API read operation (e.g. disk size), terraform will notice the difference, and if it's impossible to change it to the value defined in the configuration (i.e. API doesn't provide appropriate method), the resource recreation will be triggered. To determine which field change requires recreation, schema `ForceNew` attribute is used.

E.g. for `opentelekomcloud_compute_floatingip_associate_v2`
```go
			"floating_ip": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
```

**Comment by canaykin** [comment]
You were right @outcatcher and @gtema . This API is not allowed to be called from outside and calls to:
`/v1.0/{{PROJECT}}/clusters/{{CLUSTER}}/enlarge`
`/v1.0/{{PROJECT}}/clusters/{{CLUSTER}}/role_extend`
returns
```
{
    "message": "API not found",
    "request_id": "39d489d0954ea89f0ef44868b5178acd"
}
```
It seems this is exclusive to UI and only `/v1.0/{{PROJECT}}/clusters/{{CLUSTER}}/extend` can be called which only allows changing the number of nodes.

Also, thank you very much @outcatcher for clarifying the state update behaviour.

**Comment by outcatcher** [comment]
Impossible to implement with current API :slightly_frowning_face: Based on the documentation, it's expected behaviour.

@canaykin If you want, we can create an internal issue for API to support this

**Comment by canaykin** [comment]
It would be a good addition to OTC in the long run but nothing critical for our current project. Thank you very much as usual!

**Comment by outcatcher** [comment]
Internal incident:
https://jira.tsi-dev.otc-service.com/browse/OTCBIGDAI-1383

**Comment by outcatcher** [comment]
Demand created:
https://jira.tsi-dev.otc-service.com/browse/DM-2773

**Comment by Aloento** [comment]
Status:EVALUATION

**Comment by artem-lifshits** [comment]
@canaykin issue is fixed, please check.
