### ISSUE TITLE
[CCE] Add taints to CCE node

### ISSUE THREAD

**Issue by 0xd3e** [opentelekomcloud/terraform-provider-opentelekomcloud#1151]
# Description of the enhancement

I've seen that it is possible to add taints to a CCE node pool, but not to a CCE node.
The API seems to support it.

I'd be happy to write a PR if you're interested.

**Comment by outcatcher** [comment]
@0xIDANT we are always happy then people contribute to the provider 🙂 Please write a PR

**Comment by 0xd3e** [comment]
@outcatcher I've realized that I could possibly implement providing taints for node creation, but the API doesn't allow updating the node specs. Only updating the node name is supported by the OTC API. So updating node taints won't work with the current API.

This is a bit weird because the node pool supports updating the taints.

Should I go forward and implement it for node creation only?

**Comment by outcatcher** [comment]
Let's start with creation-only :) marked with `ForceNew`

**Comment by outcatcher** [comment]
Internal incident for no taints in the response:
https://jira.tsi-dev.otc-service.com/browse/OCS-1477

**Comment by lego963** [comment]
Fixed in: #1191
