### ISSUE TITLE
CCE: addon-templates.md is outdated

### ISSUE THREAD

**Issue by sonic-martin** [opentelekomcloud/terraform-provider-opentelekomcloud#1154]
The CCE's [addon-templates.md](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/devel/opentelekomcloud/services/cce/addon-templates.md) is outdated. It describeds the templates for k8s version v1.17.9, but CCE in the meanwhile also allows to use k8s version v.1.19.8. There shall be two  addon-templates.md for each version with sufficient info. If no changes happend, then remark it. But probably EulerOS Version (2.5 vs 2.2.5) and template_version(?) may not be recent.

**Comment by lego963** [comment]
Internal incident: https://jira.tsi-dev.otc-service.com/browse/OCS-4045

**Comment by outcatcher** [comment]
Done in #1172
