### ISSUE TITLE
DCS please enable TLS in provider

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud/terraform-provider-opentelekomcloud#1155]
A technical question about the terraform support for redis. It seems the TLS feature is missing. It is available in the console (part of the "public access"), but it doesn't seem to be configurable via terraform.

**Comment by Aloento** [comment]
@artem-lifshits do you know something about this?

**Comment by artem-lifshits** [comment]
Hello @robert1x2 I checked DCS Redis and wasn't able to find ``TLS`` setting in ``public access``.
It's either removed or I'm looking in the wrong place, please help me there.

**Comment by robert1x2** [comment]
Please close my request.
