### ISSUE TITLE
Missing resource for vpc peering and virtual IP address

### ISSUE THREAD

**Issue by misko566** [opentelekomcloud/terraform-provider-opentelekomcloud#116]
Hi All,

I can't find resource for creating VPC peering and virtual IP address in VPC subnet.

Is there any integration ? 
They have it in API
https://docs.otc.t-systems.com/en-us/api/vpc/en-us_topic_0075677482.html

Thanks

**Comment by niuzhenguo** [comment]
@misko566 We already merged vpc peering resource to master code but not released yet, see https://github.com/terraform-providers/terraform-provider-opentelekomcloud/blob/master/CHANGELOG.md for 1.2.0 release which will be cut soon. Also you can still try to build the provider yourself by following our README and try if it satisfies your request, thanks!
