### ISSUE TITLE
opentelekomcloud_s3_bucket vs opentelekomcloud_obs_bucket

### ISSUE THREAD

**Issue by canaykin** [opentelekomcloud/terraform-provider-opentelekomcloud#1166]
# Description of the enhancement
We recently moved our resources from `opentelekomcloud_s3_bucket` to `opentelekomcloud_obs_bucket` to be able to use the new features such as bucket level encryption. Recently I noticed there are features in `opentelekomcloud_s3_bucket` that we also require such as `expired_object_delete_marker` and `abort_incomplete_multipart_upload_days` but the bucket level KMS encryption feature was missing.

Could you please clarify which of these terraform resources should be used going forward and could you please merge the features of both resources into a single one?

**Comment by lego963** [comment]
@canaykin We have disscussion about this resource https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/discussions/776

**Comment by outcatcher** [comment]
Generally, `obs` is a new one and `s3` is to be removed in future releases. We haven't prioritized that before, but I suppose we should implement all missing features from s3 to obs in the nearest releases.

**Comment by outcatcher** [comment]
@canaykin Do you need anything besides `expired_object_delete_marker` and `abort_incomplete_multipart_upload_days` to be implemented in nearest future?

**Comment by canaykin** [comment]
@outcatcher thank you for super fast reply, I believe those two resources should be sufficient for the near future. 

The `mfa_delete` is the only other feature that caught my eye but I do not know  the exact purpose of that flag to be honest.

**Comment by outcatcher** [comment]
Functionality is still not implemented in OBS service

Delete marker DM:
https://jira.tsi-dev.otc-service.com/browse/DM-2624

`abort_incomplete_multipart_upload_days` is not implemented (DM  to be created)


`mfa_delete` is missing too. But as you don't need it - we won't create DM :)

**Comment by outcatcher** [comment]
`AbortIncompleteMultipartUpload` support to be implemented in OBS:
https://jira.tsi-dev.otc-service.com/browse/DM-2677

**Comment by Aloento** [comment]
Status:EVALUATION

**Comment by artem-lifshits** [comment]
Hello @canaykin `abort_incomplete_multipart_upload_days` should be working now, please check.
