### ISSUE TITLE
identity mapping does not work

### ISSUE THREAD

**Issue by victorgetz** [opentelekomcloud/terraform-provider-opentelekomcloud#1169]
If i apply the opentelekomcloud_identity_mapping_v3 resource it does nothing

# Terraform Version
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.24.2

# Affect
- opentelekomcloud_identity_mapping_v3
- opentelekomcloud_identity_provider_v3

# Terraform Configuration Files
```hcl
// Everything for the OTC Provider
resource "opentelekomcloud_identity_provider_v3" "keycloak" {
  name = "otc"
  description = "Keycloak SSO"
  enabled = true
}

resource "opentelekomcloud_identity_mapping_v3" "keycloak_role_mapping" {
  mapping_id = opentelekomcloud_identity_provider_v3.keycloak.id
  rules = <<EOF
  [
    {
      "local":[
        {
          "user":{"name":"{0}"}
        },
        {
          "groups":"[\"admin\",\"manager\"]"
        }
      ],
      "remote":[
        {
          "type":"uid"
        }
      ]
    }
  ]
EOF
}
```

# Steps to Reproduce
1. `terraform apply`
2. Default Rules are still active

# Expected Behavior
Rules should be applied

# Actual Behavior
Default Rules are still there

# References
- https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/947

**Comment by outcatcher** [comment]
API for identity provider/mapping generally looks very strange. Basically, there is no documentation about how API identity mappings correlate with console identity mappings.
There is a question about a related topic: https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/discussions/1053.
The internal incident is still in an unclear state. I will push it once again.

Internal incident:
https://jira.tsi-dev.otc-service.com/browse/OTCSEC-1905

**Comment by outcatcher** [comment]
Mapping can be attached to a provider using protocol:
https://docs.otc.t-systems.com/en-us/api/iam/en-us_topic_0057845609.html

This will require SDK changes and a new resource

**Comment by outcatcher** [comment]
Example of binding mapping and provider in `v1.24.4+`:

```hcl
resource "opentelekomcloud_identity_provider_v3" "provider" {
  name        = "ACME"
  description = "This is simple identity provider"
  enabled     = true
}

resource "opentelekomcloud_identity_mapping_v3" "mapping" {
  mapping_id = "ACME"
  rules      = file("./rules.json")
}

resource "opentelekomcloud_identity_protocol_v3" "saml" {
  protocol    = "saml"
  provider_id = opentelekomcloud_identity_provider_v3.provider.id
  mapping_id  = opentelekomcloud_identity_mapping_v3.mapping.id
}
```
