### ISSUE TITLE
WAF precise protection rule invalid logic for ip category

### ISSUE THREAD

**Issue by pschmidbauer** [opentelekomcloud/terraform-provider-opentelekomcloud#1186]
# Terraform Version
1.0.0

# Affected Resource(s)
opentelekomcloud_waf_preciseprotection_rule_v1

# Debug Output/Panic Output
Terraform debug output https://gist.github.com/pschmidbauer/f9494164f23c61ab771e5924afd57388

# Steps to Reproduce
1. Add resource and try to set logic to "not_equal" for IP
`resource "opentelekomcloud_waf_preciseprotection_rule_v1" "only_allow_office_ip" {
  policy_id = opentelekomcloud_waf_policy_v1.policy_1.id
  name      = "only-office-ip"
  conditions {
    category = "ip"
    contents = ["XXX.XX.XXX.XX"]
    logic    = 4
  }

  action_category = "block"
  priority        = 4
}`
2. terraform apply

# Expected Behavior
A precise protection rule is created and all IP addresses are blocked except for the provided IP which can be an office IP for example. As the documentation says you can use 3 or 4 value for category ip

# Actual Behavior
It says the logic is invalid as you can see in the above provided GitHub gist

# Important Factoids
OTC provider version: 1.24.2

# References
None

**Comment by outcatcher** [comment]
Fixed in #1193
