### ISSUE TITLE
opentelekomcloud_lb_loadbalancer_v2 - Create public ELB

### ISSUE THREAD

**Issue by OC-Takeru** [opentelekomcloud/terraform-provider-opentelekomcloud#1202]
### Terraform Version
```
Terraform v0.15.1
on darwin_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.24.3
```

### Affected Resource(s)
opentelekomcloud_lb_loadbalancer_v2

### Terraform Configuration Files
A possible solution could be:

```
resource "opentelekomcloud_lb_loadbalancer_v2" "lb_1" {
  name           = var.elbName
  description    = var.elbDescription
  public_ip_address = var.eip
  vip_subnet_id = var.subnetId
}
```

### Expected Behavior
Creation of Load Balancer as Public LoadBalancer with private IP-Address (DHCP) in vip_subnet and EIP for public access which I created beforehand. 

### Actual Behavior
There is no parameter so far. In OTC Console it is possible to create such an LoadBalancer and in API Docs it is mentioned which parameters are needed.

This is the Error I got before I knew that vip_address is a private ip address from vpc-subnet:
`POST https://vpc.eu-de.otc.t-systems.com/v2.0/lbaas/loadbalancers], error message: {"NeutronError": {"detail": "", "type": "BadRequest", "message": "IP address 80.***.***.224 is not a valid IP for the specified subnet.`

**Comment by outcatcher** [comment]
Please check if IP address exists and is in the same project with the subnet. You can also use `opentelekomcloud_vpc_eip_v1` data source to check that.

**Comment by OC-Takeru** [comment]
Hi @outcatcher I am able to create the LoadBalancer with the same EIP when using OTC Console

**Comment by outcatcher** [comment]
Sorry, I've got the issue wrong. I thought, currently existing solution won't work. 
API don't provide method for assigning floating IP during LB creation. It can be done the following way:
```hcl
resource "opentelekomcloud_networking_floatingip_associate_v2" "associate" {
  floating_ip = var.eip
  port_id     = opentelekomcloud_lb_loadbalancer_v2.lb_1.vip_port_id
}
```

I suppose it should be added to the `opentelekomcloud_lb_loadbalancer_v2` documentation
