### ISSUE TITLE
OBS bucket creation - set default encryption 

### ISSUE THREAD

**Issue by aengelhorn** [opentelekomcloud/terraform-provider-opentelekomcloud#1205]
## Description of the enhancement
It would be cool to be able to configure and change the default encryption setting (encrypt by default on/off and select key) for an OBS bucket as it is possible via CLI.

**Comment by outcatcher** [comment]
KMS encryption for the bucket is already implemented, though a known issue exists (not resolvable for now):
https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1160

**Comment by outcatcher** [comment]
Example in the documentation:
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/obs_bucket#using-server-side-encryption-for-the-bucket

**Comment by outcatcher** [comment]
Please comment if you have any more questions :slightly_smiling_face:
