### ISSUE TITLE
CCE: Node creation: Subnet

### ISSUE THREAD

**Issue by sonic-martin** [opentelekomcloud/terraform-provider-opentelekomcloud#1208]
The CCE API allows to create Nodes with IPs in another Subnet as the Control Plane.
Via Terraform it doesnt seems to be able right now.

**Comment by outcatcher** [comment]
Do you refer to `primaryNic.subnetId` setting or `extNics` implementation?
Reference: https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0242.html#cce_02_0242__request_NicSpec

**Comment by sonic-martin** [comment]
I am unsure, but I think primaryNic.subnetId.
Big Picture: I have one VPC with handful subnets. Main nodes/control plane shall be in one subnet. The worker nodes shall be in another subnet.

**Comment by sonic-martin** [comment]
works, thanks!
