### ISSUE TITLE
DCS instance parameters

### ISSUE THREAD

**Issue by canaykin** [opentelekomcloud/terraform-provider-opentelekomcloud#1211]
# Description of the enhancement
We are using Terraform to manage multiple DCS instances per project. One of the problematic default settings we noticed is `maxmemory-policy = noeviction` and we switch this parameter to `maxmemory-policy = allkeys-lru` for our use scenario.

Unfortunately, this operation can not be performed with the current provider version. It would be really nice if DCS parameters can be adjusted via Terraform similarly to the RDS instances.

**Comment by outcatcher** [comment]
I suppose the following API is used for DCS instance configuration:
https://docs.otc.t-systems.com/api/dcs/dcs-api-0312017.html

**Comment by canaykin** [comment]
Yep, it seems like the UI is also using the same API in this case:
```
curl 'https://console.otc.t-systems.com/dcs/rest/dcs/v1.0/53a4f4caa7d444429d9b3e93e49bb828/instances/8e230257-24e7-4bfa-a80c-9a8549241428/configs' \
  -X 'PUT' \
  -H 'Connection: keep-alive' \
  -H 'region: eu-de' \
  -H 'Accept: */*' \
  -H 'ProjectName: eu-de_01pre-nmcloud' \
  -H 'Origin: https://console.otc.t-systems.com' \
  -H 'Referer: https://console.otc.t-systems.com/dcs/?agencyId=e70f3a7331c441b8aa1a9e026b40fb56&locale=en-us&region=eu-de_01pre-nmcloud' \
  --data-raw '{"instance_id":"8e230257-24e7-4bfa-a80c-9a8549241428","redis_config":[{"param_id":"2","param_name":"maxmemory-policy","param_value":"allkeys-lru"}]}' 
 ```
 
 The `param_id` seems to be not easily guessable though. It is definitely not alphabetic.

**Comment by outcatcher** [comment]
I suppose we can use parameters by just name, there is a method for listing them:
https://docs.otc.t-systems.com/api/dcs/dcs-api-0312015.html#dcs-api-0312015__table1439111281351
