### ISSUE TITLE
Tolerations & affinities in CCE add-on templates

### ISSUE THREAD

**Issue by DasLeo** [opentelekomcloud/terraform-provider-opentelekomcloud#1224]
Since we are able to set `k8s_tags` and `taints` in CCE nodepools it would be great to have the possibility to set affinities and tolerations as well on the add-on part.
Otherwise it's impossible to schedule the add-on pods properly.

**Comment by DasLeo** [comment]
Hey @lego963 would it help if I add the ticket to https://github.com/opentelekomcloud/gophertelekomcloud instead?

**Comment by lego963** [comment]
@DasLeo you can create there also, yes. Don't close this one :)

**Comment by nahian166** [comment]
Hi, 
The solution is the following:
You can use kubectl to edit the addons deployments (metricserver) in kube-system namespace and add the pod affinity to scheduler the addons pod wherever you want. 

Not all our addons are deployed as deployments, some of them deploy as daemonsets (coredns, gpu-beta) that can't have affinity or tolerations. That is why addons modification feature is not given in the GUI. 

And in the nodepool, it is just a template to create the nodes, nodes can have tags or taint. It has no direct relation with the addons plugin.
You can still have taint on the nodes, to block the addons deployment on that nodes.

**Comment by lego963** [comment]
Current OTC approach won't allow this setting.
