### ISSUE TITLE
Autoscaler add-on does not work

### ISSUE THREAD

**Issue by rfleschenberg** [opentelekomcloud/terraform-provider-opentelekomcloud#1227]
When I use the `opentelekomcloud_cce_addon_v3` resource to install the autoscaler add-on, the add-on gets created, but the pod reports an error afterwards:

```
E0720 13:31:52.406761       1 hws_manager.go:197] Failed to fresh node group cache: Unexpected Response error, StatusCode: 401, Error Message: {"message":"Authorization information is wrong","request_id":"d06c3234864f09faf5cc328e176d7321"}
F0720 13:31:52.406782       1 hws_cloud_provider.go:154] Failed to create HWS Manager: Unexpected Response error, StatusCode: 401, Error Message: {"message":"Authorization information is wrong","request_id":"d06c3234864f09faf5cc328e176d7321"}
```

 If I install the add-on manually via the OTC console, it works fine. I ran `diff` against the kubernetes YAML for both cases. The YAML looks identical except for expected differences like timestamps and the pod status.

If I inspect the secrets (`cluster-autoscaler-token-*`), they look different in the raw values. But if I run `base64 -d` on them, they seem to decode to the same value. However, in both cases, `base64 -d` reports `"base64: invalid input"`. But it still shows me the decoded data (`{"alg":"RS256","kid":"XXX"})`. Could this be related to the problem, maybe?

# Terraform Version

```
Terraform v1.0.2
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.24.5
```

# Affected Resource(s)

```
opentelekomcloud_cce_addon_v3
```

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_cce_addon_v3" "autoscaler-addon" {
  template_name    = "autoscaler"
  template_version = "1.19.1"
  cluster_id       = opentelekomcloud_cce_cluster_v3.mycluster.id
  values {
    basic = {
      "cceEndpoint": "https://cce.eu-de.otc.t-systems.com",
      "ecsEndpoint": "https://ecs.eu-de.otc.t-systems.com",
      "image_version": "1.19.1",
      "platform": "linux-amd64",
      "region": "eu-de",
      "swr_addr": "100.125.7.25:20202",
      "swr_user": "hwofficial"
    }
    custom = {
      "cluster_id": opentelekomcloud_cce_cluster_v3.mycluster.id,
      "coresTotal": 32000,
      "expander": "priority",
      "logLevel": 4,
      "maxEmptyBulkDeleteFlag": 10,
      "maxNodeProvisionTime": 15,
      "maxNodesTotal": 1000,
      "memoryTotal": 128000,
      "scaleDownDelayAfterAdd": 10,
      "scaleDownDelayAfterDelete": 10,
      "scaleDownDelayAfterFailure": 3,
      "scaleDownEnabled": false,
      "scaleDownUnneededTime": 10,
      "scaleDownUtilizationThreshold": 0.5,
      "scaleUpCpuUtilizationThreshold": 1,
      "scaleUpMemUtilizationThreshold": 1,
      "scaleUpUnscheduledPodEnabled": true,
      "scaleUpUtilizationEnabled": true,
      "tenant_id": "eu-de_myproject",
      "unremovableNodeRecheckTimeout": 5,
      "skipNodesWithLocalStorage": false,
    }
  }
}
```

# Debug Output/Panic Output

Logs from the autoscaler pod (`kubectl logs cluster-autoscaler-55c846b67-2d469 -n kube-system | head -n 200`):
https://gist.github.com/rfleschenberg/e0a6a3ab2cfc2c2ab7719e23d2d2a4a0

# Steps to Reproduce
Define an add-on resource as described above and run `terraform apply`, then check the pod status.

# Expected Behavior
The autoscaler should work, as it does when I install it manually via the OTC console.

# Actual Behavior
See above.

**Comment by lego963** [comment]
@rfleschenberg sorry for delay.
I suppose that addon was created before CCE nodes were deployed.

Can you add this block in resource config?
```hcl
resource "opentelekomcloud_cce_addon_v3" "autoscaler-addon" {
...
  depends_on = [
    opentelekomcloud_cce_node_v3.node_1
  ]
}
```

**Comment by lego963** [comment]
my .tf config
```hcl
resource "opentelekomcloud_cce_cluster_v3" "cluster_1" {
  name                    = "cce-cluster-test-addon"
  cluster_type            = "VirtualMachine"
  flavor_id               = "cce.s1.medium"
  vpc_id                  = var.vpc_id
  subnet_id               = var.network_id
  container_network_type  = "overlay_l2"
  kubernetes_svc_ip_range = "10.247.0.0/16"
}

resource "opentelekomcloud_cce_node_v3" "node_1" {
  cluster_id        = opentelekomcloud_cce_cluster_v3.cluster_1.id
  flavor_id         = "s2.xlarge.2"
  availability_zone = var.az
  key_pair          = var.keypair
  root_volume {
    size       = 40
    volumetype = "SATA"
  }
  data_volumes {
    size       = 100
    volumetype = "SATA"
  }
}

resource "opentelekomcloud_cce_addon_v3" "autoscaler-addon" {
  template_name    = "autoscaler"
  template_version = "1.19.1"
  cluster_id       = opentelekomcloud_cce_cluster_v3.cluster_1.id
  values {
    basic = {
      "cceEndpoint" : "https://cce.eu-de.otc.t-systems.com",
      "ecsEndpoint" : "https://ecs.eu-de.otc.t-systems.com",
      "image_version" : "1.19.1",
      "platform" : "linux-amd64",
      "region" : "eu-de",
      "swr_addr" : "100.125.7.25:20202",
      "swr_user" : "hwofficial"
    }
    custom = {
      "cluster_id" : "${opentelekomcloud_cce_cluster_v3.cluster_1.id}",
      "coresTotal" : 32000,
      "expander" : "priority",
      "logLevel" : 4,
      "maxEmptyBulkDeleteFlag" : 10,
      "maxNodeProvisionTime" : 15,
      "maxNodesTotal" : 1000,
      "memoryTotal" : 128000,
      "scaleDownDelayAfterAdd" : 10,
      "scaleDownDelayAfterDelete" : 10,
      "scaleDownDelayAfterFailure" : 3,
      "scaleDownEnabled" : false,
      "scaleDownUnneededTime" : 10,
      "scaleDownUtilizationThreshold" : 0.5,
      "scaleUpCpuUtilizationThreshold" : 1,
      "scaleUpMemUtilizationThreshold" : 1,
      "scaleUpUnscheduledPodEnabled" : true,
      "scaleUpUtilizationEnabled" : true,
      "tenant_id" : "${var.tenant_id}",
      "unremovableNodeRecheckTimeout" : 5,
      "skipNodesWithLocalStorage" : false,
    }
  }

  depends_on = [
    opentelekomcloud_cce_node_v3.node_1
  ]
}

```

**Comment by lego963** [comment]
If you have questions, then write here :)

**Comment by rfleschenberg** [comment]
@lego963 I added a `depends_on` on my node pool, that seems to fix it. Thanks!

**Comment by rfleschenberg** [comment]
> @lego963 I added a `depends_on` on my node pool, that seems to fix it. Thanks!

Ah sorry, actually, it did not. The error is still there, even though it says "Node(s) created successfully" under "Add-on Instance Details" -> "Events".

Maybe I have to actually add a dependency to a node? I'm not sure how to get the reference to the node though. I'll try to figure that out.

**Comment by rfleschenberg** [comment]
@lego963 I used exactly your config with only the following changes:

* Replaced `opentelekomcloud_cce_cluster_v3.cluster_1.id` and `"${opentelekomcloud_cce_cluster_v3.cluster_1.id}"` with `module.cce_cluster.cluster_id` (my cluster is defined in a separate module)
* Replaced `opentelekomcloud_cce_node_v3.node_1` in `depends_on` with my node pool (`opentelekomcloud_cce_node_pool_v3.node_pool_1`)

I also recreated the add-on a couple of times, so the nodes are definitely deployed before the add-on gets created.

`"${opentelekomcloud_cce_cluster_v3.cluster_1.id}"` is invalid syntax in my terraform version, so I guess you tested with an older one?

**Comment by lego963** [comment]
@rfleschenberg we are investigating this

**Comment by lego963** [comment]
@rfleschenberg I tried a multiple runs. So, when you create a cluster with the autoscaler addon it will be in `down` (yellow) state, because it waits for a node. When your cluster will have a node this autoscaler pod will be in `running` (green) state. Can you check it? You don't need this `depends_on`. Just create cluster+addon and add a node.

PS: for a node scaling with this pod you need to create an autoscaling policy, but now we don't have API to implement this resource in terraform (https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1316)

**Comment by mokhos** [comment]
Hi. I have the same problem with my configuration. 
First I create a node_pool resource and then the autoscaler addon. 
The status of autoscaler is still abnormal. The events section says that the container has been 26 times restarted.

**Comment by lego963** [comment]
@mokhos do you have a node? It requires a node.

**Comment by mokhos** [comment]
> @mokhos do you have a node? It requires a node.

Well, I have a nodepool with 2 nodes in it. That's not enough?!

Update: The thing is that with this configuration, installing the addon manually has no problem. When I install it by terraform, the error happens! So I guess having a nodepool instead of one node shouldn't be the issue.

**Comment by outcatcher** [comment]
You can't trust common sense in that case. Console sometimes works drastically different from the API, even if it looks the same. We will investigate the case further.

**Comment by lego963** [comment]
@mokhos can you compare my config with yours? It creates cluster + addon +nodepool (with 2 nodes)
```hcl
data "opentelekomcloud_vpc_subnet_v1" "this" {
  name = var.subnet_name
}

resource "opentelekomcloud_cce_cluster_v3" "this" {
  name = "tf-cluster"

  cluster_type           = "VirtualMachine"
  flavor_id              = "cce.s1.medium"
  vpc_id                 = data.opentelekomcloud_vpc_subnet_v1.this.vpc_id
  subnet_id              = data.opentelekomcloud_vpc_subnet_v1.this.network_id
  container_network_type = "overlay_l2"
  authentication_mode    = "rbac"
}

resource "opentelekomcloud_cce_node_pool_v3" "this" {
  cluster_id         = opentelekomcloud_cce_cluster_v3.this.id
  name               = "tf-nodepool"
  os                 = "EulerOS 2.5"
  flavor             = "s2.xlarge.2"
  initial_node_count = 2
  availability_zone  = "random"
  key_pair           = var.kp

  min_node_count           = 2
  max_node_count           = 9
  scale_down_cooldown_time = 100
  priority                 = 1

  root_volume {
    size       = 40
    volumetype = "SSD"
  }
  data_volumes {
    size       = 100
    volumetype = "SSD"
  }
}

resource "opentelekomcloud_cce_addon_v3" "this" {
  template_name    = "autoscaler"
  template_version = "1.19.1"
  cluster_id       = opentelekomcloud_cce_cluster_v3.this.id
  values {
    basic = {
      "cceEndpoint" : "https://cce.eu-de.otc.t-systems.com",
      "ecsEndpoint" : "https://ecs.eu-de.otc.t-systems.com",
      "image_version" : "1.19.1",
      "platform" : "linux-amd64",
      "region" : "eu-de",
      "swr_addr" : "100.125.7.25:20202",
      "swr_user" : "hwofficial"
    }
    custom = {
      "cluster_id" : "${opentelekomcloud_cce_cluster_v3.this.id}",
      "coresTotal" : 32000,
      "expander" : "priority",
      "logLevel" : 4,
      "maxEmptyBulkDeleteFlag" : 10,
      "maxNodeProvisionTime" : 15,
      "maxNodesTotal" : 1000,
      "memoryTotal" : 128000,
      "scaleDownDelayAfterAdd" : 10,
      "scaleDownDelayAfterDelete" : 10,
      "scaleDownDelayAfterFailure" : 3,
      "scaleDownEnabled" : false,
      "scaleDownUnneededTime" : 10,
      "scaleDownUtilizationThreshold" : 0.5,
      "scaleUpCpuUtilizationThreshold" : 1,
      "scaleUpMemUtilizationThreshold" : 1,
      "scaleUpUnscheduledPodEnabled" : true,
      "scaleUpUtilizationEnabled" : true,
      "tenant_id" : "${var.tenant_id}",
      "unremovableNodeRecheckTimeout" : 5,
      "skipNodesWithLocalStorage" : false,
    }
  }
}
```

Addon works
![image](https://user-images.githubusercontent.com/17201690/151153437-0a2b4cec-7399-4f6f-9e23-9fb9f0e707c3.png)

**Comment by mokhos** [comment]
@lego963 
It's weird. I checked my config with yours and couldn't find anything. This is my config:


```

resource "opentelekomcloud_identity_agency_v3" "enable_cce_auto_creation" {
  name                  = "cce_admin_test"
  description           = "Created by Terraform to auto create cce"
  delegated_domain_name = "op_svc_cce"
  dynamic "project_role" {
    for_each = var.projects
    content {
      project = project_role.value
      roles = [
        "Tenant Administrator"
      ]
    }
  }
}

# Kubenetes Cluster
resource "opentelekomcloud_cce_cluster_v3" "cluster_1" {
  name        = "test-cluster"
  description = "Create cluster"

  cluster_type           = "VirtualMachine"
  flavor_id              = var.flavor_id
  vpc_id                 = module.vpc.vpc_id #var.vpc_id
  subnet_id              = module.vpc.network_id #var.subnet_id
  container_network_type = "overlay_l2"
  authentication_mode    = "rbac"
  multi_az = "true"

  depends_on = [opentelekomcloud_identity_agency_v3.enable_cce_auto_creation]
}

# Node Pool
resource "opentelekomcloud_cce_node_pool_v3" "node_pool_1" {
  cluster_id         = opentelekomcloud_cce_cluster_v3.cluster_1.id
  name               = "opentelekomcloud-cce-node-pool-test"
  os                 = "EulerOS 2.5"
  flavor             = "s2.xlarge.2" # 4cores | 8GB 
  initial_node_count = 2
  availability_zone  = var.availability_zone
  key_pair           = var.ssh_key

  #scale_enable             = true
  min_node_count           = 2
  max_node_count           = 9
  scale_down_cooldown_time = 100
  priority                 = 1

  root_volume {
    size       = 40
    volumetype = "SSD"
  }
  data_volumes {
    size       = 100
    volumetype = "SSD"
  }
}

resource "opentelekomcloud_cce_addon_v3" "auto-scaler" {
  template_name    = "autoscaler"
  template_version = "1.19.1"
  cluster_id       = opentelekomcloud_cce_cluster_v3.cluster_1.id

  values {
    basic = {
      "cceEndpoint": "https://cce.eu-de.otc.t-systems.com",
      "ecsEndpoint": "https://ecs.eu-de.otc.t-systems.com",
      "image_version": "1.19.1",
      "platform": "linux-amd64",
      "region": "eu-de",
      "swr_addr": "100.125.7.25:20202",
      "swr_user": "hwofficial"
}
    custom = {
      "cluster_id": "${opentelekomcloud_cce_cluster_v3.cluster_1.id}",
      "coresTotal": 32000,
      "expander": "priority",
      "logLevel": 4,
      "maxEmptyBulkDeleteFlag": 10,
      "maxNodeProvisionTime": 15,
      "maxNodesTotal": 1000,
      "memoryTotal": 128000,
      "scaleDownDelayAfterAdd": 10,
      "scaleDownDelayAfterDelete": 10,
      "scaleDownDelayAfterFailure": 3,
      "scaleDownEnabled": false,
      "scaleDownUnneededTime": 10,
      "scaleDownUtilizationThreshold": 0.5,
      "scaleUpCpuUtilizationThreshold": 1,
      "scaleUpMemUtilizationThreshold": 1,
      "scaleUpUnscheduledPodEnabled": true,
      "scaleUpUtilizationEnabled": true,
      "tenant_id": "${var.tenant_id}",
      "unremovableNodeRecheckTimeout": 5,
      "skipNodesWithLocalStorage" : false
}
  }
}
```

**Comment by lego963** [comment]
@mokhos can you send autoscaler addon events?
![image](https://user-images.githubusercontent.com/17201690/151329990-d1c64c76-6d7f-411f-838f-90c9b39f0211.png)

**Comment by mokhos** [comment]
@lego963 
Here are the events:
<img width="1059" alt="Bildschirmfoto 2022-01-27 um 10 44 00" src="https://user-images.githubusercontent.com/60837530/151334867-9b303c4f-a563-48e9-9186-3f2cb5012dd8.png">


<img width="1052" alt="Bildschirmfoto 2022-01-27 um 10 44 28" src="https://user-images.githubusercontent.com/60837530/151334910-e8e7a8fc-3a5f-40e8-b3e7-e591ac039a66.png">

**Comment by lego963** [comment]
@mokhos compute squad were updating CCE `controllers` and `addonmgr` yesterday. Can you please recreate your infra?
Also, they have said that there is updated version of the `autoscaler` addon. Try to update it please

```hcl
resource "opentelekomcloud_cce_addon_v3" "this" {
  template_name    = "autoscaler"
  template_version = "1.19.7"
...
  values {
    basic = {
...
      "image_version" : "1.19.7",
```

**Comment by mokhos** [comment]
@lego963 
That's unfortunately still the same.

Update: Does that anything to do with the AZ on my nodepool being set to "random" ?
I had the same problem with other resource!

**Comment by chrkaatz** [comment]
I have a similar issue, If I add the add-on from the UI, there is no Problem but from terraform it goes into the abnormal state with the following error:

> E0720 13:31:52.406761       1 hws_manager.go:197] Failed to fresh node group cache: Unexpected Response error, StatusCode: 401, Error Message: {"message":"Authorization information is wrong","request_id":"d06c3234864f09faf5cc328e176d7321"}
> F0720 13:31:52.406782       1 hws_cloud_provider.go:154] Failed to create HWS Manager: Unexpected Response error, StatusCode: 401, Error Message: {"message":"Authorization information is wrong","request_id":"d06c3234864f09faf5cc328e176d7321"}

**Comment by nfelger** [comment]
@chrkaatz I had this problem too. Turns out that you need to set the `tenant_id` to the project id of the region you're deploying into. This worked for me:

```hcl
data "opentelekomcloud_identity_project_v3" "eu_de" {
  name = "eu-de"
}

resource "opentelekomcloud_cce_cluster_v3" "this" {
  ...
}

resource "opentelekomcloud_cce_addon_v3" "autoscaler" {
  template_name    = "autoscaler"
  template_version = "1.19.7"
  cluster_id       = opentelekomcloud_cce_cluster_v3.this.id

  values {
    basic = {
      ...
    }

    custom = {
      "cluster_id" : opentelekomcloud_cce_cluster_v3.this.id,
      "tenant_id" : data.opentelekomcloud_identity_project_v3.eu_de.id,
      ...
    }
  }
}
```

@lego963 @outcatcher I only learned this by trial & error. Might be a good idea to document these options [in the addon documentation](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/devel/opentelekomcloud/services/cce/addon-templates-v1.19.8.md) to save others the same headache?

**Comment by nfelger** [comment]
For any others coming to this issue: at some point auto scaling also failed because we ran into Quota limits. Another thing worth cecking…

**Comment by Aloento** [comment]
Any news? @lego963

**Comment by generalpax** [comment]
plus one

**Comment by lego963** [comment]
> Any news? @lego963

@Aloento I don't know about any progress here and cannot proceed. Maybe @anton-sidelnikov @artem-lifshits @vladimirvshivkov can help you here.

**Comment by marco4320** [comment]
Just solved the issue for SwissOTC by applying all the suggestions from above. Please improve documentation on the swr_addr property. It turned out that "swr_addr" : "100.125.7.25:20202" will never work for SwissOTC...

**Comment by Tobeje** [comment]
You are missing the Tenant_id... It also took me a few month until i found it :/
`resource "opentelekomcloud_cce_addon_v3" "auto-scaler" {
  template_name    = "autoscaler"
  template_version = "1.19.1"
  cluster_id       = opentelekomcloud_cce_cluster_v3.cluster_1.id

  values {
    basic = {
      "cceEndpoint": "https://cce.eu-de.otc.t-systems.com",
      "ecsEndpoint": "https://ecs.eu-de.otc.t-systems.com",
      "image_version": "1.19.1",
      "platform": "linux-amd64",
      "region": "eu-de",
      "swr_addr": "100.125.7.25:20202",
      "swr_user": "hwofficial"
}
    custom = {
      "cluster_id": "${opentelekomcloud_cce_cluster_v3.cluster_1.id}",
      "tenant_id": "ProjectID, found in IAM -> Projects -> Project view",
      "coresTotal": 32000,
      "expander": "priority",
      "logLevel": 4,
      "maxEmptyBulkDeleteFlag": 10,
      "maxNodeProvisionTime": 15,
      "maxNodesTotal": 1000,
      "memoryTotal": 128000,
      "scaleDownDelayAfterAdd": 10,
      "scaleDownDelayAfterDelete": 10,
      "scaleDownDelayAfterFailure": 3,
      "scaleDownEnabled": false,
      "scaleDownUnneededTime": 10,
      "scaleDownUtilizationThreshold": 0.5,
      "scaleUpCpuUtilizationThreshold": 1,
      "scaleUpMemUtilizationThreshold": 1,
      "scaleUpUnscheduledPodEnabled": true,
      "scaleUpUtilizationEnabled": true,
      "tenant_id": "${var.tenant_id}",
      "unremovableNodeRecheckTimeout": 5,
      "skipNodesWithLocalStorage" : false
}
  }
}`

**Comment by anton-sidelnikov** [comment]
Added additional notes to templates
