### ISSUE TITLE
Unable to find auth_url

### ISSUE THREAD

**Issue by ReenaAcharya** [opentelekomcloud/terraform-provider-opentelekomcloud#123]
Hi,

I am writing terraform template for OpentelekomCloud. I am unable to find the auth_url. 
Also, how what is the resource name and syntax for creating VPC and Subnets.

Any suggestion\details on this will be very helpful.

Thanks.

**Comment by niuzhenguo** [comment]
@ReenaAcharya The auth_url is https://iam.eu-de.otc.t-systems.com/v3 which you should be able to find on the API docs of OTC. Regarding VPC and Subnet resources you can find the details here https://www.terraform.io/docs/providers/opentelekomcloud/r/vpc_v1.html and https://www.terraform.io/docs/providers/opentelekomcloud/r/vpc_subnet_v1.html respectively.

**Comment by ReenaAcharya** [comment]
Thank you so much @niuzhenguo
