### ISSUE TITLE
CES alarm rule argument missing

### ISSUE THREAD

**Issue by pbckr** [opentelekomcloud/terraform-provider-opentelekomcloud#1230]
For the Cloud Eye alarm rule resource there is no option in what frequency an alarm message will be sent out when the alarm has been triggered and the monitoring object is still abnormal:
![image](https://user-images.githubusercontent.com/52598729/126778439-2f4d87e0-de31-43df-b00b-a3ade7775a41.png)
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/ces_alarmrule

Using the OTC Console UI this setting can be configured:
![image](https://user-images.githubusercontent.com/52598729/126777922-404012fa-f711-49d8-b101-0c402cfcdc85.png)

**Comment by lego963** [comment]
@pbckr using the doc from HC this setting can't be configured https://docs.otc.t-systems.com/en-us/api/ces/ces_03_0031.html

**Comment by lego963** [comment]
Internal incident: https://jira.tsi-dev.otc-service.com/browse/XAAS-8907

**Comment by Aloento** [comment]
moved to https://jira.tsi-dev.otc-service.com/browse/OTCORC-528

**Comment by artem-lifshits** [comment]
@pbckr frequency is specified in `period` section in seconds.
Specifying `86400` in `period` will put frequency to 1 day (24 hours).

**Comment by artem-lifshits** [comment]
@pbckr sorry missed the point here. 

We still have problems with docu (this parameter is not descritbed) but after some reverse engineering I've found how we can set interval for alarm triggering.

Will be available on next release.

**Comment by artem-lifshits** [comment]
@pbckr feature available in latest release.
