### ISSUE TITLE
OBS Bucket Creation Fails (partly)

### ISSUE THREAD

**Issue by DanielHabenicht** [opentelekomcloud/terraform-provider-opentelekomcloud#1231]
# Terraform Version
Terraform v0.14.7
```
opentelekomcloud = {
      source  = "opentelekomcloud/opentelekomcloud"
      version = ">= 1.24.6"
    }
```

# Affected Resource(s)

- opentelekomcloud_obs_bucket

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_obs_bucket" "ssl_storage" {
  bucket        = "ssl-storage"
  storage_class = "STANDARD"
  acl           = "private"
}
```

# Debug Output/Panic Output
```bash
module.setup.opentelekomcloud_obs_bucket.ssl_storage: Creating...

Error: error creating bucket ssl-storage: AccessDenied,
 Reason: Access Denied

  on modules\setup\main.tf line 50, in resource "opentelekomcloud_obs_bucket" 
"ssl_storage":
  50: resource "opentelekomcloud_obs_bucket" "ssl_storage" {
```

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior
No Error. 

# Actual Behavior
The Storage is created but the Terraform script errors. 

# Important Factoids
I tried it also on a different account but there i am getting the following error: 
```bash
Error: error reading bucket encryption: obs: service returned error: Status=403 Forbidden, Code=SignatureDoesNotMatch, Message=The request signature we calculated does not match 
the signature you provided. Check your key and signing method., RequestId=051A0000017AD44940B3481A6343C572
```

# References

**Comment by DanielHabenicht** [comment]
@outcatcher can you replicate the behavior or am I doing something wrong?

**Comment by outcatcher** [comment]
@DanielHabenicht I wasn't able to reproduce this behaviour, though @lego963 has such a problem with OBS too. He was going to investigate the issue.

**Comment by DanielHabenicht** [comment]
thanks! at the moment I am working around it by using a SFS turbo drive for kubernetes volumes. But reserving 500GB for a 2MB file kind of defeating.

**Comment by DanielHabenicht** [comment]
Can you maybe also as a workaround create a data source for `opentelekomcloud_obs_bucket` so that one can create the obs bucket manually and then import it or would this run into the same problem?

**Comment by outcatcher** [comment]
@DanielHabenicht should be no problem creating a data source

**Comment by DanielHabenicht** [comment]
Does this also solve the internal Connectivity problem?

**Comment by lego963** [comment]
Internal incident: https://jira.tsi-dev.otc-service.com/browse/STO-5608

**Comment by lego963** [comment]
@DanielHabenicht teams work on that issue

**Comment by DanielHabenicht** [comment]
@lego963 how is it progressing? (I can't see the issue tracker)
cc @pbckr

**Comment by lego963** [comment]
@DanielHabenicht there is no progress ... We are still waiting for a response.

**Comment by Aloento** [comment]
Status:PENDING

**Comment by artem-lifshits** [comment]
Hello @DanielHabenicht Storage squad has performed several changes for OBS firewall settings, can you please check if the issue still persists?

**Comment by DanielHabenicht** [comment]
Unfortunately I do not have access to this Project anymore. So you can close it if you confirmed it yourself :),

**Comment by artem-lifshits** [comment]
@DanielHabenicht I see, thank you for fast reply.
