### ISSUE TITLE
opentelekomcloud_elb_health documentation

### ISSUE THREAD

**Issue by hcantzler** [opentelekomcloud/terraform-provider-opentelekomcloud#1238]
Documentation of elb health check contains a small error. The argument healthcheck_interval must be a number between 1 and 50. The "0" is missing.

I also noticed an argument block "timeouts" in the example, but there is no explanation about it.

https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/elb_health

**Comment by hcantzler** [comment]
I think this is another issue. I try to use the health check with opentelekomcloud_lb_listener_v2, but this is not working.

**Comment by lego963** [comment]
@hcantzler These ELBv1 resources are deprecated.
```
opentelekomcloud_elb_backend
opentelekomcloud_elb_health
opentelekomcloud_elb_listener
opentelekomcloud_elb_loadbalancer
```
Try to use ELBv2.
```
opentelekomcloud_lb_certificate_v2
opentelekomcloud_lb_l7policy_v2
opentelekomcloud_lb_l7rule_v2
opentelekomcloud_lb_listener_v2
opentelekomcloud_lb_loadbalancer_v2
opentelekomcloud_lb_member_v2
opentelekomcloud_lb_monitor_v2
opentelekomcloud_lb_pool_v2
opentelekomcloud_lb_whitelist_v2
```

**Comment by hcantzler** [comment]
Thank you
