### ISSUE TITLE
provider.opentelekomcloud: Authentication failed

### ISSUE THREAD

**Issue by ReenaAcharya** [opentelekomcloud/terraform-provider-opentelekomcloud#125]
Hi,

I am trying to connect OpenTelekomCloud using Terraform template.I am getting authentication failure while connecting to cloud. Below is the provider code I am using to connect to OpenTelekomCloud.
variable "username" {}
variable "password" {}
variable "domain_name" {}
variable "endpoint" {}
#variable "vpc_name" {}

provider "opentelekomcloud" {
  user_name   = "${var.username}"
  password    = "${var.password}"
  #tenant_name = "${var.tenant_name}"
  domain_name = "${var.domain_name}"
  auth_url    = "${var.endpoint}"
}

data "opentelekomcloud_vpc_v1" "vpc" {
  name = "Prod-VPC"
  region = "eu-de"
  cidr = "10.0.0.0/16"
}

I am providing right parameters values to all variables defined.

Any suggestion here would be very helpful.

Thanks,
Reena

**Comment by niuzhenguo** [comment]
@ReenaAcharya You need to provide a tenant_name and you can export OS_DEBUG=1 and TF_LOG=DEBUG with the terraform command to get more debug logs for the issue.

**Comment by ReenaAcharya** [comment]
Hi @niuzhenguo...I gave tenant name same as username. Also I exported OS_DEBUG=1.
I am getting following error:-

The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
Error refreshing state: 1 error(s) occurred:
* provider.opentelekomcloud: Authentication failed


Thanks,
Reena

**Comment by niuzhenguo** [comment]
@ReenaAcharya The tenant_name should not be same with the username, you can find it on the Console->My Credentials, Project is the tenant, mine is eu-de.

**Comment by ReenaAcharya** [comment]
Thanks @niuzhenguo ... the authentication issue got solved after setting tenant name and creating API password.
