### ISSUE TITLE
CCE - AOM integration. Please provide a way to install icagent at cluster setup

### ISSUE THREAD

**Issue by dombisza** [opentelekomcloud/terraform-provider-opentelekomcloud#1285]
Hi,

As far as I can see when I install a CCE cluster from the console, the ICAgent deamonset is deployed by default, which is needed for AOM integration of CCE.
Please consider installing the agent by default so terraform deployments can be the same as console deployments.
If you dont think it is a good idea to deploy the agent by default, please provide a way to install it from terraform.

br
Szabolcs

**Comment by lego963** [comment]
@dombisza if we create `resource/opentelekomcloud_cce_daemonset_v3` will it be enough?

**Comment by dombisza** [comment]
@lego963 I dont want to manage deamonsets from terraform and I dont even think it is a good idea to do that. ICAgent is an agent provided by OTC/CCE and it is installed by default when you set up a cluster from the OTC console.
I am not sure if you can do the deployment of this agent from the OTC API or not. If there is no way of doing this from the API I am guessing we cannot do it from terraform as well, no matter how hard we want it.
If this is the case I can open an internal DEMAND so we can deploy it from API or make the deployment of the agent a default setting.

**Comment by dombisza** [comment]
I have just checked and ICAgent is not installed if I deploy the cluster via the CCE API. So I guess we need to modify the CCE API to allow the deployment or deploy it by default.
I will create a DEMAND for this then we will see. I am closing this issue for now.

**Comment by dombisza** [comment]
DM-2913
