### ISSUE TITLE
[CI] automate all acceptance testing

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/terraform-provider-opentelekomcloud#1290]
# Description of the enhancement
Currently, lack of automated acceptance leads to such problems as #1288

This needs to be avoided in the future.

**Comment by Aloento** [comment]
moved to https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1822

**Comment by artem-lifshits** [comment]
@Aloento this PR has a story of what exactly was done to implement automatisation.
We can also provide here future automatisation tasks, therefore I'm reopening the ticket to see full history/picture.

**Comment by anton-sidelnikov** [comment]
@bakhterets In each test need to enshure in which region it passed or failed and fix if possible.
add to each test: supportedRegions := []string{"eu-de", "eu-nl", "eu-ch2"} and 
common.TestAccPreCheckServiceAvailability(t, testServiceV1, supportedRegions)
where testService* points to service name from service catalog (openstack endpoint list) (look at as tests for example)

**Acceptance tests**
- [x] antiddos
  - [x] data_source_opentelekomcloud_antiddos_v1_test.go
  - [x] resource_opentelekomcloud_antiddos_v1_test.go
- [x] as
  - [x] resource_opentelekomcloud_as_configuration_v1_test.go
  - [x] resource_opentelekomcloud_as_group_v1_test.go
  - [x] resource_opentelekomcloud_as_policy_v1_test.go
  - [x] resource_opentelekomcloud_as_policy_v2_test.go
- [x] bms - skip
- [ ] cbr
  - [ ] data_source_opentelekomcloud_cbr_backup_v3_test.go
  - [ ] data_source_opentelekomcloud_cbr_backups_ids_v3_test.go
  - [ ] resource_opentelekomcloud_cbr_policy_v3_test.go
  - [ ] resource_opentelekomcloud_cbr_vault_v3_test.go
- [ ] cce
  - [ ] data_source_opentelekomcloud_cce_addon_template_v3_test.go
  - [ ] data_source_opentelekomcloud_cce_cluster_kubeconfig_v3_test.go
  - [ ] data_source_opentelekomcloud_cce_cluster_v3_test.go
  - [ ] data_source_opentelekomcloud_cce_node_ids_v3_test.go
  - [ ] data_source_opentelekomcloud_cce_node_v3_test.go
  - [ ] resource_opentelekomcloud_cce_addon_v3_test.go
  - [ ] resource_opentelekomcloud_cce_cluster_v3_test.go
  - [ ] resource_opentelekomcloud_cce_node_pool_v3_test.go
  - [ ] resource_opentelekomcloud_cce_node_v3_test.go
- [ ] ces
  - [ ] resource_opentelekomcloud_ces_alarmrule_test.go
- [ ] common
  - [ ] quotas_test.go
- [ ] csbs
  - [ ] data_source_opentelekomcloud_csbs_backup_policy_v1_test.go
  - [ ] data_source_opentelekomcloud_csbs_backup_v1_test.go
  - [ ] resource_opentelekomcloud_csbs_backup_policy_v1_test.go
  - [ ] resource_opentelekomcloud_csbs_backup_v1_test.go
- [ ] css
  - [ ] data_source_opentelekomcloud_css_flavor_v1_test.go
  - [ ] resource_opentelekomcloud_css_cluster_v1_test.go
  - [ ] resource_opentelekomcloud_css_snapshot_configuration_v1_test.go
- [ ] cts
  - [ ] data_source_opentelekomcloud_cts_tracker_v1_test.go
  - [ ] resource_opentelekomcloud_cts_event_notification_v3_test.go
  - [ ] resource_opentelekomcloud_cts_tracker_v1_test.go
- [ ] dcs
  - [ ] data_source_opentelekomcloud_dcs_az_v1_test.go
  - [ ] data_source_opentelekomcloud_dcs_maintainwindow_v1_test.go
  - [ ] data_source_opentelekomcloud_dcs_product_v1_test.go
  - [ ] resource_opentelekomcloud_dcs_instance_v1_test.go
- [ ] dds
  - [ ] data_source_opentelekomcloud_dds_flavors_v3_test.go
  - [ ] data_source_opentelekomcloud_dds_instance_v3_test.go
  - [ ] resource_opentelekomcloud_dds_instance_v3_test.go
- [ ] deh
  - [ ] data_source_opentelekomcloud_deh_host_v1_test.go
  - [ ] data_source_opentelekomcloud_deh_server_v1_test.go
  - [ ] import_opentelekomcloud_deh_host_v1_test.go
  - [ ] resource_opentelekomcloud_deh_host_v1_test.go
- [ ] dms
  - [ ] data_source_opentelekomcloud_dms_az_v1_test.go
  - [ ] data_source_opentelekomcloud_dms_maintainwindow_v1_test.go
  - [ ] data_source_opentelekomcloud_dms_product_v1_test.go
  - [ ] resource_opentelekomcloud_dms_instance_v1_test.go
  - [ ] resource_opentelekomcloud_dms_topic_v1_test.go
- [ ] dns
  - [ ] data_source_opentelekomcloud_dns_nameservers_v2_test.go
  - [ ] data_source_opentelekomcloud_dns_zone_v2_test.go
  - [ ] import_opentelekomcloud_dns_recordset_v2_test.go
  - [ ] import_opentelekomcloud_dns_zone_v2_test.go
  - [ ] resource_opentelekomcloud_dns_ptrrecord_v2_test.go
  - [ ] resource_opentelekomcloud_dns_recordset_v2_test.go
  - [ ] resource_opentelekomcloud_dns_zone_v2_test.go
- [ ] ecs
  - [ ] data_source_opentelekomcloud_compute_availability_zones_v2_test.go
  - [ ] data_source_opentelekomcloud_compute_flavor_v2_test.go
  - [ ] data_source_opentelekomcloud_compute_instance_v2_test.go
  - [ ] resource_opentelekomcloud_compute_floatingip_associate_v2_test.go
  - [ ] resource_opentelekomcloud_compute_floatingip_v2_test.go
  - [ ] resource_opentelekomcloud_compute_instance_v2_test.go
  - [ ] resource_opentelekomcloud_compute_keypair_v2_test.go
  - [ ] resource_opentelekomcloud_compute_secgroup_v2_test.go
  - [ ] resource_opentelekomcloud_compute_servergroup_v2_test.go
  - [ ] resource_opentelekomcloud_compute_volume_attach_v2_test.go
  - [ ] resource_opentelekomcloud_ecs_instance_v1_test.go
- [ ] elb
  - [ ] v2
    - [ ] data_source_opentelekomcloud_lb_member_ids_v2_test.go
    - [ ] resource_opentelekomcloud_lb_certificate_v2_test.go
    - [ ] resource_opentelekomcloud_lb_l7policy_v2_test.go
    - [ ] resource_opentelekomcloud_lb_l7rule_v2_test.go
    - [ ] resource_opentelekomcloud_lb_listener_v2_test.go
    - [ ] resource_opentelekomcloud_lb_loadbalancer_v2_test.go
    - [ ] resource_opentelekomcloud_lb_member_v2_test.go
    - [ ] resource_opentelekomcloud_lb_monitor_v2_test.go
    - [ ] resource_opentelekomcloud_lb_pool_v2_test.go
    - [ ] resource_opentelekomcloud_lb_whitelist_v2_test.go
  - [ ] v3
    - [ ] data_source_opentelekomcloud_lb_certificate_v3_test.go
    - [ ] data_source_opentelekomcloud_lb_flavor_v3_test.go
    - [ ] data_source_opentelekomcloud_lb_flavors_v3_test.go
    - [ ] data_source_opentelekomcloud_lb_listener_v3_test.go
    - [ ] data_source_opentelekomcloud_lb_loadbalancer_v3_test.go
    - [ ] resource_opentelekomcloud_lb_certificate_v3_test.go
    - [ ] resource_opentelekomcloud_lb_listener_v3_test.go
    - [ ] resource_opentelekomcloud_lb_loadbalancer_v3_test.go
    - [ ] resource_opentelekomcloud_lb_member_v3_test.go
    - [ ] resource_opentelekomcloud_lb_monitor_v3_test.go
    - [ ] resource_opentelekomcloud_lb_policy_v3_test.go
    - [ ] resource_opentelekomcloud_lb_pool_v3_test.go
    - [ ] resource_opentelekomcloud_lb_rule_v3_test.go
- [ ] evs
  - [ ] resource_opentelekomcloud_blockstorage_volume_v2_test.go
  - [ ] resource_opentelekomcloud_evs_volume_v3_test.go
- [ ] fw
  - [ ] import_opentelekomcloud_fw_firewall_group_v2_test.go
  - [ ] import_opentelekomcloud_fw_policy_v2_test.go
  - [ ] import_opentelekomcloud_fw_rule_v2_test.go
  - [ ] resource_opentelekomcloud_fw_firewall_group_v2_test.go
  - [ ] resource_opentelekomcloud_fw_policy_v2_test.go
  - [ ] resource_opentelekomcloud_fw_rule_v2_test.go
- [ ] iam
  - [ ] data_source_opentelekomcloud_identity_agency_v3_test.go
  - [ ] data_source_opentelekomcloud_identity_auth_scope_v3_test.go
  - [ ] data_source_opentelekomcloud_identity_group_v3_test.go
  - [ ] data_source_opentelekomcloud_identity_project_v3_test.go
  - [ ] data_source_opentelekomcloud_identity_projects_v3_test.go
  - [ ] data_source_opentelekomcloud_identity_role_custom_v3_test.go
  - [ ] data_source_opentelekomcloud_identity_role_v3_test.go
  - [ ] data_source_opentelekomcloud_identity_user_v3_test.go
  - [ ] import_opentelekomcloud_identity_credential_v3_test.go
  - [ ] import_opentelekomcloud_identity_mapping_v3_test.go
  - [ ] import_opentelekomcloud_identity_project_v3_test.go
  - [ ] import_opentelekomcloud_identity_provider_v3_test.go
  - [ ] resource_opentelekomcloud_identity_agency_v3_test.go
  - [ ] resource_opentelekomcloud_identity_credential_v3_test.go
  - [ ] resource_opentelekomcloud_identity_group_membership_v3_test.go
  - [ ] resource_opentelekomcloud_identity_group_v3_test.go
  - [ ] resource_opentelekomcloud_identity_mapping_v3_test.go
  - [ ] resource_opentelekomcloud_identity_project_v3_test.go
  - [ ] resource_opentelekomcloud_identity_protocol_v3_test.go
  - [ ] resource_opentelekomcloud_identity_provider_v3_test.go
  - [ ] resource_opentelekomcloud_identity_role_assignment_v3_test.go
  - [ ] resource_opentelekomcloud_identity_role_v3_test.go
  - [ ] resource_opentelekomcloud_identity_user_group_membership_v3_test.go
  - [ ] resource_opentelekomcloud_identity_user_v3_test.go
- [ ] ims
  - [ ] data_source_opentelekomcloud_images_image_v2_test.go
  - [ ] import_opentelekomcloud_images_image_access_accept_v2_test.go
  - [ ] import_opentelekomcloud_images_image_access_v2_test.go
  - [ ] import_opentelekomcloud_images_image_v2_test.go
  - [ ] resource_opentelekomcloud_images_image_access_accept_v2_test.go
  - [ ] resource_opentelekomcloud_images_image_access_v2_test.go
  - [ ] resource_opentelekomcloud_images_image_v2_test.go
  - [ ] resource_opentelekomcloud_ims_data_image_v2_test.go
  - [ ] resource_opentelekomcloud_ims_image_v2_test.go
- [ ] kms
  - [ ] data_source_opentelekomcloud_kms_data_key_v1_test.go
  - [ ] data_source_opentelekomcloud_kms_key_v1_test.go
  - [ ] import_opentelekomcloud_kms_key_v1_test.go
  - [ ] resource_opentelekomcloud_kms_grant_v1_test.go
  - [ ] resource_opentelekomcloud_kms_key_v1_test.go
- [ ] lts
  - [ ] resource_opentelekomcloud_lts_loggroup_test.go
  - [ ] resource_opentelekomcloud_lts_logtopic_test.go
- [ ] mrs
  - [ ] resource_opentelekomcloud_mrs_cluster_v1_test.go
  - [ ] resource_opentelekomcloud_mrs_job_v1_test.go
- [ ] nat
  - [ ] resource_opentelekomcloud_nat_dnat_rule_v2_test.go
  - [ ] resource_opentelekomcloud_nat_gateway_v2_test.go
  - [ ] resource_opentelekomcloud_nat_snat_rule_v2_test.go
- [ ] obs
  - [ ] data_source_opentelekomcloud_obs_bucket_object_test.go
  - [ ] data_source_opentelekomcloud_obs_bucket_test.go
  - [ ] resource_opentelekomcloud_obs_bucket_object_test.go
  - [ ] resource_opentelekomcloud_obs_bucket_policy_test.go
  - [ ] resource_opentelekomcloud_obs_bucket_test.go
- [ ] rds
  - [ ] data_source_opentelekomcloud_rds_backup_v3_test.go
  - [ ] data_source_opentelekomcloud_rds_flavors_v1_test.go
  - [ ] data_source_opentelekomcloud_rds_flavors_v3_test.go
  - [ ] data_source_opentelekomcloud_rds_instance_v3_test.go
  - [ ] data_source_opentelekomcloud_rds_versions_v3_test.go
  - [ ] import_opentelekomcloud_rds_instance_v3_test.go
  - [ ] import_opentelekomcloud_rds_read_replica_v3_test.go
  - [ ] resource_opentelekomcloud_rds_instance_v1_test.go
  - [ ] resource_opentelekomcloud_rds_instance_v3_test.go
  - [ ] resource_opentelekomcloud_rds_parametergroup_v3_test.go
  - [ ] resource_opentelekomcloud_rds_read_replica_v3_test.go
- [ ] rts
  - [ ] data_source_opentelekomcloud_rts_software_config_v1_test.go
  - [ ] data_source_opentelekomcloud_rts_software_deployment_v1_test.go
  - [ ] data_source_opentelekomcloud_rts_stack_resource_v1_test.go
  - [ ] data_source_opentelekomcloud_rts_stack_v1_test.go
  - [ ] import_opentelekomcloud_rts_software_config_v1_test.go
  - [ ] import_opentelekomcloud_rts_software_deployment_v1_test.go
  - [ ] import_opentelekomcloud_rts_stack_v1_test.go
  - [ ] resource_opentelekomcloud_rts_software_config_v1_test.go
  - [ ] resource_opentelekomcloud_rts_software_deployment_v1_test.go
  - [ ] resource_opentelekomcloud_rts_stack_v1_test.go
- [ ] s3
  - [ ] data_source_opentelekomcloud_s3_bucket_object_test.go
  - [ ] resource_opentelekomcloud_s3_bucket_object_test.go
  - [ ] resource_opentelekomcloud_s3_bucket_policy_test.go
  - [ ] resource_opentelekomcloud_s3_bucket_test.go
- [ ] sdrs
  - [ ] data_source_opentelekomcloud_sdrs_domain_v1_test.go
  - [ ] import_opentelekomcloud_sdrs_protected_instance_v1_test.go
  - [ ] resource_opentelekomcloud_sdrs_protected_instance_v1_test.go
  - [ ] resource_opentelekomcloud_sdrs_protectiongroup_v1_test.go
- [ ] sfs
  - [ ] data_source_opentelekomcloud_sfs_file_system_v2_test.go
  - [ ] data_source_opentelekomcloud_sfs_turbo_share_v1_test.go
  - [ ] import_opentelekomcloud_sfs_file_system_v2_test.go
  - [ ] import_opentelekomcloud_sfs_share_access_rules_v2_test.go
  - [ ] import_opentelekomcloud_sfs_turbo_share_v1_test.go
  - [ ] resource_opentelekomcloud_sfs_file_system_v2_test.go
  - [ ] resource_opentelekomcloud_sfs_share_access_rules_v2_test.go
  - [ ] resource_opentelekomcloud_sfs_turbo_share_v1_test.go
- [ ] smn
  - [ ] resource_opentelekomcloud_smn_subscription_v2_test.go
  - [ ] resource_opentelekomcloud_smn_topic_attribute_v2_test.go
  - [ ] resource_opentelekomcloud_smn_topic_v2_test.go
- [ ] swr
  - [ ] import_opentelekomcloud_swr_organization_v2_test.go
  - [ ] import_opentelekomcloud_swr_repository_v2_test.go
  - [ ] resource_opentelekomcloud_swr_domain_v2_test.go
  - [ ] resource_opentelekomcloud_swr_organization_permissions_test.go
  - [ ] resource_opentelekomcloud_swr_organization_v2_test.go
  - [ ] resource_opentelekomcloud_swr_repository_v2_test.go
- [ ] vbs
  - [ ] data_source_opentelekomcloud_vbs_backup_policy_v2_test.go
  - [ ] data_source_opentelekomcloud_vbs_backup_v2_test.go
  - [ ] import_opentelekomcloud_vbs_backup_policy_v2_test.go
  - [ ] import_opentelekomcloud_vbs_backup_share_v2_test.go
  - [ ] import_opentelekomcloud_vbs_backup_v2_test.go
  - [ ] resource_opentelekomcloud_vbs_backup_policy_v2_test.go
  - [ ] resource_opentelekomcloud_vbs_backup_share_v2_test.go
  - [ ] resource_opentelekomcloud_vbs_backup_v2_test.go
- [ ] vpc
  - [ ] data_source_opentelekomcloud_networking_network_v2_test.go
  - [ ] data_source_opentelekomcloud_networking_port_v2_test.go
  - [ ] data_source_opentelekomcloud_networking_secgroup_rule_ids_v2_test.go
  - [ ] data_source_opentelekomcloud_networking_secgroup_v2_test.go
  - [ ] data_source_opentelekomcloud_vpc_bandwidth_test.go
  - [ ] data_source_opentelekomcloud_vpc_bandwidth_v2_test.go
  - [ ] data_source_opentelekomcloud_vpc_eip_v1_test.go
  - [ ] data_source_opentelekomcloud_vpc_peering_connection_v2_test.go
  - [ ] data_source_opentelekomcloud_vpc_route_ids_v2_test.go
  - [ ] data_source_opentelekomcloud_vpc_route_v2_test.go
  - [ ] data_source_opentelekomcloud_vpc_subnet_ids_v1_test.go
  - [ ] data_source_opentelekomcloud_vpc_subnet_v1_test.go
  - [ ] data_source_opentelekomcloud_vpc_v1_test.go
  - [ ] resource_opentelekomcloud_networking_floatingip_associate_v2_test.go
  - [ ] resource_opentelekomcloud_networking_floatingip_v2_test.go
  - [ ] resource_opentelekomcloud_networking_network_v2_test.go
  - [ ] resource_opentelekomcloud_networking_port_v2_test.go
  - [ ] resource_opentelekomcloud_networking_router_interface_v2_test.go
  - [ ] resource_opentelekomcloud_networking_router_route_v2_test.go
  - [ ] resource_opentelekomcloud_networking_router_v2_test.go
  - [ ] resource_opentelekomcloud_networking_secgroup_rule_v2_test.go
  - [ ] resource_opentelekomcloud_networking_secgroup_v2_test.go
  - [ ] resource_opentelekomcloud_networking_subnet_v2_test.go
  - [ ] resource_opentelekomcloud_networking_vip_associate_v2_test.go
  - [ ] resource_opentelekomcloud_networking_vip_v2_test.go
  - [ ] resource_opentelekomcloud_vpc_bandwidth_associate_v2_test.go
  - [ ] resource_opentelekomcloud_vpc_bandwidth_v2_test.go
  - [ ] resource_opentelekomcloud_vpc_eip_v1_test.go
  - [ ] resource_opentelekomcloud_vpc_flow_log_v1_test.go
  - [ ] resource_opentelekomcloud_vpc_peering_connection_accepter_v2_test.go
  - [ ] resource_opentelekomcloud_vpc_peering_connection_v2_test.go
  - [ ] resource_opentelekomcloud_vpc_route_v2_test.go
  - [ ] resource_opentelekomcloud_vpc_subnet_v1_test.go
  - [ ] resource_opentelekomcloud_vpc_v1_test.go
- [ ] vpcep
  - [ ] data_source_opentelekomcloud_vpcep_public_service_v1_test.go
  - [ ] data_source_opentelekomcloud_vpcep_service_v1_test.go
  - [ ] resource_opentelekomcloud_vpcep_endpoint_v1_test.go
  - [ ] resource_opentelekomcloud_vpcep_service_test.go
- [ ] vpn
  - [ ] data_source_opentelekomcloud_vpnaas_service_v2_test.go
  - [ ] resource_opentelekomcloud_vpnaas_endpoint_group_v2_test.go
  - [ ] resource_opentelekomcloud_vpnaas_ike_policy_v2_test.go
  - [ ] resource_opentelekomcloud_vpnaas_ipsec_policy_v2_test.go
  - [ ] resource_opentelekomcloud_vpnaas_service_v2_test.go
  - [ ] resource_opentelekomcloud_vpnaas_site_connection_v2_test.go
- [ ] waf
  - [ ] import_certificate_v1_test.go
  - [ ] resource_alarm_notification_v1_test.go
  - [ ] resource_ccattackprotection_rule_v1_test.go
  - [ ] resource_certificate_v1_test.go
  - [ ] resource_datamasking_rule_v1_test.go
  - [ ] resource_domain_v1_test.go
  - [ ] resource_falsealarmmasking_rule_v1_test.go
  - [ ] resource_policy_v1_test.go
  - [ ] resource_preciseprotection_rule_v1_test.go
  - [ ] resource_webtamperprotection_rule_v1_test.go
  - [ ] resource_whiteblackip_rule_v1_test.go
- [ ] provider_test.go
