### ISSUE TITLE
Data Source for opentelekomcloud_sfs_turbo_share_v1

### ISSUE THREAD

**Issue by DanielHabenicht** [opentelekomcloud/terraform-provider-opentelekomcloud#1295]
# Description of the enhancement
I would like to get data from `opentelekomcloud_sfs_turbo_share_v1` by 
```
data "opentelekomcloud_sfs_turbo_share_v1" "example" {
  name = "my-sfs-storage-name"
}
```
Thanks!

**Comment by DanielHabenicht** [comment]
To provide some reason or insight it would be great to get `export_location` `region` and `size` from the data source as I have to import already created storage drives into kubernetes and need those information to create the persistent volume.

**Comment by outcatcher** [comment]
@DanielHabenicht Do you need other filter criteria besides the `name`?

**Comment by DanielHabenicht** [comment]
No not yet
