### ISSUE TITLE
[CCE] creating a node scaling policy

### ISSUE THREAD

**Issue by ghost** [opentelekomcloud/terraform-provider-opentelekomcloud#1316]
I want to enable CCE node auto scaling.
I can create a "node scaling policy" in the OTC Web interface. But I could not find any documentation on how 
to do this in terraform. Is this even needed for automatic node autoscaling if I set scaleUpUnscheduledPodEnabled=true in the autoscaling plugin?

**Comment by philippeckel** [comment]
I wonder if only the documentation is missing or the implementation in the Terraform provider :-)

**Comment by lego963** [comment]
@philippeckel we are waiting answer from a responsible squad

**Comment by lego963** [comment]
We don't have API for now
Demand created: https://jira.tsi-dev.otc-service.com/browse/DM-3001

**Comment by ghost** [comment]
Maybe Using the AutoScaler PlugIn like described here is an Option?
https://community.open-telekom-cloud.com/community/community?id=community_blog&sys_id=90b46a31138d3c18d15ac969a6744175

**Comment by ghost** [comment]
Thank you @ulrschne for the link. I follwed the instructions but scaling of nodes does not happen. I see pods that want to start because hpa scaled up the deployment. But they are all 'pending' because there are not enough resources on the nodes, but the nodepool never gets scaled up.
Is there documentation of which values are needed and which are optional?

**Comment by ghost** [comment]
Problem was on our side. The autoscaler ignored our soft affinities for the nodepools. We changed them to hard (requiredDuringSchedulingIgnoredDuringExecution) and now it works. Thanks a lot :)
https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#does-ca-respect-node-affinity-when-selecting-node-groups-to-scale-up
