### ISSUE TITLE
[REQUEST] Add support for Cloud_container_engine (CCE)

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#133]
It would be so nice to be enabled to use kubernetes of the OTC
Since this seams to be one of their main features....

### Terraform Version
```
terraform -v
Terraform v0.11.8
+ provider.kubernetes v1.3.0
+ provider.opentelekomcloud v1.3.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- opentelekomcloud_cce

### Expected Behavior
I'm enabled to use the CCE feature and provision a Kubernetes Cluster within the OTC

### Actual Behavior
There is either an Openstack nor a OTC module to use this feature

**Comment by Moep90** [comment]
@niuzhenguo are there any plans?

**Comment by Moep90** [comment]
I was able to create a Cluster using the following as POST

Endpoint: `https://cce.eu-de.otc.t-systems.com/api/v3/projects/<ProjectID>/clusters`

```
{
    "kind": "Cluster",
    "apiVersion": "v3",
    "metadata": {
        "name": "<ClusterName>",
        "uid": "<UID>",
        "creationTimestamp": "<timestamp>",
        "updateTimestamp": "<timestamp>",
        "labels": {
            "foo": "bar"
        }
    },
    "spec": {
        "type": "VirtualMachine",
        "flavor": "cce.s1.small",
        "az": "eu-de-02",
        "version": "v1.9.2-r2",
        "description": "this is a demo cluster",
        "hostNetwork": {
            "vpc": "<VPC-ID>",
            "subnet": "<SUBNET-ID>"
        },
        "containerNetwork": {
            "mode": "overlay_l2",
            "cidr": "<CIDR>/16"
        },
        "billingMode": 0
    },
    "status": {
        "phase": "Creating",
        "jobID": "<jobID>",
        "endpoints": {}
    }
}
```

**Comment by niuzhenguo** [comment]
@Moep90 Yes, we are working on that now, will try to get it done in the next release.

**Comment by Moep90** [comment]
Thats perfect news!
@niuzhenguo Is there some kind of roadmap online?

**Comment by niuzhenguo** [comment]
@Moep90 Sorry for the late reply, there's not online roadmap yet, but we will try to add issues for tracking new features as you always do :P

**Comment by Moep90** [comment]
@niuzhenguo I commented directly into the PR.

**Comment by Moep90** [comment]
Since v1.4 is released.
