### ISSUE TITLE
Resource/data source opentelekomcloud_dns_zone_v2 does not return values for masters attribute

### ISSUE THREAD

**Issue by akroshchenko** [opentelekomcloud/terraform-provider-opentelekomcloud#1344]
# Terraform Version
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.25.2

# Affected Resource(s)
resources/data source: opentelekomcloud_dns_zone_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_dns_zone_v2" "public_testdomain_eu" {
  name        = "testdomain.eu."
  email       = "akros@testdomain.de"
  description = "Public zone"
  ttl         = 3000
  type        = "public"

  tags = local.tags
}

resource "opentelekomcloud_dns_recordset_v2" "test_record" {
  zone_id     = opentelekomcloud_dns_zone_v2.public_testdomain_eu.id
  name        = "test.${opentelekomcloud_dns_zone_v2.public_testdomain_eu.name}"
  description = "An example record set"
  ttl         = 300
  type        = "A"
  records     = ["10.0.0.1"]
}
output "public_testdomain_eu_zone_spec" {
  value = opentelekomcloud_dns_zone_v2.public_testdomain_eu
}

# NOTE: uncomment and apply these changes once you deploy the resources above
# data "opentelekomcloud_dns_zone_v2" "public_testdomain_eu" {
#   name = "testdomain.eu."
# }
# output "data_source_public_testdomain_eu_zone_spec" {
#   value = data.opentelekomcloud_dns_zone_v2.public_testdomain_eu
# }
```

# Debug Output/Panic Output
Outputs:
public_testdomain_eu_zone_spec = {
  "description" = "Public zone"
  "email" = "akros@testdomain.de"
  "masters" = toset([])   <-------------------- is empty
  "name" = "testdomain.eu."
  "region" = "eu-de"
  "router" = toset([])
  "timeouts" = null /* object */
  "ttl" = 3000
  "type" = "public"
  "value_specs" = tomap(null) /* of string */
}

# Steps to Reproduce
1. `terraform apply`

# Expected Behavior
`masters` attribute is not empty

# Actual Behavior
`masters` attribute is empty

# Important Factoids

# References

**Comment by outcatcher** [comment]
@akroshchenko This attribute is returned empty from the API. Per [documentation](https://docs.otc.t-systems.com/en-us/api/dns/dns_api_62002.html) it is not used:
```
Master DNS servers, from which the slave servers get DNS information

This parameter is not used currently.
```
So data source itself behaves correctly.
