### ISSUE TITLE
ECS Instance unable to choose DISK-I/O-type of local volume

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#136]
Hi there,

unfortunatly I'm unable to change the type of my boot volume.
Since block devices cannot be mounted as boot volumes I need to create, attach and mount additional volumes which is very unhandy.

### Terraform Version
```
$ terraform -v
Terraform v0.11.10
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.opentelekomcloud v1.3.0
+ provider.random v2.0.0

```

### Affected Resource(s)
Please list the resources as a list, for example:
- opentelekomcloud_compute_instance_v2

### Terraform Configuration Files
```hcl
variable "ecs_volume_type" {
    description = "SSD (ultra-high I/O), SAS (high I/O disk), SATA (common I/O disk)"
}

resource "opentelekomcloud_compute_instance_v2" "ecs_instance" {
[...]
  image_name        = "${var.ecs_image_name}"
  flavor_name       = "${var.ecs_flavor}"
[...]

  metadata {
[...]
  }

  block_device {
    uuid                  = "${data.opentelekomcloud_images_image_v2.ecs_image_data.id}"
    volumetype            = "${var.ecs_volume_type}"
    source_type           = "image"
    boot_index            = 0
    destination_type      = "local"
    delete_on_termination = "${var.delete_on_termination}"
  }

  network {
[...]
  }

}
```

### Expected Behavior
To choose wether my boot volume is SSD, SAS or SATA like its written in api doc of OpenTelekomCloud (OTC)
https://docs.otc.t-systems.com/en-us/api/ecs/en-us_topic_0020212668.html

### Actual Behavior
```hcl
Error: module.[...].opentelekomcloud_compute_instance_v2.ecs_instance[0]: block_device.0: invalid or unknown key: volumetype
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by Moep90** [comment]
@niuzhenguo Could this please be part of the next release?
Do you already know when this will take place?

**Comment by niuzhenguo** [comment]
@Moep90 Thanks for raising that, it's already supported now but need to wait until we cut a new release.
https://github.com/terraform-providers/terraform-provider-opentelekomcloud/commit/7dc9d1e67715e1f82a2cba73415c824e36020d9a

**Comment by Moep90** [comment]
This seams to be included in v1.4.0 but there is a lack of documentation.
@niuzhenguo So I opened #149 to fix this

**Comment by niuzhenguo** [comment]
@Moep90 Thanks for that, just merged it.

**Comment by Moep90** [comment]
Perfect Thx

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
