### ISSUE TITLE
[Acceptance] Allow test to be parallel

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/terraform-provider-opentelekomcloud#1363]
# Description of the enhancement
Some (or even most of) tests can be made running parallel with `t.Parallel()`

**Comment by Aloento** [comment]
What else needs to be changed?

**Comment by outcatcher** [comment]
Any test which can be parallelized 🙂 I suppose there should be at least tests inherited from openstack sdk that are not done parallel.

**Comment by artem-lifshits** [comment]
We don't need to run tests in parallel taking into account that most of them would fail due to quota issues if we'd like to.
Still, that might be an issue after we automate tests and not at the moment.
