### ISSUE TITLE
ECS resource failed "resizing" when changing the Instance flavor

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#137]
Hi there,

I just spon up 6 instances with flavor_name: `s2.xlarge.2` after that I wanted to change the flavor to `h1.4xlarge.4` expecting to recreate or shutdown and resize it, instead it fails not get instances to correct state.

### Terraform Version
```
terraform -v
Terraform v0.11.10
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.opentelekomcloud v1.3.0
+ provider.random v2.0.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- opentelekomcloud_compute_instance_v2

### Terraform Configuration Files
Instance creation:
```hcl

resource "opentelekomcloud_compute_instance_v2" "ecs_instance" {
[...]
  image_name        = "${var.ecs_image_name}"
  flavor_name       = "s2.xlarge.2"
[...]

  metadata {
[...]
  }

  block_device {
    uuid                  = "${data.opentelekomcloud_images_image_v2.ecs_image_data.id}"
    source_type           = "image"
    boot_index            = 0
    destination_type      = "local"
    delete_on_termination = "${var.delete_on_termination}"
  }

  network {
[...]
  }

}
```
Instance resizing:
```hcl

resource "opentelekomcloud_compute_instance_v2" "ecs_instance" {
[...]
  image_name        = "${var.ecs_image_name}"
  flavor_name       = "h1.4xlarge.4"
[...]

  metadata {
[...]
  }

  block_device {
    uuid                  = "${data.opentelekomcloud_images_image_v2.ecs_image_data.id}"
    source_type           = "image"
    boot_index            = 0
    destination_type      = "local"
    delete_on_termination = "${var.delete_on_termination}"
  }

  network {
[...]
  }

}
```

### Debug Output
https://gist.github.com/Moep90/78d569ab08df7f0a83b6ce5a16df2d3a

### Error Output
```
6 error(s) occurred:

* module.[...].opentelekomcloud_compute_instance_v2.ecs_instance[2]: 1 error(s) occurred:

* opentelekomcloud_compute_instance_v2.ecs_instance.2: Error waiting for instance (f38eeb9e-63f6-4852-960a-5d8bb44e7a98) to resize: unexpected state 'SHUTOFF', wanted target 'VERIFY_RESIZE'. last error: %!s(<nil>)
* module.[...].opentelekomcloud_compute_instance_v2.ecs_instance[3]: 1 error(s) occurred:

* opentelekomcloud_compute_instance_v2.ecs_instance.3: Error waiting for instance (f25b9e7f-0756-4252-9845-0eac8cde56ec) to resize: unexpected state 'SHUTOFF', wanted target 'VERIFY_RESIZE'. last error: %!s(<nil>)
* module.[...].opentelekomcloud_compute_instance_v2.ecs_instance[5]: 1 error(s) occurred:

[...]
```

### Expected Behavior
Expection 1.)
The instances are shut down and beeing restarted when new flavor (resize) happened.
Expection 2.)
Or the instances got replaced with the new flavor.

### Actual Behavior
Got unexpected state:
When shut off: `unexpected state 'SHUTOFF', wanted target 'VERIFY_RESIZE'`
When running: `unexpected state '(RUNNING or READY), wanted target 'VERIFY_RESIZE'` when changing flavor of provisioned instances.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by niuzhenguo** [comment]
will dig more, thanks for raising this.

**Comment by niuzhenguo** [comment]
@Moep90 If recreating instance is OK for you, I can set flavor to force_new. Need to dig more about why resizing API not work.

**Comment by niuzhenguo** [comment]
I tried some flavors, the 'resizing' works fine. Seems something wrong with your flavors?

**Comment by Moep90** [comment]
> I tried some flavors, the 'resizing' works fine. Seems something wrong with your flavors?

Hey there I atm cannot check it again.

**Comment by Moep90** [comment]
Resizing works now. Thank you.
