### ISSUE TITLE
[OBS] ACL setting are ignored when set to "public-read"

### ISSUE THREAD

**Issue by jansgescheit** [opentelekomcloud/terraform-provider-opentelekomcloud#1401]
# Terraform provider version

Terraform v1.0.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/tls v3.1.0
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.25.4

# Affected Resource(s)

- opentelekomcloud_obs_bucket

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_obs_bucket" "test" {
  bucket = "awesome-bucket-test"
  acl = "public-read"

  website {
    index_document = "index.html"
    error_document = "index.html"
  }
}
```

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior
The bucket should be set to "Public-Read" in the OTC Console under Standard Bucket Policies

# Actual Behavior

The bucket is set to "Private" in the OTC Console under Standard Bucket Policies, i have to manual enable public-read via OTC Console

**Comment by lego963** [comment]
@jansgescheit in console you set `Bucket Policy`, not the `Bucket ACL`. This is different things. 
This one is `"private"` ACL
![image](https://user-images.githubusercontent.com/17201690/133617591-88cd707b-ea20-460d-8a55-02932da5e0ea.png)
This is "public-read" ACL
![image](https://user-images.githubusercontent.com/17201690/133617523-94b277cf-2aa2-4dff-ad06-2c69b90e2ead.png)
Here you can see change of `Public Permissions.Anonymous User.Read or ---`

**Comment by jansgescheit** [comment]
@lego963 You are absolutely right, I was misled because the terminology in the console is similar. When I set the policy via terraform, public access works as expected.

**Comment by mjromka** [comment]
Could you provide an example how to set public-read policy via Terraform?
