### ISSUE TITLE
Use Terraform with MFA user

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#1404]
We have an issue using TF with an OTC user, that has MFA enabled.

# Affected Resource(s)
provider "opentelekomcloud"

# Terraform Configuration Files

provider "opentelekomcloud" {
  user_id   = "USER_ID"
  password    = var.otc_password
  passcode    = var.otc_passcode
  domain_name = "OTC000000000010000XXXXX"
  tenant_name = "eu-de"
  auth_url    = "https://iam.eu-de.otc.t-systems.com/v3" 
}

# Debug Output/Panic Output
Error: failed to authenticate:
│ error generating project client: error extracting token: Authentication Failed, error message: {"error":{"code":401,"message":"The username or password is wrong.","title":"Unauthorized"}}
│
│   with provider["registry.terraform.io/opentelekomcloud/opentelekomcloud"],
│   on terraform.tf line 20, in provider "opentelekomcloud":
│   20: provider "opentelekomcloud" {

We are not able to login via TF despite using the correct passcode from the MFA device.
Login via OTC GUI works this way.

Could you please check it?

**Comment by lego963** [comment]
We can't reproduce. MFA works on our side. Can you recheck the passcode and date time on the phone?
