### ISSUE TITLE
availability_zone seems to be required now

### ISSUE THREAD

**Issue by Zaziki1337** [opentelekomcloud/terraform-provider-opentelekomcloud#141]
Hi there,
the last couple days we had trouble creating new `opentelekomcloud_compute_instance_v2` resources. After some research and debugging we found the issue: the missing `availability_zone`-parameter. Regarding the docs this parameter should be optional and is computed. But without this parameter the resource is not created and fails with this error:
`retry 2 times: Could not find a handler for proxy volume.;Could not find a handler for proxy volume...No valid host was found. There are not enough hosts available` 
(sadly this error message is not recognized by terraform, it was extracted with a networktraffic dump)
If the `availability_zone` is set in the resource, everything runs fine.
Has anyone else ran into this issue?

### Terraform Version
```
Terraform v0.11.10
+ provider.null v1.0.0
+ provider.opentelekomcloud v1.3.0
+ provider.template v1.0.0
```

### Affected Resource(s)
- opentelekomcloud_compute_instance_v2

### Terraform Configuration Files
(abstracted from original code)
#### Fails with error:
```hcl
resource "opentelekomcloud_compute_instance_v2" "instance_test" {
  count           = 1
  name            = "instance-test"
  image_name      = "Community_Ubuntu_16.04_TSI_latest"
  flavor_name     = "s2.medium.1"
  key_pair        = "deploy-key"

  security_groups = [
    "default"
  ]

  network {
    name = "my_network"
  }
}
```

#### No Problems:
```hcl
resource "opentelekomcloud_compute_instance_v2" "instance_test" {
  count           = 1
  name            = "instance-test"
  image_name      = "Community_Ubuntu_16.04_TSI_latest"
  flavor_name     = "s2.medium.1"
  key_pair        = "deploy-key"
  availability_zone = "eu-de-02"

  security_groups = [
    "default"
  ]

  network {
    name = "my_network"
  }
}
```
Only `availability_zone` is added.

### Expected Behavior
Regarding docs it should run without an given availability_zone.

### Actual Behavior
Creation is aborted.

### Steps to Reproduce
1. `terraform apply`

**Comment by rsritesh** [comment]
Hi @Zaziki1337 

I have just executed a simple configuration with the terraform opentelekomcloud provider . I did not see any  issue at this moment.

 Please see below details of my executions, please check again. 

**Terraform Version**

Terraform v0.11.10
+ provider.openstack v1.12.0
+ provider.opentelekomcloud v1.3.0

**Terraform Configuration**

```
resource "opentelekomcloud_compute_instance_v2" "terraform" {
  name            = "terraform"
  image_name      = "${var.image}"
  flavor_name     = "${var.flavor}"
  key_pair        = "${opentelekomcloud_compute_keypair_v2.terraform.name}"
  security_groups = ["${opentelekomcloud_networking_secgroup_v2.terraform.name}"]
 
  network {
    uuid = "${opentelekomcloud_networking_network_v2.terraform.id}"
 }
}
```

**Comment by niuzhenguo** [comment]
@Zaziki1337 I also can't reproduce the issue, maybe that's because of some temporary issue on the server side? If you encounter the error again please let us know, thanks!

**Comment by niuzhenguo** [comment]
Closing this, please feel free to reopen it if you still have the same issue.
