### ISSUE TITLE
allow SMN to use DMS as endpoint

### ISSUE THREAD

**Issue by ghost** [opentelekomcloud/terraform-provider-opentelekomcloud#1439]
The documentation says that the endpoint of a opentelekomcloud_smn_subscription_v2 can not be a 'DMS' endpoint.
Only http,https,email and sms are mentioned.
How are we supposed to use SMN to DMS?
It is (in theory, doesn't work because of other problems) possible to configre a subscription in the OTC console UI.
![Screenshot 2021-10-01 at 14 24 07](https://user-images.githubusercontent.com/89472114/135619395-60b77a44-09fd-495e-82da-952da0e65238.png)

**Comment by lego963** [comment]
@christophk-coyo platform doesn't support this for now. We are waiting answer from a responsible squad.

**Comment by ghost** [comment]
I don't think this is worth implementing then. 
We decided not to use OTC queues for our use case because it doesn't even work in UI.
And even the OTC support said we should run our own queue service instead of using their service :)
