### ISSUE TITLE
Acceptance: improve smart diff

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/terraform-provider-opentelekomcloud#1441]
# Description of the enhancement
Improve smart diff feature to find effective dependencies of the change

**Comment by Aloento** [comment]
Can you provide more details?

**Comment by artem-lifshits** [comment]
Hi @outcatcher can you please elaborate?

**Comment by outcatcher** [comment]
This is related to https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/devel/scripts/run-acceptance.sh
There is currently a diff check to decrease number of tests run as acceptance tests to the scope of changed code only.

This script is actually not used in CI, as zuul works with git in a very extravagant way, so we put the idea on hold.

**Comment by anton-sidelnikov** [comment]
Now we preparing another way for the zuul, no need to continue this.
