### ISSUE TITLE
[RDS] Restore backup to new DB instance

### ISSUE THREAD

**Issue by philippeckel** [opentelekomcloud/terraform-provider-opentelekomcloud#1456]
Hey,

it would be nice if restoring a backup to a new DB instance in RDS would be possible via Terraform.

API covers this here: https://docs.otc.t-systems.com/api/rds/rds_09_0008.html

This could go along with fetching backup ids using a datasource via https://docs.otc.t-systems.com/api/rds/rds_09_0005.html

Would this be possible?

Thanks,
Philipp

**Comment by outcatcher** [comment]
@philippeckel Can you provide an expected terraform configuration? Do you expect it to be a new resource or something else?

**Comment by outcatcher** [comment]
@philippeckel SDK for this feature is implemented. Though I still can't understand how it should be working. Should it be passing [restore information](https://docs.otc.t-systems.com/api/rds/rds_09_0008.html#rds_09_0008__table15343138128) to the resource?
E.g.
```hcl
resource "opentelekomcloud_rds_backup_restore_v3" "restored_instance" {
  ...
  instance_id   = var.rds_instance_id
  restore_type  = "backup"
  backup_id     = var.rds_backup_id
}
```

**Comment by eumel8** [comment]
@outcatcher @lego963  Are you interested to work on a RDS Operator? We use already RDS instances as backend of apps in Kubernetes Cluster and from our customer view it would be easier to maintain the database as K8S resource together with the application. At the moment we deploy RDS with Terraform, which works fine while instance creating and scaling. For backup handling or other operational tasks like reboot it seems hard to handle for the user. Based on [Go Operator SDK](https://sdk.operatorframework.io/docs/building-operators/golang/) and [Gophertelekomcloud](https://github.com/opentelekomcloud/gophertelekomcloud/) half of the work is almost done :-)

**Comment by outcatcher** [comment]
@eumel8 It seems to be a nice idea, we should think about that 😄

**Comment by philippeckel** [comment]
@outcatcher quite late to reply, but yes, something similar you proposed would be amazing. 

@eumel8 sounds amazing too!

**Comment by outcatcher** [comment]
Was implemented as `restore_point` argument in `opentelekomcloud_rds_instance_v3` resource.
