### ISSUE TITLE
CCE: Node: data_volumes: Data disk space allocation

### ISSUE THREAD

**Issue by sonic-martin** [opentelekomcloud/terraform-provider-opentelekomcloud#1482]
# CCE: Node: data_volumes: Data disk space allocation

Via ORC Console one is able, when creating Nodes for CCE to give a Data disk space allocation.
E.g.
![disk](https://user-images.githubusercontent.com/14333891/139248663-4960717d-076d-4d79-bb0e-0e13b512181d.PNG)

Is it possible via the Terraform Provider for OTC as well, or can you implement it?

**Comment by outcatcher** [comment]
Yes, there is `data_volumes` for that in `openetelekomcloud_cce_node_v3` resource:
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cce_node_v3#data_volumes

**Comment by sonic-martin** [comment]
I dont mean the Data Disk Type/Size part.
This is covered in ```data_volumes```.

I mean the Data disk space allocation part.
When this is also possible, can you please give an example?

**Comment by outcatcher** [comment]
Sorry, got you wrong. I don't see such parameters in the documentation, I will clarify with CCE people if it's possible via the API.

**Comment by outcatcher** [comment]
API for that seems to be missing.
Internal incident created: https://jira.tsi-dev.otc-service.com/browse/OCS-4709

**Comment by outcatcher** [comment]
@sonic-martin 
Internal response: 
This is supported setting `docker_lvm_config_override` (API field `DockerLVMConfigOverride` described in [Node creation](https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0242.html)), e.g.:
`dockerThinpool=vgpaas/80%VG;kubernetesLV=vgpaas/10%VG;userLV=vgpaas/10%VG;userPath=/aaa;diskType=evs;lvType=linear`
has the following effect:
![image](https://user-images.githubusercontent.com/8591561/165905789-7fad923e-3f35-422a-81d1-ba67460c8dcf.png)

**Comment by Aloento** [comment]
OCS-4709 closed
CCE Node: data disk allocation via API (DM-3698) is about to be resolved.
If you have further questions, please reopen it.
