### ISSUE TITLE
RDS: Possibility to add database,users,roles for instances

### ISSUE THREAD

**Issue by greenbourne277** [opentelekomcloud/terraform-provider-opentelekomcloud#1513]
# Feature Request/ Question

After creating an database instance with the resource` opentelekomcloud_rds_instance_v3` I'm not able
to create **users**, **roles** or/and **databases** for this instance.
Instead, I have to connect manually to the database and execute `psql` commands (or equivalent) by hand or apply these changes with the help of a tool like `ansible`. That is opposite of what I want. I want to automate this procedure as much as possible. Other providers, like the one for the GCP, have resources for that. Why not the OTC cloud?
Maybe I just wasn't able to find that option in the documentation or there is a good reason that this is missing. If the later is the case, then I would ask to document this somewhere.

Best,
Christian

**Comment by outcatcher** [comment]
GCP has SQL admin APIs: https://cloud.google.com/sql/docs/mysql/admin-api/rest/v1beta4/users.
But right now Open Telekom Cloud doesn't have such APIs. 
I can create a feature request to add these APIs, but I'm not sure it will be implemented.

I suppose you can use database-specific providers (e.g.  [postgresql](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs)) to manage databases as a single terraform configuration.

**Comment by greenbourne277** [comment]
Thanks for your response. I will try out the specific provider and try to work it out that way.
I think that such a feature would be really beneficial :)

**Comment by chrkaatz** [comment]
Hey @outcatcher - I looked at the database specific provider but no option no create users.

@greenbourne277 did you find a solution to this?

**Comment by outcatcher** [comment]
@chrkaatz 
I suppose, if you take postgresql, respective resource is [postgresql_role](https://registry.terraform.io/providers/cyrilgdn/postgresql/latest/docs/resources/postgresql_role).

**Comment by chrkaatz** [comment]
I will try that, thx

**Comment by Aloento** [comment]
If you have further questions, please reopen it.
