### ISSUE TITLE
Deprecation warning unclear in opentelekomcloud_elb_loadbalancer

### ISSUE THREAD

**Issue by tvannahl** [opentelekomcloud/terraform-provider-opentelekomcloud#1519]
In the [opentelekomcloud_elb_loadbalancer](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/elb_loadbalancer) resource there is the following deprecation warning:

>  Classic load balancers are no longer provided. Please use elastic load balancers instead.

To me it is not clear which resources is supposed to replace `opentelekomcloud_elb_loadbalancer`. "elastic load balancer" sounds like elb to me which again points to the deprecated resource.

**Comment by outcatcher** [comment]
Unfortunately, it's also a mystery for us why LBv1 resources are named `opentelekomcloud_elb_...` while being classic load balancer and actual ELBv2 resources are named `opentelekomcloud_lb_...` (though the further makes more sense).
We will update resources documentation to add a reference to the exact resource which replaces the deprecated one :slightly_smiling_face:

**Comment by outcatcher** [comment]
New documentation will contain a link to a replacing v2 resource and have category `Classic Load Balancer (LB)`

**Comment by tvannahl** [comment]
Thank you, that does make it much more clear :heart:. Yeah  we did wounder about the `lb` vs `elb` naming difference as well.
