### ISSUE TITLE
Possibility to use terraform to automate icagent installation on CCE

### ISSUE THREAD

**Issue by canaykin** [opentelekomcloud/terraform-provider-opentelekomcloud#1534]
Greetings,

I would like to be able to install icagent on an autoscaling enabled CCE cluster. Previously, I was using the solution presented [here](https://support.huaweicloud.com/intl/en-us/usermanual-aom/aom_02_002301.html) to install icagent. Unfortunately I was unable to use the same method with CCE v1.19.8-r0. 

I was able to install the icagent via AOM in cloud console as explained in [docs](https://docs.otc.t-systems.com/usermanual/aom/aom_02_2012.html) and it went quite hassle free. It also supported the autoscaling fully and automatically made the installation on all new instances created by autoscaler.

If possible I believe it would be a really good addition to CCE to have the same capability via terraform.

Thank you very much in advance!

**Comment by lego963** [comment]
hi @canaykin,
Currently, this feature (I mean API) is under `evaluation` process. We are waiting for a responsible squad. I hope that it will be available soon. :)

Reference: #1285 

Demand link: https://jira.tsi-dev.otc-service.com/browse/DM-2913

**Comment by canaykin** [comment]
Thank you for the quick reply, I will be looking forward to it :)

**Comment by Aloento** [comment]
DM-2913 and #1285 closed
If you have further questions, please reopen it.

**Comment by anton-sidelnikov** [comment]
@Aloento https://jira.tsi-dev.otc-service.com/browse/DM-3635 still unresolved, why are you closed this issue?

**Comment by AdamVB** [comment]
you can request the installation of icagent during the cluster creation in the annotations field:


```
resource "opentelekomcloud_cce_cluster_v3" "cluster" {
  name        = "cluster"
  cluster_type           = "VirtualMachine"
  container_network_type = "overlay_l2"
  authentication_mode    = "rbac"
  flavor_id              = var.cluster_flavor_id
  vpc_id                 = opentelekomcloud_vpc_v1.vpc.id
  subnet_id              = opentelekomcloud_vpc_subnet_v1.subnet.id
  annotations = {
  "cluster.install.addons.external/install" = "[{\"addonTemplateName\":\"icagent\"}]"  }
}
```

**Comment by anton-sidelnikov** [comment]
Solution above
