### ISSUE TITLE
Possibility to set Advanced Kubernetes Settings for CCE

### ISSUE THREAD

**Issue by canaykin** [opentelekomcloud/terraform-provider-opentelekomcloud#1535]
Greetings,

One of the containers we are running requires over 10GB of space which made me notice the possibility to adjust the `Maximum Data Space per Container` parameter when creating a CCE cluster under `Advanced Kubernetes Settings`. Unfortunately, these options are not accessible via terraform and currently I am solving the issue by mounting extra ephemeral volumes to the pod with kustomize.

![advanced_k8s](https://user-images.githubusercontent.com/70644420/141811753-e97a9b41-14ba-4120-a1a0-53b484e89d83.jpg)

The api docs suggest an `extendedParam` field for CCE nodes where the `dockerBaseSize` parameter can be adjusted [cce_node_docs](https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0242.html) . This feature seems missing on the node pool resources so I am not entirely sure if the api supports the same option for node pool resources [cce_nodepool_docs](https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0354.html) .

Nevertheless, I believe the capability to manage these parameters via terraform would be a beneficial addition to the provider both for node resources and for node pool resources.

Thank you very much in advance.

**Comment by outcatcher** [comment]
We are missing `spec.extendedParam` argument. It needs to be added.
After that, it maybe will be possible to set `dockerBaseSize` parameter.
