### ISSUE TITLE
Acceptance: quotas `t.Cleanup` usage

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/terraform-provider-opentelekomcloud#1538]
Currently, acceptance tests use `defer` to release acquired quotas, but in case of failed or skipped tests, `defer` won't be executed.
The correct way to do something after the test is `t.Cleanup` usage.

**Comment by Aloento** [comment]
What else needs to be changed?

**Comment by outcatcher** [comment]
Issue assumes removing all `defer` usages in tests, at least, for quota usage.

**Comment by anton-sidelnikov** [comment]
Seems that we can close it now
