### ISSUE TITLE
[ECS] Server group is not applied to the server

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/terraform-provider-opentelekomcloud#1555]
# Terraform provider version
`v1.23.6`

# Affected Resource(s)
- `opentelekomcloud_compute_instance_v2`
- `opentelekomcloud_compute_servergroup_v2`

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_compute_servergroup_v2" "sg_1" {
  name     = "sg_1"
  policies = ["affinity"]
}

resource "opentelekomcloud_compute_instance_v2" "instance_1" {
  name            = "instance_1"
  security_groups = ["default"]
  network {
    uuid = data.opentelekomcloud_vpc_subnet_v1.shared_subnet.network_id
  }
  scheduler_hints {
    group = opentelekomcloud_compute_servergroup_v2.sg_1.id
  }
}
```

# Debug Output/Panic Output

# Steps to Reproduce

1. Run `TestAccComputeV2ServerGroup_affinity` acceptance test

# Actual Behavior

```
resource_opentelekomcloud_compute_servergroup_v2_test.go:66: Step 1/1 error: Check failed: Check 3/3 error: instance ea215f23-98d9-4a23-86ac-5bebbf1064b4 is not part of Server Group eb8fd373-4dc7-4aab-8e56-ab2e6901696b
```

# Important Factoids
Checked in the console: server is not assigned to the group too.

**Comment by artem-lifshits** [comment]
`affinity` policy was never supported for ECS group, this is a documentation bug.
