### ISSUE TITLE
[Network] All protocols are not allowed in rules

### ISSUE THREAD

**Issue by nash-sprd** [opentelekomcloud/terraform-provider-opentelekomcloud#1587]
I cannot create a Security Group `opentelekomcloud_compute_secgroup_v2` rule with `All` protocols.
I tried the `""`, `"All"`, `"ALL"`, `"all"`, `"*"`, `"-1"` and `-1`. I always get the same `400` error: Invalid IP protocol... .

When I create this rule in OTC and import it, I the resource is without an `ip_protocol` field, which in turn, prevents the resource from being  modified. (The argument "ip_protocol" is required, but no definition was found.)

**Comment by lego963** [comment]
@nash-sprd hi,
[API ](https://docs.otc.t-systems.com/en-us/api/ecs/en-us_topic_0065817703.html) for Compute SecGroup Rules are in `Discarded` state. I can suggest you to use `resource opentelekomcloud_networking_secgroup_rule_v2`
this example will create rule with `All` protocols.
```hcl
resource "opentelekomcloud_networking_secgroup_rule_v2" "secgroup_rule" {
  direction         = "ingress"
  ethertype         = "IPv4"
  security_group_id = opentelekomcloud_networking_secgroup_v2.secgroup.id
}
```
And you also can use our [secgroup module](https://registry.terraform.io/modules/terraform-opentelekomcloud-modules/security-group/opentelekomcloud/latest)


Ref: #1588

**Comment by nash-sprd** [comment]
Thanks for the tip. I will close the issue.
