### ISSUE TITLE
Secrurity group management via compute API should be deprecated

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/terraform-provider-opentelekomcloud#1588]
# Description of the enhancement
Security group compute APIs are marked as `discarded` in documentation:
https://docs.otc.t-systems.com/en-us/api/ecs/en-us_topic_0267427144.html

So we need to deprecate corresponding resources.

**Comment by lego963** [comment]
Resolved in https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/1594
