### ISSUE TITLE
[CCE autoscaler addon] Available parameters for autoscaler addon?

### ISSUE THREAD

**Issue by philippeckel** [opentelekomcloud/terraform-provider-opentelekomcloud#1589]
Hello,

I am trying to configure the autoscaler addon for CCE and I am wondering which arguments to it are possible but maybe are not documented i.e. [here](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/devel/opentelekomcloud/services/cce/addon-templates-v1.19.8.md)?

The official list of available parametes is [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-the-parameters-to-ca).

I was interested to get `skip-nodes-with-local-storage=false` which worked by using ` "skipNodesWithLocalStorage" : false`, but `skip-nodes-with-system-pods=false` by setting `skipNodesWithSystemPods=false` does not work. Changing the deployment manually with 
`skip-nodes-with-system-pods=false` works.

So how can other parameters be set for the autoscaler addon?

```hcl
resource "opentelekomcloud_cce_addon_v3" "autoscaling_addon" {
  template_name    = "autoscaler"
  template_version = "1.19.1"
  cluster_id       = opentelekomcloud_cce_cluster_v3.cluster.id
  values {
    basic = {
      "cceEndpoint" : "https://cce.eu-de.otc.t-systems.com",
      "ecsEndpoint" : "https://ecs.eu-de.otc.t-systems.com",
      "euleros_version" : "2.2.5",
      "region" : "eu-de",
      "swr_addr" : "100.125.7.25:20202",
      "swr_user" : "hwofficial"
    }
    custom = {
      "cluster_id" : opentelekomcloud_cce_cluster_v3.cluster.id,
      "tenant_id" : data.opentelekomcloud_identity_project_v3.project.id,
      "coresTotal" : 1000,
      "expander" : "priority",
      "logLevel" : 4,
      "maxEmptyBulkDeleteFlag" : 10,
      "maxNodeProvisionTime" : 15,
      "maxNodesTotal" : 1000,
      "memoryTotal" : 128000,
      "scaleDownDelayAfterAdd" : 10,
      "scaleDownDelayAfterDelete" : 10,
      "scaleDownDelayAfterFailure" : 3,
      "scaleDownEnabled" : true,
      "scaleDownUnneededTime" : 10,
      "scaleDownUtilizationThreshold" : 0.5,
      "scaleUpCpuUtilizationThreshold" : 1,
      "scaleUpMemUtilizationThreshold" : 1,
      "scaleUpUnscheduledPodEnabled" : true,
      "scaleUpUtilizationEnabled" : true,
      "unremovableNodeRecheckTimeout" : 5,
      "skipNodesWithLocalStorage" : false,
      "skipNodesWithSystemPods" : false <-- not working!
    }
  }
}
```

**Comment by lego963** [comment]
@philippeckel hi,
Sorry for delay, but I've tried to create an addon with this parameter, and it was successful. 
Maybe I didn't understand your issue. :(

**Comment by philippeckel** [comment]
@lego963 including `"skipNodesWithSystemPods" : false` ?

Yeah, the **creation** works with **any** parameter, but the question is if they're also taken over as CLI argument to cluster autoscaler.

**Comment by philippeckel** [comment]
Working now; therefore closing the issue.
