### ISSUE TITLE
KMSv1 unexpected state

### ISSUE THREAD

**Issue by greenbourne277** [opentelekomcloud/terraform-provider-opentelekomcloud#1604]
# Terraform provider version
Terraform v1.1.4
on linux_amd64

    provider registry.terraform.io/hashicorp/external v2.2.0
    provider registry.terraform.io/hashicorp/local v2.1.0
    provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.27.3

# Affected Resource(s)
opentelekomcloud_kms_key_v1

# Terraform Configuration Files

`main.tf`
```hcl
resource "opentelekomcloud_identity_project_v3" "projects" {
  for_each = local.projects
  name     = "${local.otc_region}_${each.value}"
  description = "Dedicated project space for ${each.value}"
}

resource "opentelekomcloud_s3_bucket" "tf_remote_states" {
  for_each = local.projects
  bucket   = "${each.value}-tfstate-bucket"
  acl      = "private"
  region   = local.otc_region
  versioning {
    enabled = true
  }
}

resource "opentelekomcloud_kms_key_v1" "bucket_kms_keys" {
  for_each        = opentelekomcloud_s3_bucket.tf_remote_states
  key_alias       = "${each.value.bucket}-key"
  key_description = "${each.value.bucket} encryption key"
  pending_days    = 7
  is_enabled      = "true"
}
```

`variables.tf`
```hcl
locals {
  otc_domain_name = "OTC0000000000XXXXXXXXX"
  otc_tenant_name = "eu-nl"
  otc_region = "eu-nl"
  projects = toset([
    "dev-nl",
    "tools-nl",
    ])
}
```

# Debug Output/Panic Output

https://gist.github.com/greenbourne277/3176eab1834761ecd97fb536bfe2ba53

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

Terraform should be able to create the KMS key.
# Actual Behavior

Key creation failed with unexpected state.
Following error message appears:

```
╷
│ Error: error waiting for key (097242d6-fae5-4663-96e5-d795e421eb8b) to become ready: unexpected state '4', wanted target '2'. last error: %!s(<nil>)
│
│   with opentelekomcloud_kms_key_v1.bucket_kms_keys["tools-nl"],
│   on main.tf line 17, in resource "opentelekomcloud_kms_key_v1" "bucket_kms_keys":
│   17: resource "opentelekomcloud_kms_key_v1" "bucket_kms_keys" {
│
╵
╷
│ Error: error waiting for key (75e2f1e4-cc66-4821-a6e2-f25417c72c63) to become ready: unexpected state '4', wanted target '2'. last error: %!s(<nil>)
│
│   with opentelekomcloud_kms_key_v1.bucket_kms_keys["dev-nl"],
│   on main.tf line 17, in resource "opentelekomcloud_kms_key_v1" "bucket_kms_keys":
│   17: resource "opentelekomcloud_kms_key_v1" "bucket_kms_keys" {
│
```

-> KMS key can't be be created
-> The error message is not displayed correctly

# Important Factoids
Same Terraform code works for DE. Trying to the same setup on NL.

# References

**Comment by philippeckel** [comment]
Same problem here, but the keys are created before but apparently do not seem to be "ready" for being used to encrypt buckets.

**Comment by outcatcher** [comment]
@greenbourne277 I face the same error when creating a KMS key with the same name as a key in the `Pending Delete` state.
This includes re-running `apply` after the `destroy`.

We can change the logic so deletion will be canceled in this case, but I'm not sure it's a secure approach.

**Comment by greenbourne277** [comment]
@outcatcher Thanks for the answer. It worked for me when i created the key for the first time, after destroying it and creating it again this error occured. I should have mentioned it in the first place, sorry for that. After changing the `key_alias` property of the key it works now. Can I enforce the deletion of the keys somewhere? I guess it's on `Pending Delete` for over 5 days now because i still can't use the original key alias.

Best,
Christian

**Comment by outcatcher** [comment]
@greenbourne277 The minimal value for deletion is 7 days, I wasn't able to find a way to delete them earlier. But you can generate random key aliases, as far as I remember, a key quota is quite high.

**Comment by greenbourne277** [comment]
Ah ok the 7 days are new to me. Thanks that explains it. Then I guess it is not a bug and more like expected behavior. Shall I close the ticket?

**Comment by greenbourne277** [comment]
Maybe the error message could be more specific? And `last error: %!s(<nil>)` shouldn't be part of the output as well I guess.

**Comment by lego963** [comment]
@greenbourne277 this `last error: %!s(<nil>)` has come from terraform wait mechanism. We can't change it in provider
