### ISSUE TITLE
CES: Alarm Rule shows Insufficient Data when using multiple dimensions 

### ISSUE THREAD

**Issue by 0xd3e** [opentelekomcloud/terraform-provider-opentelekomcloud#1605]
# Terraform provider version

Terraform v1.0.11
on darwin_amd64

# Affected Resource(s)

- opentelekomcloud_ces_alarmrule

# Terraform Configuration Files
```hcl
locals {
  node_count = var.architecture == "replicaset" ? 3 : 1
  nodes = {
    for i in range(local.node_count) : format("mongodb%02s", i + 1) => {
      availability_zone = var.availability_zones[i % length(var.availability_zones)]
    }
  }
}

resource "opentelekomcloud_ces_alarmrule" "cpu_critical" {
  alarm_name           = "MongoDB_${title(var.identifier)}_CPU_Usage_Critical"
  alarm_description    = "The CPU usage is over 80% since 15 minutes."
  alarm_level          = 1
  alarm_enabled        = true
  alarm_action_enabled = true

  dynamic "metric" {
    # Nested dynamic block didn't work without using for_each here too.
    for_each = {"unused" = local.nodes}
    content {
      namespace = "SYS.ECS"
      metric_name = "cpu_util"

      dynamic "dimensions" {
        for_each = metric.value
        content {
          name  = "instance_id"
          value = opentelekomcloud_compute_instance_v2.node[dimensions.key].id
        }
      }
    }
  }

  condition {
    period              = 300
    filter              = "average"
    comparison_operator = ">"
    value               = 80
    unit                = "percent"
    count               = 3
  }

  alarm_actions {
    type              = "notification"
    notification_list = [var.alerting_topic_urn]
  }

  ok_actions {
    type              = "notification"
    notification_list = [var.alerting_topic_urn]
  }
}
```

# Debug Output/Panic Output

# Steps to Reproduce

1. create a alarm rule using opentelekomcloud_ces_alarmrule with 3 dimensions
2. check the alarm rule in OTC console
3. alarm rule status should be "Insufficient data"
4. create alarm rule manually by selecting the same 3 resources
5. check manually created alarm rule
6. alarm rule should show "OK" or "Alarm"

# Expected Behavior

Alarm rule should be created and show status OK or Alarm

# Actual Behavior

Alarm rule was created but shows status "Insufficient data"

# Important Factoids

# References

**Comment by outcatcher** [comment]
This is a CES service problem. The following internal incidents were created:
https://jira.tsi-dev.otc-service.com/browse/XAAS-10354
https://jira.tsi-dev.otc-service.com/browse/XAAS-10355
https://jira.tsi-dev.otc-service.com/browse/XAAS-10357

**Comment by Aloento** [comment]
XAAS-10354 / XAAS-10355 / XAAS-10357 closed

**Comment by Aloento** [comment]
New tracking
https://jira.tsi-dev.otc-service.com/browse/OTCORC-511
https://jira.tsi-dev.otc-service.com/browse/OTCORC-650
https://jira.tsi-dev.otc-service.com/browse/OTCORC-660

**Comment by artem-lifshits** [comment]
Hello @0x1DA117 looks like issue has been fixed, can you recheck please?

I was able to create alarm rule with 3 dimensions and status is ``enabled`` in OTC console.

**Comment by 0xd3e** [comment]
Hi thanks for your work and the information that the issue has been fixed.
Currently I'm working on a different project, so I cannot recheck.

Since you were able to create the rule correctly I'd suggest to close the issue.
