### ISSUE TITLE
ECS Flavor s3.xlarge.1 is abandoned

### ISSUE THREAD

**Issue by mokhos** [opentelekomcloud/terraform-provider-opentelekomcloud#1606]
# Terraform provider version
v1.1.3

# Affected Resource(s)
- opentelekomcloud_compute_instance_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_compute_instance_v2" "ecs_1" {
  region            = var.region
  availability_zone = var.availability_zone
  name              = "${var.ecs_name}-${random_id.ecs.id}"
  image_id          = var.image_id
  #flavor_name         = "s3.large.8" # 2 vCPU,  8G RAM
  flavor_id = "s3.xlarge.1" #--> doesn't work. There is no reference
  #key_pair        = var.key_name
  # security_groups = [var.security_groups]
  security_groups   = [opentelekomcloud_compute_secgroup_v2.secgroup_1.id]
  network {
    uuid = module.vpc.network_id
  }
  #tag = {
  #   key1 = "value1"
  #   key2 = "value2"
  #  }
}
```

# Debug Output/Panic Output
```
Error: error creating OpenTelekomCloud server: Bad request with: [POST https://ecs.eu-de.otc.t-systems.com/v2.1/a552a15264d94569b9135d7941d1defb/servers], error message: {"error":{"message":"Flavor s3.xlarge.1 is abandoned","code":"Ecs.0019"}}
```

# Steps to Reproduce
1. `terraform apply`

# Expected Behavior
ECS resource to be created.

# Actual Behavior
Flavor x.x.x is abandoned

# References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/compute_instance_v2
- https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/devel/examples/basic-examples/modules/ecs/main.tf

Hi Folks. So I'm trying to create an ECS resource with terraform provider, but every flavor_id (or flavor_name) that I use, I get the error above.

P.S: Actually the provider has so many bugs. Are there going to be an upgrade for the provider any time soon?!

**Comment by outcatcher** [comment]
@mokhos 
The following configuration works for me just fine:
```
# base infra
data "opentelekomcloud_images_image_v2" "image" {
  name = "Standard_Debian_10_latest"
}

resource "opentelekomcloud_vpc_v1" "vpc" {
  cidr = "192.168.0.0/16"
  name = "test-vpc"
}

resource "opentelekomcloud_vpc_subnet_v1" "subnet" {
  cidr       = "192.168.0.0/16"
  gateway_ip = cidrhost("192.168.0.0/16", 1)
  name       = "test-sn"
  vpc_id     = opentelekomcloud_vpc_v1.vpc.id
}

# server

resource "opentelekomcloud_compute_instance_v2" "ecs_1" {
  name              = "test-ecs"
  image_id          = data.opentelekomcloud_images_image_v2.image.id
  flavor_id = "s3.xlarge.1"
  security_groups   = []
  network {
    uuid = opentelekomcloud_vpc_subnet_v1.subnet.id
  }
}

```
Can you clarify which region and AZ are you using? This can be a region-specific issue.


Please report the exact bugs you face to GitHub. We still have a long way to fix the provider. Especially, the documentation and examples. Reporting problems will help us to fix issues the users face.

**Comment by mokhos** [comment]
@outcatcher 
Thanks for getting back to me. 

I'm using "eu-de" as region and "random" for my AZ.

**Comment by outcatcher** [comment]
It seems, `random` AZ is the reason here, it works for any exact AZ set.

**Comment by mokhos** [comment]
Thank you @outcatcher 
That was exactly the problem.

**Comment by outcatcher** [comment]
I will create an internal incident for that, maybe it will be fixed in the future.

**Comment by outcatcher** [comment]
Internal incident created:
https://jira.tsi-dev.otc-service.com/browse/OCS-5220

**Comment by outcatcher** [comment]
Response from the internal issue about the `random` AZ:
`Such parameter doesn't exist on API and therefore it should not be used. It's only existing in the UI Console.`
