### ISSUE TITLE
CTS - No resource for specification of Key Event Notifications

### ISSUE THREAD

**Issue by pwurbs** [opentelekomcloud/terraform-provider-opentelekomcloud#1608]
# Terraform provider version
1.27.3

# Affected Resource(s)
opentelekomcloud_cts_tracker_v1

# Expected Behavior
In OTC, there is the configuration panel for "Key Event Notifications", which allows for fine granular event notification configuration.
I miss a corresponding resource in OTC Terraform provider.

# Actual Behavior
Within opentelekomcloud_cts_tracker_v1, event notifications can only be configured very roughly.
So, the fine granular configuration must be done manually in the OTC UI.

Is it a bug or an intentionally missed feature? Or have I overseen something?

**Comment by outcatcher** [comment]
We are limited in configuration by the parameters the API provides:
https://docs.otc.t-systems.com/en-us/api/cts/en-us_topic_0168602251.html
The only part we can implement now is `lts`, as it's missing from the resource.

**Comment by pwurbs** [comment]
This is unfortunately true. The lts functions doesn't help to solve my requirement.
