### ISSUE TITLE
NL: Creating ELB fails with API error

### ISSUE THREAD

**Issue by greenbourne277** [opentelekomcloud/terraform-provider-opentelekomcloud#1612]
# Terraform provider version

```
provider registry.terraform.io/hashicorp/external v2.2.0
provider registry.terraform.io/hashicorp/local v2.1.0
provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.27.3
```

# Affected Resource(s)
- opentelekomcloud_lb_loadbalancer_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_lb_loadbalancer_v2" "elb" {
  name          = "elb_${var.context_name}_${var.stage_name}"
  description   = "ELB for project ${var.context_name} (${var.stage_name})"
  vip_subnet_id = var.subnet_id
}
```

# Debug Output/Panic Output
```
╷
│ Error: error creating LoadBalancer: Resource not found: [POST https://elb.eu-nl.otc.t-systems.com//v2.0/lbaas/loadbalancers], error message: {"error_msg":"The API does not exist or has not been published in the environment","error_code
":"APIGW.0101","request_id":"d1819922eb43e3f43085cb2eb04180e0"}
│
│
│   with module.loadbalancer.opentelekomcloud_lb_loadbalancer_v2.elb,
│   on ../../modules/loadbalancer/main.tf line 1, in resource "opentelekomcloud_lb_loadbalancer_v2" "elb":
│    1: resource "opentelekomcloud_lb_loadbalancer_v2" "elb" {
│
```
GIST: https://gist.github.com/greenbourne277/60a6d0a0a4f3ed92cf91a29aa2215432

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior
The ELB will be created without any errors.

# Actual Behavior

The ELB can not be created due to problems reaching an API
# Important Factoids

This terraform code ran for me in DE a few months ago and I did not change it.
Is v2 the issue here? Should I use v3 instead?

# References

**Comment by lego963** [comment]
@greenbourne277 can you try to use v3? We can't guarantee that v2 will be enabled in the nearest future.

**Comment by greenbourne277** [comment]
v3 seems to work :+1:
