### ISSUE TITLE
Cannot Bind EIP to ECS instance

### ISSUE THREAD

**Issue by mokhos** [opentelekomcloud/terraform-provider-opentelekomcloud#1613]
Hi.
So I'm trying to create an ECS instance and connect to it through remote-exec provisioner. The Public IP is being created and passed to the ECS through the "floatingip_associate_v2" resource, but actually no IP is bound to the instance. 
Am I doing something wrong?

# Terraform provider version
1.1.3

# Affected Resource(s)

- opentelekomcloud_compute_instance_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_compute_instance_v2" "ecs_1" {
  region            = var.region
  availability_zone = var.ecs_az
  name              = "${var.ecs_name}-${random_id.ecs.id}"
  image_id          = data.opentelekomcloud_images_image_v2.ubuntu.id
  flavor_id = "s2.large.4" #--> doesn't work with "Random" AZ
  key_pair        = opentelekomcloud_compute_keypair_v2.quickstart_ssh_key.name  
  security_groups   = [opentelekomcloud_networking_secgroup_v2.rke-server-secgroup.id]
  network {
    uuid = module.vpc.network_id
  }
  provisioner "remote-exec" {
    inline = [
      "echo 'Waiting for cloud-init to complete...'",
      "cloud-init status --wait > /dev/null",
      "echo 'Completed cloud-init!'",
    ]

    connection {
      type        = "ssh"
      host        = opentelekomcloud_networking_floatingip_v2.floatip_1.address
      user        = local.node_username
      private_key = tls_private_key.global_key.private_key_pem
    }
  }
}

# Create Public IP 
resource "opentelekomcloud_networking_floatingip_v2" "floatip_1" {
  pool = "admin_external_net"
}

resource "opentelekomcloud_compute_floatingip_associate_v2" "fip_2" {
  floating_ip = opentelekomcloud_networking_floatingip_v2.floatip_1.address
  instance_id = opentelekomcloud_compute_instance_v2.ecs_1.id
}
```

# Debug Output/Panic Output
```
 Error: remote-exec provisioner error
 
   with opentelekomcloud_compute_instance_v2.ecs_1,
   on infra.tf line 93, in resource "opentelekomcloud_compute_instance_v2" "ecs_1":
   93:   provisioner "remote-exec" {
 
 timeout - last error: dial tcp x.x.x.x:22: i/o timeout
```

# Steps to Reproduce
1. `terraform apply`

# Expected Behavior
EIP to be bound to the ECS instance and "connection" section works.

# Actual Behavior
Timeout, because EIP is not bound to ECS instance.

# References

**Comment by lego963** [comment]
@mokhos can you try something like this?

```hcl
data "opentelekomcloud_vpc_subnet_v1" "this" {
  name = var.subnet_name
}

resource "tls_private_key" "this" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "opentelekomcloud_compute_keypair_v2" "this" {
  name       = var.environment
  public_key = tls_private_key.this.public_key_openssh
}

resource "opentelekomcloud_compute_instance_v2" "this" {
  region            = var.region
  availability_zone = var.az
  name              = var.environment
  image_id          = var.debian_image_id
  flavor_id         = "s2.large.4" #--> doesn't work with "Random" AZ
  key_pair          = opentelekomcloud_compute_keypair_v2.this.name
  network {
    uuid = data.opentelekomcloud_vpc_subnet_v1.this.network_id
  }
}

# Create Public IP 
resource "opentelekomcloud_networking_floatingip_v2" "this" {
  pool = "admin_external_net"
}

resource "opentelekomcloud_compute_floatingip_associate_v2" "this" {
  floating_ip = opentelekomcloud_networking_floatingip_v2.this.address
  instance_id = opentelekomcloud_compute_instance_v2.this.id
}


resource "null_resource" "this" {
  provisioner "remote-exec" {
    inline = [
      "echo 'Waiting for cloud-init to complete...'",
      "cloud-init status --wait > /dev/null",
      "echo 'Completed cloud-init!'",
    ]

    connection {
      type        = "ssh"
      host        = opentelekomcloud_networking_floatingip_v2.this.address
      user        = "linux"
      private_key = tls_private_key.this.private_key_pem
    }
  }

  depends_on = [
    opentelekomcloud_compute_floatingip_associate_v2.this
  ]
}
```

**Comment by mokhos** [comment]
@lego963 
Thanks for your help. 
That actually worked. But then the consistency of the code is somehow broken. So basically what I'm doing is that I'm trying to use rancher official repository and install it on my otc k8s cluster. So for the first time the ECS will be created and then IP will be bound to it. The next time I'm trying to destroy the infra, the EIP is gone sooner than other resources are removed. I hope  my explanations are clear.

Is it actually OK to define the remote-exec outside of its resource as a separate resource?

**Comment by outcatcher** [comment]
@mokhos The problem is, you can't connect to the ECS until it's created and has IP assigned, but a provisioner is triggered after ECS is created, without waiting for IP assignment.
It's better to use [`user_data`](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/compute_instance_v2#instance-with-user-data-cloud-init) for passing cloud-init file.
Terraform documentation [marks](https://www.terraform.io/language/resources/provisioners/syntax#how-to-use-provisioners) provisioners as a last resort:
```
Provisioners should only be used as a last resort. For most common situations there are better alternatives. For more information, see the sections above.
```

**Comment by lego963** [comment]
@mokhos this is ok from my side and https://github.com/hashicorp/terraform-provider-aws/issues/5525#issuecomment-413191520

**Comment by mokhos** [comment]
@lego963 @outcatcher 
Thanks.
I'll close the issue for now.
