### ISSUE TITLE
Migrating lb_v2 to lb_v3 no outbound traffic

### ISSUE THREAD

**Issue by greenbourne277** [opentelekomcloud/terraform-provider-opentelekomcloud#1614]
# Terraform provider version

```
provider registry.terraform.io/hashicorp/external v2.2.0
provider registry.terraform.io/hashicorp/local v2.1.0
provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.27.3
```

# Affected Resource(s)
- opentelekomcloud_lb_loadbalancer_v3

# Terraform Configuration Files

## Old Loadbalancer V2 (working)
```hcl
resource "opentelekomcloud_lb_loadbalancer_v2" "elb" {
  name          = "elb_${var.context_name}_${var.stage_name}"
  description   = "ELB for project ${var.context_name} (${var.stage_name})"
  vip_subnet_id = var.subnet_id
}

resource "opentelekomcloud_vpc_eip_v1" "ingress_eip" {
  bandwidth {
    charge_mode = "traffic"
    name        = "${var.stage_name}-${var.context_name}-ingress-bandwidth"
    share_type  = "PER"
    size        = var.bandwidth
  }
  publicip {
    type    = "5_bgp"
    port_id = opentelekomcloud_lb_loadbalancer_v2.elb.vip_port_id
  }
}
```

## New loadbalancer v3 (not working)
```hcl
resource "opentelekomcloud_lb_loadbalancer_v3" "elbv3" {
  name          = "elbv3_${var.context_name}_${var.stage_name}"
  description   = "ELB for project ${var.context_name} (${var.stage_name})"
  subnet_id     = var.subnet_id
  network_ids   = [var.network_id]
  availability_zones = [var.availability_zone]

  public_ip {
    ip_type        = "5_bgp"
    bandwidth_charge_mode = "traffic"
    bandwidth_name = "${var.stage_name}-${var.context_name}-ingress-bandwidth"
    bandwidth_size  = var.bandwidth
    bandwidth_share_type = "PER"
  }
}
```

# Expected Behavior

**lb_loadbalancer_v3** should be able to reach to internet.

# Actual Behavior

[Here](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1612) it was recommended to use
`lb_loadbalancer_v3` in the netherlands. I set it up as above and am not able to reach the internet anymore from ECS that are part of that subnet. 
Using the v2 in DE works and binding my server to another EIP also works.
Am I using v3 wrong? 
I triple checked any differences in the UI between the working version in DE and NL. The only difference I could spot was,
that the EIP has under **Associated Instance** no **Subnet** or **NIC** listed and only the **VPC** (see attachments).

# Important Factoids

# References

![Screenshot_20220131_165657](https://user-images.githubusercontent.com/82470038/151833210-7a6367d7-49ad-4b27-b5cb-590d81a22846.png)
![Screenshot_20220131_172526](https://user-images.githubusercontent.com/82470038/151833217-3ed3a674-8248-4e43-85e3-964f6d390195.png)

**Comment by lego963** [comment]
@greenbourne277 we are investigating the issue. 

UPD: Can you share full terraform config file?

**Comment by greenbourne277** [comment]
@lego963:

Module loadbalancer_v3: https://gist.github.com/greenbourne277/f8dcf9a13ceba1937d72c64d08c8198b

Code that includes the loadbalancer: https://gist.github.com/greenbourne277/5e0fa4e2857e9c1753e4506f66630587

**Comment by greenbourne277** [comment]
@lego963 
And here a gist with the usage of loadbalancer_v2 (the rest of the files are the same): https://gist.github.com/greenbourne277/3bc73f5e3ddb6f298d043f4f1c9ee5fd

**Comment by lego963** [comment]
@greenbourne277 do you want to have access from ECS to internet through ELB with the public ip?

**Comment by greenbourne277** [comment]
I think so.
I have a CCE, which is part of a subnet. The ECS, that are part of the CCE, should be able to access the internet through the ELB with the public ip.

**Comment by philippeckel** [comment]
@greenbourne277 I'd say you need a [NAT Gateway](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/nat_gateway_v2) and an [EIP](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/vpc_eip_v1) connected to it.

If using the NAT Gateway, be aware to set `spec` as low as possible, because `3` is already getting quite expensive ...

**Comment by greenbourne277** [comment]
@philippeckel Thanks, I try that if I don't get it running otherwise. The setup in DE does not have a NAT Gateway. So this shouldn't be the reason why it is not working in NL.

**Comment by lego963** [comment]
@greenbourne277 the only possibility to have outbound traffic in `EU-NL` is to use `NAT` or `Elastic IP`. The problem is not with ELB versions. There is a difference between the two regions. `EU-DE` VPCs has shared SNAT, `EU-NL` hasn't. :( 
That's why you can't have outbound traffic with the same infrastructure.
