### ISSUE TITLE
Using modules in main.tf doesn't work!

### ISSUE THREAD

**Issue by mokhos** [opentelekomcloud/terraform-provider-opentelekomcloud#1615]
Hi folks. As titles says, use of modules in my code doesn't work. I used modules as defined in the examples page, but for no good reason, terraform is looking to download the "hashicorp/opentelekomcloud" instead of "opentelekomcloud/opentelekomcloud" provider. The result for command "terraform providers" is also like so:

```
Providers required by configuration:
.
├── provider[registry.terraform.io/opentelekomcloud/opentelekomcloud] 1.27.3
├── module.cce
│   └── provider[registry.terraform.io/hashicorp/opentelekomcloud]
└── module.vpc_subnets
    ├── provider[registry.terraform.io/hashicorp/random]
    └── provider[registry.terraform.io/hashicorp/opentelekomcloud]
```
Thanks in advance for your help.

# Terraform provider version
1.1.3

# Affected Resource(s)
- All

# Terraform Configuration Files
```hcl
module "vpc_subnets" {
  source             = "./modules/vpc_subnet"
  vpc_name           = var.vpc_name
  vpc_cidr           = var.vpc_cidr
  subnet_name1       = var.subnet_name1
  subnet_cidr1       = var.subnet_cidr1
  subnet_gateway_ip1 = var.subnet_gateway_ip1
  primary_dns        = var.primary_dns
  secondary_dns      = var.secondary_dns
  subnet_name2       = var.subnet_name2
  subnet_cidr2       = var.subnet_cidr2
  subnet_gateway_ip2 = var.subnet_gateway_ip2
}

module "cce" {
  source = "./modules/cce"
  cce_name      = var.cce_name
  cce_type      = var.cce_type
  cce_node_name = var.cce_node_name
  vpc_id        = module.vpc_subnets.vpc_id
  key_name      = var.key_name
  subnet_id     = module.vpc_subnets.subnet1_id
}
```

# Debug Output/Panic Output
```
 Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/opentelekomcloud: provider registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/opentelekomcloud
│ 
│ Did you intend to use opentelekomcloud/opentelekomcloud? If so, you must specify that source address in each module which requires that provider. To see which
│ modules are currently depending on hashicorp/opentelekomcloud, run the following command:
│     terraform providers
```

# Steps to Reproduce
1. `terraform init`

# Expected Behavior
Terraform init to download all the dependencies for opentelekomcloud/opentelekomcloud provider.

# Actual Behavior
Looking for "hashicorp/opentelekomcloud" provider.

# References
- https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/tree/devel/examples/basic-examples

**Comment by outcatcher** [comment]
This is not an OTC provider issue.

Please check the terraform documentation:
https://www.terraform.io/language/providers/requirements#requiring-providers

Note that the provider should be defined in each module, while the provider configuration is inherited by the child modules.
