### ISSUE TITLE
ECS - Add support for key-value Tags

### ISSUE THREAD

**Issue by gunzl1ng3r** [opentelekomcloud/terraform-provider-opentelekomcloud#162]
Hi all,

as of now the provider does not support 2D / key-value tags.

I have taken a look at the providers source code to figure out, which changes would be required.

The file `resource_opentelekomcloud_instance_v2.go` makes the call, and input validation would have to be changed to somethin like this:

```
"tags": &schema.Schema{
  Type:     schema.TypeSet,
  Optional: true,
  Elem:     &schema.Resource{
    Schema: map[string]*schema.Schema{
      "key": &schema.Schema{
        Type:     schema.TypeString,
        Required: true,
      },
      "value": &schema.Schema{
        Type:     schema.TypeString,
        Required: true,
      },
    },
  },
},
```

Unfortunately, to support 2D tags `github.com/huaweicloud/golangsdk/openstack/compute/v2/extensions/tags` needs to be changed too - and I am unsure about backwards-compatibility.

This would be the part to change in order to represent the new format:
```
// CreateOpts implements CreateOptsBuilder
type CreateOpts struct {
	// Tags is a set of tags.
	Tags []string `json:"tags" required:"true"`
}
```

Probably to something like this:
```
type CreateOpts struct {
  Tags []struct {
    Key   int    `json:"key"`
    Value string `json:"value"`
  } `json:"tags"`
}
```

But that would break compatibility and I don't know if anything else relies on this.

**Comment by niuzhenguo** [comment]
@gunzl1ng3r I'm already working on this, but yes there's a concern about the backwards-compatibility :(

**Comment by niuzhenguo** [comment]
@gunzl1ng3r we added a new `tag` field and deprecated the `tags` to keep backwards-compatibility. The key-value tag is same with blockstorage volume's as below:
```
tag {
    key = value
    foo = bar
}
```

**Comment by niuzhenguo** [comment]
Closing this, and please help to test if the new instance tag meet your request, thanks!

**Comment by gunzl1ng3r** [comment]
Hi, I just tested the implementation and can confirm that it works as expected using the mentioned syntax:

```
tag = {
    tag1="value1"
    tag2="value2"
}
```

Thank you very much
