### ISSUE TITLE
[IAM] Importing an agency

### ISSUE THREAD

**Issue by philippeckel** [opentelekomcloud/terraform-provider-opentelekomcloud#1625]
Hey,

importing an IAM agency is currently not in the provider. I am very aware of CCE requiring the agency in place :-)

We've create many clusters right now and do not want to manually click the permissions again. We could revoke the agency in IAM manually, use `opentelekomcloud_identity_agency_v3` to create it again with all the projects. 

But I am pretty sure that this would "break" CCE for a short time, so new nodes could not be spawned etc.

So ideally we should be able to import the existing ageny. Could this feature be provided?

Thanks, 
Philipp

**Comment by lego963** [comment]
@philippeckel hiho, we support agency import in current release. Can you try to use it? However, we didn't have this in doc. I will update it.

**Comment by philippeckel** [comment]
@lego963 thanks; we will check!
