### ISSUE TITLE
Typo in API request for creating ELB in eu-nl region 

### ISSUE THREAD

**Issue by 5RK7N** [opentelekomcloud/terraform-provider-opentelekomcloud#1630]
# Terraform provider version
Terraform v1.0.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/vault v2.23.0
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.27.4

# Affected Resource(s)
- opentelekomcloud_lb_loadbalancer_v2

# Debug Output/Panic Output
`Error: error creating LoadBalancer: Resource not found: [POST https://elb.eu-nl.otc.t-systems.com//v2.0/lbaas/loadbalancers], error message: {"error_msg":"The API does not exist or has not been published in the environment","error_code":"APIGW.0101","request_id":""}`

# Steps to Reproduce
`terraform apply -target=opentelekomcloud_lb_loadbalancer_v2.elb`

# Expected Behavior
It should create an ELB

# Actual Behavior
Error returns "API does not exist". 

# Important Factoids
There is a double slash in the API call: `https://elb.eu-nl.otc.t-systems.com//v2.0/lbaas/loadbalancers`, which is not in eu-de region: `https://elb.eu-de.otc.t-systems.com/v2.0/lbaas/loadbalancers`

**Comment by lego963** [comment]
Already done in: https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/1617

PS: 
We **don't recommend** using ELBv2 in EU-NL. Please use ELBv3.
