### ISSUE TITLE
opentelekomcloud_identity_project_v3 data source to return provider's project by default

### ISSUE THREAD

**Issue by canaykin** [opentelekomcloud/terraform-provider-opentelekomcloud#1633]
# Description of the enhancement
Greetings, 
While working on a reusable CCE module today I required to obtain the `project_id` of the provider configuration. This made me notice that a blank data source call to project is not possible to obtain "current project" of the provider.

I believe it would be beneficial to use an empty data call to return the project attributes of the provider's project configuration (essentially calling the data source on `tenant_name`).
```hcl
data "opentelekomcloud_identity_project_v3" "project" {} 
```
would imply
```hcl
data "opentelekomcloud_identity_project_v3" "project" {
  domain_id = provider.domain_id
  name = provider.tenant_name
}
```

Thank you very much in advance and have a great day!

**Comment by vladimirvshivkov** [comment]
resolved in https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/1665
