### ISSUE TITLE
IAM - Identity Provider creation Forbidden

### ISSUE THREAD

**Issue by kgeroczi** [opentelekomcloud/terraform-provider-opentelekomcloud#1641]
Hello,

I'm trying to create a new IdP via Terraform, but just getting Forbidden messages.

# Terraform provider version
- Installed opentelekomcloud/opentelekomcloud v1.27.6 (self-signed, key ID 3EDA0171114F71DF)

# Affected Resource(s)
- opentelekomcloud_identity_provider_v3
- opentelekomcloud_identity_mapping_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_identity_provider_v3" "provider" {
  name        = "TestIdP123"
  description = "Some text..."
  enabled     = true
}

resource "opentelekomcloud_identity_mapping_v3" "mapping" {
  mapping_id = "TestIdP123"
  rules      = file("./saml_mapping.json")
}

resource "opentelekomcloud_identity_protocol_v3" "saml" {
  protocol    = "saml"
  provider_id = opentelekomcloud_identity_provider_v3.provider.id
  mapping_id  = opentelekomcloud_identity_mapping_v3.mapping.id

  metadata {
    domain_id = "OTC-EU-DE-000000000010000123456"
    metadata  = file("keycloak_saml.xml")
  }
}

```

# Debug Output/Panic Output
```
| Error: error creating identity provider v3: Action Forbidden, error message: {"error": {"message": "Policy doesn't allow iam:identityProviders:createIdentityProvider to be performed.", "code": 403, "title": "Forbidden"}}
│ 
│   with opentelekomcloud_identity_provider_v3.provider,
│   on idp.tf line 1, in resource "opentelekomcloud_identity_provider_v3" "provider":
│    1: resource "opentelekomcloud_identity_provider_v3" "provider" {
│ 
╵
╷
│ Error: error creating identity mapping v3: Action Forbidden, error message: {"error": {"message": "Policy doesn't allow iam:identityProviders:createMapping to be performed.", "code": 403, "title": "Forbidden"}}
│ 
│   with opentelekomcloud_identity_mapping_v3.mapping,
│   on idp.tf line 7, in resource "opentelekomcloud_identity_mapping_v3" "mapping":
│    7: resource "opentelekomcloud_identity_mapping_v3" "mapping" {
```

# Steps to Reproduce
1. `terraform apply`

# Expected Behavior
New IdP created with the configured mapping and metadata.

# Actual Behavior
Getting Forbidden error message instead of resource creation.

# Important Factoids
The used API user is in the default "admins" group and also part of a new "secu" group with global permission "Security Administrator"
This user is a programmatic user and can do anything else, just this is not working.

# References
Not found

**Comment by kgeroczi** [comment]
Any update?

**Comment by outcatcher** [comment]
Sorry for a long response. Currently under investigation.

**Comment by kgeroczi** [comment]
Hello,

It seems we found out the problem.

After getting a different error message for an other Identity v3 resource we were realised that we have to use domain_name in the provider configuration. (https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs#domain_name):
(Optional) The Name of the Domain to scope to (Identity v3).

Since it was just Optional it was not configured.

BTW it's still strange, that the error message is Forbidden, but for the other resource it was clearly the missing domain_name, so after we configured it properly it started to working right.

**Comment by outcatcher** [comment]
@kgeroczi Domain ID/Name is optional in terms of the provider configuration (it can be empty and still work, e.g. taking configurations from `clouds.yaml`). 
We need to add this validation on our side to avoid such obscure issues.

**Comment by outcatcher** [comment]
@kgeroczi Hi, can you please clarify, what kind of credentials have you used, AK/SK, token, or plain username/password?

**Comment by outcatcher** [comment]
Requires user feedback to be implemented
