### ISSUE TITLE
[CCE] kubeconfig as an output attribute 

### ISSUE THREAD

**Issue by chrkaatz** [opentelekomcloud/terraform-provider-opentelekomcloud#1644]
# Description of the enhancement

It would be handy to have the possibility to safe a given kubeconfig during cluster creation as an output, that it could be used for further process automation like kubectl.

**Comment by philippeckel** [comment]
@chrkaatz it's already in the provider, but just in parts and you have to build a `kubeconfig` yourself.

See the attributes reference [here](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cce_cluster_v3#certificate_clusters/name).

We're using [Jsonnet](https://jsonnet.org/) and some scripting to build a `kubeconfig` ourselves via this template:

```
{
    kind :  "Config" ,
    apiVersion :  "v1" ,
    preferences : {},
    clusters : [
        {
            name :  "otc-" +std.extVar('environment') ,
            cluster : {
                "server" :  "https://" +std.extVar('cluster_eip_address') +":5443",
                "certificate-authority-data" : std.extVar('certificate_authority_data')
            }
        }
    ],
    users : [
        {
            name :  "user",
            user : {
                "client-certificate-data" :  std.extVar('client_certificate_data'),
                "client-key-data" :  std.extVar('client_key_data')
            }
        }
    ],
    contexts : [
        {
            name :  "otc-" +std.extVar('environment') ,
            context : {
                cluster :  "otc-" +std.extVar('environment') ,
                user :  "user"
            }
        }
    ],
    "current-context" :  "otc-" +std.extVar('environment')
}
```

**Comment by lego963** [comment]
Implemented here https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/1649
