### ISSUE TITLE
opentelekomcloud_lb_loadbalancer_v3 is not functioning on any region

### ISSUE THREAD

**Issue by canaykin** [opentelekomcloud/terraform-provider-opentelekomcloud#1645]
# Terraform provider version
provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.27.6

# Affected Resource(s)
- opentelekomcloud_lb_loadbalancer_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_lb_loadbalancer_v3" "elb_v3_test" {
  name        = "elb_v3_test_lb"
  subnet_id   = values(module.vpc.subnets)[0].subnet_id
  network_ids = [values(module.vpc.subnets)[0].id]

  availability_zones = var.availability_zones

  public_ip {
    bandwidth_name       = "elb_v3_test_lb_bw"
    ip_type              = "5_bgp"
    bandwidth_size       = 100
    bandwidth_share_type = "PER"
  }
}
```

# Debug Output/Panic Output
```
opentelekomcloud_lb_loadbalancer_v3.elb_v3_test: Creating...
2022-03-08T11:01:45.202+0100 [INFO]  Starting apply for opentelekomcloud_lb_loadbalancer_v3.elb_v3_test
2022-03-08T11:01:45.203+0100 [DEBUG] opentelekomcloud_lb_loadbalancer_v3.elb_v3_test: applying the planned Create change
2022-03-08T11:01:45.207+0100 [ERROR] vertex "opentelekomcloud_lb_loadbalancer_v3.elb_v3_test" error: No suitable endpoint could be found in the service catalog.

│ Error: No suitable endpoint could be found in the service catalog.
│ 
│   with opentelekomcloud_lb_loadbalancer_v3.elb_v3_test,
│   on main.tf line 16, in resource "opentelekomcloud_lb_loadbalancer_v3" "elb_v3_test":
│   16: resource "opentelekomcloud_lb_loadbalancer_v3" "elb_v3_test" {
│ 

```

# Steps to Reproduce
1. add  `opentelekomcloud_lb_loadbalancer_v3` resource
1. `terraform apply`

# Important Factoids
- The problem exists for both eu-nl and eu-de regions.
- The API endpoint as documented in [docs](https://docs.otc.t-systems.com/api/elb/elb_dx_0000.html) is reachable from outside but has a different syntax compared to v2 API. 
- I was able to confirm API reachability (via token authentication) using Postman to GET https://elb.eu-de.otc.t-systems.com/v3/{project_id}/elb/loadbalancers 

Thank you very much in advance. :+1:

**Comment by outcatcher** [comment]
@canaykin I've tried to reproduce it, but it's broken currently only of `eu-de`. It's missing from service endpoint catalog in that region.

**Comment by canaykin** [comment]
@outcatcher You are correct, it was a bug in my code which made it fall back to default provider configuration at `eu-de` rather than using `eu-nl`. I can confirm that `eu-nl` works as expected.

**Comment by outcatcher** [comment]
We will update service catalog for that. This is not bind to the provider milestone ― I will close this issue when service catalog will be updated.

**Comment by outcatcher** [comment]
@canaykin 

Endpoint added to the service catalog:
```shell
$ os endpoint list --service elbv3
+----------------------------------+--------+--------------+--------------+---------+-----------+------------------------------------------------------+
| ID                               | Region | Service Name | Service Type | Enabled | Interface | URL                                                  |
+----------------------------------+--------+--------------+--------------+---------+-----------+------------------------------------------------------+
| 1f4fd5a285784a958c05c011829b4ef9 | eu-de  | elbv3        | elbv3        | True    | public    | https://elb.eu-de.otc.t-systems.com/v3/$(tenant_id)s |
| 6e669834c4034bc4805956d9e1585a46 | eu-nl  | elbv3        | elbv3        | True    | public    | https://elb.eu-nl.otc.t-systems.com/v3/$(tenant_id)s |
+----------------------------------+--------+--------------+--------------+---------+-----------+------------------------------------------------------+
```

Acceptance tests for LB creation passes:
```
=== RUN   TestAccLBV3LoadBalancer_basic
=== PAUSE TestAccLBV3LoadBalancer_basic
=== CONT  TestAccLBV3LoadBalancer_basic
--- PASS: TestAccLBV3LoadBalancer_basic (78.23s)
PASS

Process finished with the exit code 0
```
Please note that it's recommended to use `5_gray` EIPs for the v3 load balancers in `eu-de` region.
Also, for some reason creation of ELBv3 within `eu-de-03` zone fails with message `"Cannot allocate resource for the loadbalancer."`, this zone is also unavailable for LB creation on the console.
