### ISSUE TITLE
WAF Domain and Policy association is broken

### ISSUE THREAD

**Issue by canaykin** [opentelekomcloud/terraform-provider-opentelekomcloud#1650]
# Terraform provider version
provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.27.6

# Affected Resource(s)
- opentelekomcloud_waf_domain_v1
- opentelekomcloud_waf_policy_v1

# Terraform Configuration Files
- Binding on the domain side:
```hcl
resource "opentelekomcloud_waf_certificate_v1" "certificate" {
  for_each = var.subdomains

  name    = replace(each.key, ".", "_")
  content = "${acme_certificate.certificate[each.key].certificate_pem}${acme_certificate.certificate[each.key].issuer_pem}"
  key     = acme_certificate.certificate[each.key].private_key_pem
}


resource "opentelekomcloud_waf_domain_v1" "domain" {
  for_each = var.subdomains

  hostname = each.key
  server {
    client_protocol = "HTTPS"
    server_protocol = "HTTPS"
    address         = each.value
    port            = "443"
  }
  policy_id      = opentelekomcloud_waf_policy_v1.policy
  certificate_id = opentelekomcloud_waf_certificate_v1.certificate[each.key].id
  proxy          = false
}

resource "opentelekomcloud_dns_recordset_v2" "waf" {
  for_each = var.subdomains

  zone_id     = var.dns_zone_id
  name        = "${each.key}."
  description = "CNAME for ${each.key} WAF."
  ttl         = 3000
  type        = "CNAME"
  records     = ["${opentelekomcloud_waf_domain_v1.domain[each.key].cname}."]
}

resource "opentelekomcloud_waf_policy_v1" "policy" {
  name = var.waf_policy_name
  options {
    webattack       = true
    common          = true
    crawler         = true
    crawler_scanner = true
    cc              = true
    custom          = true
    whiteblackip    = true
    privacy         = true
    ignore          = true
    antitamper      = true
  }
  action {
    category = "block"
  }
  full_detection = false
}
```

- Alternatively, binding on the policy side::

```hcl
resource "opentelekomcloud_waf_certificate_v1" "certificate" {
  for_each = var.subdomains

  name    = replace(each.key, ".", "_")
  content = "${acme_certificate.certificate[each.key].certificate_pem}${acme_certificate.certificate[each.key].issuer_pem}"
  key     = acme_certificate.certificate[each.key].private_key_pem
}


resource "opentelekomcloud_waf_domain_v1" "domain" {
  for_each = var.subdomains

  hostname = each.key
  server {
    client_protocol = "HTTPS"
    server_protocol = "HTTPS"
    address         = each.value
    port            = "443"
  }
  certificate_id = opentelekomcloud_waf_certificate_v1.certificate[each.key].id
  proxy          = false
}

resource "opentelekomcloud_dns_recordset_v2" "waf" {
  for_each = var.subdomains

  zone_id     = var.dns_zone_id
  name        = "${each.key}."
  description = "CNAME for ${each.key} WAF."
  ttl         = 3000
  type        = "CNAME"
  records     = ["${opentelekomcloud_waf_domain_v1.domain[each.key].cname}."]
}

resource "opentelekomcloud_waf_policy_v1" "policy" {
  name = var.waf_policy_name
  options {
    webattack       = true
    common          = true
    crawler         = true
    crawler_scanner = true
    cc              = true
    custom          = true
    whiteblackip    = true
    privacy         = true
    ignore          = true
    antitamper      = true
  }
  action {
    category = "block"
  }
  full_detection = false
  hosts       = [ for name, domain in  opentelekomcloud_waf_domain_v1.domain : domain.id ]
}
```

# Debug Output/Panic Output

```
│ Error: error updating OpenTelekomCloud WAF Policy Hosts: Bad request with: [PUT https://waf.eu-de.otc.t-systems.com/v1/2248debf19ef4739bd40b8c0204c495e/waf/policy/3ce123d75bae4e64a0520561029a2478/hosts], error message: {"error_msg": "The policy already bind this host","error_code":"WAF.3010"}
```

# Expected Behavior
The relation between domains and policies is N to 1. It is possible (according to API spec and OTC Console) to assign a policy to multiple domains.

# Actual Behavior
Terraform provider can only create the relation in 1 policy to 1 domain and will get an API error if a policy is assigned to more than one domain.

# Important Factoids
- It is interesting and unorthodox that the policy binding relation is defined on both `opentelekomcloud_waf_domain_v1` (via `policy_id`) and `opentelekomcloud_waf_policy_v1` (via `hosts`). 
- Trying to define it on both resources would result in a cyclic dependency.
- According to API docs, the domain creation, policy creation and domain-policy binding are different calls. 
- It might be a better approach to create a third resource to handle binding operation similar to IAM rolebinding.

**Comment by outcatcher** [comment]
I suppose, we should add new `associate` resource for that, same as for other resource.

**Comment by outcatcher** [comment]
@canaykin 
After some investigation:

1. The API we have allows only adding domain to the policy (https://docs.otc.t-systems.com/api/waf/waf_02_0032.html). There is no removal at all.
2. When you adding domain to another policy, it's being reassigned. That's the only way besides deletion to remove domain from a policy.
3. Passing empty domain list to our API it doesn't change anything (so the logic currently defined in the provider is incorrect)
4. `The policy already bind this host` error is shown when we're trying to apply policy to the domain already using this policy.
5. Domain creation automatically creates a policy, so the provider spams orphan policies, as they are not known and not being deleted.

As a result, I'm going to fix existing provider logic, including removal of auto-created policies, but not creating a new resource for now, as assignment workflow is too different from standard TF resource workflow. I would propose marking one of the ways of assignment (e.g. setting `policy_id` in the domain) deprecated, and removing it in future releases.

**Comment by outcatcher** [comment]
@canaykin Will it be okay for you if setting `policy_id` in domain will be the only valid way? It's easier to track orphan policies like that.

**Comment by canaykin** [comment]
@outcatcher I believe it makes sense. The only addition I would love to have to that is the deletion of the autocreated default policy if `policy_id` is specified during domain creation.

By default the new domain creation always causes a new default policy creation (where the domain creation API call returns the policy id). Perhaps the overhauling can include the change to automatically make a delete policy call for the newly created default policy if `policy_id` is not null.

**Comment by outcatcher** [comment]
@canaykin Okay, no problem :+1:
