### ISSUE TITLE
CSS cluster creation fails with "Resource not found"

### ISSUE THREAD

**Issue by mrgasparov** [opentelekomcloud/terraform-provider-opentelekomcloud#1657]
# Terraform provider version

registry.terraform.io/opentelekomcloud/opentelekomcloud v1.27.7

# Affected Resource(s)

opentelekomcloud_css_cluster_v1

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_css_cluster_v1" "central_elastic" {
  count            = var.central_elasticsearch == true ? 1 : 0
  name             = "${var.environment}-central-elastic"
  expect_node_num  = length(var.central_elastic_nodes)
  enable_authority = false
  enable_https     = false
  admin_pass       = random_password.central_elastic_password[0].result
  node_config {
    flavor = var.central_elastic_flavor
    network_info {
      security_group_id = opentelekomcloud_networking_secgroup_v2.central_elastic_security_group[0].id
      network_id        = data.terraform_remote_state.network.outputs.private_subnet_id
      vpc_id            = data.terraform_remote_state.network.outputs.vpc_id
    }
    volume {
      encryption_key = opentelekomcloud_kms_key_v1.central_elastic_kms[0].id
      volume_type    = "HIGH"
      size           = var.central_elastic_storage
    }
  }

  datastore {
    type    = "elasticsearch"
    version = "7.6.2"
  }
}
```
I'm omitting other dependents/dependencies because I don't think they are relevant for this particular issue.

# Debug Output/Panic Output

```
╷
│ Error: error creating CSS cluster: Resource not found: [POST https://css.eu-de.otc.t-systems.com/v1.0/xxx/clusters], error message: {"errCode":"CSS.0016","externalMessage":"CSS.0016 : Resource not found!"}
│ 
│   with opentelekomcloud_css_cluster_v1.central_elastic[0],
│   on central-elasticsearch.tf line 20, in resource "opentelekomcloud_css_cluster_v1" "central_elastic":
│   20: resource "opentelekomcloud_css_cluster_v1" "central_elastic" {
│ 
╵
```

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

CSS cluster should be created

# Actual Behavior

Cluster creation fails with error message: `{"errCode":"CSS.0016","externalMessage":"CSS.0016 : Resource not found!"}`

# Important Factoids

This functionality seems to be broken at the API level, as I cannot create new CSS clusters from the OTC console either.

# References

**Comment by mrgasparov** [comment]
Hi @outcatcher thanks for adding this issue to the `v1.27.9` milestone. In the meantime, is there any workaround to this issue that we can use in order to create a CSS cluster?

**Comment by outcatcher** [comment]
@mrgasparov I will check the issue today, and include in today's release, if possible :)

**Comment by outcatcher** [comment]
@mrgasparov 
I've started with running acceptance tests we have and they seems to be passing.
The following configuration is used:
```hcl
resource "opentelekomcloud_css_cluster_v1" "cluster" {
  expect_node_num = 1
  name            = "test-cluster"
  node_config {
    flavor = "css.medium.8"
    network_info {
      security_group_id = data.opentelekomcloud_networking_secgroup_v2.default_secgroup.id
      network_id        = data.opentelekomcloud_vpc_subnet_v1.shared_subnet.network_id
      vpc_id            = data.opentelekomcloud_vpc_subnet_v1.shared_subnet.vpc_id
    }
    volume {
      volume_type = "COMMON"
      size        = 40
    }

    availability_zone = "eu-de-03"
  }
  datastore {
    version = "7.6.2"
  }
  enable_https     = true
  enable_authority = true
  admin_pass       = "QwertyUI!"
}
```

Can you provide the POST request body? You can find it in logs running Terraform with env vars `TF_LOG=DEBUG OS_DEBUG=1`.

I will continue to investigate it further, but it's clear that it's working for some configurations at least.

**Comment by outcatcher** [comment]
@mrgasparov I wasn't able to reproduce it with my data. Can you check, if all resources used by the CCS cluster exist?
`{"errCode":"CSS.0016","externalMessage":"CSS.0016 : Resource not found!"}` seems like some dependency is not existing.

**Comment by mrgasparov** [comment]
Hi @outcatcher i got a reply from OTC saying there was an issue with the CSS backend which is fixed now, so I'm closing this ticket. Thanks a lot for your quick reply!
