### ISSUE TITLE
Tagging of opentelekomcloud_nat_gateway_v2

### ISSUE THREAD

**Issue by nfelger** [opentelekomcloud/terraform-provider-opentelekomcloud#1659]
# Terraform provider version
v1.27.7

# Affected Resource(s)
- opentelekomcloud_nat_gateway_v2

It seems I can tag NAT Gateways through the console but not via Terraform. Are there plans to support this? IMO, all resources that generate significant costs should be taggable for cost tracking in the financial dashboard.

**Comment by lego963** [comment]
@nfelger hiho,
We don't have API for tags :(
I can ask responsible squad about this feature.

**Comment by lego963** [comment]
@nfelger we've found a solution and we will implement in the `1.27.9` release

**Comment by nfelger** [comment]
Fantastic news! Thank you 😊
