### ISSUE TITLE
Documentation for transparent_client_ip_enable for opentelekomcloud_lb_listener_v2 in contradiction to OTC UI behavior

### ISSUE THREAD

**Issue by pwurbs** [opentelekomcloud/terraform-provider-opentelekomcloud#1663]
The provider version v1.27.7 added a new argument which supports the new ELB parameter "Obtain Client IP Address"

[ELB] Add SSL passthrough for lbv2 listener

In OTC UI the feature can be activated also for TCP listeners, but the resource documentation for "opentelekomcloud_lb_listener_v2" is as follows: 
[transparent_client_ip_enable]
(Optional) Specifies whether to pass source IP addresses of the clients to backend servers. The value can be true or false, and the default value is false for TCP and UDP listeners. **The value can only be true for HTTP and HTTPS listeners.**

So, the last statement is in contradiction to the behavior in the OTC UI. So either the documentation is wrong or the feature hasn't been implemented in a suited way.

**Comment by outcatcher** [comment]
SSL passthrough is always enabled for:

1. Dedicated Load Balancers (this is only v3 in case of `eu-de` region)
2. HTTP and HTTPS listeners

And it **CAN** be activated for TCP and UDP listeners on Shared Load Balancer. Just as  written in previous statement of the documentation: `The value can be true or false, and the default value is false for TCP and UDP listeners.`.

I suppose, the `The value can only be true for HTTP and HTTPS listeners.` part should be rephrased to make it more clear.

**Comment by pwurbs** [comment]
Yes only "The value can only be true for HTTP and HTTPS listeners." is misunderstandable.
