### ISSUE TITLE
Too many requests have been sent in a given amount of time. Pause requests, wait up to one minute, and try again.

### ISSUE THREAD

**Issue by eumel8** [opentelekomcloud/terraform-provider-opentelekomcloud#1671]
# Terraform provider version

% terraform -v
Terraform v1.1.3
on darwin_arm64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.27.2

# Affected Resource(s)

data.opentelekomcloud_images_image_v2.image-1
data.opentelekomcloud_images_image_v2.image-2
opentelekomcloud_compute_floatingip_associate_v2.wireguard[0]
opentelekomcloud_compute_instance_v2.k3s-server-1
opentelekomcloud_compute_instance_v2.k3s-server-2
opentelekomcloud_compute_instance_v2.wireguard[0]
opentelekomcloud_compute_keypair_v2.k3s-server-key
opentelekomcloud_dns_recordset_v2.public_record[0]
opentelekomcloud_dns_zone_v2.dns[0]
opentelekomcloud_lb_listener_v2.listener_443
opentelekomcloud_lb_listener_v2.listener_6443
opentelekomcloud_lb_listener_v2.listener_80
opentelekomcloud_lb_loadbalancer_v2.lb
opentelekomcloud_lb_member_v2.member_443_1
opentelekomcloud_lb_member_v2.member_6443_1
opentelekomcloud_lb_member_v2.member_80_1
opentelekomcloud_lb_member_v2.member_80_2
opentelekomcloud_lb_monitor_v2.monitor_443
opentelekomcloud_lb_monitor_v2.monitor_6443
opentelekomcloud_lb_monitor_v2.monitor_80
opentelekomcloud_lb_pool_v2.pool_443
opentelekomcloud_lb_pool_v2.pool_6443
opentelekomcloud_lb_pool_v2.pool_80
opentelekomcloud_networking_floatingip_v2.eip
opentelekomcloud_networking_floatingip_v2.wireguard[0]
opentelekomcloud_networking_secgroup_rule_v2.secgroup_rule
opentelekomcloud_networking_secgroup_rule_v2.sg_icmp_in[0]
opentelekomcloud_networking_secgroup_rule_v2.sg_k3s_10250_in
opentelekomcloud_networking_secgroup_rule_v2.sg_k3s_22_in_self[0]
opentelekomcloud_networking_secgroup_rule_v2.sg_k3s_443_in
opentelekomcloud_networking_secgroup_rule_v2.sg_k3s_443_in_self
opentelekomcloud_networking_secgroup_rule_v2.sg_k3s_6443_in
opentelekomcloud_networking_secgroup_rule_v2.sg_k3s_6443_in_self
opentelekomcloud_networking_secgroup_rule_v2.sg_k3s_80_in
opentelekomcloud_networking_secgroup_rule_v2.sg_k3s_8472_in
opentelekomcloud_networking_secgroup_rule_v2.sg_k3s_9796_in
opentelekomcloud_networking_secgroup_rule_v2.sg_k3s_all_out
opentelekomcloud_networking_secgroup_rule_v2.sg_wg_all_out[0]
opentelekomcloud_networking_secgroup_rule_v2.sg_wg_in[0]
opentelekomcloud_networking_secgroup_v2.k3s-server-secgroup
opentelekomcloud_networking_secgroup_v2.secgroup
opentelekomcloud_networking_secgroup_v2.wireguard-secgroup[0]
opentelekomcloud_rds_instance_v3.rds
opentelekomcloud_rds_parametergroup_v3.pg
opentelekomcloud_vpc_subnet_v1.subnet
opentelekomcloud_vpc_v1.vpc

(46 resources in state file)

# Debug Output/Panic Output

```shell
Too many requests have been sent in a given amount of time. Pause requests, wait up to one minute, and try again.
```

# Steps to Reproduce
1. `terraform apply`

# Expected Behavior

resource applied in one run

# Actual Behavior

Since few days I got very often this `too many request` failure from OTC API. It works after some minutes in a second run, but it's not very comfortable.  In fact this is not really a bug of the terraform-provider-opentelekomcloud. Maybe you have some hints or want to add something on documentation. `terraform apply -parallelism=1` might be helpful but slow down the whole deployment. I don't know any limits for API requests.

thx

**Comment by outcatcher** [comment]
It seems like a WAF throttling threshold, by default it should be 200 RPS, but depends on the service.
Terraform provider creates quite a lot of requests due to independence of authentication in resources (basically we issue the token quite often, at least once per resource). We should investigate how can we change that behaviour, but this will take time.

As a workaround we can add retires for the resource with longer wait times, so it will be possible to solve that problem setting higher `max_retries` value.

**Comment by outcatcher** [comment]
Also, maybe some higher parallelism will work? Like 3 or 5?

**Comment by eumel8** [comment]
thx @outcatcher for the reply. Yeah, that's a pretty new  behavior so something was changed on OTC. I think workarounds are enough available for  the moment and now comes the really work ;-)
Maybe a queuing of token requests might be a way for extend functionality. In fact for the mix of resources I use different service endpoints, so this can't be overloaded in a manner of using one API for all services. I will investigate this further to give you more information and what makes sense to work on.

**Comment by outcatcher** [comment]
We already done some steps to decrease client creation reusing existing client where possible even without thinking about potential throttling problem. Though it was done as part of common refactoring we do when making improvements or bug fixes, not as a standalone task. If possible, can you please attach you full configuration so we will be able to use it as a benchmark :smile: 

I've also created a milestone to track future throttling-related tasks (not sure if it's a valid way to use milestones though).

**Comment by eumel8** [comment]
The full configuration is here:https://github.com/eumel8/tf-k3s-otc
The full set deploy 3 ECS while 2 are behind an ELB with 3 listener. It breaks very often on the same resource:

```
╷
│ Error: error creating member: Too many requests have been sent in a given amount of time. Pause requests, wait up to one minute, and try again.
│ 
│   with opentelekomcloud_lb_member_v2.member_443_1,
│   on main.tf line 122, in resource "opentelekomcloud_lb_member_v2" "member_443_1":
│  122: resource "opentelekomcloud_lb_member_v2" "member_443_1" {
│ 
╵
2022-03-24T08:36:15.867+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2022-03-24T08:36:15.870+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/opentelekomcloud/opentelekomcloud/1.27.2/darwin_arm64/terraform-provider-opentelekomcloud_v1.27.2 pid=17734
2022-03-24T08:36:15.870+0100 [DEBUG] provider: plugin exited
```

No addional information in DEBUG/TRACE which headed me to the IAM endpoint and the token thing. This is not covered by OS_DEBUG log in [gophertelekomcloud](https://github.com/opentelekomcloud/gophertelekomcloud/) I had some [providerclient debug ](https://github.com/eumel8/otc-rds-client/blob/unittests/provider_client.go.patch)on my RDS client some days ago.

**Comment by outcatcher** [comment]
@eumel8 That's a good point, I see at least one potential problem at LB member creation that can lead to "too many requests"

**Comment by outcatcher** [comment]
Fixes for ELB member will be a part of v1.28.2 release today

**Comment by eumel8** [comment]
@outcatcher tested multiple times and works now without any errors.  many thanks, we might be close the ticket

**Comment by outcatcher** [comment]
@eumel8 It should fail though if you increase number of the used resources, I suppose :slightly_smiling_face:  Fell free to comment here I you will face throttling again, or just create a new issue.
