### ISSUE TITLE
Creating v3 loadbalancer fails with "API not found"

### ISSUE THREAD

**Issue by mazw77** [opentelekomcloud/terraform-provider-opentelekomcloud#1673]
# Terraform provider version
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.28.1

# Affected Resource(s)
- opentelekomcloud_lb_loadbalancer_v3

# Terraform Configuration Files
```
resource "opentelekomcloud_lb_loadbalancer_v3" "elb" {
  name          = "${var.project}-elb"
  description   = "ELB for project ${var.project})"
  // vip_subnet_id = opentelekomcloud_vpc_subnet_v1.terraform.subnet_id
  subnet_id   = opentelekomcloud_vpc_subnet_v1.terraform.subnet_id
  network_ids = [opentelekomcloud_vpc_subnet_v1.terraform.network_id]
  availability_zones = [var.availability_zone]
}

resource "opentelekomcloud_lb_listener_v3" "listener_1" {
  protocol        = "HTTP"
  protocol_port   = 8080
  loadbalancer_id = opentelekomcloud_lb_loadbalancer_v3.elb.id

  tags = {
    muh = "kuh"
  }
}
resource "opentelekomcloud_lb_pool_v3" "pool_1" {
  protocol    = "HTTP"
  lb_algorithm   = "ROUND_ROBIN"
  listener_id = opentelekomcloud_lb_listener_v3.listener_1.id

  session_persistence {
    type                = "SOURCE_IP"
    persistence_timeout = "30"
  }
}
resource "opentelekomcloud_lb_member_v3" "member1" {
  address       = opentelekomcloud_compute_instance_v2.terraform.network[0].fixed_ip_v4
  protocol_port = 8080
  pool_id       = opentelekomcloud_lb_pool_v3.pool_1.id
  subnet_id     = opentelekomcloud_vpc_subnet_v1.terraform.subnet_id
}
resource "opentelekomcloud_vpc_eip_v1" "ingress_eip" {
  bandwidth {
    charge_mode = "traffic"
    name        = "${var.project}-ingress-bandwidth"
    share_type  = "PER"
    size        = var.bandwidth
  }
  publicip {
    type    = "5_bgp"
    port_id = opentelekomcloud_lb_loadbalancer_v3.elb.vip_port_id
  }
}

output "elb_id" {
  value = opentelekomcloud_lb_loadbalancer_v3.elb.id
}

output "elb_public_ip" {
  value = opentelekomcloud_vpc_eip_v1.ingress_eip.publicip[0].ip_address
}
```

# Debug Output/Panic Output
│ Error: error creating LoadBalancerV3: Resource not found: [POST https://elb.eu-de.otc.t-systems.com/v3/f13df91e2b6a46b4af19871815692e54/elb/loadbalancers], error message: {"message":"API not found","request_id":"44f6bcf65a0b6d9373137c350acd2c98"}
│
│
│   with opentelekomcloud_lb_loadbalancer_v3.elb,
│   on main.tf line 68, in resource "opentelekomcloud_lb_loadbalancer_v3" "elb":
│   68: resource "opentelekomcloud_lb_loadbalancer_v3" "elb" {

# Steps to Reproduce
1. `terraform apply`

# Expected Behavior
A load-balancer should be created.

# Actual Behavior
Execution fails with above error message: "API not found"

# Important Factoids
Same problem with v2 loadbalancer

# References

**Comment by outcatcher** [comment]
@mazw77 I wasn't able to reproduce it.

Can you please show the output of the following commands:
```shell
$ nslookup elb.eu-de.otc.t-systems.com
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
Name:	elb.eu-de.otc.t-systems.com
Address: 80.158.48.32

$ nslookup elb.eu-de.otc.t-systems.com 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	elb.eu-de.otc.t-systems.com
Address: 80.158.48.32

```

**Comment by mazw77** [comment]
nslookup gives me some T-Systems internal IPs with 10.x.x.x.
I do not like to post this internal information here.
Please contact me T-Systems internally, see WebEx chat.

**Comment by mazw77** [comment]
OK. I had to overwrite /etc/hosts with above public IP address.
Then the request is working.

**Comment by outcatcher** [comment]
@mazw77 It's common problem when using internal T-Sys VPNs :smile: they have problems with DNS servers.
