### ISSUE TITLE
[Provider] Implement in-provider FQDN resolution

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/terraform-provider-opentelekomcloud#1674]
# Description of the enhancement
When using the provider with some VPN, it's a common problem to get DNS-related issues, e.g. #1673, #1499, #1468

Proposed solution: resolve FQDN inside of the provider. To avoid certain firewall restrictions it makes sense to use DoH, e.g. [google DoH](https://developers.google.com/speed/public-dns/docs/doh)

**Comment by outcatcher** [comment]
Current implementation of Go http resolver don't allow overriding system configuration on Windows: https://github.com/golang/go/issues/33097

**Comment by Aloento** [comment]
https://github.com/golang/go/issues/33097 closed and merged
@outcatcher
