### ISSUE TITLE
In block_device use image-name instead of image-id

### ISSUE THREAD

**Issue by ebal** [opentelekomcloud/terraform-provider-opentelekomcloud#1679]
When the latest image is being updated in OTC (eg. Standard_Ubuntu_20.04_latest) , the image-id of the image changes to the new image id (as it should).

In the block-device section, I see only the image-id reference - thus making the above change to break tf plan, first destroy previous image and then failing to create the new one.

I was wondering if it is possible to use image-name in the block_device section instead of image-id as it is already a possibility in ecs (compute instance) section.

thank you

```yaml
  block_device {
    name                  = "<image-name>"       <---- proposal
    source_type           = "image"
    volume_size           = 5
    boot_index            = 0
    destination_type      = "volume"
    delete_on_termination = true
    volume_type           = "SSD"
  }
```

**Comment by lego963** [comment]
@ebal, as a temporary solution you can use `ignore_changes` block
https://www.terraform.io/language/meta-arguments/lifecycle#ignore_changes

**Comment by ebal** [comment]
@lego963 I'll try it, thanks.

It would be great though to use reference names instead of hard-copied uuid in tf files.

**Comment by lego963** [comment]
@ebal you can use image data_source in order to forget about hard-copy :)
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/data-sources/images_image_v2

**Comment by ebal** [comment]
Very nice tip. Thanks worked :+1:

**Comment by ebal** [comment]
The data source of opentelekomcloud_images_image_v2 is working for me. if you feel this feature request does not provide any further value, feel free to close this ticket. I am pretty happy with the image data source.

**Comment by lego963** [comment]
@ebal thanks for response. If you have any additional questions, feel free to ask :)
