### ISSUE TITLE
How to import opentelekomcloud_lb_member_v2 ?

### ISSUE THREAD

**Issue by ebal** [opentelekomcloud/terraform-provider-opentelekomcloud#1683]
Hi,

I am not sure if this is the correct place to ask this question so plz excuse me if not. I am trying to import a current OTC infra to a local state and seems that I can not import the opentelekomcloud_lb_member_v2 resources. Is there a way or a workaround ?

```bash
 Error: resource opentelekomcloud_lb_member_v2 doesn't support import
│
```

thanks in advance.

**Comment by outcatcher** [comment]
This functionality to be added

**Comment by ebal** [comment]
okay, thank you
