### ISSUE TITLE
How to bind EIPs to ELBs

### ISSUE THREAD

**Issue by simonszu** [opentelekomcloud/terraform-provider-opentelekomcloud#1700]
After an ELB is created in the console, it is possible to bind an External IP to that instance so that requests from the internet to that IP address are load balanced to the various services. I am unable to find any documentation how to do that in terraform. Is that even possible? 

If this is not possible by design, i could need some information how i should load balance between several CCE router nodes which will do all ingress traffic to the CCE.

**Comment by outcatcher** [comment]
Sorry for the late response. If I've understood you correctly, you need `opentelekomcloud_lb_member_v3` resource.

Example of the  `opentelekomcloud_lb_member_v3` usage:
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_member_v3#example-usage

Example of ELBv3 with floating IP:
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_loadbalancer_v3#public-load-balancer-with-floating-ip

**Comment by simonszu** [comment]
I managed it. Thanks.
