### ISSUE TITLE
Creating opentelekomcloud_obs_bucket fails with error

### ISSUE THREAD

**Issue by kocsvin** [opentelekomcloud/terraform-provider-opentelekomcloud#1701]
# Terraform provider version

Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.29.0

# Affected Resource(s)

opentelekomcloud_obs_bucket

# Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
provider "opentelekomcloud" {
  # access_key  = var.access_key
  # secret_key  = var.secret_key
  user_name   = var.otc_user
  password    = var.otc_password
  domain_name = "OTC-EU-DE-00000000001000013609"
  tenant_name = "eu-de"
  auth_url    = "https://iam.eu-de.otc.t-systems.com/v3"
}

terraform {
   required_providers {
      opentelekomcloud = {
         source = "opentelekomcloud/opentelekomcloud"
         version = ">= 1.29.0"
      }
   }
}

#  variable "access_key" {
#   description = "The access key used to connect to OTC"
#   sensitive = true
# }


# variable "secret_key" { 
#   description = "The secret key used to connect to OTC"
#   sensitive = true
# }

variable "otc_user" {
  description = "Username used to connect to the otc"
  sensitive = true
}

variable "otc_password" {
  description = "Password used to connect to the otc"
  sensitive = true
}

resource "opentelekomcloud_obs_bucket" "b" {
  bucket = "my-tf-test-bucket-vkocsis"
  acl    = "private"

  tags = {
    foo = "bar"
    Env = "Test"
  }
}

```

# Debug Output/Panic Output

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior
obs bucket resource is created without error

# Actual Behavior
process ends unsuccessfuly with error message: 
error creating bucket my-tf-test-bucket-vkocsis: InvalidArgument,
│  Reason: Unsupported Authorization Type

# Important Factoids
I have tried authorization via access key + secret key , and username + passoword. Both ends up with same error. Other resources can be created without error

# References

**Comment by outcatcher** [comment]
After clarification: seems to be related to #1674

**Comment by outcatcher** [comment]
DNS-related, waiting for language feature to be available: 
https://go-review.googlesource.com/c/go/+/400654/

**Comment by Aloento** [comment]
go feature was reverted: https://go-review.googlesource.com/c/go/+/401754
so it still can't be implemented to be working with windows
