### ISSUE TITLE
"masters" attribute is always empty for opentelekomcloud_dns_zone_v2 public zone

### ISSUE THREAD

**Issue by kbechler** [opentelekomcloud/terraform-provider-opentelekomcloud#1703]
# Terraform provider version
`Terraform v1.1.7`

# Affected Resource(s)
`opentelekomcloud_dns_zone_v2`

# Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 0.15.0, < 2.0"
  required_providers {
    opentelekomcloud = {
      source  = "opentelekomcloud/opentelekomcloud"
      version = "= 1.29.1"
    }
  }
}

provider "opentelekomcloud" {
  tenant_name = "eu-de"
  auth_url    = "https://iam.eu-de.otc.t-systems.com/v3"
}

resource "opentelekomcloud_dns_zone_v2" "this" {
  name = "some.domain.tld."
  type = "public"
}

output "masters" { value = opentelekomcloud_dns_zone_v2.this.masters }
```

# Steps to Reproduce
`terraform apply`

# Expected Behavior
I should see a list of NS servers for newly created zone

# What actually happened?
Empty output:
`
masters = toset([])
`

# Important Factoids
API allows getting name servers for a public zone:

[https://docs.otc.t-systems.com/en-us/api/dns/dns_api_62004.html,](https://docs.otc.t-systems.com/en-us/api/dns/dns_api_62004.html)

**Comment by lego963** [comment]
@kbechler as I can see description in hc doc 
```
Master DNS servers, from which the slave servers get DNS information
This parameter is not used currently.
```
`nameserver` is another attribute

**Comment by outcatcher** [comment]
I suppose, as there is `masters` attribute in API documentation (not working), it's better to use `name_servers` attribute or dedicated data source for getting list of the name servers for the zone with the following API: https://docs.otc.t-systems.com/en-us/api/dns/dns_api_62004.html

**Comment by vladimirvshivkov** [comment]
@kbechler We might return a list of nameservers? But in this case, there may be not only master servers. 
Will this be acceptable for you?

**Comment by kbechler** [comment]
@vladimirvshivkov My goal is to automate the process of adding new zone. If it will be a valid list of nameservers that could be used to configure NS delegation in parent zone, if will be acceptable for me.

On the other hand, maybe such variable should be called "nameservers", not "masters" as the latter one would be confusing.

**Comment by outcatcher** [comment]
Implementing as `masters` requires API changes

**Comment by vladimirvshivkov** [comment]
@kbechler 
We released a new version with DNS nameservers data source.

try to use this config:
```
terraform {
  required_version = ">= 0.15.0, < 2.0"
  required_providers {
    opentelekomcloud = {
      source  = "opentelekomcloud/opentelekomcloud"
      version = "= 1.29.2"
    }
  }
}

provider "opentelekomcloud" {
  tenant_name = "eu-de"
  auth_url    = "https://iam.eu-de.otc.t-systems.com/v3"
}

resource "opentelekomcloud_dns_zone_v2" "zone_1" {
  name        = "test-zone-1.com."
  email       = "email1@example.com"
  description = "a public zone"
  ttl         = 3000
  type        = "public"
}

data "opentelekomcloud_dns_nameservers_v2" "nameservers" {
  zone_id = opentelekomcloud_dns_zone_v2.zone_1.id
}

output "masters" { value = data.opentelekomcloud_dns_nameservers_v2.nameservers }
```

this outputs the following:

```
masters = {
  "id" = "ns1.open-telekom-cloud.com."
  "nameservers" = tolist([
    {
      "hostname" = "ns1.open-telekom-cloud.com."
      "priority" = 1
    },
    {
      "hostname" = "ns2.open-telekom-cloud.com."
      "priority" = 2
    },
  ])
  "zone_id" = "ff80808275f5fc0f01806ba10ea62b11"
}
```

Can't wait for your feedback!

**Comment by vladimirvshivkov** [comment]
@kbechler,
If this is still relevant for you, reopen the issue, please.
