### ISSUE TITLE
DNS: Retrieve nameservers

### ISSUE THREAD

**Issue by Nils-Magnus** [opentelekomcloud/terraform-provider-opentelekomcloud#1704]
# DNS: Feature request for retrieving nameservers of DNS zones

Albeit the nameservers for the Open Telekom Cloud are currently effectively static, they could theoretically change in the future. There's an [API call](https://docs.otc.t-systems.com/en-us/api/dns/dns_api_62004.html) to retrieve the NS records for a zone.
    
So, it would be nice to have this feature in the Terraform provider.

**Comment by vladimirvshivkov** [comment]
Related to #1703
