### ISSUE TITLE
Wrong API URL call for CCE 

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#1705]
Hey, we have the problem that this Error is shown when we Create an CCE.
Error: error creating OpenTelekomCloud CCE Node: Resource not found: [GET https://cce.eu-de.otc.t-systems.com/api/v3/projects/#####/clusters/########/nodes/], error message: {"error_msg":"The API does not exist or has not been published in the environment","error_code":"APIGW.0101","request_id":"###########"}
The Problem is the last /
So it shut be https://cce.eu-de.otc.t-systems.com/api/v3/projects/$Project_ID/clusters/$ClusterID/nodes not https://cce.eu-de.otc.t-systems.com/api/v3/projects/$Project_ID/clusters/$ClusterID/nodes/
It was the Terraform Provider opentelekomcloud/opentelekomcloud versions "1.29.1" used

Affected Resource:
opentelekomcloud_cce_node_v3

The used config is:
```

resource "opentelekomcloud_cce_cluster_v3" "cluster" {
  name                   = "###-dev"
  cluster_type           = "VirtualMachine"
  cluster_version        = "v1.19.10-r0"
  flavor_id              = "cce.s1.small"

  vpc_id                 = opentelekomcloud_vpc_v1.main.id
  subnet_id              = opentelekomcloud_vpc_subnet_v1.private.id
  container_network_type = "vpc-router"
  eip                    = opentelekomcloud_vpc_eip_v1.cluster.publicip[0].ip_address

  labels = {
    Env  = var.env-name
  }
}

resource "opentelekomcloud_cce_node_v3" "node" {
  count             = 3
  name              = "####-dev-node-${count.index}"
  cluster_id        = opentelekomcloud_cce_cluster_v3.cluster.id
  availability_zone = "eu-de-01"

  flavor_id         = "s2.xlarge.4"
  key_pair          = opentelekomcloud_compute_keypair_v2.generic.id

  root_volume {
    size       = 40
    volumetype = "SATA"
  }

  data_volumes {
    size       = 100
    volumetype = "SATA"
  }

  tags = {
    Env  = var.env-name
  }
}

```

**Comment by outcatcher** [comment]
The last `/` seems to be meaning that there should be ID of the node after it. The problem seems to be that ID of the node is not set.

**Comment by arkadiusjonczek** [comment]
Hi @outcatcher !

Do you know why the ID of the node is not set?

Error using #1706 Bugfix:
```
module.foobar.module.kubernetes-cluster-1.opentelekomcloud_cce_node_v3.node-az1[1]: Creating...
module.foobar.module.kubernetes-cluster-1.opentelekomcloud_cce_node_v3.node-az1[0]: Creating...
module.foobar.module.kubernetes-cluster-1.opentelekomcloud_cce_node_v3.node-az1[2]: Creating...
module.foobar.module.kubernetes-cluster-1.opentelekomcloud_cce_node_v3.node-az1[1]: Still creating... [10s elapsed]
module.foobar.module.kubernetes-cluster-1.opentelekomcloud_cce_node_v3.node-az1[0]: Still creating... [10s elapsed]
module.foobar.module.kubernetes-cluster-1.opentelekomcloud_cce_node_v3.node-az1[2]: Still creating... [10s elapsed]
Error: can't find node ID in job response
Job 7451f7c0-c195-11ec-93ab-xxxxxxxxxx in status "Initializing":
Reason: 
Message: 
```

Is this a problem in the API of the opentelekomcloud?

Best regards,
Arkadius

**Comment by outcatcher** [comment]
@arkadiusjonczek That's exactly what I'm trying to find out :) #1706 Is not actually fix, but more a diagnosis helper.
Thanks to your comment, now it's clear that we have job in status `Initializing` without `CreateNodeVM` sub-job containing node ID. Seems we need to wait for a job to get in `Running` state.

**Comment by arkadiusjonczek** [comment]
@outcatcher sounds like you're on the right track. Let me know if can help you.

https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/7e11bafb61492fa96794ad078a5298f6ac855403/opentelekomcloud/services/cce/resource_opentelekomcloud_cce_node_v3.go#L556
Do you think the first index (=0) is always the right subJob?

**Comment by outcatcher** [comment]
It should be, as there is only one node created per operation: `count` in create node request (not to be confused with TF `count` argument) is always set to `1`.
