### ISSUE TITLE
Feature Request: Add publicip_ids field to opentelekomcloud_lb_loadbalancer_v3 (Dedicated Load Balancer)

### ISSUE THREAD

**Issue by arkadiusjonczek** [opentelekomcloud/terraform-provider-opentelekomcloud#1709]
The ELB API has a field called "publicip_ids" when creating Dedicated ELB which is missing in the resource opentelekomcloud_lb_loadbalancer_v3. (See: https://docs.otc.t-systems.com/api/elb/CreateLoadBalancer.html)

> Specify publicip_ids and either vpc_id or vip_subnet_cidr_id if you want to bind an existing IPv4 EIP to the load balancer.

With this field it is possible to use an existing EIP as public ip.

Is it possible to add this field to the resource? :)

Best regards,
Arkadius

**Comment by outcatcher** [comment]
@arkadiusjonczek Sure, this should be not a big change from our side :)
