### ISSUE TITLE
opentelekomcloud_identity_role_v3 CCE FullAccess missing in docs

### ISSUE THREAD

**Issue by tvannahl** [opentelekomcloud/terraform-provider-opentelekomcloud#1724]
Hi I am missing the Role name for `CCE FullAccess` in the following documentation: [opentelekomcloud_identity_role_v3](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/data-sources/identity_role_v3)

**Comment by lego963** [comment]
@tvannahl we will update doc with new entities, but for now I can say that `CCE FullAccess` has the name `system_all_27`
