### ISSUE TITLE
CSS - creation of VPC endpoint service not possible

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#1733]
VPC Endpoint cannot be created and used from the resource.
is it possible to add this option the opentelekomcloud_css_cluster_v1

**Comment by anton-sidelnikov** [comment]
Hello @CHS-OTC you should use opentelekomcloud_vpcep_service_v1 for this, it is not right decision to put vpcep logic inside css resource. Yes it present on ui, but this not fit terraform provider structure.
