### ISSUE TITLE
Too many requests have been sent in a given amount of time. Pause requests, wait up to one minute, and try again

### ISSUE THREAD

**Issue by tobiashoefler** [opentelekomcloud/terraform-provider-opentelekomcloud#1753]
# Terraform provider version
Terraform Version: 1.1.9
OTC Provider Version: 1.29.4

# Affected Resource(s)
- opentelekomcloud_networking_secgroup_rule_v2

# Debug Output/Panic Output
`Error: OpenTelekomCloud Security Group Rule: Too many requests have been sent in a given amount of time. Pause requests, wait up to one minute, and try again.`

# Steps to Reproduce
1. `terraform plan`

# Important Factoids
According to my quota report, I have around 400 security group rules. 

# References
- 1671

# Actual Behavior
I think the effect is similar to [#1671](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1671) with a different resource. Any ideas how to fix it ?

**Comment by lego963** [comment]
@tobiashoefler can you update the issue with affected resources?

**Comment by lego963** [comment]
@tobiashoefler 
Fixes for SecGroup Rule and SecGroup will be a part of v1.29.5 release

**Comment by tobiashoefler** [comment]
@lego963 Thank you very much for the fast feedback and the fix !
When will v1.29.5 be released ?

**Comment by lego963** [comment]
@tobiashoefler now :)

**Comment by lego963** [comment]
@tobiashoefler tf registry now has a new version. Can you try use it?

**Comment by lego963** [comment]
Resolved in: #1754
