### ISSUE TITLE
Member IDs of opentelekomcloud_lb_member_v2

### ISSUE THREAD

**Issue by ebal** [opentelekomcloud/terraform-provider-opentelekomcloud#1757]
We can successfully import the opentelekomcloud_lb_member_v2 with https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/1684  and many thanks for that,  but now I have another question regarding that.

I am trying to get the list of the existing Member IDs under a BSG  as we do with the below openstack command. I am facing the problem that the member_id is different than the ECS_id in OTC. 

Perhaps there is another way to correlate this information via terraform. 

The assign of a LB member v2 is being done by the ECS address (The IP address of the member to receive traffic from the load balancer) , but the query/import via the member ID ! 

Thanks in advance, I hope it make sense what I wrote 

```bash
openstack loadbalancer member list <BSG_ID>
```

**Comment by lego963** [comment]
@ebal what do you mean by BSG_ID?

**Comment by ebal** [comment]
yup sorry for the confusion, 

the relative cmd is 

```bash
terraform import opentelekomcloud_lb_member_v2.member pool_id/member_id

```

the **pool_id** is the same with pool_ids in openstack command, which is the BSG (backend server group) ID under the webui console ! 


In a nutshell, we can do the import if we already know the member_IDs  which is quite difficult to know before hand as there are different IDs than the ECS IDs and I was wondering if there is a way with tf to get the list of members under a pool_id .

Hope it is a little more clear now.

**Comment by lego963** [comment]
@ebal I can offer you a new `data_source/opentelekomcloud_lb_member_ids_v2`. Something like `data_source/opentelekomcloud_cce_node_ids_v3`. Is it ok?

**Comment by ebal** [comment]
I guess that could work. Thanks
