### ISSUE TITLE
[Feature] KMS Enabling Key Rotation

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#1762]
# Description of the enhancement
Terraform settings should be aligned with whats possible in the GUI.

In my case, I searched for the "Enabling Key Rotation" feature.

It seams like there is currently no API for it....
https://docs.otc.t-systems.com/en-us/usermanual/kms/kms_01_0139.html
```hcl
resource "opentelekomcloud_kms_key_v1" "this" {
    key_alias       = "example-key"
    pending_days    = null
    key_description = "KMS-Key for example"
    realm           = "eu-de-01"
    is_enabled      = true
    rotation_period = "365d" <----- new use timestamp format of GO

    tags = merge(
        var.tags
    )
}
```

**Comment by lego963** [comment]
@Moep90 we will implement this, but I suppose that it should be another resource `resource/opentelekomcloud_kms_key_rotate_v1`

API Ref:
https://docs.otc.t-systems.com/en-us/api/kms/kms_02_0038.html

**Comment by Moep90** [comment]
@lego963 why do you want this to be another resource?

**Comment by lego963** [comment]
@Moep90 we want do it as a new resource :D It was just a proposal. Sorry for inconvenience

**Comment by Moep90** [comment]
yeah no its fine, I just want to undestand why? Because it just feels like a "feature flag" if you like.

**Comment by vladimirvshivkov** [comment]
@Moep90 
no worry, we'll try to implement this the way you want

**Comment by vladimirvshivkov** [comment]
@Moep90,

I modified resource to enable key rotation. 
After the next release (later today), you will be able to use the example below: 
```
resource "opentelekomcloud_kms_key_v1" "this" {
    key_alias       = "example-key"
    pending_days    = null
    key_description = "KMS-Key for example"
    realm           = "eu-de-01"
    is_enabled      = true
    rotation_enabled = true   <------  will rotate key after 365 days
    rotation_interval = 183   <------ you may select rotate interval from 30 to 365 days

    tags = merge(
        var.tags
    )
}
```

**Comment by Moep90** [comment]
@vladimirvshivkov I suggest something like this:

```hcl
resource "opentelekomcloud_kms_key_v1" "this" {
    key_alias       = "example-key"
    pending_days    = null
    key_description = "KMS-Key for example"
    realm           = "eu-de-01"
    is_enabled      = true
    rotation_interval = 183   <------ you may select rotate interval from 30 to 365 days

    tags = merge(
        var.tags
    )
}
```

if `rotation_interval` is `null` or not set by default it should be disabled.
Having both option seams to be not feasable as they both achive the same thing....

**Comment by vladimirvshivkov** [comment]
@Moep90 
no, you need only to set `rotation_enable = true`,
and by default it will set rotation interval to 365.
and if you want to set custom period you may explicitly specify it by setting  `rotation_interval = 183 `.
is it clear?

**Comment by Moep90** [comment]
I understand what you're telling me. But I challenge the fact, that we need both resource inputs

if you set `rotation_interval` you want to enable key-rotation.
if you dont set `rotation_interval` it should be disabled by default.

Therfore `rotation_enable` can be removed as resource input IMHO.

**Comment by vladimirvshivkov** [comment]
that's the point. you don't need both.
set the only `rotation_enable` and that's it.

we need this argument to disable rotation.
