### ISSUE TITLE
[OBS] Allow Import for opentelekomcloud_obs_bucket

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#1763]
# Description of the enhancement
According to the docs, importing for OBS buckets is not possible. See https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/data-sources/obs_bucket

```
terraform import opentelekomcloud_obs_bucket.this <my-resource-id-123>
```

**Comment by lego963** [comment]
@Moep90 hiho, do you want to import a `resource` or `data_source`?
You opened the `data_source` doc, there is `resource` https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/obs_bucket#import

**Comment by Moep90** [comment]
yeah no, layer 8 problem :facepalm:  just did not close and post my comment to it! Thanks
