### ISSUE TITLE
Limited IAM Roles to specific ressource ids

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#1767]
For some OTC services it is possible to create IAM permission roles, which are only effective for a single ressource of the service.
Like access to a single KMS key or a single OBS bucket.

The API has for that a "Resource" block in the statement. 
https://docs.otc.t-systems.com/api/iam/iam_11_0016.html

Can this be added to the opentelekomcloud_identity_role_v3 ressource.
So it possible to create permissions like this:

{
    "Version": "1.1",
    "Statement": [
        {
            "Action": [
                "kms:cmk:get",
                "kms:dek:crypto",
                "kms:dek:create",
                "kms:cmk:crypto"
            ],
            "Resource": [
                "kms:*:*:KeyId:aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
            ],
            "Effect": "Allow"
        }
    ]
}

**Comment by designtesbrot** [comment]
Highly relevant for us, as key access ideally is resource limited

**Comment by artem-lifshits** [comment]
Feature is released in provider v1.30.2, please check.
