### ISSUE TITLE
[ECS] New data_source/opentelekomcloud_compute_instance_v2

### ISSUE THREAD

**Issue by ebal** [opentelekomcloud/terraform-provider-opentelekomcloud#1771]
# Description of the enhancement

I was wondering if there is a way to have a new data_source about ECS instances similar to the below openstack command?

```bash
$ openstack server show <ECS_NAME>
```

The idea behind this request, is to dynamically query our current infra (we use naming scheme) to get the list of VMs and their IDs so we can then create a proper import list based on their IDs. 

thanks in advance,

**Comment by vladimirvshivkov** [comment]
Resolved by https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/1772

**Comment by ebal** [comment]
Hi,

with all due respect the request is for import the ECS querying based on their name (that we already know), in order to get the IDs (that we do not know) thus the openstack command as an example. 

This is the opposite, to import the ECSs with the ID as argument to get their name.

We were expecting something like 

```bash
data "opentelekomcloud_compute_instance_v2" "instance" {
  # The OTC name of the ECS
  name = "<vm_web_001>"
}
```

and get the UUID

**Comment by vladimirvshivkov** [comment]
ok, understood.
will do.
