### ISSUE TITLE
CBR vault refresh issue if server backups exclude disks

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#1776]
Hello,

we have an issue with updating the TF state when the OTC CBR vault API response includes a "exclude_volumes" or a "include_volumes" in the extra_info field of a ressource.

# Terraform provider version
Terraform v1.2.3
on windows_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.29.6
+ provider registry.terraform.io/terraform-provider-openstack/openstack v1.47.0

# Affected Resource(s)
opentelekomcloud_cbr_vault_v3

# Terraform Configuration Files
resource "opentelekomcloud_cbr_policy_v3" "default_policy" {
  name           = "mh-policy"
  operation_type = "backup"
  trigger_pattern = [
    "FREQ=DAILY;INTERVAL=1;BYHOUR=23;BYMINUTE=00"
  ]
  operation_definition {
    timezone    = "UTC+01:00"
    max_backups = "5"
  }
  enabled = "true"
}

resource "opentelekomcloud_cbr_vault_v3" "vault_server" {
  name             = "mh-vault-tf"
  description      = "CBR vault for default backup policy"
  backup_policy_id = opentelekomcloud_cbr_policy_v3.default_policy.id
  auto_bind        = true
  auto_expand      = true
  billing {
    size          = 10000
    object_type   = "server"
    protect_type  = "backup"
    charging_mode = "post_paid"
  }
}

# Steps to Reproduce
1. I did create the ressource via terraform apply. That worked without issues.
2.  I did add via the OTC GUI a server to the vault. But I selected not every disks of that ECS.
![image](https://user-images.githubusercontent.com/79697776/174993911-e5d653bd-6b2e-4ceb-8476-f564caa49a35.png)
3. After that I run terraform apply again. That should only update the TFState. But it results in the error below.

PS C:\Users\Administrator\Desktop\terraform\ecs\test> terraform apply
opentelekomcloud_cbr_policy_v3.default_policy: Refreshing state... [id=2c73fd16-a335-477d-aa0b-4b5daf8526ee]
opentelekomcloud_cbr_vault_v3.vault_server: Refreshing state... [id=0e7fd304-ed99-4396-9234-14796107af16]
╷
│ Error: error setting vault fields: 1 error occurred:
│       * resource.55.extra_info.exclude_volumes: '' expected type 'string', got unconvertible type '[]interface {}', value: '[1b7a16c3-0dca-4c67-a160-610888330ffb]'
│
│
│
│   with opentelekomcloud_cbr_vault_v3.vault_server,
│   on cbr.tf line 14, in resource "opentelekomcloud_cbr_vault_v3" "vault_server":
│   14: resource "opentelekomcloud_cbr_vault_v3" "vault_server" {
│
╵

# Expected Behavior
The added server to the vault should be included in the tf state file. No further actions

# Actual Behavior
The mentioned error message

# Important Factoids
Current TF state entry regarding the CBR vault
{
      "mode": "managed",
      "type": "opentelekomcloud_cbr_vault_v3",
      "name": "vault_server",
      "provider": "provider[\"registry.terraform.io/opentelekomcloud/opentelekomcloud\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "auto_bind": true,
            "auto_expand": true,
            "backup_policy_id": "2c73fd16-a335-477d-aa0b-4b5daf8526ee",
            "billing": [
              {
                "allocated": 90,
                "charging_mode": "post_paid",
                "cloud_type": "public",
                "consistent_level": "crash_consistent",
                "console_url": "",
                "extra_info": {},
                "frozen_scene": "",
                "is_auto_pay": false,
                "is_auto_renew": false,
                "object_type": "server",
                "order_id": "",
                "period_num": 0,
                "period_type": "month",
                "product_id": "",
                "protect_type": "backup",
                "size": 10000,
                "spec_code": "vault.backup.server.normal",
                "status": "available",
                "storage_unit": "",
                "used": 60632
              }
            ],
            "bind_rules": [],
            "created_at": "2022-06-21T07:17:03.156857",
            "description": "CBR vault for default backup policy",
            "enterprise_project_id": "0",
            "id": "0e7fd304-ed99-4396-9234-14796107af16",
            "name": "mh-vault-tf",
            "project_id": "c87a0390a7f242a8b32b104b4e899793",
            "provider_id": "0daac4c5-6707-4851-97ba-169e36266b66",
            "resource": [],
            "tags": {},
            "user_id": "0423ef71a3914444a381f18a3bbd5e26"
          },
          "sensitive_attributes": [],
          "private": "bnVsbA==",
          "dependencies": [
            "opentelekomcloud_cbr_policy_v3.default_policy"
          ]
        }
      ]
    }

The request response done by Terraform to the OTC API includes the following  ressource data:
{"id": "1d114217-35dc-4b90-8f0a-32c85988c676", "type": "OS::Nova::Server", "name": "ecs-mh-test-lts", "size": 40, "backup_size": 13748, "backup_count": 1, "protect_status": "available", "extra_info": {"exclude_volumes": ["1b7a16c3-0dca-4c67-a160-610888330ffb"]}}

So it appears there is an issue with the "extra_info" field. 
The data for a server where every disk is backuped looks like this and does not cause an issue;
{"id": "f8f9ffa9-12e9-4360-8e25-c472e1048c20", "type": "OS::Nova::Server", "name": "ecs-mh-test1", "size": 40, "backup_size": 20892, "backup_count": 2, "protect_status": "available", "extra_info": {}}

A customer also reported that the same issue occours if the extra_info field contains "include_volumes" instead of "excluded_volumes" . I guess that error has the same origin as this one.

Could you please check it?

**Comment by anton-sidelnikov** [comment]
Checking it...

**Comment by anton-sidelnikov** [comment]
Released, please check.
