### ISSUE TITLE
check return data "opentelekomcloud_networking_port_v2"

### ISSUE THREAD

**Issue by vladimirvshivkov** [opentelekomcloud/terraform-provider-opentelekomcloud#1780]
I had the same problem and now I have a follow-up question concerning the data source "opentelekomcloud_networking_port_v2".

Question: Can you giv e me a working example how filtering fixed_ips would look like in practice? The documentation only states it supports an argument "fixed_ip" with the description _"(Optional) The port IP address filter."_, but I can not find an info on how such a filter needs to be defined. Simply passing the corresponding IP does not work for me.

I have the following port resource with three fixed_ip blocks (output of terraform state show):

```
# module.testnetwork.opentelekomcloud_networking_port_v2.this:
resource "opentelekomcloud_networking_port_v2" "this" {
    admin_state_up        = true
    all_fixed_ips         = [
        "172.23.35.3",
        "172.23.34.3",
        "172.23.33.3",
    ]
    id                    = "d9be961b-47c1-45bb-93ac-a4d0d0f5a31e"
    mac_address           = "fa:16:3e:b1:d0:cf"
    network_id            = "82054e51-e941-4ad2-9055-bbb72c2600d3"
    port_security_enabled = true
    region                = "eu-de"
    security_group_ids    = [
        "c48df6cc-6ed1-45ee-8676-5e04dca38acc",
    ]
    tenant_id             = "c7b5384e487149d696b7cfc420589afe"

    fixed_ip {
        ip_address = "172.23.34.3"
        subnet_id  = "282765ba-c0f2-4c4e-aa43-306f06fca068"
    }
    fixed_ip {
        ip_address = "172.23.35.3"
        subnet_id  = "1dbc594b-80af-4a78-8d7d-86bc26d287ef"
    }
    fixed_ip {
        ip_address = "172.23.33.3"
        subnet_id  = "54ef48fa-80fb-452e-8e55-01c10365b5ec"
    }
}

```

And the datasource from your example above:

```
data "opentelekomcloud_networking_port_v2" "fw_port" {
  network_id   = opentelekomcloud_networking_network_v2.network.id
  device_owner = "network:router_interface_distributed"

  depends_on = [
    opentelekomcloud_networking_router_interface_v2.router_interface
  ]
}
```

This will lead to a datasource error message that it found three ports. Well, congrats Sherlock, I would have expected the data source to return a map here, but okay, I can live with this. Because the documentation states it supports filtering for fixed_ips. 

Let's create a for_each loop which iterates over the fixed_ip blocks:

```
data "opentelekomcloud_networking_port_v2" "this" {
  depends_on = [ opentelekomcloud_networking_router_interface_v2.this ]
  for_each = var.network_port_fixed_ip != null ? var.network_port_fixed_ip : {}
  
  network_id = opentelekomcloud_networking_network_v2.this.id
  device_owner = "network:router_interface_distributed"
  #fixed_ip = each.value["ip_address"]
}

```
But I have no luck here. I tried several things, even AWS-style filter{} blocks and other things, and even when I hardcode the IP "10.0.10.51" in  your otherwise working example, I always get the error "Error: no opentelekomcloud_networking_port_v2 found". 

So, can you give me an example how to use the fixed_ip argument correctly?

Thanks,

Ralf

_Originally posted by @rramge in https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/discussions/1590#discussioncomment-3007738_

**Comment by rramge** [comment]
Since the afternoon of Friday, June 24 2022, trying to create a network port with more than one fixed_ip block leads to the following error:

```
module.my-network.opentelekomcloud_networking_router_interface_v2.this["IP_webserver"]: Creation complete after 11s [id=3bc884c5-1032-4544-8fc3-f3f16c5f4d05]
╷
│ Error: error creating OpenTelekomCloud Neutron port: Bad request with: [POST https://vpc.eu-de.otc.t-systems.com/v2.0/ports], error message: {"NeutronError":{"message":"One port can only set one ipaddress","type":"InvalidInput","detail":""}}
│ 
│   with module.my-network.opentelekomcloud_networking_port_v2.this,
│   on .terraform/modules/my-network/main.tf line 22, in resource "opentelekomcloud_networking_port_v2" "this":
│   22: resource "opentelekomcloud_networking_port_v2" "this" {
│ 
╵
Operation failed: failed running terraform apply (exit 1)
[rramge@ol8 examples.cloud]$ 
[rramge@ol8 examples.cloud]$ terraform version
Terraform v1.2.3
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.29.7
[rramge@ol8 examples.cloud]$ 
```

This means the example above doesn't work anymore, at least when using terraform instead of the OTC web interface.

When trying to resolve the issue by creating three ports with one fixed_ip instead, the datasource fails:

```
│ Error: more than one opentelekomcloud_networking_port_v2 found (3)
│ 
│   with module.testnetwork.data.opentelekomcloud_networking_port_v2.this["databases"],
│   on ../modules/terraform-opentelekomcloud-network/datasources.tf line 9, in data "opentelekomcloud_networking_port_v2" "this":
│    9: data "opentelekomcloud_networking_port_v2" "this" {
│ 
╵
╷
│ Error: more than one opentelekomcloud_networking_port_v2 found (3)
│ 
│   with module.testnetwork.data.opentelekomcloud_networking_port_v2.this["webserver"],
│   on ../modules/terraform-opentelekomcloud-network/datasources.tf line 9, in data "opentelekomcloud_networking_port_v2" "this":
│    9: data "opentelekomcloud_networking_port_v2" "this" {
│ 
╵
╷
│ Error: more than one opentelekomcloud_networking_port_v2 found (3)
│ 
│   with module.testnetwork.data.opentelekomcloud_networking_port_v2.this["middleware"],
│   on ../modules/terraform-opentelekomcloud-network/datasources.tf line 9, in data "opentelekomcloud_networking_port_v2" "this":
│    9: data "opentelekomcloud_networking_port_v2" "this" {
│ 
╵
```

The datasource:

```
data "opentelekomcloud_networking_port_v2" "this" {
  depends_on = [ opentelekomcloud_networking_router_interface_v2.this ]
  for_each = var.network_port_fixed_ip != null ? var.network_port_fixed_ip : {}
  
    network_id = opentelekomcloud_networking_network_v2.this.id
    # port_id =  <with the actual ID of the corresponding networking_port_v2 delivers no result>
    device_owner = "network:router_interface_distributed"
}
```
In my opinion, the port_id argument should accept the actual port id of the port ressource as input parameter. But it doesn't, when I associate the fw rule to the three subnets manually and import the fw rule, the content of the port_id attribute does not match anything in the entire state file.

Cheers,

Ralf

**Comment by anton-sidelnikov** [comment]
Question to backend team: [ONS-12115](https://jira.tsi-dev.otc-service.com/browse/ONS-12115)

**Comment by anton-sidelnikov** [comment]
Answer from development: "We got info from vendor side that creating port with several ipsis not supported" - will do some changes in provider according. Also will check ability to filter by ip in data-source.
