### ISSUE TITLE
When I try to create a private DNS zone I get Internal Server Error

### ISSUE THREAD

**Issue by sgyuris** [opentelekomcloud/terraform-provider-opentelekomcloud#1781]
# Terraform provider version

Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/hashicorp/tls v3.4.0
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.24.3
+ provider registry.terraform.io/rhythmictech/errorcheck v3.0.0

Your version of Terraform is out of date! The latest version
is 1.2.3. You can update by downloading from https://www.terraform.io/downloads.html

# Affected Resource(s)

opentelekomcloud_dns_zone_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_dns_zone_v2" "admin1_runner_magentacloud_de" {
  name        = "admin1.magentacloud.de."
  email       = "private@admin1.magentacloud.de"
  description = "admin1 private dns zone"
  ttl         = 300
  type        = "private"

  router {
    router_id     = module.network.vpc.id
    router_region = "eu-de_01admin-runner"
  }
  tags = local.common_tags

  provider = opentelekomcloud.subproject
}
```

# Debug Output/Panic Output

module.provisioning.opentelekomcloud_dns_zone_v2.admin1_runner_magentacloud_de: Creating...

Error: error creating OpenTelekomCloud DNS zone: Internal Server Error

  on ../../provisioning/baseinfra.tf line 16, in resource "opentelekomcloud_dns_zone_v2" "admin1_runner_magentacloud_de":
  16: resource "opentelekomcloud_dns_zone_v2" "admin1_runner_magentacloud_de" {

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

Private DNZ should created.

# Actual Behavior

Internal Server Error

**Comment by anton-sidelnikov** [comment]
Hi @sgyuris , may be problem in router_region = "eu-de_01admin-runner"?

**Comment by sgyuris** [comment]
What kind of problem could it be?

**Comment by anton-sidelnikov** [comment]
i assume the region should be: router_region = "eu-de"

**Comment by sgyuris** [comment]
True. Just now I changed the 'provider' to '...subproject' and now it is fine. Just I don't understand the server internal error part.

**Comment by anton-sidelnikov** [comment]
i will check if we can set some proper message in that case

**Comment by anton-sidelnikov** [comment]
New message after next release
