### ISSUE TITLE
In-place upgrade of CCE

### ISSUE THREAD

**Issue by simonszu** [opentelekomcloud/terraform-provider-opentelekomcloud#1784]
We have two CCE instances deployed with CCE version 1.19. In the meantime, the OTC suggest us to upgrade the instances to the newest version 1.21. This seems to be an in-place upgrade. 

The TF provider documentation for the CCE objects states that the newest available version is 1.19. I would like to suggest a feature request: 
- Provide the deployment of 1.21 CCE instances
- Support in-place upgrades of a CCE. For a productive instance, a downtime with complete rebuild is not feasible. 
- Alternatively: Provide best-practices, for example "Upgrade manually, and fix the version in the TF afterwards" which will collide with the infrastructure-as-code approach.

**Comment by vladimirvshivkov** [comment]
Sorry, but we dont have API for that.
