### ISSUE TITLE
Creation of opentelekomcloud_lb_pool_v3 with HTTPS protocol 

### ISSUE THREAD

**Issue by PakesDavid** [opentelekomcloud/terraform-provider-opentelekomcloud#1789]
# Description of the enhancement
There is no possibility to create opentelekomcloud_lb_pool_v3 with HTTPS backend protocol. Via OTC gui it is possible. In terraform doc is also said that:
For HTTP or HTTPS listeners, the protocol of the backend server group must be HTTP.
But with OTC I was able to set backend protocol as HTTPS and everything was working okay. 
Is it possible to add this possibility to terraform as well?

**Comment by anton-sidelnikov** [comment]
Current doc doesn't describe this is possible, but this is possible, so we update code in opentelekomcloud_lb_pool_v3.
