### ISSUE TITLE
[CCE] Cluster creation fails, because the subnet resource on OTC API if not exists or could not be found

### ISSUE THREAD

**Issue by d0schuma** [opentelekomcloud/terraform-provider-opentelekomcloud#1797]
# Terraform provider version

```
Terraform v1.2.4
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.29.8
```

# Affected Resource(s)

relevant:
- opentelekomcloud_cce_cluster_v3

<br>

possibly not relevant:
- opentelekomcloud_networking_router_v2
- opentelekomcloud_networking_network_v2
- opentelekomcloud_networking_subnet_v2
- opentelekomcloud_networking_router_interface_v2

# Terraform Configuration Files

example configuration file

```hcl
resource "opentelekomcloud_networking_router_v2" "router" {
  name              = "tf_test_router"
  admin_state_up    = true
}

resource "opentelekomcloud_networking_network_v2" "network" {
  name           = "tf_test_network"
  admin_state_up = "true"
}

resource "opentelekomcloud_networking_subnet_v2" "subnet" {
    name        = "tf_test_subnet"
    network_id  = opentelekomcloud_networking_network_v2.network.id
    cidr        = "192.168.199.0/24"
}

resource "opentelekomcloud_networking_router_interface_v2" "router_interface" {
  router_id   = opentelekomcloud_networking_router_v2.router.id
  subnet_id   = opentelekomcloud_networking_subnet_v2.subnet.id
}


resource "opentelekomcloud_cce_cluster_v3" "cluster" {
    name                    = "tf-test-cce-cluster"
    description             = "test description"
    billing_mode            = 0
    flavor_id               = "cce.s2.small"
    cluster_version         = "v1.21.1-r1"
    cluster_type            = "VirtualMachine"
    multi_az                = true
    vpc_id                  = opentelekomcloud_networking_router_interface_v2.router_interface.router_id
    subnet_id               = opentelekomcloud_networking_subnet_v2.subnet.id
    container_network_type  = "overlay_l2"
    container_network_cidr  = "10.0.0.0/16"
    kubernetes_svc_ip_range = "10.247.0.0/16"
    no_addons               = false
    authentication_mode     = "rbac"
    
    authenticating_proxy {
        ca          = ""
        cert        = ""
        private_key = ""
    }
}
```

# Debug Output/Panic Output

```shell
│ Error: 1 error occurred:
│       * can't find subnet `xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`: Resource not found: [GET https://vpc.eu-de.otc.t-systems.com/v1/{project id}/subnets/{subnet id}], error message: {"code":"VPC.0202","message":"Query resource by id xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx fail.the subnet could not be found."}
```

# Steps to Reproduce

1. `terraform apply -auto-approve`

# Expected Behavior

Creation of cce cluster

# Actual Behavior

Error
No cce cluster creation

# Important Factoids

I think the problem is that the API address (https://vpc.eu-de.otc.t-systems.com/v1/{project_id}/subnets/{subnet_id}) doesn't works.
https://docs.otc.t-systems.com/en-us/api/vpc/vpc_subnet01_0002.html

But this API address works (https://vpc.eu-de.otc.t-systems.com/v2.0/subnets/{subnet_id})
https://docs.otc.t-systems.com/en-us/api/vpc/vpc_subnet02_0002.html

I think the current query API address would need to be changed in cce.
Please fix this bug as soon as possible. Thanks in advance.

# References

- https://docs.otc.t-systems.com/en-us/api/vpc/vpc_subnet01_0002.html
- https://docs.otc.t-systems.com/en-us/api/vpc/vpc_subnet02_0002.html

**Comment by lego963** [comment]
@d0schuma here `subnet_id` means `network_id`
```
* `subnet_id` - (Required) The Network ID of the subnet used to create the cluster. Changing this parameter will create a new cluster resource.
```

**Comment by d0schuma** [comment]
Yes, it works. Thanks :)

I don't know, if it would better to change the variable name, because this is actual misleading? I mean in all other resource that i had used it `subnet_id` means `subnet_id` and not `network_id` or others. Is only a recommendation. :)

**Comment by lego963** [comment]
@d0schuma you are right. We are thinking about `tf-provider-v2`, because here we can't just rename the field. (Backward compatibility)
