### ISSUE TITLE
identity_project_v3: Please add region datasource

### ISSUE THREAD

**Issue by rramge** [opentelekomcloud/terraform-provider-opentelekomcloud#1798]
# Description of the enhancement

The doc states for the required "name" attribute:
[name](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/identity_project_v3#name) - (Required) The name of the project. it must start with ID of an existing region and be less than or equal to 64 characters. Example: eu-de_project1.

In a fully automated environment, that's easier said than done. Dynamic modules which are designed to be used in different environments can not hardcode a region. 

To resolve this, please add a datasource which returns a map or object of available regions, preferably with the home region of an account (the region in which a customer logs in initially) being flagged.

**Comment by anton-sidelnikov** [comment]
datasource for /v3/regions api
