### ISSUE TITLE
identity_project_v3: Project region prefix can not be modified

### ISSUE THREAD

**Issue by rramge** [opentelekomcloud/terraform-provider-opentelekomcloud#1799]
# Terraform provider version

Terraform v1.3.0-alpha20220608
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.29.9

# Affected Resource(s)

opentelekomcloud_identity_project_v3

# Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

# Debug Output/Panic Output

When changing the region part of a project's name, the provider states during the plan phase:
```
Terraform will perform the following actions:

  # module.testproject.opentelekomcloud_identity_project_v3.this["project_1"] will be updated in-place
  ~ resource "opentelekomcloud_identity_project_v3" "this" {
        id        = "b6698a2c46eb4df3a3e31a30d1e9d077"
      ~ name      = "eu-nl_test" -> "eu-de_test"
        # (5 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

But this leads to an API error "null" during the roll-out:

```
module.testproject.opentelekomcloud_identity_project_v3.this["project_1"]: Modifying... [id=b6698a2c46eb4df3a3e31a30d1e9d077]
╷
│ Error: error updating OpenStack project: Bad request with: [PATCH https://iam.eu-de.otc.t-systems.com/v3/projects/b6698a2c46eb4df3a3e31a30d1e9d077], error message: {"error": {"message": "Project region prefix can not be modified.", "code": 400, "error_code": null, "error_msg": null, "title": "Bad Request"}}
│ 
│   with module.testproject.opentelekomcloud_identity_project_v3.this["project_1"],
│   on ../modules/terraform-opentelekomcloud-iam/main.tf line 79, in resource "opentelekomcloud_identity_project_v3" "this":
│   79: resource "opentelekomcloud_identity_project_v3" "this" {
│ 
╵
```

# Steps to Reproduce

- create a project
- change the project's name accordingly
- Test your code with 'terraform plan' -> Provider says the project will be updated in place, gives no error message
- Deploy your code with 'terraform apply' -> Error

# Expected Behavior

This change has to recreate the resource instead of updating it.

And since using a valid region is completely delegated to the user, the input should be validated for correctness, and Acceptance Test leading to error during the plan phase, as recommended by HashiCorp in the SDKv2 Best Practices. 

# Actual Behavior

API error 400, error_code null, error_msg "null"

# Important Factoids

# References

[HashiCorp SDKv2 Testing Patterns: Basic test to verify attributes](https://www.terraform.io/plugin/sdkv2/best-practices/testing#basic-test-to-verify-attributes)

**Comment by vladimirvshivkov** [comment]
project change prefix is invalid between regions

**Comment by rramge** [comment]
Yes, that's why you need to recreate the resource instead of updating it ...
