### ISSUE TITLE
Terraform API to support more services of OTC

### ISSUE THREAD

**Issue by YUANTSI** [opentelekomcloud/terraform-provider-opentelekomcloud#1805]
Our Customer would like to have Terraform API to support their services used on our OTC. DRS, GaussDB, GaussDBforNonSQL, DWS, ModelArts, DLI, DIS, DGC, CDM.

**Comment by vladimirvshivkov** [comment]
We also would like to have these services in terraform.
But we lack API for many of these e.g., gaussdb.
And the rest services are planned, but it may take months to implement.
It will be better if customer prioritizes their needs.
Thanks in advance!

**Comment by YUANTSI** [comment]
I'm contacting customer to prioritize this list of services they request. I hope I will get a reply soon. any of these services already support? or at the moment none of them?

**Comment by YUANTSI** [comment]
Customer gave the following priorities. 1 as the highest, 9 as the lowest priority.
1 | GaussDB (DM-4477)
2 | DRS (DM-4476) 
3 | GaussDBforNonSQL (DM-4483) 
4 | DWS (DM-4478) 
5 | CDM 
6 | DIS (DM-4481) 
7 | DGC (DM-4482) 
8 | DLI (DM-4480) 
9 | ModelArts (DM-4479)

**Comment by YUANTSI** [comment]
Can we please have some time evaluation about when these API will be supported? thanks!

**Comment by vladimirvshivkov** [comment]
We planned implementation, but cannot evaluate them now, because of a lack of API for these new services.
And some of them are even hardly be operated by terraform, i.e. ModelArts, DIS.

**Comment by artem-lifshits** [comment]
We are not responsible for API implementation on R&D OTC side and can work only on services when its API available for public use.
If you have specific demands on provider resource implementation please open a separate ticket.
