### ISSUE TITLE
opentelekomcloud_identity_user_v3 updates object during `terraform plan`

### ISSUE THREAD

**Issue by siebertm** [opentelekomcloud/terraform-provider-opentelekomcloud#1812]
Hello,

for security reasons, we want our CI to run `terraform plan` with a readonly user to avoid unreviewed code to be applied.

For this, I created a specific user which only has readonly permissions. Unfortunately, `terraform plan` now fails with rather unspecific error `update os user failed` with status code 403.

I set up `Cloud Trace Service` and ran the same `terraform plan` with a full-admin user, it shows an update to the user:

```
{
    "service_type": "IAM",
    "user": {
        "name": "redacted",
        "id": "redacted",
        "domain": {
            "name": "redacted",
            "id": "redacted"
        }
    },
    "time": "2022-07-15 10:30:35 GMT+02:00",
    "code": 200,
    "resource_type": "user",
    "resource_name": "redacted",
    "resource_id": "redacted",
    "trace_name": "updateUser",
    "trace_type": "ApiCall",
    "message": "Update User:{\"user\":{}}\n",
    "record_time": "2022-07-15 10:30:35 GMT+02:00",
    "trace_id": "redacted",
    "trace_status": "normal"
}
```

So it's sending an empty `update`, thus I'd need a `Security Administrator` role at least, but that's not what I want. Instead, running `terraform plan` should be a readonly operation.

# Terraform provider version
```
Terraform v1.2.5
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.29.9
```

# Affected Resource(s)
- opentelekomcloud_identity_user_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_identity_user_v3" "backup" {
  name    = "redacts"
  enabled = true
  email   = "redacted"
}
```

**Comment by artem-lifshits** [comment]
Fix for this issue is added in provider v1.30.2, please check.
