### ISSUE TITLE
[CCE] Encryption on root volume

### ISSUE THREAD

**Issue by r-ising** [opentelekomcloud/terraform-provider-opentelekomcloud#1813]
# Encryption on root volume

In the API documentation its the same "Volume object" type on rootVolume and on dataVolumes.
See https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0242.html

The terraform provider supports the kms_id only on dataVolumes.

I already tried to create a CCE with an node pool with encrypted root volume and data volumes (by API) and it works fine.

Its just a very small improvement, because the functionality for the data volumes already exists.

Thanks

**Comment by vladimirvshivkov** [comment]
closed by https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/1827
