### ISSUE TITLE
[ECS] opentelekomcloud_ecs_instance_v1 not working corrently with opentelekomcloud_compute_volume_attach_v2

### ISSUE THREAD

**Issue by r-ising** [opentelekomcloud/terraform-provider-opentelekomcloud#1820]
# Terraform provider version

1.2.5

# Affected Resource(s)

- opentelekomcloud_ecs_instance_v1
- opentelekomcloud_compute_volume_attach_v2
- opentelekomcloud_blockstorage_volume_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_blockstorage_volume_v2" "myvol" {
  name              = "myvol"
  availability_zone = "eu-de-01"
  size              = 10
}

resource "opentelekomcloud_ecs_instance_v1" "basic" {
  name     = "server_1"
  image_id = local.default_image_id
  flavor   = "s2.medium.1"
  vpc_id   = opentelekomcloud_vpc_v1.vpc.id

  nics {
    network_id = opentelekomcloud_vpc_subnet_v1.ops.id
    ip_address = "172.18.30.99"
  }

  availability_zone = "eu-de-01"
  key_name          = opentelekomcloud_compute_keypair_v2.main.name
}

resource "opentelekomcloud_compute_volume_attach_v2" "attached" {
  instance_id = opentelekomcloud_ecs_instance_v1.basic.id
  volume_id   = opentelekomcloud_blockstorage_volume_v2.myvol.id
}
```

# Steps to Reproduce

Run terraform apply multiple times

# Expected Behavior

VM shouldn't be recreated on every apply without changing the terraform files.

# Actual Behavior

VM will recreated on every run. See screenshot:

<img width="1038" alt="Screenshot 2022-07-18 at 14 32 57" src="https://user-images.githubusercontent.com/16190832/179512034-c406f533-cb94-4252-b62b-dd768da3109e.png">

**Comment by r-ising** [comment]
I found this example on your documentation: https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/ecs_instance_v1

**Comment by anton-sidelnikov** [comment]
@r-ising now all data_disks using only in create, All volumes can be found now in volumes_attached attribute

**Comment by anton-sidelnikov** [comment]
If you have further questions, please reopen it.
