### ISSUE TITLE
[Peering] VPC is destroyed while Router Interface and Subnets still exist?

### ISSUE THREAD

**Issue by rramge** [opentelekomcloud/terraform-provider-opentelekomcloud#1824]
# Terraform provider version

Terraform v1.3.0-alpha20220706
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.30.0

# Affected Resource(s)

opentelekomcloud_vpc_peering_connection_v2
opentelekomcloud_vpc_route_v2
opentelekomcloud_vpc_v1

# Terraform Configuration Files

You can find an example, where the issue can be reproduced in about 50% of tries here: [https://gitlab.ict.technology/ioda/tf/tutorial/-/tree/main/02](https://gitlab.ict.technology/ioda/tf/tutorial/-/tree/main/02   )

You can find the corresponding modules which are used here: [https://gitlab.ict.technology/ioda/tf/modules](https://gitlab.ict.technology/ioda/tf/modules )

# Debug Output/Panic Output

```
module.testnetwork_3.opentelekomcloud_networking_router_interface_v2.this["webserver"]: Still destroying... [id=1fada8cb-5671-4fb0-ad4c-f822295392d5, 10s elapsed]
module.testnetwork_3.opentelekomcloud_networking_router_interface_v2.this["webserver"]: Destruction complete after 11s
module.testvpc_2.opentelekomcloud_vpc_subnet_v1.this["webserver"]: Destruction complete after 17s
module.testvpc_peering.opentelekomcloud_vpc_peering_connection_v2.this["testvpc_peering"]: Destruction complete after 9s
module.testvpc_1.opentelekomcloud_vpc_subnet_v1.this["webserver"]: Destruction complete after 9s
module.testvpc_1.opentelekomcloud_vpc_subnet_v1.this["databases"]: Still destroying... [id=200d859c-d81f-42a2-880d-834159f71ed3, 10s elapsed]
module.testvpc_2.opentelekomcloud_vpc_subnet_v1.this["middleware"]: Still destroying... [id=5efc0c2e-ef56-4649-a4d4-a35afa34537d, 10s elapsed]
module.testvpc_2.opentelekomcloud_vpc_subnet_v1.this["middleware"]: Destruction complete after 10s
module.testvpc_2.opentelekomcloud_vpc_v1.this: Destroying... [id=e87cbafc-6051-488c-9092-2acd15f0e61e]
module.testvpc_1.opentelekomcloud_vpc_subnet_v1.this["databases"]: Destruction complete after 17s
module.testvpc_1.opentelekomcloud_vpc_v1.this: Destroying... [id=86a3d6ae-3ac9-4411-8f19-372ad6dd3bb5]
module.testvpc_2.opentelekomcloud_vpc_v1.this: Still destroying... [id=e87cbafc-6051-488c-9092-2acd15f0e61e, 10s elapsed]
module.testvpc_2.opentelekomcloud_vpc_v1.this: Destruction complete after 11s
module.testvpc_1.opentelekomcloud_vpc_v1.this: Still destroying... [id=86a3d6ae-3ac9-4411-8f19-372ad6dd3bb5, 10s elapsed]
module.testvpc_1.opentelekomcloud_vpc_v1.this: Destruction complete after 10s
╷
│ Error: error deleting OpenTelekomCloud Neutron Router Interface: Internal Server Error
│ 
│ 
╵
```

# Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

May take more than one attempt, sometimes the destroy works, but most of the time not.
Nearly 100% chance if a compute instance had previously been deployed in an involved subnet.

# Expected Behavior

All resources should be destroyed, state file empty.

# Actual Behavior

Automated Continuous Testing scenarios always end with the provider stating that everything will work fine (terraform plan). During destroy phase, the Internal server error as shown above happens.

Then, the state still contains those resources (please take note the the router and subnets are still in the state, but the VPCs are not. That should not even be possible on terraform level, is the dependency graph incorrect?):

```
[rramge@ol9 02]$ tf state list
module.testnetwork_3.opentelekomcloud_networking_network_v2.this
module.testnetwork_3.opentelekomcloud_networking_router_interface_v2.this["middleware"]
module.testnetwork_3.opentelekomcloud_networking_router_v2.this
module.testnetwork_3.opentelekomcloud_networking_subnet_v2.this["databases"]
module.testnetwork_3.opentelekomcloud_networking_subnet_v2.this["middleware"]
module.testnetwork_3.opentelekomcloud_networking_subnet_v2.this["webserver"]
[rramge@ol9 02]$ 
```

Any additional attempts to destroy the resources don't work, because the VPC is missing and isn't recovered during the refresh phase anymore, which leads to missing vpc_ids on the terraform level.

Pardon my french, but when checking in the OTC console, the shit really hits the fan. The VPCs still exist there, but with empty display name. Usually only one of the three subnets from the state file still exists. **And this subnet can not even be deleted manually anymore**; any attempt leads to the following error:

`""NeutronError": {"detail": "", "message": "Unable to complete operation on network 47f47ebe-52f9-4510-94d9-e6aa6d242476. There are one or more ports still in use on the network.", "type": "NetworkInUse"}}"`

So, this means that obviously the OTC backend and the API are utter garbage here, but the provider is also problematic. It's the provider's responsibility that the dependencies are correct and the resources are deleted in the correct order, errors from the API must be avoided or handled (otherwise all testing scenarios above unit test level will be broken).

Please update the provider accordingly and, if possible, raise a ticket at the REST API team.

Thanks a lot,

Ralf

# Important Factoids

```
variable "domain_name" {
  type    = string
  default = "OTC-EU-DE-00000000001000035579"
}

variable "tenant_name" {
  type    = string
  default = "eu-de"
}
```
This is a OTC public cloud testing environment before production rollout in a OTC private cloud installation.

# References

**Comment by rramge** [comment]
I attach the terraform graph here, just in case. A subsequent destroy operation failed with the reported error. 

[graph.out.txt](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/files/9147367/graph.out.txt)

**Comment by anton-sidelnikov** [comment]
@rramge please check
