### ISSUE TITLE
[DNS] "The TTL parameter has been out of range. The value ranges from 300 to 2147483647."

### ISSUE THREAD

**Issue by rramge** [opentelekomcloud/terraform-provider-opentelekomcloud#1825]
# Terraform provider version

Terraform v1.3.0-alpha20220706
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.29.9

# Affected Resource(s)

opentelekomcloud_dns_recordset_v2

# Terraform Configuration Files

Anything with TTL < 300

# Debug Output/Panic Output

```
│ Error: error creating OpenTelekomCloud DNS record set: Bad request with: [POST https://dns.eu-de.otc.t-systems.com/v2/zones/2c9c2de9821a985501821a9f15a80004/recordsets], error message: {"code":"DNS.0319","message":"The TTL parameter has been out of range. The value ranges from 300 to 2147483647."}
│ 
│   with module.dns.opentelekomcloud_dns_recordset_v2.this["www.example2.com. A"],
│   on ../modules/terraform-opentelekomcloud-dns/main.tf line 20, in resource "opentelekomcloud_dns_recordset_v2" "this":
│   20: resource "opentelekomcloud_dns_recordset_v2" "this" {
```

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

**TTLs lower than 300 still worked two days ago, now they are broken.**

# Actual Behavior

Production scenarios have been broken. 

The provider doesn't catch it, so during testing it still states the configuration is fine and in rollout it breaks.

Short TTLs (with short meaning "1") are absolutely vital for dynamic environments, where servers are spun up on demand and get destroyed again after use. The usual Pet vs. Cattle principle. It is absolutely not possible to wait 5 Minutes during production changes until a TTL finally times out, wait 5 minutes until an ACME cert TXT record gets updated, and so on. We simply cannot delay the destruction or update of any resource which depends on a DNS record for 5 minutes just to make sure the reality and codebase still represent each other.

So please adjust the provider defaults and/or raise a ticket with whoever did this change and to make sure they roll it back...

Thanks,

Ralf

# Important Factoids

# References

**Comment by anton-sidelnikov** [comment]
Internal issue, we investigating this.

**Comment by artem-lifshits** [comment]
https://jira.tsi-dev.otc-service.com/browse/ONS-10800

**Comment by anton-sidelnikov** [comment]
Fixed
