### ISSUE TITLE
[OBS / S3] Error: error creating bucket tfstate-governance: DeregisterUserId

### ISSUE THREAD

**Issue by rramge** [opentelekomcloud/terraform-provider-opentelekomcloud#1826]
# Terraform provider version

Terraform v1.3.0-alpha20220706
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.30.0

# Affected Resource(s)

opentelekomcloud_obs_bucket
opentelekomcloud_s3_bucket

# Terraform Configuration Files

This is an S3 example for calling the modules linked below, OBS is basically identical except for some additional minor features S3 doesn't support.

```hcl
module "bucket_test" {

  source = "../modules/terraform-opentelekomcloud-s3_bucket"

  #bucket_name = "tfstate"

  #log_target_bucket = module.bucket_logging.bucket_id

  #website_redirect_all_requests_to = "https://ict.technology" # supersedes the document variables
  # and the routing rules

  website_index_document     = "index.html"
  website_error_document     = "error.jpg"

  website_routing_rules_file = "${path.root}/website_routing_rules.json" # supersedes website_routing_rules, but only if the file exists from the module's perspective
  website_routing_rules      = <<EOF
        [{
    "Condition": {
        "KeyPrefixEquals": "docs/"
    },
    "Redirect": {
        "ReplaceKeyPrefixWith": "documents/"
    }
   }]
   EOF

  #cors_allowed_origins = ["https://s3-website-test.hashicorp.com"]
  #cors_allowed_methods = ["PUT", "POST"]

  lifecycle_rule = {
    "myrule" = {
      name    = "MyRule"
      enabled = true
      prefix  = ""
    },
  }

  expiration = [{
    days = 365
  }]

  noncurrent_version_expiration = [{
    days          = 365
    storage_class = "WARM"
  }]
}

```

OBS module: [https://gitlab.ict.technology/ioda/tf/modules/terraform-opentelekomcloud-obs_bucket](https://gitlab.ict.technology/ioda/tf/modules/terraform-opentelekomcloud-obs_bucket)
S3 module: [https://gitlab.ict.technology/ioda/tf/modules/terraform-opentelekomcloud-s3_bucket](https://gitlab.ict.technology/ioda/tf/modules/terraform-opentelekomcloud-s3_bucket)

# Debug Output/Panic Output

```
│ Error: error creating bucket tfstate-governance: DeregisterUserId,
│  Reason: This userid belongs to an OBS deregistered user.
│ 
│   with module.tfstate.opentelekomcloud_obs_bucket.this,
│   on ../modules/terraform-opentelekomcloud-obs_bucket/main.tf line 15, in resource "opentelekomcloud_obs_bucket" "this":
│   15: resource "opentelekomcloud_obs_bucket" "this" {
│ 
╵
╷
│ Error: error creating S3 bucket: DeregisterUserId: This userid belongs to an OBS deregistered user.
│ 	status code: 403, request id: 000001821AAE511D4814465A0BBDE719, host id: 32AAAQAAEAABAAAQAAEAABAAAQAAEAABCScvWn8py0CgUd7DE7+DbkC2UuD+BeXD
│ 
│   with module.bucket_test.opentelekomcloud_s3_bucket.this,
│   on ../modules/terraform-opentelekomcloud-s3_bucket/main.tf line 15, in resource "opentelekomcloud_s3_bucket" "this":
│   15: resource "opentelekomcloud_s3_bucket" "this" {
│ 
╵
```

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

**It worked until yesterday, now the bucket creation of both OBS and S3 are broken.**

# Actual Behavior

See error message above.

What is a DeregisterUserId, / "OBS Deregistered User" and how to handle this situation?

# Important Factoids

The user under which this 'terraform apply' is executed has full admin rights in the tenancy.

# References

**Comment by rramge** [comment]
Starting today, I also get error messages in the OTC webconsole which may shed some light on what is going on. It's seems like the entire tenancy got disabled; data in buckets can not be accessed, VMs are created but only in "Stopped" state, and so on.

This might explain the mystery, but still the provider needs to handle the error code somehow, e.g. by displaying a proper error message.

Cheers,

Ralf

**Comment by artem-lifshits** [comment]
Hello @rramge you are using `storage_class` in `noncurrent_version_expiration` while it's not supported in `S3` resource. Maybe it's not the issue but that's the first that I noticed here.

So the end setting would be like this:
```
resource "opentelekomcloud_s3_bucket" "bucket" {
  bucket = "terra-bucket"
  website {
    index_document = "index.html"
    error_document = "error.html"
    routing_rules = <<EOF
[{
    "Condition": {
        "KeyPrefixEquals": "docs/"
    },
    "Redirect": {
        "ReplaceKeyPrefixWith": "documents/"
    }
}]
EOF
  }

  lifecycle_rule {
    enabled = true
    prefix = ""
    expiration {
      days = 365
    }
    noncurrent_version_expiration {
      days = 365
    }

  }
}
```

Which was working for me:
```
opentelekomcloud_s3_bucket.bucket: Creating...
opentelekomcloud_s3_bucket.bucket: Creation complete after 5s [id=terra-43]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Comment by rramge** [comment]
@artem-lifshits I am pretty sure that this DeregisterUserId has been connected to an issue which appeared in our eu-de environment after an OTC update back then, which caused everything to work but totally closed us out of Object Storage operations, including on the webconsole. I guess somehow our tenancy admins became "Deregistered Users" or something like that.
This has lead to an OTC internal issue being raised and I think we can close this issue for you now, except if you have a general interest in this error message.

Thanks for pointing out the noncurrent_version_expiration detail.

**Comment by artem-lifshits** [comment]
@rramge I see, if there's some update on the issue please reopen.

Closing for now.
