### ISSUE TITLE
cannot unmarshal number 6.5 into Go struct

### ISSUE THREAD

**Issue by ddimasik** [opentelekomcloud/terraform-provider-opentelekomcloud#1832]
# Terraform provider version
1.30.1

# Affected Resource(s)
opentelekomcloud_csbs_backup_v1

# Terraform Configuration Files

```hcl
resource "opentelekomcloud_csbs_backup_v1" "backup_v1" {
   for_each = {for vm in module.instances.instances_output: 
              vm.name => vm
              if var.create_backup == true}            
  resource_id = each.value.id
  backup_name = each.value.name
  resource_type = "OS::Nova::Server"
  tags {
      key   = "terraformed"
      value = "at-${formatdate("YYYY-MM-DD", timestamp())}"
    }
 
  lifecycle {
    create_before_destroy = true
  }
}
```

# Debug Output/Panic Output
https://gist.github.com/ddimasik/5c27bcbf35fb631cca9c008d2aaa0862

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior
Backup created and no error message appeared

# Actual Behavior
Backup created and error message appeared

# Important Factoids

# References

**Comment by anton-sidelnikov** [comment]
@ddimasik  please check

**Comment by ddimasik** [comment]
@anton-sidelnikov Great! It works like a charm, thank you very much!
