### ISSUE TITLE
[DCS] Capacity not supporting floats

### ISSUE THREAD

**Issue by Dustlayer** [opentelekomcloud/terraform-provider-opentelekomcloud#1839]
# Terraform provider version
Terraform Provider Version: 1.30.1

# Affected Resource(s)
- opentelekomcloud_dcs_instance_v1

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_dcs_instance_v1" "redis_instance" {
  name           = "redis-instance"
  engine_version = "5.0"
  password       = "random_secure_password"
  engine         = "Redis"
  capacity       = 0.125
  vpc_id         = opentelekomcloud_vpc_v1.vpc_v1.id

  security_group_id = opentelekomcloud_networking_secgroup_v2.redis_secgroup.id
  subnet_id         = opentelekomcloud_vpc_subnet_v1.subnet_v1.id
  available_zones   = [data.opentelekomcloud_dcs_az_v1.redis_az.id]
  product_id        = data.opentelekomcloud_dcs_product_v1.redis_product.id
}
```

# Debug Output/Panic Output
```
│ Error: Attribute must be a whole number, got 0.125
│ 
│   with opentelekomcloud_dcs_instance_v1.redis_instance,
│   on instance-resources.tf line 30, in resource "opentelekomcloud_dcs_instance_v1" "redis_instance":
│   30:   capacity       = 0.125
```

# Steps to Reproduce
1. `terraform plan` or `terraform apply`

# Expected Behavior
I expected that the resource supports float values as capacity.
The [documentation of the OTC API](https://docs.otc.t-systems.com/api/dcs/dcs-api-0312004.html) states:

> For a single-node or master/standby DCS Redis 4.0 or 5.0 instance, the value can be 0.125, 0.25, 0.5, 1, 2, 4, 8, 16, 32, 24, 48, or 64. For a Redis Cluster DCS Redis 4.0 or 5.0 instance, the value can be 4, 8, 16, 24, 32, 48, 64, 96, 128, 192, 256, 384, 512, 768, or 1024.

# Actual Behavior
Error saying `Attribute must be a whole number, got 0.125`

# Important Factoids
Nothing special.

# References
-

**Comment by Aloento** [comment]
https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/1851
