### ISSUE TITLE
Error: unable to query groups: Too many requests

### ISSUE THREAD

**Issue by shaderecker** [opentelekomcloud/terraform-provider-opentelekomcloud#1844]
# Terraform provider version

Terraform v1.2.6
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.30.2

# Affected Resource(s)

opentelekomcloud_identity_group_membership_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_identity_user_v3" "user" {
  for_each = var.users

  name               = "ta_${each.key}"
  description        = "TA ${each.value["full_name"]}"
  email              = each.value["email"]
  send_welcome_email = true
}

resource "opentelekomcloud_identity_project_v3" "project" {
  for_each = var.users

  name        = "eu-nl_ta_${each.key}"
  description = "TA ${each.value["full_name"]}"
}

resource "opentelekomcloud_identity_group_v3" "group" {
  for_each = var.users

  name        = "ta_${each.key}"
  description = "TA ${each.value["full_name"]}"
}

resource "opentelekomcloud_identity_group_membership_v3" "membership" {
  for_each = var.users

  group = opentelekomcloud_identity_group_v3.group[each.key].id
  users = [opentelekomcloud_identity_user_v3.user[each.key].id]
}

resource "opentelekomcloud_identity_role_assignment_v3" "role_assignment" {
  for_each = var.users

  group_id   = opentelekomcloud_identity_group_v3.group[each.key].id
  project_id = opentelekomcloud_identity_project_v3.project[each.key].id
  role_id    = opentelekomcloud_identity_role_v3.role.id
}

```

# Debug Output/Panic Output

```
 Error: unable to query groups: Too many requests have been sent in a given amount of time. Pause requests, wait up to one minute, and try again.
│
│   with opentelekomcloud_identity_group_membership_v3.membership["username"],
│   on main.tf line 24, in resource "opentelekomcloud_identity_group_membership_v3" "membership":
│   24: resource "opentelekomcloud_identity_group_membership_v3" "membership" {

```

# Steps to Reproduce

1. `terraform plan`
2. Having more than 50 user groups, now I run into this issue

# Expected Behavior

I get the Terraform plan

# Actual Behavior

Getting rate limited

# Important Factoids

# References

https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues?q=is%3Aissue+%22Too+many+requests%22

**Comment by artem-lifshits** [comment]
Hello @shaderecker fix will be available in new release this week.

**Comment by shaderecker** [comment]
Hi @artem-lifshits,
I'm back from vacation and tested the new provider version 1.31.1.
However it seem that I still get rate limited. It is the same error message as before.

**Comment by artem-lifshits** [comment]
Hello @shaderecker I've opened an internal ticket on requests limit increase for IAM components:
https://jira.tsi-dev.otc-service.com/browse/DM-4807

**Comment by eumel8** [comment]
Hi @artem-lifshits,

you have an answer from the internal ticket? I have the same error message on creating an ELB with 3 pools and 2 servers and when I remember right you already optimized token handling in this area.

thx

**Comment by lego963** [comment]
@eumel8 yes, you are right. We did improvements there. Can you paste here resources which you use?

**Comment by eumel8** [comment]
@lego963 This problem is solved. I mixed up HTTP Listener with TCP Backend Server Group, which is not more tolerated on OTC site. I think terraform tried too often this API calls in a loop and I ended up with 409. Could be an option to compare this during the plan stage and raised this  as error without and API calls.

**Comment by lego963** [comment]
@eumel8 great, but if you face this issue again please add comment here with your tf config.
https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1848

**Comment by anton-sidelnikov** [comment]
All `Too many requests have been sent in a given amount of time. Pause requests, wait up to one minute, and try again.` errors should be properly handled in 1.32.1
