### ISSUE TITLE
error sending a welcome email: {"error": {"code": 400,"message": "User not bind email.","title": "Bad Request"}}

### ISSUE THREAD

**Issue by shaderecker** [opentelekomcloud/terraform-provider-opentelekomcloud#1850]
# Terraform provider version

Terraform v1.2.6
on linux_amd64

* provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.30.2

# Affected Resource(s)

opentelekomcloud_identity_user_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_identity_user_v3" "user" {
  for_each = var.users

  name               = "ta_${each.key}"
  description        = "TA ${each.value["full_name"]}"
  email              = each.value["email"]
  send_welcome_email = true
}
```

# Debug Output/Panic Output

```
│ Error: error sending a welcome email: Bad request with: [POST https://iam.eu-de.otc.t-systems.com/v3.0/OS-USER/users/5df0849dd2a14394aaa429022d80652b/welcome], error message: {"error": {"code": 400,"message": "User not bind email.","title": "Bad Request"}}
│ 
│   with opentelekomcloud_identity_user_v3.user["username"],
│   on main.tf line 1, in resource "opentelekomcloud_identity_user_v3" "user":
│    1: resource "opentelekomcloud_identity_user_v3" "user" {
```

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

The user gets created successfully.

# Actual Behavior

The user fails to create with the error posted above, although an email address is provided.
This happens occasionally when I create multiple users (e.g. three) in one run.
It seems like a race condition where sometimes it wants to send the welcome email before the user was completely created.

# Important Factoids

# References

**Comment by artem-lifshits** [comment]
Hi @shaderecker I've tested this config several times - with 3-5 users, wasn't able to reproduce the issue.
Can you check the vars part please?
```
resource "opentelekomcloud_identity_user_v3" "user" {
  for_each = var.users

  name               = "ta_${each.key}"
  description        = "TA ${each.value["full_name"]}"
  email              = each.value["email"]
  send_welcome_email = true
}

variable "users" {
    default = {
        "user1" = {
            "full_name": "bla-bla1",
            "email": "test1@mail.com"
        },
        "user2" = {
            "full_name": "bla-bla2",
            "email": "test2@mail.com"
        },
        "user3" = {
            "full_name": "bla-bla3",
            "email": "test3@mail.com"
        }
    }
}
```

**Comment by shaderecker** [comment]
Hi @artem-lifshits I also tested with your config a couple of times but could not reproduce it now.
As I said it only happens occasionally :/
In my CI/CD pipeline (Github Actions) it happened three times in the past, which annoyed me enough to open this ticket.

What I can add: A second re-run of the TF config then works and everything gets created normally.

**Comment by artem-lifshits** [comment]
This problem might be related to throttling issue (described in #1848), especially if user creation config is used with a couple of other resources.

During the research I've also noticed that we lack a validations for ``opentelekomcloud_identity_user_v3``, currently working on a PR for it.

**Comment by artem-lifshits** [comment]
Hello @shaderecker can you please check if the issue remains now?

**Comment by shaderecker** [comment]
Hi @artem-lifshits, I cannot reproduce it right now.
So I will close the issue for now.
