### ISSUE TITLE
[DCS] updated in-place error

### ISSUE THREAD

**Issue by Aloento** [opentelekomcloud/terraform-provider-opentelekomcloud#1863]
When run the test `TestAccDcsInstancesV1_basic`
we got this:
```
=== RUN   TestAccDcsInstancesV1_basic
=== PAUSE TestAccDcsInstancesV1_basic
=== CONT  TestAccDcsInstancesV1_basic
    resource_opentelekomcloud_dcs_instance_v1_test.go:24: Step 1/1 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # opentelekomcloud_dcs_instance_v1.instance_1 will be updated in-place
          ~ resource "opentelekomcloud_dcs_instance_v1" "instance_1" {
                id                 = "37b0ae11-20b2-46b7-b0a0-4d1db57a9d70"
                name               = "dcs_instance_k0oxp"
              + security_group_id  = "400e4d31-2b18-4d25-b516-58efeeef54b3"
                # (21 unchanged attributes hidden)
        
                # (2 unchanged blocks hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccDcsInstancesV1_basic (78.14s)

FAIL
```

In the console, the instance has been successfully created.

![image](https://user-images.githubusercontent.com/11802769/182367750-38a7d3a0-afec-4356-b07d-3f7bda9ccca0.png)

https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/1851

**Comment by Aloento** [comment]
Some analysis

`resourceDcsInstancesV1Read` returns null correctly.
`resourceDcsInstancesV1Create` also returns null correctly.
`Capacity` and `CapacityMinor` are read correctly.

![image](https://user-images.githubusercontent.com/11802769/182374117-87027311-4847-4551-b3ba-1c9b3e40db3c.png)

No call to `resourceDcsInstancesV1Update`.

![image](https://user-images.githubusercontent.com/11802769/182380358-38ba70ca-fa21-4dd4-8a01-ade42ebce749.png)
![image](https://user-images.githubusercontent.com/11802769/182380363-46ec6a56-feb1-4c7d-a85b-c4fe7527d8f9.png)
Perhaps returning empty is normal.

**Comment by Aloento** [comment]
This is an OTC bug that is tracked here:
BUG: DCS: Null "security_group_id" returned Query_DCS_Instance API
OTCORC-1589

**Comment by anton-sidelnikov** [comment]
I think we need to wait resolving inside OTC and the we can close on our side

**Comment by Aloento** [comment]
Moved to https://jira.tsi-dev.otc-service.com/browse/OTCORC-1614
and Status:DONE
