### ISSUE TITLE
[OBS] Swiss-Region (eu-ch2) - OBS Bucket creation not possible 

### ISSUE THREAD

**Issue by uli-max** [opentelekomcloud/terraform-provider-opentelekomcloud#1872]
# Terraform provider version

Terraform v1.2.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.3.2
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.30.2

# Affected Resource(s)

opentelekomcloud_obs_bucket

# Terraform Configuration Files
```hcl

resource "opentelekomcloud_obs_bucket" "tf_remote_state" {
  bucket     = local.bucket_name
  acl        = "private"
  versioning = true
  storage_class = "STANDARD"
  server_side_encryption {
    algorithm  = "kms"
    kms_key_id = opentelekomcloud_kms_key_v1.tf_remote_state_bucket_kms_key.id
  }
}

```

# Debug Output/Panic Output

╷
│ Error: error getting storage class of OBS bucket eu-ch2-uli-cce-showcase-v2-tfstate: MethodNotAllowed,
│  Reason: The specified method is not allowed against this resource.
│
│   with opentelekomcloud_obs_bucket.tf_remote_state,
│   on main.tf line 21, in resource "opentelekomcloud_obs_bucket" "tf_remote_state":
│   21: resource "opentelekomcloud_obs_bucket" "tf_remote_state" {
│
╵

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

Create the bucket and accept return the values.  

# Actual Behavior

Bucket is created and is visible in console. 
It is idependend from the server side encryption, same for non crypted bucket.
It looks like that provider can not access api and request the storage class.
Infact there is actually only STANDARD (Normal OBS Storage) in swiss region available.  

# Important Factoids

No 

# References

No

**Comment by anton-sidelnikov** [comment]
@artem-lifshits it can be the same issue like in #1886

**Comment by artem-lifshits** [comment]
Hello @uli-max bucket creation should be working in new terraform ``v1.31.2``, please check.

**Comment by uli-max** [comment]
I can confirm it is now working!
opentelekomcloud_obs_bucket.tf_remote_state: Creating...
opentelekomcloud_obs_bucket.tf_remote_state: Creation complete after 1s [id=eu-ch2-uli-cce-showcase-v2-tfstate]

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Thanks !!!
