### ISSUE TITLE
[VBS] week_frequency must have exactly one item

### ISSUE THREAD

**Issue by rramge** [opentelekomcloud/terraform-provider-opentelekomcloud#1874]
# Terraform provider version

```
Terraform v1.3.0-alpha20220803
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.31.0
```

# Affected Resource(s)

opentelekomcloud_vbs_backup_policy_v2

# Terraform Configuration Files
```hcl
module "volbackup" {
  source = "../../modules/terraform-opentelekomcloud-vbs"

  backup_policies = {
    gold = { name = "Gold", start_time = "00, 12", frequency_numdays = 1, retention_days = 365 }
    silver = { name = "Silver", start_time = "00", frequency_numdays = 1, retention_days = 30, retain_first_backup = "Y" }
    bronze = { name = "Bronze", start_time = "00", frequency_weekdays = "FRI,SUN", retention_days = 30, retain_first_backup = "Y" }
  }
}
```
Module: [https://gitlab.ict.technology/ioda/tf/modules/terraform-opentelekomcloud-vbs](https://gitlab.ict.technology/ioda/tf/modules/terraform-opentelekomcloud-vbs)

# Debug Output/Panic Output

```
module.volbackup.opentelekomcloud_vbs_backup_policy_v2.this["bronze"]: Modifying... [id=0665d70b-4158-465c-acb3-a7387f673082]
╷
│ Error: expected item of week_frequency to be one of [SUN MON TUE WED THU FRI SAT], got FRI,SUN
│ 
│   with module.volbackup.opentelekomcloud_vbs_backup_policy_v2.this["bronze"],
│   on ../../modules/terraform-opentelekomcloud-vbs/main.tf line 1, in resource "opentelekomcloud_vbs_backup_policy_v2" "this":
│    1: resource "opentelekomcloud_vbs_backup_policy_v2" "this" {
│ 
╵
```

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

The documentation states:

`(Optional) Specifies on which days of each week backup jobs are executed. The value can be one or more of the following: SUN, MON, TUE, WED, THU, FRI, SAT. Either this field or frequency must be specified.`

# Actual Behavior

If the value has more than one weekday, the provider accepts the value and the API throws an error.
If the value is an empty list [] (not null) and "frequency" is specified instead, the provider accepts the values and the API throws an error. This error can be handled on Terraform module level, so it has a low priority (for me).

I consider the Provider and the documentation being correct in both cases, the issue is in my opinion an OTC issue. But maybe you see this differently and need to restrict the provider functionality, please investigate and discuss internally.

# Important Factoids

Test in OTC eu-de.

# References

**Comment by anton-sidelnikov** [comment]
@rramge, you should pass week_days as separated list items:
resource "opentelekomcloud_vbs_backup_policy_v2" "vbs" {
  name                = "policy"
  start_time          = "00:00,12:00"
  retain_first_backup = "N"
  rentention_day      = 30
  week_frequency      = ["MON", "WED", "SAT"]
}

**Comment by rramge** [comment]
Thank you for the info, I will test during the next days.

**Comment by rramge** [comment]
You are right.

This works:

```
      + week_frequency        = [
          + "MON",
          + "WED",
          + "SAT",
        ]
```

This result of tolist(string) doesn't work:

```
      + week_frequency        = [
          + "SUN, FRI",
        ]
```

Thank you :-)
