### ISSUE TITLE
[VBS] Please add a timeout block to opentelekomcloud_vbs_backup_v2

### ISSUE THREAD

**Issue by rramge** [opentelekomcloud/terraform-provider-opentelekomcloud#1875]
# Description of the enhancement

Resource: opentelekomcloud_vbs_backup_v2

The OTC backend is ridiculously slow when shoveling data, and backups of even very small volumes far below 1 TB take a very long time and run into timeouts. 

The result is that there is no backup in the state, but it still exists in the infrastructure and appears on the billing invoice.

Please add a timeout block to the resource, for example something like the pretty common:

```
  timeouts {
    create = "24h",
    update = "24h",
    delete = "10m"
  }
```

Nice to have: If a timeout occurs, please add the resource to the state and mark it as tainted. This would help with the billing issue.

Kind regards,

Ralf

**Comment by anton-sidelnikov** [comment]
@rramge 
This block already used in resource:
```
resource "opentelekomcloud_blockstorage_volume_v2" "volume_1" {
  name        = "volume_123"
  description = "first test volume"
  size        = 40
  cascade     = true
}

resource "opentelekomcloud_vbs_backup_v2" "backup_1" {
  volume_id   = opentelekomcloud_blockstorage_volume_v2.volume_1.id
  name        = "vbs-backup"
  description = "Backup_Demo"

  timeouts {
    create = "5m"
    delete = "5m"
  }
}
```

**Comment by rramge** [comment]
@anton-sidelnikov  You are right. I think I ran into an error because I also had an update argument in there when I tried.

Maybe you want to add the existence of the block to the documentation? It's not mentioned in there.

Thank you and bye,

Ralf
