### ISSUE TITLE
[CSBS] backup provider ID datasource

### ISSUE THREAD

**Issue by rramge** [opentelekomcloud/terraform-provider-opentelekomcloud#1877]
# Description of the enhancement
Hello,

the documentation for opentelekomcloud_csbs_backup_policy_v1 states: 

[provider_id](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/csbs_backup_policy_v1#provider_id) - (Required) Specifies backup provider ID. Default value is fc4d5750-22e7-4798-8a46-f48f62c4c1da

Can you please add a datasource for retrieving the backup provider ID, so we don't have to hardcode the given ID in modules everywhere? I am also concerned that this ID could differ in different public and private cloud regions sooner or later.

Thanks,

Ralf

**Comment by Aloento** [comment]
This value distinguishes whether the backup target is a server or a disk.

`fc4d5750-22e7-4798-8a46-f48f62c4c1da` indicates that it is a server, 
and you can't modify this value, and you can only fill it in.

We will consider hiding this parameter.
That way you don't have to worry about it changing.

**Comment by rramge** [comment]
Well, a pretty complicated way to tell if it's a server or disk :-) But as long as it won't change, I'm cool with it. Hiding it would make sense with the next major release of the provider, IMHO.
