### ISSUE TITLE
Cannot automate renewing of certificates because OTC_PASSWORD for the user expires

### ISSUE THREAD

**Issue by flodev** [opentelekomcloud/terraform-provider-opentelekomcloud#1879]
# Description of the enhancement
Hi,

we would like to automate the renewal of certificates using github actions.
Our problem is that acme_certificate requires a username and password and that the password for that user expires from time to time which is related to OTC rules.
This makes us unable to automate the process.
Isn't it possible to use otc key and secret only?

```terraform
resource "acme_certificate" "..." {
  for_each           = local.certificate_domains
  account_key_pem    = ...
  common_name        = each.value.name
  min_days_remaining = 30

  dns_challenge {
    provider = "otc"

    config = {
      OTC_DOMAIN_NAME       = "434343"
      OTC_IDENTITY_ENDPOINT = "https://iam.eu-de.otc.t-systems.com:443/v3/auth/tokens"
      OTC_PROJECT_NAME      = "eu-de"
      OTC_USER_NAME         = "our-terraform-user"
      OTC_PASSWORD          = var.OTC_PASSWORD
    }
  }
}
```

**Comment by anton-sidelnikov** [comment]
@flodev Sorry, but currently we cannot use ak/sk in this resources. You can try some third party for password rotation like Vault (https://github.com/opentelekomcloud/vault-plugin-secrets-openstack)

**Comment by outcatcher** [comment]
@anton-sidelnikov actually both SDK and provider should support AK/SK for most of resources. But that's not the case here.

@flodev 
I see that you're using [`acme_certificate`](https://registry.terraform.io/providers/vancluever/acme/latest/docs) provider, as far as I can see it is using not OTC provider, nor [OTC Go SDK](https://github.com/opentelekomcloud/gophertelekomcloud), but [`acme-lego`](https://github.com/go-acme/lego/blob/master/providers/dns/otc/otc.go) package. I would suggest requesting AK/SK support in those projects.

**Comment by rramge** [comment]
Or simply install acme.sh (https://github.com/acmesh-official/acme.sh) and call it via a local_exec provisioners. Provisioners are evil, but better than nothing in such a case.

I think about writing an acme Module for OTC at some point, but at the moment this has not a real priority and will not happen in the foreseeable future.
