### ISSUE TITLE
Cannot define conditions in custom policies attached to a role

### ISSUE THREAD

**Issue by carhartl** [opentelekomcloud/terraform-provider-opentelekomcloud#1881]
# Using conditions in custom policies

I would like to be able to make custom policies more fine-grained by specifying a condition, like so:

```json
{
    "Version": "1.1",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iam:credentials:createCredential"
            ],
            "Condition": {
                "StringEquals": {
                    "g:UserName": [
                        "foo"
                    ]
                }
            }
        }
    ]
}
```

At the moment the `opentelekomcloud_identity_role_v3` resource only allows statement blocks with `action`, `effect`, `resource`.

**Comment by artem-lifshits** [comment]
Hi @carhartl this feature will be added in the next release on 1st September. 
Please reopen the issue if you have some troubles with it.
