### ISSUE TITLE
opentelekomcloud_identity_credential_v3 returns empty access secret

### ISSUE THREAD

**Issue by simonszu** [opentelekomcloud/terraform-provider-opentelekomcloud#1884]
# Terraform provider version
1.31

# Affected Resource(s)
opentelekomcloud_identity_user_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_identity_user_v3" "arangodb_backup_user" {
  name      = "${var.env}_arangodb_backup"
  password  = var.admin_password
}

resource "opentelekomcloud_identity_credential_v3" "arangodb_access_key" {
  user_id     = opentelekomcloud_identity_user_v3.arangodb_backup_user.id
  description = "Created by terraform"
}

resource "kubectl_manifest" "arangodb_backup_secret" {
  yaml_body = templatefile("${path.module}/templates/backup/secrets.yaml", {
    accesskey     = base64encode(opentelekomcloud_identity_credential_v3.arangodb_access_key.access)
    secret        = base64encode(opentelekomcloud_identity_credential_v3.arangodb_access_key.secret)
    root-password = base64encode(var.arango_root_password) 
  })
  depends_on = [
    kubernetes_namespace.arangodb_namespace,
    opentelekomcloud_identity_credential_v3.arangodb_access_key
  ]
}
```

# Debug Output/Panic Output
╷
│ Error: Invalid function argument
│ 
│   on modules/arangodb/backup.tf line 84, in resource "kubectl_manifest" "arangodb_backup_secret":
│   84:     secret        = base64encode(opentelekomcloud_identity_credential_v3.arangodb_access_key.secret)
│     ├────────────────
│     │ opentelekomcloud_identity_credential_v3.arangodb_access_key.secret is null
│ 
│ Invalid value for "str" parameter: argument must not be null.

# Steps to Reproduce
0. Empty tenant
1. `terraform apply`

# Expected Behavior
The k8s secret should be created with the resource's secret attribute

# Actual Behavior
The access key pair gets generated and is visible in the web frontend. The provider module does not return the secret for further reusing.

**Comment by lego963** [comment]
@simonszu today will be new release with fix #1869

**Comment by simonszu** [comment]
@lego963 Nice, thank you. Depending on time zones i will check it tomorrow :)

**Comment by simonszu** [comment]
I'm afraid but after upgrading to 1.31.1 i still have the same problem. 
``` 
Error: Error in function call
│ 
│   on modules/arangodb/backup.tf line 82, in resource "kubectl_manifest" "arangodb_backup_secret":
│   82:   yaml_body = templatefile("${path.module}/templates/backup/secrets.yaml", {
│   83:     accesskey     = base64encode(opentelekomcloud_identity_credential_v3.arangodb_access_key.access)
│   84:     secret        = opentelekomcloud_identity_credential_v3.arangodb_access_key.secret
│   85:     root-password = base64encode(var.arango_root_password) 
│   86:   })
│     ├────────────────
│     │ opentelekomcloud_identity_credential_v3.arangodb_access_key.access has a sensitive value
│     │ opentelekomcloud_identity_credential_v3.arangodb_access_key.secret has a sensitive value
│     │ path.module is "modules/arangodb"
│     │ var.arango_root_password is "xyz"
│ 
│ Call to function "templatefile" failed: modules/arangodb/templates/backup/secrets.yaml:9,13-19: Invalid template interpolation value; The expression result is null. Cannot include a
│ null value in a string template..
```

**Comment by simonszu** [comment]
I have checked the terraform state of the resource created by the `opentelekomcloud_identity_credential_v3` module, and indeed the secret is not properly fetched and returned: 

```json
          "attributes": {
            "access": "H2IK8WKN0BYCMP6BOZDZ",
            "create_time": "2022-08-17T09:52:48.831538Z",
            "description": "Created by terraform",
            "id": "H2IK8WKN0BYCMP6BOZDZ",
            "key_fingerprint": null,
            "last_use_time": "2022-08-17T09:52:48.831538Z",
            "pgp_key": null,
            "secret": null,
            "status": "active",
            "user_id": "26bb8a0aa7d34a37938b1f761a65fb8c"
          },
```

**Comment by simonszu** [comment]
Additionally, the tfstate file of an older environment we deployed with the same terraform code has an actual value for the secret.

**Comment by vladimirvshivkov** [comment]
@simonszu 
try to recreate the credential and try again.
the reason is that the ability to store unencrypted secret in state file was removed in the previous release.
in release 1.31.1 user may now choose to encrypt secret or not by setting pgp.
but it should be recreated and put in state file by terraform.

so, please, try to recreate and give us feedback

**Comment by simonszu** [comment]
Yeah, thanks. Deleteing and recreating did the trick :)
