### ISSUE TITLE
DNS change in v1.30.2 (#1829) seems to break existing terraform code

### ISSUE THREAD

**Issue by pwurbs** [opentelekomcloud/terraform-provider-opentelekomcloud#1885]
Before the change I used escaping to specify TXT records.  
`"\"blablabla"\"`
This worked and configured the TXT record in OTC with double quotes:
`"blablabla"`

Now, after upgrading the allowed OTC provider version, the apply job wanted to change the existing resource:

```
16:49:28        ~ records     = [
16:49:28            + "\"v=spf1 mx a:otc-de-spf.mms.t-systems-service.com -all\"",
16:49:28            - "v=spf1 mx a:otc-de-spf.mms.t-systems-service.com -all",
```

We canceled the job, because we were afraid, that the escape would be configured as part of the TXT string in OTC.
We hope, that a simple delete of `\"` in the code can fix the issue. At least this is our understanding of the provider change.

if you agree, then you should mention this in the doc and in the release notes.

**Comment by anton-sidelnikov** [comment]
@pwurbs currently escaping done inside terraform, you should pass clear string.
https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/devel/releasenotes/notes/fix-txt-recordsets-6383b965e457ad71.yaml - it mentioned in releasenotes, but you're right we should update doc with example.

**Comment by pwurbs** [comment]
@anton-sidelnikov Yes, this is what we plan to do. And I know this short release notes text.
I only want to say that this is a breaking change because it leads to forced (and faulty) changes in the resources. So you should tell  in the release notes (and/or in the doc).  That existing manifests including escaping must be changed.

**Comment by anton-sidelnikov** [comment]
Released with new doc
