### ISSUE TITLE
Storage Class is not supported in eu-ch2

### ISSUE THREAD

**Issue by generalpax** [opentelekomcloud/terraform-provider-opentelekomcloud#1886]
# Terraform provider version

```bash
[linux@io4da-jump upload]$ terraform -v
Terraform v1.3.0-alpha20220803
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.31.1
```

# Affected Resource(s)

- opentelekomcloud_obs_bucket_object

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_obs_bucket" "uploadtest" {
  bucket = "uploadtest"
  acl    = "private"
}
resource "opentelekomcloud_obs_bucket_object" "object" {
  bucket = opentelekomcloud_obs_bucket.uploadtest.bucket
  key    = "somefile"
  source = "somefile"
}
```

# Debug Output/Panic Output

```bash
[linux@io4da-jump upload]$ terraform apply
opentelekomcloud_obs_bucket.examplebucket: Refreshing state... [id=examplebuckettftest]
╷
│ Error: error getting storage class of OBS bucket examplebuckettftest: MethodNotAllowed,
│  Reason: The specified method is not allowed against this resource.
│
```

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior
file should be uploaded

# Actual Behavior
seems that storage class is not implemented in eu-ch2 api but is not choosable to false

# Important Factoids

working with TSI-CH domain eu-ch2

# References

**Comment by artem-lifshits** [comment]
Hi @generalpax bucket creation is fixed in the latest provider update ``v1.31.2``, please check.
