### ISSUE TITLE
[Autoscaling] AS Group resources not deleted during destroy 

### ISSUE THREAD

**Issue by rramge** [opentelekomcloud/terraform-provider-opentelekomcloud#1889]
# Terraform provider version

Terraform v1.3.0-alpha20220803
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.31.1

# Affected Resource(s)

opentelekomcloud_as_group_v1

# Terraform Configuration Files

plan output is probably more useful here than a for_each loop:

```hcl
  # module.autoscaling.opentelekomcloud_as_group_v1.this["group-01"] will be created
  + resource "opentelekomcloud_as_group_v1" "this" {
      + available_zones                    = []
      + cool_down_time                     = 900
      + current_instance_number            = (known after apply)
      + delete_instances                   = "no"
      + delete_publicip                    = false
      + desire_instance_number             = 3
      + health_periodic_audit_grace_period = 600
      + health_periodic_audit_method       = "NOVA_AUDIT"
      + health_periodic_audit_time         = 5
      + id                                 = (known after apply)
      + instance_terminate_policy          = "OLD_CONFIG_OLD_INSTANCE"
      + instances                          = (known after apply)
      + max_instance_number                = 5
      + min_instance_number                = 1
      + region                             = (known after apply)
      + scaling_configuration_id           = "f96b4a3a-8c81-4c55-98a5-27370b9ba754"
      + scaling_group_name                 = "group-01"
      + status                             = (known after apply)
      + vpc_id                             = "63ec2a21-c579-46ce-8335-0895fd75bb04"

      + networks {
          + id = "a924927b-0604-426e-9a94-8a568c3f4774"
        }
    }
```

All input values are defaults excepts those specified here (argument names can differ):

```hcl
  autoscaling_groups = {
    "group-01" = {
                  scaling_group_name = "group-01"
                  min_instance_number = 1
                  max_instance_number = 5
                  desired_instance_number = 3
                  vpc_id = module.testvpc_1.vpc_id
                  subnets = [ lookup(module.testvpc_1.subnet_list, "webserver") ]
                  }
  }
```

# Debug Output/Panic Output

# Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`
3. Check ECS instances, volumes and other associated resources in OTC webconsole

# Expected Behavior

All resources which were created during the apply phase are destroyed again.

# Actual Behavior

Nothing. All resources continue to exist, and are online.
The infrastructure state is inconsistent, the IaC is no longer the "Single Source of Truth" as expected. 
Any audits will fail, potential security issue will arise (services still online which shouldn't be).
Overbilling will occur.

A second apply will create the resources again, meaning that if you defined 5 instances + 5 system disks + 5 data disks in the AS group, the first apply creates those, and a second apply then ends in adding another complete set, resulting in 10 instances, 10 system disks and 10 data disks.

# Important Factoids

Tested in OTC eu-de.

# References

**Comment by rramge** [comment]
I think this can be resolved by setting proper default values in the provider for [delete_publicip](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/as_group_v1#delete_publicip), [delete_instances](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/as_group_v1#delete_instances) and maybe [instance_terminate_policy](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/as_group_v1#instance_terminate_policy)   (I don't know what the options of instance_terminate_policy do exactly). 

I recommend doing this, to save customers from potentially unpleasant surprises.

**Comment by gtema** [comment]
@rramge: do you mean that the resources created by AS remain existing after AS configuration itself got deleted?

**Comment by rramge** [comment]
It remains after the AS group is deleted. Or the AS configuration as well (groups depend on it).

It only gets not deleted, if the user sets the optional parameters delete_publicip and delete_instances are explicitely set to "true" and "yes". If unset and left on their default values, the resources continue to exist.

Turning them into required arguments instead of optional ones could be a working solution as well, because then the users are forced to decide which behavior they want.

**Comment by gtema** [comment]
yeah, making them mandatory might be a good way. Having default values is definitely not going to save users from surprises.

**Comment by anton-sidelnikov** [comment]
Released with changes
