### ISSUE TITLE
Can opentelekomcloud_ces_alarmrule be used/extended also for (new) Event Monitoring

### ISSUE THREAD

**Issue by pwurbs** [opentelekomcloud/terraform-provider-opentelekomcloud#1896]
There is the rather new feature to configure Event Monitoring Alarm Rules.
Currently we configure it by hand. 
Is it possible to use the resource opentelekomcloud_ces_alarmrule to configure these alarms resp. can the resource be extended?

**Comment by anton-sidelnikov** [comment]
@Aloento please look at this

**Comment by Aloento** [comment]
We have recently implemented this functionality in the SDK at
https://github.com/opentelekomcloud/gophertelekomcloud/blob/devel/openstack/ces/v1/alarms/create_alarm.go

It is possible to configure it via opentelekomcloud_ces_alarmrule.
https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/fa4a86843d4659f181164cf0509219870f98b66f/opentelekomcloud/services/ces/resource_opentelekomcloud_ces_alarmrule.go#L299

Example:
https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/fa4a86843d4659f181164cf0509219870f98b66f/opentelekomcloud/acceptance/ces/resource_opentelekomcloud_ces_alarmrule_test.go#L118

**Comment by pwurbs** [comment]
Thanks. Were can I find information how to set the whole bunch of parameters in opentelekomcloud_ces_alarmrule to configure Event Monitoring alerts?

**Comment by Aloento** [comment]
@pwurbs 
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/ces_alarmrule
https://docs.otc.t-systems.com/en-us/api/ces/ces_03_0031.html

**Comment by pwurbs** [comment]
@Aloento Yes, I know this. 
But how to set the values for namespace, metric_name, dimensions (name, value). Even for ECS and ELB it was not easy to find out. For Event Monitoring I wouldn't know how to set these parameters.

E.g. the table in the referred link https://docs.otc.t-systems.com/en-us/api/ces/ces_03_0059.html doesn't include anything regarding Event Monitoring.

**Comment by Aloento** [comment]
All the services listed in this table are the ones we support monitoring. 
(List of services supported for monitoring)
Can you tell me exactly which service you want to monitor, such as CES?

**Comment by pwurbs** [comment]
Therefore I asked in my initial question, if the "Event Monitoring" is supported at all.
Unfortunately there are errors while I try to upload screenshot.

**Comment by pwurbs** [comment]
"Event Monitoring" is a rather new type of cloud eye events for which alarm rules can be configured.
For instance in case a backup failed or an ECS has been rebooted or deleted etc.

**Comment by pwurbs** [comment]
In the list of configured "Alarm Rules", these alarms are of Alarm Type = Event

**Comment by Aloento** [comment]
I have understood your need ~~we don't seem to have implemented it in TF yet~~
Can you tell me how you set it up manually? thank you~

**Comment by pwurbs** [comment]
Unfortunately, the image upload function doesn't work. 
Event Monitoring alarms can be setup like any other alarm, but in the Resource Type Listbox "Event Monitoring" has to be selected instead e.g. Elastic Cloud Server or Elastic Volume Service.
Then there are the dimensions "System event" and "Custom event" to be selected. If I select "System event", then I select an "Event Source" like "Cloud Backup and Recovery". As the last step I select the events.

**Comment by Aloento** [comment]
Is this what you want?
![image](https://user-images.githubusercontent.com/11802769/186629826-3d7549be-1a22-49a3-97b8-20192ac8d490.png)

**Comment by pwurbs** [comment]
Yes :)

**Comment by pwurbs** [comment]
Maybe it's already supported in the TF provider and I only don't know the actual values to be used for namespace, metric_name, dimensions (name, value)...

**Comment by Aloento** [comment]
I tried to create a rule with the configuration shown above and queried it out using the API and this is the result:

```json
{
    "metric_alarms": [
        {
            "alarm_id": "al1661421324562Lby9KmnPG",
            "alarm_name": "alarm-7nt7",
            "alarm_description": "",
            "metric": {
                "namespace": "SYS.ECS",
                "dimensions": [],
                "metric_name": "faultAutoRecovery"
            },
            "condition": {
                "period": 0,
                "filter": "average",
                "comparison_operator": ">=",
                "value": 1,
                "unit": "count",
                "count": 1
            },
            "alarm_level": 2,
            "alarm_type": "EVENT.SYS",
            "alarm_enabled": true,
            "alarm_action_enabled": false,
            "alarm_actions": [],
            "ok_actions": [],
            "insufficientdata_actions": [],
            "update_time": 1661421324000,
            "alarm_state": "ok"
        }
    ]
}
```

You can get the values you want by creating rules on the web and using 
GET /V1.0/{project_id}/alarms/{alarm_id}

then you got the namespace, alarm_type and metric_name
There doesn't seem to be a better way to get them at the moment.

**Comment by rramge** [comment]
The "terraform way" of retrieving such information and best practice:

1. Create the resource via mouse clicking in the web console
2. Retrieve the resource ID via the web console
3. Create an empty terraform resource. (empty meaning  "{}" only)
4. terraform import resource_name id
5. terraform state show resource_name

Then copy & paste the required arguments and their values to the empty resource. That's why the output of "terraform state show" already has the format of a resource template since TF 0.10 or something around that. 

When finished and complete, a "terraform plan" will not propose any changes, 0 to create, 0 to change, 0 to destroy.  
Just make sure you don't set any read-only value, so don't just copy & paste everything blindly.

**Comment by pwurbs** [comment]
Thanks @rramge. This is what I was looking for...

So it's my conclusion, that the OTC provider already supports alarm resources for Event Monitoring. Right?

**Comment by Aloento** [comment]
@pwurbs Yes
No need to close this issue, I need to submit this issue internally and see if I can find a better solution.

**Comment by pwurbs** [comment]
Thanks, fine for me. Maybe someone provides a documentation regarding the values to avoid time consuming reverse engineering.

**Comment by Nemental** [comment]
@rramge Unfortunately terraform import isn't available for this resource.
> Error: resource opentelekomcloud_ces_alarmrule doesn't support import

**Comment by rramge** [comment]
Well, then it should be added (https://www.terraform.io/plugin/sdkv2/resources/import) or a datasource be provided.

**Comment by Aloento** [comment]
The query function is already under development.

**Comment by dpakes** [comment]
Hello, I'm sorry if it was already explained, but it's not clear to me from the answers.
There is no option to use "alarm_type" as an argument in opentelekomcloud_ces_alarmrule so we are not able to create that resource with "Event monitoring" as alarm type. Will this option be implemented in the near future? 

Also, it would be nice to have a possibility in terraform to user Alarm templates which are in OTC. Would it be possible to implement this?

Thank you in advance

**Comment by Aloento** [comment]
Ok, this new API about this now already available.
SDK and document will update soon.

**Comment by Nemental** [comment]
Still not fixed...
`dimensions` is currently an required argument for the provider, but there is no need and technically no option to fill this argument.
As @Aloento mentioned in https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1896#issuecomment-1227054055, it's pointing to `Monitored Object    All resources`

```json
{
  "metric_alarms": [
    {
      "alarm_id": "ALARM_ID",
      "alarm_name": "alarm-6i1r",
      "alarm_description": "",
      "metric": {
        "namespace": "SYS.CBR",
        "dimensions": [],
        "metric_name": "backupFailed"
      },
      "condition": {
        "period": 0,
        "filter": "average",
        "comparison_operator": ">=",
        "value": 1,
        "unit": "count",
        "count": 1
      },
      "alarm_level": 2,
      "alarm_type": "EVENT.SYS",
      "alarm_enabled": true,
      "alarm_action_enabled": false,
      "alarm_actions": [],
      "ok_actions": [],
      "insufficientdata_actions": [],
      "update_time": 1677671037000,
      "alarm_state": "ok"
    }
  ]
}
```

```tf
resource "opentelekomcloud_ces_alarmrule" "alarm_cbr_policy_dev_daily_backup_failed" {
  alarm_name           = "alarm_cbr_policy_dev_daily_backup_failed"
  alarm_action_enabled = false

  metric {
    namespace   = "SYS.CBR"
    metric_name = "backupFailed"
  }

  condition {
    period              = 0
    filter              = "average"
    comparison_operator = ">="
    value               = 1
    unit                = "count"
    count               = 1
  }

}
```

**Comment by pwurbs** [comment]
@Aloento 
I am a bit lost regarding the status. 
- The import of opentelekomcloud_ces_alarmrule resource still doesn't seem to work
- There is still no provider docu for opentelekomcloud_ces_alarmrule rearding event monitoring
- Is the alert setup for event monitoring now implemented in opentelekomcloud_ces_alarmrule ?

**Comment by Nemental** [comment]
@Aloento Hi 👋  Can you give us some updates on this topic please? 🤝

**Comment by Aloento** [comment]
@anton-sidelnikov can you check `opentelekomcloud_ces_alarmrule / alarmevent`? thx.

**Comment by artem-lifshits** [comment]
Hello @Nemental! Either `resource_id` or `resource_group_id` is required for alerts to work. Resource id is specified in dimensions section along with `value = "instance_id"`. Value can change for some services, I will update the list soon.
```
    dimensions {
      name  = "instance_id"
      value = var.server_id
    }
```

There are no API to create resource group at the moment but it's possible to create a group through UI and reference it in TF config. I will update ces alarm rule API so `resource_group_id` could be specified instead of `dimensions` section.

**Comment by artem-lifshits** [comment]
Hello @pwurbs! Import will be available on next release.

**Comment by artem-lifshits** [comment]
I'm currently pushing orchestration squad to update documentation because it's a complete mess.
After some reverse engineering I found out that it's possible to specify alarm type, this part will be implemented in resource along with documentation.

**Comment by artem-lifshits** [comment]
@Nemental @pwurbs working on implementing events part, should also be available on next release. Will keep you updated!

**Comment by artem-lifshits** [comment]
CES event monitoring is available in latest release along with updated documentation and frequency settings for alarm rules.
