### ISSUE TITLE
Dedicated LB L4/L7 flavors?

### ISSUE THREAD

**Issue by rramge** [opentelekomcloud/terraform-provider-opentelekomcloud#1898]
# Description of the enhancement

Concerning the resource opentelekomcloud_lb_loadbalancer_v3, the documentation states:

[l4_flavor](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_loadbalancer_v3#l4_flavor) - (Optional) The ID of the Layer-4 flavor.

[l7_flavor](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_loadbalancer_v3#l7_flavor) - (Optional) The ID of the Layer-7 flavor.

Can you please add a datasource which returns vailable L4 and L7 flavors in a region? The currently existing datasource opentelekomcloud_lb_flavor_v3 is of no use, since the ID and/or name must already be known for this one.

Thanks,

Ralf

**Comment by anton-sidelnikov** [comment]
Released with new datasource
