### ISSUE TITLE
opentelekomcloud_logtank_group_v2 missing parameter ttl_in_days

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#1899]
while trying to create a log tank group: 

 error message: {"error_code":"LTS.0106","error_msg":"The log group TTL day must be integer and between 1 and 30"}

If I try to set the parameter "ttl_in_days": 

│ Can't configure a value for "ttl_in_days": its value will be decided automatically based on the result of applying this configuration.

the parameter is optional according to the OTC HelpCenter, but in fact it is mandatory on API level as well (reported to OTC operations)

possible solution: please add the parameter "ttl_in_days"

# Terraform provider version
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.31.1

# Affected Resource(s)
opentelekomcloud_logtank_group_v2

# Terraform Configuration Files
resource "opentelekomcloud_logtank_group_v2" "log_group" {
  group_name = "lts-main-group"
 //(ttl_in_days = 7)
}

# Debug Output/Panic Output
 error message: {"error_code":"LTS.0106","error_msg":"The log group TTL day must be integer and between 1 and 30"}

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior
create LTS group

# References
SCTASK0122643
https://docs.otc.t-systems.com/api/lts/lts_02_0003.html

**Comment by vladimirvshivkov** [comment]
@CHS-OTC 
Hi!
According to lts documentation, ttl_in_days parameter is fixed to 7. 
API doesn't accept any other values. 
If it is important for you to set ttl different from 7 in range from 1 to 30, we may raise internal ticket.

**Comment by CHS-OTC** [comment]
yes, you are right. i was misleaded by the error message: 
"error_code":"LTS.0106","error_msg":"The log group TTL day must be integer and between 1 and 30"
it doesnt matter what number you define for the ttl in the api call it is always set to 7 in the console. 
then I dont think it is necessary to provide a parameter but better hardcode it so it is always set to 7. Because the problem in TF is still the same, the API needs this parameter to be set.

**Comment by vladimirvshivkov** [comment]
ok, will fix it

**Comment by vladimirvshivkov** [comment]
fixed in new release
