### ISSUE TITLE
Error: error creating OpenTelekomCloud CCEv1 client: No suitable endpoint could be found in the service catalog

### ISSUE THREAD

**Issue by kucerakk** [opentelekomcloud/terraform-provider-opentelekomcloud#1901]
Hi,

https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/fa4a86843d4659f181164cf0509219870f98b66f/opentelekomcloud/services/cce/resource_opentelekomcloud_cce_node_v3.go#L741

seems to be using CceV1Client object in a CCEv3 node resource. Please check if it has some reason behind. 

# Terraform provider version

provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.31.1

# Affected Resource(s)

resource "opentelekomcloud_cce_node_v3"

# Terraform Configuration Files
example CCE cluster/node provisioning

# Debug Output/Panic Output

Error: error creating OpenTelekomCloud CCEv1 client: No suitable endpoint could be found in the service catalog.
│
│   with opentelekomcloud_cce_node_v3.node_1,
│   on cce.tf line 11, in resource "opentelekomcloud_cce_node_v3" "node_1":
│   11: resource "opentelekomcloud_cce_node_v3" "node_1" {

# Steps to Reproduce
terraform apply

# Expected Behavior

Provisioning of CCE cluster + Node should work without raising exeption.

# Actual Behavior

Provisioning of CCE cluster + Node works, but terraform reports exception.

# Important Factoids
It fails with clouds where CCEv1 version (endpoint) is not available, only CCEv3.

# References
N/A

**Comment by anton-sidelnikov** [comment]
Currently k8s metadata for nodes not exposed in Swiss, created internal incident ES-569.
