### ISSUE TITLE
opentelekomcloud_sfs_turbo_share_v1 IaC Single Source of Truth violation

### ISSUE THREAD

**Issue by rramge** [opentelekomcloud/terraform-provider-opentelekomcloud#1909]
# Terraform provider version

any

# Affected Resource(s)

opentelekomcloud_sfs_turbo_share_v1

# Expected Behavior

The Terraform / IaC code must be the "Single Source of Truth". The infrastructure must look exactly as _defined in the code_. This is also relevant for audits of any form, e.g. security audits.

# Actual Behavior

Quote from documentation:

```
SFS Turbo will create two private IP addresses and one virtual IP address under the subnet you specified. 
To ensure normal use, SFS Turbo will enable the inbound rules for ports 111, 445, 2049, 2051, 2052, and 20048 in the security group you specified.
```

If this is really the case, please stop doing this. Such things violate core DevOps principles and Immutability. Except if you have some fairy dust which magically updates the relevant .tf file in the end user's code repository and re-imports the affected resources into the state.

# Important Factoids

# References

Any DevOps basics training course.

**Comment by anton-sidelnikov** [comment]
Hi. this is not related with tf provider, this is about "how" implemented this service. I agree that is a mess, i will try to contact the responsible team.

**Comment by rramge** [comment]
@anton-sidelnikov 
I guessed so ( or feared so). Thanks for putting this on their plate again. As soon as we use SFS officially in SOTC, we will address this also from the client side.
