### ISSUE TITLE
WAF feature to adjust/set alarm page

### ISSUE THREAD

**Issue by DasLeo** [opentelekomcloud/terraform-provider-opentelekomcloud#1911]
Possibility to set the `alarm_page` using `opentelekomcloud_waf_domain_v1`
![Screenshot 2022-08-31 at 15 11 46](https://user-images.githubusercontent.com/3002846/187687558-5ea6c108-98bb-4c2a-98b3-1258a99301ae.png)

**Comment by anton-sidelnikov** [comment]
@DasLeo Hi, currently we do not have an API for this

**Comment by DasLeo** [comment]
Hey @anton-sidelnikov,

thanks for the feedback.
So what's the proper process in that case, will you file a feature request to Huawei or will this never be implemented then?

**Comment by anton-sidelnikov** [comment]
@DasLeo yesterday, I've created internal incident about this, so waiting for response

**Comment by artem-lifshits** [comment]
Corresponding ticket: https://jira.tsi-dev.otc-service.com/browse/OTCSEC-3956

**Comment by artem-lifshits** [comment]
Hello @DasLeo feature is available in latest release.
