### ISSUE TITLE
Different Networking information in state than in webconsole

### ISSUE THREAD

**Issue by rramge** [opentelekomcloud/terraform-provider-opentelekomcloud#1913]
Hi,

there is something I really don't understand and which keeps me totally baffled right now. Maybe because it's Friday and I had a tough week and my brain went FUBAR (pardon me if that's the case), but maybe I am onto something here.
This is related to #1906.

# Terraform provider version

Terraform v1.3.0-alpha20220817
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.31.1

# Affected Resource(s)

opentelekomcloud_networking_network_v2
opentelekomcloud_networking_router_interface_v2
opentelekomcloud_networking_router_v2
opentelekomcloud_networking_subnet_v2

# Terraform Configuration Files

This is the basic code @artem-lifshits posted in #1906.

```hcl
resource "opentelekomcloud_networking_subnet_v2" "databases" {
      name       = "databases"
      ip_version = 4
      cidr       = "172.23.34.0/24"
      network_id = opentelekomcloud_networking_network_v2.testnetwork-3.id
    }

resource "opentelekomcloud_networking_subnet_v2" "middleware" {
      name       = "middleware"
      ip_version = 4
      cidr       = "172.23.35.0/24"
      dns_nameservers   = ["100.125.4.25", "1.1.1.1"]
      network_id = opentelekomcloud_networking_network_v2.testnetwork-3.id
    }

resource "opentelekomcloud_networking_subnet_v2" "webserver" {
      name       = "webserver"
      ip_version = 4
      cidr       = "172.23.33.0/24"
      dns_nameservers   = ["8.8.8.8"]
      network_id = opentelekomcloud_networking_network_v2.testnetwork-3.id
    }

resource "opentelekomcloud_networking_network_v2" "testnetwork-3" {
  name           = "testnetwork-3"
  admin_state_up = true
}

resource "opentelekomcloud_networking_router_v2" "this" {
  admin_state_up = true
}

resource "opentelekomcloud_networking_router_interface_v2" "webserver" {
  router_id = opentelekomcloud_networking_router_v2.this.id
  subnet_id = opentelekomcloud_networking_subnet_v2.webserver.id
}
```

# Debug Output/Panic Output

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

The information in the OTC web console and the statefile should match.

# Actual Behavior

This is my state, as expected:

```
[rramge@ol9 12]$ tf state list
opentelekomcloud_networking_network_v2.testnetwork-3
opentelekomcloud_networking_router_interface_v2.webserver
opentelekomcloud_networking_router_v2.this
opentelekomcloud_networking_subnet_v2.databases
opentelekomcloud_networking_subnet_v2.middleware
opentelekomcloud_networking_subnet_v2.webserver
[rramge@ol9 12]$
```

These are the details of the network:

```
[rramge@ol9 12]$ tf state show opentelekomcloud_networking_network_v2.testnetwork-3
# opentelekomcloud_networking_network_v2.testnetwork-3:
resource "opentelekomcloud_networking_network_v2" "testnetwork-3" {
    admin_state_up = "true"
    id             = "c9c339ee-b962-4b38-b5e6-3beff585576a"
    name           = "testnetwork-3"
    region         = "eu-de"
    shared         = "false"
    tenant_id      = "c7b5384e487149d696b7cfc420589afe"
}
[rramge@ol9 12]$ 
```

All parameters are set, everything looks good here.
But when I log in to the console, the Network console gives me different information:

- Column "Name": not set, only "--" is displayed
- Column "IPv4 CIDR Block":  not set, only "--" is displayed (which is no suprise, I wonder why it's not a parameter of the network anyway?)

I click on the Network and get the details. What I see here:

- Even though all three subnets are in the state, only opentelekomcloud_networking_subnet_v2.databases gets displayed in the console.
- The network ID in the webconsole is d195ca1c-054d-4f67-9df9-e052d3e1e260, which is different to the ID in the statefile

Next step, I try to deploy an ECS in this network manually via webconsole.

- During network selection, an empty string ("") is displayed for testnetwork-3. When I select it, the conole complains that this field cannot be left blank. 
- Only "databases" is offered as subnet.

=> I can't deploy via the webconsole.

Now I add the following Terraform code, which is a slightly adjusted copy & paste from the opentelekomcloud_compute_instance_v2 documentation:

```
resource "opentelekomcloud_compute_instance_v2" "basic" {
  name            = "basic"
  image_id        = "b260813c-074c-432d-9685-7d9842828386"
  flavor_id       = "s2.large.4"
  key_pair        = "passwordless"
  security_groups = ["default"]

  network {
   uuid = opentelekomcloud_networking_subnet_v2.webserver.network_id 
  }
}
```

Then the API says: 

```
opentelekomcloud_compute_instance_v2.basic: Creating...
╷
│ Error: error creating OpenTelekomCloud server: Bad request with: [POST https://ecs.eu-de.otc.t-systems.com/v2.1/c7b5384e487149d696b7cfc420589afe/servers], error message: {"badRequest":{"message":"network param is illegal, no virtual private cloud found","code":"400"}}
│ 
│   with opentelekomcloud_compute_instance_v2.basic,
│   on vpc-router.tf line 37, in resource "opentelekomcloud_compute_instance_v2" "basic":
│   37: resource "opentelekomcloud_compute_instance_v2" "basic" {
│ 
╵
```

Hmm, maybe I give the wrong network ID, let's try the other one:

```
[...]
  network {
   #uuid = opentelekomcloud_networking_subnet_v2.webserver.network_id
   uuid = opentelekomcloud_networking_subnet_v2.webserver.id
  }
[...]
```

Nope, but different error:

opentelekomcloud_compute_instance_v2.basic: Creating...

```
╷
│ Error: error trying to get network information from the Network API: could not find any matching network for id 728399a6-216b-445f-a267-100f65c2c60f
│ 
│   with opentelekomcloud_compute_instance_v2.basic,
│   on vpc-router.tf line 37, in resource "opentelekomcloud_compute_instance_v2" "basic":
│   37: resource "opentelekomcloud_compute_instance_v2" "basic" {
│ 
╵
```

=> Can't add an ECS instance via webconsole, nor Terraform

So, last idea I have: I delete the resource from the state and try to import it again with the new ID the web console gave me. Maybe there's a new network_id then, which will work....

```
[rramge@ol9 12]$ tf state rm opentelekomcloud_networking_network_v2.testnetwork-3
Removed opentelekomcloud_networking_network_v2.testnetwork-3
Successfully removed 1 resource instance(s).

[rramge@ol9 12]$ tf import opentelekomcloud_networking_network_v2.testnetwork-3 d195ca1c-054d-4f67-9df9-e052d3e1e260
opentelekomcloud_networking_network_v2.testnetwork-3: Importing from ID "d195ca1c-054d-4f67-9df9-e052d3e1e260"...
opentelekomcloud_networking_network_v2.testnetwork-3: Import prepared!
  Prepared opentelekomcloud_networking_network_v2 for import
opentelekomcloud_networking_network_v2.testnetwork-3: Refreshing state... [id=d195ca1c-054d-4f67-9df9-e052d3e1e260]
╷
│ Error: Cannot import non-existent remote object
│ 
│ While attempting to import an existing object to
│ "opentelekomcloud_networking_network_v2.testnetwork-3", the provider detected that no object
│ exists with the given id. Only pre-existing objects can be imported; check that the id is
│ correct and that it is associated with the provider's configured region or endpoint, or use
│ "terraform apply" to create a new remote object for this resource.
╵
[rramge@ol9 12]$ 
```

So, importing is not possible, because the resource I see in the console doesn't exist?

Does anyone understand what is going on here and can enlighten me? Do I misunderstand something foundationally?
How can I make sure that the webconsole and the state file match?
How can I deploy an ECS instance in a networking_subnet_v2?

# Important Factoids

Tested in and examples taken from OTC eu-de.

# References

#1906 depends on this issue.

**Comment by anton-sidelnikov** [comment]
@rramge Hi, our go sdk based on openstack, but console not represent the openstack naming of the resources, please rely on statefile

**Comment by artem-lifshits** [comment]
Hello @rramge that's the issue with Openstack/AWS naming conventions which is pretty misleading. 
VPC for OTC is basically a router and information on network can't be really seen in console except for ``network id`` if ``router_interface`` is set up for it.

Network and subnet info can be seen in tfstate file/API/[otcextensions](https://github.com/opentelekomcloud/python-otcextensions).

Here's how it looks like with otcextensions:
<img width="1383" alt="Screenshot 2022-09-02 at 19 35 36" src="https://user-images.githubusercontent.com/55093318/188199095-421157c1-d613-4976-bf08-a0f2bce601a4.png">

So resources are there and can be used.
We have a milestone on improving these resource naming ([v2.0.0](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/milestone/43)), but it already has a lot of dependancies and won't be backwards compatible so it's not being pushed.

Hope this helps.

EDIT: to set VPC name please specify name in ``opentelekomcloud_networking_router_v2``

**Comment by rramge** [comment]
Okay, thanks for those details. But I am still struggling with this part: How can I place an ECS instance in a subnet?

```
resource "opentelekomcloud_compute_instance_v2" "basic" {
  name            = "basic"
  image_id        = "b260813c-074c-432d-9685-7d9842828386"
  flavor_id       = "s2.large.4"
  key_pair        = "passwordless"
  security_groups = ["default"]

  network {
   uuid = opentelekomcloud_networking_subnet_v2.webserver.network_id 
  }
}
```

```
opentelekomcloud_compute_instance_v2.basic: Creating...
╷
│ Error: error creating OpenTelekomCloud server: Bad request with: [POST https://ecs.eu-de.otc.t-systems.com/v2.1/c7b5384e487149d696b7cfc420589afe/servers], error message: {"badRequest":{"message":"network param is illegal, no virtual private cloud found","code":"400"}}
│ 
│   with opentelekomcloud_compute_instance_v2.basic,
│   on vpc-router.tf line 37, in resource "opentelekomcloud_compute_instance_v2" "basic":
│   37: resource "opentelekomcloud_compute_instance_v2" "basic" {
│ 
╵
```

**Comment by anton-sidelnikov** [comment]
> Okay, thanks for those details. But I am still struggling with this part: How can I place an ECS instance in a subnet?
> 
> ```
> resource "opentelekomcloud_compute_instance_v2" "basic" {
>   name            = "basic"
>   image_id        = "b260813c-074c-432d-9685-7d9842828386"
>   flavor_id       = "s2.large.4"
>   key_pair        = "passwordless"
>   security_groups = ["default"]
> 
>   network {
>    uuid = opentelekomcloud_networking_subnet_v2.webserver.network_id 
>   }
> }
> ```
> 
> ```
> opentelekomcloud_compute_instance_v2.basic: Creating...
> ╷
> │ Error: error creating OpenTelekomCloud server: Bad request with: [POST https://ecs.eu-de.otc.t-systems.com/v2.1/c7b5384e487149d696b7cfc420589afe/servers], error message: {"badRequest":{"message":"network param is illegal, no virtual private cloud found","code":"400"}}
> │ 
> │   with opentelekomcloud_compute_instance_v2.basic,
> │   on vpc-router.tf line 37, in resource "opentelekomcloud_compute_instance_v2" "basic":
> │   37: resource "opentelekomcloud_compute_instance_v2" "basic" {
> │ 
> ╵
> ```

Hello, thats strange i can only find configs with opentelekomcloud_vpc_subnet_v1. I will check opentelekomcloud_networking_subnet_v2
```
resource "opentelekomcloud_compute_instance_v2" "instance_1" {
  name              = "instance_1"
  availability_zone = "eu-de-01"
  metadata = {
    foo = "bar"
  }
  network {
    uuid = data.opentelekomcloud_vpc_subnet_v1.shared_subnet.network_id
  }

  tags = {
    muh = "value-create"
    kuh = "value-create"
  }
}
```

**Comment by anton-sidelnikov** [comment]
Example for v2 network, subnet attaching through port:
```
resource "opentelekomcloud_networking_subnet_v2" "subnet" {
  name            = "${var.prefix}_subnet"
  network_id      = opentelekomcloud_networking_network_v2.network.id
  cidr            = var.subnet_cidr
  dns_nameservers = ["100.125.4.25", "100.125.129.199"]
}`

resource "opentelekomcloud_compute_instance_v2" "bastion" {
  name        = "${var.scenario}_${var.name}"
  image_name  = var.bastion_image
  flavor_name = var.ecs_flavor
  key_pair    = opentelekomcloud_compute_keypair_v2.pair.name
  user_data = templatefile("${path.module}/first_boot_bastion.sh", {
    cidr            = var.subnet.cidr,
    bastion_address = local.bastion_local_ip,
  })

  availability_zone = var.availability_zone

  depends_on = [
    opentelekomcloud_networking_port_v2.bastion_port
  ]

  network {
    port = opentelekomcloud_networking_port_v2.bastion_port.id
  }
  # Install system in volume
  block_device {
    volume_size           = var.volume_bastion
    destination_type      = "volume"
    delete_on_termination = true
    source_type           = "image"
    uuid                  = data.opentelekomcloud_images_image_v2.current_deb_image.id
  }

  tag = {
    "scenario" : var.scenario
  }
}

resource "opentelekomcloud_networking_port_v2" "bastion_port" {
  name               = "${var.name}_port"
  network_id         = var.network.id
  admin_state_up     = true
  security_group_ids = [opentelekomcloud_compute_secgroup_v2.bastion_group.id]
  fixed_ip {
    subnet_id  = var.subnet.id
    ip_address = local.bastion_local_ip
  }
}
```

**Comment by rramge** [comment]
Well, that's messy, but let's give it a try.

```
resource "opentelekomcloud_compute_instance_v2" "webserver" {
  name            = "basic"
  image_id        = "b260813c-074c-432d-9685-7d9842828386"
  flavor_id       = "s2.large.4"
  key_pair        = "passwordless"
  security_groups = ["default"]

  network {
    #uuid = opentelekomcloud_networking_subnet_v2.webserver.network_id
    port = opentelekomcloud_networking_port_v2.webserver.id
  }
}

resource "opentelekomcloud_networking_port_v2" "webserver" {
  name       = "webserver_port"
  network_id = opentelekomcloud_networking_subnet_v2.webserver.network_id
  #network_id = opentelekomcloud_networking_subnet_v2.webserver.id
  #network_id = opentelekomcloud_networking_network_v2.testnetwork-3.id
  admin_state_up     = true
  security_group_ids = []
  fixed_ip {
    subnet_id  = opentelekomcloud_networking_subnet_v2.webserver.network_id
    ip_address = "172.23.33.5"
  }
}
```

It leads to:

```
opentelekomcloud_networking_port_v2.webserver: Creating...
╷
│ Error: error creating OpenTelekomCloud Neutron port: Resource not found: [POST https://vpc.eu-de.otc.t-systems.com/v2.0/ports], error message: {"NeutronError":{"message":"Subnet bdfc6919-b032-486e-bd7f-2403e2dbd719 could not be found.","type":"SubnetNotFound","detail":""}}
│ 
│   with opentelekomcloud_networking_port_v2.webserver,
│   on vpc-router.tf line 50, in resource "opentelekomcloud_networking_port_v2" "webserver":
│   50: resource "opentelekomcloud_networking_port_v2" "webserver" {
│ 
╵
```
As you can see in the network_id lines I commented out, using the subnet id and the network itself were also fruitless. 
EDIT: Please remember from earlier in this issue, I can also not see this subnet in the webconsole, but it is in the state.

But when I destroy everything, and applying it again multiple times, I SOMETIMES (meaning not always) I get this curious error:

```
│ Error: error creating OpenTelekomCloud Neutron subnet: Bad request with: [POST https://vpc.eu-de.otc.t-systems.com/v2.0/subnets], error message: {"NeutronError":{"message":"Invalid input for operation: on vxlan Network: 2141ed45-6ce5-4884-bd90-f363ab38ad83, Request subnet's ip version already exist, which is:3e6e66b8-6fae-4ed5-8636-e19ac20f6835.","type":"InvalidInput","detail":""}}
│ 
│   with opentelekomcloud_networking_subnet_v2.webserver,
│   on vpc-router.tf line 14, in resource "opentelekomcloud_networking_subnet_v2" "webserver":
│   14: resource "opentelekomcloud_networking_subnet_v2" "webserver" {
│ 
╵
```

From my current point of view, the networking implementation in OTC (OTC, not the provider) is not ready for production.

**Comment by rramge** [comment]
I found a way to make it work ( but it leads to new errors during apply and destroy phases).

It works when using this module (total source is too much to quote here): [https://gitlab.devops.telekom.de/tsystemsalpine/io4da/tf/modules/terraform-opentelekomcloud-compute_instance](https://gitlab.devops.telekom.de/tsystemsalpine/io4da/tf/modules/terraform-opentelekomcloud-compute_instance)

And using the following root code:

```
module "server_with_blockvolume" {
  source = "../../modules/terraform-opentelekomcloud-compute_instance"

  instance_name     = "server-with-blockvolume"
  instance_image_id = data.opentelekomcloud_images_image_v2.rhel7.id
  instance_flavor_name = "s3.medium.1"

  instance_network = {
    "vnic0" = {
      network_uuid           = lookup(module.testnetwork_3.subnet_uuid_list, "webserver")
      network_fixed_ip_v4    = "172.23.33.10"
      network_access_network = true
    },
  }

  instance_eips = {
    "testserver" = {
      port_id     = module.server_with_blockvolume.port_id[0]
      name        = "testserver-01-00"
      size        = 300
    },
  }
  attached_block_volumes = [ module.bv_01.blockstorage_volume_id ]
}
```

This is ugly because of the recursion in instance_eips.testserver.port_id (the module must point to itself when the values are not determined yet).

And this then leads to another error during the destroy phase:

```
╷
│ Error: error deleting OpenTelekomCloud Neutron Router Interface: Expected HTTP response code [200] when accessing [PUT https://vpc.eu-de.otc.t-systems.com/v2.0/routers/1894432c-86f5-48f8-9d0e-c0e1d618b5ab/remove_router_interface], but got 409 instead
│ {"NeutronError":{"message":"Unable to complete operation. LB or VM has have an IP allocation from the subnet.","type":"HTTPInternalServerError","detail":""}}
│ 
│ 
╵
```
But I am losing interested now, the Neutron implementation is clearly an unfinished product. Will try again next year, maybe.
