### ISSUE TITLE
cbr_vault_v3 bind_rules?

### ISSUE THREAD

**Issue by rramge** [opentelekomcloud/terraform-provider-opentelekomcloud#1918]
Quote from documentation:
[bind_rules](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cbr_vault_v3#bind_rules) - (Optional) Rules for automatic association.

This is a bit too unprecise ;-)   When trying to implement a module, Terraform error messages hinted towards this not being a variable, but an entire optional block. And there seem to be variables named "key" and "value" expected inside.

An implementation like this survives `terraform validate`:

```
variable "vault_bind_rules" {
  type        = map(any)
  default     = null
  description = "(Optional) Rules for automatic association."
 }

resource "opentelekomcloud_cbr_vault_v3" "this" {
[...]

  dynamic "bind_rules" { 
    for_each = var.vault_bind_rules != null ? var.vault_bind_rules : {}

    content {
      # This is undocumented content. provider doc only states this block exists.
      key   = bind_rules.key 
      value = bind_rules.value 
    }
  }

  lifecycle {
    precondition {
       condition = var.vault_bind_rules == null ? true : length(var.vault_bind_rules) <= 1
       error_message = "The allowed maximum number of bind_rules blocks is not documented, so only use one until further notice."
       }
  }

[...]
```

Could you please add some documention (e.g. how many rules are allowed here?) and maybe an example?

Thanks,

Ralf

**Comment by artem-lifshits** [comment]
@rramge documentation changes were applied in the latest release ``v1.31.3``.
