### ISSUE TITLE
Information about possible CCE cluster versions not clear

### ISSUE THREAD

**Issue by arenk** [opentelekomcloud/terraform-provider-opentelekomcloud#1921]
A `cluster_version` can be specified for the resource `opentelekomcloud_cce_cluster_v3`. The documentation mentions only v1.17.9-r0 and v1.19.8-r0 as possible values, with a reference to the CCE API documentation

The CCE API says: 
> To learn which cluster versions are available, choose Dashboard > Create Cluster on the CCE console and check the Version parameter.

However, in the dashboard, the versions displayed are only v1.21 and v1.19 - which is not an accepted value since the suffix (e.g -r0) is missing. One could guess the suffix, but then the latest version when I created a CCE cluster wasn't v1.21-r0, but v1.21.1-r1 (additional minor release & different suffix).

Is there an overview of all available CCE versions that could be added as a link to the Terraform provider documentation? Or am I missing something?

**Comment by rramge** [comment]
When I played around with 1.12.1 last week, I had trouble with configuring the autoscaler for this version. Maybe it was me, but my code worked with 1.19.8-r0, so it might be worth reviewing.

**Comment by artem-lifshits** [comment]
Hello @arenk you can check available CCE versions here:
https://docs.otc.t-systems.com/usermanual2/cce/cce_bulletin_0068.html

**Comment by arenk** [comment]
@artem-lifshits thanks for the quick response and the link!
 Looking at the version tags, I assume they won't work after v1.17.9-r0 (missing details, e.g. it's not 1.21 but v1.21.1-r1)

**Comment by artem-lifshits** [comment]
@arenk yep I went over docu and looks like patch versions were removed after v1.17.9-r0 and minor version after v1.19.10:
https://docs.otc.t-systems.com/usermanual2/cce/cce_bulletin_0003.html

**Comment by artem-lifshits** [comment]
@arenk @rramge I've created a discussion with CCE supported versions for easier cluster management: #1927
