### ISSUE TITLE
Unable to create users

### ISSUE THREAD

**Issue by shaderecker** [opentelekomcloud/terraform-provider-opentelekomcloud#1934]
# Terraform provider version

Terraform v1.2.9
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.31.3

# Affected Resource(s)

opentelekomcloud_identity_user_v3.user

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_identity_user_v3" "user" {
  for_each = var.users

  name               = "ta_${each.key}"
  description        = "TA ${each.value["full_name"]}"
  email              = each.value["email"]
  send_welcome_email = true
}

resource "opentelekomcloud_identity_project_v3" "project" {
  for_each = var.users

  name        = "eu-nl_ta_${each.key}"
  description = "TA ${each.value["full_name"]}"
}

resource "opentelekomcloud_identity_group_v3" "group" {
  for_each = var.users

  name        = "ta_${each.key}"
  description = "TA ${each.value["full_name"]}"
}

resource "opentelekomcloud_identity_group_membership_v3" "membership" {
  for_each = var.users

  group = opentelekomcloud_identity_group_v3.group[each.key].id
  users = [opentelekomcloud_identity_user_v3.user[each.key].id]
}

resource "opentelekomcloud_identity_role_assignment_v3" "role_assignment" {
  for_each = var.users

  group_id   = opentelekomcloud_identity_group_v3.group[each.key].id
  project_id = opentelekomcloud_identity_project_v3.project[each.key].id
  role_id    = opentelekomcloud_identity_role_v3.role.id
}
```

# Debug Output/Panic Output

https://gist.github.com/shaderecker/475e04cdd8ae31c18ac555c371f09961

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

new users get created

# Actual Behavior

User creation fails with this error:
```
 Error: error creating OpenTelekomCloud user: Bad request with: [POST https://iam.eu-de.otc.t-systems.com/v3/users], error message: {"error": {"message": "check_email_exist() takes exactly 6 arguments (3 given)", "code": 400, "error_code": null, "error_msg": null, "title": "Bad Request"}}
```

# Important Factoids

I did not change anything on my TF code. Last time I ran this, it worked, but now it doesn't.
Both users are totally normal, nothing about the email addresses is any special.

Previously I was on v1.31.1 where this error also happend, then I tried out the latest version v1.31.3, but that didn't fix the issue.

# References

**Comment by rramge** [comment]
I just verified and I can reproduce this error with my module.  It is indeed a new behaviour.

**Comment by artem-lifshits** [comment]
Hello @shaderecker thank you for report, fix is on the way.

And please don't hesitate to open an issue here / pm me in Zulip right when you have found an issue.

**Comment by artem-lifshits** [comment]
@shaderecker @rramge new release was published, please check.

**Comment by shaderecker** [comment]
Hi @artem-lifshits thank you very much! It now works again with the new release. 🎉
