### ISSUE TITLE
[vpcep_endpoint_v1] Please state the whitelist variable type

### ISSUE THREAD

**Issue by rramge** [opentelekomcloud/terraform-provider-opentelekomcloud#1935]
Hi,

the documentation states:

[whitelist](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/vpcep_endpoint_v1#whitelist) - (Optional) Specifies the whitelist for controlling access to the VPC endpoint.

It is not clear what variable type / content is required here. list(string)? jsonencode(string)? Something else? Can you please clarify this?

Thanks,

Ralf

**Comment by artem-lifshits** [comment]
Hello @rramge whitelist here is a list of strings in format:
``whitelist = [ "value1", "value2" ]``
I will update this part of documentation, thank you.

**Comment by artem-lifshits** [comment]
Hello @rramge new provider version was released, please check.

**Comment by artem-lifshits** [comment]
Hello @rramge changes released in latest release.

**Comment by rramge** [comment]
Looks good, thank you.
