### ISSUE TITLE
[Docs] opentelekomcloud_identity_user_v3

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#1939]
Update the attribute reference. 

Versions:
```
Terraform v1.2.9
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.31.3
```

Undocumented are at least (tested):

```hcl
output "this_user_id" {
  description = "ID of OTC IAM User"
  value       = { for k, v in opentelekomcloud_identity_user_v3.this : k => v.id }
}

output "this_user_name" {
  description = "Name of OTC IAM User"
  value       = { for k, v in opentelekomcloud_identity_user_v3.this : k => v.name }
}
```

**Comment by artem-lifshits** [comment]
Hello @Moep90.

Every resource in OTC provider has an ``id`` and would have the same reference for every resource. 
Therefore ``id`` argument is not included in documentation.

Name is ``required`` argument for ``opentelekomcloud_identity_user_v3``, here's the screenshot:
![Screenshot 2022-09-19 at 15 20 55](https://user-images.githubusercontent.com/55093318/191016598-398f1a1a-0aaf-42a1-80a2-a71453d97b11.png)

**Comment by artem-lifshits** [comment]
@Moep90 please reopen the ticket if you have other concerns.
