### ISSUE TITLE
Facing challenge while creating CTS Key Event Notification service using Terraform.

### ISSUE THREAD

**Issue by sandipamte** [opentelekomcloud/terraform-provider-opentelekomcloud#1948]
# Terraform provider version
Terraform v1.0.11

# Affected Resource(s)
Please list the resources as a list, for example:
- opentelekomcloud_cts_tracker_v1

# Terraform Configuration Files
```resource "opentelekomcloud_cts_tracker_v1" "tracker_v1" {
  bucket_name               = "bpmaas-cts-logs"
  file_prefix_name          = "loadtest1"
  is_support_smn            = true
  topic_id                  = opentelekomcloud_smn_topic_v2.topic_1.id
  is_send_all_key_operation = false
  operations                = ["create", "delete"]
  need_notify_user_list = ["samte"]
}

resource "opentelekomcloud_smn_topic_v2" "topic_1" {
  name         = "cts-topic"
  display_name = "The display name of topic_1"
}
resource "opentelekomcloud_smn_subscription_v2" "subscription_1" {
  topic_urn = opentelekomcloud_smn_topic_v2.topic_1.id
  endpoint  = "sandip.amte@t-systems.com"
  protocol  = "email"
  remark    = "cts"
}
```

# Actual Behavior
Using above code, I am able to create/enable CTS Tracker, SMN Topic and Subscription.
In CTS service, we want to create Key Event Notification which will connect this tracker to SMN topic.

![image](https://user-images.githubusercontent.com/86256736/193014671-5ab0b199-f3b6-495b-b89c-96c669b6a41b.png)

Could you please help us to create Key Event Notification in CTS using terraform or share reference document which help to create it?

# References
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cts_tracker_v1
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/smn_topic_attribute_v2

**Comment by anton-sidelnikov** [comment]
@sandipamte Did you check the doc https://docs.otc.t-systems.com/en-us/api/cts/en-us_topic_0168602251.html?

- is_send_all_key_operation - You can select Typical or All for Trigger Condition.
  > When the value is false, operations cannot be left empty.  
  > When the value is true, operations is not supported.

- operations
  > Specifies trigger conditions for sending a notification when Typical is selected. You can select delete, create, or login or at least one of them.
  > Specifies trigger conditions for sending a notification when All is selected. All conditions including delete, create, change, and OpenStack API Event are selected by default. Modification is not allowed.

**Comment by sandipamte** [comment]
Hi,

Thanks for guidance, now I have made below change in the code which as follows.

resource "opentelekomcloud_cts_tracker_v1" "tracker_v1" {
  bucket_name               = "bpmaas-cts-logs"
  file_prefix_name          = "loadtest1"
  is_support_smn            = true
  topic_id                  = opentelekomcloud_smn_topic_v2.topic_1.id
  is_send_all_key_operation = true
  need_notify_user_list = null
}

resource "opentelekomcloud_smn_topic_v2" "topic_1" {
  name         = "cts-topic"
  display_name = "The display name of topic_1"
}
resource "opentelekomcloud_smn_subscription_v2" "subscription_1" {
  topic_urn = opentelekomcloud_smn_topic_v2.topic_1.id
  endpoint  = "sandip.amte@t-systems.com"
  protocol  = "email"
  remark    = "cts"
}

Set is_send_all_key_operation to true and removed operations part from the code ( When the value is true, operations is not supported.) and need_notify_user_list to null, so that target objects are all users by default.

Still i am not able to create Key event notification under CTS. ( Note: Able to create Tracker and Topic wit subscription )

Can you please guide on same?

**Comment by artem-lifshits** [comment]
Hello @sandipamte maybe you already have CTS tracker created?
In that case it needs to be deleted from console first.

**Comment by sandipamte** [comment]
I am able to create CTS Tracker, topic, subscription, and Key Event Notification service manually in OTC. 
After tested the setup we have deleted it.
Now we are creating same setup using terraform. 
Using above code, we are able to create CTS Tracker, topic, subscription using terraform. But not able to create Key Event Notification in CTS using terraform.
Could you please guide us to create Key Event Notification using terraform?

**Comment by artem-lifshits** [comment]
@sandipamte I've checked the API for CTS.
Sadly the API for CTS notifications isn't released yet, only tracker management is available at the moment:
https://docs.otc.t-systems.com/en-us/api/cts/en-us_topic_0168602232.html

When API is released we will be able to implement notifications feature.

**Comment by artem-lifshits** [comment]
Waiting for API implementation to implement provider support.

**Comment by artem-lifshits** [comment]
Internal ticket: https://jira.tsi-dev.otc-service.com/browse/RM-3679

**Comment by artem-lifshits** [comment]
Hello @sandipamte cts events resource will be available on next release.

**Comment by artem-lifshits** [comment]
@sandipamte resource is available in latest release, please check.

**Comment by sandipamte** [comment]
Hi,

I have added the code, but still getting below error.

Error: Invalid resource type
│ 
│   on ../../modules/cts/cts.tf line 22, in resource "opentelekomcloud_cts_event_notification_v3" "notification_v3":
│   22: resource "opentelekomcloud_cts_event_notification_v3" "notification_v3" {
│ 
│ The provider opentelekomcloud/opentelekomcloud does not support resource type "opentelekomcloud_cts_event_notification_v3".

We are using opentelekomcloud V1.27.2, and i upgraded it to 1.27.4. 
For both version i am getting same error, 
Could you please guide to enable the service.
