### ISSUE TITLE
Imported ECS key pair still is to be recreated

### ISSUE THREAD

**Issue by simonszu** [opentelekomcloud/terraform-provider-opentelekomcloud#1954]
# Terraform provider version
provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.31.4

# Affected Resource(s)
opentelekomcloud_compute_keypair_v2

# Terraform Configuration Files
```hcl
# Configure SSH Keypair for node access
resource "opentelekomcloud_compute_keypair_v2" "cce_node_keypair" {
  name = "${var.application}-${var.env}-keypair"
  public_key = var.ssh_pubkey
}
```

# Debug Output/Panic Output
```
  # module.cce.opentelekomcloud_compute_keypair_v2.cce_node_keypair must be replaced
-/+ resource "opentelekomcloud_compute_keypair_v2" "cce_node_keypair" {
      ~ id          = "dLS-test-keypair" -> (known after apply)
        name        = "dLS-test-keypair"
      + private_key = (known after apply)
      ~ public_key  = <<-EOT # forces replacement
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNdQzVMMAt2K1cD6VD075697AUh+Sm9kKTBoXd4QaW4+q2xDpf3kdF9jbOGWoAQkXuonfkSRiur1O5aASSf1w50WvamLgpe6ZhC/L8ouqZkElLZd8FETJV8abZuvudywv4lIu3OGcGeClRiuvZxLNewM6MD+RWl4kJ1/akyldo7YyEHopJHapF8CICZEKSrvSVKb8vm584Gomvrpwq+cgfW22ZMh7Wc3ZyQM+9uSdgwKsIh1pCHyG6+OOeUeqjMugzyID6kFN8g7o1vJQWkdtDF/gnQuUzaCN2thOjqc2sWNDWzkxIbMVWKtJLOv/rnE6juxcIseQde/u7Pt3YNmyH Generated-by-Nova
        EOT
      ~ region      = "eu-de" -> (known after apply)
        # (1 unchanged attribute hidden)
    }
```
# Steps to Reproduce
1. Upload SSH key / generate key pair for the user who is logging in to the OTC API via Terraform
2. Make sure the key pair has the same public key as is defined in the TF manifests
3. Make sure the key pair has the same name as is defined in the TF manifests
4. Do a "terraform plan"

# Expected Behavior
This is for a setup where multiple IAM accounts should execute the terraform manifests against a single tenant. According to the OTC support it is intended that key pairs are only visible to the account which created them. They suggested that each account should upload the same key pair and give it the same name as it is defined in the manifests. Terraform should recognize the key pair as present since it is identified by its name and not by its UID. Terraform should neither suggest to recreate the key pair or to recreate any ECS instances depending on that key pair. 

# Actual Behavior
- Terraform does not recognize the existing key pair and the one described in the manifest as identical
- Terraform wants to recreate the key pair
- Terraform wants to recreate any ECS instance which depends on the key pair
- This is not acceptable because the instances are already somehow productive

# Important Factoids
The key pair in the OTC was created with Terraform initially as well (by not specifying any public key in the manifest), when we were not yet aware of the constraints for multi user usage. As soon as we became aware, we specified the public key in the manifest with the contents of the now existing key pair. 
The key pair was removed from the stage and re-imported, so that Terraform should in theory be well aware that the key exists and has the same content as it is specified in the manifest. 

# References
I have an open issue with the OTC support about that topic as well. The ticket ID is INC00946113.

**Comment by simonszu** [comment]
I have compared the public key in the terraform state to the one i am providing as an argument to the module. They are exact identical. 
For now i have made this workaround: 
```hcl
# Configure SSH Keypair for node access
resource "opentelekomcloud_compute_keypair_v2" "cce_node_keypair" {
  name = "${var.application}-${var.env}-keypair"
  public_key = var.ssh_pubkey

  # Workaround for https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1954
  lifecycle {
    ignore_changes = [
      public_key,
    ]
  }
}
```

**Comment by vladimirvshivkov** [comment]
Hi, @simonszu 

I suggest changing `ForceNew: true` param to false in `opentelekomcloud_compute_instance_v2` to avoid instance recreation in cases like this.
But is it only about ECS or CCE nodes as well?

**Comment by simonszu** [comment]
Hi, 
this is especially for CCE nodes which are managed by a node pool. A change/recreation of the key pair ressource would cause the node pools to be recreated as well. 

Your suggestion sounds like a workaround, though. I do not really understand why TF wants to recreate the key pair, although it was imported right now, and the name and the public key are absolutely identical.

**Comment by vladimirvshivkov** [comment]
I think i found the bug, will try to fix

**Comment by vladimirvshivkov** [comment]
Oh, wait. I cannot reproduce the bug.
It works fine for me.
Could you send here the value of `var.ssh_pubkey`?
```data.local_file.ssh_pubkey: Reading...
data.local_file.ssh_pubkey: Read complete after 0s [id=cfabd3f50c4820b1bda3ad508a9e7300dc61bc82]
opentelekomcloud_compute_keypair_v2.cce_node_keypair: Refreshing state... [id=test-keypair]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.```

**Comment by vladimirvshivkov** [comment]
tested TF manifest:
```
resource "opentelekomcloud_compute_keypair_v2" "cce_node_keypair" {
  name = "test-keypair"
  public_key = data.local_file.ssh_pubkey.content
}

data "local_file" "ssh_pubkey" {
    filename = var.ssh_pubkey
}

**Comment by simonszu** [comment]
Yeah, sure. The resource definition is the same as i posted yesterday, with the workaround. The `var.ssh_pubkey` looks like this: 
```
ssh_pubkey = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNdQzVMMAt2K1cD6VD075697AUh+Sm9kKTBoXd4QaW4+q2xDpf3kdF9jbOGWoAQkXuonfkSRiur1O5aASSf1w50WvamLgpe6ZhC/L8ouqZkElLZd8FETJV8abZuvudywv4lIu3OGcGeClRiuvZxLNewM6MD+RWl4kJ1/akyldo7YyEHopJHapF8CICZEKSrvSVKb8vm584Gomvrpwq+cgfW22ZMh7Wc3ZyQM+9uSdgwKsIh1pCHyG6+OOeUeqjMugzyID6kFN8g7o1vJQWkdtDF/gnQuUzaCN2thOjqc2sWNDWzkxIbMVWKtJLOv/rnE6juxcIseQde/u7Pt3YNmyH Generated-by-Nova"
```
If you compare it to the output i posted in the opening post, you will see that it is identical. 

I should mention that this happens not only in this case. We have 3 workspaces in our manifest project to deploy 3 similar setups. In all setups the key was auto-generated by Terraform before, until i changed the resource definition to include the pubkey definition, and deleted and reimported the keypair resource to the state.

**Comment by vladimirvshivkov** [comment]
could you please share your manifests?
I guess problem may be somewhere in them.

**Comment by simonszu** [comment]
Sure. This is the resource definition of the CCE module in the manifests collection: https://pastebin.com/bS6yMyBY

**Comment by vladimirvshivkov** [comment]
on line 196  local_file resource recreates your ssh privkeys.
Try to change resource to datasource.
```
#Write local ssh privkey file
resource "local_file" "privkey" {
  content = opentelekomcloud_compute_keypair_v2.cce_node_keypair.private_key
  filename = "output/${var.env}/id_rsa"
  depends_on = [
    opentelekomcloud_cce_cluster_v3.cce
  ]
}
```


like this:
```
data "local_file" "ssh_pubkey" {
    filename = "output/${var.env}/id_rsa"
}
```

**Comment by simonszu** [comment]
Yes, but the problem is not the local file as i stated in the opening post: 
```
module.cce.opentelekomcloud_compute_keypair_v2.cce_node_keypair must be replaced
```

**Comment by vladimirvshivkov** [comment]
That's correct because it generates a new private key.
I think it is about how you distribute your secrets.
Maybe it could be better to store keys for your team somewhere like Hashicorp Vault?

**Comment by simonszu** [comment]
Yes, this is definitely in planning. 

However, even if i completely remove the local_file resource, Terraform still thinks that the public_key in the keypair resource differs from the public_key reported back from the OTC API, and therefore tries to recreate everything. The public key was imported before, as this was mentioned to me by the OTC support as the preferred way to do: 

1. Import SSH keys
2. Reference SSH keys by name and pubkey in the resource definition
3. Terraform should recognize the preimported keys and proceed as usual

But, in this case, it isn't recognizing the preimported key, which has nothing to do with any additional resources which should get exported. The root cause in my eyes is that it thinks the public key differs, even if it doesn't.

**Comment by simonszu** [comment]
OK, i have rebuilt the environment from scratch with the help of the manifests (per customer request, not because of this issue) and the issue is gone. Sorry for keeping you up with my trouble.
