### ISSUE TITLE
EIP management in 1.31.5 un-assigns public IP from CCE instance

### ISSUE THREAD

**Issue by simonszu** [opentelekomcloud/terraform-provider-opentelekomcloud#1956]
# Terraform provider version
1.31.5

# Affected Resource(s)
- opentelekomcloud_vpc_eip_v1
- opentelekomcloud_cce_cluster_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_vpc_eip_v1" "cce_cli_eip" {
  publicip {
    type = "5_bgp"
  }
  bandwidth {
    name        = "${var.application}-${var.env}-cce-cli-bandwidth"
    size        = 20
    share_type  = "PER"
  }

  tags = {
    Name        = "${var.application}-${var.env}-cce-cli-eip"
    Application = var.application
    Environment = var.env
  }
}

# Configure OpenTelekomCloud CCE cluster
resource "opentelekomcloud_cce_cluster_v3" "cce" {
  name        = "${lower(var.application)}-${lower(var.env)}-cce"
  description = "k8s ${var.env} cluster"

  cluster_type           = "VirtualMachine"
#  cluster_version        = "v1.19.10-r0"
  flavor_id              = var.node_flavor
  vpc_id                 = var.vpc_id
  subnet_id              = var.subnet_id
  container_network_type = "overlay_l2"
  authentication_mode    = "rbac"
  eip                    = opentelekomcloud_vpc_eip_v1.cce_cli_eip.publicip[0].ip_address

  annotations = {
    Name        = "${var.application}-${var.env}-cce"
    Application = "digiLS"
    Environment = var.env
  }
}
```

# Debug Output/Panic Output
Terraform will perform the following actions:
```
  # module.cce.opentelekomcloud_vpc_eip_v1.cce_cli_eip will be updated in-place
  ~ resource "opentelekomcloud_vpc_eip_v1" "cce_cli_eip" {
        id     = "a6a8b954-a8d3-4dbf-8334-d2cc06c17681"
        tags   = {
            "Application" = "dLS"
            "Environment" = "test"
            "Name"        = "dLS-test-cce-cli-eip"
        }
        # (1 unchanged attribute hidden)

      ~ publicip {
          - port_id    = "bb1d08d4-e210-49ba-8166-5a8578757889" -> null
            # (2 unchanged attributes hidden)
        }

        # (2 unchanged blocks hidden)
    }
```
# Steps to Reproduce

1. `terraform apply`

# Expected Behavior
- The EIP should get created
- The CCE should take up the EIP as the IP address of its API

# Actual Behavior
The EIP resource and the CCE resource were created with the provider prior to 1.31.5. Upgrading to 1.31.5 causes the EIP to unbind from the CCE instance because there is no `publicip.port_id` specified. I cannot specify a port_id during EIP creation time since the CCE is created later - and takes the EIP as dependency. Looks like a circular reference to me? 

# Important Factoids

# References
Maybe related to https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/commit/08eeeb061327747829e178a8de667f21901bbfb4 since it's an EIP related commit in 1.31.5 - last working version for me was 1.31.4.

**Comment by anton-sidelnikov** [comment]
@simonszu here is some kind of bug in tf for nested parameters which optional and computed - no way set it to nil. I revert compatibility, and add additional parameter for manual port unbind

**Comment by panikgaul** [comment]
I tested it now with 1.31.6 and unfortunately the problem still here.

My CCE cluster has a bounded floating and cluster IP as EIP and after apply TF will unbind them.

```
Terraform will perform the following actions:

  # module.medpower3.opentelekomcloud_vpc_eip_v1.floating will be updated in-place
  ~ resource "opentelekomcloud_vpc_eip_v1" "floating" {
        id     = "91c27910-cf98-4cee-a65d-9eeeaba8efb3"
        # (1 unchanged attribute hidden)

      ~ publicip {
          - port_id    = "ebaa36d6-387e-4883-8f56-95f8c5b49006" -> null
            # (2 unchanged attributes hidden)
        }

        # (2 unchanged blocks hidden)
    }

  # module.cce_cluster_1.opentelekomcloud_vpc_eip_v1.cluster will be updated in-place
  ~ resource "opentelekomcloud_vpc_eip_v1" "cluster" {
        id     = "82fb600f-fb98-409b-b6f3-a9a1c4d897fa"
        # (1 unchanged attribute hidden)

      ~ publicip {
          - port_id    = "f5bc981c-c969-4eb0-bbc0-876fd2f657cf" -> null
            # (2 unchanged attributes hidden)
        }

        # (2 unchanged blocks hidden)
    }

```

**Comment by anton-sidelnikov** [comment]
@simonszu @panikgaul this fix do not want to be in release, now it was merge error, sorry. Now please look at https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/1.31.6-hotfix.1
