### ISSUE TITLE
identity_user_v3: add Login Protection (MFA)

### ISSUE THREAD

**Issue by k11h-de** [opentelekomcloud/terraform-provider-opentelekomcloud#1958]
Hi team,

first off: thank you very much for providing such an extensive and well-documented Terraform provider for OTC. We're using it a lot. :thumbsup:

# Description of the enhancement

We're creating our user accounts with the [identity_user_v3](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/identity_user_v3) resource. We do this for physical persons where we need to **enable MFA**. In the graphical management console you can configure this setting during user account creation wizard.

Do you see any chance to **make MFA settings available via terraform** user resource?

Again, thanks a million for your awesome work.

Cheers Karsten

**Comment by anton-sidelnikov** [comment]
@k11h-de Hi, yes I think it is possible, we will create resource for that

**Comment by anton-sidelnikov** [comment]
@k11h-de Hello, so we did some investigations, this api currently in very raw state. Some of endpoints not published. But biggest point that through that api you cannot create MFA for another user in easy way, it possible, but this is security unsafe. For now not possible to implement.

**Comment by k11h-de** [comment]
Okay, I understand. Would you mind requesting this improvement to OTC?

For us to be able to work around this limitation, we need to be able to get the information if a user has MFA / Login Protection enabled in terraform. So, do you see any chance to make an attribute (like `mfa_present`) available in the [user data source](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/data-sources/identity_user_v3)? We would then be able to query which users have mfa set up manually.

Thanks in advance

**Comment by artem-lifshits** [comment]
Hello @k11h-de user_v3 data source was updated with mfa information in the latest release, please check.

**Comment by anton-sidelnikov** [comment]
Close for now, will continue work when api ready to implementation
