### ISSUE TITLE
data source opentelekomcloud_identity_role_v3: name vs. display_name

### ISSUE THREAD

**Issue by k11h-de** [opentelekomcloud/terraform-provider-opentelekomcloud#1959]
Hi there, first of all: thanks a lot for your effort in providing this terraform provider :thumbsup:

I am truggeling using a `opentelekomcloud_identity_role_v3` data source to get a resource by it's **display_name**. A different team (using a different terraform context / state) creates a `opentelekomcloud_identity_role_v3` resource and I need to get it by it's `display_name` (as this follows a certain naming schema).      
Do you see any chance to add `display_name` to the opentelekomcloud_identity_role_v3 data source? 

# Terraform provider version
1.31.5

# Affected Resource(s)
- data_source: [opentelekomcloud_identity_role_v3](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/data-sources/identity_role_v3)

# Debug Output/Panic Output
```
Error: your query returned no results. Please change your search criteria and try again.
│
│   with data.opentelekomcloud_identity_role_v3.role_custom_global,
│   on tf_data.tf line 55, in data "opentelekomcloud_identity_role_v3" "role_custom_global":
│   55: data "opentelekomcloud_identity_role_v3" "role_custom_global" {
│
```

# Steps to Reproduce

1. define a `opentelekomcloud_identity_role_v3` data source and try to get a resource outside the current terraform scope by it's name
   ```hcl
   data "opentelekomcloud_identity_role_v3" "role_custom_global" {
     name      = "obs_mybucket_rw"
     domain_id = "5643f7f00d64xxxxxxxxxxxxxxxxxxxxx"
   }
   ```
3. `terraform apply`

# Expected Behavior
I expected the data source to get the role resource by it's name displayed in the OTC management console. 

# Actual Behavior
the data source is not able find the role by it's display_name. Only `name` is supported

Looking at the role created by terraform it is obvious that `name` and `display_name` are different

```json
   {
      "mode": "managed",
      "type": "opentelekomcloud_identity_role_v3",
      "name": "role_obs_rw",
      "provider": "provider[\"registry.terraform.io/opentelekomcloud/opentelekomcloud\"]",
      "instances": [
        {
          "index_key": "mybucket",
          "schema_version": 0,
          "attributes": {
            "catalog": "CUSTOMED",
            "description": "obs mybucket rw",
            "display_layer": "domain",
            "display_name": "obs_mybucket_rw",
            "domain_id": "5643f7f00d644f9ea5f18cd3a86a2fed",
            "id": "714a764cca5146e6ac51702efddbbb7f",
            "name": "custom_5643f7f00d644f9ea5f18cd3a86a2fed_2",
            "statement": [ ]
          },
          "sensitive_attributes": [],
        },
```

**Comment by k11h-de** [comment]
Hi Artem, Hi OTC users

I was hoping I found a workaround for my above problem by maintaining a `map(string)` variable in Terraform like this:

## problem

```hcl
map_custom_policies = {
  "mypolicy1" = "custom_5643f7f00d644f9ea5f18cd3a86a2fed_0",
  "mypolicy2" = "custom_5643f7f00d644f9ea5f18cd3a86a2fed_1",
  "mypolicy3" = "custom_5643f7f00d644f9ea5f18cd3a86a2fed_2"
}
```

but then I made further tests and found out the following:

1. I create the first custom policy 
    ```
    display_name = mypolicy1
    name         = custom_5643f7f00d644f9ea5f18cd3a86a2fed_0
   ```
2. I create a second custom policy 
    ```
    display_name = mypolicy2
    name         = custom_5643f7f00d644f9ea5f18cd3a86a2fed_1
   ```
3. I delete `mypolicy1`
4. When I create a third custom policy, the internal `name` from `mypolicy1` is re-used. 
    ```
    display_name = mypolicy3
    name         = custom_5643f7f00d644f9ea5f18cd3a86a2fed_0
   ```
(`name` is always generated by OTC) 


This behaviour breakes my `map_custom_policies` workaround. 
Additionally, I am able to create many custom policies with the exact same `display_name`.

So the main issue I see is that none of `name` and `display_name` are a unique identifier for one custom role, which is a real pain from the coding perspective. 

## possible solution

There might be a way to work around but that requires me to ensure that `display_name` stays a unique identifier.     
A code example might look like this

```hcl
resource "random_id" "id" {
  byte_length = 4
}

resource "opentelekomcloud_identity_role_v3" "role_obs_rw" {
  display_name  = "obs_${var.bucketname}_rw_${random_id.id.hex}"
  display_layer = "domain"
  statement {
    effect   = "Allow"
    action   = ["obs:*:*"]
    resource = ["OBS:*:*:bucket:${var.bucketname}"]
  }
}
```
This solution still depends on the data source `opentelekomcloud_identity_role_v3` to allow search for my `display_name`

I hope I was able to describe by problem well.    
Do you see any solutions to it?

Thanks a million
Karsten

**Comment by artem-lifshits** [comment]
Hello @k11h-de I think there's some mixture here regarding the roles.

`data "opentelekomcloud_identity_role_v3"` can query and return data of existing pre-defined system roles. At the moment there's no data source that can query custom roles.

I will create a new data source so custom roles could be queried.

**Comment by k11h-de** [comment]
Hi @artem-lifshits 
Well, I was already successfully able to query custom roles. I needed to set `domain_id` . So it is definitely possible with the current version.

**Comment by artem-lifshits** [comment]
@k11h-de the fact that it's working this way is interesting but definitely not intended 😁
