### ISSUE TITLE
Resizing node pool with terraform causes unwanted scale-in

### ISSUE THREAD

**Issue by nfelger** [opentelekomcloud/terraform-provider-opentelekomcloud#1961]
Whenever I change my node pool's `max_node_count` with terraform, the nodes in the node pool gets scaled down to its `initial_node_count`. This means I lose running workloads in situations where I want to _add_ capacity, not reduce it.

Making the same change via the web UI works as expected and does not have this effect.

# Terraform provider version
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/random v3.1.3
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.29.2

# Affected Resource(s)
- opentelekomcloud_cce_node_pool_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_cce_cluster_v3" "this" {
...
}

resource "opentelekomcloud_compute_keypair_v2" "this" {
...
}

resource "opentelekomcloud_cce_node_pool_v3" "this" {
  name = "test"
  cluster_id         = opentelekomcloud_cce_cluster_v3.this.id
  flavor             = "s2.large.2"
  os                 = "CentOS 7.7"
  availability_zone  = "random"
  key_pair           = opentelekomcloud_compute_keypair_v2.this.name
  initial_node_count = 2

  scale_enable             = true
  min_node_count           = 2
  max_node_count           = 10
  scale_down_cooldown_time = 100
  priority                 = 1

  root_volume {
    size       = 40
    volumetype = "SATA"
  }

  data_volumes {
    size       = 100
    volumetype = "SATA"
  }

  lifecycle {
    ignore_changes = [
      k8s_tags,
      status,
    ]
  }
}
```

# Steps to Reproduce

1. Scale node pool to have 5 nodes (e.g. via the web UI)
2. Change `max_node_count` in the `opentelekomcloud_cce_node_pool_v3` resource to 15
3. `terraform apply`

# Expected Behavior

The number of nodes currently in the node pool should not change. Only its `max_node_count` setting should be updated.

**This is what happens when I edit the node pool via the web UI.**

# Actual Behavior

The node pool is scaled down to its `initial_node_count`. Existing nodes above that count get deleted. In my example, 3 of the 5 existing nodes get deleted.

# Important Factoids

I have an autoscaler add-on running in the cluster.

**Comment by nfelger** [comment]
Updated the description to clarify: the node pool gets scaled down to its `initial_node_count`. I was using a single variable to set both `initial_node_count` and `min_node_count`, hence the confusion. Still, very undesirable behaviour.

**Comment by anton-sidelnikov** [comment]
Hey @nfelger, if you scale nodes not from ui, but from tf, there is the same behavior? I found that it seems to be the API error, from provider we send only http.update with new numbers and that's all, nothing more.

**Comment by anton-sidelnikov** [comment]
Anyway internal incident was created https://jira.tsi-dev.otc-service.com/browse/CONT-1073

**Comment by nfelger** [comment]
> Hey @nfelger, if you scale nodes not from ui, but from tf, there is the same behavior?

Not sure I understand your question. The issue is that if I change `max_node_count` via terraform I get the scale-in problem; if I do it from the UI, I don't get the problem. Does that help?

**Comment by anton-sidelnikov** [comment]
@nfelger i just meant if you not change your nodes count on ui while all infra controlled by terraform, in do it inside terraform config, there will be same issue or not

**Comment by nfelger** [comment]
You mean if I only ever use terraform and never touch the UI for the node pool? I can't guarantee it but I only started looking at the UI when we got the terraform problems, so I _think_ it happens even when not using the UI.

**Comment by anton-sidelnikov** [comment]
@nfelger answer from backend team: 
```
This seems to be the expected behavior of the nodepool, as by the time you update the nodepool, the initial_count has been changed to 5 by step3 (this can be verified by making a GET request of the nodepool)

And through this update:

{
  initial_node_count = 1,
  min_node_count           = 1
  max_node_count           = 15
  scale_down_cooldown_time = 6
} we are specifying the initialNodeCount to be "1" again, so the extra nodes are deleted.
```
I think it is possible to avoid this behavior with updating max_node_count simultaneously with initial_node_count
