### ISSUE TITLE
Data source for CCE Addons

### ISSUE THREAD

**Issue by canaykin** [opentelekomcloud/terraform-provider-opentelekomcloud#1969]
# Description of the enhancement
Hi team, 

Due to a recent change in addon image repo with CCE 1.23, some addons are no longer available via `"swr_user": "hwofficial"`. 

The change is also not consistent where metric server 1.2.1 is available at both `/hwofficial` and at `/cce-addons`, but autoscaler 1.23.6 is only available at `/cce-addons` (whereas older autoscaler versions are only available at  `/hwofficial`). 

When we asked the OTC team, we were told to use an API call to `https://<cluster_id>.cce.eu-de.otc.t-systems.com/api/v3/addontemplates` in order to dynamically retrieve the addon template parameters instead of hardcoding them.

Would it make sense to either build this functionality into the `opentelekomcloud_cce_addon_v3` or create a data source to obtain the addon parameters?

Thank you very much in advance,
Can.

**Comment by lego963** [comment]
@canaykin from my pov, better to update template docs, because template api call response is awfully long
https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/devel/opentelekomcloud/services/cce/addon-templates-v1.19.8.md
https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/devel/opentelekomcloud/services/cce/addon-templates-v1.17.9.md

**Comment by canaykin** [comment]
@lego963 That would be an improvement, yes. 

But the key problem for us is to keep backwards compatibility in project factory CCE module. We can not support both new and old versions of CCE simultaneously without some hack like checking the CCE version to hardcode multiple values in a lookup.

Similarly, as the number of regions increase, the parameter `swr_addr` also diversifies. A dynamic call would help us for that reason unless it is too impractical to implement on your side.

**Comment by uli-max** [comment]
CCE 1.23 today was released in eu-nl.

There the  /hwofficial way is used again ... 
swr.eu-nl.otc.t-systems.com/hwofficial/metrics-server:v0.4.4

Handling this over a data-source seems the best in my mind.

**Comment by anton-sidelnikov** [comment]
@canaykin @uli-max please check data.opentelekomcloud_cce_addon_template_v3, supported versions is a mess, but at least you can get swr_user and swr_addr. If you want any improvements to this datasource please give response here.

**Comment by anton-sidelnikov** [comment]
No response in 20 days, close issue.

**Comment by canaykin** [comment]
@anton-sidelnikov written the reply and completely forgotton to send it apparently...

Thank you very much for this, we are making good use of the new data source on project factory >=5.0.0 :)
