### ISSUE TITLE
Import ability for opentelekomcloud_nat_gateway_v2

### ISSUE THREAD

**Issue by panikgaul** [opentelekomcloud/terraform-provider-opentelekomcloud#1972]
It would be nice to have a import ability for the ressource **opentelekomcloud_nat_gateway_v2**

Currently in 1.31.6 it is not possible.

`│ Error: resource opentelekomcloud_nat_gateway_v2 doesn't support import
`

Thanks!

**Comment by anton-sidelnikov** [comment]
import added in latest release 1.31.7
