### ISSUE TITLE
Question - When will v1.31.6-hotfix.1 integrated in an official release?

### ISSUE THREAD

**Issue by pwurbs** [opentelekomcloud/terraform-provider-opentelekomcloud#1974]
The bug which is fixed in v1.31.6-hotfix.1, blocks me to deploy changes. I don't want to loose my EIP assignment and I want to change my pipeline to accept the hotfix version.
When can we expect the hotfix in the next official release?

**Comment by anton-sidelnikov** [comment]
@pwurbs currently fix in pre-release state you can use it. In next main release it also will be available. Next release 2 nov 2022

**Comment by pwurbs** [comment]
Yes, I see. But as I said, I don't want to change my pipeline resp. version policy in TF to use the pre-release state. So, I have to wait for 2.11. 
Thx
