### ISSUE TITLE
opentelekomcloud_compute_instance_v2 data provider needs manage serverPasswords permissions

### ISSUE THREAD

**Issue by dibi-codes** [opentelekomcloud/terraform-provider-opentelekomcloud#1983]
# Terraform provider version
terraform v1.3.4
terraform-provider-opentelekomcloud v1.31.6

# Affected Resource(s)
- opentelekomcloud_compute_instance_v2

# Terraform Configuration Files
```hcl
data "opentelekomcloud_compute_instance_v2" "fino-ecs" {
  # Search ecs by name
  id = "<instance-id>"
}
```

# Debug Output/Panic Output
```
│ Error: error getting password: Action Forbidden, error message: {"forbidden": {"message": "Policy doesn't allow ecs:serverPasswords:manage to be performed.", "code": 403}}
```

# Steps to Reproduce
1. Create a OTC terraform user that only has "ECS Viewer" Permissions
2. `terraform plan`

# Expected Behavior
Should find the proper ECS instance data

# Actual Behavior
```
Error: error getting password: Action Forbidden, error message: {"forbidden": {"message": "Policy doesn't allow ecs:serverPasswords:manage to be performed.", "code": 403}}
```

The API responds with a missing "manage" permission wich I don't wan't to permit terraform as I only need the data provider and want to query an ECS. I think this might be optional for the data provider

**Comment by anton-sidelnikov** [comment]
@dabeck this is not from provider, the API check policies before answer you. Password could not be exposed to Viewer.

**Comment by dibi-codes** [comment]
> @dabeck this is not from provider, the API check policies before answer you. Password could not be exposed to Viewer.

Ok got it. And the API has no endpoint for listing/viewing all ECSs accordingly without the need for a "manage" permission? 🤔
Is there any way to obtain a list of ECSs via terraform.

**Comment by anton-sidelnikov** [comment]
@dabeck I did some workaround, will be available in next release

**Comment by anton-sidelnikov** [comment]
Fixed in latest release
