### ISSUE TITLE
Add opentelekomcloud_vpc_eip_associate resource

### ISSUE THREAD

**Issue by sebbbastien** [opentelekomcloud/terraform-provider-opentelekomcloud#1986]
Hi,

Please allow us to associate an EIP [`opentelekomcloud_vpc_eip_v1`](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/vpc_eip_v1) to a port [`opentelekomcloud_networking_network_v2`](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/networking_port_v2).

Best regards,

**Comment by anton-sidelnikov** [comment]
@sebbbastien Hey, for v2 resources you can use opentelekomcloud_networking_floatingip_associate_v2

**Comment by sebbbastien** [comment]
Hi,

I can confirm that using `opentelekomcloud_networking_floatingip_associate_v2` to bind an EIP to a `openstack_networking_port_v2` resource is working fine.

Maybe a short sentence to describe this usage on `opentelekomcloud_networking_floatingip_associate_v2` documentation can help others.


Thanks for your help,

Best regards,

**Comment by anton-sidelnikov** [comment]
@sebbbastien interesting that no doc file for this resource, i will add

**Comment by anton-sidelnikov** [comment]
@sebbbastien https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/networking_floatingip_associate_v2
