### ISSUE TITLE
opentelekomcloud_vpc_eip_v1 - Explanation of "type"

### ISSUE THREAD

**Issue by salvatorelali** [opentelekomcloud/terraform-provider-opentelekomcloud#1989]
# Issue

The doc for [opentelekomcloud_vpc_eip_v1](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/vpc_eip_v1) says, that the used type must be supported by "the system", which leads to a page saying almost the same thing.

We like to have a clearer information about what "the system" supports, as we try to create an EIP of type "5_gray" to connect it to a Dedicated LoadBalancer.

## further information

This resource:

```bash
resource "opentelekomcloud_vpc_eip_v1" "webkatalog_lb_eip" {
  publicip {
    type = "5_gray"
  }
  bandwidth {
    name        = "webkatalog_lb_bandwidth"
    size        = 100
    share_type  = "PER"
    charge_mode = "traffic"
  }
}
```

throws this exception while tf apply:

```bash
│ Error: error allocating EIP: Bad request with: [POST https://vpc.eu-de.otc.t-systems.com/v1/52492e7b01fd487c8ae9f3de12c19bfd/publicips], error message: {"code":"VPC.0501","message":"PublicIp type is invalid."}
│ 
│   with opentelekomcloud_vpc_eip_v1.webkatalog_lb_eip,
│   on lb.tf line 23, in resource "opentelekomcloud_vpc_eip_v1" "webkatalog_lb_eip":
│   23: resource "opentelekomcloud_vpc_eip_v1" "webkatalog_lb_eip" {
│ 
```

If we create the EIP as part of a resource "opentelekomcloud_lb_loadbalancer_v3", it works perfectly.

**Comment by anton-sidelnikov** [comment]
@salvatorelali The value can be 5_bgp (Dynamic BGP), 5_mailbgp (Mail BGP), or 5_gray (Dedicated load balancer, shared load balancer).
You cannot create 5_gray by this module this type reserved only for loadbalancers and can be created only by loadbalancer service. It is not possible to attach eip to existing loadbalancer v3. EIP can be assigned only on creation, we still discussing with dev team about that, but no improvements so far.

**Comment by k11h-de** [comment]
@anton-sidelnikov 
Oh thats a pity. 
When we modify / increase the bandwidth size in the setup you suggested, the EIP is destroyed and recreated which is a pain in a production environment. It is not an issue to define the EIP implicitly, but adjusting the bandwidth size without "downtime" is.

**Comment by anton-sidelnikov** [comment]
> @anton-sidelnikov Oh thats a pity. When we modify / increase the bandwidth size in the setup you suggested, the EIP is destroyed and recreated which is a pain in a production environment. It is not an issue to define the EIP implicitly, but adjusting the bandwidth size without "downtime" is.

Hm, i will check, maybe possible to not destroy ip while bandwidth change

**Comment by anton-sidelnikov** [comment]
In latest release added option for change bandwidth without recreating lb
