### ISSUE TITLE
Set TimeZone on RDS resource

### ISSUE THREAD

**Issue by netclectic** [opentelekomcloud/terraform-provider-opentelekomcloud#1993]
# Description of the enhancement

Currently there is no way to set the Timezone for an RDS instance as the `resource_opentelekomcloud_rds_instance_v3` has no timezone property exposed. Strangely it is available in the equivalent datasource.

Please add a timezone property to the RDS v3 resource so this can set during RDS creation.

**Comment by vladimirvshivkov** [comment]
Sorry, but we do not have API for that.
Datasource can provide you info about the timezone, but we cannot update it via resource.

**Comment by netclectic** [comment]
That's a shame.

**Comment by anton-sidelnikov** [comment]
@netclectic Added example in #2006 how to change this parameter through opentelekomcloud_rds_parametergroup_v3

**Comment by netclectic** [comment]
That's great, thanks!
