### ISSUE TITLE
CCE NodePool "SoldOut"-Error will destroy created NodePool and create a new

### ISSUE THREAD

**Issue by bbung** [opentelekomcloud/terraform-provider-opentelekomcloud#1997]
# Terraform provider version

Terraform v1.3.3
on darwin_arm64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.31.8

# Affected Resource(s)

opentelekomcloud_cce_node_pool_v3

# Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

resource "opentelekomcloud_cce_node_pool_v3" "node_pool_1" {
  cluster_id         = opentelekomcloud_cce_cluster_v3.cluster_1.id
  name               = "node-pool-01"
  os                 = "EulerOS 2.9"
  flavor             = "s3.large.4"
  initial_node_count = 2
  availability_zone  = "eu-de-01"
  key_pair           = opentelekomcloud_compute_keypair_v2.cce_ha_nodes_keypair.name
  scale_enable             = true
  min_node_count           = 2
  max_node_count           = 10
  scale_down_cooldown_time = 10
  priority                 = 1

  root_volume {
    size       = 40
    volumetype = "SSD"
    kms_id = data.opentelekomcloud_kms_key_v1.key_1.id
  }
  data_volumes {
    size       = 100
    volumetype = "SSD"
    kms_id = data.opentelekomcloud_kms_key_v1.key_1.id
  }

  depends_on = [
    opentelekomcloud_compute_keypair_v2.cce_ha_nodes_keypair
  ]

  timeouts {
    create = "1h"
    update = "30m"
    delete = "30m"
  }
}

```

# Debug Output/Panic Output

```
│ Error: error creating Open Telekom Cloud CCE Node Pool: unexpected state 'SoldOut', wanted target ''. last error: %!s(<nil>)
│ 
│   with opentelekomcloud_cce_node_pool_v3.node_pool_2,
│   on cluster.tf line 91, in resource "opentelekomcloud_cce_node_pool_v3" "node_pool_2":
│   91: resource "opentelekomcloud_cce_node_pool_v3" "node_pool_2" {
│ 
```

terraform apply again
```
  # opentelekomcloud_cce_node_pool_v3.node_pool_2 is tainted, so must be replaced
+/- resource "opentelekomcloud_cce_node_pool_v3" "node_pool_2" {
      ~ id                       = "12e53261-698f-11ed-b11b-02550a10004a" -> (known after apply)
      ~ k8s_tags                 = {} -> (known after apply)
        name                     = "dev-otc-001-node-pool-de-02"
      + status                   = (known after apply)
        # (11 unchanged attributes hidden)

      ~ data_volumes {
            # (3 unchanged attributes hidden)
        }

      ~ root_volume {
            # (3 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }
```
Plan: 1 to add, 0 to change, 1 to destroy.# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

If for the reason of a "SoldOut" flavor the node pool can not be created in full capacity. For example if only one of two requested nodes can be created, terraform will fail with the above error message. Running 'terraform apply' , the NodePool should NOT be deleted and instead it should try to create the missing nodes (ie. scale the node pool to the desired size)

# Actual Behavior

If for the reason of "SoldOut" the node pool can not be created in full capacity. For example if only one of two requested nodes can be created, terraform will fail with the above error message. Running 'terraform apply' again will DESTROY the created nodePool (and therefor delete all nodes that are already created) and create a new nodepool.

You can somehow mitigate the deletion of the "tainted" node pool if you use the "create_before_destroy" lifecycle rule. But this will only create more tainted node pools as long as one creation is fully successful and then delete all tainted node pools but this will bind more resources at OTC and enhance the issue of missing resources in the first place.

# Important Factoids

# References

**Comment by artem-lifshits** [comment]
Hello @bbung, `SoldOut` issue points out that there are not enough resources on AZ.
You can contact OTC support and request quota increase for CCE resources.

Regarding the issue at hand - do I understand correctly that you expect some nodes to be created/auto-scaled by terraform even though it wouldn't 100% resemble terraform config?

**Comment by bbung** [comment]
Hi @artem-lifshits,

> SoldOut issue points out that there are not enough resources on AZ.
You can contact OTC support and request quota increase for CCE resources.

Thanks, I was aware of that. Issue is addressed at OTC and is not a quota issue.

> Regarding the issue at hand - do I understand correctly that you expect some nodes to be created/auto-scaled by terraform even though it wouldn't 100% resemble terraform config?

You are right, if you view it from the terraform point of view, that sounds wrong. I will discuss this issue further with OTC, i cannot think of any solution that the provider could handle this situation differently. Issue Clothed. Thank you.
