### ISSUE TITLE
[VPC] - Custom Route Table Management

### ISSUE THREAD

**Issue by sebbbastien** [opentelekomcloud/terraform-provider-opentelekomcloud#1999]
Hello

As a Terraform developer, I would like to create custom route tables with specific routes and associate desired subnet(s).

I would like something like:

- `opentelekomcloud_custom_route_table`: create the route table
- `opentelekomcloud_custom_route_table_association`: associate one or more subnet to a custom route table
- `opentelekomcloud_custom_route_table_route`: create a route into a given custom route table

Could it be possible to add these new resources for the next provider release?

Thanks in advance,

Sébastien

**Comment by anton-sidelnikov** [comment]
@sebbbastien hello, we will check if it possible from api side

**Comment by anton-sidelnikov** [comment]
Waiting for API documentation

**Comment by artem-lifshits** [comment]
@sebbbastien new resource was implemented for route table management: `opentelekomcloud_vpc_route_table_v1`, please check.
