### ISSUE TITLE
Role name does not fit for eu-ch2

### ISSUE THREAD

**Issue by generalpax** [opentelekomcloud/terraform-provider-opentelekomcloud#2008]
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/data-sources/identity_role_v3

This table of role name documentation does not work for eu-ch2.

**Comment by anton-sidelnikov** [comment]
@generalpax docs updated but api changes from time to time, if role doesn't work pls check roles through direct api calls
