### ISSUE TITLE
Since today: OpenTelekomCloud Security Group Rule: Too many requests have been sent in a given amount of time

### ISSUE THREAD

**Issue by tobiashoefler** [opentelekomcloud/terraform-provider-opentelekomcloud#2012]
# Terraform provider version
1.31.8

# Affected Resource(s)
- opentelekomcloud_networking_secgroup_rule_v2

# Debug Output/Panic Output
Error: OpenTelekomCloud Security Group Rule: Too many requests have been sent in a given amount of time. Pause requests, wait up to one minute, and try again.

# Steps to Reproduce
1. `terraform plan`

# Important Factoids
The error occurs since today. The exact same execution ran perfectly fine yesterday at 9:22 pm. 
We tried it at different times today. All executions resulted in the same error

**Comment by tobiashoefler** [comment]
Hi @anton-sidelnikov,
thanks a lot for the fast response (and fix).
When are you planning to create a new release?
Would it work to decrease parallelism until the new release is available?

Thanks!

**Comment by anton-sidelnikov** [comment]
@tobiashoefler yes it may helps if you set parallelism to 1, next release will be on 7th of December(Wednesday)

**Comment by tobiashoefler** [comment]
@anton-sidelnikov, thanks for the new version!
Unfortunately, the error still exists:
`Error: OpenTelekomCloud Security Group Rule: Too many requests have been sent in a given amount of time. Pause requests, wait up to one minute, and try again.`

This is very critical for us since we cannot change our infra at the moment....

**Comment by anton-sidelnikov** [comment]
@tobiashoefler hi, please give me all the list of resources from your infra, maybe I can also decrease some others calls. And I will try to push backend team to increase amount of calls, not so much we can do from our side.
And how many rules you try to create/update?

**Comment by tobiashoefler** [comment]
thanks a lot for your support!

The following resources are used most (sorted by usage):
opentelekomcloud_networking_secgroup_rule_v2
opentelekomcloud_evs_volume_v3
opentelekomcloud_compute_volume_attach_v2
opentelekomcloud_lb_member_v3
opentelekomcloud_compute_instance_v2
opentelekomcloud_networking_secgroup_v2
opentelekomcloud_lb_pool_v3
opentelekomcloud_lb_monitor_v3
opentelekomcloud_lb_listener_v3
opentelekomcloud_dns_recordset_v2


At the moment we have around 650 security group rules. I think we want to add another 10 now. But during the `terraform plan`, all resources are `Refreshing state...`. Therefore, probably every rule will lead to an API call

**Comment by anton-sidelnikov** [comment]
@tobiashoefler I added retry function to SDK for 429 errors, hope it helps to avoid this issue in the future, today I created more than 700 security group rules in 54.66s without fails. Workaround will be available in next release 21.12. But maybe still need to use decreased level of parallelism.

**Comment by anton-sidelnikov** [comment]
@tobiashoefler please check on latest

**Comment by tobiashoefler** [comment]
Thanks a lot! It works again with the default parallelism of 10.
