### ISSUE TITLE
DDS single node instances support missing

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#2016]
Hi, it is now possible to create single node DDS instances.
But the values for opentelekomcloud_dds_instance_v3 do not allow the single value for mode and type 
The infos can be found here https://docs.otc.t-systems.com/api/dds/dds_api_0020.html

# Terraform provider version
v1.31.9

# Affected Resource(s)
DDS

!--
Please list the resources as a list, for example:
opentelekomcloud_dds_instance_v3

# Terraform Configuration Files
locals {
  mongo_mode = terraform.workspace == "prod" ? "ReplicaSet" : "Single"
  mongo_class = terraform.workspace == "prod" ? "dds.mongodb.s2.medium.4.repset" : "dds.mongodb.s2.medium.4.single"
  mongo_availability_zone = local.otc_az # Perhaps spread over 3 for production
}

variable "mongo_root_pw" {
  description = "Password for 'root' account in MongoDB"
  type        = string
  sensitive   = true
}

resource "opentelekomcloud_dds_instance_v3" "instance" {
  name = "mongodb"
  datastore {
    type           = "DDS-Community"
    version        = "4.0"
    storage_engine = "wiredTiger"
  }

  availability_zone = local.mongo_availability_zone
  vpc_id            = opentelekomcloud_vpc_v1.binosight.id
  subnet_id         = opentelekomcloud_vpc_subnet_v1.mongodb.id
  security_group_id = opentelekomcloud_networking_secgroup_v2.mongodb.id
  password          = var.mongo_root_pw # Admin user is rwuser
  mode              = local.mongo_mode
  flavor {
    type      = "replica"
    num       = 1 # Is this where we decide if it is single not or 3-node replica set?
    storage   = "ULTRAHIGH"
    size      = 30
    spec_code = local.mongo_class
  }
}

# Debug Output/Panic Output
╷
│ Error: expected mode to be one of [Sharding ReplicaSet], got Single Node
│
│   with opentelekomcloud_dds_instance_v3.instance,
│   on mongodb.tf line 27, in resource "opentelekomcloud_dds_instance_v3" "instance":
│   27:   mode              = local.mongo_mode
│
╵
╷
│ Error: expected flavor.0.type to be one of [mongos shard config replica], got single
│
│   with opentelekomcloud_dds_instance_v3.instance,
│   on mongodb.tf line 29, in resource "opentelekomcloud_dds_instance_v3" "instance":
│   29:     type      = "single"
│
╵

# Steps to Reproduce
1. `terraform apply`

# Expected Behavior
The single node DDS instance should be able to be created

# Actual Behavior
Terrorform throws an error during file validation

**Comment by anton-sidelnikov** [comment]
@CHS-OTC hey, please check on latest version
