### ISSUE TITLE
Support setting SWR Repo Sharing settings

### ISSUE THREAD

**Issue by schjan** [opentelekomcloud/terraform-provider-opentelekomcloud#2020]
It would be nice to have an additional Terraform resource like `opentelekomcloud_swr_repository_permissions_v2` or `[...]_repository_sharing` to be able to share an SWR Repository with a different domain using Terraform

**Comment by anton-sidelnikov** [comment]
Will add new resource when implement it in SDK

**Comment by anton-sidelnikov** [comment]
@schjan opentelekomcloud_swr_domain_v2 Manages the SWR image sharing domain resource within Open Telekom Cloud.
