### ISSUE TITLE
using opentelekomcloud_obs_bucket_object completely breaks buckets

### ISSUE THREAD

**Issue by canaykin** [opentelekomcloud/terraform-provider-opentelekomcloud#2023]
# Terraform provider version
Tested on 1.3.3

# Affected Resource(s)
opentelekomcloud_obs_bucket_object

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_obs_bucket_object" "secrets" {
  key          = var.bucket_object_key
  encryption   = true
  content      = jsonencode(var.secrets)
  content_type = "application/json"
  bucket       = opentelekomcloud_obs_bucket.secrets.bucket
  kms_key_id   = opentelekomcloud_kms_key_v1.encrypted_secrets_key.id
}
```
- Note that while the docs point `sse_kms_key_id` for the attribute, it actually is `kms_key_id`
- The bucket, the KMS key and the bucket object resources are created in region level (eu-de) project and not in a sub-project as they are supposed to be.

# Debug Output/Panic Output
```
│ Error: error listing objects of OBS bucket otc-obs-test-bucket-5: InternalError,
│  Reason: We encountered an internal error. Please try again.
│ 
│   with module.encyrpted_secrets_bucket.opentelekomcloud_obs_bucket_object.secrets,
│   on ../../modules/obs_secrets_writer/main.tf line 24, in resource "opentelekomcloud_obs_bucket_object" "secrets":
│   24: resource "opentelekomcloud_obs_bucket_object" "secrets" {
```

# Steps to Reproduce

1. Create an OBS bucket with KMS encryption (may also work without encryption, I did not test it without)
2. Create an object in the bucket via `opentelekomcloud_obs_bucket_object` with the same KMS key

# Expected Behavior
The resource is supposed to create an object inside the bucket.

# Actual Behavior
Resource used to work without issues but currently it results in a 500 internal error and breaks the bucket completely:

![image](https://user-images.githubusercontent.com/70644420/207852905-e8f063c3-3d31-4ff9-bcaf-41a6ddcfd2e4.png)

# Important Factoids
- The object "appears" to be written to the bucket as the bucket information displays the number of objects and the total size correctly
- As the bucket information shows the objects, the bucket is considered not empty and can not be deleted
- Since objects can not be accessed, the bucket is no longer removable by the user
- Uploading new objects appear to work and the object count and size is increased when new objects are pushed, but the objects tab remains unresponsive with 500

**Comment by artem-lifshits** [comment]
Hi @canaykin could you please provide provider parameters that you use?
Also do I understand correctly that you are using KMS keys from a sub-project?
Can you also share which IAM policy in regards of OBS your account have?

Thank you.

**Comment by canaykin** [comment]
hi @artem-lifshits . We are using the module from [opentelekomcloud-project-factory](https://github.com/iits-consulting/terraform-opentelekomcloud-project-factory/tree/master/modules/obs_secrets_writer) and passing the aliased region level provider (eu-de in this case) in the following manner:

```HCL
provider "opentelekomcloud" {
  auth_url    = "https://iam.${var.region}.otc.t-systems.com/v3"
  tenant_name = var.region
  alias       = "top_level_project"
}

module "stage_secrets_to_encrypted_s3_bucket" {
  providers = {opentelekomcloud=opentelekomcloud.top_level_project}
 ...
}
```
The authentication secrets of the provider are taken from environment via `OS_DOMAIN_NAME`, `OS_ACCESS_KEY `and `OS_SECRET_KEY`.

**Comment by artem-lifshits** [comment]
@canaykin I wasn't able to reproduce the issue with your config.

Does that config consistently break every bucket you try to upload object to?

**Comment by canaykin** [comment]
@artem-lifshits I was able to consistently break it on two completely unrelated OTC domains. Also noteworthy is that the module used to work on both of these domains before the latest OBS changes on OTC. 

Perhaps it was just a temporary API bug on the OTC side. I will test it again and post and update here.

**Comment by canaykin** [comment]
@artem-lifshits I can confirm that the module and the object resource are both working without issues at the moment. 

Unfortunately the buckets that were broken still can not be deleted due to "not empty" but show no objects/deleted/fragments that can be removed. I will try to force delete them or ask the OTC support to remove them.

Regardless, as far as I can see, the issue is resolved in terms of the provider.
Thank you very much for the help!
Can.

**Comment by artem-lifshits** [comment]
@canaykin you can try and delete objects via `obsutil` tool that can be downloaded here:
https://support.huaweicloud.com/intl/en-us/utiltg-obs/obs_11_0003.html
Works for OTC too, command to delete all objects looks like that:
`obsutil rm obs://bucket-test -r -f`
Usage can be checked here:
https://support.huaweicloud.com/intl/en-us/utiltg-obs/obs_11_0021.html

**Comment by canaykin** [comment]
@artem-lifshits unfortunately the obsutil also fails to resolve the problem with the broken buckets.

When I try to remove objects it sees no objects:
```
$ obsutil rm obs://otc-obs-test-bucket-5 -r -f
Start at 2022-12-21 12:48:29.545052343 +0000 UTC

[_________________________________________________________________________________________________] ?% tps:0.00 0/0 28ms
Warn: No task to run
```
And when I try to force remove the bucket:
```
$ obsutil rm obs://otc-obs-test-bucket-5 -f
Start at 2022-12-21 12:48:34.212854357 +0000 UTC

Delete bucket [otc-obs-test-bucket-5] failed, status [409], error code [BucketNotEmpty], error message [The bucket you tried to delete is not empty], request id [0000018534BA7A12441E6FA5BA54A5F8]
```
In more detail, the bucket stat shows 2 objects and 8.03KB size:
```
$ obsutil stat obs://otc-obs-test-bucket-5
Start at 2022-12-21 12:53:30.426255887 +0000 UTC

Bucket:
  obs://otc-obs-test-bucket-5
StorageClass:
  standard
Location:
  eu-de
ObsVersion:
  3.0
BucketType:
  OBJECT
ObjectNumber:
  2
Size:
  8.03KB
Quota:
  0
```
but object listing shows:
```
$ obsutil ls obs://otc-obs-test-bucket-5
Start at 2022-12-21 12:53:02.879432807 +0000 UTC

Listing objects .

Total size of bucket is: 0B
Folder number is: 0
File number is: 0
```
As such think I will need to open a support ticket for this one.

**Comment by artem-lifshits** [comment]
@canaykin yep looks like this is an OTC issue, if you open a ticket I can try to push it to OPS guys directly.
