### ISSUE TITLE
bind VPC resource to a Project resource

### ISSUE THREAD

**Issue by PeterBarczi** [opentelekomcloud/terraform-provider-opentelekomcloud#2030]
# bind VPC resource to a Project resource

We are about to deploy e.g. VPC under a specific Project e.g. eu-de_test.
We want to create both resources using Terraform, but getting into "checkedn & egg" problem.
How can I bound the VPC to a specific project (which should be also created within terraform apply run)?

I've been browsing the docu, but so far no working solution :(

I'm able to bind a VPC to a Project which already exists, but how to bind VPC to a Project which should be also created within the same terraform apply run?

Many thanks in advance

**Comment by anton-sidelnikov** [comment]
@PeterBarczi Hello, as I understand you need to define multiple providers in your config and switch between them.

**Comment by anton-sidelnikov** [comment]
If you need some additional help, please respond here. And I reopen this issue.
