### ISSUE TITLE
[VPC] deleting `opentelekomcloud_networking_router_route_v2` finishes with error

### ISSUE THREAD

**Issue by anton-sidelnikov** [opentelekomcloud/terraform-provider-opentelekomcloud#2034]
Deleting `opentelekomcloud_networking_router_route_v2` finishes with error

# Terraform provider version
On latest

# Affected Resource(s)
- opentelekomcloud_networking_router_route_v2
- opentelekomcloud_networking_router_v2

# Terraform Configuration Files
```hcl
TestAccNetworkingV2RouterRoute_basic
```

# Debug Output/Panic Output
Error running post-test destroy, there may be dangling resources: exit status 1
Error: error deleting OpenTelekomCloud Neutron Router Interface: Internal Server Error

# Steps to Reproduce

1. Run `TestAccNetworkingV2RouterRoute_basic`

# Expected Behavior
Resource should delete without errors

# Actual Behavior
Error running post-test destroy, there may be dangling resources: exit status 1
Error: error deleting OpenTelekomCloud Neutron Router Interface: Internal Server Error

**Comment by artem-lifshits** [comment]
This looks like a 448 issue, test passed for me:
 === RUN   TestAccNetworkingV2RouterRoute_basic
=== PAUSE TestAccNetworkingV2RouterRoute_basic
=== CONT  TestAccNetworkingV2RouterRoute_basic
--- PASS: TestAccNetworkingV2RouterRoute_basic (190.98s)
PASS

Process finished with the exit code 0

**Comment by anton-sidelnikov** [comment]
Possible network issue, passed
