### ISSUE TITLE
opentelekomcloud_swr_repository_v2: error when using forward slash ("/") in repository name

### ISSUE THREAD

**Issue by qa-simon-heuser** [opentelekomcloud/terraform-provider-opentelekomcloud#2037]
# Terraform provider version
`registry.terraform.io/opentelekomcloud/opentelekomcloud v1.32.1`

# Affected Resource(s)
- opentelekomcloud_swr_repository_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_swr_organization_v2" "test" {
  name = "test"
}

resource "opentelekomcloud_swr_repository_v2" "repository" {
  name         = "grafana/grafana"
  organization = opentelekomcloud_swr_organization_v2.test.name
  is_public    = false
  category     = "linux"
}
```

# Debug Output/Panic Output
The configuration above does not crash Terraform but rather it produces an error:
```
╷
│ Error: invalid value for name (Only lowercase letters, digits, periods (.), underscores (_), and hyphens (-) are allowed.)
│
│   with opentelekomcloud_swr_repository_v2.repository,
│   on reproduce.tf line 6, in resource "opentelekomcloud_swr_repository_v2" "repository":
│    6:   name         = "grafana/grafana"
│
╵
```

# Steps to Reproduce
1. `terraform apply`

# Expected Behavior
The provider should provision the repository named `grafana/grafana`. It should accept a `/` in the repository name.

# Actual Behavior
The provider reports an error and refuses to create the resource.

# Important Factoids
- *Why should the provider create the repository?* Because when I push an image -- e.g. `grafana/grafana:9.3.1` -- to the SWR via `docker login` & `docker push`, OTC automatically creates such a repository -- `grafana/grafana`. Therefore, it seems that the provider has placed an unnecessary restriction on the repository name.

**Comment by anton-sidelnikov** [comment]
@agileman-droid please, try on latest version

**Comment by qa-simon-heuser** [comment]
Now it works to create the repository! :+1:
However, now we have discovered another issue related to `opentelekomcloud_swr_domain_v2`, which also handles slashes incorrectly. I will create another issue.
