### ISSUE TITLE
Not able to create resource OTC Log Tank service.

### ISSUE THREAD

**Issue by sandipamte** [opentelekomcloud/terraform-provider-opentelekomcloud#2038]
# Terraform provider version
Terraform v1.0.11

# Affected Resource(s)
opentelekomcloud_logtank_group_v2

# Terraform Configuration Files
```
resource "opentelekomcloud_logtank_group_v2" "log_group1" {
  group_name  = "${var.prefix}-log_group"
}

resource "opentelekomcloud_logtank_topic_v2" "log_topic1" {
  group_id   = opentelekomcloud_logtank_group_v2.log_group1.id
  topic_name   = "${var.prefix}-log_topic"
}

resource "opentelekomcloud_vpc_flow_log_v1" "flowlog1" {
  name   = "${var.prefix}-flow_log"
  description   = "VPC Flow Logs"
  resource_type = "vpc"
  resource_id   = opentelekomcloud_vpc_v1.vpc.id
  traffic_type  = "all"
  log_group_id  = opentelekomcloud_logtank_group_v2.log_group1.id
  log_topic_id  = opentelekomcloud_logtank_topic_v2.log_topic1.id
}

```

# Debug Output/Panic Output
Error: error creating log group: Bad request with: [POST https://lts.eu-de.otc.t-systems.com/v2.0/10b697ff8903458b9dd5c24a4da4808b/log-groups], error message: {"error_code":"LTS.0106","error_msg":"The log group TTL day must be integer and between 1 and 365"}
│ 
│   with module.provisioning.module.network.opentelekomcloud_logtank_group_v2.log_group1,
│   on ../../modules/network/network.tf line 35, in resource "opentelekomcloud_logtank_group_v2" "log_group1":
│   35: resource "opentelekomcloud_logtank_group_v2" "log_group1" {

We added ttl_in_days = 7 in the code, 
Code as below:
resource "opentelekomcloud_logtank_group_v2" "log_group1" {
  group_name  = "${var.prefix}-log_group"
  ttl_in_days = 7
}

Output:
Error: Value for unconfigurable attribute
│ 
│   with module.provisioning.module.network.opentelekomcloud_logtank_group_v2.log_group1,
│   on ../../modules/network/network.tf line 37, in resource "opentelekomcloud_logtank_group_v2" "log_group1":
│   37:   ttl_in_days = 7
│ 
│ Can't configure a value for "ttl_in_days": its value will be decided automatically based on the result of applying this configuration.

Can you please suggest how can we create OTC Log Tank Service using terraform?

**Comment by artem-lifshits** [comment]
Hello @sandipamte `ttl_in_days` is definitely a required parameter for `opentelekomcloud_logtank_group_v2`, we will fix that part along with newer API introduced for lts service.

Unfortunately I wasn't able to reproduce the error with added `ttl_in_days`, here's my config:
```
variable "vpc_name" {
  default = "opentelekomcloud_vpc"
}

variable "vpc_cidr" {
  default = "192.168.0.0/16"
}

resource "opentelekomcloud_vpc_v1" "vpc_v1" {
  name = var.vpc_name
  cidr = var.vpc_cidr
}

resource "opentelekomcloud_logtank_group_v2" "log_group1" {
  group_name  = "${var.prefix}-log_group"
  ttl_in_days = 7
}

resource "opentelekomcloud_logtank_topic_v2" "log_topic1" {
  group_id   = opentelekomcloud_logtank_group_v2.log_group1.id
  topic_name   = "${var.prefix}-log_topic"
}

resource "opentelekomcloud_vpc_flow_log_v1" "flowlog1" {
  name   = "${var.prefix}-flow_log"
  description   = "VPC Flow Logs"
  resource_type = "vpc"
  resource_id   = opentelekomcloud_vpc_v1.vpc_v1.id
  traffic_type  = "all"
  log_group_id  = opentelekomcloud_logtank_group_v2.log_group1.id
  log_topic_id  = opentelekomcloud_logtank_topic_v2.log_topic1.id
}

variable "prefix" {
     default = "terra" 
}
```

Could you please try it again and send the results? Thank you.
