### ISSUE TITLE
Please add Terraform code to create OTC Log Transfer service

### ISSUE THREAD

**Issue by sandipamte** [opentelekomcloud/terraform-provider-opentelekomcloud#2039]
# Description of the enhancement
Dear team,

We want to transfer OTC VPC Flow logs into OBS bucket using Terraform Log Transfer service.
We can create VPC Flowlog, Log Group, Log Topic, but moving those logs into OBS bucket, log transfer service is being used.

**Comment by artem-lifshits** [comment]
Hello @sandipamte 2 of the API for `Log transfer` aren't currently working, I've opened a ticket for this issue:
https://jira.tsi-dev.otc-service.com/browse/OTCORC-2727
As soon as it's fixed I will be able to create terraform resource.

**Comment by artem-lifshits** [comment]
Hello @sandipamte resource is available in latest release.
