### ISSUE TITLE
DCS instance creation with engine_version==3.0 fails with missing security_group_id

### ISSUE THREAD

**Issue by sgyuris** [opentelekomcloud/terraform-provider-opentelekomcloud#2047]
# Terraform provider version

terraform -v
Terraform v1.3.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/dns v3.2.3
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.32.2
+ provider registry.terraform.io/rhythmictech/errorcheck v3.0.0
+ provider registry.terraform.io/vancluever/acme v2.7.0

Your version of Terraform is out of date! The latest version
is 1.3.7. You can update by downloading from https://www.terraform.io/downloads.html

# Affected Resource(s)

- opentelekomcloud_dcs_instance_v1

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_networking_secgroup_v2" "redis_sg" {
  name                 = "${var.prefix}-redis-sg"
  description          = "REDIS cache access protection"
  delete_default_rules = true
}

...

resource "opentelekomcloud_dcs_instance_v1" "redis_instance" {
  name           = "${var.prefix}-cache-dcs"
  engine_version = var.redis_config.redis_version
  password       = random_password.redis_password.result
  engine         = "Redis"
  capacity       = var.redis_config.redis_size
  vpc_id         = var.redis_vpc_id
  subnet_id      = var.redis_sn_id

  security_group_id = opentelekomcloud_networking_secgroup_v2.redis_sg.id
  available_zones   = values(data.opentelekomcloud_dcs_az_v1.availability_zones)[*].id
  product_id        = data.opentelekomcloud_dcs_product_v1.redis_type.id
}
```
# Debug Output/Panic Output

╷
│ Error: 1 error occurred:
│       * 'security_group_id' should be set with engine_version==3.0
│ 
│ 
│ 
│   with module.provisioning.module.nextcloud_cache.opentelekomcloud_dcs_instance_v1.redis_instance,
│   on ../../provisioning/modules/nextcloud_redis/redis.tf line 82, in resource "opentelekomcloud_dcs_instance_v1" "redis_instance":
│   82: resource "opentelekomcloud_dcs_instance_v1" "redis_instance" {
│ 

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

Redis instance should be created

# Actual Behavior

See error above.

# Important Factoids

# References

**Comment by artem-lifshits** [comment]
Hello @sgyuris `security_group_id` is a mandatory parameter if you choose to create DCS v3.0.
It's optional for v4.0/5.0.

Documentation:
https://docs.otc.t-systems.com/api/dcs/dcs-api-0312004.html

**Comment by sgyuris** [comment]
Yes I'm well aware of the fact that with version 4 and 5 it is optional. Unfortunately we have old environments with Redis 3.0 and we can't just jump from 3.0 to 5.0.

It is mandatory for us to use Redis 3.0 for now. 

Because of the ?bug? our workflow is broken. If we need recreate a Redis server we can't do it. This is a risk for us.

We just switched from terraform version 0.45 ... the in-place updates were fine in the environment. There was no issue with Redis. Now I run down one of our dev env and started the build up. And now I'm stuck because of the error.

**Comment by artem-lifshits** [comment]
@sgyuris thank you for detailed answer, I was able to reproduce the issue.
I will fix the bug and in the meanwhile please try to use provider [v1.31.4](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/releases/tag/v1.31.4).

Another workaround is to write id of security group directly in the parameter (without linking it to resource).

**Comment by sgyuris** [comment]
May I ask when could we expect the next release with the fix?

Unfortunately with v1.31.4 the - for us - required version of elasticsearch not supported. :(

Thank you!

**Comment by artem-lifshits** [comment]
Next provider release will happen on 25th of January.

**Comment by sgyuris** [comment]
Thanks.

**Comment by artem-lifshits** [comment]
Hello @sgyuris fix is implemented in latest provider release, please check.
