### ISSUE TITLE
Wrong reference vpc_id should be router_id

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#205]
### Terraform Version
```
$ terraform --version
Terraform v0.11.11
+ provider.opentelekomcloud v1.5.2


```

### Affected Resource(s)
- opentelekomcloud_cce_cluster_v3

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "opentelekomcloud_cce_cluster_v3" "cce_cluster" {
  name = "${var.project_name}-cce-${var.network_name}"

  description            = "CCE Cluster for: ${var.project_name} in ${var.network_name}"
  flavor_id              = "${var.cce_master_flavor}"
  cluster_version        = "${var.cce_version}"
  container_network_type = "${var.cce_pod_network_type}"
  vpc_id                 = "${var.router_id}"
  subnet_id              = "${var.subnet_id}"
  cluster_type           = "VirtualMachine"
}
```
`opentelekomcloud_networking_network_v2.vpc.id` is different from `opentelekomcloud_networking_router_v2.router.id` and seams to be required.

This might be an issue on OTC side aswell because the output always tells that the `VPC <VPCID> not found`

### Expected Behavior
vpc_id should be referenced correctly.

### Actual Behavior
instead OTC requires the router_id 

### Steps to Reproduce
1. `terraform apply`

**Comment by niuzhenguo** [comment]
@Moep90 Sorry, I don't understand the problems here, you mean opentelekomcloud_networking_network_v2 is VPC?  Please refer to the router docs [here](https://www.terraform.io/docs/providers/opentelekomcloud/r/networking_router_v2.html) The router is the top-level resource for the VPC within OpenTelekomCloud

**Comment by Moep90** [comment]
Ok so...

As you can see below the `opentelekomcloud_networking_network_v2.vpc.vpc.id = bd687c20-b219-4698-bfee-dc1647eafd6a`
and the
`opentelekomcloud_networking_router_v2.router.id = b018b019-5e6f-4b28-bb56-61e3c08aa7d5`.

But in CCE is a vpc_id referenced `"vpc_id": "b018b019-5e6f-4b28-bb56-61e3c08aa7d5"`.

Which means that not `opentelekomcloud_networking_network_v2.vpc.id.` is required here but instead the `opentelekomcloud_networking_router_v2.router.id` is referenced in CCE.
This is somewhat misleading in my opinion. 

I found this out by checking an older statefile I had and comparing ID by ID within those resources.

VPC
```hcl
 "data.opentelekomcloud_networking_network_v2.vpc": {
                    "type": "opentelekomcloud_networking_network_v2",
[...]
                        "id": "bd687c20-b219-4698-bfee-dc1647eafd6a",
[...]
                            "id": "bd687c20-b219-4698-bfee-dc1647eafd6a",
[...]
                    "provider": "provider.opentelekomcloud"
                },
```
This is a router for all my subnet's **not the extnet router**..
```hcl
"opentelekomcloud_networking_router_v2.router": {
[...]
                    "primary": {
                        "id": "b018b019-5e6f-4b28-bb56-61e3c08aa7d5",
[...]
                            "id": "b018b019-5e6f-4b28-bb56-61e3c08aa7d5",
[...]
                    "deposed": [],
                    "provider": "provider.opentelekomcloud"
                }
            }
```
CCE Cluster
```hcl
"resources": {
                "data.opentelekomcloud_cce_cluster_v3.cluster": {
                    "type": "opentelekomcloud_cce_cluster_v3",
[...]
                        "id": "4ddb5a61-f481-11e8-849b-0255ac10161c",
[...]
                            "subnet_id": "bd687c20-b219-4698-bfee-dc1647eafd6a",
                            "vpc_id": "b018b019-5e6f-4b28-bb56-61e3c08aa7d5"
[...]
}
```

**Comment by niuzhenguo** [comment]
@Moep90 I think that's because you name the opentelekomcloud_networking_network_v2 as `vpc` but in fact it's not. You can choose to use opentelekomcloud_vpc_v1 and opentelekomcloud_vpc_subnet_v1 set instead of opentelekomcloud_networking_router, opentelekomcloud_networking_network, and opentelekomcloud_networking_subnet to keep consistent with console and be more clear.

**Comment by Moep90** [comment]
@niuzhenguo ok good point. I'll try it.

But then anyway..something like this should not be possible:
There may be others as well
https://www.terraform.io/docs/providers/opentelekomcloud/r/dns_zone_v2.html
router_id refers to vpc_id..
```
resource "opentelekomcloud_dns_zone_v2" "private_example_com" {
  name = "private.example.com."
  email = "private@example.com"
  description = "An example for private zone"
  ttl = 3000
  type = "private"
  router = {
     router_id = "${var.vpc_id}"
     router_region = "${var.region}"
  }
}
```

**Comment by niuzhenguo** [comment]
@Moep90 Thanks, will try to avoid such reference.

**Comment by niuzhenguo** [comment]
@Moep90 Closing this, feel free to open again if there's still questions, thanks!
