### ISSUE TITLE
RDS PostgreSQL since v13 Parameter Change is not working 

### ISSUE THREAD

**Issue by uli-max** [opentelekomcloud/terraform-provider-opentelekomcloud#2051]
# Terraform provider version

Terraform v1.3.4 on darwin_arm64
provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.32.2

# Affected Resource(s)

opentelekomcloud_rds_instance_v3

# Terraform Configuration Files
```hcl
// Customer-specific configuration file

database = {
   rds_enable = true
   enable_ha = false
   pg_version = "13"
   vol_size = 40
   db_vol_type= "COMMON" # ULTRAHIGH = SSD
   db_flavor = "rds.pg.c2.medium"

   parameters = {
      max_prepared_transactions = "200"
      max_connections = "250"
   }
}
```
# Debug Output/Panic Output

Error: error applying parameters to the instance: error applying configuration parameters: Action Forbidden, error message: {"error_msg":"Failed to change parameter template values because the DB instance is currently being operated.","error_code":"DBS.212033"}

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

Modification of RDS parameters 

# Actual Behavior

RDS is created, but the parameters are not set.
See also: https://community.open-telekom-cloud.com/community/community?id=community_question&sys_id=f1da7aa3b79429d0d15aa7b16b8c02af

# Important Factoids

None 

# References

See OTC Community 
Error applying parameter max_prepared_transactions = "200" to RDS instance in Terraform with PostgreSQL version 13 or higher
https://community.open-telekom-cloud.com/community/community?id=community_question&sys_id=f1da7aa3b79429d0d15aa7b16b8c02af

**Comment by artem-lifshits** [comment]
Hello @uli-max same issue is already described in #2044.
This is OTC issue and ticket progress can be checked here: https://jira.tsi-dev.otc-service.com/browse/OTCDB-2547

**Comment by uli-max** [comment]
@artem-lifshits: The https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/2044 is a little bit different, it is not possible to create v14. a v13 works as long there is no parameter change. But both looks like underlaying API issues.

**Comment by mazw77** [comment]
Same problem occurs with Postgres v14 after fix of https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/2044#issuecomment-1406451548

**Comment by artem-lifshits** [comment]
Hello @mazw77 please create additional ticket for the issue with detailed information and configuration you are using.

**Comment by artem-lifshits** [comment]
Hello @mazw77 @uli-max we've implemented a WA in latest release, please check.

**Comment by uli-max** [comment]
@artem-lifshits : I can confirm for me it is working. 
Also updated the answer in OTC-Community. 
Thanks!
