### ISSUE TITLE
DDS: settings tags fails while mentioned in documentation

### ISSUE THREAD

**Issue by k11h-de** [opentelekomcloud/terraform-provider-opentelekomcloud#2059]
# Terraform provider version

`v1.32.2`

# Affected Resource(s)

- opentelekomcloud_dds_instance_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_dds_instance_v3" "replica-set" {
  name = "mytest"
  ...
  tags = {
    creator = "BRU"
    team = "a-team"
  }
}
```

# Debug Output/Panic Output

```
tf apply
╷
│ Error: Unsupported argument
│ 
│   on dds.tf line 38, in resource "opentelekomcloud_dds_instance_v3" "replica-set":
│   38:   tags = {
│ 
│ An argument named "tags" is not expected here.
```

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

Hi Team,
first: thanks a lot for your work on these modules. We're using them a lot.

We try to use resource tags for all the infrastructure we create. I noticed that in DDS adding tags fails.
In the docs there is a reference to tags in the [Attributes Reference](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/dds_instance_v3#attributes-reference) but when I try to set tags, it fails.
According to the OTC docs, the API supports setting tags (see reference).

# Actual Behavior

Setting `tags` fails. 

# References

https://docs.otc.t-systems.com/document-database-service/api-ref/apis_v3.0_recommended/db_instance_management/creating_a_db_instance.html#requests

**Comment by artem-lifshits** [comment]
Hello @k11h-de tags management is fixed in the latest provider release, please check.

**Comment by k11h-de** [comment]
Perfect, works like a charm. 
Thanks a million for the quick fix.
