### ISSUE TITLE
DMS - Topic retention validation too restrictive

### ISSUE THREAD

**Issue by deibl** [opentelekomcloud/terraform-provider-opentelekomcloud#2063]
# Terraform provider version
1.32.1

# Affected Resource(s)
opentelekomcloud_dms_topic_v1

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_dms_topic_v1" "topic" {
  ...
  retention_time   = 720
}
```

# Debug Output/Panic Output
expected retention_time to be in the range (1 - 168), got 720

# Steps to Reproduce
set retention_time to value > 168

# Expected Behavior
retention_time up to 720 should work (as this is possible via UI) 

# Actual Behavior
expected retention_time to be in the range (1 - 168), got 720

**Comment by artem-lifshits** [comment]
Looks like maximum `retention time` has changed since this resource was first introduced.
Will be fixed on next release.

**Comment by artem-lifshits** [comment]
Hello @deibl retention time was fixed in latest release, please check.
