### ISSUE TITLE
[IMS] opentelekomcloud_ims_image_v2 missing option

### ISSUE THREAD

**Issue by r-ising** [opentelekomcloud/terraform-provider-opentelekomcloud#2067]
Hello,

with the api its possible to create a system image from an data volume.

https://docs.otc.t-systems.com/image-management-service/api-ref/ims_apis/image/creating_an_image.html
(Parameters for creating a system disk image using a data disk)

POST https://ims.eu-de.otc.t-systems.com/v2/cloudimages/action
```json
{
  "name": "test123",
  "os_version": "Windows Server 2016 Standard 64bit",
  "volume_id": "123"
}
```

Can you please support this kind of creating images?

**Comment by anton-sidelnikov** [comment]
@r-ising 
Sorry for long answer, you can use another resource for that:
```
resource "opentelekomcloud_ims_data_image_v2" "image_1" {
  name        = "data_image"
  description = "created by Terraform"
  volume_id   = opentelekomcloud_compute_instance_v2.instance_1.volume_attached.1.id
}
```

**Comment by r-ising** [comment]
@anton-sidelnikov Hey, sorry for the late answer, but if you create a data image, than its not a system image, correct? Because if it is a system image you need to specific the os version, like the request i show before:

 **"os_version": "Windows Server 2016 Standard 64bit"**

**Comment by r-ising** [comment]
@anton-sidelnikov Here the screenshots of my test:

![Screenshot 2023-02-21 at 16 02 33](https://user-images.githubusercontent.com/16190832/220381196-cf7eb1fc-23d7-42d1-83bf-527825e09b27.png)
![Screenshot 2023-02-21 at 15 54 30](https://user-images.githubusercontent.com/16190832/220381205-e80e7507-e7eb-46c1-bf8e-da77cc0dd35d.png)
![Screenshot 2023-02-21 at 15 54 24](https://user-images.githubusercontent.com/16190832/220381211-e66c4959-d4af-466e-8629-4638c4bf33db.png)

**Comment by anton-sidelnikov** [comment]
@r-ising yes, got it. We need to update our ims sdk for that, after that will implement this into terraform

**Comment by anton-sidelnikov** [comment]
@r-ising hi, please check on latest
```
resource "opentelekomcloud_ims_image_v2" "image_volume" {
  name        = "image_volume"
  volume_id   = "54a6c3a4-8511-4d01-818f-3fe5177cbb07"
  os_version  = "Debian GNU/Linux 10.0.0 64bit"
  description = "created by Terraform"

  tags = {
    foo = "bar"
    key = "value"
  }
}
```

**Comment by r-ising** [comment]
@anton-sidelnikov perfect, now its working

<img width="675" alt="Screenshot 2023-02-24 at 13 34 32" src="https://user-images.githubusercontent.com/16190832/221186337-a6d6524f-4f62-4bab-a85b-e5c5e17737f5.png">
