### ISSUE TITLE
expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[]'

### ISSUE THREAD

**Issue by Shizzlebix** [opentelekomcloud/terraform-provider-opentelekomcloud#2072]
# Terraform provider version
in version 1.31.2 all works fine
in version 1.32.3 it come this error

│       * data_volumes.0.extend_param: '' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[]'
│
│
│
│   with data.opentelekomcloud_cce_node_v3.server_id_node-xxx-network-xxx,
│   on main.tf line 344, in data "opentelekomcloud_cce_node_v3" "server_id_node-xxx-network-xxx":
│  344: data "opentelekomcloud_cce_node_v3" "server_id_node-xxx-network-xxx" 

Initializing provider plugins...
- Finding terraform-providers/opentelekomcloud versions matching ">= 0.0.0"...
- Finding latest version of hashicorp/local...
- Finding latest version of hashicorp/template...
- Using previously-installed hashicorp/local v2.3.0
- Using previously-installed hashicorp/template v2.2.0
- Using previously-installed terraform-providers/opentelekomcloud v1.32.3

**Comment by artem-lifshits** [comment]
Hello @Shizzlebix fix is available in latest release, please check.
