### ISSUE TITLE
[TurboSFS/CBR Vault]

### ISSUE THREAD

**Issue by sfhl** [opentelekomcloud/terraform-provider-opentelekomcloud#2073]
Hi there,
Please add support for the new TurboSFS beakcup feature in CBR

`Error: expected resource.0.type to be one of [OS::Nova::Server OS::Cinder::Volume], got OS::Sfs::Turbo`

**Comment by artem-lifshits** [comment]
Hello @sfhl sfsturbo support is available in latest release.
