### ISSUE TITLE
opentelekomcloud_cbr_vault_v3 to support SFS Turbo volumes.

### ISSUE THREAD

**Issue by canaykin** [opentelekomcloud/terraform-provider-opentelekomcloud#2074]
Greetings team!

While working with the SFS Turbo instances I wanted to add the backup vaults and policies for the storage system. While it was possible to do via the Cloud Console, it appears the current provider does not yet support the SFS Turbo Vaults.

With a little bit of digging I was able to determine that the CBR Vault created via Cloud Console show the resource type as `OS::Sfs::Turbo`:

``` JSON
    "resources": [
      {
        "id": "<REDACTED>" ,
        "type": "OS::Sfs::Turbo" ,
        "name": "<REDACTED>" ,
        "auto_protect": true ,
        "size": 500 ,
        "backup_size": 0 ,
        "backup_count": 0 ,
        "protect_status": "available" ,
        "extra_info": {}
      }
    ] ,
```

Unfortunately, this resource type can not be used with the terraform provider due to the resource schema validation allowing only `OS::Nova::Server` and `OS::Cinder::Volume`:

``` go
Elem: &schema.Resource{
	Schema: map[string]*schema.Schema{
	...
		"type": {
			Type:     schema.TypeString,
			Required: true,
			ValidateFunc: validation.StringInSlice([]string{
				"OS::Nova::Server", "OS::Cinder::Volume",
			}, false),
		},
	...
	}
}
```

We are planning to add prepackaged storage modules for EVS and SFS going forward and as such, having the CBR Vault as a backup solution within them would be great.

Looking forward for your answer and as always, thank you very much for the great provider!
Best,
Can.

**Comment by artem-lifshits** [comment]
Hello @canaykin sfsturbo support is available in latest release.
