### ISSUE TITLE
The provider opentelekomcloud/opentelekomcloud does not support resource type "opentelekomcloud_cts_event_notification_v3"

### ISSUE THREAD

**Issue by sandipamte** [opentelekomcloud/terraform-provider-opentelekomcloud#2075]
# Terraform provider version
Terraform v1.0.11

# Affected Resource(s)
opentelekomcloud_cts_event_notification_v3

# Terraform Configuration Files
```hcl

resource "opentelekomcloud_cts_tracker_v1" "tracker_v1" {
  bucket_name      = "bpmaas-cts-logs"
  file_prefix_name = "${var.prefix}"
  is_support_smn = true
  #is_lts_enabled   = true
}

resource "opentelekomcloud_smn_topic_v2" "topic_1" {
  name         = "${var.prefix}-topic"
  display_name = "The display name of topic_1"
}

resource "opentelekomcloud_smn_subscription_v2" "subscription_1" {
topic_urn = opentelekomcloud_smn_topic_v2.topic_1.id
endpoint = "sandip.amte@t-systems.com"
protocol = "email"
remark = "cts"
}

resource "opentelekomcloud_cts_event_notification_v3" "notification_v3" {
  notification_name = "test_user"
  operation_type    = "customized"
  topic_id          = opentelekomcloud_smn_topic_v2.topic_1.id
  status            = "enabled"
  operations {
    resource_type = "vpc"
    service_type  = "VPC"
    trace_names = ["deleteVpc",
    "createVpc"]
  }
  operations {
    resource_type = "evs"
    service_type  = "EVS"
    trace_names = ["createVolume",
    "deleteVolume"]
  }
  notify_user_list {
    user_group = "user_group"
    user_list  = ["user_one", "user_two"]
  }
}
```

# Debug Output/Panic Output
│ Error: Invalid resource type
│ 
│   on ../../modules/cts/cts.tf line 22, in resource "opentelekomcloud_cts_event_notification_v3" "notification_v3":
│   22: resource "opentelekomcloud_cts_event_notification_v3" "notification_v3" {
│ 
│ The provider opentelekomcloud/opentelekomcloud does not support resource type "opentelekomcloud_cts_event_notification_v3".

# Steps to Reproduce
We are using opentelekomcloud V1.27.2, and i upgraded it to 1.27.4.
For both version i am getting same error,
Could you please guide to enable the service.

Reference Ticket: https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1948

**Comment by artem-lifshits** [comment]
Hello @sandipamte ``opentelekomcloud_cts_event_notification_v3`` was implemented in provider `v1.32.0`.
Latest version is `1.32.3`. 

Please also keep in mind that API for ``opentelekomcloud_cts_tracker_v1`` was changed and therefore resource is working a bit different (`is_support_smn` is not supported anymore, smn is now specified in events).
