### ISSUE TITLE
OTC Terraform service : An argument named is not expected here.

### ISSUE THREAD

**Issue by sandipamte** [opentelekomcloud/terraform-provider-opentelekomcloud#2076]
# Terraform provider version
Terraform v1.0.11

# Affected Resource(s)
opentelekomcloud_kms_key_v1

# Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "opentelekomcloud_kms_key_v1" "db_kms_key" {
  provider        = opentelekomcloud.subproject
  key_alias       = "Test"
  key_description = "PEGA as a Service db encryption key"
  pending_days    = "7"
  realm           = "test"
  is_enabled      = "true"
  rotation_interval = 365
  rotation_enabled = "true"
  
}
```

# Debug Output/Panic Output
│ Error: Unsupported argument
│ 
│   on main.tf line 147, in resource "opentelekomcloud_kms_key_v1" "db_kms_key":
│  147:   rotation_interval = 365
│ 
│ An argument named "rotation_interval" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 148, in resource "opentelekomcloud_kms_key_v1" "db_kms_key":
│  148:   rotation_enabled = "true"
│ 
│ An argument named "rotation_enabled" is not expected here.

# References
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/kms_key_v1

**Comment by artem-lifshits** [comment]
Please run this config with provider version > 1.31.0.

**Comment by sandipamte** [comment]
Tried this on latest version, and it is working fine.
Thanks for quick response.
