### ISSUE TITLE
RDS PosgreSQL version 14 can not be created since v1.32.3 release

### ISSUE THREAD

**Issue by mercora** [opentelekomcloud/terraform-provider-opentelekomcloud#2083]
Hello, I  noticed that after upgrading the Terraform provider >1.32.2 im no longer able to create PostgreSQL instances with version 14. Apparently it tries to get a list of valid flavors for that version which fails and aborts the Plans execution.

# Terraform provider versions
provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.33.0
provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.32.3

# Affected Resource(s)
opentelekomcloud_rds_instance_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_rds_instance_v3" "some_name" {
  name = "some-name-20230210"

  vpc_id            = data.opentelekomcloud_vpc_subnet_v1.otc_managed_rds.vpc_id
  subnet_id         = data.opentelekomcloud_vpc_subnet_v1.otc_managed_rds.network_id
  availability_zone = ["eu-de-01"]
  security_group_id = opentelekomcloud_networking_secgroup_v2.some_name_rds.id

  flavor = "rds.pg.c2.medium"
  db {
    password = random_password.some_name_rds.result
    type     = "PostgreSQL"
    version  = "14"
    port     = "5432"
  }
  volume {
    type = "COMMON"
    size = 100

    disk_encryption_id = opentelekomcloud_kms_key_v1.some_name_rds.id
  }
  backup_strategy {
    start_time = "08:00-09:00"
    keep_days  = 7
  }
}
```

# Debug Output/Panic Output
```
│ Error: 1 error occurred:
│       * unable to get flavor pages: Bad request with: [GET https://rds.eu-de.otc.t-systems.com/v3/01334465114c4d8586900df6b86972dc/flavors/PostgreSQL?version_name=14.4], error message: {"error_msg":"Invalid database version.","error_code":"DBS.280236"}
│ 
│ 
│ 
│   with opentelekomcloud_rds_instance_v3.some_name,
│   on persistence.tf line 30, in resource "opentelekomcloud_rds_instance_v3" "some_name":
│   30: resource "opentelekomcloud_rds_instance_v3" "some_name" {
│ 
```

# Steps to Reproduce
1. `terraform apply`

# Expected Behavior
Instance is created with version 14 according to the Terraform Plan. 

# Actual Behavior
Plan execution aborts with the message above.

# Important Factoids
Creating the instance on the Console with this flavor/version works fine.
The opentelekomcloud_rds_flavors_v3 data resource correctly reflects this too.
Downgrading the Terraform provider to 1.32.2 solves the issue.

**Comment by anton-sidelnikov** [comment]
@mercora please check on latest
