### ISSUE TITLE
opentelekomcloud_identity_projects_v3 not returning domain_id?

### ISSUE THREAD

**Issue by shaderecker** [opentelekomcloud/terraform-provider-opentelekomcloud#2090]
# Terraform provider version

Terraform v1.3.9
on linux_amd64
\+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.33.0

# Affected Resource(s)

opentelekomcloud_identity_projects_v3
# Terraform Configuration Files
```hcl
data "opentelekomcloud_identity_role_v3" "tms_adm" {
  name = "tms_adm"
}

data "opentelekomcloud_identity_projects_v3" "all_projects" {
}

resource "opentelekomcloud_identity_role_assignment_v3" "role_assignment_tms_adm" {
  group_id  = opentelekomcloud_identity_group_v3.my_group.id
  domain_id = data.opentelekomcloud_identity_projects_v3.all_projects.domain_id
  role_id   = data.opentelekomcloud_identity_role_v3.tms_adm.id
}
```

# Debug Output/Panic Output

╷
│ Error: Unsupported attribute
│
│   on main.tf line 74, in resource "opentelekomcloud_identity_role_assignment_v3" "role_assignment_tms_adm":
│   74:   domain_id = data.opentelekomcloud_identity_projects_v3.all_projects.domain_id
│
│ This object has no argument, nested block, or exported attribute named "domain_id".
╵

# Steps to Reproduce

1. `terraform apply` or `terraform validate`

# Expected Behavior

The domain_id should be returned

# Actual Behavior

It fails with the aforementioned error.

**Comment by shaderecker** [comment]
Update: It seems that just the docu is not 100% correct on that.
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/data-sources/identity_projects_v3
After inspecting the data source I figured out that the `domain_id` is actually supplied as `id`.

So using it like this works:
```hcl
data "opentelekomcloud_identity_role_v3" "tms_adm" {
  name = "tms_adm"
}

data "opentelekomcloud_identity_projects_v3" "all_projects" {
}

resource "opentelekomcloud_identity_role_assignment_v3" "role_assignment_tms_adm" {
  group_id  = opentelekomcloud_identity_group_v3.my_group.id
  domain_id = data.opentelekomcloud_identity_projects_v3.all_projects.id
  role_id   = data.opentelekomcloud_identity_role_v3.tms_adm.id
}
```

Could you adjust the docu that it explains this `id` parameter?

**Comment by artem-lifshits** [comment]
Documentation fixed in latest provider version.
