### ISSUE TITLE
opentelekomcloud_lb_loadbalancer_v3 datasource not working

### ISSUE THREAD

**Issue by mele78** [opentelekomcloud/terraform-provider-opentelekomcloud#2098]
# Terraform provider version
Terraform v1.3.9
on linux_amd64

# Affected Resource(s)
- opentelekomcloud_lb_loadbalancer_v3

# Terraform Configuration Files
```hcl
#
# ELB
#
data "opentelekomcloud_lb_loadbalancer_v3" "loadbalancer_1" {
  name = "elb-mleimete-test"
}

#
# DNS records
#
locals {
  # Pointed to ECS with instance switch but should point to ELB instead
  record_instance = [data.opentelekomcloud_lb_loadbalancer_v3.loadbalancer_1.vip_address]
}
```

# Debug Output/Panic Output
data.opentelekomcloud_lb_loadbalancer_v3.loadbalancer_1: Reading...
╷
│ Error: Plugin did not respond
│ 
│   with data.opentelekomcloud_lb_loadbalancer_v3.loadbalancer_1,
│   on main.tf line 4, in data "opentelekomcloud_lb_loadbalancer_v3" "loadbalancer_1":
│    4: data "opentelekomcloud_lb_loadbalancer_v3" "loadbalancer_1" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-opentelekomcloud_v1.33.1 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 139 [running]:
github.com/opentelekomcloud/terraform-provider-opentelekomcloud/opentelekomcloud/common.StrSlice(...)
        github.com/opentelekomcloud/terraform-provider-opentelekomcloud/opentelekomcloud/common/utils.go:209
github.com/opentelekomcloud/terraform-provider-opentelekomcloud/opentelekomcloud/services/elb/v3.dataSourceLoadBalancerV3Read({0x173c7a0?, 0xc0005f92f0?}, 0x0?, {0x1496a60?, 0xc00018e380})
        github.com/opentelekomcloud/terraform-provider-opentelekomcloud/opentelekomcloud/services/elb/v3/data_source_opentelekomcloud_lb_loadbalancer_v3.go:153 +0xa4a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000112b60, {0x173c7a0, 0xc0005f92f0}, 0xd?, {0x1496a60, 0xc00018e380})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:724 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000112b60, {0x173c7a0, 0xc0005f92f0}, 0xc000214680, {0x1496a60, 0xc00018e380})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:943 +0x145
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000208018, {0x173c7a0?, 0xc0005f91d0?}, 0xc00048eea0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1179 +0x38f
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0004501e0, {0x173c7a0?, 0xc0005f89c0?}, 0xc000764dc0)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:658 +0x3ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x143da60?, 0xc0004501e0}, {0x173c7a0, 0xc0005f89c0}, 0xc00011c310, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:421 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000001e0, {0x1740c60, 0xc0001bf6c0}, 0xc0000c1680, 0xc0001b8bd0, 0x1fbadf0, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc0000001e0, {0x1740c60, 0xc0001bf6c0}, 0xc0000c1680, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-opentelekomcloud_v1.33.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

# Steps to Reproduce
1. terraform plan

# Expected Behavior

# Actual Behavior
Critical exit

# Important Factoids
It seems like the loadbalancer data resource can not be called by name. The loadbalancer exists.

# References

**Comment by anton-sidelnikov** [comment]
@mele78 please check on latest
