### ISSUE TITLE
Provide examples for deploying DCS as Active/Passive or Cluster

### ISSUE THREAD

**Issue by slauger** [opentelekomcloud/terraform-provider-opentelekomcloud#2108]
Hi,

we are trying to deploy DCS in active/passive mode. We are a bit confused how the code should look like.  It would be great if you could add some examples. The current example code in the repository is 3 years old and seems a bit outdated.

https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/tree/devel/examples/basic-examples/modules/dcs

Currently we use the code below code, which results in the following error:

```
│ Error: Expected HTTP response code [200] when accessing [GET https://dcs.eu-de.otc.t-systems.com/v1.0/availableZones], but got 504 instead
│ {"request_id":"....","error_code":"APIGW.0201","error_msg":"Service DCS timed out (30000 ms)"}
│ 
│ 
│   with module.awesome_reds.data.opentelekomcloud_dcs_az_v1.primary,
│   on ../terraform-modules/otc_cache/main.tf line 1, in data "opentelekomcloud_dcs_az_v1" "primary":
│    1: data "opentelekomcloud_dcs_az_v1" "primary" {
│ 
╵
╷
│ Error: not found any available zones
│ 
│   with module.awesome_reds.data.opentelekomcloud_dcs_az_v1.secondary,
│   on ../terraform-modules/otc_cache/main.tf line 7, in data "opentelekomcloud_dcs_az_v1" "secondary":
│    7: data "opentelekomcloud_dcs_az_v1" "secondary" {
```

```
variable "spec_code" {
  type = string
  default = "redis.ha.xu1.large.r2.4"
}

data "opentelekomcloud_dcs_az_v1" "primary" {
  name = "AZ3"
  port = "8004"
  code = "eu-de-03"
}

data "opentelekomcloud_dcs_az_v1" "secondary" {
  name = "AZ2"
  port = "8004"
  code = "eu-de-02"
}

data "opentelekomcloud_dcs_product_v1" "dcs_product" {
  spec_code = var.spec_code
}

resource "opentelekomcloud_dcs_instance_v1" "dcs_instance" {
  name           = var.name
  engine_version = var.engine_version
  password       = random_password.password.result
  engine         = "Redis"
  capacity       = var.capacity
  subnet_id      = data.opentelekomcloud_vpc_subnet_v1.subnet.id
  vpc_id         = data.opentelekomcloud_vpc_v1.vpc.id
  available_zones = [
    data.opentelekomcloud_dcs_az_v1.primary.id,
    data.opentelekomcloud_dcs_az_v1.secondary.id
  ]
  product_id = data.opentelekomcloud_dcs_product_v1.dcs_product.id

  enable_whitelist = var.enable_whitelist

  dynamic "whitelist" {
    for_each = var.whitelist
    content {
      group_name = whitelist.value["group_name"]
      ip_list    = whitelist.value["ip_list"]
    }
  }

  dynamic "backup_policy" {
    for_each = var.enable_backup == true ? toset(["enabled"]) : toset([])
    content {
      save_days   = 30
      backup_type = "manual"
      begin_at    = "02:00-03:00"
      period_type = "weekly"
      backup_at   = [1, 2, 3, 4, 5, 6, 7]
    }
  }

  maintain_begin = "03:00"
  maintain_end   = "05:00"
}
```

**Comment by artem-lifshits** [comment]
Hello @slauger you are right, documentation is a bit outdated, fix is on the way.

In order to get AZ id you can provide AZ name without any additional arguments in the following format:
`eu-de-01`/`eu-de-02`/`eu-de-03`.

In this case `id`/`port`/`code` will be computed automatically for specified AZ.

Here are couple examples on overall data_source usage:
```
data "opentelekomcloud_dcs_az_v1" "primary" {
  name = "eu-de-02"
}
```
```
data "opentelekomcloud_dcs_az_v1" "primary" {
  name = "eu-de-01"
  port = "8002"
}
```
```
data "opentelekomcloud_dcs_az_v1" "primary" {
  port = "8002"
  code = "eu-de-01"
}
```

I have also noticed that one of the request ended with 504, if the error persists after providing correct AZ arguments please open a ticket for OTC support and we will try to push it (I wasn't able to reproduce this status on my side).

**Comment by robert1x2** [comment]
@artem-lifshits thx quick reply - I will open up the OTC support ticket. Thx.

**Comment by torsten-online** [comment]
Hi @artem-lifshits

Your answer fixed our issue.

The Problem was, that we used a own defined name, e.g. for AZ2 and AZ3. 

The name should be the code of the AZ, so when we use eu-de-02 and eu-de-03, all seems to be work (running the plan) over terraform with the DCS Instance setup as Primary/Standby.

Thx.

**Comment by slauger** [comment]
Thanks for the quick response and help!

It seems that the documentation here was just wrong. The value `AZ1` was copied from the documentation.

<img width="703" alt="Bildschirm­foto 2023-03-10 um 17 12 51" src="https://user-images.githubusercontent.com/8333300/224366681-bd97e87e-62a9-4fdb-b6c6-a63ab8a4b503.png">

In general it would be great if the documentation could always contain all accepted values for a parameter.

**Comment by artem-lifshits** [comment]
Examples and documentation will be updated on next release.
