### ISSUE TITLE
Support importing opentelekomcloud_lb_listener_v2

### ISSUE THREAD

**Issue by siebertm** [opentelekomcloud/terraform-provider-opentelekomcloud#2112]
We need to manage ELB listeners created by nginx-ingress, and need a way to import those into our TF state, but the resource does not support importing

**Comment by anton-sidelnikov** [comment]
@siebertm you can import from v3 resource

**Comment by siebertm** [comment]
Thanks Anton!

Is that a new change? Last time I checked, the v3 resource was only available for dedicated ELB...

Micha

**Comment by anton-sidelnikov** [comment]
@siebertm this is how api works now, apiv3 can work with v2 resources, this is some new feature

**Comment by anton-sidelnikov** [comment]
But anyway I've added separated import will be available in the next release

**Comment by anton-sidelnikov** [comment]
Import added in latest release
