### ISSUE TITLE
cannot add ipv6 subnet

### ISSUE THREAD

**Issue by generalpax** [opentelekomcloud/terraform-provider-opentelekomcloud#2119]
# Terraform provider version

# Affected Resource(s)

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_networking_subnet_v2" "tsch-mgmt-6-dummy" {
  network_id = opentelekomcloud_networking_network_v2.tsch-mgmt-dummy.id
  #cidr       = "2a07:8700:1:1003::/64"
  ip_version = 6
  name       = "tsch-mgmt-6-dummy"
}
```

# Debug Output/Panic Output

```

│ Error: Missing required argument
│ 
│   on vpc-tsch-mgmt.tf line 40, in resource "opentelekomcloud_networking_subnet_v2" "tsch-mgmt-6-dummy":
│   40: resource "opentelekomcloud_networking_subnet_v2" "tsch-mgmt-6-dummy" {
│ 
│ The argument "cidr" is required, but no definition was found.
```

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

subnet should be created with ipv6 enabled and attached ipv6 range, because its denied to attach fixed ipv6

# Actual Behavior
subnet is not created

# Important Factoids

# References

**Comment by anton-sidelnikov** [comment]
@generalpax hi, regarding doc, only supported version is ipv4 https://docs.otc.t-systems.com/virtual-private-cloud/api-ref/native_openstack_neutron_apis_v2.0/subnet/creating_a_subnet.html#vpc-subnet02-0003
