### ISSUE TITLE
Failed to decode CSBS from state after newer provider version

### ISSUE THREAD

**Issue by krkardos** [opentelekomcloud/terraform-provider-opentelekomcloud#2127]
Since update to 1.33.0, our CSBS module is not working anymore

# Terraform provider version
  ">=1.33.0"

# Affected Resource(s)
- opentelekomcloud_csbs_backup_policy_v1

# Debug Output/Panic Output
 Error: Failed to decode resource from state
│ 
│ Error decoding
│ "module.csbs_pgsql.opentelekomcloud_csbs_backup_policy_v1.backup_policy_v1"
│ from previous state: missing expected {
╵
╷
│ Error: missing expected {
│ 
│   with module.csbs.opentelekomcloud_csbs_backup_policy_v1.backup_policy_v1,
│   on .terraform/modules/csbs/main.tf line 1, in resource "opentelekomcloud_csbs_backup_policy_v1" "backup_policy_v1":
│    1: resource "opentelekomcloud_csbs_backup_policy_v1" "backup_policy_v1" {
# Steps to Reproduce
Run code with provider >=1.33.0

# Expected Behavior
Working script

# Actual Behavior
Our script breaks, only works with <= v.1.32.3

# Important Factoids
CSBS module and our scripts works fine with provider <=1.32.3 , but after provider's version upgrade, with newer versions our existing and already implemented code/script breaks, 

Our csbs module looks like:
```terraform
resource "opentelekomcloud_csbs_backup_policy_v1" "backup_policy_v1" {
  name = var.name

  dynamic "resource" {
    for_each = var.resources
    content {
      ....
    }
  }

  scheduled_operation {
 ...
  }
}
```

**Comment by anton-sidelnikov** [comment]
@krkardos Hi, please attach more details regarding scheduled_operation section

**Comment by krkardos** [comment]
@anton-sidelnikov It looks like this:


```terraform
  scheduled_operation {
    enabled         = true
    name            = "default"
    operation_type  = "backup"
    permanent       = false
    max_backups     = var.max_backups // 10
    day_backups     = var.day_backups // 0
    week_backups    = var.week_backups // 0
    month_backups   = var.month_backups // 12
    year_backups    = var.year_backups //0
    retention_duration_days = var.retention_duration_days
    timezone        = var.timezone
    trigger_pattern = var.trigger_pattern
  }
```

**Comment by anton-sidelnikov** [comment]
@krkardos Hello, try on latest version

**Comment by krkardos** [comment]
> @krkardos Hello, try on latest version

@anton-sidelnikov  Thank You very much, now it is working fine :- )
