### ISSUE TITLE
CSS - support new opensearch version Opensearch_1.3.6

### ISSUE THREAD

**Issue by k11h-de** [opentelekomcloud/terraform-provider-opentelekomcloud#2134]
Can you please add support for the new opensearch version `Opensearch_1.3.6` released to OTC last week?
This is possible in the OTC Web Console and we would love to use your terraform provider for this.

# Terraform provider version
1.34.0

# Affected Resource(s)

- opentelekomcloud_css_cluster_v1

# Debug Output/Panic Output
```
│ Error: expected datastore.0.version to be one of [7.6.2 7.9.3 7.10.2], got Opensearch_1.3.6
```

# Steps to Reproduce
use `Opensearch_1.3.6` as cluster version.

# Actual Behavior
creating a cluster fails with above error. Please support the new version.

# References
https://open-telekom-cloud.com/en/support/release-notes/css-offers-opensearch-1-3-6-as-alternative-to-elasticsearch

**Comment by anton-sidelnikov** [comment]
@vladimirvshivkov I think we should get rid validation for versions, to avoid this in future

**Comment by anton-sidelnikov** [comment]
@k11h-de Hello, please check on latest version

**Comment by k11h-de** [comment]
works like a charm. Thanks
