### ISSUE TITLE
security_token can be used for iam authentication in opentelekomcloud provider

### ISSUE THREAD

**Issue by haochen233** [opentelekomcloud/terraform-provider-opentelekomcloud#2139]
Huaweicloud provider suppouts security_token to authenticate with a [temporary security credential](https://support.huaweicloud.com/intl/en-us/iam_faq/iam_01_0620.html). 
![image](https://user-images.githubusercontent.com/45994302/230841769-f0c7dc2c-8b6e-46f0-bc33-36bafc63db4d.png)
This is helpful when user A delegates to user B to create the resource. User B can get Temporary Security Credentials(AK/SK and SecurityToken) through agency from IAM. So I suggest opentelekomcloud provider to suppout  security_token to authenticate for iam

**Comment by artem-lifshits** [comment]
Hello @haochen233 there's an issue with domain level client creation when provider is using temporary AK/SK + security token.

Project level client works fine but under the hood of the provider both project and domain level clients are created. Domain one doesn't work as intended, ticket opened to fix the issue: https://jira.tsi-dev.otc-service.com/browse/OTCSEC-4873

**Comment by haochen233** [comment]
> Hello @haochen233 there's an issue with domain level client creation when provider is using temporary AK/SK + security token.
> 
> Project level client works fine but under the hood of the provider both project and domain level clients are created. Domain one doesn't work as intended, ticket opened to fix the issue: https://jira.tsi-dev.otc-service.com/browse/OTCSEC-4873

thanks @artem-lifshits , When will this feature go live？

**Comment by artem-lifshits** [comment]
Hello @haochen233 should be available on next release (18-19 of April).

**Comment by artem-lifshits** [comment]
Hello @haochen233 feature was implemented on latest release, please check.
