### ISSUE TITLE
Assigning firewalls

### ISSUE THREAD

**Issue by mriegler** [opentelekomcloud/terraform-provider-opentelekomcloud#214]
### Terraform Version
Terraform v0.11.11
+ provider.openstack v1.14.0
+ provider.opentelekomcloud v1.5.2

### Affected Resource(s)
- opentelekomcloud_fw_firewall_group

### Terraform Configuration Files
```hcl
resource "opentelekomcloud_fw_firewall_group_v2" "public" {
  name = "public"
  ingress_policy_id = "${opentelekomcloud_fw_policy_v2.public_in.id}"
  egress_policy_id = "${opentelekomcloud_fw_policy_v2.public_out.id}"
}
```

### Expected Behavior
I can assign a firewall using Terraform. 

### Actual Behavior
OTC creates custom routers when you create a VPC. There's no automatic way to get those "side-effect" resources. One of them would be a port whose ID I need to assign the firewall. Without it, the firewall configuration is pointless. How do I assign a firewall? Enabling SNAT for the automatically created router is another such example.

**Comment by niuzhenguo** [comment]
@mriegler Thanks for raising this, but can you get the port ID you needed on GUI? will try to find if we lose something from the API response.

**Comment by niuzhenguo** [comment]
@mriegler Regarding the port ID, you can use networking_port data source to fetch it with the gateway ip:
```
data "opentelekomcloud_networking_port_v2" "port_1" {
  fixed_ip = "${var.gateway_ip}"
  network_id = "${var.network_id}"
}

resource "opentelekomcloud_fw_firewall_group_v2" "public" {
  name = "public"
  ingress_policy_id = "${opentelekomcloud_fw_policy_v2.public_in.id}"
  egress_policy_id = "${opentelekomcloud_fw_policy_v2.public_out.id}"
  ports = [
    "${data.opentelekomcloud_networking_port_v2.port_1.id}"
  ]
}
```

**Comment by niuzhenguo** [comment]
@mriegler Does the solution above work?

**Comment by mriegler** [comment]
Works for me.
