### ISSUE TITLE
CCE: Setting Container Engine on Node

### ISSUE THREAD

**Issue by david-slr** [opentelekomcloud/terraform-provider-opentelekomcloud#2141]
# Description of the enhancement
Hey, 
with release of Kubernetes 1.25 for CCE we wanted to Create a new Cluster with containerd as Container Engine, but we couldn't find the argument. 
Can we get the Argument for CCE Nodes to set the Container Engine to docker/containerd?

Greetings

**Comment by vladimirvshivkov** [comment]
Released in latest v1.34.2.

**Comment by john-funk** [comment]
Is there an option to avoid replacing nodes? Both the default "docker" as well as "containerd" value force a replacement of the node which is rather unfortunate for production environments.

**Comment by vladimirvshivkov** [comment]
@Jay-Funk 
If runtime is the same with node, no replacement will happen.
Otherwise, node or nodepool will be recreated.

**Comment by john-funk** [comment]
Where can I see the current runtime?

I have a node that was created with v1.34.1 so that I was not able to change the runtime value.
But both using the default "docker" runtime as well as using "containerd" replaces the node.

**Comment by vladimirvshivkov** [comment]
that's basically docker everythere. 
then try to import the node or nodepool like this:
```terraform import opentelekomcloud_cce_node_pool_v3.pool_1 14a80bc7-c12c-4fe0-a38a-cb77eeac9bd6/89c60255-9bd6-460c-822a-e2b959ede9d2```

**Comment by john-funk** [comment]
So it's not possible to use the newer version without having to reimport all nodes manually?

**Comment by vladimirvshivkov** [comment]
It's possible, but if runtime value is not equal, node will be recreated. 
If the ForceNew parameter is not set, then users may face an issue where, for example, runtime of node is `docker`, but you set `containerd`, users will get an error and no node will be created, and all infrastructure will not be updated.
that's the bigger issue, I guess.

Have to think about fix for that case. And will release it soon as a hotfix.

**Comment by vladimirvshivkov** [comment]
Fix released
