### ISSUE TITLE
Output of data provider opentelekomcloud_compute_instances_v2 seems to be incomplete

### ISSUE THREAD

**Issue by bnaard** [opentelekomcloud/terraform-provider-opentelekomcloud#2155]
# Terraform provider version
Output of `terraform -v`:
```bash
Terraform v1.3.7
on darwin_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.34.3
```

# Affected Resource(s)
- data: opentelekomcloud_compute_instances_v2

# Terraform Configuration Files
- terraform to reproduce: https://gist.github.com/bnaard/739911f0b062416236f1a2d563b34e29#file-reproduce-tf
- no `*.tfvars`-files needed

# Received Output
- received output: https://gist.github.com/bnaard/739911f0b062416236f1a2d563b34e29#file-output_received-md
- expected output: https://gist.github.com/bnaard/739911f0b062416236f1a2d563b34e29#file-output_expected-md

# Steps to Reproduce

1. In WebConsole, on an empty tenant, deploy an ECS (spec: eu-de-01 | General-purpose | s3.medium.1 | 1 vCPUs | 1 GiB | Standard_CentOS_Stream-9_latest | System Disk 6GB High-IO | 1 NIC | 1 EIP Dynamic BGP 5 MBit/s | VPC default | Security Group default). No other resources deployed. 

With this terraform script https://gist.github.com/bnaard/739911f0b062416236f1a2d563b34e29#file-reproduce-tf run:

2. `terraform init`

3. `terraform apply`

# References
May relate to https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/2071

**Comment by bnaard** [comment]
Added one more addition to exptected output https://gist.github.com/bnaard/739911f0b062416236f1a2d563b34e29#file-output_expected-md regarding `security_group_ids`:

```hcl
"security_group_ids" = tolist([
        "default",                                           # <== expected sec group IDs instead of sec group names
      ])
```

**Comment by anton-sidelnikov** [comment]
> * opentelekomcloud_compute_instances_v2

Hi @bnaard, do you really need ids of sec groups, or i will just rename this parameter to security_groups? Also flavor ID and flavor name has same value

**Comment by bnaard** [comment]
> > * opentelekomcloud_compute_instances_v2
> 
> Hi @bnaard, do you really need ids of sec groups, or i will just rename this parameter to security_groups? Also flavor ID and flavor name has same value

@anton-sidelnikov Thanks for the rapid reaction in fixing most of the highlighted topics. If I were to choose, I'd like to have ID's everywhere (sec-groups, flavors, disks, images ...), because if I need more, I could use the ID as unique identifier into any other data-structures (eg. retrieve the full disk meta-data, get a flavor-name, or get all other meta-data for sec groups). Names always risk to be not unique. So, as a principle, always having ID's is better.

**Comment by anton-sidelnikov** [comment]
@bnaard check on latest release
