### ISSUE TITLE
Addon Template Changes for CCE v1.25

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#2156]
The old page for 1.19 is https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/devel/opentelekomcloud/services/cce/addon-templates-v1.19.8.md

With the new CCE version 1.25 new addons were introduced.
For old addons the "swr_user" value changed for all 1.25 addons to "cce-addons".
Also NPD and Volcano were introduced as new addons. So an up to date example for CCE v1.25 would be nice to have.

Current template values can be read with this API https://docs.otc.t-systems.com/cloud-container-engine/api-ref/apis/add-on_management/reading_add-on_templates.html#cce-02-0321

**Comment by anton-sidelnikov** [comment]
@CHS-OTC also this contains in addon-templates-*.md:
```
Up to date reference of addon arguments for your cluster you can get using API for listing CCE addon templates
at `https://<cluster_id>.cce.eu-de.otc.t-systems.com/api/v3/addontemplates`, where `<cluster_id>` is ID of the created
cluster.
```

**Comment by anton-sidelnikov** [comment]
New documentation available in latest release
