### ISSUE TITLE
Please check CCE-Cluster provisioning time/notification ...  

### ISSUE THREAD

**Issue by uli-max** [opentelekomcloud/terraform-provider-opentelekomcloud#2158]
# Terraform provider version

Terraform v1.3.5
on darwin_arm64

+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.34.3

# Affected Resource(s)

opentelekomcloud_cce_cluster_v3

# Terraform Configuration Files
```hcl
Just an runtime issue ... 
```

# Debug Output/Panic Output

In OTC-UI Cluster is shown finished after 6.5min. 

![image](https://user-images.githubusercontent.com/104261288/236493347-ff44a982-cd7b-4fcb-9592-c7b9b1852348.png)

But terraform show 10 more minutes "Still creating" ... 
... 
module.cce.opentelekomcloud_cce_cluster_v3.cluster: Still creating... [17m0s elapsed]
module.cce.opentelekomcloud_cce_cluster_v3.cluster: Still creating... [17m10s elapsed]
module.cce.opentelekomcloud_cce_cluster_v3.cluster: Still creating... [17m20s elapsed]
module.cce.opentelekomcloud_cce_cluster_v3.cluster: Creation complete after 17m25s [id=c910abd6-eb49-11ed-bef8-02550a10004e]

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

Please check, why "provider" didn't recognize that OTC is already finished with creation. 

# Actual Behavior

Provider wait or need over 10min to recognize that OTC is already finished. 

# Important Factoids

None ... 

# References

Internal-Jira: CONT-1665

**Comment by anton-sidelnikov** [comment]
@uli-max This cluster with addons or without? Because now if you set no_addons key - terraform will wait additionally because addons statuses was changed and we should wait before deletion

**Comment by Nils-Magnus** [comment]
Could you please provide a stripped down tf template that exemplifies the long-running behavior? Just to rule out to compare apples with pears.

**Comment by victorgetz** [comment]
Uli is using our project factory: https://github.com/iits-consulting/terraform-opentelekomcloud-project-factory/tree/master/modules/cce

We install autoscaler and metrics

**Comment by anton-sidelnikov** [comment]
@uli-max Hi check on latest please

**Comment by uli-max** [comment]
@anton-sidelnikov: 
My Results today: 
![05_42_21](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/104261288/2cbbb686-30f3-41c5-998c-9c23b3c7f7e2)

Looking good for me! 
Only 2-3min lost instead of 10min. 

Thanks for the fix !!!
