### ISSUE TITLE
opentelekomcloud_dcs_instance_v1 documentation is outdated

### ISSUE THREAD

**Issue by EugenFo** [opentelekomcloud/terraform-provider-opentelekomcloud#2160]
The Documentation for [opentelekomcloud_dcs_instance_v1](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/dcs_instance_v1) is a bit outdated. 
For example [access_user](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/dcs_instance_v1#access_user) is still available as an output according to the docs, but in the actual code it was removed with [PR](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/2005/files#diff-0b3c0e167d0fee0f4d3a16de9a5d23da78d498558721d89a899ead931e77d040L77).

**Comment by anton-sidelnikov** [comment]
fixed
