### ISSUE TITLE
opentelekomcloud_dcs_instance_v1 setting `enabled_whitelist = false` still requires `whitelist` configuration

### ISSUE THREAD

**Issue by EugenFo** [opentelekomcloud/terraform-provider-opentelekomcloud#2163]
Hey, there is an logical error when you define `enable_whitelist = false` without the `whitelist` configuration block. 
The code should still work, but in fact it doesn't.

One could argue to just don't configure `enable_whitelist` at all, but if you develop modules for DCS it becomes nearly impossible to create an workaround for such use case. Either your module requires an whitelist or not, you can't let the user decide if they want it or not.

# Terraform provider version

Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.34.3

# Affected Resource(s)

- opentelekomcloud_dcs_instance_v1

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_dcs_instance_v1" "this" {
  [...] # just boilerplate
  engine_version = "5.0"
  enable_whitelist = false
}
```

# Debug Output/Panic Output

```
│ Error: Missing required argument
│ 
│   with module.dcs.opentelekomcloud_dcs_instance_v1.this,
│   on ../../../terraform-module-dcs/main.tf line 35, in resource "opentelekomcloud_dcs_instance_v1" "this":
│   35:   enable_whitelist = false
│ 
│ "enable_whitelist": all of `enable_whitelist,whitelist` must be specified
```

# Steps to Reproduce

Configure an working DCS instance with `enable_whitelist = false` and without the `whitelist` configuration.

# Expected Behavior

The DCS instance should be created as I explicitly have disabled `enable_whistelist`.

# Actual Behavior

Terraform won't create the DCS instance, because `whitelist` is not configured.

**Comment by anton-sidelnikov** [comment]
@EugenFo, you can define variable as null:
```
variable "enable_whitelists" {
  type    = any
  default = null
}
```
but we also thinks about some fix which will remove dependency between this fields

**Comment by anton-sidelnikov** [comment]
@EugenFo Hi! check on latest please

**Comment by EugenFo** [comment]
Can confirm it works now :+1: 
Thanks!
