### ISSUE TITLE
opentelekomcloud_dcs_instance_v1 `whitelist` configuration block doesn't work in an dynamic block

### ISSUE THREAD

**Issue by EugenFo** [opentelekomcloud/terraform-provider-opentelekomcloud#2165]
Hey, I found an weird issue when you want to create the `whitelist` block dynamically with the `dynamic` feature from terraform.
I use the same method for the `configuration` block and with this it works fine. See the example code.
Maybe I did messed up something, but to me it looks like an bug.

# Terraform provider version

Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.34.3

# Affected Resource(s)

- opentelekomcloud_dcs_instance_v1

# Terraform Configuration Files
In dcs_module.tf
```hcl
resource "opentelekomcloud_dcs_instance_v1" "this" {
  [...] # just boilerplate
  engine_version = "5.0"
  enable_whitelist = true

  # this doesn't work
  dynamic "whitelist" {
    for_each = var.whitelists
    content {
      group_name = whitelist.value.group_name
      ip_list = whitelist.value.ip_list
    }
  }

  # this works
  dynamic "configuration" {
    for_each = var.configuration
    content {
      parameter_id = configuration.value.parameter_id
      parameter_name = configuration.value.parameter_name
      parameter_value = configuration.value.parameter_value
    }
  }

}

variable "whitelists" {
  type = list(object({
    group_name = string
    ip_list = list(string)
  }))
  default = []
}

variable "configuration" {
  type = list(object({
    parameter_id = string
    parameter_name = string
    parameter_value = string
  }))
  default = []
}
```

In dcs.tf
```hcl
module "dcs" {
  source = "../dcs_module"
  [...] # just boilerplate

  whitelists = [
    {
      group_name = "test-group"
      ip_list = ["192.168.0.0/24", "172.20.128.0/24"]
    }
  ]

  configuration = [
    {
      parameter_id = "2"
      parameter_name = "maxmemory-policy"
      parameter_value = "allkeys-lru"
    },
    {
      parameter_id = "11"
      parameter_name = "maxclients"
      parameter_value = "1002"
    }
  ]
}
```

# Debug Output/Panic Output

There is no real error output or similar. See actual behavior

# Steps to Reproduce

Use the code snippets from above and try to create and DCS instance with an dynamic whitelist configuration.

# Expected Behavior

DCS instance will be created with the proper whitelist configuration.

# Actual Behavior

Terraform creates the DCS instance that even changes into the running state. Even though the instance was created `Terraform apply` is still running, because it wants to modify the whitelist configuration, but it doesn't show up in the OTC Console. At some point the apply runs into an timeout. 
On the other side the `configuration` setting for the parameters that has the same `dynamic` setup was created properly.

**Comment by anton-sidelnikov** [comment]
Hi @EugenFo
This is weird thing, but you must put comma at the end of the list:
```
  whitelists = [
    {
      group_name = "test-group"
      ip_list = ["192.168.0.0/24", "172.20.128.0/24",]
    }
  ]
```
Vars:
```
configuration = [
  {
    parameter_id = "2"
    parameter_name = "maxmemory-policy"
    parameter_value = "allkeys-lru"
  },
  {
    parameter_id = "11"
    parameter_name = "maxclients"
    parameter_value = "1002"
  }
]
whitelists = [
  {
    group_name = "test-group-name"
    ip_list    = ["10.10.10.1", "10.10.10.2",]
  },
  {
    group_name = "test-group-name-2"
    ip_list    = ["10.11.10.1/24", "10.11.10.2/24",]
  }
]
```
Plan output:
```
Terraform will perform the following actions:

  # opentelekomcloud_dcs_instance_v1.this will be created
  + resource "opentelekomcloud_dcs_instance_v1" "this" {
      + available_zones     = [
          + "bf84aba586ce4e948da0b97d9a7d62fb",
        ]
      + capacity            = 0.125
      + created_at          = (known after apply)
      + description         = (known after apply)
      + enable_whitelist    = false
      + engine              = "Redis"
      + engine_version      = "5.0"
      + id                  = (known after apply)
      + internal_version    = (known after apply)
      + ip                  = (known after apply)
      + maintain_begin      = (known after apply)
      + maintain_end        = (known after apply)
      + max_memory          = (known after apply)
      + name                = "dcs-test"
      + order_id            = (known after apply)
      + password            = (sensitive value)
      + port                = (known after apply)
      + product_id          = "redis.ha.xu1.tiny.r2.128-h"
      + resource_spec_code  = (known after apply)
      + security_group_name = (known after apply)
      + status              = (known after apply)
      + subnet_id           = "44ed75f0-65df-4865-b4d9-4565fc56e2f1"
      + subnet_name         = (known after apply)
      + used_memory         = (known after apply)
      + user_id             = (known after apply)
      + user_name           = (known after apply)
      + vpc_id              = "16dbd25d-c55c-405b-9e56-11b03e7e7dc1"
      + vpc_name            = (known after apply)

      + backup_policy {
          + backup_at   = [
              + 4,
            ]
          + backup_type = "manual"
          + begin_at    = "00:00-01:00"
          + period_type = "weekly"
          + save_days   = 1
        }

      + configuration {
          + parameter_id    = "2"
          + parameter_name  = "maxmemory-policy"
          + parameter_value = "allkeys-lru"
        }
      + configuration {
          + parameter_id    = "11"
          + parameter_name  = "maxclients"
          + parameter_value = "1002"
        }

      + whitelist {
          + group_name = "test-group-name"
          + ip_list    = [
              + "10.10.10.1",
              + "10.10.10.2",
            ]
        }
      + whitelist {
          + group_name = "test-group-name-2"
          + ip_list    = [
              + "10.11.10.1/24",
              + "10.11.10.2/24",
            ]
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

**Comment by EugenFo** [comment]
Hey, @anton-sidelnikov, thanks for your reply.

The `terraform plan` output is actually not the problem. It doesn't matter if I append an comma to the list or not. 
The DCS Instance itself will be created, but `terraform apply` still goes on and you can see in the OTC console that the whitelists are missing.

That's more than a weird thing, because the plan for whitelist
```hcl
      + whitelist {
          + group_name = "test-group-name"
          + ip_list    = [
              + "10.10.10.1",
              + "10.10.10.2",
            ]
        }
      + whitelist {
          + group_name = "test-group-name-2"
          + ip_list    = [
              + "10.11.10.1/24",
              + "10.11.10.2/24",
            ]
        }
```
look exactly like you would define it, but in the end it doesn't work. I assume that there is some issue with the modify function for the whitelist as the DCS Instance was created just fine.

I let `terraform apply` run until the timeout was hit(10 minutes) and I got this error message:
```
╷
│ Error: error waiting for instance (ddef3487-4cfa-4af2-9d00-3e1b5b06f992) to update whitelist: context deadline exceeded
│ 
│   with module.dcs.opentelekomcloud_dcs_instance_v1.this[0],
│   on ../../../terraform-module-dcs/main.tf line 18, in resource "opentelekomcloud_dcs_instance_v1" "this":
│   18: resource "opentelekomcloud_dcs_instance_v1" "this" {
│ 
```
Maybe this will give you more insights into the issue.

**Comment by anton-sidelnikov** [comment]
Hi @EugenFo that strange, because:
![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/53078276/5153f846-00b2-45ba-a7af-1db3b0f15dd8)
![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/53078276/b49624d4-f04d-4a33-b899-90812552ef3b)
My config:
![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/53078276/4fcda6eb-4709-4a0e-b644-7b4aba8a20ab)

**Comment by anton-sidelnikov** [comment]
Probably you have some network configuration which can block some requests

**Comment by EugenFo** [comment]
Okay that is getting weirder :sweat_smile: 
I will check this configuration with my colleagues and I will come back to you again with more informations. 
This looks now that something is broken in my setup.

Thanks again!

**Comment by EugenFo** [comment]
Hey again @anton-sidelnikov,

me and my colleague have tested a few things now and we found the issue. 
The problem is actually not the `dynamic "whitelist"` block.

If `enable_whitelist = true` is set then no whitelists will be created OR modified. However when you define `enable_whitelist = false` then everything works fine. The whistelists will be created even when you have disabled them.
We noticed that, because in your screenshot we saw that you have disabled the whitelist which is little bit odd.

Can you make another test with `enable_whitelist = true`?

**Comment by anton-sidelnikov** [comment]
@EugenFo try to set ips in subnet range, I will create a ticket regarding this, because no error massage in case of wrong ip addresses and masks

**Comment by anton-sidelnikov** [comment]
Ticket about missing error messages: https://jira.tsi-dev.otc-service.com/browse/BM-2127

**Comment by EugenFo** [comment]
Ohh, now I see the issue. The IPs don't need to be in the subnet range they just need to be valid cidr ranges. I honestly just entered some cidr ranges for my module testing without thinking about it. 
When you enter invalid cidr ranges in the OTC console for the whitelist then you will be notified. I haven't double checked if my ranges are also working via OTC console.

Thanks @anton-sidelnikov :+1:
