### ISSUE TITLE
[DMS] Missing resources for user creation and granting permission 

### ISSUE THREAD

**Issue by EugenFo** [opentelekomcloud/terraform-provider-opentelekomcloud#2166]
# Description of the enhancement
In the OTC Console you can create more SASL_SSL Users than just the initial one. Currently there are no Terraform resources to do so with Terraform. API for this can be found [here](https://docs.otc.t-systems.com/distributed-message-service/umn/managing_users/creating_a_sasl_ssl_user.html)

Additionally granting permissions to those users is also missing an Terraform resource. [API for this](https://docs.otc.t-systems.com/distributed-message-service/api-ref/apis_v2_recommended/user_management/granting_user_permissions.html)

Would be cool to have both features. Thanks!

**Comment by artem-lifshits** [comment]
Hello @EugenFo resources are available in latest release.
