### ISSUE TITLE
[autoscaling] alarm rule doesn't work when created with Terraform

### ISSUE THREAD

**Issue by GaborBella** [opentelekomcloud/terraform-provider-opentelekomcloud#2168]
# Terraform provider version
`v1.34.3`

# Affected Resource(s)
- opentelekomcloud_ces_alarmrule

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_ces_alarmrule" "alarm_rule" {
  alarm_name = "alarm_rule"
  alarm_enabled = true
  alarm_level   = 1
  alarm_action_enabled = true
  metric {
    namespace   = "SYS.AS"
    metric_name = "cpu_util"

    dimensions {
      name  = "instance_id"
      value = module.as.as_group_id
    }
  }
  condition {
    period              = 300
    filter              = "min"
    comparison_operator = ">="
    value               = 1
    unit                = "%"
    count               = 1
  }
  alarm_actions {
    type              = "autoscaling"
    notification_list = []
  }
  ok_actions {
    type              = "autoscaling"
    notification_list = []
  }
}

```

# Debug Output/Panic Output

# Steps to Reproduce

1. Create an autoscale config
2. Create an autoscale group
3. Create alarm rule with the config above
4. Stress test the autoscale group
5. See that nothing happens

# Expected Behavior

Because of the alarm rule, the groups should start to scale up

# Actual Behavior
Nothing happens.

# Important Factoids

If I create an alarm rule manually, the scale will start.
There is a variable what we can modify / set up in OTC manually, what the provider doesn't have. (On frontend it called: alarmFrequencyElementId_input)
With this can be set the frequency of the alarm. 

# References

**Comment by artem-lifshits** [comment]
Internal ticket: https://jira.tsi-dev.otc-service.com/browse/OTCORC-3004

**Comment by artem-lifshits** [comment]
Hello @GaborBella!
You have to add `opentelekomcloud_as_policy_v1` resource to bind alarm rule to AS.
Also `name` in `dimensions` sections should be `AutoScalingGroup` for AS, this part is not well documented and we are also waiting for documentation release.

So overall configuration should look like that:
```
resource "opentelekomcloud_ces_alarmrule" "alarm_rule" {
  alarm_name = "alarm_rule"
  alarm_enabled = true
  alarm_level   = 1
  alarm_action_enabled = true
  metric {
    namespace   = "SYS.AS"
    metric_name = "cpu_util"

    dimensions {
      name  = "AutoScalingGroup"
      value = "df864d7f-8e11-45da-a9ef-995d9676f829"
    }
  }
  condition {
    period              = 300
    filter              = "min"
    comparison_operator = ">="
    value               = 1
    unit                = "%"
    count               = 1
  }
  alarm_actions {
    type              = "autoscaling"
    notification_list = []
  }
  ok_actions {
    type              = "autoscaling"
    notification_list = []
  }
}

resource "opentelekomcloud_as_policy_v1" "increase_policy" {
  scaling_group_id    = "df864d7f-8e11-45da-a9ef-995d9676f829"
  scaling_policy_name = "as_increase_policy"
  scaling_policy_type = "ALARM"
  alarm_id            = opentelekomcloud_ces_alarmrule.alarm_rule.id
  scaling_policy_action {
    operation       = "ADD"
    instance_number = 1
  }
  cool_down_time = 60
}
```
