### ISSUE TITLE
opentelekomcloud_identity_protocol_v3 to support OIDC

### ISSUE THREAD

**Issue by canaykin** [opentelekomcloud/terraform-provider-opentelekomcloud#2177]
Greetings team!

We are very fond of using an SSO solution to handle user management and streamline the project accessibility. Until recently we have been using the [opentelekomcloud_identity_provider_v3](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/identity_provider_v3), [opentelekomcloud_identity_protocol_v3](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/identity_protocol_v3) and [opentelekomcloud_identity_mapping_v3](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/identity_mapping_v3) to create a SAML based identity provider solution since this was the only option.  

Recently, OTC added OIDC support for identity providers and after some testing we found it to be more capable and less error prone for our purpose. 

While we were able to create and configure the OIDC identity provider over the UI, the terraform resource appears to lack this capability yet. Considering the absence of the API docs on the topic, I am unsure if the API support is there or not either. Nevertheless, I believe this would be a good feature to include in a future release.

Looking forward to your answer and thank you very much!
Best,
Can.

**Comment by anton-sidelnikov** [comment]
Please check on latest
