### ISSUE TITLE
[CCE] Incorrect implementation or documentation of data `opentelekomcloud_cce_addon_template_v3`

### ISSUE THREAD

**Issue by Nemental** [opentelekomcloud/terraform-provider-opentelekomcloud#2182]
# Terraform provider version

v1.34.4

# Affected Resource(s)

- opentelekomcloud_cce_addon_template_v3

# Terraform Configuration Files
## Example A (actual - working)
```hcl
data "opentelekomcloud_cce_addon_template_v3" "addon-dev-cce-npd_template" {
  # https://docs.otc.t-systems.com/cloud-container-engine/api-ref/apis/add-on_management/reading_add-on_templates.html
  addon_version = "1.17.4" # manually read version from https://cce.eu-de.otc.t-systems.com/api/v3/addontemplates
  addon_name    = "npd"
}

resource "opentelekomcloud_cce_addon_v3" "addon-dev-cce-npd" {
  template_name    = "npd"
  template_version = "1.17.4"
  cluster_id       = opentelekomcloud_cce_cluster_v3.cce-dev.id

  values {
    basic = {
      "image_version" : data.opentelekomcloud_cce_addon_template_v3.addon-dev-cce-npd_template.image_version,
      "swr_addr" : data.opentelekomcloud_cce_addon_template_v3.addon-dev-cce-npd_template.swr_addr,
      "swr_user" : data.opentelekomcloud_cce_addon_template_v3.addon-dev-cce-npd_template.swr_user
    }
    custom = {}
  }
}
```

## Example B (expected - not working)
```hcl
data "opentelekomcloud_cce_addon_template_v3" "addon-dev-cce-npd_template" {
  # https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/data-sources/cce_addon_template_v3#addon_version
  addon_version = "1.25.2" # (Required) The version of the CCE cluster. For example: 1.23.6.
  addon_name    = "npd"
}

resource "opentelekomcloud_cce_addon_v3" "addon-dev-cce-npd" {
  template_name    = "npd"
  template_version = "1.17.4"
  cluster_id       = opentelekomcloud_cce_cluster_v3.cce-dev.id

  values {
    basic = {
      "image_version" : data.opentelekomcloud_cce_addon_template_v3.addon-dev-cce-npd_template.image_version,
      "swr_addr" : data.opentelekomcloud_cce_addon_template_v3.addon-dev-cce-npd_template.swr_addr,
      "swr_user" : data.opentelekomcloud_cce_addon_template_v3.addon-dev-cce-npd_template.swr_user
    }
    custom = {}
  }
}
```

# Debug Output/Panic Output

## Example A
```hcl
data.opentelekomcloud_cce_addon_template_v3.addon-dev-cce-npd_template: Reading...
data.opentelekomcloud_cce_addon_template_v3.addon-dev-cce-npd_template: Read complete after 0s [id=npd]

  # opentelekomcloud_cce_addon_v3.addon-dev-cce-npd will be created
  + resource "opentelekomcloud_cce_addon_v3" "addon-dev-cce-npd" {
      + cluster_id       = "XXXXXXXXXX"
      + description      = (known after apply)
      + id               = (known after apply)
      + name             = (known after apply)
      + template_name    = "npd"
      + template_version = "1.17.4"

      + values {
          + basic = {
              + "image_version" = "1.17.4"
              + "swr_addr"      = "100.125.7.25:20202"
              + "swr_user"      = "cce-addons"
            }
        }
    }
```

## Example B
```hcl
Planning failed. Terraform encountered an error while generating this plan.


│ Error: your query returned no results by provided version. Please change your search criteria and try again
│
│   with data.opentelekomcloud_cce_addon_template_v3.addon-dev-cce-npd_template,
│   on main.tf line 442, in data "opentelekomcloud_cce_addon_template_v3" "addon-dev-cce-npd_template":
│  442: data "opentelekomcloud_cce_addon_template_v3" "addon-dev-cce-npd_template" {
```

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

Value of `addon_version` for data `opentelekomcloud_cce_addon_template_v3` should be CCE cluster version to get a compatible addon `template_version` which is supported for that CCE cluster version.

# Actual Behavior

Value of `addon_version` for data `opentelekomcloud_cce_addon_template_v3` must be a compatible `template_version` for the CCE cluster version. That doesn't make much sense, because, as I understand, the data `opentelekomcloud_cce_addon_template_v3` should be designed to get informations like a CCE-cluster-compatible `template_version`.
> [addon_version](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/data-sources/cce_addon_template_v3#addon_version) - (Required) The version of the CCE cluster. For example: 1.23.6.

# Important Factoids

/

# References

/

**Comment by anton-sidelnikov** [comment]
@Nemental Hi, this is doc bug, in fact you should pass not cluster but addon version. Because data which returns by API is really messy it really hard to distinguish supported cluster version.  I asked backend team to make it better. Also I will think about some workaround.

**Comment by Nemental** [comment]
@anton-sidelnikov That's what I thought. I think you understand why it doesn't really make sense to pass the addon version. That's one of the main attributes I want to get from this data response. Let me know if I can give some user input. Thank you.

**Comment by anton-sidelnikov** [comment]
@Nemental ok, lets try another one ds, tomorrow will be released:
```
data "opentelekomcloud_cce_addon_templates_v3" "templates" {
  cluster_version = "1.25.2"
  addon_name      = "gpu-beta"
}
```
I'm not sure that all cases are covered, api response are rough.

**Comment by ihanwen99** [comment]
Great to see this issue, I also have the similar problem

**Comment by Nemental** [comment]
```hcl
data "opentelekomcloud_cce_addon_templates_v3" "addon-dev-cce-npd_template" {
  cluster_version = replace(coalesce(opentelekomcloud_cce_cluster_v3.cce-dev.cluster_version, "0.00"), "/^v((\\d+)(\\.\\d+){1,2})$/", "$1")
  addon_name      = "npd"
}

resource "opentelekomcloud_cce_addon_v3" "addon-dev-cce-npd" {
  template_name    = "npd"
  template_version = data.opentelekomcloud_cce_addon_templates_v3.addon-dev-cce-npd_template.addons.0.addon_version
  cluster_id       = opentelekomcloud_cce_cluster_v3.cce-dev.id

  values {
    basic = {
      "image_version" : data.opentelekomcloud_cce_addon_templates_v3.addon-dev-cce-npd_template.addons.0.image_version,
      "swr_addr" : data.opentelekomcloud_cce_addon_templates_v3.addon-dev-cce-npd_template.addons.0.swr_addr,
      "swr_user" : data.opentelekomcloud_cce_addon_templates_v3.addon-dev-cce-npd_template.addons.0.swr_user
    }
    custom = {}
  }
}
```
@anton-sidelnikov thanks, I tested v1.35.0 and it work's so far!
But there is one more question... `addons` is a list with an entry for each ECS-node in this CCE? How can I get the relation between the list entry of `addons` and the ECS?

**Comment by anton-sidelnikov** [comment]
Hi @Nemental, here only list of supported addon versions and some additional info for each of them. The list from this API endpoint: https://docs.otc.t-systems.com/cloud-container-engine/api-ref/apis/add-on_management/reading_add-on_templates.html#cce-02-0321, this is static data not related to nodes. Anyway I can add some custom parameter from response, maybe it will helps, please check https://cce.eu-de.otc.t-systems.com/api/v3/addontemplates and tell me what you want to add.

**Comment by Nemental** [comment]
@anton-sidelnikov thanks, I understand 👍 
So the entry `0` of `addons` is always the latest supported version?

**Comment by anton-sidelnikov** [comment]
@Nemental hm, I forgot about sorting, currently latest entry is the latest version

**Comment by Nemental** [comment]
@anton-sidelnikov no problem... Got this workaround for now
```hcl
locals {
  addon-dev-cce-npd_template-last = reverse(data.opentelekomcloud_cce_addon_templates_v3.addon-dev-cce-npd_template.addons)[0]
}
```

**Comment by anton-sidelnikov** [comment]
If you have any suggestions for improvements please open new issue.
