### ISSUE TITLE
[RDS] Failover/Switchover in OTC makes DB to be re-created

### ISSUE THREAD

**Issue by tobiashoefler** [opentelekomcloud/terraform-provider-opentelekomcloud#2191]
availability_zone is a required argument for opentelekomcloud_rds_instance_v3. The first element is chosen to be the primary AZ. If you have a HA setup with multiple AZs defined within this argument, automatic failover in the OTC will produce a difference between the terraform state and the OTC. 
As changes in the availability_zone argument will force the RDS instance to be re-created, this scenario will lead to a re-creation of the DB, losing all data/backups/private IPs......

**Suggestion:**
Move the definition of the primary AZ to a separate optional argument and ignore the order in the current availability_zone argument.

**Comment by anton-sidelnikov** [comment]
Hi @tobiashoefler could you provide your hcl config for rds?

**Comment by tobiashoefler** [comment]
Hi @anton-sidelnikov 
sure:

```
resource "opentelekomcloud_rds_instance_v3" "instance" {
  name              = "......."
  availability_zone = ["eu-de-01", "eu-de-02"]

  security_group_id   = var.security_group_id
  subnet_id           = var.subnet_id
  vpc_id              = var.vpc_id
  flavor              = var.flavor
  ha_replication_mode = var.ha_replication_mode
  param_group_id      = ....

  db {
    password = var.db_password
    type     = var.db_type
    version  = var.db_version
    port     = var.db_port
  }

  volume {
    disk_encryption_id = var.kms_key_id
    type               = "ULTRAHIGH"
    size               = var.volume_size
  }
  
  backup_strategy {
    start_time = "......"
    keep_days  = var.backup_retention_in_days
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

**Comment by anton-sidelnikov** [comment]
@tobiashoefler Hi, check on latest please.
