### ISSUE TITLE
[CCE Autoscale in] Successfully deploy autoscaller but can not scale in

### ISSUE THREAD

**Issue by ihanwen99** [opentelekomcloud/terraform-provider-opentelekomcloud#2193]
# Terraform provider version
1.5.0

# Affected Resource(s)
opentelekomcloud_cce_addon_v3

# Terraform Configuration Files
```tf
resource "opentelekomcloud_cce_addon_v3" "autoscaler" {
  template_name    = "autoscaler"
  template_version = "1.25.7"
  cluster_id       = opentelekomcloud_cce_cluster_v3.cce_cluster.id

  values {
    basic = {
      "cceEndpoint" : "https://cce.eu-nl.otc.t-systems.com",
      "ecsEndpoint" : "https://ecs.eu-nl.otc.t-systems.com",
      "image_version" : "1.25.7",
      "region" : "eu-nl",
      "swr_addr" : "swr.eu-nl.otc.t-systems.com",
      "swr_user" : "hwofficial"
    }
    custom = {
      "cluster_id" : opentelekomcloud_cce_cluster_v3.cce_cluster.id,
      "coresTotal" : 32000,
      "expander" : "priority",
      "logLevel" : 4,
      "maxEmptyBulkDeleteFlag" : 10,
      "maxNodeProvisionTime" : 15,
      "maxNodesTotal" : 1000,
      "memoryTotal" : 128000,
      "scaleDownDelayAfterAdd" : 1,
      "scaleDownDelayAfterDelete" : 1,
      "scaleDownDelayAfterFailure" : 1,
      "scaleDownEnabled" : true,
      "scaleDownUnneededTime" : 1,
      "scaleDownUtilizationThreshold" : 0.5,
      "scaleUpCpuUtilizationThreshold" : 1,
      "scaleUpMemUtilizationThreshold" : 1,
      "scaleUpUnscheduledPodEnabled" : true,
      "scaleUpUtilizationEnabled" : true,
      "tenant_id" : yout_own_tenent_id,
      "unremovableNodeRecheckTimeout" : 1
    }
    
  }
}

```

# Debug Output/Panic Output
Successful in the command line and also the console, but fail in the real environment.
- 

# Steps to Reproduce
1. `terraform apply` 
2. After successfully deploying the CCE and Autoscaller, trigger the workload
3. The node pool could extend automatically.
4. Shutdown the workload, it can not scale in as expected

# Expected Behavior
1. Scale in as expected

# Actual Behavior
1. Nothing happens

# References
[CCE] Autoscaler #2188

**Comment by vladimirvshivkov** [comment]
Could you, please,  describe the issue in detail with screenshots and what exactly happens.
Moreover, need to understand what the workload runs, does it have proper requests/limits?

**Comment by ihanwen99** [comment]
On successfully deployed, the node and node pool, and autoscaler are here. [this part is correct]
<img width="1588" alt="image" src="https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/37998674/569a9bc5-5cee-4d3e-9794-f0a9ef2c6871">
<img width="1596" alt="image" src="https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/37998674/15636824-0862-4b19-964c-3af7c2263da9">
After successfully deploying the workload, it scales out automatically.[this part is correct]
<img width="1552" alt="image" src="https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/37998674/269fa48f-9220-45e2-8728-cdc1d0473490">
<img width="1577" alt="image" src="https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/37998674/7685808f-3ee4-459b-a27c-8d96ebf6ad69">
After deleting the whole workload, it can not scale in as expected. [wrong here]
<img width="1526" alt="image" src="https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/37998674/d06696b1-6d70-4f2c-8154-8c3d43d82eb8">

**Comment by ihanwen99** [comment]
This problem is solved.

The core thing to configure more is in the nood_pool setting. We also should configure the `scale_down_cooldown_time`.
