### ISSUE TITLE
opentelekomcloud_identity_role_assignment_v3 to assign role to All resources [Existing and future projects]

### ISSUE THREAD

**Issue by brunoagueda** [opentelekomcloud/terraform-provider-opentelekomcloud#2196]
# Description of the enhancement
I'm trying to assign a role to a group for All resources [Existing and future projects] using the opentelekomcloud_identity_role_assignment_v3 (version 1.35.1) module, but as per the doc, it's only possible to do so in a domain level or project level.
It would be nice to assign the role in all resources trough terraform, since with the GUI that's possible.
If this feature is already available, the doc needs to be updated.
Thanks in advance

**Comment by artem-lifshits** [comment]
Hello @brunoagueda, we don't have the API to grant permissions to all project at the moment.
If it becomes available we will implement the feature.

**Comment by anton-sidelnikov** [comment]
Available in latest release
