### ISSUE TITLE
Data Ingestion Service (DIS)

### ISSUE THREAD

**Issue by beibeiJ** [opentelekomcloud/terraform-provider-opentelekomcloud#2198]
# Description of the enhancement
Will OTC consider offering terraform guide for Data Ingestion Service (DIS)?

**Comment by anton-sidelnikov** [comment]
@beibeiJ Hi, seems API published, we will start implementation as soon as possible

**Comment by anton-sidelnikov** [comment]
implemented

**Comment by beibeiJ** [comment]
Super! @anton-sidelnikov Thanks for the fast reaction and your effort on the implementation
