### ISSUE TITLE
[ELB] New ipgroup/blacklist feature not available for (shared) ELBv2?

### ISSUE THREAD

**Issue by pwurbs** [opentelekomcloud/terraform-provider-opentelekomcloud#2199]
The non-dedicated ELB offers the possibility to create ipgroups and assign them to listener whitelists and blacklists.
But I only see in the TF provider doc the corresponding v3 resources for [DLB] and not for [ELB].
Do I oversee something, was it simply forgotten ;) or is it planned for the future?

**Comment by anton-sidelnikov** [comment]
Hi @pwurbs, you can use v3 resources to create this features for elbv2

**Comment by pwurbs** [comment]
Ok, thx @anton-sidelnikov 
I will try out. But you should mention it in the doc. Currently, v3 resources are assigned to [DLB] which is the Dedicated Loadbalancer. So we could only guess that these resources are also applicable for the Shared ELB

**Comment by anton-sidelnikov** [comment]
@pwurbs yes, we will update doc. But because this is undocumented feature now, when is was approved we will do it for sure.

**Comment by pwurbs** [comment]
What does "undocumented feature" mean? Can we use it for production?

**Comment by anton-sidelnikov** [comment]
Yes you can, but currently we can't mention that in our tf documentation.

**Comment by pwurbs** [comment]
Can I reference resources from opentelekomcloud_lb_ipgroup_v3 in opentelekomcloud_lb_listener_v2 or do I have to move to opentelekomcloud_lb_listener_v3 and maybe even to opentelekomcloud_lb_loadbalancer_v3?

**Comment by anton-sidelnikov** [comment]
Hello @pwurbs, we didn't test that, but I think loadbalancer v2, didn't support ip_groups, probably you need to change your loadbalancer first.

**Comment by pwurbs** [comment]
Hi @anton-sidelnikov 
I still don't understand the current situation: 
The IP groups feature is available since months, also for the shared loadbalancer (currently supported by the v2 loadbalancer resource in OTC TF provider). So, why don't we get the appropriate addition into the existing ELB v2 resource? 
Based on your latest answer, it's not possible to use the workaround (using v3 resource for shared ELB), because it would mean to move to another resource (v3) which would require cumbersome state manipulation / import. And to be honest I am reluctant to use a TF provider resource (v3) which is not intended for the intended OTC service (shared ELB). BTW, the doc has not been changed yet.
So, please give us some feedback how you intend to make some progress here. Thx.

**Comment by anton-sidelnikov** [comment]
Hi, @pwurbs,
Maybe I've missed something from your question from the beginning, but for v2 we have whitelist API, it differs from ip_group API, but has pretty same functionality, why you didn't use it?

**Comment by pwurbs** [comment]
Hi @anton-sidelnikov I know and use this feature. But this only provides a whitelist. But we have to blacklist some IP addresses. For this, ip_groups can be defined and added to the listener as blacklist or whitelist.

**Comment by anton-sidelnikov** [comment]
@pwurbs Hi, check the latest release

**Comment by pwurbs** [comment]
@anton-sidelnikov Great! Thx. I will try out.
