### ISSUE TITLE
False positive result of opentelekomcloud_identity_role_assignment_v3

### ISSUE THREAD

**Issue by IngIhorMuzychka** [opentelekomcloud/terraform-provider-opentelekomcloud#2202]
# Terraform provider version
Terraform v1.5.1
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.35.1

# Affected Resource(s)
- opentelekomcloud_identity_group_v3
- opentelekomcloud_identity_role_assignment_v3

# Terraform Configuration Files
```hcl
data "opentelekomcloud_identity_project_v3" "customer_project" {
  name = "test_project"
}

resource "opentelekomcloud_identity_group_v3" "group_1" {
  name = "group_1"
}

resource "opentelekomcloud_identity_role_v3" "role_admin" {
  display_name = "Policy-test"
  display_layer = "domain"
   
  statement {
    effect = "Allow"
    action = [
      "obs:bucket:HeadBucket",
      "obs:bucket:List*",
      "obs:bucket:ListBucketMultipartUploads",
      "obs:object:*",
      "obs:bucket:Get*"
    ]
    resource = [
      "obs:*:*:object:rm-state-bucket/test/*",
      "obs:*:*:bucket:rm-state-bucket"
    ]
  }

  statement {
    effect = "Allow"
    action = [
      "obs:object:PutObject"
    ]
    resource = [
      "obs:*:*:object:rm-state-bucket/test"
    ]
  }
}

resource "opentelekomcloud_identity_role_assignment_v3" "admin_role_assignment" {
  group_id = opentelekomcloud_identity_group_v3.group_1.id
  domain_id = data.opentelekomcloud_identity_project_v3.customer_project.domain_id
  role_id = opentelekomcloud_identity_role_v3.role_admin.id
}
```

# Debug Output/Panic Output
**opentelekomcloud_identity_role_assignment_v3.admin_role_assignment: Creation complete after 1s**

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior
User assigned to this group must have access to read and write data in "rm-state-bucket" OBS bucket.

# Actual Behavior
All described resources are created, but when I try to read data from the bucket, I get 403 Access denied.

# Important Factoids
After I created the user I used for the tests, I waited over an hour after assigning him to a group, as advised by OTC.
I manually remove those rights and put them back in the console and after that everything works as I expected.

# References

**Comment by artem-lifshits** [comment]
Hello @IngIhorMuzychka are you using encrypted bucket?

**Comment by IngIhorMuzychka** [comment]
Hello, @artem-lifshits not in this case, but I'm using KMSFullAccess rights in same group anyway, this is not the problem I guess

**Comment by artem-lifshits** [comment]
@IngIhorMuzychka there's a special project on every domain called `MOS` - which is used to grant access to OBS.
So all OBS related permissions should use role assignment for MOS project and related project_id.

Some small changes in your config and it should work fine:
```
data "opentelekomcloud_identity_project_v3" "obs_project" {
  name = "MOS"
}

resource "opentelekomcloud_identity_group_v3" "group_1" {
  name = "group_1"
}

resource "opentelekomcloud_identity_role_v3" "role_admin" {
  display_name = "Policy-test"
  display_layer = "domain"
  description = "-"
   
  statement {
    effect = "Allow"
    action = [
      "obs:bucket:HeadBucket",
      "obs:bucket:ListBucket",
      "obs:bucket:List*",
      "obs:bucket:ListBucketMultipartUploads",
      "obs:object:*",
      "obs:bucket:Get*",
      "obs:object:GetObject",
      "obs:object:GetObjectAcl"
    ]
    resource = [
      "obs:*:*:object:rm-state-bucket/test/*",
      "obs:*:*:bucket:rm-state-bucket"
    ]
  }

  statement {
    effect = "Allow"
    action = [
      "obs:object:PutObject"
    ]
    resource = [
      "obs:*:*:object:rm-state-bucket/test"
    ]
  }
 statement {
            action = [
                "obs:bucket:ListAllMyBuckets"
            ]
            effect = "Allow"
        }
}

resource "opentelekomcloud_identity_role_assignment_v3" "admin_role_assignment" {
  group_id = opentelekomcloud_identity_group_v3.group_1.id
  project_id = data.opentelekomcloud_identity_project_v3.obs_project.id
  role_id = opentelekomcloud_identity_role_v3.role_admin.id
}
```

**Comment by IngIhorMuzychka** [comment]
Thank you @artem-lifshits, assignment through MOS project helped for me

**Comment by pwurbs** [comment]
@artem-lifshits But is this really the official and right way to do it? Normally we assign a OBS role/policy to a user group as Global. This is the officially documented way which should work.
Using an hidden project like MOS might be a workaround but it sounds brittle. 
BTW, I am facing the same issue like the OP. The role is only applied after removing and adding the JSON manually in the UI.

Yes, the MOS workaround works, but the MOS assigned role is only visible in the old edition of the UI.

**Comment by pwurbs** [comment]
As a reasonable workaround I added 
`all_projects = true`
to the opentelekomcloud_identity_role_assignment_v3 resource.
This also covers the magic MOS project and is visible in the old and new UI edition

But the issue must be fixed anyway
