### ISSUE TITLE
[CCE] Do not save administrator kubeconfig in statefile

### ISSUE THREAD

**Issue by bbung** [opentelekomcloud/terraform-provider-opentelekomcloud#2208]
# Description of the enhancement

Currently the opentelekomcloud_cce_cluster_v3 stores the initial "all access" kubeconfig parametes (user) in the terraform state. In my opinion this is a security issue. I have no option to omit storing the "all mighty" kubecon in my terraform state.

Feature Request:
Introduce a option to omit at least the user data from the terraform state. 

Thanks and regards

**Comment by anton-sidelnikov** [comment]
Hi @bbung please check on latest

**Comment by bbung** [comment]
Works as expected. Thanks!
