### ISSUE TITLE
opentelekomcloud_obs_bucket - support Parallel File System creation

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#2209]
opentelekomcloud_obs_bucket
seems it is currently not possible to create Parallel File System OBS Buckets. According to:
https://docs.otc.t-systems.com/object-storage-service/parallel-file-system/managing_parallel_file_systems_by_apis/supported_apis.html#obs-13-0004
there is a supported API.

**Comment by artem-lifshits** [comment]
@CHS-OTC feature available in latest release, please check.
