### ISSUE TITLE
Terraform module for Direct Connect

### ISSUE THREAD

**Issue by brunoagueda** [opentelekomcloud/terraform-provider-opentelekomcloud#2215]
# Description of the enhancement
I'm using the Direct Connect APIs (https://docs.sc.otc.t-systems.com/api/dc/en-dc_topic_0055025300.html) but our main goal is to setup our tenants' configurations entirely in Terraform.
Since there is already APIs to manage Connection, Virtual Gateway, Virtual Interface, etc would it be possible to make available terraform modules for that as well?

**Comment by anton-sidelnikov** [comment]
@brunoagueda, Direct Connect resource available from 1.35.7, please check

**Comment by vladimirvshivkov** [comment]
@anton-sidelnikov qué pasa? its not done yet

**Comment by brunoagueda** [comment]
@vladimirvshivkov and @anton-sidelnikov I will wait for the next update. Thanks

**Comment by brunoagueda** [comment]
Hello guys
@vladimirvshivkov  and @anton-sidelnikov do you have an update on this topic?

**Comment by vladimirvshivkov** [comment]
> Hello guys @vladimirvshivkov and @anton-sidelnikov do you have an update on this topic?
@brunoagueda 
task is still in progress.
linked PRs above

**Comment by vladimirvshivkov** [comment]
@brunoagueda Direct connect resources are now available in the latest release

**Comment by brunoagueda** [comment]
Thanks! Gonna test it in the next few weeks.
If you like, you can close this issue. If necessary I can re-open or open a new one in case something doesn't work for me or if I have any questions.
