### ISSUE TITLE
OBS not working behind proxy

### ISSUE THREAD

**Issue by Richie1710** [opentelekomcloud/terraform-provider-opentelekomcloud#2220]
# Terraform provider version
 v1.35.2

# Affected Resource(s)
- opentelekomcloud_obs_*

# Debug Output/Panic Output
2023-07-11T12:10:01.279+0200 [ERROR] vertex "module.ObjectStorageService.opentelekomcloud_obs_bucket.my_bucket" error: Put "https://my-bucket.obs.eu-de.otc.t-systems.com:443": dial tcp 80.158.25.140:443: i/o timeout
╷
│ Error: Put "https://my-bucket.obs.eu-de.otc.t-systems.com:443": dial tcp 80.158.25.140:443: i/o timeout
│
│   with module.ObjectStorageService.opentelekomcloud_obs_bucket.my_bucket,
│   on ObjectStorageService/object_storage_service.tf line 35, in resource "opentelekomcloud_obs_bucket" "my_bucket":
│   35: resource "opentelekomcloud_obs_bucket" "my_bucket" {
│

# Steps to Reproduce
set proxy 

HTTPS_PROXY=my_proxy:8080
HTTP_PROXY=my_proxy:8080

place yourself behind a firewall 

1. `terraform apply`

# Expected Behavior
Bucket should be created

# Actual Behavior
Timeout and proxy is ignored

# Important Factoids
Can see requests to OBS directly (and not to proxy) if I'm doing tcpdump 

```
tcpdump -i eth0 -s 0 -nn "port 443"
dropped privs to tcpdump
tcpdump: verbose output suppressed, use -v[v]... for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), snapshot length 262144 bytes

11:50:18.701221 IP 172.30.130.199.37446 > 80.158.25.140.443: Flags [S], seq 3781491737, win 64770, options [mss 1270,sackOK,TS val 264310616 ecr 0,nop,wscale 7], length 0
11:50:19.759311 IP 172.30.130.199.37446 > 80.158.25.140.443: Flags [S], seq 3781491737, win 64770, options [mss 1270,sackOK,TS val 264311674 ecr 0,nop,wscale 7], length 0
```

**Comment by anton-sidelnikov** [comment]
Hi @Richie1710 here is two issue, one on our side which I will fix soon, and second on backend side. When you are using proxy with our OBS api (not huawei api with s3cmd) you will get this: 
`"obs: service returned error: Status=400 Bad Request, Code=InvalidArgument, Message=Unsupported Authorization Type, RequestId=051900000189459E7795637364D004C5"`

So please create customer request for whitelisting your proxy for OBS api (https://obs.otc.t-systems.com/)

**Comment by Richie1710** [comment]
Hi @anton-sidelnikov  as we are both using same proxy settings and I can work with same settings with s3cmd or ansible module but not with provider I guess the issue is not about whitelisting.

**Comment by anton-sidelnikov** [comment]
Hi @Richie1710, proxy support added in latest release, please check

**Comment by Richie1710** [comment]
will test tomorrow

**Comment by Richie1710** [comment]
Not working now I'm getting 

error creating OBS client: parse "10.140.11.40:8080": invalid URI for request
when setting 
HTTPS_PROXY=10.140.11.40:8080
but 
HTTPS_PROXY=http://10.140.11.40:8080

is working. 
I think it should be also working without an http:// or https:// infront

**Comment by anton-sidelnikov** [comment]
Currently this proxy setting only accepts full url, for first approach it is not possible to change that in our sdk. But if you will face some problems with that, please reopen this ticket.
