### ISSUE TITLE
[RDS] Support Storage Autoscaling

### ISSUE THREAD

**Issue by jrod-97** [opentelekomcloud/terraform-provider-opentelekomcloud#2222]
# Description of the enhancement
In line with this announcement: https://open-telekom-cloud.com/en/support/release-notes/rds-supports-storage-autoscaling-in-all-mysql-versions
I would like to be able to create RDS instances with storage autoscaling enabled.

**Comment by artem-lifshits** [comment]
@jrod-97 feature is available on PROD through web-ui but API haven't been implemented yet.
After API implementation I will update the resource.

**Comment by valkaitibor** [comment]
Hello @artem-lifshits,
Could you please help if the RDS autoscaling works, or if not, when it will work?
Thank you so much and have a nice day! :)
Tibi

**Comment by artem-lifshits** [comment]
Hello @valkaitibor sadly autoscaling API is still not implemented so we can't implement the feature.

**Comment by svenreppin** [comment]
hi @artem-lifshits, it seems there is an updated/new RDS autoscaling API. could you please have a look on it! thank you!

**Comment by artem-lifshits** [comment]
@jrod-97 @valkaitibor @brieseme feature implemented in latest release.

**Comment by valkaitibor** [comment]
Hello @artem-lifshits,
Could you please help me a little bit:
- https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/rds_instance_v3 <-- in this page, i can see these 2 parameters: limit_size and trigger_threshold, these are optional. The question is: if these 2 are set, then the autoscaling is active? If these are not set, then autoscaling is inactive?
- will this autoscaling feature be available in case of Postrgre databases, not only for MySQL?
Thank you in advance :)

**Comment by artem-lifshits** [comment]
@valkaitibor `volume` block now has 2 additional fields to enable auto-scaling: `limit_size` and `trigger_threshold`. Both are required if you want to set autoscaling for MySQL.

Roadmap page shows that autoscaling for PostgreSQL will be available around Q3 2024:
https://www.open-telekom-cloud.com/en/products-services/roadmap
