### ISSUE TITLE
opentelekomcloud_identity_projects_v3 returning null

### ISSUE THREAD

**Issue by brunoagueda** [opentelekomcloud/terraform-provider-opentelekomcloud#2223]
# Terraform provider version

Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.35.2

# Affected Resource(s)

- opentelekomcloud_identity_projects_v3

# Terraform Configuration Files
```hcl
data "opentelekomcloud_identity_projects_v3" "list" {
}

output "projects" {
  value = data.opentelekomcloud_identity_projects_v3.list
}
```

# Debug Output/Panic Output

https://gist.github.com/brunoagueda/5d05cc49fd5c0b80bdb43dedc711918b

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

Return the output with the list of projects available

# Actual Behavior

The output is null

# Important Factoids

I'm using Swiss OTC. When I use the API (GET https://iam-pub.eu-ch2.sc.otc.t-systems.com/v3/auth/projects) trough Postman it works, but in terraform it does not bring any results

# References

**Comment by artem-lifshits** [comment]
Hello @brunoagueda I wasn't able to reproduce the issue.
What type of authentication are you using?

**Comment by brunoagueda** [comment]
I'm authenticating with terraform provider using AK and SK from a admin user

provider "opentelekomcloud" {
  auth_url    = var.url_iam
  access_key  = var.access_key
  secret_key  = var.secret_key
  domain_name = var.domain_name
  tenant_name = var.tenant_name
}

For all other resources and queries it works. In the tenant_name variable I'm using the top level project name "eu-ch2"

**Comment by artem-lifshits** [comment]
Looks like issue happens with AK/SK auth only. 
Investigating.

**Comment by artem-lifshits** [comment]
@brunoagueda fix will be available tomorrow.

**Comment by artem-lifshits** [comment]
@brunoagueda issue is fixed in latest release.

**Comment by brunoagueda** [comment]
Just tested the new release and it works as expected. Thanks a lot!
