### ISSUE TITLE
opentelekomcloud_networking_port_v2 - not possible to create port without security group

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#2227]
# Terraform provider version
provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.35.2

# Affected Resource(s)
opentelekomcloud_networking_port_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_networking_port_v2" "port_1" {
  name           = "port_1"
  network_id     = var.network_id
  no_security_groups = true
  port_security_enabled = false
  security_group_ids = []
}
```

# Debug Output/Panic Output
│ Error: error updating OpenTelekomCloud Neutron port: Bad request with: [PUT https://vpc.eu-nl.otc.t-systems.com/v2.0/ports/6a6c1221-c475-4d5b-bf88-0613c22e4af1], error message: {"NeutronError":{"message":"Port cannot be updated without securitygroup.","type":"InvalidInput","detail":""}}

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior
Creating a port without Security Group and disabled port security. 

# Actual Behavior
error message, no port is created

# Important Factoids
there is a workaround possible: 
```hcl
resource "opentelekomcloud_networking_port_v2" "port_1" {
  name           = "port_1"
  network_id     = var.network_id
#  no_security_groups = true
  port_security_enabled = false
  security_group_ids = []
}
```
without the "no_security_groups = true" parameter it is possible to create a port with default security group: 

openstack port show 6a6c1221-c475-4d5b-bf88-0613c22e4af1 --os-cloud=otc_eunl | grep sec
| port_security_enabled   | True                                                                                                                                                                                 |
| security_group_ids      | eaffbe2c-6771-4bfc-92d7-3c04f39d4c8f

applying the same TF-code with "terraform apply" again: 
```hcl
Terraform will perform the following actions:

  # opentelekomcloud_networking_port_v2.port_1 will be updated in-place
  ~ resource "opentelekomcloud_networking_port_v2" "port_1" {
        id                    = "6a6c1221-c475-4d5b-bf88-0613c22e4af1"
        name                  = "port_1"
      ~ port_security_enabled = true -> false
      ~ security_group_ids    = [
          - "eaffbe2c-6771-4bfc-92d7-3c04f39d4c8f",
        ]
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
openstack port show 6a6c1221-c475-4d5b-bf88-0613c22e4af1 --os-cloud=otc_eunl | grep sec
| port_security_enabled   | False                                                                                                                                                                                |
| security_group_ids      |    

I also tested it directly using RestAPI: 
```json
POST https://vpc.eu-nl.otc.t-systems.com/v2.0/ports

{
    "port": {
       "admin_state_up": true,
        "network_id": "$Network_ID",
        "name": "port-test",
        "port_security_enabled": false
    }
}
```
works fine and creates a port without security group directly.

tested it in eu-nl and eu-de

# References
https://docs.otc.t-systems.com/virtual-private-cloud/api-ref/native_openstack_neutron_apis_v2.0/port/creating_a_port.html

**Comment by anton-sidelnikov** [comment]
fixed in latest release

**Comment by CHS-OTC** [comment]
@anton-sidelnikov seems that now the default value for [port_security_enabled](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/networking_port_v2#port_security_enabled) is set to "false" I guess this should be "true" instead.
