### ISSUE TITLE
[RDS] Import of instance forces recreation

### ISSUE THREAD

**Issue by marcel-wollschlaeger** [opentelekomcloud/terraform-provider-opentelekomcloud#2229]
# Terraform provider version
```
terraform -v
Terraform v1.5.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/tls v3.3.0
+ provider registry.terraform.io/integrations/github v5.30.1
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.35.3
```

# Affected Resource(s)
- opentelekomcloud_rds_instance_v3

# Terraform Configuration Files

I am using this database configuration as a module: https://github.com/digitalservicebund/terraform-modules/tree/0b219afc673a491f44fcc6874bd64cc7cd93216c/otc-rds-database

```hcl
module "database" {
  source         = "github.com/digitalservicebund/terraform-modules//otc-rds-database?ref=0888e07881833cb2292610416e786cf44465656f"
  resource_group = "foobar"

  subnet_id          = "some-subnet-id"
  vpc_id             = "some-vpc-id"
  availability_zones = ["eu-de-01"]

  flavor         = "rds.pg.c2.large"
  engine_version = "12"
  port           = "5432"

  disk_size        = 160
  backup_keep_days = 1

  db_access_from_security_group_ids = ["some-access-id"]
}

---

import {
  to = module.database.opentelekomcloud_rds_instance_v3.this
  id = "an-existing-id"
}

```

# Debug Output/Panic Output

# Steps to Reproduce
1. Fetch ID from OTC web console of Database instance or from an existing remote state
2. Prepare import.tf file with correct ID and corresponding resources defined in the module
3. Run `terraform apply`

# Expected Behavior
The database instance can be imported into the new state.

# Actual Behavior
A new database must be created as the nodes couldn't be copied over to the existing availability zone.

```
  # module.database.opentelekomcloud_rds_instance_v3.this must be replaced
  # (imported from "an-existing-id")
  # Warning: this will destroy the imported resource
-/+ resource "opentelekomcloud_rds_instance_v3" "this" {
      + availability_zone   = [ # forces replacement
          + "eu-de-01",
        ]
      ~ availability_zones  = [
          - "eu-de-01",
        ] -> (known after apply)
      ~ created             = "2023-06-13T07:01:55+0000" -> (known after apply)
        flavor              = "rds.pg.c2.large"
      + ha_replication_mode = (known after apply)
      ~ id                  = "an-existing-ud" -> (known after apply)
        name                = "some-database-name"
      ~ nodes               = [
          - {
              - availability_zone = "eu-de-01"
              - id                = "node-id"
              - name              = "foo_node0"
              - role              = "master"
              - status            = "ACTIVE"
            },
        ] -> (known after apply)
      ~ private_ips         = [
          - "old.ip.address",
        ] -> (known after apply)
        security_group_id   = "some-security-group-ud"
        subnet_id           = "some-subnet-id"
      + tags                = {
          + "resource_group" = "foobar"
        }
        vpc_id              = "some-vpc-id"

        backup_strategy {
            keep_days  = 1
            start_time = "03:00-04:00"
        }

      ~ db {
          + password  = (sensitive value)
            port      = 5432
            type      = "PostgreSQL"
          ~ user_name = "root" -> (known after apply)
            version   = "12"
        }

      - timeouts {}

        volume {
            disk_encryption_id = "some-id"
            size               = 160
            type               = "COMMON"
        }
    }
```

# Important Factoids
This regression started to show up with version 1.35.2 and later.

When using the provider version 1.35.1, the database will be imported without being recreated.

# References
- https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/1026

**Comment by anton-sidelnikov** [comment]
Hi @marcel-wollschlaeger I think you must review this module, because from https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/2194 there some changes in storing of azs for rds. The value of availability_zones = ["eu-de-01"] can be different from availability_zone initial value.

For example add availability_zone in ignore_changes block

**Comment by marcel-wollschlaeger** [comment]
@anton-sidelnikov Thanks for the hint, adding the section to the block solves that issue.

```
  ...

  lifecycle {
    ignore_changes = [
      db,
      availability_zone
    ]
  }
```

Do you think it might be worth then to add a [section to the notes](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/rds_instance_v3#notes) then?

**Comment by anton-sidelnikov** [comment]
@marcel-wollschlaeger yes I will add this info.
