### ISSUE TITLE
D-WAF is not supported

### ISSUE THREAD

**Issue by uli-max** [opentelekomcloud/terraform-provider-opentelekomcloud#2231]
# Description of the enhancement

terraform provider Support for Dedicated WAF is missing.
Dedicated WAF is now general available since around a month. 

User Guide and API Description is available here:
https://docs.otc.t-systems.com/web-application-firewall-dedicated/index.html

Release-Note: 
https://open-telekom-cloud.com/en/support/release-notes/general-availability-dedicated-waf

Please provide terraform support for this product.

**Comment by anton-sidelnikov** [comment]
Hi @uli-max as I said before we still in discussion regarding dedicated waf, we still have issues that blocks implementation of this service.

**Comment by anton-sidelnikov** [comment]
#2241 now available

**Comment by uli-max** [comment]
Thanks, for the first progress for Ded. WAF.

**Comment by anton-sidelnikov** [comment]
Finished
