### ISSUE TITLE
Path to import lb_v2 to lb_v3

### ISSUE THREAD

**Issue by Xaving** [opentelekomcloud/terraform-provider-opentelekomcloud#2244]
Hello, 

Is there a path to import ELB([lb_loadbalancer_v2](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_loadbalancer_v2)) into DLB Dedicated Load Balancer ([lb_loadbalancer_v3](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_loadbalancer_v3))? Or are they totally different resources?

The import command seems to work:
```
import opentelekomcloud_lb_loadbalancer_v3.my_loadbalancer   id_of_lb_v2
``` 

But then in the terraform plan , the required attributs of lb_v3 seems to cause a force replacement of the resource:
```
# opentelekomcloud_lb_loadbalancer_v3.egress must be replaced
-/+ resource "opentelekomcloud_lb_loadbalancer_v3" "my_loadbalancer" {
      ~ availability_zones = [ # forces replacement
          + "eu-de-01",
          + "eu-de-03",
        ]
      ~ created_at         = "[202](https://git......." -> (known after apply)
      ~ id                 = "....sd345w...." -> (known after apply)
      ~ ip_target_enable   = false -> (known after apply)
      + l4_flavor          = (known after apply)
      + l7_flavor          = (known after apply)
        name               = "thebridge-egress"
      ~ network_ids        = [
          + "...........b5.....",
        ]
      - subnet_id          = "....." -> null
      - tags               = {} -> null
      ~ updated_at         = "2020-0......" -> (known after apply)
      ~ vip_port_id        = "......6fe...." -> (known after apply)
        # (3 unchanged attributes hidden)
    }

```
The lb_v2 object was created with terraform version 0.12.26 with OTC provider version v1.22.7.
The new terraform state uses terraform version 1.5.0 with OTC provider version v1.28.2.

**Comment by anton-sidelnikov** [comment]
Hey @Xaving, yes you can import but for some attributer please use ignore_changes block:
```
  lifecycle {
    ignore_changes = [
      availability_zones
    ]
  }
```

**Comment by Xaving** [comment]
Thank you, it works.
