### ISSUE TITLE
Import opentelekomcloud_lb_whitelist_v2

### ISSUE THREAD

**Issue by Xaving** [opentelekomcloud/terraform-provider-opentelekomcloud#2245]
Hello,

Is there a way  to import whitelist ([opentelekomcloud_lb_whitelist_v2](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/1.28.2/docs/resources/lb_whitelist_v2))? 

The import command
```
import opentelekomcloud_lb_whitelist_v2.mywhitelist   id_of_whitelist
```
results in the following error:
```
╷
│ Error: resource opentelekomcloud_lb_whitelist_v2 doesn't support import
│ 
```
The whitelist object was created with terraform version 0.12.26 with OTC provider version v1.22.7.
The new terraform state uses terraform version 1.5.0 with OTC provider version v1.28.2.

**Comment by Xaving** [comment]
I can also recreate the whitelist if it can't be imported.
I try to disable the whitelist through the console interface, or to set them to blank, in order to recreate it. But the object still exists, and recreation by terraform  is not permitted.

**Comment by anton-sidelnikov** [comment]
Hi @Xaving, we will add import function for whitelists soon.

**Comment by artem-lifshits** [comment]
Hello @Xaving import implemented in latest release, please check.
