### ISSUE TITLE
DCS - Support SSL encryption

### ISSUE THREAD

**Issue by uli-max** [opentelekomcloud/terraform-provider-opentelekomcloud#2253]
# Description of the enhancement
DCS with Redis 6.0 support SSL 
https://docs.otc.t-systems.com/distributed-cache-service/umn/managing_dcs_instances/configuring_ssl.html

It is also available in API description:
https://docs.otc.t-systems.com/distributed-cache-service/api-ref/lifecycle_management_apis/creating_a_dcs_instance.html#

PLease activate in one of the next versions.

**Comment by artem-lifshits** [comment]
Hello @uli-max `enable_ssl` parameter doesn't enable SSL for DCS 6.0.
Looks like SSL part of API wasn't updated.

**Comment by artem-lifshits** [comment]
Draft pull request is ready to be merged when issue is fixed.

**Comment by anton-sidelnikov** [comment]
Bug report: https://jira.tsi-dev.otc-service.com/browse/BM-3040

**Comment by siebertm** [comment]
@anton-sidelnikov is there any update on the matter?

**Comment by artem-lifshits** [comment]
No updates so far.
@uli-schneider could you kindly help us push this issue?
Ongoing discussion here: https://jira.tsi-dev.otc-service.com/browse/OTCPAAS-192

**Comment by siebertm** [comment]
I can also ask my sales rep for additional "push" if that helps (and you want me doing that!)

**Comment by uli-schneider** [comment]
Hi Artem, Hi Anton,

Attached my Mail from Mid of. Feb. with all information that I can give you in my role.

@Christian: Can you share the actual Outcome / PIP-Ticket for the DCS “new API” topic?
Problems? And the expected timeline?

From my point of view: (of course, customer driven …)

We have a API Description (but not public published), but in our Systems (gitea).

Thanks & Best

Uli

---

Join our Next Community Event, Friday, April 5th,  at 10:00 am CET: Introduction into API Management using OTC API-Gateway<https://community.open-telekom-cloud.com/community?id=community_event&sys_id=bcf94cdbb7344a50d15aa7b16b8c0233>

Save your Seat at our next k8s/CCE Hackathon, Friday, April 12th, at 10:00 am CEST: k8s/CCE Hackathon - GitOps with Terraform, Helm and ArgoCD on Open Telekom Cloud<https://community.open-telekom-cloud.com/community?id=community_event&sys_id=f70dc56213980a14d15a246ea67441fe>

---

Open Telekom Cloud
Customer Success Manager
Ulrich Schneider
T-Systems International GmbH
Fasanenweg 5, 70771 Leinfelden-Echterdingen

E-Mail: ***@***.******@***.***>
LinkedIn: https://www.linkedin.com/in/ulrich-schneider
Mobile +49 170 8632962

***@***.***
Website <https://www.open-telekom-cloud.com/en> | Community<https://community.open-telekom-cloud.com/community/?id=community_home> | LinkedIn<https://www.linkedin.com/products/t-systems-open-telekom-cloud/> | Compulsory Statement<https://www.t-systems.com/de/en/compulsory-statement>


Von: Artem Lifshits ***@***.***>
Antworten an: opentelekomcloud/terraform-provider-opentelekomcloud ***@***.***>
Datum: Donnerstag, 14. März 2024 um 14:21
An: opentelekomcloud/terraform-provider-opentelekomcloud ***@***.***>
Cc: Ulrich Max Schneider ***@***.***>, Mention ***@***.***>
Betreff: Re: [opentelekomcloud/terraform-provider-opentelekomcloud] DCS - Support SSL encryption (Issue #2253)


No updates so far.
@uli-schneider<https://github.com/uli-schneider> could you kindly help us push this issue?
Ongoing discussion here: https://jira.tsi-dev.otc-service.com/browse/OTCPAAS-192

**Comment by artem-lifshits** [comment]
So I guess this issue is not going to be fixed for v1.0 API and new resource should be introduced when API v2 is released.

**Comment by siebertm** [comment]
Thanks a lot for your clarification and all the prompt replies!

**Comment by uli-schneider** [comment]
APi v2 seems available incl.Documentation 

https://docs.otc.t-systems.com/distributed-cache-service/api-ref/apis_v2_recommended/index.html
https://docs.otc.t-systems.com/distributed-cache-service/api-ref/apis_v2_recommended/network_security/enabling_or_disabling_ssl.html

**Comment by artem-lifshits** [comment]
New DCSv2 instance resource available in latest release.

**Comment by uli-schneider** [comment]
DataSource for "v2" for downloading SSL-Certificate is missing.  

Please also correct tf-doku. 
![grafik](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/156002757/ee2a6c3b-b20e-47b1-8399-b268b3db74c7)

**Comment by artem-lifshits** [comment]
Data source implemented.
