### ISSUE TITLE
RDSv3: Error "missing input for argument [KeepDays]" when keep_days is 0

### ISSUE THREAD

**Issue by kaibernhard** [opentelekomcloud/terraform-provider-opentelekomcloud#2262]
# Terraform provider version

1.35.5

# Affected Resource(s)

- opentelekomcloud_rds_instance_v3

# Terraform Configuration Files
The issue can be reproduced with the example [Create a single db instance](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/rds_instance_v3#create-a-single-db-instance).

# Steps to Reproduce

* prepare cluster, provide vars for example (`availability_zone`, `subnet_id`, `vpc_id`)
* change `keep_days = 1` to `keep_days = 0`
* run `terraform apply` and note that the error only occurs after confirming `yes`, not before, and not when running `terraform plan`.

# Expected Behavior

`terraform apply` succeeds without errors, since the [documentation for keep_days](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/rds_instance_v3#keep_days) claims the value range is from 0 to 732 and `terraform plan` succeeds.

# Actual Behavior

`terraform apply` fails:
```
opentelekomcloud_rds_instance_v3.instance: Still creating... [5m0s elapsed]
╷
│ Error: error updating OpenTelekomCloud RDSv3 Backup Strategy: error building request body: missing input for argument [KeepDays]
│ 
│   with opentelekomcloud_rds_instance_v3.instance,
│   on main.tf line 31, in resource "opentelekomcloud_rds_instance_v3" "instance":
│   31: resource "opentelekomcloud_rds_instance_v3" "instance" {
│ 
╵
```

**Comment by artem-lifshits** [comment]
Hello @kaibernhard please check latest.

**Comment by kaibernhard** [comment]
Hello @artem-lifshits, thank you very much for your help. I don't see the error message any longer with 1.35.6, but it doesn't seem to apply the change to `0`. So, if the setting was at a non-zero value, and I want to change it to `0`, there is no error message and `terraform apply` completes, but when I run `terraform apply` again, it detects the non-zero value and wants to change to `0` again, and again, and again. When checking in OTC console, the backup policy still shows `Automated Backup` enabled - I would expect that to be disabled with `keep_days = 0`.

**Comment by artem-lifshits** [comment]
@kaibernhard please check the latest release.

**Comment by kaibernhard** [comment]
Fix confirmed, thank you @artem-lifshits!
