### ISSUE TITLE
IMS: Data source opentelekomcloud_images_image_v2 name_regex result is missing

### ISSUE THREAD

**Issue by sgyuris** [opentelekomcloud/terraform-provider-opentelekomcloud#2264]
# Terraform provider version

Terraform v1.3.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.4
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.35.5
+ provider registry.terraform.io/rhythmictech/errorcheck v3.0.0
+ provider registry.terraform.io/vancluever/acme v2.7.0

# Affected Resource(s)

- opentelekomcloud_images_image_v2

# Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
data "opentelekomcloud_images_image_v2" "image" {
  name        = var.image_name
  most_recent = true
  visibility  = "private"
  provider    = opentelekomcloud.root_admin
}

# Debug Output/Panic Output

Error: your query returned no results. Please change your search criteria and try again
│ 
│   with module.provisioning.module.....data.opentelekomcloud_images_image_v2.image,
│   on ../../provisioning/modules/.../images.tf line 1, in data "opentelekomcloud_images_image_v2" "image":
│    1: data "opentelekomcloud_images_image_v2" "image" {

# Steps to Reproduce

1. Create an image on OTC in your main project.
2. Put the name into `var.image_name`.
3. `terraform plan` for the sub-project
4. It works. You can see the result.
5. Share the image with the sub-project
6. `terraform plan` for the sub-project
7. Terraform doesn't find the very same image as before. Nothing else is changed expect you just shared the image with the sub-project (the image is not even accepted by the sub-project - even accepting the image doesn't help).

# Expected Behavior

Terraform should find the image.

# Actual Behavior

Terraform doesn't find the image if image is shared with a sub-project.

# Important Factoids

# References

**Comment by sgyuris** [comment]
The last working otc provider version is: 1.35.**_2_**

**Comment by artem-lifshits** [comment]
Hello @sgyuris the issue must be related to `visibility` set to `private`.
Please try changing it to `shared` or removing at all.

**Comment by sgyuris** [comment]
It worked. Thank you.
