### ISSUE TITLE
Make routers configurable as list for DNS Zone 

### ISSUE THREAD

**Issue by Richie1710** [opentelekomcloud/terraform-provider-opentelekomcloud#2266]
Based on documentation I can only add one router to the DNS zone 

https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/dns_zone_v2

as you can see in attached screenshot its possible to add multiple VPCs/routers to one Service Zone

<img width="768" alt="image" src="https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/7263154/47fed3e8-02cd-4787-bdaf-1ea5b69ffe8f">

**Comment by anton-sidelnikov** [comment]
Hi @Richie1710,
I will update example block: 

```
resource "opentelekomcloud_dns_zone_v2" "zone_1" {
  name        = "test"
  email       = "email1@example.com"
  description = "a private zone"
  ttl         = 3000
  type        = "private"

  router {
    router_id     = "first"
    router_region = "eu-de"
  }

  router {
    router_id     = "second"
    router_region = "eu-de"
  }
}
```
