### ISSUE TITLE
[DMS for Kafka] Manage parameters via Terraform

### ISSUE THREAD

**Issue by tobiashoefler** [opentelekomcloud/terraform-provider-opentelekomcloud#2270]
# Description of the enhancement
We use DMS for Kafka and must modify the parameters to enable larger message sizes.
Since we manage the whole infrastructure via Terraform, we also want to manage the parameters likewise.
For RDS, this is already possible.

**Comment by artem-lifshits** [comment]
Hello @tobiashoefler we lack the api to manage DMS parameters at the moment.
Enhancement can be implemented when apis are released:
https://docs.otc.t-systems.com/distributed-message-service/api-ref/apis_v2_recommended/index.html

**Comment by artem-lifshits** [comment]
Please contact customer support team with a demand to implement API for DMS parameters management.
We can only implement resources when corresponding APIs are available.
