### ISSUE TITLE
TMS: Support via terraform 

### ISSUE THREAD

**Issue by uli-max** [opentelekomcloud/terraform-provider-opentelekomcloud#2271]
# Description of the enhancement
OTC offers a central place for Tag Management incl. API.

OTC offers also therefore an API: 
https://docs.otc.t-systems.com/tag-management-service/api-ref/api_description/predefined_tag_operations/creating_or_deleting_predefined_tags.html#en-us-topic-0056765935

Would be nice, to have the possibility to create and reuse predefined Tags from this service over terraform. 

Tagging with variables is working fine, so this consider maybe as a low prio topic.

**Comment by anton-sidelnikov** [comment]
Hi @uli-max what the reason to have this service in terraform? I don't really understand how to use it, how this tags should be assigned to resource?

**Comment by uli-max** [comment]
Hi @anton-sidelnikov, this enables customers to predefine a list of tags, which can be used by other users. 
It helps for customers who has users which are also working in UI, to select the predefined tags. 
I agree the further usage in terraform is not so senseful.

**Comment by anton-sidelnikov** [comment]
Hi, @uli-max this resource available in 1.35.7
