### ISSUE TITLE
EIP - Offers a "real" name 

### ISSUE THREAD

**Issue by uli-max** [opentelekomcloud/terraform-provider-opentelekomcloud#2272]
# Description of the enhancement

Network Service offers meanwhile to set a real name for the ressource of an EIP. 

![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/104261288/f2014d45-4e59-4dfc-abac-4ce2dbd9ea6d)

This should be support also in terraform, to use "name" when creating  an EIP, but also to use the name instead of an ID in addditional terrafrom code.

**Comment by artem-lifshits** [comment]
Hello @uli-max I wasn't able to find the API which supports this feature, are you sure it's available?
Here's the API we rely on at the moment and `publicip` field doesn't have `name` support:
https://docs.otc.t-systems.com/elastic-ip/api-ref/apis/eip/assigning_an_eip.html
<img width="883" alt="Screenshot 2023-08-23 at 09 58 45" src="https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/55093318/3d169aff-4b19-460b-b001-cdf82564af4f">

**Comment by uli-max** [comment]
It is possilbe in UI.
![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/104261288/1c98a6e4-99d5-4ae8-acef-797becb05006)


Maybe the parameter "policy" is not described in our API Description.
Table 3 - publicip field:
https://support.huaweicloud.com/intl/en-us/api-eip/eip_api_0001.html

"alias" is used therefore.

**Comment by anton-sidelnikov** [comment]
Hi @uli-max, I think better to create Jira issue for API docs, because we cannot rely on huawei docs in our work. Best approach to check our internal documentation and fix it if needed.

**Comment by anton-sidelnikov** [comment]
Feature added
