### ISSUE TITLE
[CCE][NODEPOOL] forces replacement after state import

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#2279]
# Terraform provider version
```
Terraform v1.5.5
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.35.5

```

# Affected Resource(s)
- opentelekomcloud_cce_node_pool_v3

# Steps to Reproduce
1. create cce-cluster
2. create cce-node-pool within that cluster
3. delete cce-node-pool from state `terraform state rm opentelekomcloud_cce_node_pool_v3.this`
4. `terraform import opentelekomcloud_cce_node_pool_v3.this <clusterid>/<node_pool_id>`
5. Rerun `terraform apply`
6.  `subnet_id` and `max_pods` cause `# force replacement`
7. `terraform state show opentelekomcloud_cce_node_pool_v3.this` does not contain `max_pods` nor `subnet_id` after beein imported

# Expected Behavior
`opentelekomcloud_cce_node_pool_v3` will be imported with all required data to NOT beeing instantly replaced

# Actual Behavior
see reproduction steps

**Comment by anton-sidelnikov** [comment]
Hi @Moep90 did you try to add this fields in lifecycle ignore_changes?

**Comment by Moep90** [comment]
@anton-sidelnikov How should the `ignore_changes` help here?
It of course helps for the moment but also adds the inability to ever change these values again with terraform but recreating them.

**Comment by anton-sidelnikov** [comment]
@Moep90 Aw, yes, didn't get it, will check now.

**Comment by anton-sidelnikov** [comment]
@Moep90 Check on latest please
