### ISSUE TITLE
1.35.5 removes domain_id from opentelekomcloud_identity_user_v3

### ISSUE THREAD

**Issue by bbung** [opentelekomcloud/terraform-provider-opentelekomcloud#2281]
# Terraform provider version

1.35.4 & 1.35.5

# Affected Resource(s)

opentelekomcloud_identity_user_v3

# Terraform Configuration Files
```hcl
```

# Debug Output/Panic Output

# Steps to Reproduce

Create a opentelekomcloud_identity_user_v3 and use attribute domain_id from the resulting object. Domain_id is no longer available starting from version 1.35.5. As this is a breaking change this has be be at least a minor not a patch version!
This should also be mentioned in the Changelog as breaking change!

# Expected Behavior

Stick to semantic versioning, add breaking changes to changelog!

# Actual Behavior

Patch update breakes your project!

# Important Factoids

# References

**Comment by artem-lifshits** [comment]
Hello @bbung `domain_id` is an optional parameter transferred from openstack which doesn't influence anything in config.
You can remove it in versions before 1.35.4 without any consequences.

**Comment by bbung** [comment]
Hey,

sorry, i may not have made myself clear enough. I am not using this as an argument for the user but use the output "domain_id" in other resources, like in bucket policies. So the issue is the missing output.

`resource "opentelekomcloud_obs_bucket_policy" "policy" {
  bucket = opentelekomcloud_obs_bucket.bucket.id
  policy = <<POLICY
    {
    "Statement":[
      {
      "Effect":"Allow",
      "Principal":{
      "ID":[
        "domain/${opentelekomcloud_identity_user_v3.user.domain_id}:user/${opentelekomcloud_identity_user_v3.user.id}"
      ]
      },
    "Action":["*"],
    "Resource":[
    "*"
    ]
    },`

So the removal from the output breaks all my bucket polices.

**Comment by artem-lifshits** [comment]
Ah you're right, will fix it for next release.

**Comment by artem-lifshits** [comment]
@bbung please check latest.
