### ISSUE TITLE
Include Ubuntu Image in CCE Terraform Node creation

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#2288]
Please include the OS Option for Ubuntu in the CCE OS Node creation section.

https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cce_node_v3

**Comment by anton-sidelnikov** [comment]
Hi! @CHS-OTC, I didn't see in doc any description about Ubuntu, where did you see that?

**Comment by CHS-OTC** [comment]
![Screenshot 2023-08-29 112513](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/79697776/956875e0-2e9a-4edf-88d3-c29b8d2c7c7a)

You can find already deployed. docs Documentation will also need to be updated.

**Comment by anton-sidelnikov** [comment]
Available in v1.35.7
