### ISSUE TITLE
Import opentelekomcloud_lb_whitelist_v2 is not working

### ISSUE THREAD

**Issue by Xaving** [opentelekomcloud/terraform-provider-opentelekomcloud#2289]
Hello,

The following command  
```
import opentelekomcloud_lb_whitelist_v2.mywhitelist_list[0]   id_of_whitelist
```
displays the following message
```
Import successful!
The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
but the resource is not visible in the terraform state. And indeed the object was not created, this can be confirmed by deleting the object:
```
terraform state rm opentelekomcloud_lb_whitelist_v2.mywhitelist_list
╷
│ Error: Invalid target address
│ 
│ No matching objects found. To view the available instances, use "terraform
│ state list". Please modify the address to reference a specific instance.
```
The whitelist object was created with terraform version 0.12.26 with OTC provider version v1.22.7.
The new terraform state uses terraform version 1.5.0 with OTC provider version v1.35.5.

This issue is related to issue #2245.

**Comment by artem-lifshits** [comment]
Hello @Xaving are you trying to import resource in some kind of list?
I've tested the import just now and everything works fine from my side.

Import commands:
<img width="987" alt="Screenshot 2023-08-29 at 11 54 52" src="https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/55093318/0a43c108-da01-4f27-84f0-cbd6c8f949db">

Terraform state after import:
<img width="705" alt="Screenshot 2023-08-29 at 12 03 30" src="https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/55093318/6e664d93-81d9-491a-afa1-8d0d78711816">

**Comment by Xaving** [comment]
@artem-lifshits thank you for the detailed answer. I tried to import as a normal object and not as a list:
```
import opentelekomcloud_lb_whitelist_v2.mywhitelist_list_object   id_of_whitelist
```
and get the message:
```
Error: Cannot import non-existent remote object
```
Indeed the object does not exists! I was a bit misleading by the previous  message.
