### ISSUE TITLE
ip_list description in lb_ipgroup_v3 resource is misleading

### ISSUE THREAD

**Issue by wonderfulspam** [opentelekomcloud/terraform-provider-opentelekomcloud#2299]
The documentation states:
> [ip_list](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_ipgroup_v3#ip_list) - (Required) Specifies the IP addresses or CIDR blocks in the IP address group. [] indicates any IP address.

From my understanding, `[] indicates any IP address.` actually refers to the value of the `ip` attribute. That is, the following will achieve the intended goal:
```
resource "opentelekomcloud_lb_ipgroup_v3" "my_lb_ipgroup" {
  name        = "my_lb_ipgroup"
  description = "IPs allowed to access"

  ip_list {
    ip          = "[]"
    description = "all IPs"
  }
}
```

As such, the comment about how to allow access to all IPs should be moved to the `ip` attribute. I may also be completely mistaken in my understanding and perhaps the documentation fix should be something else entirely.

**Comment by wonderfulspam** [comment]
Maybe this is not a docs issue at all but a code issue? My use case is to remove the IP restriction on an `lb_ipgroup`. Based on [the test case](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/2ea42b8528171b23eac8e7ed982bd883e4aa1145/opentelekomcloud/acceptance/elb/v3/resource_opentelekomcloud_lb_ipgroup_v3_test.go#L185) and the documentation I would expect this to be possible simply by removing any `ip_list` entries. However, this errors with `At least 1 "ip_list" blocks are required.` despite `ip_list` being an optional parameter.

Can you please advise whether the docs are wrong, the provider is wrong or my understanding is wrong?

**Comment by artem-lifshits** [comment]
Hello @wonderfulspam doc updated in latest release along with resource, please check.
