### ISSUE TITLE
DDS - Support actual version 4.2 and 4.4

### ISSUE THREAD

**Issue by uli-max** [opentelekomcloud/terraform-provider-opentelekomcloud#2311]
# Description of the enhancement
tf-provider should provide the actual versions 4.2 and 4.4. for DDS.
https://open-telekom-cloud.com/en/support/release-notes/dds-version-4-4-available-in-eu-de-region

for region eu-de and region eu-nl 

There seems to be also a check, which avoids to create a instance with 4.2 & 4.4.

╷
│ Error: expected datastore.0.storage_engine to be one of [wiredTiger], got rocksDB
│ 
│   with opentelekomcloud_dds_instance_v3.dds_single,
│   on tf_B210_DDS_Single_Instance.tf line 95, in resource "opentelekomcloud_dds_instance_v3" "dds_single":
│   95:     storage_engine = local.dds_single_engine
│ 
╵

While DDS <4-2 was based on "wiredTiger", the 4.2/4.4 are based on "rocksDB".

https://docs.otc.t-systems.com/document-database-service/api-ref/apis_v3.0_recommended/db_instance_management/creating_a_db_instance.html

Please update the provider and also update the documention-page for the provider. 

Thanks!

**Comment by artem-lifshits** [comment]
@uli-max available in latest release.

**Comment by uli-max** [comment]
@artem-lifshits : Thanks for the fast implementation !!!
