### ISSUE TITLE
[DRS] opentelekomcloud_drs_task_v3 support PostgreSQL on endpoints.

### ISSUE THREAD

**Issue by thople** [opentelekomcloud/terraform-provider-opentelekomcloud#2317]
# Description of the enhancement
I would like to request support for PostgreSQL in the opentelekomcloud_drs_task_v3 resource for both source and destination endpoints (source_db and destination_db). 
Currently, the db_info block only supports MySQL, MongoDB, and GaussDBv5 as engine types.

DRS already includes the PostgreSQL migration engine. Additionally, the API endpoints are already compatible with PostgreSQL, as documented in the API documentation:
https://docs.otc.t-systems.com/data-replication-service/api-ref/api/public_api_management/creating_tasks_in_batches.html#id5

I would appreciate it if support for PostgreSQL endpoints could be added.

Thank you.

**Comment by anton-sidelnikov** [comment]
Available in v1.36.17
