### ISSUE TITLE
Change "Country Code" sample in documentation

### ISSUE THREAD

**Issue by uli-max** [opentelekomcloud/terraform-provider-opentelekomcloud#2321]
Please consider to change country code from "0086" to the german code: "0049" in documentation. ;-) 
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/identity_user_v3#country_code

e.g.: The country code of germany is 0086.

**Comment by artem-lifshits** [comment]
@uli-max fixed in the latest release.
