### ISSUE TITLE
[ECS] Unable to create a tag with an empty value

### ISSUE THREAD

**Issue by mreichardt95** [opentelekomcloud/terraform-provider-opentelekomcloud#2324]
# Terraform provider version
```
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/vault v3.20.1
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.35.8
```

# Affected Resource(s)
- opentelekomcloud_compute_instance_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_compute_instance_v2" "ecs-k8s-infra-cp" {
  tags = {
      tag_1 = "",
      customer = var.customer,
  }
}
```

# Steps to Reproduce
1. Create tag with empty value
2. `terraform apply`

# Expected Behavior
Terraform Creates a tag with an empty value

# Actual Behavior
```
│ Error: value "tags" cannot be shorter than 1 characters: ""
│ 
│   with opentelekomcloud_compute_instance_v2.ecs-k8s-infra-cp[0],
│   on kubernetes.tf line 54, in resource "opentelekomcloud_compute_instance_v2" "ecs-k8s-infra-cp":
│   54:   tags = {
│   55:       tag_1 = "",
│   56:       customer = var.customer,
│   57:   }
│ 

```

# Important Factoids
It is possible to create a tag with an empty value in console:
![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/18323490/da4ddc0f-cfd2-4a91-bc7f-647a1bc31588)
![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/18323490/c54ee91c-13f5-4226-ab49-d351966936f0)

**Comment by anton-sidelnikov** [comment]
Hi @mreichardt95 thats interesting because from API side this is ristricted

**Comment by anton-sidelnikov** [comment]
UI and API inconsistency bug: https://jira.tsi-dev.otc-service.com/browse/BM-3139

**Comment by mreichardt95** [comment]
@anton-sidelnikov thank you, for looking into the issue!

**Comment by dombisza** [comment]
It is interesting, at first I thought that empty tags are completely a thing for the console only, but if I query an ECS which has empty tags, it shows up in the API response. So I guess technically the ECS API should be able to handle empty tags. 
```
curl -X GET \                                                                                                                                                     
  -H "Content-Type: application/json" \
  -H "X-Auth-Token: $TOKEN" \
  "https://ecs.eu-de.otc.t-systems.com/v1/$project/cloudservers/$ecs_id/tags"
{"tags":[{"key":"Managed_By","value":"terraform"},{"key":"Owner","value":"sdombi"},{"key":"Stage","value":"dev"},{"key":"empty_test","value":""}]}
```

**Comment by dombisza** [comment]
I tried to add an empty tag via the API and it succeeded:
```bash
curl -X POST -H "Content-Type: application/json" \                                                                                                               
  -H "X-Auth-Token: $TOKEN" \
  -d '{
    "action": "create",
    "tags": [
      {
        "key": "empty",
        "value": ""
      }
    ]
  }' \
  "https://ecs.eu-de.otc.t-systems.com/v1/$project/cloudservers/$ecs_id/tags/action"
```

![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/28303104/499d6363-731d-42d4-9f05-41b0ada33ca6)

So the documentation about mandatory tag value is incorrect most likely.

**Comment by anton-sidelnikov** [comment]
Hi @mreichardt95 @dombisza please check on latest, should works now
