### ISSUE TITLE
obs_bucket_policy: the given example does not work

### ISSUE THREAD

**Issue by sekoban** [opentelekomcloud/terraform-provider-opentelekomcloud#2329]
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/obs_bucket_policy

The given example does not work: "Error: error putting OBS policy: obs: service returned error: Status=400 Bad Request, Code=MalformedPolicy, Message=Action does not apply to any resource(s) in statement., RequestId=0000018AFB2ADF2549D83DEBECE5D1AE"

I assume  "ListBucket" and "ListBucketVersions" do not exist.

**Comment by artem-lifshits** [comment]
@sekoban thank you for reporting, fixed in latest release.
