### ISSUE TITLE
AS group lfecycle hook

### ISSUE THREAD

**Issue by valkaitibor** [opentelekomcloud/terraform-provider-opentelekomcloud#2331]
# Description of the enhancement
Hello OTC Team,

I need a little help in connection with the Autoscaling Group.
My aim is when an ECS is destroyed by the AS group, I would like to stop the cron job. This means that an action should be triggered when an ECs dies.
As I can see, it can be possible (https://support.huaweicloud.com/intl/en-us/usermanual-as/en-us_topic_0042018380.html) but I haven't found the way to do it with terraform.

Could you please help me to integrate this feature into the provider?

Thank you in advance!

**Comment by anton-sidelnikov** [comment]
Hi @valkaitibor this feature not implemented yet, we will check the status.

**Comment by anton-sidelnikov** [comment]
@valkaitibor Available in v1.36.22, please check.
