### ISSUE TITLE
openpgp: key expired when fetching the provider

### ISSUE THREAD

**Issue by cyrgimenv** [opentelekomcloud/terraform-provider-opentelekomcloud#2332]
# Terraform provider version
v1.35.9

# Affected Resource(s)
provider

# Terraform Configuration Files
```hcl
terraform {
  required_providers {
    opentelekomcloud = {
      source = "opentelekomcloud/opentelekomcloud"
    }
  }
}%
```

# Debug Output/Panic Output
```
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to install provider
│ 
│ Error while installing opentelekomcloud/opentelekomcloud v1.35.9: error
│ checking signature: openpgp: key expired
```

# Steps to Reproduce

1. Run a plan on terraform cloud

# Expected Behavior
Init should succeed

# Actual Behavior
```
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to install provider
│ 
│ Error while installing opentelekomcloud/opentelekomcloud v1.35.9: error
│ checking signature: openpgp: key expired
```

**Comment by anton-sidelnikov** [comment]
@cyrgimenv we are working on it, maybe need to wait a few days

**Comment by tbroders** [comment]
Hint: 
I have the same issue using image hashicorp/terraform:1.6.0
With hashicorp/terraform:1.4.7 the installation of the provider is successfull

**Comment by anton-sidelnikov** [comment]
Hi @tbroders @cyrgimenv this is general terraform issue with 1.6.0, there is a lot gpg issues with this version in different providers now. Please use 1.5.7 for now or any version lower that 1.6.0

https://github.com/hashicorp/terraform/issues/33984

**Comment by hi9105** [comment]
I am also facing following issue
 
 Error: Failed to install provider
│ 
│ Error while installing cyrilgdn/postgresql v1.21.0: error checking
│ signature: openpgp: key expired

**Comment by anton-sidelnikov** [comment]
Fixed in latest terraform versions
