### ISSUE TITLE
firewall rule: configure port range

### ISSUE THREAD

**Issue by phake24** [opentelekomcloud/terraform-provider-opentelekomcloud#2333]
# Terraform provider version
1.35.9

# Affected Resource(s)
opentelekomcloud_fw_rule_v2

# Terraform Configuration Files
resource "opentelekomcloud_fw_rule_v2" "rule_1" {
  name             = "my_rule"
  description      = "drop traffic"
  action           = "deny"
  protocol         = "tcp"
  destination_port = "23-30"
  enabled          = "true"
}

# Debug Output/Panic Output
│ Error: Bad request with: [POST https://vpc.eu-de.otc.t-systems.com/v2.0/fwaas/firewall_rules], error message: {"NeutronError":{"message":"Invalid input for destination_port. Reason: Port '23-30' is not a valid number..","type":"HTTPBadRequest","detail":""}}
│
│   with opentelekomcloud_fw_rule_v2.rule_1,
│   on secgroup_web.tf line 32, in resource "opentelekomcloud_fw_rule_v2" "rule_1":
│   32: resource "opentelekomcloud_fw_rule_v2" "rule_1" {

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior
I excted that it is possible to configure a port range within a firewall rule, as OTC console supports it.

# Actual Behavior
only one port can be configure, no port range

**Comment by anton-sidelnikov** [comment]
Hi @phake24 should be like: destination_port = "23:30"
https://docs.otc.t-systems.com/virtual-private-cloud/api-ref/native_openstack_neutron_apis_v2.0/firewall/creating_a_firewall_rule.html#vpc-firewall-0003

**Comment by phake24** [comment]
yo are right! I was searching for documentation regarding that, but could not find. Thanks for your help!
