### ISSUE TITLE
Password complexity rules seem to not match documented requirements

### ISSUE THREAD

**Issue by Z3po** [opentelekomcloud/terraform-provider-opentelekomcloud#2335]
# Terraform provider version
1.35.9

# Affected Resource(s)
opentelekomcloud_dcs_instance_v1

# Terraform Configuration Files
```hcl
resource "random_password" "testinstance" {
  length           = 32
  min_lower        = 1
  min_upper        = 1
  min_numeric      = 1
  min_special      = 1
}

resource "opentelekomcloud_dcs_instance_v1" "instance_1" {
  name           = "testinstance"
  engine_version = "6.0"
  password       = random_password.testinstance.result
  engine         = "Redis"
  capacity       = 0.125
*SNIP*
}
```

I've snipped all other configuration settings but just kept the necessary to report the bug.

# Debug Output/Panic Output
```
Error: error creating DCS instance: Bad request with: [POST https://dcs.eu-de.otc.t-systems.com/v1.0/{PROJECT_ID}/instances], error message: {"error":{"code":"111400019","message":"The password does not meet complexity requirements.","ext_message":null}}
```

# Steps to Reproduce
Apply the above resources (with all necessary settings applied of course)

# Expected Behavior
The instance gets created

# Actual Behavior
See Panic Output

# Important Factoids
Lowering the complexity of the random password to

```hcl
resource "random_password" "testinstance" {
  length           = 32
  min_lower        = 1
  min_upper        = 1
  min_numeric      = 0
  min_special      = 1
}
```

causes the resource to be created succesfully.
Feels like there's a bug in the complexity check that only succeeds on passwords with "less or equal" 3 characters instead of "greater or equal" 3 characters.

The errormessage indicates that this might rather be a bug in the API than in the terraform provider, but I didn't know where I should report this instead.

# References
* https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/dcs_instance_v1
* https://docs.otc.t-systems.com/distributed-cache-service/api-ref/lifecycle_management_apis/creating_a_dcs_instance.html#dcs-api-0312004

**Comment by anton-sidelnikov** [comment]
Created internal bug: https://jira.tsi-dev.otc-service.com/browse/BM-3307

**Comment by anton-sidelnikov** [comment]
Hi @Z3po test team double checked, seems the problem in random module. Only this special characters are valid: `~!@#$^&*()-_=+|\{}:,<>./? but random sometimes adds others, like: %

**Comment by Z3po** [comment]
HI @anton-sidelnikov thanks for your answer and sorry for my late reply.

Do you plan to update your documentation then?\
In https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/319eee9da3c65b31981312846caff77297be9989/docs/resources/dcs_instance_v1.md?plain=1#L114-L118 it still says:

```
and special characters (`~!@#$%^&*()-_=+|[{}]:'",<.>/?).
```

Which includes the `%` character.

Thanks a lot!
