### ISSUE TITLE
Add Support for OpenTofu

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#2342]
# Description of the enhancement

As Terraform is now under BSL, please consider to support [OpenTofu](https://github.com/opentofu/opentofu) in the future

**Comment by anton-sidelnikov** [comment]
@Moep90 Hi, OpenTofu not even in production state now, and also there is a lot of other issues, one and the biggest that we can't use terraform registry if choose OpenTofu. So, there is still place to think.

**Comment by Moep90** [comment]
> @Moep90 Hi, OpenTofu not even in production state now, and also there is a lot of other issues, one and the biggest that we can't use terraform registry if choose OpenTofu. So, there is still place to think.

I know. And I know processes. Therfore I just wanted to make sure that this is on your roadmap if its get serious.
They are already planing a registry so it should not last long.

Thx and best regards

**Comment by artem-lifshits** [comment]
While OpenTF is still in development stage let's keep this topic in discussions section.
Thank you.

**Comment by kvendingoldo** [comment]
btw. you can also integrate [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management.
