### ISSUE TITLE
CSS - Opensearch is missing in documentation

### ISSUE THREAD

**Issue by uli-max** [opentelekomcloud/terraform-provider-opentelekomcloud#2343]
Since a while CSS support Opensearch. PLease add to documentation.

https://open-telekom-cloud.com/en/support/release-notes/css-offers-now-opensearch-1-3-6-as-alternative-to-elasticsearch-in-the-netherlands

Please add "Opensearch_1.3.6" to the versions. (datastore block). 

  css_datastore_type     = "elasticsearch"
  css_datastore_version  = "Opensearch_1.3.6"
 
 Please check als0 the mentioned flavors.
 There are more flavors available. 
https://docs.otc.t-systems.com/cloud-search-service/api-ref/cluster_management_apis/creating_a_cluster.html#css-03-0019
   
Thanks 
uli

**Comment by artem-lifshits** [comment]
Fixed in latest release.
