### ISSUE TITLE
Missing attributes for SNAT configuration

### ISSUE THREAD

**Issue by valkaitibor** [opentelekomcloud/terraform-provider-opentelekomcloud#2350]
# Description of the enhancement
Hello OTC Team,

I need your help. We would like to use SNAT to let the ECSs reach the internet without an own EIP. To make our method terraform compatible, we would like to set some parameters with terraform, that cannot be achieved at the moment.
1. For an ECS, I am not able to set the `1/a) Source/Destination check` and `1/b) Virtual IP address` with terraform.
As the `virtual IP address` belongs to a subnet and should be attached to an ECS (or an EIP), I think it would be the best the create the Virtual IP address as an individual resource, with the `subnet ID` as a parameter. After that, it can be bind to the ECS (or EIP) like we bind an EIP to the ECS as well with `opentelekomcloud_networking_floatingip_associate_v2`.
The `Source/Destination check` attribute should be available for an ECS in the `nics` block, the values can be `true` or `false`.
I have found a similar ticket: https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/116

2. At the moment, it is not possible to set the `nexthop` type in the `opentelekomcloud_vpc_route_v2` resource to `server`. We also need this for the SNAT configuration. Now, only `peering` can be used as `type`. On the OTC GUI, it is possible to set `Server`, `Extension NIC`, `NAT gateway`, `VPC peering connection` and `Virtual IP address`. From the list, we would like to use `server` as soon as possible, and the `next hop` is the ECS itself (that has the virtual private IP address associated).

Thank you so much for the help! :)

**Comment by anton-sidelnikov** [comment]
@valkaitibor SNAT can be enabled only through user_data: https://docs.otc.t-systems.com/virtual-private-cloud/umn/route_tables/configuring_an_snat_server.html#vpc-route-0004, there is no api for Source/Destination check enabling/disabling. Regarding virtual IP, i will look how to deal with it.


Btw, also for  route_v2 only peering type now supported: https://docs.otc.t-systems.com/virtual-private-cloud/api-ref/apis/vpc_route/creating_a_vpc_route.html#vpc-route-0003

**Comment by anton-sidelnikov** [comment]
@valkaitibor we have `opentelekomcloud_networking_vip_v2` and `opentelekomcloud_networking_vip_associate_v2` for virtual ips management

**Comment by lhajba** [comment]
@anton-sidelnikov: what about this old example? "opentelekomcloud_networking_port_v2" and "opentelekomcloud_compute_instance_v2" 
https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/devel/examples/basic-examples/modules/vpc_subnet/network.tf
this should also create the virtual IP for the ECS. 

@valkaitibor: please check if the example helps you.

**Comment by valkaitibor** [comment]
Hello @anton-sidelnikov,

I have tried using those resources (`opentelekomcloud_networking_vip_v2`, `opentelekomcloud_networking_vip_associate_v2`), but I have a little problem.
When I would like to create a virtual ip address this way, it needs to have a networking_network resource, which we don’t have.
I don’t have experience in using this resource, but as I can image, it is similar to a VPC. It has a subnet under it, and for that subnet, we can create a virtual ip address.
In the project, we are using VPC with a subnet. And it is not possible to create a virtual IP address for the VPC subnet, I mean I am having error messages that the network id is not found (I am using the VPC ID).
Could you please help me if it is possible to create a virtual IP address for a VPC and its subnet?
On the OTC console, it is possible to create a virtual IP address for a VPC subnet, and it is not a must to use a networking network for this.

**Comment by anton-sidelnikov** [comment]
@valkaitibor having error messages that the network id is not found (I am using the VPC ID). - did you try to use subnet_id in that case?

**Comment by valkaitibor** [comment]
Hello @anton-sidelnikov,

Thank you, I have got a hint from Martin Happel, that is working:

resource "opentelekomcloud_ecs_instance_v1" "ecs_tibi_test" {
  name              = "ecs_tibi_test"
  image_id          = "..."
  flavor            = "s2.medium.1"
  vpc_id            = "..."

  nics {
    network_id      = "..." **<-- VPC subnet network ID**
  }

  security_groups   = ["..."]
  availability_zone = "..."
  key_name          = "..."

  system_disk_type = "SATA"
  system_disk_size = 40
}


resource "opentelekomcloud_networking_vip_v2" "vip_1" {
  network_id = ".." <-- VPC subnet network ID
  subnet_id  = "f1ef4cea-8f07-472f-9fe4-2f7043128311" **<-- VPC Subnet Subnet ID**
}

resource "opentelekomcloud_networking_vip_associate_v2" "vip_associate_1" {
  vip_id = opentelekomcloud_networking_vip_v2.vip_1.id
  port_ids = [opentelekomcloud_ecs_instance_v1.ecs_tibi_test.nics.0.port_id]
}


And a soon as a virtual IP address is attached to the ECS, the "Source/Destination check" flag is changed to "false" automatically.
There was a confusion inside my head that a subnet has a subnet ID and a network ID as well.

So the missing part is now the routing: setting the next hop type to "server".
As I know, this is currently not supported by the OTC API at all, it only supports type=peering.
Sven told me this: "_It first needs to be possible via OTC API, afterwards the Terraform provider can be updated._"

**Comment by anton-sidelnikov** [comment]
@valkaitibor, yes there is some confusion because previously in old resources we tries to be closer to openstack naming notation, but that brings this confusion now, if in future terraform will support attribute aliasing, then we will fix that. 
Also I'm currently working on route tables implementation https://github.com/opentelekomcloud/gophertelekomcloud/pull/590, this resource supports not only peering but other types.

**Comment by anton-sidelnikov** [comment]
@valkaitibor new resource vpc_route_table_v1 now available
