### ISSUE TITLE
CCE addon installation fails with "Internal Server Error"

### ISSUE THREAD

**Issue by generalpax** [opentelekomcloud/terraform-provider-opentelekomcloud#2352]
# Terraform provider version

# Affected Resource(s)

# Terraform Configuration Files
```hcl
Terraform v1.6.2
on darwin_arm64
+ provider registry.terraform.io/hashicorp/kubernetes v2.23.0
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.35.10
```

# Debug Output/Panic Output

https://gist.github.com/generalpax/6f7c76a0964b0d8041747b0a7fd735b6

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

Addons where installed on a CCE cluster

# Actual Behavior

Addons shortly installing without running any pods, then disappearing giving this terraform error which i also found in the provider code, but acutally says nothing helpful:

```
2023-10-23T18:43:55.654+0200 [ERROR] vertex "opentelekomcloud_cce_addon_v3.npd" error: error creating CCE addon instance:
Addon template spec: {"kind":"Addon","apiVersion":"v3","items":[{"kind":"Addon","apiVersion":"v3","metadata":{"name":"npd","uid":"npd","lables":null,"annotaions":null},"spec":{"type":"helm","require":false,"labels":["Maintenance"],"logoURL":"https://obs.eu-ch2.sc.otc.t-systems.com/cce-addon-eu-ch2-aw1hz2u/npdlogo.svg","readmeURL":"","description":"node-problem-detector aims to make various node problems visible to the upstream layers in cluster management stack","versions":[{"version":"1.17.4","input":{"basic":{"image_version":"1.17.4","swr_addr":"swr.eu-ch2.sc.otc.t-systems.com","swr_user":"hwofficial"},"parameters":{"custom":{"feature_gates":"","npc":{"enable":true}},"flavor1":{"description":"custom resources","name":"custom-resources","replicas":2,"resources":[{"limitsCpu":"100m","limitsMem":"300Mi","name":"node-problem-controller","requestsCpu":"30m","requestsMem":"100Mi"},{"limitsCpu":"30m","limitsMem":"100Mi","name":"node-problem-detector","requestsCpu":"30m","requestsMem":"100Mi"}]}}},"stable":true,"supportVersions":[{"clusterType":"VirtualMachine","clusterVersion":["v1.(19|21|23|25).*"]},{"clusterType":"ARM64","clusterVersion":["v1.(19|21|23|25).*"]}],"creationTimestamp":"2023-04-04T12:34:28Z","updateTimestamp":"2023-04-04T12:34:28Z"}]}}]}
Internal Server Error
```

# Important Factoids

region: eu-ch2
The cluster is behind SNAT gateway without having any EIP. When i install the addons without terraform directly over the API with a http "POST" call it works as a charm. So it must be a provider bug...

# References

**Comment by artem-lifshits** [comment]
Hello @generalpax. `Internal server error` means that 500 error response was received from the server in reply to some API request.
This is not a provider bug but problems on OTC backend, please report this issue to OTC support team.

**Comment by generalpax** [comment]
Ok, i will raise an Issue to the OTC support also.
