### ISSUE TITLE
Cannot configure Backend for Remote tfstate file

### ISSUE THREAD

**Issue by makwana030482** [opentelekomcloud/terraform-provider-opentelekomcloud#2359]
I am trying to configure the Backend for Open telekom Cloud. When I use terraform v1.5.5 all goes well, however, when I use latest Terraform v1.6.2, I get below error: 
Please note, the code andeverything is same. I am not able to find any documentation on opentelekomprovider for Terraform version 1.6.2, like deprecated or changed features. 
![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/145347300/57751673-a30e-49b5-b044-64842b664417)

**Comment by artem-lifshits** [comment]
Hello @makwana030482 looks like the issue is related to terrafrom version, not provider part.
Anyways if you provide the config with remote tfstate file initialisation we might be able to help.
You can also check this ticket with related issue: [#2269](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/2269)

**Comment by makwana030482** [comment]
> Hello @makwana030482 looks like the issue is related to terrafrom version, not provider part. Anyways if you provide the config with remote tfstate file initialisation we might be able to help. You can also check this ticket with related issue: [#2269](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/2269)

hello @artem-lifshits, you are bang on, issue is with terraform version, currently I am using the workaround with lower version of terraform, was worndering if we have any documents with providers version cmpatibilty with teraform versions.

**Comment by artem-lifshits** [comment]
@makwana030482 maybe this link will be of help, I've found the same issue in terraform github with a workaround:
https://github.com/hashicorp/terraform/issues/33983

```
[lotusnoir](https://github.com/lotusnoir) commented [3 hours ago](https://github.com/hashicorp/terraform/issues/33983#issuecomment-1801632383)
I got it working replacing

endpoint = "https://s3.fr-par.scw.cloud"

by

    endpoints = { s3 = "https://s3.fr-par.scw.cloud" }
    skip_requesting_account_id = true
then

terraform init -reconfigure
```

I'll discuss with the team whether such compatibilty documentation should be created for OTC provider, at the moment we don't have any.
Thanks for the tip!
