### ISSUE TITLE
[REQUEST] Add Tag support to RDS resource

### ISSUE THREAD

**Issue by tstrohmeier** [opentelekomcloud/terraform-provider-opentelekomcloud#236]
Hi!

We would like to see a support for tags in the RDS instance resource , like in Compute Instance v2 resource.

```hcl
resource "opentelekomcloud_rds_instance_v1" "instance" {
  name            = "basic"
  ...
  tag {
    foo = "bar"
    key = "value"
  }
  ...
}
```

According to the OTC Documentation, there is a support for tags in the API: https://docs.otc.t-systems.com/en-us/api/rds/en-us_topic_0110967280.html

Thank you,
Thomas

**Comment by niuzhenguo** [comment]
@tstrohmeier do you mean https://docs.otc.t-systems.com/en-us/api/rds/en-us_topic_0160329113.html ?

**Comment by niuzhenguo** [comment]
@tstrohmeier I tried the API but seems it doesn't work as the docs said :(

**Comment by bym520zy** [comment]
awesome

**Comment by bym520zy** [comment]
@niuzhenguo  we will watch this

**Comment by tstrohmeier** [comment]
@niuzhenguo : Yes you URL is correct. Maybe they changed the URL of the docs with the new release.

The docs are a bit confusing. I talked with T-Systems and got a hint: It is necessary to set the 
`X-Language: en-us` header. You can find this info, well hidden, in the docs with the title **"Common Request Headers"** (https://docs.otc.t-systems.com/en-us/api/rds/en-us_topic_0032347753.html). 

A example request would look like this:

```
curl -s -H "Content-Type: application/json" -H "X-Auth-Token: $OS_TOKEN" -H "X-Language: en-us" https://rds.eu-de.otc.t-systems.com/v1/{project_id}/rds/{instanceId}/tags -d '{"tag":{"key":"FOO","value":"BAR"}}'
```

**Comment by niuzhenguo** [comment]
@tstrohmeier Tag support for RDS instance v1 is already done, but V1 tag API doesn't work for V3 instance.

**Comment by tstrohmeier** [comment]
@niuzhenguo: Thank you! We are aware of this. Currently I try to clarify if we can expect tag support for RDS API v3 soon. I keep you up to date. 
Do you already know when you release the provider version v1.8.0?

**Comment by niuzhenguo** [comment]
@tstrohmeier already sent the release request to HashiCorp, wait them to help cut the release.

**Comment by niuzhenguo** [comment]
@tstrohmeier v1.8.0 released!

**Comment by tstrohmeier** [comment]
@niuzhenguo Thank you!

**Comment by TomMann** [comment]
Is there any update on this in regards to the the v3 api ? can we expect tagging support on the v3 api any time soon ?

**Comment by niuzhenguo** [comment]
@TomMann not sure when v3 API will support it.

**Comment by tstrohmeier** [comment]
@TomMann As far as I know it will be end of this year.

**Comment by tstrohmeier** [comment]
We had a discussion now and came up with a possible workaround, untill RDS API v3 will be feature complete:

I looked at the docs of RDS API v1 & RDS API v3 regarding the instance IDs.
From my understanding it should be possible to use the RDS API v1, with a easy mapping, as a workaround for all the actions which are not yet implemented in RDS API v3. 

My proposal is to use the following mapping:
`v1_instance.id = v3_instance.nodes[0].id`

**Example:**
`curl -H "Content-Type: application/json" -H "X-Auth-Token: $OS_TOKEN" -H "X-Language: en-us" -X POST https://rds.eu-de.otc.t-systems.com/v1/{$project_id}/rds/{$v3_instance.nodes[0].id}/tags -d '{"tag":{"key":"FOO","value":"BAR"}}'`

The same should work for changing the flavor and instance volume.


@niuzhenguo What do you think about this?

Refer to:
- #336
- #267

Maybe also interresting for:
- @Moep90 
- @TomMann 
- @baumjamin
- @Guchelkaben

**Comment by niuzhenguo** [comment]
@tstrohmeier Thanks for the proposal, will have a try.

**Comment by niuzhenguo** [comment]
@tstrohmeier I have added the instance flavor changing support, but after changing to MODIFYING state, it is stucked.

**Comment by tstrohmeier** [comment]
@niuzhenguo Is this issue resolved with #373 ?

**Comment by niuzhenguo** [comment]
@tstrohmeier Yes, closing this.

**Comment by tstrohmeier** [comment]
> @tstrohmeier I have added the instance flavor changing support, but after changing to MODIFYING state, it is stucked.

@niuzhenguo  Is this still an issue?

**Comment by niuzhenguo** [comment]
@tstrohmeier Seems it's a bug on Cloud side, the state may be stucked in MODIFYING state.
