### ISSUE TITLE
opentelekomcloud_obs_bucket proxyconnect tcp: dial tcp :0: connect: connection refused

### ISSUE THREAD

**Issue by dombisza** [opentelekomcloud/terraform-provider-opentelekomcloud#2362]
# Terraform provider version

v1.35.10
# Affected Resource(s)

`opentelekomcloud_obs_bucket`
# Terraform Configuration Files

As a t-systems employee I cannot create OBS buckets from my company client. Seems like this is the only terraform/otc resource I am having troubles with. I can reach OBS endpoint via HTTPS. Do you guys have any idea what is going wrong here? thanks. I have tried with and without company proxies. I tried `opentelekomcloud_s3_bucket` resource for bucket creation and that worked for me, so I am lost...

```hcl
resource "opentelekomcloud_obs_bucket" "this" {
  bucket = var.s3_chunks
  acl    = "private"
  server_side_encryption {
    algorithm = "kms"
    kms_key_id = opentelekomcloud_kms_key_v1.this.id
  }
}
```

```
╷
│ Error: Put "https://sdombi-chunker.obs.eu-de.otc.t-systems.com:443": proxyconnect tcp: dial tcp :0: connect: connection refused
│
│   with opentelekomcloud_obs_bucket.this,
│   on obs.tf line 8, in resource "opentelekomcloud_obs_bucket" "this":
│    8: resource "opentelekomcloud_obs_bucket" "this" {
│
╵
```
```
curl https://sdombi-chunker.obs.eu-de.otc.t-systems.com:443                                                                                                ░▒▓ sia-lb.telekom.de:8080 ↔
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><RequestId>0000018B952DC76C49D412DF1B83312F</RequestId><HostId>aa/RqNdRzpUSDbDAf7It+1nMdn9sX0Y0EIKnT05Mp1gG5+xvUwTrY6jK5qwilTdi</HostId><BucketName>sdombi-chunker</BucketName></Error>
```

# Debug Output/Panic Output

https://gist.github.com/dombisza/b8f80da8f3a809b04a6422e0812535f7
# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

# Actual Behavior

# Important Factoids

# References

**Comment by anton-sidelnikov** [comment]
Hi @dombisza did you check proxy approach from #2220?

**Comment by dombisza** [comment]
hi @anton-sidelnikov you are a life saver, thanks!
