### ISSUE TITLE
Password complexity rules documentation is wrong (dcs_instance_v1)

### ISSUE THREAD

**Issue by Z3po** [opentelekomcloud/terraform-provider-opentelekomcloud#2366]
This issue is a follow-up of https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/2335 as I think nobody will notice my latest comment about it :)

Reading the statement of @anton-sidelnikov in the mentioned issue

> Hi @Z3po test team double checked, seems the problem in random module. Only this special characters are valid: `~!@#$^&*()-_=+|{}:,<>./? but random sometimes adds others, like: %

 it looks like the documentation of password recovery rules in  https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/319eee9da3c65b31981312846caff77297be9989/docs/resources/dcs_instance_v1.md?plain=1#L114-L118 is wrong. It says there:

```
and special characters (`~!@#$%^&*()-_=+|[{}]:'",<.>/?).
```

Which includes the `%` character.

Can you update your documentation?

Thanks a lot!

_Originally posted by @Z3po in https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/2335#issuecomment-1797953327_

**Comment by anton-sidelnikov** [comment]
HI @Z3po, sorry I for no response on your comment, for sure we will update documentation. Thanks

**Comment by artem-lifshits** [comment]
@Z3po fixed in latest release.
