### ISSUE TITLE
RDS autoscaling

### ISSUE THREAD

**Issue by valkaitibor** [opentelekomcloud/terraform-provider-opentelekomcloud#2373]
# Description of the enhancement
Hello OTC Team,
I need some help regarding the `opentelekomcloud_rds_instance_v3` resource.
I would like to create an RDS with autoscaling, but I can find how to apply it with terraform.
Could you please help me, if this feature is already implemented in the provider?

**Comment by artem-lifshits** [comment]
Duplicate, please refer to #2222
