### ISSUE TITLE
IMS missing image properties

### ISSUE THREAD

**Issue by opnmind** [opentelekomcloud/terraform-provider-opentelekomcloud#2374]
Please check and repair the ability to use properties. We need this to read the metadata from an existing image and it would be great if it is possible to set them during the image creation.

https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/ba5d9dc183597d165cefcc98d4e52f680878ef19/opentelekomcloud/services/ims/data_source_opentelekomcloud_images_image_v2.go#L270

Thanks and greetings

**Comment by artem-lifshits** [comment]
Hello @opnmind what kind of metadata do you need?
The properties section in `data_source/opentelekomcloud_images_image_v2` was used for image filtering and it doesn't affect the output of metadata.

I guess you want to have ability to add some metadata for `resource/opentelekomcloud_images_image_v2` on creation?

**Comment by opnmind** [comment]
Hello @artem-lifshits,
yes and no :). I want to get some metadata from a public images to receive e.g. the default login user name which is available there. And of course it would be also usefule to set some metadata during a creation of an image.

**Comment by artem-lifshits** [comment]
@opnmind please check latest images data source.
For other resources / data sources you can link documentation or give a list of metadata parameters you want to be implemented and I'll work on it.
