### ISSUE TITLE
dedicated waf creation failed. unexpected status 4.

### ISSUE THREAD

**Issue by celinesantosh98** [opentelekomcloud/terraform-provider-opentelekomcloud#2375]
terraform version Terraform v1.6.4

# Affected Resource(s)
opentelekomcloud_waf_dedicated_instance_v1

I ran the script as in documentation 
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/waf_dedicated_instance_v1 
to create dedicated waf. it was working fine for me but past two days the same script failed to create dedicated waf

# Expected Behavior

create dedicated waf in running status

# Actual Behavior

creation failed with unexpected status 4
below is the error message 
 Error: error creating OpenTelekomCloud WAF dedicated instance: error while creating opentelekomcloud WAF dedicated instance 3bc758148f324111adf35a884a8b725d. Unexpected status: 4

**Comment by artem-lifshits** [comment]
API was updated with required parameter, implementation ongoing from our side.

**Comment by celinesantosh98** [comment]
Thank you

**Comment by celinesantosh98** [comment]
Can you please inform once it's fixed?

**Comment by artem-lifshits** [comment]
@celinesantosh98 fix will be available in the upcoming release on 30th of November.
I will ping you here.

**Comment by celinesantosh98** [comment]
Thanks for the update.

**Comment by artem-lifshits** [comment]
@celinesantosh98 please check latest release.

**Comment by celinesantosh98** [comment]
Can you tell me the steps I should do ? I have upgraded terraform and ran my code again but still I am getting the same issue.

**Comment by celinesantosh98** [comment]
Can you tell me the steps I should do ? I have upgraded terraform and ran my code again but still I am getting the same issue.

**Comment by artem-lifshits** [comment]
@celinesantosh98 please check if you're providing `network_id` in the `subnet_id` parameter.
There's some mixture between Openstack and OTC naming so please make sure these parameters aren't confused.

**Comment by celinesantosh98** [comment]
data "opentelekomcloud_networking_secgroup_v2" "default_secgroup" {
  name = "default"
}

resource "opentelekomcloud_waf_dedicated_instance_v1" "wafd_1" {
  name              = "wafd-instance-1"
  availability_zone = "eu-de-01"
  specification     = "waf.instance.professional"
  flavor            = "s2.large.2"
  architecture      = "x86"
  vpc_id            = data.opentelekomcloud_vpc_subnet_v1.shared_subnet.vpc_id
  subnet_id         = data.opentelekomcloud_vpc_subnet_v1.shared_subnet.network_id

  security_group = [
    data.opentelekomcloud_networking_secgroup_v2.default_secgroup.id
  ]
}

this is my code from document which I ran now. still I am getting same error 
Error: error creating OpenTelekomCloud WAF dedicated instance: error while creating opentelekomcloud WAF dedicated instance 44ad966e923245b6aa7e1a1b5a36febe. Unexpected status: 4
│ 
│   with opentelekomcloud_waf_dedicated_instance_v1.wafd_1,
│   on create_waf.tf line 61, in resource "opentelekomcloud_waf_dedicated_instance_v1" "wafd_1":
│   61: resource "opentelekomcloud_waf_dedicated_instance_v1" "wafd_1" {
│ 
terraform version I am using

Terraform v1.6.5
on darwin_arm64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.35.12

**Comment by artem-lifshits** [comment]
@celinesantosh98 please specify provider version:
```
terraform {
  required_providers {
    opentelekomcloud = {
      source  = "opentelekomcloud/opentelekomcloud"
      version = "~> 1.35.13"
    }
  }
}
```
and update terraform provider by running:
```
terraform init --upgrade
```

**Comment by celinesantosh98** [comment]
Yes now it's working for me. Thanks a lot .
