### ISSUE TITLE
opentelekomcloud_dds_instance_v3 suddenly what to be recreated

### ISSUE THREAD

**Issue by bbung** [opentelekomcloud/terraform-provider-opentelekomcloud#2378]
# Terraform provider version

Terraform v1.5.3
on darwin_arm64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.35.12

# Affected Resource(s)

opentelekomcloud_dds_instance_v3 

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_dds_instance_v3" "db-single-1" {
  name   = "db-single-1"
  region = "eu-de"
  datastore {
    type           = "DDS-Community"
    version        = "4.0"
    storage_engine = "wiredTiger"
  }

  availability_zone = "eu-de-03"
  vpc_id            = data.opentelekomcloud_vpc_v1.workload-vpc.id
  subnet_id         = one(data.opentelekomcloud_vpc_subnet_ids_v1.subnet_ids.ids)
  security_group_id = data.opentelekomcloud_networking_secgroup_v2.nodes-to-documentdb.id
  password          = "ChangeMePLS"
  mode              = "Single"
  flavor {
    type    = "single"
    num     = 1
    storage = "ULTRAHIGH"
    size    = 10 // divisible by 10
    spec_code = "dds.mongodb.s2.large.4.single"

    # terraform state show data.opentelekomcloud_dds_flavors_v3.all_flavors

  }
  disk_encryption_id = opentelekomcloud_kms_key_v1.db-single-1.id

  ssl = true

  lifecycle {
    // API for passwordchange is not available
    ignore_changes = [
      password
    ]
    prevent_destroy = true
  }

  depends_on = [
    opentelekomcloud_kms_key_v1.db-single-1
  ]
}

```

# Debug Output/Panic Output

# Steps to Reproduce

1. `terraform apply`
nothing changes (wait a couple of month ?!)
2. `terraform apply`again

# Expected Behavior

no changes, so nothing should happen

# Actual Behavior

Just applied terraform again in this longer running database resource. Terraform suddenly wants to destroy / recreate the database. If if disable the prevent_destroy i get the following output which are the exact values that are A defined in the terraform resource and B are exactly the thinks currently running in OTC.
```
  # opentelekomcloud_dds_instance_v3.db-single-1 must be replaced
-/+ resource "opentelekomcloud_dds_instance_v3" "db-single-1" {
      + availability_zone  = "eu-de-03" # forces replacement
      ~ db_username        = "rwuser" -> (known after apply)
      ~ id                 = "REDACTED" -> (known after apply)
        name               = "db-single-1"
      ~ nodes              = [
          - {
              - id         = "REDACTED"
              - name       = "db-single-1_single_node_1"
              - private_ip = "REDACTED"
              - public_ip  = ""
              - role       = "Primary"
              - status     = "normal"
              - type       = "single"
            },
        ] -> (known after apply)
      + password           = (sensitive value)
      ~ pay_mode           = "0" -> (known after apply)
      ~ port               = 8635 -> (known after apply)
      ~ status             = "normal" -> (known after apply)

        # (7 unchanged attributes hidden)

      + flavor { # forces replacement
          + num       = 1
          + size      = 10
          + spec_code = "dds.mongodb.s2.large.4.single"
          + storage   = "ULTRAHIGH" # forces replacement
          + type      = "single" # forces replacement
        }

      - timeouts {}

        # (1 unchanged block hidden)
    }


Plan: 1 to add, 0 to change, 1 to destroy.
```
![Screenshot 2023-11-24 at 16 17 38](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/1083986/4ca69569-a190-4dbc-8ddd-46544b174165)

# Important Factoids

After i got the error i updated the terraform provider to the latest version (was 1.35.9)

# References

**Comment by anton-sidelnikov** [comment]
Hi @bbung, looks like error in your configuration, could it be that you are using several providers in configurations which creates conflicting resources, we cannot reproduce that, and for me single instance need ~300 seconds to create...
=== RUN   TestAccDDSV3Instance_singleT
--- PASS: TestAccDDSV3Instance_singleT (308.73s)
PASS

**Comment by bbung** [comment]
Hi @anton-sidelnikov;

thanks for testing this out. We only use the one provider (otc). This also happens when i delete the database from the state and reimport it. 

We also do have a couple of other databases provisioning in the same project, they are similar to this database server. Which have no issue.

I currently do have no idea what to do as deleting and importing also produces this behaviour.

Any other suggestions?

**Comment by anton-sidelnikov** [comment]
Hm, okay seems that can be the issue, i will check import function

**Comment by anton-sidelnikov** [comment]
@bbung pls try to add "flavor", "availability_zone" to ignore_changes block for imported resource

**Comment by bbung** [comment]
@anton-sidelnikov Adding this two entries to the ignore_changes is working. 

We just got the same behaviour in a second otc-account / terraform project. There was no state deletion or import done, yet. And also nothing changed there. No new provider version. 

This also effects only the oldest database in this project. So this is maybe a similarity. In this project and in the other project, both databases are our first databases created in the account and are also our oldest (created 2023-01-11 and 2023-03-13). However in the second terraform project we just got the error only once. We canceled the apply and applied again and the issue was gone? Very strange.

**Comment by anton-sidelnikov** [comment]
Hi @bbung seems resource was updated according api changes and this old resources some kind outdated now, reimport and ignore changes should help in that situation. Also api response is very rough and we can not add proper mapping for availability zones and flavors.

**Comment by dombisza** [comment]
I tried to reproduce this with a newly created dds resource, but for me re-creation is not triggering. It might be possible that only dds instances created in the past are affected, but if thats the case re-importing and ignoring changes should solve this.

**Comment by Nils-Magnus** [comment]
I think I have seen this pattern in the past in some completely different resources. This might be due to the relationship between names and IDs: If you, for instance, request for an ECS instance `Standard_Ubuntu_22.04_latest` as the `image`, its ID is`a2f25ad7-56fd-43b1-8847-695435f5f2a3` (as of 2023-12-14, 16:46) and is stored in Terraform's state file. If you re-run the `apply` a few minutes or hours later, nothing changes.

However, `image` resources get updated every now and then (I think once or twice a month, as a rule of thumb), but keep their name. After this update, the resource `Standard_Ubuntu_22.04_latest` may have a new ID, say `aaaaaaaa-bbbb-cccc-dddd-ffffffffffff`. Now `terraform apply` compares the ID from the state file with the ID of `Standard_Ubuntu...`, notices that `a2f2...` is not requested by any template (and thus deletes it) and that `aaaaaa-bbbb...` is currently not existing (and thus creates it).

That's why using convenient "symbolic" resource identifiers can be dangerous. Using the ID would be better in such situations. IIRC there's this `terraform refresh` command that addresses this issue, but I am no expert for that. 

Maybe this is your problem here?

**Comment by anton-sidelnikov** [comment]
Solution: https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/2378#issuecomment-1827783908
