### ISSUE TITLE
vpc - adding secondary CIDR block is not possible

### ISSUE THREAD

**Issue by gekimmel** [opentelekomcloud/terraform-provider-opentelekomcloud#2390]
# Terraform provider version
1.35.14

# Affected Resource(s)
opentelekomcloud_vpc_v1

# Issue
Option to configure a secondary CIDR block is missing. Functionality is available on API level (see https://docs.sc.otc.t-systems.com/virtual-private-cloud/api-ref/api_v3/vpc/adding_a_secondary_cidr_block_to_a_vpc.html) but not for terraform. 

# References
Internal ticket for this feature is OTCPR-5839, ONS-13174.

**Comment by anton-sidelnikov** [comment]
Depends-on: https://github.com/opentelekomcloud/gophertelekomcloud/issues/596

**Comment by anton-sidelnikov** [comment]
Hi @gekimmel, please check on latest version

**Comment by gekimmel** [comment]
Works perfectly for me - thanks a lot!
