### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by Unichron** [opentelekomcloud/terraform-provider-opentelekomcloud#2396]
Hi,

ipv6 is supported across various services (ECS, ELB, VPC, etc...) now but the terraform provider is missing this. When can we expect this to land?

**Comment by anton-sidelnikov** [comment]
Hello @Unichron we will implement ipv6 as soon as possible

**Comment by anton-sidelnikov** [comment]
@Unichron subnet, security group and firewall were updated and now supports ipv6
