### ISSUE TITLE
missing RDS replica size value

### ISSUE THREAD

**Issue by simfeiOTC** [opentelekomcloud/terraform-provider-opentelekomcloud#2402]
Title describes is pretty much. Customer needs the value to edit it via API.

**Comment by artem-lifshits** [comment]
Hello @simfeiOTC we lack the API to manage RDS replica:
https://docs.otc.t-systems.com/relational-database-service/api-ref/api_v3_recommended/db_instance_management/index.html

**Comment by simfeiOTC** [comment]
Hello, we already created a demand for the API. I can inform you once its done.

**Comment by simfeiOTC** [comment]
hello the demand got rejected due to security reasons. so this issue can be closed
