### ISSUE TITLE
No suitable endpoint could be found in the service catalog after terraform apply 

### ISSUE THREAD

**Issue by shitalkumardh** [opentelekomcloud/terraform-provider-opentelekomcloud#2406]
getting below error while terraform apply 
i am using OTC tenant_name, domain_name,auth_url,delegated_project,access_key, secret_key in provider block.

odule.vpc.opentelekomcloud_vpc_v1.MKE-MOCK: Creating...
╷
│ Error: error creating OpenTelekomCloud S3 client: No suitable endpoint could be found in the service catalog.
│ 
│   with opentelekomcloud_s3_bucket.MKE_infra_remote_state_bucket,
│   on main.tf line 28, in resource "opentelekomcloud_s3_bucket" "MKE_infra_remote_state_bucket":
│   28: resource "opentelekomcloud_s3_bucket" "MKE_infra_remote_state_bucket" {
│ 
╵
╷
│ Error: error creating OpenTelekomCloud NetworkingV1 client: No suitable endpoint could be found in the service catalog.
│ 
│   with module.vpc.opentelekomcloud_vpc_v1.MKE-MOCK,
│   on modules/vpc/main.tf line 3, in resource "opentelekomcloud_vpc_v1" "MKE-MOCK":
│    3: resource "opentelekomcloud_vpc_v1" "MKE-MOCK" {
│ 
╵
╷
│ Error: error creating OpenTelekomCloud NetworkingV1 client: No suitable endpoint could be found in the service catalog.
│ 
│   with module.vpc.opentelekomcloud_vpc_v1.MKE-k8s,
│   on modules/vpc/main.tf line 14, in resource "opentelekomcloud_vpc_v1" "MKE-k8s":
│   14: resource "opentelekomcloud_vpc_v1" "MKE-k8s" {
│ 
╵
╷
│ Error: error creating OpenTelekomCloud S3 client: No suitable endpoint could be found in the service catalog.
│ 
│   with module.vpc.opentelekomcloud_s3_bucket.MKE_infra_remote_state_bucket,
│   on modules/vpc/main.tf line 58, in resource "opentelekomcloud_s3_bucket" "MKE_infra_remote_state_bucket":
│   58: resource "opentelekomcloud_s3_bucket" "MKE_infra_remote_state_bucket" {
│

**Comment by anton-sidelnikov** [comment]
Hi @shitalkumardh please try without delegated_project

**Comment by anton-sidelnikov** [comment]
Please reopen issue if still exist
