### ISSUE TITLE
Cannot deserialize WAF certificate

### ISSUE THREAD

**Issue by ionutbucu** [opentelekomcloud/terraform-provider-opentelekomcloud#2412]
# Terraform provider version
Terraform v1.6.6
on linux_386
+ provider registry.terraform.io/hashicorp/local v2.4.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.35.16
# Affected Resource(s)
opentelekomcloud_waf_certificate_v1
# Terraform Configuration Files
```hcl

provider "registry.terraform.io/hashicorp/local" {
  version = "2.4.1"
provider "registry.terraform.io/hashicorp/template" {
  version = "2.2.0"
provider "registry.terraform.io/opentelekomcloud/opentelekomcloud" {
  version     = "1.35.16"
  constraints = ">= 1.35.16"

```

# Debug Output/Panic Output
No Panic.

Error: error retrieving OpenTelekomCloud Waf Certificate: error extracting {"id":"35f1dd919f2a42d29473124630fd74d1","name":"waf_prod_cert_api_1","expireTime":1714694399000,"timestamp":1684172021821} into *certificates.Certificate: json: cannot unmarshal number 1714694399000 into Go struct field Certificate.expireTime of type int
│
│   with module.cceclusterprod.opentelekomcloud_waf_certificate_v1.waf_prod_cert_api[0],
│   on modules/ccecluster/main.tf line 319, in resource "opentelekomcloud_waf_certificate_v1" "waf_prod_cert_api":
│  319: resource "opentelekomcloud_waf_certificate_v1" "waf_prod_cert_api" {
│

# Steps to Reproduce
1. `terraform plan`

# Expected Behavior
The certificate object to be recognized as in the state and not to give an error.

# Actual Behavior
 The expireTime of the certificate could not be parsed.

# Important Factoids
hashicorp/go-tfe v1.36.0
hashicorp/hcl/v2 v2.19.1
hashicorp/terraform-svchost v0.1.1
zclconf/go-cty v1.14.1
Go runtime version: go1.21.5

# References

**Comment by anton-sidelnikov** [comment]
Hi @ionutbucu could you try with opentelekomcloud_waf_dedicated_certificate_v1 resource, import and then check?

**Comment by ionutbucu** [comment]
Hi,
I have a non dedicated WAF but I've tried to import into the state the non dedicated waf certificate into a dedicated one and got the error that the resource does not exists:
----------------------------------------------
While attempting to import an existing object to "module.cceclusterprd.opentelekomcloud_waf_dedicated_certificate_v1.waf_prd_cert_ui[0]", the provider detected that no object exists with the given id. Only pre-existing objects can be imported; check that the id is correct and that it is associated with the
│ provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this resource.
-----------------------------------------------------------------

I changed the certificate resource to opentelekomcloud_waf_dedicated_certificate_v1 and removed the old certificates from the state and then retried the plan operation that succeeded but the apply failed with the following error:
---------------------------------------------------------------------------------
2024-01-17T21:39:55.268+0200 [INFO]  provider.terraform-provider-opentelekomcloud_v1.35.16: 2024/01/17 21:39:55 [DEBUG] OpenTelekomCloud Response Body: {
  "error_code": "WAF.00012005",
  "error_msg": "Unsubscribed WAF service"
}: timestamp="2024-01-17T21:39:55.268+0200"
2024-01-17T21:39:55.268+0200 [ERROR] provider.terraform-provider-opentelekomcloud_v1.35.16: Response contains error diagnostic: @caller=github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_summary="error creating OpenTelekomCloud WAF Dedicated Certificate: Action Forbidden, error message: {\"error_code\":\"WAF.00012005\",\"error_msg\":\"Unsubscribed WAF service\"}" diagnostic_severity=ERROR tf_proto_version=5.3 @module=sdk.proto tf_provider_addr=registry.terraform.io/opentelekomcloud/opentelekomcloud tf_req_id=3da7537f-373f-6b56-eaec-fc168906471b diagnostic_detail="" tf_resource_type=opentelekomcloud_waf_dedicated_certificate_v1 tf_rpc=ApplyResourceChange timestamp="2024-01-17T21:39:55.268+0200"
2024-01-17T21:40:08.991+0200 [ERROR] vertex "module.cceclusterprod.opentelekomcloud_waf_dedicated_certificate_v1.waf_prod_cert_api[0]" error: error creating OpenTelekomCloud WAF Dedicated Certificate: Action Forbidden, error message: {"error_code":"WAF.00012005","error_msg":"Unsubscribed WAF service"}
╷
│ Error: error creating OpenTelekomCloud WAF Dedicated Certificate: Action Forbidden, error message: {"error_code":"WAF.00012005","error_msg":"Unsubscribed WAF service"}
│
│   with module.cceclusterprod.opentelekomcloud_waf_dedicated_certificate_v1.waf_prod_cert_api[0],
│   on modules/ccecluster/main.tf line 319, in resource "opentelekomcloud_waf_dedicated_certificate_v1" "waf_prod_cert_api":
│  319: resource "opentelekomcloud_waf_dedicated_certificate_v1" "waf_prod_cert_api" {
-----------------------------------------------------------------

Thank you

**Comment by anton-sidelnikov** [comment]
Hi @ionutbucu thanks for checking, i will try to fix this issue in opentelekomcloud_waf_certificate_v1 but i can't reproduce issue on my side, but i have some ideas why this was happened

**Comment by ionutbucu** [comment]
Thank you. Maybe the following will help you to reproduce.

The expire date of the certificate is 2/12/24, 5:19:01 PM GMT+2.
The issue happened after upgrading terraform from version v1.0.10 to 1.6.6 and otc provider from 1.35.7 to 1.35.16.
The certificate can be found on the public site https://relax.ferchau.com/.
The certificate is loaded from disk as in the following:
resource "opentelekomcloud_waf_certificate_v1" "waf_prod_cert_api" {
  count = var.waf ? 1 : 0
  name    = "waf_prod_cert_api"
  content = data.local_file.certif-api.content
  key = data.local_file.privatekey-api.content
}
data "local_file" "certif-api" {
    filename = "${path.root}/otc-secrets/${var.certificate_file_api}"
}

**Comment by anton-sidelnikov** [comment]
Hm, @ionutbucu  that strange I'm also cannot reproduce with even certificate, probably issue with local_file datasource, did you try to add content attribute, as described in docs? https://registry.terraform.io/providers/hashicorp/local/latest/docs/resources/file

**Comment by ionutbucu** [comment]
I have the certificate file on the disk, and I want to read it. Using the resource I will create a file but don't want to push the content on GIT if it works like that.
My problem is also that the existing certificate from waf cannot be read on import or during plan.

**Comment by anton-sidelnikov** [comment]
Could you upload somewhere the file and gave me the link? I tried with upload local file, then import, create with raw content, always no errors on apply or plan. Also tried on latest terraform.

**Comment by ionutbucu** [comment]
Here is the file containing the certificate https://drive.google.com/file/d/1jj5fQ4OBS5-7YqHa3zegdPEGoHYL58IQ/view?usp=sharing but the certificate can be exported also from the above web site. It is the whole certificate chain actually because some browsers does not recognize all cert authorities.

**Comment by anton-sidelnikov** [comment]
Hi @ionutbucu please try on latest release

**Comment by ionutbucu** [comment]
Hello,

Thanks a lot. It worked with version 1.36.0.
