### ISSUE TITLE
[IAM] add possibility for managing Security Settings

### ISSUE THREAD

**Issue by david-slr** [opentelekomcloud/terraform-provider-opentelekomcloud#2415]
hello, 

we would like to manage the Security Settings [[OTC API docs](https://docs.otc.t-systems.com/identity-access-management/api-ref/apis/security_settings/index.html#iam-02-0020)]  for our OTC Tenants with Terraform. 
Would this be possible for an future release?

Greetings,
David

**Comment by anton-sidelnikov** [comment]
Depends-On: https://github.com/opentelekomcloud/gophertelekomcloud/issues/615

**Comment by anton-sidelnikov** [comment]
Hi @dampsoft-david several resources were added for managing policies, but use it with care, deleting of resources will return values to default.
