### ISSUE TITLE
[IAM] add abillity for activating MFA on user creation

### ISSUE THREAD

**Issue by david-slr** [opentelekomcloud/terraform-provider-opentelekomcloud#2416]
hello, 

when creating a user on the IAM Console there is a possibility to activate MFA on user creation. 
This Option is missing on the Terraform provider could we get this in a future release? 

Greetings,
David

**Comment by anton-sidelnikov** [comment]
Hi @dampsoft-david this not planned to add in terraform, mfa should managed manually.

**Comment by david-slr** [comment]
to clarify our intentions a bit we don`t want to manage the users MFA, we just want to require the User to enable MFA.

I may have expressed myself in a misleading way the console uses the Term "Login Protection" the API docs should be [this](https://docs.otc.t-systems.com/identity-access-management/api-ref/apis/security_settings/modifying_the_login_protection_configuration_of_a_user.html)

Would this be also out of scope?

**Comment by anton-sidelnikov** [comment]
Oki, close for now will look at this in #2415
