### ISSUE TITLE
`opentelekomcloud_dcs_instance_v1` add `private_ips`

### ISSUE THREAD

**Issue by r-ising** [opentelekomcloud/terraform-provider-opentelekomcloud#2420]
Hello,

you already added private_ips in `rds_instance_v3`, so maybe its a nice idea to have the same option on `opentelekomcloud_dcs_instance_v1`.

I think the api can already handle this:
https://docs.otc.t-systems.com/distributed-cache-service/api-ref/lifecycle_management_apis/creating_a_dcs_instance.html

Thanks

**Comment by r-ising** [comment]
Hi @artem-lifshits,

thanks for adding this feature, but I have a question about that:

Why you added it as a string? in `rds_instance_v3` it's a list of IPs (`private_ips`). For example, if we use the master/slave features, then we need two IPs, or how does it work?

Thanks

**Comment by artem-lifshits** [comment]
@r-ising after several resource runs I've found out that only a single private ip is being digested by backend. Same happens on webUI - you can assign only one private ip.
If you were able to assign several private ips for a single instance please provide the setup.

**Comment by artem-lifshits** [comment]
@r-ising implemented in latest release.
