### ISSUE TITLE
NAT-GW XS is not possible 

### ISSUE THREAD

**Issue by uli-max** [opentelekomcloud/terraform-provider-opentelekomcloud#2422]
# Terraform provider version

1.35.15

# Affected Resource(s)

opentelekomcloud_nat_gateway_v2

# Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
New Service NT-Gateway XS available 

  nat-gateway-spec        = "0"

# Debug Output/Panic Output

╷
│ Error: expected spec to be one of [1 2 3 4], got 0
│ 
│   with opentelekomcloud_nat_gateway_v2.nat_gateway,
│   on tf_B1200_Network_NATGateway.tf line 73, in resource "opentelekomcloud_nat_gateway_v2" "nat_gateway":
│   73:   spec                = local.nat-gateway-spec
│ 
╵

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

Provider should allow "0" to use it for NAT-GW XS

# Actual Behavior

Error Message (see bleow)

# Important Factoids

# References

**Comment by artem-lifshits** [comment]
@uli-max here's statement from documentation for `spec` field:
```
Specifies the NAT gateway type.

The value can be:

1: small type, which supports up to 10,000 SNAT connections.

2: medium type, which supports up to 50,000 SNAT connections.

3: large type, which supports up to 200,000 SNAT connections.

4: extra-large type, which supports up to 1,000,000 SNAT connections.
```
Source:
https://docs.otc.t-systems.com/nat-gateway/api-ref/api_v2.0/nat_gateway_service/creating_a_nat_gateway.html#nat-api-0061

**Comment by uli-max** [comment]
"0" zero is new NAT-Gateway "XS" (extra small) up to 1000 connections available in UI/Console since yesterday evening.

**Comment by anton-sidelnikov** [comment]
Available in latest release

**Comment by uli-max** [comment]
Thanks and already succesful tested! Thanks for the quick support!
