### ISSUE TITLE
OBS - CRR-Replication Rules - Support "Synchronize Deleting Action" 

### ISSUE THREAD

**Issue by uli-max** [opentelekomcloud/terraform-provider-opentelekomcloud#2429]
# Description of the enhancement

For OBS Cross-Region Replication: 
There is an Option "Synchronize Deleting Action" available. 

![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/104261288/80437459-b05a-465e-801c-95ad60c3ab97)

Described in my understanding: 
https://docs.otc.t-systems.com/object-storage-service/api-ref/apis/advanced_bucket_settings/configuring_cross-region_replication_for_a_bucket.html

Table 2 / DeleteData

Please add as Parameter for terraform provider, and add to the provider description.

**Comment by artem-lifshits** [comment]
Implemented in latest release.
