### ISSUE TITLE
Error: Failed to load state: 2 problems:

### ISSUE THREAD

**Issue by shitalkumardh** [opentelekomcloud/terraform-provider-opentelekomcloud#2433]
Hello Team

i am getting issue with while creating terraform backend.
terraform {
  backend "s3" {
    endpoints = { s3 = "https://obs.eu-ch2.sc.otc.t-systems.com" }

    bucket = "mke-rke2-tfstates"
    key    = "kay/tfstate"

    region = "eu-ch2"

    skip_region_validation      = true
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    force_path_style            = true
    #use_path_style              = true
    skip_requesting_account_id = true
  }
}

above code is for creating backend 
once i run terraform init  & terraform init -migrate-state  so  it running and getting message that terraform s3 backend has been initialized successfully, but then i am checking in bucket there is no statefile was created.
when i run terraform apply command then i can see the terraform statefile but i can see the statefile in local as well as in bucket.
when i run terraform show command or plan so getting this error
![123456](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/152484082/218fccb4-8cbc-4683-ad9b-43590bde27c3)

please guys help me out with it.

**Comment by anton-sidelnikov** [comment]
Hi @shitalkumardh Which version of terraform are you using?

**Comment by shitalkumardh** [comment]
i am using Terraform v1.7.2 and OTC opentelekomcloud v1.36.0

**Comment by anton-sidelnikov** [comment]
@shitalkumardh Seems hashicorp breaks s3 init for non-aws clouds, now you must explicitly set ak/sk in backend section:


tested on tf v1.7.0
```
terraform {
  required_version = ">= 1.6.3"

  required_providers {
    opentelekomcloud = {
      source  = "opentelekomcloud/opentelekomcloud"
      version = ">= 1.36.0"
    }
  }
  backend "s3" {
    endpoints = {
      s3 = "https://obs.eu-ch2.sc.otc.t-systems.com/"
    }
    key                         = "terraform_state/test"
    bucket                      = "tf-test-bucket"
    region                      = "eu-de"
    skip_credentials_validation = true
    skip_region_validation      = true
    skip_requesting_account_id  = true
    skip_metadata_api_check     = true
    skip_s3_checksum            = true
    secret_key = "secret"
    access_key = "access"
  }
}
```

**Comment by anton-sidelnikov** [comment]
related issue: https://github.com/hashicorp/terraform/issues/34053
