### ISSUE TITLE
Add "Extreme SSD" as option for data_disk argument in opentelekomcloud_ecs_instance_v1 resource

### ISSUE THREAD

**Issue by TobiWo** [opentelekomcloud/terraform-provider-opentelekomcloud#2437]
The OTC supports storage type called "Extreme SSD" via the UI. However, it is not possible to spawn a respective disk/EVS via terraform. This might be due to it is missing [here](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/7911125c5f04de374dd760941b0bc25d6bcb40fe/opentelekomcloud/services/as/resource_opentelekomcloud_as_configuration_v1.go#L102).

We explicitly need to start an ECS instance with extreme SSD as data_disk type but we only can do this while deploying an ECS and fire up the respective storage manually via the UI. Maybe there is a reason for that but in any way it would be nice if the terraform provider supports teh aforementioned storage type.

For reference, this is where the [data_disk type](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/d9fb843fb1455420e87275e708a439c7b02e9b2c/opentelekomcloud/services/ecs/resource_opentelekomcloud_ecs_instance_v1.go#L146) is defined in the code. Here there is no hard coded type reference but I guess it is referencing the types possible in EVS.

**Comment by artem-lifshits** [comment]
Hello @TobiWo `ESSD` disk type is new and provider documentation isn't updated yet but I still was able to create it in ECS by specifying:

```
  data_disks {
    size = 10
    type = "ESSD"
  }
```

Please provide configuration which doesn't work for you.

**Comment by TobiWo** [comment]
@artem-lifshits Thanks. I will try this out asap.

**Comment by TobiWo** [comment]
@artem-lifshits We just tried to deploy an ecs instance with `ESSD` set in the terraform code but it only deploys "normal" `SSD` :man_shrugging:  :sob: .

**Comment by artem-lifshits** [comment]
@TobiWo please provide configuration you are using.

**Comment by TobiWo** [comment]
@artem-lifshits My fault. We defined a variable with `ESSD` as default and overwrote that with `SSD` by accident. I will test again and give feedback in the next days.

**Comment by artem-lifshits** [comment]
Documentation updated, please reopen the ticket if you still have issues.
