### ISSUE TITLE
ssl_enable not getting set properly after forcing recreate of RDS

### ISSUE THREAD

**Issue by LeonOlbrueck** [opentelekomcloud/terraform-provider-opentelekomcloud#2438]
# Terraform provider version
Terraform v1.7.3-dev
on linux_amd64

# Affected Resource(s)
- opentelekomcloud_rds_instance_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_vpc_v1" "main_1" {
  name                    = var.name
  cidr                    = "10.77.0.0/16"
  shared                  = false
}

resource "opentelekomcloud_vpc_subnet_v1" "db" {
  name                    = var.name
  cidr                    = "10.77.1.0/24"
  vpc_id                  = opentelekomcloud_vpc_v1.main_1.id
  gateway_ip              = "10.77.1.1"
}

resource "opentelekomcloud_networking_secgroup_rule_v2" "rds_ingress" {
  direction         = "ingress"
  ethertype         = "IPv4"
  port_range_min    = 3306
  port_range_max    = 3306
  protocol          = "tcp"
  remote_ip_prefix  = opentelekomcloud_vpc_subnet_v1.cluster.cidr
  security_group_id = opentelekomcloud_networking_secgroup_v2.rds.id
}

resource "opentelekomcloud_networking_secgroup_rule_v2" "rds_ingress_public_testing" {
  direction         = "ingress"
  ethertype         = "IPv4"
  remote_ip_prefix  = "0.0.0.0/0"
  protocol          = "tcp"
  port_range_min    = 3306
  port_range_max    = 3306
  security_group_id = opentelekomcloud_networking_secgroup_v2.rds.id
}

resource "opentelekomcloud_vpc_eip_v1" "db" {
  publicip {
    type = "5_bgp"
    name = "${var.name}-db"
  }
  bandwidth {
    name       = "${var.name}-db"
    size       = 5
    share_type = "PER"
  }
}

resource "opentelekomcloud_rds_instance_v3" "main" {
  name              = "terraform_test_rds_instance"
  availability_zone = ["eu-de-01"]

  security_group_id = opentelekomcloud_networking_secgroup_v2.rds.id
  subnet_id         = opentelekomcloud_vpc_subnet_v1.db.id
  vpc_id            = opentelekomcloud_vpc_v1.main_1.id
  flavor            = "rds.mysql.c2.medium"

  ssl_enable = true
  public_ips = [
    opentelekomcloud_vpc_eip_v1.db.publicip[0].ip_address
  ]

  db {
    password = var.rds_root_pw
    type     = "MySQL"
    version  = "5.7"
    port     = "3306"
  }

  volume {
    type               = "COMMON"
    size               = 40
  }
  backup_strategy {
    start_time = "08:00-09:00"
    keep_days  = var.num_days_rds_keep_backup # 2
  }

  parameters = {
    require_secure_transport = "ON"
  }
}
```

# Debug Output/Panic Output
debug output:
https://gist.githubusercontent.com/lonlonlonlon/2691c27877eeeedebc733478d6fa506d/raw/ee4d4f42cbae178a687fd0bf4e3e752215c591e2/debug_out.log

# Steps to Reproduce
terraform plan -out="./plan"
terraform show -no-color -json plan > plan.json #
terraform apply

1. `terraform plan -out="./plan"`
2. `terraform show -no-color -json plan > plan.json`
3. `terraform apply -auto-approve "./plan"`
4. change the MySQL root pw in var.rds_root_pw
5. `terraform plan -out="./plan"`
6. `terraform show -no-color -json plan > plan.json     # taking a look at the plan ssl_enable is planned to be true for opentelekomcloud_rds_instance_v3.main.`
7. `terraform apply -auto-approve "./plan"`

# Expected Behavior
The old RDS resource gets destroyed, and a new one gets created with ssl_enable set to true.

# Actual Behavior
The old RDS resource gets destroyed, and a new one gets created with ssl_enable set to false (validated via webinterface & connecting to RDS with DataGrip configured to use SSL, prompting errormessage "SSL Connection required, but not provided by server. ").

# Important Factoids
none

# References
none

**Comment by artem-lifshits** [comment]
Hello @LeonOlbrueck fixed in latest release.
