### ISSUE TITLE
[IAM] - Create User not working for Swiss OTC

### ISSUE THREAD

**Issue by uli-max** [opentelekomcloud/terraform-provider-opentelekomcloud#2444]
# Terraform provider version

Terraform v1.5.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/random v3.6.0
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.36.1

# Affected Resource(s)

opentelekomcloud_identity_user_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_identity_user_v3" "iam_user_tapir" {
  name               = local.iam_user_tapir_name
  description        = local.iam_user_tapir_description
  email              = local.iam_user_tapir_email
  # send_welcome_email = "true"
  pwd_reset          = "false"
  lifecycle {
    ignore_changes = [email, password]
  }
}


```

# Debug Output/Panic Output

╷
│ Error: domain name or id missing: list domains failed, err=Resource not found: [GET https://iam-pub.eu-ch2.sc.otc.t-systems.com/auth/domains?name=00000000001000080327], error message: {"error_msg":"The API does not exist or has not been published in the environment","error_code":"APIGW.0101","request_id":"9f96cf6ab11b5fa691f35580d26e52c5"}
│ 
│ 
│   with opentelekomcloud_identity_user_v3.iam_user_tapir,
│   on tf_A4000_IAM_User_tapir.tf line 22, in resource "opentelekomcloud_identity_user_v3" "iam_user_tapir":
│   22: resource "opentelekomcloud_identity_user_v3" "iam_user_tapir" {
│ 
╵

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

Creating the user successfully. 

# Actual Behavior

https://docs.sc.otc.t-systems.com/identity-access-management/api-ref/apis/tenant_management/querying_the_list_of_domains_accessible_to_users.html#en-us-topic-0057845574

GET /v3/auth/domains

Looks that swiss-otc using another Endpoint. 
"v3" is missing. 

# Important Factoids

# References

**Comment by artem-lifshits** [comment]
Hello @uli-max please check that you're using proper `auth_url` with `v3` in the end:
```
https://iam-pub.eu-ch2.sc.otc.t-systems.com/v3
```

**Comment by uli-max** [comment]
Thanks for the hint. 
With:   auth_url    = "https://iam-pub.eu-ch2.sc.otc.t-systems.com/v3"
User Creation works fine. 
You can close this issue.
