### ISSUE TITLE
[ELB] Ability to chose wether to create an application, network or both on a dedicated LB. 

### ISSUE THREAD

**Issue by jorge-cr-13** [opentelekomcloud/terraform-provider-opentelekomcloud#2445]
When creating a Dedicated Elastic Load Balancer through the console it is possible to create either just the application load balancer, the network load balancer or both. It would be nice to have this option with Terraform.

**Comment by anton-sidelnikov** [comment]
Hi @jorge-cr-13 you can do it by specifying only one of l4, l7 flavors (https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/devel/docs/resources/lb_loadbalancer_v3.md)

```
-> If both l4_flavor and l7_flavor is empty, both ALB and NLB will be attached to the load balancer with the default flavor. It is advisable to specify one of them, unless your intention is to associate both flavors with the default setting.

l4_flavor - (Optional) The ID of the Layer-4 flavor.

l7_flavor - (Optional) The ID of the Layer-7 flavor.

```

**Comment by jorge-cr-13** [comment]
Hello @anton-sidelnikov thanks for your quick response. That wasn't so clear to me in the documentation, so thanks for the explanation.
