### ISSUE TITLE
[OBS] Do I really have to re-create the bucket in order to apply the WORM policy?

### ISSUE THREAD

**Issue by cazorla19** [opentelekomcloud/terraform-provider-opentelekomcloud#2446]
Provider version: v1.36.1

I'm trying to introduce the WORM Policy feature, which has been recently released in v1.36.1, to the existing OBS Bucket (also enabling the object versioning), but in the end what I get is the attempt to delete the bucket, because the `worm_policy` parameter forces the resource replacement.

```
Terraform will perform the following actions:
  # opentelekomcloud_obs_bucket.test must be replaced
-/+ resource "opentelekomcloud_obs_bucket" "test" {
      ~ bucket_domain_name = "test.obs.eu-de.otc.t-systems.com" -> (known after apply)
      ~ bucket_version     = "3.0" -> (known after apply)
      ~ id                 = "test" -> (known after apply)
      - parallel_fs        = false -> null
      ~ region             = "eu-de" -> (known after apply)
      ~ versioning         = false -> true
        # (unchanged attributes hidden)
      + worm_policy { # forces replacement
          + years = 100
        }
        # (unchanged blocks hidden)
    }
  # opentelekomcloud_obs_bucket_policy.test-policy must be replaced
-/+ resource "opentelekomcloud_obs_bucket_policy" "test-policy" {
      ~ bucket = "test" -> (known after apply) # forces replacement
      ~ id     = "test" -> (known after apply)
          ...
    }
Plan: 2 to add, 0 to change, 2 to destroy.
```

Looking at the code, I see that the `worm_policy` has `ForceNew` marked, which means that it has been built so in purpose.

https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/7911125c5f04de374dd760941b0bc25d6bcb40fe/opentelekomcloud/services/obs/resource_opentelekomcloud_obs_bucket.go#L88

However, I haven't found any piece of OTC API & Release Notes documentation that describes this topic. Specifically, I haven't found any note which says that you can't add the WORM policy to the existing bucket, and you can add one only to the new buckets that you create at the moment. I thought I could see the note in the provider documentation or in the commit history which can potentially explain this issue.

@artem-lifshits @anton-sidelnikov has this WORM Policy feature built so in purpose, because otherwise there will be an API Error? Did I miss something looking at the API documentation?

**Comment by artem-lifshits** [comment]
It's not possible for existing buckets, here's a note from [documentation](https://docs.otc.t-systems.com/object-storage-service/api-ref/apis/operations_on_buckets/creating_a_bucket.html):
```
You can enable WORM when you create a bucket, but you cannot enable WORM for an existing bucket. 
In a bucket with WORM enabled, you can further configure retention policies for objects you upload to this bucket. 
For more information, see the WORM sections. 
Once enabled, WORM cannot be disabled for a bucket. 
When you create a bucket with WORM enabled, OBS automatically enables versioning for the bucket and the versioning cannot be suspended for that bucket. 
When you create a parallel file system, you cannot enable WORM for it.
```

**Comment by cazorla19** [comment]
gotcha, thanks for the explanation, closing this one
