### ISSUE TITLE
DRS Task: set RDS in AWS as source_db

### ISSUE THREAD

**Issue by deem1978** [opentelekomcloud/terraform-provider-opentelekomcloud#2447]
Hello everybody, 
I am just planing to migrate an RDS hosted in AWS to OTC and I would like to work with your DRS tool and the related Terraform module https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/drs_task_v3
I need to know if it is possible to set as _source_db_ a DB hosted in AWS:

```
  source_db {
    engine_type = "mysql"
```

Thanks in advance.

Best, 
Davide

**Comment by deem1978** [comment]
Another question, if I take a dump of my DB in AWS and store it into an S3 Bucket (in AWS), it is possible with your Terraform module to restore the dump from the S3 to the new RDS in OTC?

Best, 
Davide

**Comment by anton-sidelnikov** [comment]
Hi @deem1978 I didn't see any posibility to import database from another cloud https://docs.otc.t-systems.com/data-replication-service/umn/real-time_migration/to_the_cloud/index.html. This is not about terraform this is api restrictions, about second question you should upload .bak file to our obs and then use drs service for rrds estoration.

**Comment by anton-sidelnikov** [comment]
Please reopen if still have some questions

**Comment by deem1978** [comment]
Thank you very much :)
