### ISSUE TITLE
Argument "value_list_id" in  "opentelekomcloud_waf_dedicated_precise_protection_rule_v1"

### ISSUE THREAD

**Issue by IamThomasB** [opentelekomcloud/terraform-provider-opentelekomcloud#2448]
See documentation:

[https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/waf_dedicated_precise_protection_rule_v1#value_list_id](url)

How can the value for the argument "value_list_id" be determined?

Which resource can be used to generate the reference table of the values in order to subsequently obtain the ID => "value_list_id"?

**Comment by anton-sidelnikov** [comment]
Need to implement new resource `reference_table`, will be available in next release.

**Comment by anton-sidelnikov** [comment]
Done
