### ISSUE TITLE
DNS Public Zone Creation Fail

### ISSUE THREAD

**Issue by jorge-cr-13** [opentelekomcloud/terraform-provider-opentelekomcloud#2449]
# Terraform provider version

Terraform v1.3.7

# Affected Resource(s)

opentelekomcloud_dns_zone_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_dns_zone_v2" "public_zone" {
  name        = var.domain
  description = "Public DNS entries for ${var.domain}."
  email       = var.email
  ttl         = 3600
  type        = "public"
  tags        = var.tags
}
```

# Debug Output/Panic Output

opentelekomcloud_dns_zone_v2.public_zone: Creating...
╷
│ Error: error creating OpenTelekomCloud DNS zone: Internal Server Error
│  {"code":"DNS.0205","message":"No pools available."}
│ 
│   with opentelekomcloud_dns_zone_v2.public_zone,
│   on public_dns.tf line 4, in resource "opentelekomcloud_dns_zone_v2" "public_zone":
│    4: resource "opentelekomcloud_dns_zone_v2" "public_zone" {
│ 
╵

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

Create a public zone in OTC.

# Actual Behavior

Failure. The terraform user has full domain access.

**Comment by anton-sidelnikov** [comment]
Hi @jorge-cr-13 this is swiss cloud issue please ask support team.

**Comment by jorge-cr-13** [comment]
Even if I’m creating the public zone on the eu-nl region?

**Comment by anton-sidelnikov** [comment]
@jorge-cr-13 yep, that strange i will also ask about it, api not works for eu-nl and eu-ch2, seems something was changed.

**Comment by artem-lifshits** [comment]
Hello @jorge-cr-13 it's not a provider issue, here's the error code description from documentation:
![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/55093318/a709b5da-99db-4d58-8219-5b7104fb2d34)
Link: https://docs.otc.t-systems.com/domain-name-service/api-ref/public_parameters/error_code.html#dns-api-80003
