### ISSUE TITLE
CCE | new OS available

### ISSUE THREAD

**Issue by oeotvos** [opentelekomcloud/terraform-provider-opentelekomcloud#2450]
Please add new OS "Huawei Cloud EulerOS 2.0"

The OS is not released yet (in coming weeks), but I'm unable to test it on preprod via tf due to (Error: expected os to be one of [EulerOS 2.5 CentOS 7.7 EulerOS 2.9], got Huawei Cloud EulerOS 2.0)

Thank you

**Comment by vladimirvshivkov** [comment]
We do not support pre-prod cloud env, because it's subject to change.

**Comment by anton-sidelnikov** [comment]
Available in latest release
