### ISSUE TITLE
Bind a user-defined domain name to OBS bucket

### ISSUE THREAD

**Issue by mjromka** [opentelekomcloud/terraform-provider-opentelekomcloud#2454]
Module: OBS

In order to create static web site hosting I need to bind custom domain name to the bucket (as described [here](https://docs.otc.t-systems.com/object-storage-service/umn/obs_console_operation_guide/static_website_hosting/using_a_user-defined_domain_name_to_configure_static_website_hosting.html), see point 5).

Is it possible to do it via Terraform?

**Comment by artem-lifshits** [comment]
Currently it's not possible, I'm going to work on it.

**Comment by artem-lifshits** [comment]
@mjromka feature available in latest release, please check.

**Comment by mjromka** [comment]
> @mjromka feature available in latest release, please check.

Cool, thanks a lot. When will it be published?

**Comment by artem-lifshits** [comment]
@mjromka there was an issue with provider registry, should be available now.

**Comment by mjromka** [comment]
Thanks @artem-lifshits. Works like a charm
