### ISSUE TITLE
OBS - Support "Inventories" feature 

### ISSUE THREAD

**Issue by uli-schneider** [opentelekomcloud/terraform-provider-opentelekomcloud#2456]
# Description of the enhancement
OBS announced the availability of a new feature. 
Please add this to terraform provider. 

https://community.open-telekom-cloud.com/community?id=community_blog&sys_id=299f3ae8133cce10d15ac969a6744183

**Comment by artem-lifshits** [comment]
@uli-schneider looks like API documentation is not available yet, will start working on this feature when it's released.

**Comment by uli-schneider** [comment]
@artem-lifshits : API documentation is released today: 
https://docs.otc.t-systems.com/object-storage-service/api-ref/apis/advanced_bucket_settings/configuring_bucket_inventories.html

**Comment by artem-lifshits** [comment]
Available in latest release.
