### ISSUE TITLE
Support tags for `opentelekomcloud_dcs_instance_v1`

### ISSUE THREAD

**Issue by siebertm** [opentelekomcloud/terraform-provider-opentelekomcloud#2457]
For implementing proper cost control, we'd like to tag all our resources.

Unfortunately, `opentelekomcloud_dcs_instance_v1` does not seem to support tags, blocking us to do so.

Can this be added?

**Comment by anton-sidelnikov** [comment]
Available in latest release

**Comment by siebertm** [comment]
Thanks @anton-sidelnikov !
