### ISSUE TITLE
Hyphens (-) and periods(.) are not permitted in the name attribute of an opentelekomcloud_waf_dedicated_reference_table_v1

### ISSUE THREAD

**Issue by IamThomasB** [opentelekomcloud/terraform-provider-opentelekomcloud#2465]
# Terraform provider version

Terraform v1.7.2
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.36.4

# Affected Resource(s)

opentelekomcloud_waf_dedicated_reference_table_v1

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_waf_dedicated_reference_table_v1" "test_table" {
  name = "test-table.v1"

  type = "url"

  conditions = [
                "/proxy/api/ping",
                "/proxy/api/liveness",
                "/proxy/api/ready"
  ]
}
```

# Debug Output/Panic Output
│ Error: invalid value for name (The name can contains of 1 to 64 characters.Only letters, digits and underscores (_) are allowed.)
│ 
│   with opentelekomcloud_waf_dedicated_reference_table_v1.test_table,
│   on test_ref_table.tf line 2, in resource "opentelekomcloud_waf_dedicated_reference_table_v1" "test_table":
│    2:   name = "test-table.v1"
│ 

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior
Hyphens (-) and periods(.) should be allowed as described in the API doc:

"Reference table name. The value can contain a maximum of 64 characters. Only digits, letters, **hyphens (-)**, underscores (_), and periods (.) are allowed."

https://docs.otc.t-systems.com/web-application-firewall-dedicated/api-ref/apis/rule_management/creating_a_reference_table.html

# References

https://docs.otc.t-systems.com/web-application-firewall-dedicated/api-ref/apis/rule_management/creating_a_reference_table.html

**Comment by artem-lifshits** [comment]
@IamThomasB fixed in latest release.
