### ISSUE TITLE
Add Support for SDRS-Replication and Replicationattchment

### ISSUE THREAD

**Issue by hlange4** [opentelekomcloud/terraform-provider-opentelekomcloud#2469]
# Addition of SDRS Replication and Replication-Attachment
Hi everyone - it would be cool to have the above services included in the opentelekomcloud terraformprovider
Why? As of now one can create a protected instance and a protection group. So far so good:
But if you need to have a disk attached to your protected instance, you cannot achieve it using Terraform.
Therfore I suggest to add the following:

## Replication 
This service represents the replication entity which has to be assigned to a protection group in order to work.
It takes a volume_id and a protection_group_id and starts to replicate the specified volume based on the settings of the protection_group.

#### API Description 
https://docs.otc.t-systems.com/storage-disaster-recovery-service/api-ref/sdrs_apis/replication_pair/index.html
#### Golang SDK 
https://github.com/opentelekomcloud/gophertelekomcloud/tree/devel/openstack/sdrs/v1/replications

-----------------
## Replication-Attachment
In order to assiciate a disk_id with the according protected_instance_id the attachment service has to be used.
The attachment in the end is a sub-service of the protected instance (to which you can attach/detach disks-replication).
I think it becomes clear, if you read the API Doc over here:
#### Attach: 
https://docs.otc.t-systems.com/storage-disaster-recovery-service/api-ref/sdrs_apis/protected_instance/attaching_a_replication_pair_to_a_protected_instance.html

#### Golang SDK 
https://github.com/opentelekomcloud/gophertelekomcloud/tree/devel/openstack/sdrs/v1/attachreplication

**Comment by artem-lifshits** [comment]
@hlange4 added in latest release.

**Comment by hlange4** [comment]
Thanks a lot man 😎
