### ISSUE TITLE
Import of opentelekomcloud_dcs_instance_v1

### ISSUE THREAD

**Issue by niklasweimann** [opentelekomcloud/terraform-provider-opentelekomcloud#2477]
The import documentation for _opentelekomcloud_dcs_instance_v1_ states:

`terraform import opentelekomcloud_dcs_instance_v1.instance instance_name `

but for the import to succeed _instance_name_ needs to be the _instance_id_ of the opentelekomcloud_dcs_instance_v1. (See: [here](https://docs.otc.t-systems.com/distributed-cache-service/api-ref/lifecycle_management_apis/querying_a_dcs_instance.html))

**Comment by anton-sidelnikov** [comment]
Available in latest release
