### ISSUE TITLE
Verify if SNAT still is needed in VPC resource

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud/terraform-provider-opentelekomcloud#2481]
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/vpc_v1

Is SNAT still usable via API?

It clearly says its gone: https://www.open-telekom-cloud.com/en/support/release-notes/vpc-shared-snat-end-of-life

**Comment by anton-sidelnikov** [comment]
Hi @robert1x2, i double checked, seems api didn't changed, it sets and returns the value of shared_snat, but i don't know if shared snat still works or not, please ask support about that.

**Comment by anton-sidelnikov** [comment]
Deprecated
