### ISSUE TITLE
Cipher value not recognized

### ISSUE THREAD

**Issue by ionutbucu** [opentelekomcloud/terraform-provider-opentelekomcloud#2492]
# Terraform provider version
2024-04-29T12:55:04.309+0300 [INFO]  Terraform version: 1.6.6
2024-04-29T12:55:04.309+0300 [INFO]  Go runtime version: go1.21.5
2024-04-29T12:55:04.309+0300 [INFO]  CLI args: []string{"./ci/app/terraform", "-v"}
2024-04-29T12:55:04.310+0300 [INFO]  CLI command args: []string{"version", "-v"}
Terraform v1.6.6
on linux_386
+ provider registry.terraform.io/hashicorp/local v2.4.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.36.0

# Affected Resource(s)
opentelekomcloud_waf_domain_v1

# Terraform Configuration Files
```
resource "opentelekomcloud_waf_domain_v1" "waf_prod_api_domain" {
  count = var.waf ? 1 : 0
  hostname = "*.prime-ing.com"
  server {
    client_protocol = "HTTPS"
    server_protocol = "HTTPS"
    address         = data.opentelekomcloud_vpc_eip_v1.fip_app_live.public_ip_address 
    port            = "443"
  }
  certificate_id  = opentelekomcloud_waf_certificate_v1.waf_prod_cert_api[0].id
  policy_id = opentelekomcloud_waf_policy_v1.waf_prod_policy[0].id
  proxy           = false
  cipher = "сipher_2"
  tls = "TLS v1.2"
  depends_on       = [opentelekomcloud_lb_listener_v2.listener_http]
}
```

# Debug Output/Panic Output
│ Error: expected cipher to be one of [cipher_default cipher_1 cipher_2 cipher_3], got сipher_2
│
│   with module.ccecluster.opentelekomcloud_waf_domain_v1.waf_prod_api_domain,
│   on modules/ccecluster/main.tf line 406, in resource "opentelekomcloud_waf_domain_v1" "waf_prod_api_domain":
│  406:   cipher = "сipher_2"

# Steps to Reproduce
1. `terraform  plan -var-file="./ci/secrets/secret.tfvars" -out=adis-plan03.dat -target=module.cceclusterprod.opentelekomcloud_waf_certificate_v1.waf_prod_cert_api[0] -target=module.cceclusterprod.opentelekomcloud_waf_domain_v1.waf_prod_api_domain[0]`

# Expected Behavior
Changes should be proposed

# Actual Behavior
The cipher value is not recognized.
Error: expected cipher to be one of [cipher_default cipher_1 cipher_2 cipher_3], got сipher_2

# Important Factoids

# References

**Comment by anton-sidelnikov** [comment]
Hi @ionutbucu  you are using old waf resource which need to be deprecated, please use opentelekomcloud_waf_dedicated_domain_v1

**Comment by anton-sidelnikov** [comment]
@ionutbucu anyway just checked, old resource works too please check your atrribute if it contains non-eng symbols (cipher_2) your cipher_2 starts from Cyrillic c
