### ISSUE TITLE
update opentelekomcloud_cts_tracker_v3 documentation

### ISSUE THREAD

**Issue by gekimmel** [opentelekomcloud/terraform-provider-opentelekomcloud#2499]
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cts_tracker_v3 for opentelekomcloud_cts_tracker_v3 mentions v3 availability only for Swisscloud. Since CTS v3 was introduced now in eu-de (https://www.open-telekom-cloud.com/en/support/release-notes/cts-api-v3-available-in-eu-de) please change this warning to something like opentelekomcloud_cts_tracker_v3 is currently not available for eu-nl region.

**Comment by anton-sidelnikov** [comment]
Changed
