### ISSUE TITLE
[IAM] Secuity Settings API Error on create

### ISSUE THREAD

**Issue by david-slr** [opentelekomcloud/terraform-provider-opentelekomcloud#2507]
# Terraform provider version
```
tf providers -v
Terraform v1.8.3
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.36.8

```
# Affected Resource(s)
- opentelekomcloud_identity_login_policy_v3
- opentelekomcloud_identity_password_policy_v3
- opentelekomcloud_identity_protection_policy_v3

# Terraform Configuration Files
```hcl
terraform {
  required_providers {
    opentelekomcloud = {
      source  = "opentelekomcloud/opentelekomcloud"
      version = "~> 1"
    }
  }
}

provider "opentelekomcloud" {
  access_key  = ""
  secret_key  = ""
  domain_name = ""
  tenant_name = "eu-de"
  region      = "eu-de"
  auth_url    = "https://iam.eu-de.otc.t-systems.com/v3"
}

resource "opentelekomcloud_identity_protection_policy_v3" "this" {
  enable_operation_protection_policy = true
}

```

# Debug Output/Panic Output
```
opentelekomcloud_identity_protection_policy_v3.this: Creating...
Error: error updating the IAM operation protection policy: Resource not found: [PUT https://iam.eu-de.otc.t-systems.com/v3.0/OS-SECURITYPOLICY/domains//protect-policy], error message: {"error_msg":"The API does not exist or has not been published in the environment","error_code":"APIGW.0101","request_id":"71d53ba40c3ad62cdea44b5e9ce5996b"}
```

# Steps to Reproduce
1. `terraform init`
2. `terraform apply`

# Expected Behavior
Setting the desired option values

# Actual Behavior
Error

# Important Factoids
Hi, 

we encountered a Problem with using the IAM Security Setting Resources as shown down above. (example only show one resource but all 3 are affected)
If we import the resources before applying everything works as expected, so it seems there is something wrong with the initial creation/importing.

**Comment by artem-lifshits** [comment]
Hello @dampsoft-david I was able to reproduce the issue, it will be fixed on next release.
Until that as a workaround user/password auth can be used.

**Comment by artem-lifshits** [comment]
@dampsoft-david fixed in latest release, please check.

**Comment by david-slr** [comment]
@artem-lifshits thanks for the quick fix. Works for me now with v1.36.9
