### ISSUE TITLE
opentelekomcloud_lb_listener_v2: Issues with ip_group assignment

### ISSUE THREAD

**Issue by pwurbs** [opentelekomcloud/terraform-provider-opentelekomcloud#2510]
# Terraform provider version
v1.36.8

# Affected Resource(s)
opentelekomcloud_lb_listener_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_lb_listener_v2" "listener" {
  name                          = "listener-${var.elb_listener_name}"
  protocol                      = "TCP"
  protocol_port                 = var.elb_listener_port
  loadbalancer_id               = var.elb_id
  transparent_client_ip_enable  = true
  ip_group {
    id   = opentelekomcloud_lb_ipgroup_v3.whitelist.id
    type = "white"
    enable = true
  }
  ip_group {
    id   = opentelekomcloud_lb_ipgroup_v3.blacklist.id
    type = "black"
    enable = true
  }
}

```

# Steps to Reproduce
1. Apply the TF manifest
2. Check the result in OTC
3. Apply a 2nd time

# Expected Behavior
1. According to the TF provider doc, enable = true is default
2. Both ip_groups (whitelist and blacklist) are assigned to the listener

# Actual Behavior
1. I had to set "enable = true" in the TF resource to activate the assignment in the listener
2. After 1st apply, only the first ip_group is assigned to the listener (whitelist). The 2nd ip_group (blacklist) is configured but not assigned to the listsner
3. The 2nd TF apply shows the difference and wants to assign the blacklist again (and again)

**Comment by anton-sidelnikov** [comment]
Hi @pwurbs only one ip_group could be assigned to listener https://docs.otc.t-systems.com/elastic-load-balancing/api-ref/apis_v3/listener/adding_a_listener.html#createlistener

**Comment by niklasweimann** [comment]
I have only one ip_group assigned to the listener. The [dokumentation](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_listener_v2#enable) says that the default value of enabled is true, but when i applied the TF the access control was not enabled in the ui.

**Comment by anton-sidelnikov** [comment]
Hi @niklasweimann this is mistake in doc, we will fix soon

**Comment by pwurbs** [comment]
@anton-sidelnikov You are right. The OTC only supports assigning only either a blacklist or a whitelist. It makes sense...
But the provider should throw an error if someone tries to assign 2 ip_group to the same listener.

**Comment by anton-sidelnikov** [comment]
@pwurbs i will add restriction to one element in next release
