### ISSUE TITLE
CTS - v3 - Add new features for "eu-de"

### ISSUE THREAD

**Issue by uli-schneider** [opentelekomcloud/terraform-provider-opentelekomcloud#2511]
# Description of the enhancement
Dears,

CTS-v3 API in region eu-de offers new functionality.
Please add them to the terraform provider and provider-description.
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cts_tracker_v3 

![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/156002757/30cd9c86-b6d8-4c28-b973-21ed305ab4d1)

pls. see https://docs.otc.t-systems.com/cloud-trace-service/api-ref/v3_apis_recommended/tracker_management/creating_a_tracker.html
Table 3. 

![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/156002757/666099e0-ab78-4289-8c5a-77561639b63d)

**Comment by artem-lifshits** [comment]
Features added in latest release.
