### ISSUE TITLE
opentelekomcloud_dc_virtual_gateway_v2 fails to add IPv6 endpoint group

### ISSUE THREAD

**Issue by brunoagueda** [opentelekomcloud/terraform-provider-opentelekomcloud#2516]
# Terraform provider version

Terraform v1.8.3
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.36.9

# Affected Resource(s)

opentelekomcloud_dc_virtual_gateway_v2

# Terraform Configuration Files
```hcl
data "opentelekomcloud_vpc_v1" "vpc" {
  name   = "default-testing"
}

resource "opentelekomcloud_dc_virtual_gateway_v2" "vgw_1" { 
  vpc_id      = data.opentelekomcloud_vpc_v1.vpc.id
  name        = "test-vgw-uan-mgmt1"
  local_ep_group {
    name        = "test-vgw-uan-mgmt1"
    endpoints   = ["xxxx:xxxx:x:xxxx::/64"]
  }
}
```

# Debug Output/Panic Output

https://gist.github.com/brunoagueda/ffa9456b73d11b8f63f7302cf407e4bc

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

A virtual gateway with an IPv6 endpoint group should be created

# Actual Behavior

It fails with error "invalid Endpoints for address family ipv4"

# Important Factoids

IPv6 endpoint groups are available both on the console and API, probably there is a validation on the TF module that is blocking IPv6 endpoint group creation. The local_ep_group block should be dynamic, so we can create both IPv4 and IPv6 endpoint groups. I opened this issue as a bug report, but since the IPv6 feature is relatively new for the virtual gateway you can change to enhancement request if you see fit.

# References

**Comment by artem-lifshits** [comment]
IPV6 support added in latest release.

**Comment by brunoagueda** [comment]
Hi. I tested the new release and it works to deploy a virtual gateway with IPV6 addresses as local endpoint group, but I cannot deploy a gateway with both IPV4 and IPV6 endpoint groups. The updated documentation states: "IPv4 and IPv6 CIDRs endpoints should be assigned in separate resources", but I didn't understand how this would work. I cannot create another opentelekomcloud_dc_virtual_gateway_v2 resource for the same VPC. Could you please explain how this works or give an example?

**Comment by artem-lifshits** [comment]
@brunoagueda in latest release IPV4 and IPV6 addresses are separated in 2 different parameters and both can be provided, please check.

**Comment by brunoagueda** [comment]
I just checked and it is working, thank you very much!
I will close this issue
