### ISSUE TITLE
Changing a DB Instance Type from Single to Primary/Standby

### ISSUE THREAD

**Issue by deem1978** [opentelekomcloud/terraform-provider-opentelekomcloud#2518]
Hello everybody, 
I have just stumbled on this article from the official OTC documentation https://docs.otc.t-systems.com/relational-database-service/umn/working_with_rds_for_postgresql/instance_modifications/changing_a_db_instance_type_from_single_to_primary_standby.html#rds-pg-05-0023 and I am would like to ask if there is the same possibility with terraform too.
I mean as far as I know in order to get an HA setup, a particular instance type ending by "*.ha" has to be defined and I am pretty sure that if I change my terraform code in order to use e.g. the "rds.pg.s1.large.ha" instance type, then the current setup will be destroyed and then a new one with the new instance type will be created. Am I right or am I missing something?

Thank you
Davide

**Comment by artem-lifshits** [comment]
Hello @deem1978 you're right, this change will lead to inconsistencies between state and configuration.
If you want to change the type of existing RDS instance I suggest manually changing it in UI and then importing in tf via `terraform import`.

**Comment by deem1978** [comment]
Hello @artem-lifshits thank you very much for the info.
