### ISSUE TITLE
Support creating IAM policies with NotAction

### ISSUE THREAD

**Issue by bascht** [opentelekomcloud/terraform-provider-opentelekomcloud#2519]
# Description of the enhancement

When testing with the Console JSON builder and checking the documentation, e.g.:

https://docs.otc.t-systems.com/object-storage-service/permissions-configuration-guide/appendix/bucket_policy_parameters.html#obs-40-0041-en-us-topic-0118394684-section1623516525350

OTC does support negating IAM policy statements like `NotAction` e.g. to only allow access to a certain set of actions. This policy is valid in the JSON builder:

```json
{
    "Version": "1.1",
    "Statement": [
        {
            "Effect": "Deny",
            "NotAction": [
                "iam:groups:listGroupsForUser",
                "iam:credentials:listCredentials",
                "iam:mfa:deleteVirtualMFADevice",
                "iam:roles:listRoles",
                "iam:mfa:listVirtualMFADevices",
                "iam:mfa:bindMFADevice",
                "iam:mfa:getVirtualMFADevice",
                "iam:users:getUser",
                "iam:mfa:createVirtualMFADevice",
                "iam:credentials:getCredential"
            ],
            "Condition": {
                "Bool": {
                    "g:MFAPresent": [
                        "false"
                    ]
                }
            }
        }
    ]
}
```

yet I cannot describe it in a `opentelekomcloud_identity_role_v3` resource, like:

```hcl
statement {
  effect = "Deny"
  notaction = [
    "iam:groups:listGroupsForUser",
    "iam:credentials:listCredentials",
    "iam:mfa:deleteVirtualMFADevice",
    "iam:roles:listRoles",
    "iam:mfa:listVirtualMFADevices",
    "iam:mfa:bindMFADevice",
    "iam:mfa:getVirtualMFADevice",
    "iam:users:getUser",
    "iam:mfa:createVirtualMFADevice",
    "iam:credentials:getCredential"
  ]
}
```

Since it will only accept `action`s:

```
│ Error: Unsupported argument
│ 
│   on opentelekomcloud.tf line 250, in resource "opentelekomcloud_identity_role_v3" "enforce_mfa":
│  250:     notaction = [
│ 
│ An argument named "notaction" is not expected here.
```

I suppose this isn't a quick feature to implement but it would be really nice to have. :angel:

**Comment by artem-lifshits** [comment]
Hello @bascht API documentation is not updated yet:
https://docs.otc.t-systems.com/identity-access-management/api-ref/apis/custom_policy_management/creating_a_custom_policy.html

I will work on enhancement when documentation is updated.

**Comment by bascht** [comment]
@artem-lifshits I see, thanks for the update! :+1:

**Comment by artem-lifshits** [comment]
@bascht I think IAM and bucket policies are mixed here.
`NotAction` can be provided to `opentelekomcloud_obs_bucket_policy` resource specifically for OBS buckets.

**Comment by bascht** [comment]
@artem-lifshits I just linked to the bucket policies since it was the only place where I found `NotAction`, but I don't think I'm mixing up bucket and IAM policies.

The code snippet from above is an actual IAM policy that we can apply without any issues via the OTC console:

![Screenshot-2024-06-13-130722](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/51264/13410842-ef05-42dc-9f7b-48eb3e203802)

We specifically *want* this to be an IAM policy instead of individual bucket policies.

**Comment by artem-lifshits** [comment]
@bascht please open a customer support ticket with a demand to update documentation / feature description for IAM regarding `NotAction`.
There're lots and lots of undocumented features for IAM service specifically that we can implement but it can be changed from API side without any notice and terraform provider will be broken.
