### ISSUE TITLE
[REQUEST] CSS - Cloud Search Service

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#252]
Hi there,

Since february OTC released the CSS Service with underlaying Elasticsearch.

See here:
https://docs.otc.t-systems.com/en-us/api/css/css_03_0019.html

**Comment by niuzhenguo** [comment]
https://github.com/terraform-providers/terraform-provider-opentelekomcloud/pull/255
