### ISSUE TITLE
CCE: Nodepool Taints can not contain Subdomain in Key

### ISSUE THREAD

**Issue by lestich** [opentelekomcloud/terraform-provider-opentelekomcloud#2520]
# Terraform provider version
opentelekomcloud provider: 1.36.9
terraform: v1.6.2

# Affected Resource(s)
- opentelekomcloud_cce_node_pool_v3

# Terraform Configuration Files
```
resource "opentelekomcloud_cce_node_pool_v3" "nodes" {
  cluster_id         = opentelekomcloud_cce_cluster_v3.cluster.id
  name               = "foo"
  os                 = "EulerOS 2.9"
  flavor             = "s2.xlarge.2"
  initial_node_count = 2
  availability_zone  = "random"

  scale_enable             = true
  min_node_count           = 0
  max_node_count           = 2
  scale_down_cooldown_time = 100
  runtime                  = "containerd"

  root_volume {
    size       = 100
    volumetype = SSD
  }
  data_volumes {
    size       = 100
    volumetype = SSD
  }
 
  taints {
        effect = "NoSchedule"
        key    = "example.com/node"
        value  = "infra"
    }

}
```

# Debug Output/Panic Output
Error: invalid value for taints.0.key (Invalid key. Cluster pool taint key is 1 to 63 characters starting with a letter or digit. Only lowercase letters, digits, and hyphens (-) are allowed.)

# Steps to Reproduce
try to set a taint key with a subdomain e.g. example.com/nodes

# Expected Behavior
According to the documentation subdomains should be working. Taints with "/" can be set via the otc ui as well.

Reference: 
- https://kubernetes.io/docs/reference/kubectl/generated/kubectl_taint/#synopsis
- https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cce_node_pool_v3#key

# Actual Behavior
terraform error (see above)

# Important Factoids
-

# References

**Comment by anton-sidelnikov** [comment]
Please check on latest
