### ISSUE TITLE
CCE: Addon Configuration does not allow list

### ISSUE THREAD

**Issue by lestich** [opentelekomcloud/terraform-provider-opentelekomcloud#2521]
# Terraform provider version
opentelekomcloud provider: 1.36.9
terraform: v1.6.2

# Affected Resource(s)
- opentelekomcloud_cce_addon_v3

# Terraform Configuration Files
```
data "opentelekomcloud_cce_addon_templates_v3" "corednstpl" {
  cluster_version = opentelekomcloud_cce_cluster_v3.cluster.cluster_version
  addon_name      = "coredns"
}

data "opentelekomcloud_cce_addon_template_v3" "coredns" {
  addon_version = "1.28.4"
  addon_name    = data.opentelekomcloud_cce_addon_templates_v3.corednstpl.addon_name
}

resource "opentelekomcloud_cce_addon_v3" "coredns" {
  template_name    = data.opentelekomcloud_cce_addon_template_v3.coredns.addon_name
  template_version = data.opentelekomcloud_cce_addon_template_v3.coredns.addon_version
  cluster_id       = opentelekomcloud_cce_cluster_v3.cluster.id

  values {
    basic = {
      cluster_ip    = data.opentelekomcloud_cce_addon_template_v3.coredns.cluster_ip,
      image_version = data.opentelekomcloud_cce_addon_template_v3.coredns.image_version
      swr_addr      = data.opentelekomcloud_cce_addon_template_v3.coredns.swr_addr,
      swr_user      = data.opentelekomcloud_cce_addon_template_v3.coredns.swr_user
      ipv6          = false
    }
    custom = {
      "upstream_nameservers" = jsonencode(["0.0.0.0", "8.8.8.8"])
    }
  }
}
```

# Debug Output/Panic Output
Internal Server Error

# Steps to Reproduce
insert list under "upstream_nameservers" key in coredns custom config (as expected by the api)

# Expected Behavior
upstream nameservers should work (they do work over the otc ui)

# Actual Behavior
internal server error from the api. Terraform cannot be applied (no local terraform validation error)

# Important Factoids
There seems to be an error with the following function:

https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/devel/opentelekomcloud/services/cce/resource_opentelekomcloud_cce_addon_v3.go#L287 

json unmarshalling of a list is not handled (+ no error handling at all)

Tests were written for stub_domains but not for upstream_nameservers see https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/commit/357c461e811b9ea152cc22f34008612d40cf9d74#diff-4b4aba94611500695d8bac9394458c5284fcd2be6971d06cba5c4bd6fea66982R392

**Comment by anton-sidelnikov** [comment]
Hi @lestich, you can pass this values as `"upstream_nameservers": "[\"8.8.8.8\",\"8.8.4.4\"]"`, values accepts only string values, i will add example

**Comment by anton-sidelnikov** [comment]
Hi @lestich, please check on latest
