### ISSUE TITLE
Data Source for opentelekomcloud_networking_vip_v2

### ISSUE THREAD

**Issue by Starimmigrant** [opentelekomcloud/terraform-provider-opentelekomcloud#2526]
# Description of the enhancement
Hi,

I'm trying to create a new VIP in a different project (Project B) and need to retrieve the ID of the opentelekomcloud_networking_vip_v2 resource to my current project (Project A) to associate the VIP with a port I'm creating in Project A.

However, I couldn't find an available data source to pull information from a opentelekomcloud_networking_vip_v2 resource. As a workaround, I'm currently pulling the state of Project B and retrieving the ID via configured outputs.

If such a data source does not currently exist, I suggest adding one in a future update. This feature would be very helpful for managing resources across different projects.

Thank you for your attention.

### Affected Resource(s)
opentelekomcloud_networking_vip_v2

**Comment by artem-lifshits** [comment]
Hello @Starimmigrant you can use `data_source/networking_port_v2` to get port information.

**Comment by Starimmigrant** [comment]
Hi @artem-lifshits, thanks for your answer, but sadly this doesn't work. Because I need the ID of the virtual IP to associate it with the port.

In Project A I'm creating the resource opentelekomcloud_networking_vip_associate_v2 . The resource needs the vip_ip and the port_id. This is the step where I need the vip_id from Project B. The port isn't yet associated with the VIP. That's why I can't use this data source, like you recommended.

**Comment by artem-lifshits** [comment]
@Starimmigrant oh I see will sort it on next release.

**Comment by artem-lifshits** [comment]
@Starimmigrant I've tried creating `networking_vip_v2` and `data_source/networking_port_v2`.
`id` in `networking_vip_v2` should be identical to `data_source/networking_port_v2`. So if you create `networking_vip_v2` with unique name you should be able to get vip info by using port data source (while specifying name).

**Comment by Starimmigrant** [comment]
It does indeed work with the networking_port_v2 data source, even though I don't really understand why. 
With that I can get the id and also ip_address, which makes stuff much easier for me. 
@artem-lifshits Thank you very much for your help!

The documentation should be updated accordingly for anybody else finding themselves in the same situation. @artem-lifshits Do I open a new issue or should I leave this one open until the documentation is updated?

**Comment by artem-lifshits** [comment]
@Starimmigrant good point, I will update the docu.
Let's leave issue opened for now.

**Comment by artem-lifshits** [comment]
Documentation updated and available in latest release.
