### ISSUE TITLE
CCE - Add parameter "Disk Encryption for Master Nodes" 

### ISSUE THREAD

**Issue by uli-schneider** [opentelekomcloud/terraform-provider-opentelekomcloud#2528]
# Description of the enhancement

Please add new parameter incl. Documentation to tf-provider:
  
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cce_cluster_v3

Screenshot UI: 
![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/156002757/2bad76b0-4e97-46d0-8efa-d14b0e48861d)

https://docs.otc.t-systems.com/cloud-container-engine/api-ref/apis/cluster_management/creating_a_cluster.html
(Table 5) 
![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/156002757/ff668402-e20d-4909-866e-c27d9f470b4c)

**Comment by artem-lifshits** [comment]
Feature available in latest release.
