### ISSUE TITLE
CCE - Add parameter "CPU management policy"

### ISSUE THREAD

**Issue by uli-schneider** [opentelekomcloud/terraform-provider-opentelekomcloud#2531]
# Description of the enhancement
Please add new parameter incl. Documentation to tf-provider:

https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cce_cluster_v3

Screenshot UI:
![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/156002757/ffe064cc-e94e-4404-8a51-dd1a873fd171)

https://docs.otc.t-systems.com/cloud-container-engine/api-ref/apis/cluster_management/creating_a_cluster.html
(Table 13) 
![image](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/156002757/4585af73-79eb-424a-92fd-c77e9964763c)

**Comment by artem-lifshits** [comment]
@uli-schneider this parameter can already be provided to `extend_param` argument.
