### ISSUE TITLE
Issue creating Image via Terraform / type missing

### ISSUE THREAD

**Issue by simfeiOTC** [opentelekomcloud/terraform-provider-opentelekomcloud#2544]
<img width="1178" alt="INC04960431" src="https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/155572270/031f8de5-78a3-4724-a209-7d8320646f1a">
<img width="718" alt="INC04960431_3" src="https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/155572270/11897132-e3f1-4e94-8e0f-3955af2dff20">

# Affected Resource(s)

Please list the resources as a list, for example:
- opentelekomcloud_ims_image_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_ims_image_v2" "ocp_iso_file" {
  name        = "test"
  image_url   = "otc-obs:fa71928b-7541-42ec-9201-d2f3b0a9a297-discovery.iso"
  os_version  = "Red Hat Linux Enterprise 8.0 64bit"
  type        = "ECS"
  min_disk    = 100
  description = "Create an image using a file in the OBS bucket."
}

resource "opentelekomcloud_ecs_instance_v1" "server" {
  name              = "server"
  image_id          = opentelekomcloud_ims_image_v2.ocp_iso_file.id
  flavor            = "s2.2xlarge.2"
  vpc_id            = opentelekomcloud_vpc_v1.vpc2.id
  availability_zone = "eu-de-01"

  nics {
    network_id = var.subnet2
    ip_address = "10.103.205.10"
  }
```

# Important Factoids

We have been trying to create a private image with an ISO disk file which was uploaded to a bucket.

The error we encounter is "os type is invalid" although we tried different variations for the os_version parameter and also tried to create the resources without this parameter. 

In addition to that, based on the documentation below the image type must be "IsoImage", however, terraform doesn't accept this type of image.

We would much appreciate it if you could please let us know whether it is possible to create private iso images and ECS with those images in terraform. 

After testing it we found out that this is unfortunately not possible.

Thank you for any help you can provide.

**Comment by artem-lifshits** [comment]
@simfeiOTC fixed in latest release.

**Comment by simfeiOTC** [comment]
hello @artem-lifshits customer tried again and it didn`t work with IsoImage as you see in  those screenshots:
<img width="629" alt="screen" src="https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/155572270/d3f863ed-03ed-487b-8a9b-23869878bfe9">
<img width="1057" alt="screen2" src="https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/155572270/899b9288-cad4-4c43-8682-9993a8848eec">

could you please check again? here the code:

resource "opentelekomcloud_ims_image_v2" "ocp_iso_file2" {
name = "test"
image_url = "test1306:11213a25-c256-49da-9350-8fdf69c17dca-discovery.iso"
os_version = "Red Hat Linux Enterprise 9.1 64bit"
type = "IsoImage"
min_disk = "100"
description = "Create an image using a file in the OBS bucket."
}

resource "opentelekomcloud_ecs_instance_v1" "server1" {
name = "server"
image_id = opentelekomcloud_ims_image_v2.ocp_iso_file2.id
flavor = "s2.2xlarge.2"
vpc_id = opentelekomcloud_vpc_v1.vpc2.id
availability_zone = "eu-de-01"

nics {
network_id = var.subnet2
ip_address = "10.103.205.10"
}
}

**Comment by artem-lifshits** [comment]
Hello @simfeiOTC the initial error was related to provider validation. This error is related to the API itself.
Parameter `type` is optional so customer can try and remove it completely. If it doesn't work I suggest contacting compute squad and ask them if `IsoImage` works at all.
