### ISSUE TITLE
How to attach a VPC subnet to a opentelekomcloud_compute_instance_v2

### ISSUE THREAD

**Issue by dschemp** [opentelekomcloud/terraform-provider-opentelekomcloud#2547]
From the docs it is not clear at all how I would go on about attaching VPC subnets to a opentelekomcloud_compute_instance_v2 resource.
The docs use a network block which only uses a name string as a parameter. What does that map to in other TF (data) resources or the management UI?
When creating an ECS instance on the management UI you clearly select a VPC und a subnet. Would be nice to have that as an example here too.

**Comment by anton-sidelnikov** [comment]
Hi @dschemp,
it requires network_id, you can obtain this parameter from subnet
example:
```
resource "opentelekomcloud_compute_instance_v2" "instance_1" {
  name              = "instance_1"
  availability_zone = "az"
  image_name        = "Standard_Debian_10_latest"
  metadata = {
    foo = "bar"
  }
  network {
    uuid = data.opentelekomcloud_vpc_subnet_v1.shared_subnet.network_id
  }

  tags = {
    muh = "value-create"
    kuh = "value-create"
    emp = ""
  }
}
```

**Comment by dschemp** [comment]
Yep, thank you. It worked. Could you add this as a comprehensive example to the docs please?

**Comment by anton-sidelnikov** [comment]
Example added in latest version
