### ISSUE TITLE
How to get the Image name / id for a Compute Instance v2

### ISSUE THREAD

**Issue by dschemp** [opentelekomcloud/terraform-provider-opentelekomcloud#2548]
`opentelekomcloud_compute_instance_v2` does reference and explain the parameters `image_name` and `image_id` briefly but it is not clear how to get to those values.
Examples showing real world values that can be inserted would be nice. Maybe including how to list / get all available images. (Hetzner for example offers a CLI tool allowing to list all available image options; some list would be nice).

**Comment by anton-sidelnikov** [comment]
Hi @dschemp,
there data-source called: opentelekomcloud_images_image_v2
https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/devel/docs/data-sources/images_image_v2.md
from it you can obtain image by different parameters, example:
```
data "opentelekomcloud_images_image_v2" "image_1" {
  name_regex  = "^Standard_Debian.+"
  most_recent = true
  visibility  = "public"
}
```

**Comment by dschemp** [comment]
Hmm, this is only partially helpful as I don't know, where to even start. How do I know how the images are called? That is my primary issue.

**Comment by anton-sidelnikov** [comment]
Hi @dschemp please start with the API documentation and user guides; they will help you understand the system better. You could also ask our customer support team.
https://docs.otc.t-systems.com/image-management-service/api-ref/
Console -> Image Management Service -> public images list

**Comment by anton-sidelnikov** [comment]
If you have additional questions please left it in #2547, close this as related issue.
