### ISSUE TITLE
Choosing a flavor when Creating VPC EP 

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#2555]
# Description of the enhancement

The terraform provider https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/vpcep_endpoint_v1 

does not support creating VPC EP with custom flavor.

We kindly ask to add such ability to this resource. We would like to create VPC EP with a flavor that is custom for our project which is vpcep.specialv2.obs

**Comment by artem-lifshits** [comment]
Hello @CHS-OTC what do you mean by flavor?
If you want to use a specific public service you should first use `data_source/opentelekomcloud_vpcep_public_service_v1` to get its `id` and then provide it to vpcep resource.

**Comment by CHS-OTC** [comment]
Customer feedback (from Jira):
"If you create a new VPC Endpoint, please contact us and we can adjust the specifications from our Backend side."

This is to the contrary of what had been said during our meeting with the T-System engineers whom said that the different flavors for the VPC EP can be set by us via API. Those flavors means bigger connections limits but that's all I know since we could not made this change via API nor we get how to that.

**Comment by artem-lifshits** [comment]
There is no `flavor` parameter in the official documentation:
https://docs.otc.t-systems.com/vpc-endpoint/api-ref/apis/apis_for_managing_vpc_endpoints/creating_a_vpc_endpoint.html#vpcep-06-0303

Moreover WEBUI API doesn't have `flavor` field either, here's an example of request body for VPCEP creation:

![Screenshot 2024-06-28 at 12 10 05](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/55093318/09523365-bf57-468a-80ba-6d74b5c423e8)

So unless API is updated we can't do anything from provider side, we use the API that is provided on doc portal.
And until that I guess the only way to change `flavor` is to contact operations team and ask them to change flavor directly.
