### ISSUE TITLE
Missing parameters for opentelekomcloud_cce_node_pool_v3

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#2557]
# Terraform provider version
v1.36.12

# Affected Resource(s)
opentelekomcloud_cce_node_pool_v3

# Details
Hello, we noticed an issue with autoscaling when an limit for ephemeral-storage is set in a deployment that should be deployed in a nodepool that has been created with 0 inital nodes via TF. The autoscaler pod is running in a different nodepool. The autoscaler is failing to scale out with the error: "predicate checking error: Insufficient ephemeral-storage; predicateName=NodeResourcesFit; reasons: Insufficient ephemeral-storage;"

For nodepools created via GUI with 0 inital nodes the autoscaler is able to correctly scale out and create a new node.

The difference is that via GUI storage/StorageSelectors/StorageGroups are added as a parameter to the nodepool creation request. 
If these parameters are also added for an API creation call, it also works.
https://docs.otc.t-systems.com/cloud-container-engine/api-ref/apis/cluster_management/creating_a_node_pool.html

There parameters are currently missing from the terraform provider.

Here is an example from a nodepool API request to create a workpool with all parameters set.

"nodeTemplate":{
    "az": "eu-de-03",
    "count": 1,
    "dataVolumes": [
        {
            "metadata": {
                "__system__cmkid": "REDACTED_CMK_ID",
                "__system__encrypted": "1"
            },
            "size": 100,
            "volumetype": "SATA"
        }
    ],
    "storage": {
        "storageSelectors": [
            {
                "name": "cceUse",
                "storageType": "evs",
                "matchLabels": {
                    "size": "100",
                    "volumeType": "SATA",
                    "count": "1",
                    "metadataEncrypted": "1",
                    "metadataCmkid": "REDACTED_CMK_ID"
                }
            }
        ],
        "storageGroups": [
            {
                "name": "vgpaas",
                "selectorNames": [
                    "cceUse"
                ],
                "cceManaged": true,
                "virtualSpaces": [
                    {
                        "name": "runtime",
                        "size": "90%"
                    },
                    {
                        "name": "kubernetes",
                        "size": "10%"
                    }
                ]
            }
        ]
    },
    "extendParam": {},
    "flavor": "c3.2xlarge.2",
    "login": {
        "sshKey": "REDACTED_KEY_PAIR",
        "userPassword": {
            "password": "",
            "username": ""
        }
    },
    "nodeNicSpec": {
        "primaryNic": {}
    },
    "os": "EulerOS 2.9",
    "publicIP": {
        "eip": {
            "bandwidth": {}
        }
    },
    "rootVolume": {
        "metadata": {
            "__system__cmkid": "REDACTED_CMK_ID",
            "__system__encrypted": "1"
        },
        "size": 40,
        "volumetype": "SATA"
    },
    "runtime": {
        "name": "containerd"
    }
}

The storage / storageSelectors / storageGroups part can currently not be set via TF.
If the nodepool is currently created via TF these parameters are just not present in the API request.
For most cases this work fine but there is a case with the autoscale where these are needed. 

# Expected Behavior
To be able to confgure storage / storageSelectors / storageGroups via TF or be automatically added to the terraform API call to the OTC.
It seems to be only used for the ratio of the disk allocation between runtime and kubernetes.

Here is the function in the GUI:
![2024-06-19 11_32_40-Cloud Container Engine - Console](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/79697776/23e9afea-f0e4-4026-8a53-8d0be790fd7d)

So propably it only needs to be possible to set the ratio via terraform. The other information could propably be generated by terraform automatically.

# References
https://docs.otc.t-systems.com/cloud-container-engine/api-ref/apis/cluster_management/creating_a_node_pool.html
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cce_node_pool_v3

**Comment by artem-lifshits** [comment]
Parameter added in latest release.
