### ISSUE TITLE
Change ip_type for Dedicated ELB Documentation / lb_loadbalancer_v3

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#2558]
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_loadbalancer_v3

Hi,
in some of the examples on the page there is still the ip type "5_gray" mentioned.
Please replace all instances of "5_gray" to "5_bgp" as "5_gray" is not used anymore for dedicated ELB and might even error when used during DELB creation.

**Comment by anton-sidelnikov** [comment]
Documentation updated
