### ISSUE TITLE
CCE - Addon / Change of "flavor not possible"  

### ISSUE THREAD

**Issue by uli-schneider** [opentelekomcloud/terraform-provider-opentelekomcloud#2560]
# Terraform provider version

Terraform v1.5.4
on darwin_arm64
+ provider registry.terraform.io/hashicorp/random v3.6.2
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.36.12

Your version of Terraform is out of date! The latest version
is 1.8.5. You can update by downloading from https://www.terraform.io/downloads.html

# Affected Resource(s)

https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cce_addon_v3

# Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

Using your sample, from provider description.
resource "opentelekomcloud_cce_addon_v3" "autoscaler" {
  template_name    = data.opentelekomcloud_cce_addon_template_v3.autoscaler.addon_name
  template_version = data.opentelekomcloud_cce_addon_template_v3.autoscaler.addon_version
  cluster_id       = opentelekomcloud_cce_cluster_v3.cluster_1.id

  values {
    basic = {
      "cceEndpoint" = "https://cce.${var.region_name}.otc.t-systems.com"
      "ecsEndpoint" = "https://ecs.${var.region_name}.otc.t-systems.com"
      "region"      = var.region_name
      "swr_addr"    = data.opentelekomcloud_cce_addon_template_v3.autoscaler.swr_addr
      "swr_user"    = data.opentelekomcloud_cce_addon_template_v3.autoscaler.swr_user
    }
    custom = {
      "cluster_id"                     = opentelekomcloud_cce_cluster_v3.cluster_1.id
      "coresTotal"                     = 32000
      "expander"                       = "priority"
      "logLevel"                       = 4
      "maxEmptyBulkDeleteFlag"         = 10
      "maxNodeProvisionTime"           = 15
      "maxNodesTotal"                  = 1000
      "memoryTotal"                    = 128000
      "scaleDownDelayAfterAdd"         = 10
      "scaleDownDelayAfterDelete"      = 11
      "scaleDownDelayAfterFailure"     = 3
      "scaleDownEnabled"               = true
      "scaleDownUnneededTime"          = 10
      "scaleDownUtilizationThreshold"  = 0.5
      "scaleUpCpuUtilizationThreshold" = 1
      "scaleUpMemUtilizationThreshold" = 1
      "scaleUpUnscheduledPodEnabled"   = true
      "scaleUpUtilizationEnabled"      = true
      "tenant_id"                      = data.opentelekomcloud_identity_project_v3.this.id
      "unremovableNodeRecheckTimeout"  = 5
    }
    flavor = <<EOF
      {
        "description": "Has only one instance",
        "name": "Single",
        "replicas": 1,
        "resources": [
          {
            "limitsCpu": "1000m",
            "limitsMem": "1000Mi",
            "name": "autoscaler",
            "requestsCpu": "500m",
            "requestsMem": "500Mi"
          }
        ]
      }
    EOF
  }
} 

Just changing the values e.g. for "requestsCpu" to a lower or higher level. 

# Debug Output/Panic Output

╷
│ Error: doesn't support update
│ 
│   with opentelekomcloud_cce_addon_v3.cce_addon_autoscaler[0],
│   on tf_B2810_02_CCE_Add-On_AutoScaler.tf line 33, in resource "opentelekomcloud_cce_addon_v3" "cce_addon_autoscaler":
│   33: resource "opentelekomcloud_cce_addon_v3" "cce_addon_autoscaler" {
│ 
╵

# Steps to Reproduce

1. Change one of the settings for your addon
1. run `terraform apply` again, to update your Add-On Settings. 

# Expected Behavior

The settings of the CCE-AddOn should be automatically updated,
and visible in OTC-COnsole/UI or via kubectl access.  

# Actual Behavior

Nothing. 

# Important Factoids

Possible, but not a good work around. 

Comment out, the cce-autoscaler plugin, run terraform apply (to remove it)
UNcomment it, Redeploy it again with "terraform apply" .. 
 

# References

**Comment by anton-sidelnikov** [comment]
Fixed in latest release
