### ISSUE TITLE
Apply job is failing every time when waf_dedicated_alarm_masking_rule advanced_settings is used.

### ISSUE THREAD

**Issue by IngIhorMuzychka** [opentelekomcloud/terraform-provider-opentelekomcloud#2570]
# Terraform provider version
v1.36.12

# Affected Resource(s)
opentelekomcloud_waf_dedicated_alarm_masking_rule_v1

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_waf_dedicated_alarm_masking_rule_v1" "integrationws-xss-body" {
  policy_id   = opentelekomcloud_waf_dedicated_policy_v1.dwaf_policy_1[0].id
  domains     = [var.waf.waf_domain.name] # String
  rule        = "xss"

  conditions {
    category        = "url"
    contents        = ["integrationws"]
    logic_operation = "contain"
  }

  advanced_settings {
    index           = "Body"
  }
}

resource "opentelekomcloud_waf_dedicated_alarm_masking_rule_v1" "integrationws-sqli-contenttype" {
  policy_id   = opentelekomcloud_waf_dedicated_policy_v1.dwaf_policy_1[0].id
  domains     = [var.waf.waf_domain.name] # String
  rule        = "sqli"

  conditions {
    category        = "url"
    contents        = ["integrationws"]
    logic_operation = "contain"
  }

  advanced_settings {
    index = "Header"
    contents = ["content-type"]
  }
}
```

# Debug Output/Panic Output
```hcl
Error: error creating OpenTelekomCloud WAF Dedicated Alarms Masking Rule:
Bad request with: [POST https://premium-waf.eu-de.otc.t-systems.com/v1/a99465aa49554e9fb91f1b3316be2353/waf/policy/0eeae57306cc4372a27f2e1a6a1fe2e4/ignore],
error message: {"error_code":"WAF.00021001","error_msg":"JSON parse error: Cannot deserialize value of type `com.huawei.waf.mgr.model.policy.Condition` from Array value (token `JsonToken.START_ARRAY`);
nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException:
Cannot deserialize value of type `com.huawei.waf.mgr.model.policy.Condition` from Array value (token `JsonToken.START_ARRAY`)
at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 168]
(through reference chain: com.huawei.waf.mgr.model.policy.Ignore[\"advanced\"])"}
```

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior
Resource is created without errors.

# Actual Behavior
Every time I'm trying to add `advanced_settings` block `terraform apply` is failing (`plan` is working without issues).
Same configuration except `advanced_settings` was successfully created.

# Important Factoids
Also I found another issue in `conditions` block,
`apply` is failing whenever `contents` string starts with "/":
```hcl
  conditions {
    category        = "url"
    contents        = ["/integrationws"] # Fails when starts with "/"
    logic_operation = "contain"
```

# References

**Comment by anton-sidelnikov** [comment]
Hi @IngIhorMuzychka, did you create also jira ticket? This is backend issue, in provider everything implemented according documentation, this error comes from api itself, need to ask devs.

Also, about second issue, without advanced options, everything is fine:
```
resource "opentelekomcloud_waf_dedicated_alarm_masking_rule_v1" "rule_1" {
  policy_id   = opentelekomcloud_waf_dedicated_policy_v1.policy_1.id
  domains     = ["www.example.com"]
  rule        = "xss"
  description = "description"

  conditions {
    category        = "url"
    contents        = ["/integrationws"]
    logic_operation = "contain"
  }
}
```
<img width="621" alt="image" src="https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/assets/53078276/d9aab56a-e86a-4e98-8fde-aa025e5b6ba2">

**Comment by IngIhorMuzychka** [comment]
Hi Anton, thanks for respond,
Oh you right, second issue is not an issue actually.
I did not open a jira ticket yet, but thanks for explanations.

**Comment by IngIhorMuzychka** [comment]
Hi,

in addition. I found out that if I receive a alarm masking rule/whitelist rule via API, the response looks like the following:
```
{
    "id": "bc5901962ce14c279b03d386a760e984",
    "policyid": "0eeae57306cc4372a27f2e1a6a1fe2e4",
    "timestamp": 1720182193288,
    "description": "Created by terraform",
    "status": 1,
    "rule": "xss",
    "mode": 1,
    "conditions": [
        {
            "category": "url",
            "contents": [
                "integrationws"
            ],
            "logic_operation": "contain"
        }
    ],
    "producer": 1,
    "domain": [
        "otc-waf-test.domain.de"
    ],


    # ------- Object --------
    "advanced": {
        "index": "header",
        "contents": [
            "content-type"
        ]
    },


    "update_time": 1720184089975,
    "clear_time": 1720182193288,
    "hit_num": 0
}
```
But in contrast the API request terraform is creating and executing is:
```
{
    # ------- Array of Objects --------
  "advanced": [
    {
      "contents": [
        "content-type"
      ],
      "index": "header"
    }
  ],
  "conditions": [
    {
      "category": "url",
      "contents": [
        "integrationws"
      ],
      "logic_operation": "contain"
    }
  ],
  "description": "Created by terraform",
  "domain": [
    "otc-waf-test.domain.de"
  ],
  "mode": 1,
  "rule": "090180"
}
```
So terraform creates an array of objects, but API is just returning an object.

**Comment by anton-sidelnikov** [comment]
Hi @IngIhorMuzychka seems you're right there is documentation bug

**Comment by anton-sidelnikov** [comment]
Hi @IngIhorMuzychka please try now, on latest release

**Comment by defritsc** [comment]
Hi @anton-sidelnikov,
thanks for the fix this is now working with header in advanced settings.
But the same settings with "body" as index is not working because the contents part must be empty array and not filled with "all"

Working request:
`{
  "advanced": {
    "contents": [],
    "index": "body"
  },
  "conditions": [
    {
      "category": "url",
      "contents": [
        "integrationws"
      ],
      "logic_operation": "contain"
    }
  ],
  "description": "Created by terraform",
  "domain": [
    "otc-waf-test.imagemaster.de"
  ],
  "mode": 1,
  "rule": "090958"
}`

Created by terraform:
`{
  "advanced": {
    "contents": [
      "all"
    ],
    "index": "body"
  },
  "conditions": [
    {
      "category": "url",
      "contents": [
        "integrationws"
      ],
      "logic_operation": "contain"
    }
  ],
  "description": "Created by terraform",
  "domain": [
    "otc-waf-test.imagemaster.de"
  ],
  "mode": 1,
  "rule": "090958"
}`

Terraform code:
```
resource "opentelekomcloud_waf_dedicated_alarm_masking_rule_v1" "integrationws-090958-body" {
  policy_id   = opentelekomcloud_waf_dedicated_policy_v1.dwaf_policy_1[0].id
  domains     = [var.waf.waf_domain.name]
  rule        = "090958"
  description = "Created by terraform"

  conditions {
    index = ""
    category        = "url"
    contents        = ["integrationws"]
    logic_operation = "contain"
  }

  advanced_settings {
    index           = "body"
    contents        = []
  }
}
```

**Comment by anton-sidelnikov** [comment]
Hi @IngIhorMuzychka, @defritsc I changed sdk types for this attributes, hope now everything will works as expected.

**Comment by anton-sidelnikov** [comment]
Hi @IngIhorMuzychka please try 1.36.15
