### ISSUE TITLE
[ASM] Request for New Features: Enhancements for Application Service Mesh (ASM) Management

### ISSUE THREAD

**Issue by Jambo-sudo** [opentelekomcloud/terraform-provider-opentelekomcloud#2574]
# Description of the enhancement
Hello,

Our current workflow involves managing Application Service Mesh (ASM) instances and their configurations. To optimize these processes, we propose enhancing the following features:

1. **Purchase ASM Mesh:**
   - Enable purchase of ASM mesh with customizable configurations.

2. **Choice of Istio Version and Cluster Configuration:**
   - Provide options to select Istio versions for ASM.
   - Configure ASM clusters based on specific requirements.

We look forward to your input and working together to enhance ASM management capabilities.

Best wish.

**Comment by anton-sidelnikov** [comment]
Hi @Jambo-sudo, i didn't see any test report from QA regarding this service, are you sure that is it ready to be implemented? Also no doc in docportal.

**Comment by Jambo-sudo** [comment]
Hi @anton-sidelnikov , Maybe you misunderstood. I am a developer using Open Telekom Cloud, and I don't know anything about test reports. I'm interested in when these features can be used since I didn't find them in the documentation. So, my question is: is this feature in development? When will this feature be available?

**Comment by anton-sidelnikov** [comment]
Hi @Jambo-sudo, we will implement service as soon as it become available and fully tested, I'm not yet received any information about readiness of api for asm, please wait.

**Comment by Jambo-sudo** [comment]
@anton-sidelnikov Ok, thanks. If anything news please let me know.

**Comment by Jambo-sudo** [comment]
Hi, the ASM API seems to have been released. May I ask, when can we expect the relevant features to be integrated into Open Telekom?

**Comment by anton-sidelnikov** [comment]
Hi @Jambo-sudo, I will check today if this service is ready for implementation. If it is, we will begin right away.

**Comment by anton-sidelnikov** [comment]
Hi @Jambo-sudo Where did you get this information? The endpoint for this service is still unavailable.

**Comment by vladimirhasko** [comment]
> Hi, the ASM API seems to have been released. May I ask, when can we expect the relevant features to be integrated into Open Telekom?

@Jambo-sudo from where/whom you have this information? Can you provide some reference to ASM API documentation?

**Comment by TaoLiu-TSI** [comment]
https://docs.otc.t-systems.com/application-service-mesh/api-ref/ 
@vladimirhasko @anton-sidelnikov @Jambo-sudo 
here is the link to API documents

**Comment by vladimirhasko** [comment]
@TaoLiu-TSI , thank you for information, finaly ASM API has been released this week.
We now wait for Quality Assurance to provide us regression tests results
After that we should be able to focus on ASM TF development

**Comment by TaoLiu-TSI** [comment]
Is there any update for this ticket?

**Comment by anton-sidelnikov** [comment]
We will start when ASM will be ready for implementation

**Comment by TaoLiu-TSI** [comment]
@anton-sidelnikov is there any update for this ticket? container colleagues have delivered the required APIs, documents, etc. customer need TF provider for their business.

**Comment by TaoLiu-TSI** [comment]
please help update the status of this ticket, if this feature added in the new version?

**Comment by anton-sidelnikov** [comment]
Resource implemented, please check latest versions
