### ISSUE TITLE
[OBS] - Creation of bucket in NL region fails

### ISSUE THREAD

**Issue by pwurbs** [opentelekomcloud/terraform-provider-opentelekomcloud#2578]
# Terraform provider version
v1.36.12

# Affected Resource(s)
- opentelekomcloud_obs_bucket

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_obs_bucket" "backup_bucket" {
  bucket        = "backup"
  acl           = "private"
  storage_class = "WARM"
  region        = "eu-nl"
  server_side_encryption {
    algorithm  = "kms"
    kms_key_id = var.obs_replication.kms_key_id
  }

```

# Debug Output/Panic Output
Error: error creating OBS client: No suitable endpoint could be found in the service catalog

# Steps to Reproduce
Apply the TF files

# Expected Behavior
Bucket should be created in de-nl region

# Actual Behavior
terraform apply results in failure above

# Important Factoids
Normally, all resources are created in eu-de region. For bucket replication, I want to create a bucket in de-nl.
Specifying the region argument in the bucket resource should be sufficient, I thought.

**Comment by artem-lifshits** [comment]
Hi @pwurbs `opentelekomcloud_obs_bucket` is an old resource and `region` parameter specified in config is redundant there.
The ability to add this parameter to the configuration should be removed, but because the resource is old, it may break existing configurations.

**Comment by pwurbs** [comment]
Hi @artem-lifshits 
What do you mean with "old resource"? It's not marked as deprecated in the TF provider docu. 
And why is "region" redundant there? Where should the resource resp. the provider know from, where to create the bucket?

**Comment by artem-lifshits** [comment]
@pwurbs is was introduced more than 4 years ago by different maintainers.
Parameters like `region` or `tenant_name`/`tenant_id` should be provided to provider settings and obs resource will use it accordingly.

`region` parameter can be completely removed from `opentelekomcloud_obs_bucket` schema but it might break the existing configs.

**Comment by pwurbs** [comment]
@artem-lifshits 
tenant_name / tenantid are the same for both eu-de and eu-nl region. 
But ok, I understand that the region can be specified in the provider configuration. 
But according to https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs#region
region: "(Optional) The name of the region to be used. Required for some resources (e.g. s3_bucket) in case no tenant name provided and no region is defined in the resource."

--> It indicates that the region should better be configured in the resource.
I also wouldn't know how to manage it if I have only resources in eu-de and I only want to create a bucket in de-nl in the same tenant for replication. 
As a result, I don't know how to create an additional backup in eu-nl using terraform to setup a bucket replication.

**Comment by pwurbs** [comment]
As a workaround, I could create a 2nd OTC provider configuring region=eu-nl and then use this provider in my bucket resource for eu-nl. Right?

**Comment by artem-lifshits** [comment]
You can define providers with alias:
```
terraform {
  required_providers {
    opentelekomcloud = {
      source  = "opentelekomcloud/opentelekomcloud"
      version = "1.36.12"
    }
  }
}

provider "opentelekomcloud" {
  cloud = "eu-de"
  alias = "main_provider"
}

provider "opentelekomcloud" {
  cloud = "eu-nl"
  alias = "secondary_provider"
}
```

And resources will look like that:
```
resource "opentelekomcloud_obs_bucket" "backup_bucket" {
  bucket        = "backup-test-bucket-1"
  acl           = "private"
  provider = opentelekomcloud.main_provider
}

resource "opentelekomcloud_obs_bucket" "replication-bucket" {
  bucket        = "replication-test-bucket-1"
  acl           = "private"
  storage_class = "WARM"
  provider = opentelekomcloud.secondary_provider
}
```

**Comment by pwurbs** [comment]
Thx @artem-lifshits 
This sounds viable. 
But I still think, the provider should either delete the region argument from the bucket resource or make it work.

**Comment by artem-lifshits** [comment]
@pwurbs I agree with you, we will do it for a major version with additional notes.
