### ISSUE TITLE
VPN Section DPDis beeing changed after changeing the PSK from console

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#2579]
# Terraform provider version 
current Version

# Affected Resource(s)
VPN - tunnel

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_vpnaas_site_connection_v2" "tunnel" {
  name           = "${var.vpn_config.name}-tunnel"
...
  dpd {
    action   = "hold"
    timeout  = 30
    interval = 10
  }
}
```

Everything works w/o any problem. Then I go to the web console and modify the VPN tunnel, specifically I update PSK. After the update DPD settings are reset to default:

```
      dpd {
          action   = "hold"
          interval = 30
          timeout  = 120
        }
```

```

This makes tunnel configuration inconsistent with the other end.

Can you please fix this so that when the tunnel is modified via web console - only affected attributes are changed and other ones are not reset to default?

**Comment by anton-sidelnikov** [comment]
Hi @CHS-OTC, as I understand this is not the right way to use terrafrom, do not change manually resources created by terraform, if you do than then re-import resource inside terraform. Otherwise terraform will revert your changes.
