### ISSUE TITLE
Error with DMS data source

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#2589]
Hello,

the current OTC terraform provider is unable to retrieve the AZ data source for the DMS service.
Propably a recent change at OTC changed the API behaviour.

# Terraform provider version
Terraform v1.9.2
on windows_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.36.14

# Affected Resource(s)
data opentelekomcloud_dms_az_v1

# Terraform Configuration Files
data "opentelekomcloud_dms_az_v1" "az1" {
  name = "eu-de-01"
  port = "8002"
}

data "opentelekomcloud_dms_az_v1" "az3" {
  name = "eu-de-03"
}

# Debug Output/Panic Output
data.opentelekomcloud_dms_az_v1.az1: Reading...
data.opentelekomcloud_dms_az_v1.az3: Reading...
╷
│ Error: not found any available zones
│
│   with data.opentelekomcloud_dms_az_v1.az1,
│   on ded.tf line 15, in data "opentelekomcloud_dms_az_v1" "az1":
│   15: data "opentelekomcloud_dms_az_v1" "az1" {
│
╵
╷
│ Error: not found any available zones
│
│   with data.opentelekomcloud_dms_az_v1.az3,
│   on ded.tf line 20, in data "opentelekomcloud_dms_az_v1" "az3":
│   20: data "opentelekomcloud_dms_az_v1" "az3" {
│
╵

# Steps to Reproduce
1. `terraform apply`

# Expected Behavior
the az data sources should be resolved to then be usable for an DMS ressource

# Actual Behavior
the terraform provider is unable to retrieve the AZ information from the API

# Important Factoids
The terraform provider does an API request to:
GET dms.eu-de.otc.t-systems.com/v1.0/availableZones
The API request also succeeds.
Response:
{"region_id":"eu-de","available_zones":[{"id":"bf84aba586ce4e948da0b97d9a7d62fb","code":"eu-de-01","name":"eu-de-01","port":"8002","resource_availability":"true"},{"id":"bf84aba586ce4e948da0b97d9a7d62fc","code":"eu-de-02","name":"eu-de-02","port":"8003","resource_availability":"true"},{"id":"eu-de-03","code":"eu-de-03","name":"eu-de-03","port":"8027","resource_availability":"true"}]}

So I guess that there was a recent change of the DMS API format and TF is unable to process the information.

# References
https://docs.otc.t-systems.com/distributed-message-service/api-ref/apis_v2_recommended/other_apis/listing_az_information.html#listavailablezones
https://docs.otc.t-systems.com/distributed-message-service/api-ref/out-of-date_apis/api_v1/other_apis/querying_az_information.html#kafka-api-180514008

**Comment by anton-sidelnikov** [comment]
Fixed in 1.36.15
