### ISSUE TITLE
Storage Class parameter not effective on creating OBS Bucket in Swiss Region

### ISSUE THREAD

**Issue by brunoagueda** [opentelekomcloud/terraform-provider-opentelekomcloud#2593]
# Terraform provider version

Terraform v1.8.3
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.36.14

# Affected Resource(s)

opentelekomcloud_obs_bucket

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_obs_bucket" "new-bucket" {
  bucket        = "new-bucket-test-storage-class"
  acl           = "private"
  versioning    = false
  storage_class = "WARM"
}
```

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

Bucket created with WARM storage class

# Actual Behavior

Bucket created with STANDARD storage class

# Important Factoids

Changing the storage_class parameter to WARM or COLD doesn't work, the bucket is always created with STANDARD storage class. Testing the API described on the Swiss OTC documentation, I tried creating a bucket with header "x-default-storage-class": "WARM" and got this response: "The default storage class is invalid, it can only be STANDARD, STANDARD_IA or GLACIER." With these values (STANDARD_IA instead of WARM, and GLACIER instead of COLD) it works. Is this a difference between the APIs in German and Swiss regions or is this something to be adjusted on the terraform module?

**Comment by artem-lifshits** [comment]
Hello @brunoagueda could you send me TF logs? 

I tried creating `STANDARD_IA` bucket type via sdk in swiss region and received this error:
```
obs: service returned error: Status=400 Bad Request, Code=InvalidDefaultStorageClass, Message=The default storage class is invalid, it can only be STANDARD, WARM or COLD., RequestId=0000019102D1AD1381475C2204F4E6F2
```
Creation of WARM bucket via WEBUI also uses `WARM` header.

**Comment by artem-lifshits** [comment]
Please reopen ticket is issue is still relevant
