### ISSUE TITLE
Fetching CSS ssl certificate

### ISSUE THREAD

**Issue by djetelina** [opentelekomcloud/terraform-provider-opentelekomcloud#2594]
# Description of the enhancement

Hey, it would be awesome if there was a way to get CSS certificate for secured clusters through TF. There is an API endpoint for it [here](https://docs.otc.t-systems.com/cloud-search-service/api-ref/cluster_management_apis/downloading_the_certificate.html) but no corresponding resource that I can find has it. It should be either part of `opentelekomcloud_css_cluster_v1` attributes, or a new data resource, e.g. `opentelekomcloud_css_ssl_cert_v1`

**Comment by anton-sidelnikov** [comment]
Hi @djetelina I have checked this doc, api seems not published for this operation. I will create internal issue.
https://jira.tsi-dev.otc-service.com/browse/BM-5592

**Comment by anton-sidelnikov** [comment]
HI @djetelina, new data-source available in v1.36.26: opentelekomcloud_css_certificate_v1
