### ISSUE TITLE
Migration strategy of DMS V1 to V2 [Terraform]

### ISSUE THREAD

**Issue by bboron86** [opentelekomcloud/terraform-provider-opentelekomcloud#2596]
### Discussed in https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/discussions/2586

<div type='discussions-op-text'>

<sup>Originally posted by **bboron86** July 15, 2024</sup>
Hi,

we're running a Kafka v2.7 with Terraform's `opentelekomcloud_dms_product_v1` provider. However the `V1` API is now deprecated and we should migrate to `V2`. How can we migrate `terraform state` to the new API,  WITHOUT recreating all kafka resources? </div>

**Comment by anton-sidelnikov** [comment]
Hi @bboron86! First, we need to implement new resources, and after that you can simply import existing resources in your tf config. So, marked this to future implementation.

**Comment by artem-lifshits** [comment]
Hello @bboron86 new DMS resource is introduced `opentelekomcloud_dms_dedicated_instance_v2`.
It doesn't have any deprecated API and you can import it by using terraform import and id of your DMS instance with a couple of lifecycle `ignore_changes`.
