### ISSUE TITLE
Dedicated WAF | Support Deep/Header Inspection 

### ISSUE THREAD

**Issue by defritsc** [opentelekomcloud/terraform-provider-opentelekomcloud#2597]
The Dedicated WAF supports Deep/Header Inspection which needs to be enabled via extend block and not via normal options.
Response from API looks like:
```
"extend": {
        "extend": "{"deep_decode":true,"check_all_headers":true}"
},
```
OTC API Documentation: https://docs.otc.t-systems.com/web-application-firewall-dedicated/api-ref/apis/policy_management/creating_a_policy.html#createpolicy-response-policyextend:~:text=Table%208%20PolicyExtend%C2%B6 

To be able to configure every possible protection, it would be great to extend waf_dedicated_policy_v1: https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/waf_dedicated_policy_v1

**Comment by anton-sidelnikov** [comment]
Available in latest version 1.36.16
