### ISSUE TITLE
OTC API change in RDS flavor names broke existing RDS environments

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#2604]
Hi,
Today were new flavors for RDS released.
They enabled to usage of the new CloudSSD.
The issue is that all RDS flavor names changed.

So a new name has for example the name = "rds.pg.n1.xlarge.2" or "rds.pg.x1.large.4.ha"
That differs from the old form = "rds.pg.c2.medium"

The RDS flavor API only offers the new types of RDS
GET /v3/PROJECTID/flavors/RDS_TYPE

But there are still existing environments with the old names of the flavors.

And when it checks the TFSTATE of an existing infrastructure, it will fail

│ Error: 1 error occurred:
│       * can't find flavor `rds.pg.c2.medium`
│ 
│ 
│ 
│   with module.postgres.opentelekomcloud_rds_instance_v3.db_instance,
│   on .terraform/modules/postgres/modules/rds/database.tf line 44, in resource "opentelekomcloud_rds_instance_v3" "db_instance":
│   44: resource "opentelekomcloud_rds_instance_v3" "db_instance" {

I guess that is because the OTC TF provider checks if the entered flavor value actually exists for opentelekomcloud_rds_instance_v3 .
But unfortunatly because the API flavor names changed this is now an issue that the flavorname is checked against the actual available names as the old ones are not listed.

So is it possible to remove the check of the "flavor" field of opentelekomcloud_rds_instance_v3 against the flavor API so existing environments will not fail at the tfstate check? 

# Terraform provider version
provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.36.15

# Affected Resource(s)
opentelekomcloud_rds_instance_v3
maybe also opentelekomcloud_rds_instance_v1

# Terraform Configuration Files
not provided as it requires an now outdated RDS flavor which cannot be created anymore

# Debug Output/Panic Output
│ Error: 1 error occurred:
│       * can't find flavor `rds.pg.c2.medium`
│ 
│ 
│ 
│   with module.postgres.opentelekomcloud_rds_instance_v3.db_instance,
│   on .terraform/modules/postgres/modules/rds/database.tf line 44, in resource "opentelekomcloud_rds_instance_v3" "db_instance":
│   44: resource "opentelekomcloud_rds_instance_v3" "db_instance" {

# Steps to Reproduce
1.Have an existing terraform environment with an opentelekomcloud_rds_instance_v3 ressource and an outdated RDS flavor like "rds.pg.c2.medium"
2. Don't change anything
3. terraform apply

**Comment by canaykin** [comment]
@CHS-OTC @anton-sidelnikov changes are currently rolled by OTC and only old instance flavors are available.

**Comment by anton-sidelnikov** [comment]
Tested hotfix on pre-production with switching from old to new version of RDS. Everything working as expected.
