### ISSUE TITLE
Missing data sources on Elastic Volume Service

### ISSUE THREAD

**Issue by krkardos** [opentelekomcloud/terraform-provider-opentelekomcloud#2611]
# Missing DATA SOURCES on opentelekomcloud_evs_volume_v3
Hi,

I would like to kindly ask you to develope the following:

At the moment, the resource: opentelekomcloud_evs_volume_v3 has no DATA SOURCES in the terraform provider, which is very necessary for us and I think it would be very useful for other OpenTelekomCloud Terraform Users.

Can you check my request and give me a feedback, is it possible to develope and implement this request in the near future and how long does it take approximately to be able to use it in production ?

Thank You in advance!

**Comment by anton-sidelnikov** [comment]
Hi @krkardos data-source available in v1.36.17

**Comment by krkardos** [comment]
> Hi @krkardos data-source available in v1.36.17

Hello Anton,

Thank You for develope this data-source in the latest provider. 
I am trying to use it but without success. Could you please check and test it ?

My code is here:

data "opentelekomcloud_evs_volumes_v2" "test" {
  server_id = opentelekomcloud_ecs_instance_v1.myinstance_2.id
}

output "disk" {
  value = data.opentelekomcloud_evs_volumes_v2.test
}

My output for the Data:
disk = {
  "availability_zone" = tostring(null)
  "id" = "0"
  "name" = tostring(null)
  "server_id" = "bd1e202d-6260-4f35-a19d-02936f087899"
  "shareable" = tobool(null)
  "status" = tostring(null)
  "tags" = tomap(null) /* of string */
  "volume_id" = tostring(null)
  "volume_type_id" = tostring(null)
  "volumes" = tolist([])
}

Unfortunatelly i am getting only null values. ( My api user has full rights as ECS + EVS Administrator ).
Can you please check it again ?

**Comment by artem-lifshits** [comment]
Hello @krkardos volume information is provided in `volumes` section, all fields above are filters provided in user config.
Are you sure `"volumes" = tolist([])` also returns an empty list?
With the config you've provided tfstate `output` will look like this:
```
"outputs": {
        "disk": {
            "value": {
                "availability_zone": null,
                "id": "2508579976",
                "name": null,
                "server_id": "8b4bf211-765d-4f2d-be05-eb7c34592e43",
                "shareable": null,
                "status": null,
                "tags": null,
                "volume_id": null,
                "volume_type_id": null,
                "volumes": [
                    {
                        "attachments": [
                            {
                                "attached_at": "2024-07-08T08:36:13.496614",
                                "attached_mode": "rw",
                                "device_name": "/dev/vda",
                                "id": "e093f5ba-2278-4402-96e1-2fe1a79f909d",
                                "server_id": "8b4bf211-765d-4f2d-be05-eb7c34592e43"
                            }
                        ],
                        "availability_zone": "eu-de-01",
                        "bootable": true,
                        "create_at": "2024-07-08T08:35:58.177317",
                        "description": "",
                        "id": "24194ced-50dc-4dbc-aa57-f4eb297f748b",
                        "name": "ecs-166d",
                        "service_type": "EVS",
                        "shareable": false,
                        "size": 60,
                        "status": "in-use",
                        "tags": {},
                        "update_at": "2024-07-08T08:36:13.549946",
                        "volume_type": "SAS",
                        "wwn": "688860300035e2adfa16815c58847003"
                    }
                ]
            },
            "type": ....
        }
    }
```

**Comment by krkardos** [comment]
> Hello @krkardos volume information is provided in `volumes` section, all fields above are filters provided in user config. Are you sure `"volumes" = tolist([])` also returns an empty list? With the config you've provided tfstate `output` will look like this:
> 
> ```
> "outputs": {
>         "disk": {
>             "value": {
>                 "availability_zone": null,
>                 "id": "2508579976",
>                 "name": null,
>                 "server_id": "8b4bf211-765d-4f2d-be05-eb7c34592e43",
>                 "shareable": null,
>                 "status": null,
>                 "tags": null,
>                 "volume_id": null,
>                 "volume_type_id": null,
>                 "volumes": [
>                     {
>                         "attachments": [
>                             {
>                                 "attached_at": "2024-07-08T08:36:13.496614",
>                                 "attached_mode": "rw",
>                                 "device_name": "/dev/vda",
>                                 "id": "e093f5ba-2278-4402-96e1-2fe1a79f909d",
>                                 "server_id": "8b4bf211-765d-4f2d-be05-eb7c34592e43"
>                             }
>                         ],
>                         "availability_zone": "eu-de-01",
>                         "bootable": true,
>                         "create_at": "2024-07-08T08:35:58.177317",
>                         "description": "",
>                         "id": "24194ced-50dc-4dbc-aa57-f4eb297f748b",
>                         "name": "ecs-166d",
>                         "service_type": "EVS",
>                         "shareable": false,
>                         "size": 60,
>                         "status": "in-use",
>                         "tags": {},
>                         "update_at": "2024-07-08T08:36:13.549946",
>                         "volume_type": "SAS",
>                         "wwn": "688860300035e2adfa16815c58847003"
>                     }
>                 ]
>             },
>             "type": ....
>         }
>     }
> ```

Hello Anton,

I got full output now, the problem was that i had to concretize in the "data" field to use the provider which was created the ECS + EVS.

Does it mean, that with this data source block, we can not query datas which was not created by terraform ?
For example, in the tenant we create several ECSs manually, we can not query them with this data source ?

**Comment by krkardos** [comment]
> Hello @krkardos volume information is provided in `volumes` section, all fields above are filters provided in user config. Are you sure `"volumes" = tolist([])` also returns an empty list? With the config you've provided tfstate `output` will look like this:
> 
> ```
> "outputs": {
>         "disk": {
>             "value": {
>                 "availability_zone": null,
>                 "id": "2508579976",
>                 "name": null,
>                 "server_id": "8b4bf211-765d-4f2d-be05-eb7c34592e43",
>                 "shareable": null,
>                 "status": null,
>                 "tags": null,
>                 "volume_id": null,
>                 "volume_type_id": null,
>                 "volumes": [
>                     {
>                         "attachments": [
>                             {
>                                 "attached_at": "2024-07-08T08:36:13.496614",
>                                 "attached_mode": "rw",
>                                 "device_name": "/dev/vda",
>                                 "id": "e093f5ba-2278-4402-96e1-2fe1a79f909d",
>                                 "server_id": "8b4bf211-765d-4f2d-be05-eb7c34592e43"
>                             }
>                         ],
>                         "availability_zone": "eu-de-01",
>                         "bootable": true,
>                         "create_at": "2024-07-08T08:35:58.177317",
>                         "description": "",
>                         "id": "24194ced-50dc-4dbc-aa57-f4eb297f748b",
>                         "name": "ecs-166d",
>                         "service_type": "EVS",
>                         "shareable": false,
>                         "size": 60,
>                         "status": "in-use",
>                         "tags": {},
>                         "update_at": "2024-07-08T08:36:13.549946",
>                         "volume_type": "SAS",
>                         "wwn": "688860300035e2adfa16815c58847003"
>                     }
>                 ]
>             },
>             "type": ....
>         }
>     }
> ```

Hello Anton,

Now i have a working code. The problem was, that my "data source" was not used the right provider. Now everything is working. Thank You for your support!
