### ISSUE TITLE
[CCE] Add label support for cce-node resource

### ISSUE THREAD

**Issue by Jambo-sudo** [opentelekomcloud/terraform-provider-opentelekomcloud#2616]
Hello Team,

Currently, the cce-node resource does not support adding labels. May I ask if there are any plans to provide this feature?
![image](https://github.com/user-attachments/assets/d95c1d63-0a91-4d41-8eb8-c8a66e49d01b)
This function is available in console.
![image](https://github.com/user-attachments/assets/6c28e8e0-a7b7-4700-bc64-79ff21c46f9c)

Thanks

**Comment by artem-lifshits** [comment]
Hello @Jambo-sudo, TF provider depends on OTC API. According to it CCE nodes support labels while CCE node pools don't, so we're unable to implement it.
Please open ticket for OTC support with a demand to implement this feature on API side and when it's available we will work on it.

**Comment by TaoLiu-TSI** [comment]
https://docs.otc.t-systems.com/cloud-container-engine/api-ref/apis/cluster_management/creating_a_node_pool.html
![image](https://github.com/user-attachments/assets/3ef6a7bb-a9a4-49aa-94d1-28cf5b1ac0d4)

@artem-lifshits please check, is this API of CCE?

**Comment by anton-sidelnikov** [comment]
@Jambo-sudo if you're looking at node_pool_v3 doc, then you will see that all tags already supported by this resource:
![image](https://github.com/user-attachments/assets/7b09e891-6724-48be-ba03-75b98c1c068d)

**Comment by TaoLiu-TSI** [comment]
thanks a lot! @anton-sidelnikov
