### ISSUE TITLE
[IAM] | Security Settings | AK Management / Information Self-Management  

### ISSUE THREAD

**Issue by uli-schneider** [opentelekomcloud/terraform-provider-opentelekomcloud#2621]
# Description of the enhancement
OTC IAM offers the posibility to manage central AK Management and Information Self-Management. 
![grafik](https://github.com/user-attachments/assets/6aabf153-c13d-4c65-8155-26f5d9b42df2)

According to a ServiceDesk Ticket
The API support this: 
https://docs.otc.t-systems.com/identity-access-management/api-ref/apis/security_settings/index.html
 
Following json body needs to be sent:  
{
"protect_policy" : {
"operation_protection" : false,
"allow_user" : {
"manage_accesskey" : false,
"manage_email" : true,
"manage_mobile" : true,
"manage_password" : true
}
}
}

Internal Jira reference: https://jira.tsi-dev.otc-service.com/browse/OTCSEC-7443

**Comment by artem-lifshits** [comment]
Hello @uli-schneider feature is not available via API according to API docs, closing the ticket.
