### ISSUE TITLE
support importing opentelekomcloud_nat_snat_rule_v2

### ISSUE THREAD

**Issue by bbung** [opentelekomcloud/terraform-provider-opentelekomcloud#2622]
# Description of the enhancement

Due to project reconstruction i have to move a opentelekomcloud_nat_snat_rule_v2 to another terraform project. The resource currently does not support importing to the state. 

Import is necessary to prevent downtime while recreating this rule.

**Comment by anton-sidelnikov** [comment]
Hi @bbung please check the latest v1.36.17

**Comment by bbung** [comment]
Working as expected. Thanks for the quick implementation!
