### ISSUE TITLE
[RDS] - Enable Autoscaling on existing RDS (PostgreSQL) leads to error message 

### ISSUE THREAD

**Issue by uli-schneider** [opentelekomcloud/terraform-provider-opentelekomcloud#2628]
# Terraform provider version

>=1.36.16"

# Affected Resource(s)

opentelekomcloud_rds_instance_v3

# Terraform Configuration Files
```hcl

... 
  volume {
    #
    type               = "ULTRAHIGH"
    size               = 40
    disk_encryption_id = opentelekomcloud_kms_key_v1.kms_project_key.id
    # Enable Autoscaling 
    limit_size         = 100
    trigger_threshold  = 10
  }
```

# Debug Output/Panic Output

╷
│ Error: error updating instance volume from result: Bad request with: [POST https://rds.eu-de.otc.t-systems.com/v3/6898640658cd4979baa0646ee30533b9/instances/2b1e580a0e3d4605a21e45fb67c5723bin03/action], error message: {"error_msg":"The new storage space must be a multiple of 10 GB and greater than the original storage space.","error_code":"DBS.200306"}
│ 
│   with opentelekomcloud_rds_instance_v3.rds_pg,
│   on tf_B4000_RDS_PostgreSQL.tf line 79, in resource "opentelekomcloud_rds_instance_v3" "rds_pg":
│   79: resource "opentelekomcloud_rds_instance_v3" "rds_pg" {
│ 
╵

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

Enable Autoscaling, Update Config. 

# Actual Behavior

See Error Message 

# Important Factoids

Creating a new rds instance with that parameters works. 
Changing on this tf-created rds instance e.g. "limit_size" from 100 to 200 throws the same error. 
 
Enable the Autoscaling via UI, is possible. 

# References

https://www.open-telekom-cloud.com/en/support/release-notes/autoscaling-rds-for-ms-sql-server-postgresql-in-all-versions

**Comment by uli-schneider** [comment]
In Addition, please add the new DB-Versions which supports now Autoscaling, to the tf-provider documentation. 
Thanks!

**Comment by anton-sidelnikov** [comment]
Hi @uli-schneider please check the latest v1.36.17

**Comment by uli-schneider** [comment]
@anton-sidelnikov , Thanks !!! seems working for me
