### ISSUE TITLE
[DDS] - Backup "period" is not implemented 

### ISSUE THREAD

**Issue by uli-schneider** [opentelekomcloud/terraform-provider-opentelekomcloud#2632]
# Terraform provider version

1.36.16

# Affected Resource(s)

opentelekomcloud_dds_instance_v3

# Terraform Configuration Files
```hcl
... 
  backup_strategy {
    start_time = "03:00-04:00"
    keep_days  = "7"
    period     = "1,3,5"
  }

```

# Debug Output/Panic Output

╷
│ Error: Unsupported argument
│ 
│   on tf_B4500_DDS_Single_Instance.tf line 91, in resource "opentelekomcloud_dds_instance_v3" "dds_single":
│   91:     period     = "1,3,5"
│ 
│ An argument named "period" is not expected here.

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior

API and UI support the value "period" for DDS Backups. 

https://docs.otc.t-systems.com/document-database-service/api-ref/apis_v3.0_recommended/backup_and_restoration/setting_an_automated_backup_policy.html#dds-api-0031

![image](https://github.com/user-attachments/assets/387644c4-495d-4117-81f0-caa81d43ea8b)

![image](https://github.com/user-attachments/assets/a3eca211-110b-4e48-bb97-431ace53abce)

# Actual Behavior

Can not managed by terraform 

Please add to provider and add it to tf-documentation. 

# Important Factoids

# References

**Comment by anton-sidelnikov** [comment]
Implemented in v1.36.17
