### ISSUE TITLE
[DMS] Add Smart Connect support to DMS resource

### ISSUE THREAD

**Issue by Jambo-sudo** [opentelekomcloud/terraform-provider-opentelekomcloud#2635]
Hello Team,

Currently the DMS resource are not provide smart connect feature.  May I ask if there are any plans to provide this feature?
This function is available in console already.

Thanks

**Comment by anton-sidelnikov** [comment]
Part of #2596

**Comment by anton-sidelnikov** [comment]
Hi @Jambo-sudo, available in v1.36.22, please check.
