### ISSUE TITLE
[VPN] - Support new "Enterprise VPN"  

### ISSUE THREAD

**Issue by uli-schneider** [opentelekomcloud/terraform-provider-opentelekomcloud#2640]
# Description of the enhancement
There is a new service available, "Enterprise VPN" please add to tf-provider: 
API: 
https://docs.otc.t-systems.com/virtual-private-network/api-ref/api_reference_enterprise_edition_vpn/index.html

Thanks!

**Comment by anton-sidelnikov** [comment]
Available in v1.36.22, please check.

**Comment by uli-schneider** [comment]
Works for me! 
Thanks for the implementation
