### ISSUE TITLE
opentelekomcloud_dcs_instance_v2: define number of replicas 

### ISSUE THREAD

**Issue by deem1978** [opentelekomcloud/terraform-provider-opentelekomcloud#2642]
Hello everybody, 
I would really appreciate if someone can help.
I need to setup a Redis instance and my setup should be 1 master + 2 replicas. In the related [documentation](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/dcs_instance_v2) I am not able to find any useful parameter, I just see that the `replica_count` attribute can be exported, but how can I define the number of the needed replicas?

Thank you, 
Davide

**Comment by artem-lifshits** [comment]
Hello @deem1978 the number of replicas is indicated within the DCS flavor name (spec_code). 
For example in flavor `redis.ha.xu1.tiny.r5.512` the `r5` component signifies that this flavor is configured to use 5 replicas.

**Comment by deem1978** [comment]
wow ok! thank you a lot!
