### ISSUE TITLE
opentelekomcloud_rds_read_replica_v3: SSL

### ISSUE THREAD

**Issue by deem1978** [opentelekomcloud/terraform-provider-opentelekomcloud#2644]
Hello everybody, 
I hope that someone can drive me to the correct info.
I have just setup a read replica for my RDS Instance. The master instance is with SSL configured, and I thought that the replica will follow the master default settings, also because in replica [resource](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/rds_read_replica_v3) there is no related parameter, but instead the replica was deployed without SSL.
I see that for rds_instance_v3 there is the option "ssl_enable" that can be used, but by replica I found no similar option.
How can I configure that for my replica too?

Thank you, 
Davide

**Comment by artem-lifshits** [comment]
Hello @deem1978 I will look if it's possible to implement ssl for read replica.

**Comment by deem1978** [comment]
Hello @artem-lifshits , that would be great thank you :)

**Comment by artem-lifshits** [comment]
@deem1978 implemented in latest release.

**Comment by deem1978** [comment]
Great, thank you.

**Comment by deem1978** [comment]
Hi @artem-lifshits, I have just tried to apply it to a running instance and I get an error when I run `terraform plan` :
This the the piece of code:

```
# create read replica
resource "opentelekomcloud_rds_read_replica_v3" "replica" {
  name          = "stage-replica"
  replica_of_id = module.rds.instance_id
  flavor_ref    = "rds.mysql.c2.large.rr"
  ssl_enable    = true

  availability_zone = module.rds.instance_az[0]

  volume {
    type               = "COMMON"
    disk_encryption_id = data.opentelekomcloud_kms_key_v1.default.id
  }
}
```
and this is the error:

```
╷
│ Error: Unsupported argument
│
│   on main.tf line 32, in resource "opentelekomcloud_rds_read_replica_v3" "replica":
│   32:   ssl_enable    = true
│
│ An argument named "ssl_enable" is not expected here.
╵
make: *** [plan] Error 1
```

Do you have an idea where is the problem? In the related [documentation](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/rds_read_replica_v3) the parameter is available...

Thank you for having a look into it.
Best 
Davide

**Comment by deem1978** [comment]
@anton-sidelnikov, any idea?

**Comment by anton-sidelnikov** [comment]
HI @deem1978 please update terraform provider to latest version

**Comment by deem1978** [comment]
Hi @anton-sidelnikov thank you for your reply. 
Terraform version is the 1.9.8 and provider is the 1.36.23, the described error persist:

```
│ Error: Unsupported argument
│
│   on main.tf line 32, in resource "opentelekomcloud_rds_read_replica_v3" "replica":
│   32:   ssl_enable    = true
│
│ An argument named "ssl_enable" is not expected here.
╵
make: *** [plan] Error 1
```

**Comment by deem1978** [comment]
Forget it, thank you, problem is solved.
