### ISSUE TITLE
Missing doc for CCE Addon installation

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#2645]
missing autoscaler addon documentation for current CCE 1.28 version

https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/1573 doesn't include autoscaler

**Comment by artem-lifshits** [comment]
Hello @CHS-OTC could you clarify what information is missing?
I don't see any info related to v1.28 on [node pool page](https://docs.otc.t-systems.com/cloud-container-engine/api-ref/apis/cluster_management/creating_a_node_pool.html).

**Comment by CHS-OTC** [comment]
eg for the ressource opentelekomcloud_cce_addon_v3 for type autoscaler

whats needed for:
- basic
- custom
- flavor
?
`
resource "opentelekomcloud_cce_addon_v3" "autoscaler" {
  template_name    = data.opentelekomcloud_cce_addon_template_v3.autoscaler.addon_name
  template_version = data.opentelekomcloud_cce_addon_template_v3.autoscaler.addon_version
  cluster_id       = opentelekomcloud_cce_cluster_v3.cluster.id

  values {
    basic = {
      "cceEndpoint" = "https://cce.${var.region_name}.otc.t-systems.com"
      "ecsEndpoint" = "https://ecs.${var.region_name}.otc.t-systems.com"
      region        = var.region_name
      # swr_addr = data.opentelekomcloud_cce_addon_template_v3.autoscaler.swr_addr
      swr_user = data.opentelekomcloud_cce_addon_template_v3.autoscaler.swr_user
    }
    custom = {
      "cluster_id"                    = opentelekomcloud_cce_cluster_v3.cluster.id
      "tenant_id"                     = "OTC000000000010000xxxx"
      "coresTotal"                    = 16000
      "expander"                      = "priority"
      "logLevel"                      = 4
      "maxEmptyBulkDeleteFlag"        = 11
      "maxNodesTotal"                 = 100
      "memoryTotal"                   = 64000
      "scaleDownDelayAfterAdd"        = 15
      "scaleDownDelayAfterDelete"     = 15
      "scaleDownDelayAfterFailure"    = 3
      "scaleDownEnabled"              = true
      "scaleDownUnneededTime"         = 7
      "scaleUpUnscheduledPodEnabled"  = true
      "scaleUpUtilizationEnabled"     = true
      "unremovableNodeRecheckTimeout" = 7
    }
    flavor = <<EOF
      {
        "description": "Has only one instance",
        "name": "Single",
        "replicas": 1,
        "resources": [
          {
            "limitsCpu": "1000m",
            "limitsMem": "1000Mi",
            "name": "autoscaler",
            "requestsCpu": "500m",
            "requestsMem": "500Mi"
          }
        ]
      }
    EOF
  }
}
`

**Comment by artem-lifshits** [comment]
Doc updated.
