### ISSUE TITLE
[CBR] - Add CrossRegion Replication functionality 

### ISSUE THREAD

**Issue by uli-schneider** [opentelekomcloud/terraform-provider-opentelekomcloud#2647]
# Description of the enhancement

Please extend following providers: 
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cbr_policy_v3
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cbr_vault_v3

to be able to setting up CBR-Cross Region functionaltiy to CBR.

https://www.open-telekom-cloud.com/en/support/release-notes/cbr-supports-geo-redundant-backups
https://community.open-telekom-cloud.com/community?id=community_blog&sys_id=b80a47c61394d610d15a246ea6744134

Seems that for the policy the parameters: 
destination_project_id, destination_region
are missing and not documented. 
https://docs.otc.t-systems.com/cloud-backup-recovery/api-ref/cbr_apis/policies/creating_a_policy.html#createpolicy

The Vault needs a field for the replication policy. 

Please add this also to terraform documentation.

**Comment by anton-sidelnikov** [comment]
Added in latest release

**Comment by pbol-samedi** [comment]
Perhaps I'm missing something, but AFAIU the vault still doesn't have a field to apply the replication_policy. In the UI I can apply the replication policy on the vault, but I don't see the option to do that through Terraform.
