### ISSUE TITLE
Extend opentelekomcloud_sdrs_protectiongroup_v1 Provider to Support "Enabling Protection" for SDRS Service

### ISSUE THREAD

**Issue by samisallam** [opentelekomcloud/terraform-provider-opentelekomcloud#2649]
The current version of the terraform-provider-opentelekomcloud does not have the feature to automatically **enable protection** for the [SDRS protection group](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/sdrs_protectiongroup_v1). 
This limitation requires manual intervention when deploying the Disaster Recovery Service (SDRS) using Terraform.
![Sdrs-enabling-protection](https://github.com/user-attachments/assets/d58da989-2247-4868-a07a-c824359a75bf)

**Comment by muneeb-jan** [comment]
Enable is now part of resource creation. Refer to PR #2655

**Comment by anton-sidelnikov** [comment]
Still not in release

**Comment by anton-sidelnikov** [comment]
HI @sallam-2021 Feature available in latest release: 1.36.20, please check
