### ISSUE TITLE
IPV6 support for Direct Connect Virtual Interface opentelekomcloud_dc_virtual_interface_v2

### ISSUE THREAD

**Issue by brunoagueda** [opentelekomcloud/terraform-provider-opentelekomcloud#2650]
# Description of the enhancement
Hello colleagues
It's been released a new version (V3) of the Direct Connect API, and this new version offers support for IPV6 Virtual Interface peers.
I would like to request the opentelekomcloud_dc_virtual_interface_v2 to be updated to add the IPV6 support to it.
The goal is to create the Virtual Interface with both IPV4 and IPV6 Virtual Interface Peers.
Link to the documentation: https://docs.sc.otc.t-systems.com/direct-connect/api-ref/api_v3/virtual_interfaces/index.html
I tested the API only in the Swiss Region so far.

**Comment by brunoagueda** [comment]
Hi. Do you have an estimate on when this feature will be available?

**Comment by anton-sidelnikov** [comment]
Hi @brunoagueda, requested DC connection from network team, still waiting, cannot start without it.

**Comment by anton-sidelnikov** [comment]
Hi @brunoagueda resources available in latest provider version 1.36.25

**Comment by brunoagueda** [comment]
Hi @anton-sidelnikov 
I tested and it works, thanks!
Is it possible to add the feature of enabling both ipv4 and ipv6 virtual interface peers on the same virtual interface? This is possible on the GUI and API

**Comment by anton-sidelnikov** [comment]
Hi @brunoagueda, i see that some api for vif peers are missing by now, so need to wait, i will add or update resource when it will be available

**Comment by brunoagueda** [comment]
What API is missing? The APIs for creating, updating and deleting are available and I tested them already.
https://docs.sc.otc.t-systems.com/direct-connect/api-ref/api_v3/virtual_interfaces/creating_a_virtual_interface_peer.html
If something is missing, please let me know. I have access to the development team if necessary

**Comment by anton-sidelnikov** [comment]
oh, interesting, could you give me request body for this endpoints? i will check today

**Comment by brunoagueda** [comment]
Here is a link to a gist with the requests

https://gist.github.com/brunoagueda/a37e03b8a758b9befcc77c4ebe60bb5a

**Comment by anton-sidelnikov** [comment]
thanks! so i found some inconsistency in api, when i send FD00::/64 as remote_ep_group, api returns fd00:0:0:0:0:0:0:0/64, which is brings state inconsistency, in this case i can only recommend you use full ipv6 representation like fd00:0:0:0:0:0:0:0/64 in terraform, i will also create internal ticket regarding this. Resource almost complete.

**Comment by brunoagueda** [comment]
Ok, thank you very much!
