### ISSUE TITLE
opentelekomcloud_rds_instance_v3: DB Engine Version

### ISSUE THREAD

**Issue by deem1978** [opentelekomcloud/terraform-provider-opentelekomcloud#2651]
Hello guys, 
I just need to understand how the definition of the DB Engine version (MySQL in my case, but I suppose it would be the same for PostgreSQL too) works.
I use provider version 1.35.5 and as far as I know starting from provider version 1.26.2, we just have to define the (DB Engine) major version.
My problem/question is that noticed that the patch version is completely randomly (at least so appears to me) applied, I mean I deployed an Instance end of October and the DB Engine Version is the 8.0.28, while an Instance deployed 4 months ago has the 8.0.32 one.
As I need to be sure which version will be deployed in order to prevent to work with some "buggy" version, I would like to know/understand how does it works and how (IF) can I manage the deployment of the exact version that I need.

Please let me know if you need more infos.

Thank you, 
Davide

**Comment by anton-sidelnikov** [comment]
Hi @deem1978, please ask this question to customer support we also only users of API. I only know that you can fetch the available datastore versions by https://rds.eu-de.otc.t-systems.com/v3/{project_id}/datastores/MySQL. And seems impossible to set minor version manually.

**Comment by deem1978** [comment]
Hello @anton-sidelnikov and thank you for your reply. 
I will do, the problem is that I have to understand how can I manage with terraform the engine version that will be deployed, and I am not sure that the customer support will answer to this...
Will let you know.

**Comment by deem1978** [comment]
So it seems that the only reason that could lead to the deployment of an older engine version is if we deploy a new instance from a backup of an older engine version instance. 
I would say it make sense, thank you.
