### ISSUE TITLE
Parser fails for opentelekomcloud_cce_node_pool_v3.cluster_node_pool resource

### ISSUE THREAD

**Issue by ABXayn** [opentelekomcloud/terraform-provider-opentelekomcloud#2654]
The resource `opentelekomcloud_cce_node_pool_v3.cluster_node_pool` fails with an parser error. 
The [OTC API describes for reading a specific CCE node only the field `.spec.nodeTemplate.extendParam.isAutoRenew`](https://docs.otc.t-systems.com/cloud-container-engine/api-ref/apis/cluster_management/reading_a_specified_node.html#cce-02-0243-en-us-topic-0079616779-en-us-topic-0079614912-ref458774242). The field uses a string variant of boolean instead of real boolean value.

This is from the debug log:

```json
      "extendParam": {
        "isAutoPay": "false",
        "isAutoRenew": "false",
        "maxPods": 20
      }
```

The parser fails on the `isAutoPay` field.

Tested with version `v1.36.19`.

**Comment by jansobczak** [comment]
Facing same problem:
```
...
            "extendParam": {
                "isAutoPay": "false",
                "isAutoRenew": "false",
                "maxPods": 80
            },

... 

 into *nodepools.NodePool: json: cannot unmarshal string into Go struct field ExtendParam.spec.nodeTemplate.extendParam.isAutoPay of type bool
```

**Comment by anton-sidelnikov** [comment]
HI @ABXayn please give me more details how did you get this parameters, because for our current version of CCE they are unsupported, or are you trying to set it?

**Comment by ABXayn** [comment]
> HI @ABXayn please give me more details how did you get this parameters, because for our current version of CCE they are unsupported, or are you trying to set it?

We don't use the fields. The problem occurs when the terraform tries to get the node pool information from OTC to compare it with the current state.

**Comment by anton-sidelnikov** [comment]
@ABXayn in which region are you reside, and could you share node_pool config? Strange that our acceptance tests not fails at least for eu-de

**Comment by ABXayn** [comment]
@anton-sidelnikov  The Region is eu-nl.

**Comment by canaykin** [comment]
@anton-sidelnikov Can confirm that the problem exists in eu-de as well. Our existing Terraform managed node pools can no longer run a plan with the same error as described above.

**Comment by chainmywallet** [comment]
We're facing the same error, any fix here?
Also using eu-nl

**Comment by JoKrefting** [comment]
Same issue now starting to happen for us as well in eu-de. 
Last tofu pipeline that worked for us was today:
`September 24, 2024 at 10:59:12 AM GMT+2`
It started to fail with our next pipeline run at:
`September 24, 2024 at 11:09:25 AM GMT+2`

**Comment by krkardos** [comment]
Same issue here in eu-de.
Will be there a fix for it ?

**Comment by anton-sidelnikov** [comment]
@jansobczak @ABXayn @canaykin @chainmywallet @krkardos check latest release please 1.36.20

**Comment by uli-schneider** [comment]
1.36.20 fixes this topic for me.

**Comment by JoKrefting** [comment]
Yes latest version fixed the problem. Thx a lot @anton-sidelnikov 🙌

**Comment by anton-sidelnikov** [comment]
Then will close issue, thanks!

**Comment by ABXayn** [comment]
> @jansobczak @ABXayn @canaykin @chainmywallet @krkardos check latest release please 1.36.20

Works for me, thanks.
