### ISSUE TITLE
Autoscaling Add "LifeCycle Hooks" 

### ISSUE THREAD

**Issue by uli-schneider** [opentelekomcloud/terraform-provider-opentelekomcloud#2656]
# Description of the enhancement
There was a Improvement in Autoscaling Functionality. (Classic ECS-Scaling). 

Please add Lifecycle Hooks to tf-Provider. 
UMN: 
https://docs.otc.t-systems.com/auto-scaling/umn/as_management/scaling_action/managing_lifecycle_hooks.html  
API: 
https://docs.otc.t-systems.com/auto-scaling/api-ref/apis/lifecycle_hooks/index.html

More you can find in the internal reference: OTCPIP-1669

**Comment by anton-sidelnikov** [comment]
Available in v1.36.22, please check.
