### ISSUE TITLE
[Config] - Please add new Service to tf-provider

### ISSUE THREAD

**Issue by uli-schneider** [opentelekomcloud/terraform-provider-opentelekomcloud#2659]
# Description of the enhancement

Add the new function "Config" to terraform provider.
ReleaseNote:
https://www.open-telekom-cloud.com/en/support/release-notes/rms-becomes-config

Documentation (UMN and API) is available. 
https://docs.otc.t-systems.com/config/index.html

Thanks!

**Comment by artem-lifshits** [comment]
@uli-schneider new resources and data sources available in new release.
