### ISSUE TITLE
opentelekomcloud_cce_node_pool_v3 cannot be scaled based on resource utilization / allocation

### ISSUE THREAD

**Issue by canaykin** [opentelekomcloud/terraform-provider-opentelekomcloud#2661]
Greetings, 

While I was investigating an issue for an OTC client, I noticed that the CCE Autoscaler behavior is changed a while ago. 

For resource utilization based autoscaling, the addon used to rely on the following parameters for all node pools:

```
      "scaleDownUtilizationThreshold"  = var.autoscaler_lower_bound
      "scaleUpCpuUtilizationThreshold" = var.autoscaler_cpu_upper_bound
      "scaleUpMemUtilizationThreshold" = var.autoscaler_mem_upper_bound
```

While the scale behavior in case of unschedulability remains the same, it appears that some time ago the behavior is changed for utilization based scaling so that the addon now relies on the node pool autoscaling rules on the individual node pools. I imagine this is done to allow custom scaling behavior on individual pools rather than a single cluster-wide behavior.

![image](https://github.com/user-attachments/assets/073e6769-2c67-4ce7-9e28-7de33757f42d)

Without the addition of the scale rules, the autoscaler will report that the pool is not set for utilization based scaling:
```
W0926 12:37:57.330566       1 scale_up.go:646] nodepool 5ff6a399-xxxx-xxxx-xxxx-02550a100043 is not set for scaleup by utilization
```
Unfortunately, I was unable to find a way to add scale out rules to node pools created via terraform using `opentelekomcloud_cce_node_pool_v3`. As a result, it seems like the only way to enable utilization based scaling is going to the OTC Cloud Console, which is not ideal.

I am unsure if the API is in place for the provider to use, but I believe that this is a feature that will be important for customers who want to use utilization based scaling.

Thank you very much in advance.

**Note:** The actual scaling behavior is based on resource requests and not utilization even though "utilization" and "allocation" is used interchangeably in the addon.

**Note2:** I forgot to mention that, yes, in the screenshot the min nodes and max nodes are set to the same number, which disables the scaling. The screenshot is not from the test cluster I used (which did have a scale range) and is only added to show the configuration section in the Cloud Console.

**Comment by artem-lifshits** [comment]
Hello @canaykin looks like the API isn't updated with scale out rules so we can't implement this change on provider side.
Please contact customer support with this issue and reopen the ticket when it's available.

**Comment by dombisza** [comment]
@canaykin I am already on it. Once we have a demand/bug anything i will post it here.

**Comment by dombisza** [comment]
https://jira.tsi-dev.otc-service.com/browse/OTCPR-20663

**Comment by canaykin** [comment]
Thanks @dombisza for also pointing out that the scaling policies are now offloaded to kubernetes apis via CRDs: https://docs.otc.t-systems.com/cloud-container-engine/umn/auto_scaling/scaling_a_node/creating_a_node_scaling_policy.html

As a result, the [official kubernetes](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs) provider or the [unofficial kubectl provider](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs) should be able to create the resources to configure the scaling policies via kubernetes api rather than CCE.

I would still argue that this is a bit cumbersome due to the limitations of both kubernetes providers (primarily the provider config depending on a resource) but it is a solution nonetheless. 

More specifically, while I am not a fan of the design choice of implementing scaling policies as a CRD, based on this design choice, the API and provider behavior is as it should be (since the kubernetes API is not part of the OTC provider).

@jb392 was the person who first brought this issue to me, and this should provide him with a solution.
