### ISSUE TITLE
opentelekomcloud_compute_instance_v2 does not work correctly in swiss environment

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#2663]
Hello,
the ressource results in an terraform error when getting created or fetching their current state.
As the ressource is getting created succesfully its probaply an parsing issue with the terraform provider but I was unable where exactly the issue after searching for differences in the API responses between eu-de and eu-ch2

# Terraform provider version
provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.36.20

# Affected Resource(s)
opentelekomcloud_compute_instance_v2 ONLY in eu-ch2

# Terraform Configuration Files
resource "opentelekomcloud_compute_instance_v2" "basic_swiss" {
  name            = "basic-tf-swiss"
  image_id        = "609a6199-d7af-4d08-b36f-e07bca5bc672"
  flavor_id       = "s3.large.2"
  key_pair        = "KeyPair"
  security_groups = ["default"]

  network {
    uuid = "63e09ab5-4a36-4294-ab51-b4b7d8f35bb8"
  }
}

# Debug Output/Panic Output
https://gist.github.com/CHS-OTC/f642a98b1d08d8bd88474a57853eee8d

# Steps to Reproduce
1. `terraform apply` in eu-ch2 environment

# Expected Behavior
ECS should be created and correctly added to state and the deployment be completed

# Actual Behavior
ECS is getting created but the deployment is receiving an error

# Important Factoids
auth_url = "https://iam-pub.eu-ch2.sc.otc.t-systems.com/v3"

**Comment by artem-lifshits** [comment]
Hello @CHS-OTC I've prepared a fix that will be available on next release.
However according to [swiss doc api](https://docs.sc.otc.t-systems.com/elastic-cloud-server/api-ref/index.html) compute v2 api (which is used in this resource) isn't supported so I'd recommend switching to `opentelekomcloud_ecs_instance_v1`.

**Comment by CHS-OTC** [comment]
Hello @artem-lifshits 
thanks for the update.

**Comment by sekoban** [comment]
@artem-lifshits
`opentelekomcloud_ecs_instance_v1` doesn't seem to support ecs groups yet, see also  [issues/2665](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/2665)

**Comment by anton-sidelnikov** [comment]
Hi @sekoban available in v1.36.22, please check.

**Comment by sekoban** [comment]
@anton-sidelnikov thanks, works fine
