### ISSUE TITLE
opentelekomcloud_ecs_instance_v1 does not support ecs groups (scheduler_hints)

### ISSUE THREAD

**Issue by sekoban** [opentelekomcloud/terraform-provider-opentelekomcloud#2665]
# Support ECS Groups with opentelekomcloud_ecs_instance_v1 

As described in the API Documentation ECS groups (os:scheduler_hints) can be set along with the creation of an ECS instance, but the module opentelekomcloud_ecs_instance_v1 doesn't seem to support that. However, the module opentelekomcloud_compute_instance_v2 does support it.

* https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/1.36.20/docs/resources/ecs_instance_v1
* https://docs.otc.t-systems.com/elastic-cloud-server/api-ref/apis_recommended/lifecycle_management/creating_an_ecs.html

**Comment by anton-sidelnikov** [comment]
@sekoban Available in v1.36.22, please check

**Comment by sekoban** [comment]
@anton-sidelnikov thank you so much

- If `os_scheduler_hints {}` is missing in the script, Terraform tries replacing the ECS instance over and over again. 
- But documentation says `os_scheduler_hints {}` is optional
- adding `os_scheduler_hints {}` ends this behavior

```
  # module.bastion.opentelekomcloud_ecs_instance_v1.linuxbox must be replaced
-/+ resource "opentelekomcloud_ecs_instance_v1" "linuxbox" {
      ~ auto_recovery               = true -> (known after apply)
      ~ id                          = "10c2c432-***" -> (known after apply)
        name                        = "skoban-th-bastion"
      ~ system_disk_id              = "e5272c56-***" -> (known after apply)
        tags                        = {
            "Environment" = "bar"
            "Terraform"   = "True"
        }
      ~ volumes_attached            = [] -> (known after apply)
        # (9 unchanged attributes hidden)

      ~ nics {
          ~ mac_address = "fa:**:3e:**:6d:**" -> (known after apply)
          ~ port_id     = "03288b25-***" -> (known after apply)
          ~ type        = "fixed" -> (known after apply)
            # (2 unchanged attributes hidden)
        }

      - os_scheduler_hints {} # forces replacement
    }

```

**Comment by anton-sidelnikov** [comment]
@sekoban we did hotfix release for that, please check on v1.36.23

**Comment by sekoban** [comment]
@anton-sidelnikov checked, works fine
