### ISSUE TITLE
Security Group Rules - Excessive time for deletion

### ISSUE THREAD

**Issue by brunoagueda** [opentelekomcloud/terraform-provider-opentelekomcloud#2668]
# Terraform provider version

Terraform v1.8.3
on linux_amd64
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.36.20

# Affected Resource(s)

opentelekomcloud_networking_secgroup_rule_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_networking_secgroup_v2" "secgroup" {
  name                  = local.file_contents.sg_name
  description           = local.file_contents.sg_description
  delete_default_rules  = true
}

resource "opentelekomcloud_networking_secgroup_rule_v2" "name" {
  for_each = { for entry in local.sg_rules : entry.rule_name => entry }

  direction         = each.value.rule_direction
  ethertype         = each.value.rule_ethertype
  protocol          = each.value.rule_protocol
  port_range_min    = each.value.rule_port_range_min
  port_range_max    = each.value.rule_port_range_max
  remote_ip_prefix  = each.value.rule_remote_ip_prefix
  security_group_id = opentelekomcloud_networking_secgroup_v2.secgroup.id
}
```

# Debug Output/Panic Output

https://gist.github.com/brunoagueda/99bf9f53a289653e7f0c462985c7025f

PS: at the end, I cancelled the execution, because it was taking too long

# Steps to Reproduce

1. `terraform plan -destroy -parallelism=1 -out plan.tfplan`
2. `terraform apply -parallelism=1 plan.tfplan`

# Expected Behavior

Deletion of all security group rules in a adequate time frame

# Actual Behavior

Rules are deleted, but each rule takes 8-10 seconds. With a great volume of rules, the whole process takes a very long time

# Important Factoids

We receive sometimes requests for security groups with a high volume of rules (over 500 rules, sometimes over a 1000), and when we need to delete the security group or update the rules, the deletion takes a long time, leading to time out on our pipeline.
To create the rules, it takes around 0-1 second for each rule (nevertheless we need to use the parameter -parallelism=1, otherwise we get an error of "Too many requests have been sent in a given amount of time"). I tested the API directly, and each request takes the same amount of time (0-1 seconds) to be completed, but using terraform module, it takes 9 times longer approximately.
I don't know if this is an actual bug or if it is the expected behavior due to some validation the TF module does or something like that.
Could you please check if there is something to be done with this excessive time for SG rules deletion?

**Comment by anton-sidelnikov** [comment]
Hi @brunoagueda, please try to use "OS_MAX_BACKOFF_RETRIES"=500, "OS_BACKOFF_RETRY_TIMEOUT"=120 and without `-parallelism=1`

**Comment by brunoagueda** [comment]
Hi @anton-sidelnikov 
With this configuration, it goes a faster without the parallelism parameter, not that fast but it is ok. And doesn't break the pipeline with the "Too many requests have been sent in a given amount of time" error.
Thanks!
I will close the issue
