### ISSUE TITLE
[CCE] CCE ControlPlane - Add Default Security for upcoming WorkerNode / NodePools 

### ISSUE THREAD

**Issue by uli-schneider** [opentelekomcloud/terraform-provider-opentelekomcloud#2677]
Since last CCE Release, a new API Parameter is available for the ControlPlane - Creation of CCE.

https://docs.otc.t-systems.com/cloud-container-engine/api-ref/apis/cluster_management/creating_a_cluster.html
Table 6 ...
![image](https://github.com/user-attachments/assets/c16f6c11-1fdc-4663-9327-5f038e749915)

Here you can adda SecurityGroup for upcoming inherited NodePools belongs to this cluster.

Please add this feature to: 
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cce_cluster_v3

Incl. the documentation. 

Consider to add also the hint, that this security must fullfil the Requirements for CCE described here: 
https://docs.otc.t-systems.com/cloud-container-engine/umn/faqs/networking/network_planning/how_can_i_configure_a_security_group_rule_in_a_cluster.html#section1

**Comment by anton-sidelnikov** [comment]
Available in v1.36.22, please check

**Comment by uli-schneider** [comment]
Works for me! 
Thanks for the Implementation.
