### ISSUE TITLE
[CCE] CCE NodePool - Add SecurityGroup Feature for NodePools

### ISSUE THREAD

**Issue by uli-schneider** [opentelekomcloud/terraform-provider-opentelekomcloud#2678]
# Description of the enhancement
Since last CCE Release, a new API Parameter is available for the NodePool - Creation for CCE.

https://docs.otc.t-systems.com/cloud-container-engine/api-ref/apis/cluster_management/creating_a_node_pool.html
Table 5
![image](https://github.com/user-attachments/assets/460e7078-a3e3-48e0-bd2c-c843e6492e4a)

Please add this feature to:
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cce_node_pool_v3

Incl. the documentation.

Consider to add also the hint, that this security must fullfil the Requirements for CCE described here:
https://docs.otc.t-systems.com/cloud-container-engine/umn/faqs/networking/network_planning/how_can_i_configure_a_security_group_rule_in_a_cluster.html#section1

**Comment by anton-sidelnikov** [comment]
Available in v1.36.22, please check.

**Comment by uli-schneider** [comment]
Works for me! 
Thanks for the quick implementation!
