### ISSUE TITLE
Can not accept shared image using opentelekomcloud_images_image_access_accept_v2

### ISSUE THREAD

**Issue by dpakes** [opentelekomcloud/terraform-provider-opentelekomcloud#2686]
# Terraform provider version
v1.36.22

# Affected Resource(s)
opentelekomcloud_images_image_access_accept_v2

# Terraform Configuration Files
```hcl
# Share the image with a specific tenant
resource "opentelekomcloud_images_image_access_v2" "image_share" {
  member_id = var.project_id
  image_id   = var.image_id
}

# Accept the image in a specific tenant
resource "opentelekomcloud_images_image_access_accept_v2" "image_accept" {
  member_id = var.project_id
  image_id   = var.image_id
  status     = "accepted"
}

# Variable for project ID
variable "project_id" {
  description = "The project ID of the tenant to share or accept the image"
  type        = string
  default     = "default"
}

# Variable for image ID
variable "image_id" {
  description = "The image ID to be shared or accepted"
  type        = string
  default     = "default"
}
```

# Debug Output/Panic Output

# Steps to Reproduce

1. `terraform apply -auto-approve -var "project_id=<project_id>" -var "image_id=<ia=image_id>" -target=opentelekomcloud_images_image_access_accept_v2.image_accept`

# Expected Behavior
Shared image is accepted.
Terraform is able to share the image, but when trying to accept it and run opentelekomcloud_images_image_access_accept_v2 the 403 Forbidden happened, even though in GUI via the same user the acceptance is possible.

# Actual Behavior
```htlm
<html>
<head>
<title>403 Forbidden</title>
</head>
<body>
<h1>403 Forbidden</h1>
Not allowed to update members for image d2bd9e44-96f1-40f2-bedb-ee7b612bdfa7.<br />
<br/>
</body> </html>
```
# Important Factoids

# References

**Comment by anton-sidelnikov** [comment]
Hi @dpakes, for accepting you need to provide credentials of member project, here is an example:
```
provider "opentelekomcloud" {
  cloud = "cloud_1"
}

provider "opentelekomcloud" {
  alias = "member"
  cloud = "cloud_2"
}

# Variable for project ID
variable "project_id" {
  description = "The project ID of the tenant to share or accept the image"
  type        = string
  default     = "project_id"
}

# Variable for image ID
variable "image_id" {
  description = "The image ID to be shared or accepted"
  type        = string
  default     = "image_id"
}

# Share the image with a specific tenant
resource "opentelekomcloud_images_image_access_v2" "image_share" {
  provider = opentelekomcloud
  member_id = var.project_id
  image_id   = var.image_id
}

# Accept the image in a specific tenant
resource "opentelekomcloud_images_image_access_accept_v2" "image_accept" {
  provider = opentelekomcloud.member

  depends_on = [opentelekomcloud_images_image_access_v2.image_share]
  member_id = var.project_id
  image_id   = var.image_id
  status     = "accepted"
}
```

**Comment by dpakes** [comment]
I think there is still a problem with opentelekomcloud_images_image_access_accept_v2 resource. 
You need to provide a list of projects to share an image across multiple projects. The current Terraform solution allows you to share only an image with one project as the member_id variable is set to string, not array. 
When trying to share the image via OTC GUI, there is a field to add multiple projects separated by a comma.
Also, OTC API requires an array of strings for members.

Does the current Terraform not support sharing the image with multiple projects, or do I need to use a different approach?

 
![image](https://github.com/user-attachments/assets/a5f5beb8-7ef5-474a-9f17-c782a2fffa36)
![image](https://github.com/user-attachments/assets/5894d947-188b-4c53-b447-0f3de21e28c4)
