### ISSUE TITLE
[IAM] - Agencies - "Feature" for All projects 

### ISSUE THREAD

**Issue by uli-schneider** [opentelekomcloud/terraform-provider-opentelekomcloud#2687]
# Description of the enhancement
There is a new API available in IAM.

https://docs.otc.t-systems.com/identity-access-management/api-ref/apis/agency_management/granting_specified_permissions_to_an_agency_for_all_projects.html

This API is used in Console to grant permissions for an agency for all projects. 

Consider ot add this feature to:
opentelekomcloud_identity_agency_v3

For Role Assignments: 
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/identity_role_assignment_v3
all_projects: 
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/identity_role_assignment_v3#all_projects

Thanks!

**Comment by artem-lifshits** [comment]
@uli-schneider implemented in latest release.

**Comment by uli-schneider** [comment]
Works as expected! 
Thanks!!!
