### ISSUE TITLE
Modify opentelekomcloud_obs_bucket_replication example

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#2695]
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/obs_bucket_replication

It should be edited the "Replicate all objects" Example

Currently it is:
###
variable "bucket" {}
variable "destination_bucket" {}
variable "agency" {}

resource "opentelekomcloud_obs_bucket_replication" "test" {
  bucket             = var.bucket
  destination_bucket = var.destination_bucket
  agency             = var.agency
}
###

I would recommend to change it to the following:
###
variable "bucket" {}
variable "destination_bucket" {}
variable "agency" {}

resource "opentelekomcloud_obs_bucket_replication" "test" {
  bucket             = var.bucket
  destination_bucket = var.destination_bucket
  agency             = var.agency

rule {
  history_enabled = false
  delete_data = false
}
}
###

As this explictily sets the history_enabled and the delete_data on the OTC API side explicitly instead of implictly as this might affect some OTC display of the rules.

**Comment by artem-lifshits** [comment]
Done, available in latest release.
