### ISSUE TITLE
Support Auto AZ Selection Mechanism for ECS

### ISSUE THREAD

**Issue by cboelle** [opentelekomcloud/terraform-provider-opentelekomcloud#2699]
# Description of the enhancement
The new API for ECS supports a random selection based on flavor availability and capacity across all AZ’s. Would be create to have TF support and hint in the documentation how to use.

```
availability_zone = empty 
batch_create_in_multi_az = true
```
https://docs.otc.t-systems.com/elastic-cloud-server/api-ref/apis_recommended/lifecycle_management/creating_an_ecs.html

**Comment by anton-sidelnikov** [comment]
Hi @cboelle, we can't include such attribute into terraform, randomization always gives a huge pain to handle within state, and availability_zone is forceNew parameter we also cant set it as empty. Need to think deeper how to properly handle this.

**Comment by anton-sidelnikov** [comment]
Hi @cboelle available in latest available version 1.36.25
