### ISSUE TITLE
Resource using OTC extended API POST /v1/{project_id}/cloudservers

### ISSUE THREAD

**Issue by liminghui18** [opentelekomcloud/terraform-provider-opentelekomcloud#270]
Hi There,
    There is an extended API to create a ECS based on a Full-backup of an ECS which make ECS creating easier. 
    can you please implement a resource based this API?
    detailed info of API:
https://docs.otc.t-systems.com/en-us/api/ecs/en-us_topic_0020212668.html#EN-US_TOPIC_0020212668__section36291317447

**Comment by niuzhenguo** [comment]
@liminghui18 Seems we only have Creating and Deleting ECS APIs from the Cloud side, but we need a Get API to fetch the details of the cloud servers.

**Comment by niuzhenguo** [comment]
@liminghui18 Will close this due to API limitations, feel free to reopen it when that's available.
