### ISSUE TITLE
[IAM] Security Settings / Password Policy - Password Composition

### ISSUE THREAD

**Issue by uli-schneider** [opentelekomcloud/terraform-provider-opentelekomcloud#2700]
# Description of the enhancement

IAM SecuritySettings offers the possibility to manage "Passwort Composition"  

Console Screenshot: 
![image](https://github.com/user-attachments/assets/c51ead0c-0f9a-4883-bee7-e7bbc16ad4ff)

This parameter is now also added to Help-Center Documentation: 
https://docs.otc.t-systems.com/identity-access-management/api-ref/apis/security_settings/modifying_the_password_policy.html

(Table 4) 

![image](https://github.com/user-attachments/assets/cb4840ef-9be1-4ef5-9425-9ead63e312e0)

Please add parameter to: 
opentelekomcloud_identity_password_policy_v3 

Thanks!

**Comment by anton-sidelnikov** [comment]
Hi @uli-schneider this feature available in latest release v1.36.26

**Comment by uli-schneider** [comment]
I can confirm it is working.
Thanks!
