### ISSUE TITLE
[KMS] Add import of KeyMaterial

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud/terraform-provider-opentelekomcloud#2707]
Hi,

can you implement this in OTC provider please?

Add import of KeyMaterial.

https://github.com/jmcorallo/terraform-aws-kms/blob/main/main.tf#L19

OTC API does support that feature allready but is not available in OTC TF provider yet:

https://docs.otc.t-systems.com/key-management-service/api-ref/apis/cmk_management/importing_cmk_material.html#kms-02-0036

AWS has this feature implemented.

**Comment by anton-sidelnikov** [comment]
Hi @robert1x2, new resource available in latest release 1.36.26
