### ISSUE TITLE
time out when create RDS instance

### ISSUE THREAD

**Issue by TTTouper** [opentelekomcloud/terraform-provider-opentelekomcloud#2713]
# Terraform provider version

1.36.15

# Affected Resource(s)

opentelekomcloud_rds_instance_v3

# Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

# Debug Output/Panic Output

![image](https://github.com/user-attachments/assets/1bd04abb-ef4e-4d43-a079-cee84fca4862)

![image](https://github.com/user-attachments/assets/969a2944-85c1-4e63-82d8-ba5f74d6ac69)

# Steps to Reproduce

1. `terraform init`
2. `terraform apply`

# Expected Behavior

should wait for the creation of RDS to complete

# Actual Behavior

The RDS is stuck in the "creating" state. Does the provider terminate the process? Is it possible to configure the timeout in the script?

# Important Factoids

# References

**Comment by anton-sidelnikov** [comment]
Hi @TTTouper, yes you can: https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/retries-and-customizable-timeouts, for RDS default timeout is 30m, you can change it to 60m for example.

**Comment by artem-lifshits** [comment]
Looks like PreProd issue with RDS, closing the ticket.
