### ISSUE TITLE
opentelekomcloud_images_image_access_v2 should be able to share multiple images to multiple projects

### ISSUE THREAD

**Issue by dpakes** [opentelekomcloud/terraform-provider-opentelekomcloud#2716]
# Description of the enhancement
Currently, the _opentelekomcloud_images_image_access_v2_ resource is using Native OpenStack API _/v2/images/{image_id}/members_ which causes that member_id variable in the resource is string and because of that terraform can share one image with one member only. When trying to run it again with a different _member_id_, it wants to replace the resource with a different member. 

There is an [API](https://docs.otc.t-systems.com/image-management-service/api-ref/ims_apis/image_sharing/adding_image_sharing_members.html) that allows sharing multiple images with multiple projects. This API endpoint requires images and projects to be an array of strings.

This solution is also supported in GUI, where you can provide a list of projects up to 100.
![image](https://github.com/user-attachments/assets/9f08ad40-8ceb-48a0-b592-b8ea9743c925)

Would it be possible to apply such a resource that can share images with multiple projects, or is there another solution for that? 

Thank you in advance,
David

**Comment by anton-sidelnikov** [comment]
Hi @dpakes! New resources available in latest release v1.36.26, which uses other api version:
resource/opentelekomcloud_ims_image_share_v1
resource/opentelekomcloud_ims_image_share_accept_v1
