### ISSUE TITLE
Issue with Terraform Provider Updating Tags

### ISSUE THREAD

**Issue by eriksueto** [opentelekomcloud/terraform-provider-opentelekomcloud#2717]
Expected Behavior: The Terraform provider should be able to update tags without destroying the entire cluster. The configuration of the cluster should remain intact.

Current Behavior: The Terraform provider attempts to delete the entire cluster when changes are made to the tags. This would result in the loss of all cluster configurations.

Steps to Reproduce:

Make changes to the tags in the Terraform configuration.
Apply the changes using the Terraform provider.
Observe that the provider attempts to delete the entire cluster.
Impact: The current behavior leads to the potential loss of all cluster configurations, which is critical for our operations.

**Comment by anton-sidelnikov** [comment]
Not tf issue, internal ticket opened https://jira.tsi-dev.otc-service.com/browse/OTCPR-21476. Will reopen after update of APIs.
