### ISSUE TITLE
[EIP] Request for New Features: The Elastic IP (EIP) Management

### ISSUE THREAD

**Issue by Jambo-sudo** [opentelekomcloud/terraform-provider-opentelekomcloud#2723]
Hello,

Our current workflow revolves around managing The Elastic IP (EIP) instances and their associated functionalities. To optimize these processes, we propose enhancing the following features:

1.Introduce the ability to manages a Shared Bandwidth resource.
2.Introduce the ability to  associates an EIP to a specified shared bandwidth.
3.Introduce the ability to  associates an EIP to a specified IP address or port.

We eagerly await the launch of these features.
Best wishes

**Comment by anton-sidelnikov** [comment]
HI @Jambo-sudo,
these resources already available:
opentelekomcloud_networking_floatingip_associate_v2 (associates an EIP to a specified IP address or port)
opentelekomcloud_vpc_bandwidth_v2 (manages a Shared Bandwidth resource)
opentelekomcloud_vpc_bandwidth_associate_v2 (associates an EIP to a specified shared bandwidth)

**Comment by Jambo-sudo** [comment]
Hello,
is opentelekomcloud_networking_floatingip_associate_v2   associates  an vip or EIP ? we need he ability to associates an EIP to a specified IP address or port.

**Comment by anton-sidelnikov** [comment]
Hi @Jambo-sudo, opentelekomcloud_networking_floatingip_associate_v2 associates an EIP to a specified IP address or port

**Comment by TaoLiu-TSI** [comment]
https://docs.otc.t-systems.com/elastic-ip/api-ref/api_v3/eips/binding_an_eip.html#associatepublicips
@Jambo-sudo @anton-sidelnikov here is the link to API document
