### ISSUE TITLE
[ELB] Request for New Features: Enhancements for Elastic Load Balance (ELB) Management

### ISSUE THREAD

**Issue by Jambo-sudo** [opentelekomcloud/terraform-provider-opentelekomcloud#2724]
Hello,

Our current workflow revolves around managing Elastic Load Balance (ELB)  instances and their associated functionalities. To optimize these processes, we propose enhancing the following features:

Introduce the ability to manage a Dedicated ELB Ip Group resource

We eagerly await the launch of these features.

Best wishes

**Comment by anton-sidelnikov** [comment]
Hi @Jambo-sudo,
already implemented: opentelekomcloud_lb_ipgroup_v3
