### ISSUE TITLE
[VPCED] Request for New Features: Enhancements for VPC Endpoints (VPCED) Management

### ISSUE THREAD

**Issue by Jambo-sudo** [opentelekomcloud/terraform-provider-opentelekomcloud#2725]
Hello,

Our current workflow revolves around managing Distributed VPC Endpoints (VPCED) instances and their associated functionalities. To optimize these processes, we propose enhancing the following features:

Introduce the ability to provides a resource to manage the VPC endpoint connections.

We eagerly await the launch of these features.

Best wishes

**Comment by anton-sidelnikov** [comment]
HI @Jambo-sudo,
already there: opentelekomcloud_vpcep_endpoint_v1 and opentelekomcloud_vpcep_service_v1

**Comment by Jambo-sudo** [comment]
Hi,
  we need the  Interface  of  vpcep_approval like huaweicloud
https://registry.terraform.io/providers/huaweicloud/huaweicloud/latest/docs/resources/vpcep_approval

**Comment by anton-sidelnikov** [comment]
Need to implement new resource based on: https://docs.otc.t-systems.com/vpc-endpoint/api-ref/apis/apis_for_managing_vpc_endpoint_services/accepting_or_rejecting_a_vpc_endpoint.html#vpcep-06-0207, and overall refactoring of endpoint and service resources

**Comment by anton-sidelnikov** [comment]
Hi @Jambo-sudo new resource available in latest 1.36.27 release
