### ISSUE TITLE
[OBS] Request for New Features: Enhancements for Object Storage Service (OBS) Management 

### ISSUE THREAD

**Issue by Jambo-sudo** [opentelekomcloud/terraform-provider-opentelekomcloud#2727]
Hello,

Our current workflow revolves around managing Object Storage Service (OBS) instances and their associated functionalities. To optimize these processes, we propose enhancing the following features:

1. Introduce the ability to manage an OBS bucket acl resource
2. Introduce the ability to manage an OBS bucket object acl resource

We eagerly await the launch of these features.

Best wishes

**Comment by artem-lifshits** [comment]
Hello @Jambo-sudo resources introduced in latest release.
