### ISSUE TITLE
Importer for RDS v3

### ISSUE THREAD

**Issue by tstrohmeier** [opentelekomcloud/terraform-provider-opentelekomcloud#273]
Hi!

### Provider Version
v 1.8.0

### Affected Resource(s)
- opentelekomcloud_rds_instance_v3

### Expected Behavior
I want to import the existing database resource.

### Actual Behavior
I get the following error:
`Error: opentelekomcloud_rds_instance_v3.instance_1 .... resource opentelekomcloud_rds_instance_v3 doesn't support import`

### Steps to Reproduce
1. `terraform import opentelekomcloud_rds_instance_v3.instance_1 <instance_id>`

### References
- #251 
- #267

**Comment by tstrohmeier** [comment]
@niuzhenguo In RDS v1 you use a `ResourceImporter` with `ImportStatePassthrough`. Would this work for RDS v3 too?

**Comment by niuzhenguo** [comment]
@tstrohmeier We tried that but unfortranately we can't read some required attributes from the API response which causes force-new issue with apply after import the rds v3 resource.

**Comment by tstrohmeier** [comment]
@niuzhenguo Do I get this right from the PR that `availability_zone`, `db.type`, `db.version`, `db.port` and `db.password` are the required attributes, which are missing?

The RDS API v3 has a query endpoint which returns all of this attributes, except the password. 
https://docs.otc.t-systems.com/en-us/api/rds/en-us_topic_0160329148.html
Table 3: `instances[i].port`
Table 5: `instances[i].datastore.type` `instances[i].datastore.version`
Table 8: `instances[i].nodes[x].availability_zone`

Is it possible to map them into the resource's schema?

**Comment by niuzhenguo** [comment]
@tstrohmeier Only `availability_zone` and `db.password`.
instances[i].nodes[x].availability_zone is availability_zone of each node, but seems it's possible to construct the availability_zone with them like [nodes[0].availability_zone, nodes[1].availability_zone]

**Comment by tstrohmeier** [comment]
@niuzhenguo Ok. 
* This was also my thought to iterate over the nodes and put the availability_zone into the array.
* Can we skip `db.password` in the import?

**Comment by niuzhenguo** [comment]
@tstrohmeier I can fix the availability_zone issue, but don't find a way to sikip db.password in the import. You need to use ignore_changes on your scripts during import to avoid that issue.

**Comment by tstrohmeier** [comment]
@niuzhenguo Ok. Thank you!
