### ISSUE TITLE
[DCS] Request for New Features: Enhancements for Distributed Cache Service (DCS) Management

### ISSUE THREAD

**Issue by Jambo-sudo** [opentelekomcloud/terraform-provider-opentelekomcloud#2737]
Hello,

Our current workflow revolves around managing Distributed Cache Service (DCS)  instances and their associated functionalities. To optimize these processes, we propose enhancing the following features:

Introduce the ability to manage a DCS account resource.

We eagerly await the launch of these features.

Best wishes

**Comment by anton-sidelnikov** [comment]
Hi @Jambo-sudo, dcs resources already there:
```
opentelekomcloud_dcs_instance_v1
opentelekomcloud_dcs_instance_v2
```
