### ISSUE TITLE
[Kafka] Request for enhance:  Specify Partition Range to 200 When Creating Kafka Topic

### ISSUE THREAD

**Issue by Jambo-sudo** [opentelekomcloud/terraform-provider-opentelekomcloud#2741]
# Description of the enhancement
Hello Team,

I'd like to request a new feature that allows users to specify the range of partitions, specifically up to 200 (current is 20), when creating a Kafka Topic.
This would enable users to optimize Kafka Topic configurations for their specific use cases, and we look forward to providing more information if necessary.

Best

**Comment by TaoLiu-TSI** [comment]
https://docs.otc.t-systems.com/distributed-message-service/api-ref/apis_v2_recommended/topic_management/creating_a_topic_for_a_kafka_instance.html#createinstancetopic
![image](https://github.com/user-attachments/assets/641705ef-11e4-4397-a4da-3478c71a65c5)

**Comment by artem-lifshits** [comment]
@Jambo-sudo new resource `opentelekomcloud_dms_topic_v2` introduced in latest release, please check.
