### ISSUE TITLE
Please Support ELB v3 APIs

### ISSUE THREAD

**Issue by TaoLiu-TSI** [opentelekomcloud/terraform-provider-opentelekomcloud#2742]
# Description of the enhancement
https://docs.otc.t-systems.com/elastic-load-balancing/api-ref/apis_v3/load_balancer/creating_a_load_balancer.html
one Customer need to functions in ELB v3 APIs
![image](https://github.com/user-attachments/assets/f72d8dd8-e421-4f79-acad-d5d12d8e83c1)

please help!

**Comment by TaoLiu-TSI** [comment]
@Jambo-sudo

**Comment by anton-sidelnikov** [comment]
Hi @TaoLiu-TSI this resources already supported, please look at documentation: https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_loadbalancer_v3
 https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_listener_v3
 https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_certificate_v3
 https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_ipgroup_v3
 https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_member_v3
 https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_monitor_v3
 https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_policy_v3
 https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_pool_v3
 https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_rule_v3
 https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/lb_security_policy_v3
