### ISSUE TITLE
[IAM] Manage users security settings

### ISSUE THREAD

**Issue by bascht** [opentelekomcloud/terraform-provider-opentelekomcloud#2747]
# Description of the enhancement

We're trying to toggle the [Access Key Management](
https://docs.otc.t-systems.com/identity-access-management/umn/user_guide/security_settings/critical_operation_protection.html#access-key-management) property of our OTC account. It seems like this property is set on the account level and applied to all users (much like `opentelekomcloud_identity_protection_policy_v3`) - but we couldn't find any Terraform resource to manage it.

![Screenshot-2024-11-26-125631](https://github.com/user-attachments/assets/d6a9dd1f-4f52-40f9-bfd3-68639d74430c)

Is this on the something that's on the road-map?

**Comment by anton-sidelnikov** [comment]
HI @bascht new features available in latest 1.36.27 release
