### ISSUE TITLE
Security_groups should disassociate their instaces first

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#282]
What I did:

- changed AZs from two to three (ECS)
- changed the number of security group rules

This resultes in:
1. recreating a few instances and build them in all three givven availability zones first.
2. try to destroy SGs + SG-rules and ran into a timeout....

### Terraform Version
```hcl
$ terraform -version
Terraform v0.11.14
+ provider.dns v2.1.1
+ provider.local v1.2.2
+ provider.null v2.1.2
+ provider.openstack v1.18.0
+ provider.opentelekomcloud v1.8.0
+ provider.template v2.1.2

```

### Affected Resource(s)
Please list the resources as a list, for example:
- opentelekomcloud_compute_secgroup_v2
- opentelekomcloud_networking_secgroup_rule_v2
- opentelekomcloud_rds_instance_v1
- opentelekomcloud_compute_instance_v2

### Terraform Code
Module main.tf
```hcl
resource "opentelekomcloud_networking_secgroup_v2" "security_group" {
  name                 = "${var.security_group_name}"
  description          = "${var.security_group_description}"
  delete_default_rules = "${var.delete_default_rules}"
}

resource "opentelekomcloud_networking_secgroup_rule_v2" "security_group_rule" {
  count             = "${var.number_of_secgroup_rules}"
  direction         = "${lookup(var.secgroup_rules[count.index], "direction", "ingress")}"
  ethertype         = "${lookup(var.secgroup_rules[count.index], "ethertype", "IPv4")}"
  protocol          = "${lookup(var.secgroup_rules[count.index], "protocol")}"
  port_range_min    = "${lookup(var.secgroup_rules[count.index], "port_range_min")}"
  port_range_max    = "${lookup(var.secgroup_rules[count.index], "port_range_max")}"
  remote_ip_prefix  = "${lookup(var.secgroup_rules[count.index], "remote_ip_cidr")}"
  security_group_id = "${opentelekomcloud_networking_secgroup_v2.security_group.id}"
}

```
#### Module call:
```hcl
module "sg_some_access" {
  source = "git::ssh://git@<myGit>/security_group.git"

  project_name               = "myProject"
  security_group_name        = "sg_some_access"
  security_group_description = "Access from anyhere"

  #
  #
  # ------------------------------
  # THIS MUST BE SET MANUALLY WHEN CHANGING NUMBER OF SEC GROUPS
  number_of_secgroup_rules = "1"
  # ------------------------------
  secgroup_rules = [
    #
    # 
    #
    { direction = "ingress" ethertype = "IPv4" protocol = "tcp" port_range_min = "<somePort>" port_range_max = "<somePort>" remote_ip_cidr = "subnetX" },
  ]
}
```
##### my change:
Here i just added a new rule: 

```hcl
[...]
  # ------------------------------
  # THIS MUST BE SET MANUALLY WHEN CHANGING NUMBER OF SEC GROUPS
  number_of_secgroup_rules = "2"
  # ------------------------------
  secgroup_rules = [
    #
    # 
    #
    { direction = "ingress" ethertype = "IPv4" protocol = "tcp" port_range_min = "<somePort>" port_range_max = "<somePort>" remote_ip_cidr = "subnetX" },
{ direction = "ingress" ethertype = "IPv4" protocol = "tcp" port_range_min = "<somePort2>" port_range_max = "<somePort2>" remote_ip_cidr = "subnetX" },
  ]
[...]
```

And the ECS module call:
```hcl
module "ecs" {
  source = "git::ssh://git@<myGit>/ecs_instance.git"

  network_name          = "${module.global_vars.subnet_names[1]}"
  domain_name           = "${module.global_vars.domain_name}"
  subnet_id             = "${module.network.subnet_id}"
  public_dns_zone_id    = "${module.public_dns_zone.public_zone_id}"
  private_dns_zone_id   = "${module.private_dns_zone.private_zone_id}"
  key_pair_name         = "${module.global_vars.key_pair_name}"
  stage                 = "${module.global_vars.stage}"
  instance_count        = "${var.ecs_instance_count}"
  project_name          = "myProject"
  ecs_purpose           = "purposeXYZ"
  ecs_image_name        = "myFlavor"
  ecs_systemdisk_size   = "${var.ecs_systemdisk_size}"
  ecs_instance_priv_ips = "${var.ecs_priv_ips}"
  ecs_volume_type       = "${var.ecs_volume_type}"
  ecs_flavor            = "${var.ecs_flavor}"
  security_groups       = ["sg_some_access",
                           "sg_some_access2",
                           "sg_some_access3",
                           "sg_some_access4"]

  delete_on_termination = "true"
  ecs_eip_associate     = "false"
}
```

### Expected Behavior
**ECS:** Terraform should first disassociate all their `Associated Instances` before trying to delete the security group itself. 
**RDS**: Terraform tries to delete the SG but this is still associated to RDS, I needed to manually change the SG so that TF can delete and create the SG

### Actual Behavior
**ECS:** Terraform tries to delete the security group but since it has `Associated Instances` it is unable to and waits till the timeout of (default) 10minutes are reached. I could work around it by deleting the SGs by hand while terraform was running....

**RDS:** Terraform tries to delete the SG but this is still associated to RDS, I needed to manually change the SG so that TF can delete and create the SG...and associate it back again after TF finished manually.

**Comment by Moep90** [comment]
@niuzhenguo 

Are there any plans to address this?
My current workaround is to run the `terraform apply` while removing the assosicated instances from the SG manually via the UI.

**Comment by niuzhenguo** [comment]
@Moep90 Sorry for the late resposne, I was thinking that if it's possible to disassociate the SG from instances in scripts as we support to update instance SGs. And add it back later, but seems also a workaround.
I'm a little worried about disassociating all the associated instances automatically before deleting the security group as some instances within the same tenant my not created by you.

**Comment by Moep90** [comment]
@niuzhenguo I understand this but I dont know how this works on other Cloud-Providers.
Manually delete should not be the necessary.

**Comment by niuzhenguo** [comment]
@Moep90 Why change security group rules cause security group recreating? I think it should only update the rules itself.

**Comment by Moep90** [comment]
@niuzhenguo I hoped to get the information from you. I dont get why it works like that either...

**Comment by outcatcher** [comment]
I suppose, the response is a bit outdated for now, but maybe there are people facing the same problem nowadays.

Described behavior happens when there is no clear relation between SG and resource for the terraform.

If Security Group is bound the following way:

```hcl

resource "opentelekomcloud_networking_secgroup_v2" "sec_group" {
  name = "simple-test-sg"
}

resource "opentelekomcloud_compute_instance_v2" "instance" {
...

  security_groups = [opentelekomcloud_networking_secgroup_v2.sec_group.name]
  
}

```

For terraform `instance` will be considered to be depending on the `sec_group`: the creation of the instance` will start after the end of the creation of the `sec_group`, and destruction of the `sec_group` will start after the end of `instance` destruction.

In case of ECS destruction, it's enough to get rid of the problem described in the original issue.

In the case of RDS destruction, there are issues with orphaned implicit resources blocking the correct cleanup process. This is a platform problem and can't be easily fixed from the client side.

**Comment by outcatcher** [comment]
Also, changing sec group rules count and changing instance count won't trigger security group recreation now. Please comment if there are still problems related to the issue topic.
