### ISSUE TITLE
[REQUEST] Support extended ACL in  opentelekomcloud_sfs_file_system_v2

### ISSUE THREAD

**Issue by tasansga** [opentelekomcloud/terraform-provider-opentelekomcloud#292]
OpenTelekomCloud Console has the ability to add several extended ACL entries, with restrictions for address segments, rw/ro as well as user- and root permission squash, for opentelekomcloud_sfs_file_system_v2 resources.

![opentelekomcloud_sfs_access](https://user-images.githubusercontent.com/22353635/58682766-23b3b100-8372-11e9-809c-ab9bdc3022ce.png)

It currently seems not possible to create those ACL with terraform. The available openstack_sharedfilesystem_share_access_v2 type only offers a subset of those options.

**Comment by niuzhenguo** [comment]
@tasansga I find the corresponding API for that on OTC https://docs.otc.t-systems.com/en-us/api/sfs/en-us_topic_0076922215.html , will test with that first.

**Comment by niuzhenguo** [comment]
@tasansga From the OTC API above, it's same with the openstack_sharefilesystem_share_access_v2. It seems not possible to add that on Terraform side, but you can contact a support on OTC to expose the API as Console.

**Comment by tasansga** [comment]
@niuzhenguo Thanks a lot for your help! I've contacted their support, let's see what they'll do. I'll close here for now and reopen when OTC makes it possible.
