### ISSUE TITLE
opentelekomcloud_vpc_peering_connection_v2 errors with missing input [RequestVpcInfo]

### ISSUE THREAD

**Issue by Tom-Mann** [opentelekomcloud/terraform-provider-opentelekomcloud#294]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.11.10
+ provider.opentelekomcloud v1.8.0

### Affected Resource(s)
Please list the resources as a list, for example:

- opentelekomcloud_vpc_peering_connection_v2

### Terraform Configuration Files
```hcl

resource "opentelekomcloud_vpc_peering_connection_v2" "CIS_peering" {
  name        = "${var.cis_peering_name}"
  vpc_id      = "${var.netvNETVpcID}"
  peer_vpc_id = "${var.prCISVPCID}"
}

```

### Debug Output
* opentelekomcloud_vpc_peering_connection_v2.CIS_peering: Error creating OpenTelekomCloud Vpc Peering Connection: Missing input for argument [RequestVpcInfo]
2019/06/03 11:40:04 [TRACE] [walkApply] Exiting eval tree: module.Project.module.peering.opentelekomcloud_vpc_peering_connection_v2.CIS_peering
2019/06/03 11:40:04 [ERROR] root.Project.peering: eval: *terraform.EvalApplyPost, err: 1 error(s) occurred:

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
The VPC should peer

### Actual Behavior
It errors with Missing input for argument [RequestVpcInfo]

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Which version of OpenTelekomCloud? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by niuzhenguo** [comment]
@Tom-Mann I tried on my local env but can't reproduce your errors. 
The "missing input [RequestVpcInfo]" happens usually because the vpc_id missing or set to be "", please check your scripts and variables.
