### ISSUE TITLE
Deploying (`terraform apply`) a opentelekomcloud_csbs_backup_policy_v1 twice fails

### ISSUE THREAD

**Issue by tasansga** [opentelekomcloud/terraform-provider-opentelekomcloud#298]
Deploying (`terraform apply`) a opentelekomcloud_csbs_backup_policy_v1 twice fails

### Terraform Version
```
$ terraform -v
Terraform v0.11.14
+ provider.opentelekomcloud v1.8.0
```
### Affected Resource(s)
`opentelekomcloud_csbs_backup_policy_v1`

### Expected Behavior
When running `terraform apply` I expect it to pick up and update the existing opentelekomcloud_csbs_backup_policy_v1 with the same name.

### Actual Behavior
An error is raised from OTC the 2nd time:
```
	* module.portal.opentelekomcloud_csbs_backup_policy_v1.backup: 1 error occurred:
	* opentelekomcloud_csbs_backup_policy_v1.backup_monthly.0: Error creating Backup Policy : Bad request with: [POST https://xxx.t-systems.com/v1/xxx/policies], error message: {"error_code": "CSBS.6004", "error_msg": "{\"msg\": \"The resource xxx is already in service.\", \"plan_id\": \"xxx\", \"plan_name\": \"backup-daily\"}"}
```

`terraform plan` simply says it'll create the resource new without conflict.

### Steps to Reproduce
Create a `main.tf` like this and apply it twice:
```
resource "opentelekomcloud_compute_instance_v2" "test" {
  name      = "test"
  flavor_id = "flavor"
}

resource "opentelekomcloud_csbs_backup_policy_v1" "backup" {
  name  = "backup"

  resource {
    id   = "${opentelekomcloud_compute_instance_v2.test.id}"
    type = "OS::Nova::Server"
    name = "${opentelekomcloud_compute_instance_v2.test.name}"
  }

  scheduled_operation {
    enabled         = false
    max_backups     = 7
    operation_type  = "backup"
    trigger_pattern = "BEGIN:VCALENDAR\r\nBEGIN:VEVENT\r\nRRULE:FREQ=DAILY;INTERVAL=1;BYHOUR=3;BYMINUTE=27\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n"
  }
}
```

**Comment by niuzhenguo** [comment]
@tasansga As the error message said, the csbs_backup_policy.name should be unique.

**Comment by tasansga** [comment]
@niuzhenguo Yes, so Terraform should update and not add it another time, right?

**Comment by niuzhenguo** [comment]
@tasansga Yes, it should update or destroy and create again instead of raising the conflict error, but I can't reproduce your errors, can you please show more debug logs?

**Comment by tasansga** [comment]
This behaviour changed when Deutsche Telekom updated their OTC production environment last Thursday. Now applying several times doesn't fail anymore, instead terraform performs an update as expected.
