### ISSUE TITLE
Create project and peer with other VPC's in one script

### ISSUE THREAD

**Issue by Tom-Mann** [opentelekomcloud/terraform-provider-opentelekomcloud#299]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
Would like to be able to create a new project that is configured in a single script, this includes peering to external tennants.

### Actual Behavior
What actually happened?
Would seem this is not possible at the moment as the providers are calculated at start so even with using aliases I'm unable to create extra providers to handle the use case I have.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create a terraform script that creates a project and peers to another tennants vpc
2. create aliased providers so that your account logs into your newly created project to start peering process.
3. above isnt possible.

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Which version of OpenTelekomCloud? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by niuzhenguo** [comment]
@Tom-Mann Unfortunately that's not possible. Authentication is done in the overarching provider block.

**Comment by Tom-Mann** [comment]
Thanks @niuzhenguo. To me what needs changing is user A creates the project and has permissions to the project, currently you need user B to login to the new project, to create the peering this is why this is not possible. In regards to the provider block you can use multiple provider blocks with the alias flag, however as mentioned because the user who creates the project needs to log out and back in its not possible. If this was fixed the above request is possible.
feel free to close, just wanted to raise that this is problematic.

**Comment by niuzhenguo** [comment]
@Tom-Mann Thanks for raising this, let's just keep this open. I will dig more and give feedbacks here.

**Comment by outcatcher** [comment]
@Tom-Mann If you're still using the provider, can you please check if the issue is still reproducing?

**Comment by outcatcher** [comment]
No interaction for a prolonged period of time. Will reopen if needed again.
