### ISSUE TITLE
Missing 'auto_recovery' variable in docs

### ISSUE THREAD

**Issue by niuzhenguo** [opentelekomcloud/terraform-provider-opentelekomcloud#30]
The 'auto_recovery' variable is not documented in the [compute_instance_v2](https://github.com/terraform-providers/terraform-provider-opentelekomcloud/blob/master/website/docs/r/compute_instance_v2.html.markdown) docs.

**Comment by zengchen1024** [comment]
@niuzhenguo yes, I will update the doc. Thanks for reminding!
