### ISSUE TITLE
example create a project with vpc + subnet

### ISSUE THREAD

**Issue by Tom-Mann** [opentelekomcloud/terraform-provider-opentelekomcloud#301]
Could you provide an example on how to create a project with vpc and subnet.

**Comment by niuzhenguo** [comment]
@Tom-Mann It's not possible to create a project with resouces in one script. You need to create a project then add a provider definition with the new created project to create resources within it.

**Comment by Chrakker** [comment]
@Tom-Mann You can check the documentation to VPC creation [VPC Doc](https://www.terraform.io/docs/providers/opentelekomcloud/d/vpc_v1.html) as well as the Subnet Creation which referenced the VPC [Subnet Doc](https://www.terraform.io/docs/providers/opentelekomcloud/d/vpc_subnet_v1.html)

You should be able to incorporate the already given exmaples in the documentation into an existing terraform project of yours.

I do also not see a possiblity to give a generic handout creation, which needs to be updated and maintained throughout the lifecycle.

**Comment by Tom-Mann** [comment]
Hey, as mentioned by @niuzhenguo my request is not possible. you need two separate terraform files one to create the project and the second for the vpc.  The request isnt for a one off, it was highlighting a common requirement creating a new area is not possible

**Comment by Chrakker** [comment]
Thanks for the clarification @Tom-Mann, please disregard my comment in this case.

**Comment by outcatcher** [comment]
Question seems to be solved
@Tom-Mann please comment if you need this issue
