### ISSUE TITLE
MRS volume configuration.

### ISSUE THREAD

**Issue by lushanlushan** [opentelekomcloud/terraform-provider-opentelekomcloud#306]
Hi, 

In OTC MRS, if defining every data node has 3 volumes with 350 GB of space. In the ui is a field “core_volume_count” and “core_volume_size” for this definition but not in terraform (https://www.terraform.io/docs/providers/opentelekomcloud/r/mrs_cluster_v1.html). 

Could we support that?

**Comment by niuzhenguo** [comment]
@lushanlushan Thanks for raising this, I will be working on it.
