### ISSUE TITLE
Project already exists, Terraform wants to create a new one

### ISSUE THREAD

**Issue by Tommy-Ten** [opentelekomcloud/terraform-provider-opentelekomcloud#318]
### Terraform Version

Terraform v0.11.14
+ provider.opentelekomcloud v1.9.0

### Affected Resource(s)

opentelekomcloud_identity_project_v3

### Terraform Configuration Files

resource "opentelekomcloud_identity_project_v3" "project" {
  name        = "${var.prProjectName}"
  description = "${var.prProjectDescription}"
}

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Terraform should recognise that the project already exists.

### Actual Behavior

Terraform wants to create the same resource without any changes done to the project name or variables

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`

Once the project has been created run

1. `terraform plan`

TF wants to create the same resource again:

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + opentelekomcloud_identity_project_v3.project
      id:          <computed>
      description: "test"
      domain_id:   <computed>
      enabled:     <computed>
      is_domain:   <computed>
      name:        "eu-de_project2"
      parent_id:   <computed>
      region:      <computed>

Plan: 1 to add, 0 to change, 0 to destroy.

### Important Factoids

N/A

### References

N/A

**Comment by Tommy-Ten** [comment]
Hi @niuzhenguo,

Thank you for your response to this issue. I understand that this will be addressed in the next provider version v1.10.0?

**Comment by niuzhenguo** [comment]
@MrTommyTen Yes, it will be addressed in the next release.

**Comment by Tommy-Ten** [comment]
@niuzhenguo Great, thanks for confirming.
