### ISSUE TITLE
Image search

### ISSUE THREAD

**Issue by Tom-Mann** [opentelekomcloud/terraform-provider-opentelekomcloud#329]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.12.3
+ provider.dns v2.1.1
+ provider.opentelekomcloud v1.10.0

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume

opentelekomcloud_images_image_v2

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

data "opentelekomcloud_images_image_v2" "LinuxImage" {
  most_recent = true
  visibility  = "shared"

  properties = {
    __os_type = "Linux"
  }

  tag = "project.default"
}

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

we can query via api
{
            "resource_name": "rhel7_OTC_nonprod_20190629",
            "resource_detail": {
                "status": "active"
            },
            "tags": [
                {
                    "value": "default",
                    "key": "project"
                }
            ],

but terraform returns 

Error: Your query returned no results. Please change your search criteria and try again.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

The image search should return images with the specified filter

### Actual Behavior
What actually happened?

adding the tag filter on shared images returns nothing.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Which version of OpenTelekomCloud? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by niuzhenguo** [comment]
@Tom-Mann Can you provide the API query rquest details

**Comment by niuzhenguo** [comment]
@Tom-Mann Seems we don't support key.value pattern tag, can you try to add a tag with only Key and empty Value, then try to search it with image data source.

**Comment by Tom-Mann** [comment]
@niuzhenguo Thanks, searching purely on the key works (or at least doesn't error).
Do you intend to add support for key.value or should we change our tagging to purely key based (not so nice)

**Comment by niuzhenguo** [comment]
@Tom-Mann The image query API doesn't support that key.value pattern, so it doesn't work on Terraform side.

**Comment by niuzhenguo** [comment]
@Tom-Mann Please try key=value pattern.
```
data "opentelekomcloud_images_image_v2" "LinuxImage" {
most_recent = true
visibility = "shared"

properties = {
__os_type = "Linux"
}

tag = "project=default"
}
```

**Comment by niuzhenguo** [comment]
@Tom-Mann Does the solution above work?

**Comment by Tom-Mann** [comment]
Sorry been working on other things, will test today.

**Comment by lushanlushan** [comment]
Hello, is there any update of this issue? Thank you.

**Comment by niuzhenguo** [comment]
Closing this, please feel free to reopen it if there are still problems.
