### ISSUE TITLE
changing RDS port shouldn't recreate the instance

### ISSUE THREAD

**Issue by EugenFo** [opentelekomcloud/terraform-provider-opentelekomcloud#336]
Hi there,
when changing the port of an existing RDS instance Terraform shouldn't recreate the instance. When you change the port over the UI the instance will just restart.

### Terraform Version
0.11.14

### Affected Resource(s)
opentelekomcloud_rds_instance_v1

### Expected Behavior
The RDS instance should just restart.

### Actual Behavior
Terraform recreates the RDS instance.

![Screenshot from 2019-07-26 15-58-14](https://user-images.githubusercontent.com/44065655/61957280-2bcd4d00-afbf-11e9-838b-c027319c36c2.png)

**Comment by niuzhenguo** [comment]
@EugenFo I didn't find an API to make that possible https://docs.otc.t-systems.com/en-us/api/rds/en-us_topic_0160329112.html

**Comment by Moep90** [comment]
@niuzhenguo when doing so via the UI, it just restarts the instance.
I dont know if there is any way to achive this with Terraform?

**Comment by niuzhenguo** [comment]
@Moep90 I couldn't fin any hint on API docs, you can open a support request on Cloud side.

**Comment by Moep90** [comment]
@niuzhenguo I did the answer was:
```
[...]
the port change is not been supported through API now, R&D team plan to support this at end of the year.

The port change needs a reboot of the instance.
[...]
```

**Comment by niuzhenguo** [comment]
@Moep90 Thanks for the feedbacks, we will add that support when it's available through API.

**Comment by tstrohmeier** [comment]
@niuzhenguo @Moep90  It's the same with RDS v3 as far as I know.

**Comment by outcatcher** [comment]
Internal incident is missing

**Comment by Moep90** [comment]
> Internal incident is missing

Well well..... organization is key: IM0026750445

**Comment by outcatcher** [comment]
@Moep90 Thanks :) funny that it has resolved status, but this seems to be not implemented. I will create an internal incident.

**Comment by Moep90** [comment]
You describe the problem of the whole otc support structure. Dealing with it since almost 2 years now...

**Comment by outcatcher** [comment]
Internal issue: https://jira.tsi-dev.otc-service.com/browse/XAAS-6691

**Comment by Aloento** [comment]
moved to DM-2465

**Comment by artem-lifshits** [comment]
RDS v1 support is discontinued, please use RDS v3 instead (recently port change api was released and team is working on implementation).
