### ISSUE TITLE
AK/SK login fails, Password login fails with 2FA enabled

### ISSUE THREAD

**Issue by dev00** [opentelekomcloud/terraform-provider-opentelekomcloud#343]
### Terraform Version
```
linux@extbuilder:~/terraform$ terraform --version
Terraform v0.12.6
+ provider.opentelekomcloud v1.11.0
```
### Affected Resource(s)
- opentelekomcloud provider

### Terraform Configuration Files
```hcl
provider "opentelekomcloud" {
  auth_url = "https://iam.eu-de.otc.t-systems.com:443/v3"
  tenant_name = "eu-de_mysubproject"
  domain_name = "OTC00000000001000000XXX"
  access_key = "foobar"
  secret_key = "secretfoobar"
}
```

### Debug Output
````
Error: Unable to find iam with name OTC00000000001000000XXX

  on buildenv.tf line 45, in provider "opentelekomcloud":
  45: provider "opentelekomcloud" {
````

### Expected Behavior
terraform should login using ak/sk credentials

### Actual Behavior
Login fails

### Steps to Reproduce
1. possibly create a subproject
2. configure provider to login using AK/SK
3. insert credentials
4. `tf plan`

### Important Factoids
AK/SK is needed as the regular login with username and password **fails** when 2FA is enabled. If possible, maybe allow usage of 2FA as well? The shown setup works just fine with username and password if 2FA is not enabled.

### References
- https://github.com/terraform-providers/terraform-provider-opentelekomcloud/issues/143
- https://github.com/terraform-providers/terraform-provider-opentelekomcloud/pull/157

**Comment by niuzhenguo** [comment]
@dev00 Thanks for raising this. Is that OK for ak/sk login with 2FA disabled for your account? I suppose the API request blocked on Cloud side if 2FA enabled, will dig more.

**Comment by YiliWang** [comment]
Do you enable 2FA in your account(myCredential)?
![image](https://user-images.githubusercontent.com/10427340/62590482-16c9b580-b8ff-11e9-95fb-a5024ae9ab16.png)

**Comment by dev00** [comment]
@niuzhenguo 

1. 2FA Disabled, Login via Name/Password:
    `works`
2. 2FA Disabled, Login via AK/SK:
    `Error: Unable to find iam with name OTC00000000001000000XXX`
3. 2FA Enabled, Login via Name/Password:
    `Error: Authentication failed`
4. 2FA Enabled, Login via AK/SK:
    `Error: Unable to find iam with name OTC00000000001000000XXX`

Hope this clarifies it a bit for you? I don't think the AK/SK topic and the 2FA problem are connected, this was just an explaination why AK/SK auth is needed :)

**Comment by niuzhenguo** [comment]
@dev00 I just tested and all works fine. 
1. 2FA Disabled, Login via Name/Password and AK/SK both work
2. 2FA Enabled, Login via Name/Password failed but AK/SK worked.

Can you show your debug logs? and seems you use a wrong Domain name.

**Comment by dev00** [comment]
@niuzhenguo I didn't change the Domain name, just replaced `user_name` and `password` with `access_key` and `secret_key`. So unless TF expects other values for `domain_name` or `tenant_name` when working with AK/SK rather than Username/PW, I feel like I miss something here if it worked for you.

I also ensured all `OS_` variables were unset and that there was also no `clouds.yaml` file placed somewhere so terraform was forced to use the values supplied to the provider. Can you tell me which attributes (domain_name, tenant_name... ?) you used for the otc provider?

I'll add logs, even though I didn't see any relevant things about the login issue :/

EDIT:
[The Gist](https://gist.github.com/dev00/fa064fafcafbb2db7daeddae763e3559)
I just had an idea... Is it possible my user is lacking the permisssions to log in via AK/SK? As I'm currently not using a user with full permissions on this Domain... In that case the error message could be considered a little bit missleading *thinks*

**Comment by niuzhenguo** [comment]
@dev00 can you try without domain_name?

**Comment by dev00** [comment]
@niuzhenguo leaving `domain_name` out and just keeping `tenant_name` works. Can we consider that a bug, atleast in the docs?

Thx at this point for the fast reply and help :)

**Comment by niuzhenguo** [comment]
@dev00 domain_name is not a required option, only when needs domain level authentication.

**Comment by dev00** [comment]
@niuzhenguo I was following [the docs](https://www.terraform.io/docs/providers/opentelekomcloud/index.html#aksk), which do not only name the domain_name in the example, but also call it `required` in the [configuration reference](https://www.terraform.io/docs/providers/opentelekomcloud/index.html#configuration-reference).

So from my point of view:
- remove the `domain_name` from the AK/SK example in the docs
- maybe add some kind of FAQ (or better FEQ, frequently encountered errors) explaining the auth strategies and the parameters/scopes (or atleast link it) 
- the tf error message should be changed and atleast hint that unsetting `domain_name` can fix that (because no way I would have figured that out by myself anytime soon)

**Comment by niuzhenguo** [comment]
@dev00 thanks for the suggestions, will update soon!

**Comment by dev00** [comment]
@niuzhenguo I'ld be interested in your point of view - is there a case where the providers behaviour is correct (failing if domain_name is set)?

**Comment by niuzhenguo** [comment]
@dev00 I agree that we shouldn't be failing if domain_name is set here :)
