### ISSUE TITLE
[REQUEST]  CCE resource to obtain certificates

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#345]
Hi there,

currently I have a shell script which will download the KUBECONFIG for every server but it would be nice to replace this with terraform.

According to the API it is possible to obtain those:
https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0249.html

### Affected Resource(s)
- opentelekomcloud_cce_certificate

### Terraform Configuration Files
As Data, which will cause a problem since the certificiate is not existing till the cce-cluster is created.
```hcl
data "opentelekomcloud_cce_certificate" "my_cce_certs" {
  project_id = ""${var.my_project_id}"
  cluster_id = "${var.my_cce_cluster_id}"
}
```
Or as resource, which can then `depends_on` something
```hcl
resource "opentelekomcloud_cce_certificate" "my_cce_certs" {
  project_id = ""${var.my_project_id}"
  cluster_id = "${var.my_cce_cluster_id}"

  depends_on = [my_cce_cluster_creation]
}
```

**Comment by niuzhenguo** [comment]
@Moep90 Thanks for raising this, will add a data source for that.

**Comment by Moep90** [comment]
> @Moep90 Thanks for raising this, will add a data source for that.

@niuzhenguo AFAIK datasources will be executed first duo to terraform logic, right?
This means if we deploy in an empty project (full deloyment). There is no CCE-Cluster + no certificate yet.
This causes the data-query to return an empty result which then might cause an error.
This discussion also exists here: https://github.com/hashicorp/terraform/issues/16380

So we might have to add this as a resource?

**Comment by niuzhenguo** [comment]
@Moep90 how about just adding some attributes to cluster?

**Comment by Moep90** [comment]
@niuzhenguo I like that idea. I think this is the best possible solution.
