### ISSUE TITLE
subnet dnslist

### ISSUE THREAD

**Issue by TomMann** [opentelekomcloud/terraform-provider-opentelekomcloud#348]
Hi there,
I would like to create subnet with 3 DNS servers and also specifying which one is primary + secondary.  My only choice as I have 3 is to use dns_list however if I just use dns_list the order of the servers doesn't seem to have any relation to primary and secondary. If I specify primary_dns and secondary_dns then the dns_list is ignored (losing the 3rd DNS).
Could you explain how I can have 3 DNS servers whilst specifying the order.
Thanks
Tom.

**Comment by niuzhenguo** [comment]
@TomMann have you tried to use both primary+secondary and dns_list, as the API doc said the dns_list is a superset of primary and secondary.

**Comment by niuzhenguo** [comment]
```
    "primary_dns": "server1",
    "secondary_dns": "server2",
    "dnsList": [
            "server1",
            "server2",
            "server3"
    ]
```

**Comment by TomMann** [comment]
@niuzhenguo have you tried this ? for me it errors with an invalid dnslist. If I then comment out primary_dns and secondary_dns it stops complaining.

**Comment by niuzhenguo** [comment]
@TomMann Seems that's because the dnsList is a Set instead of List, and we can't keep the order you specified. I will fix this soon.
