### ISSUE TITLE
[REQUEST][S2S-VPN] Resource to use OTC S2S VPN

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#364]
Hey there,

I would like to replace my openstack VPNAAS with the one for the OTC.

### Terraform Version
```
$ terraform --version
Terraform v0.11.14
+ provider.dns v2.1.1
+ provider.local v1.2.0
+ provider.null v2.1.0
+ provider.openstack v1.19.0
+ provider.opentelekomcloud v1.10.0
+ provider.template v2.1.0
```

### Affected Resource(s)
- opentelekomcloud_vpnaas_ike_policy_v2

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
### Expected Behavior
I would love to use a OTC proprietary resource.

### Actual Behavior
Currently there is no resource to do so.
I currently use the `opentstack_vpnaas_ike_policy_v2`
When updateding endpoints it forces a recreation, but I can simply update it in the UI.
I suspect that they implement some magic behind the scenes again (like RDS port update & restart).

### References
[API Docs](https://docs.otc.t-systems.com/en-us/api/vpn/en-us_topic_0133242017.html)

**Comment by niuzhenguo** [comment]
@Moep90 Is it possible according to the API docs?
