### ISSUE TITLE
implement /v3/{project_id}/cloudvolumes API

### ISSUE THREAD

**Issue by liminghui18** [opentelekomcloud/terraform-provider-opentelekomcloud#371]
Hi colleagues,
    we have a project need support of  /v3/{project_id}/cloudvolumes API so that a VBS backup can be used as a source to create new disks.
  hope it can be implemented asap.

best regards,
Jerry

**Comment by ShiChangkuo** [comment]
Please let me have a try.

**Comment by niuzhenguo** [comment]
Closed by #380
