### ISSUE TITLE
Tag/metadata not set within opentelekomcloud_compute_bms_server_v2

### ISSUE THREAD

**Issue by thomaswetzler** [opentelekomcloud/terraform-provider-opentelekomcloud#376]
Hi,

I try to set a tag with terraform 0.12.7 during the installation of a bare metal server. Since there is no option "tag" existing, I tried the option "metadata" to pass a key/value pair. It is not set. 

If I try to set a key/value tag with a direct curl  to the API, everything works as expeted:
https://ecs.eu-de.otc.t-systems.com/v1/project_id/servers/bms_instance_id/tags/action 

### Terraform Version
Terraform v0.12.9
+ provider.openstack v1.23.0
+ provider.opentelekomcloud v1.12.0

### Affected Resource(s)
opentelekomcloud_compute_bms_server_v2

### Terraform Configuration Files
```
data "opentelekomcloud_images_image_v2" "image_centos" {
  name = "${var.image_name}"
  most_recent = true

  properties = {
    key = "value"
  }
}


resource "opentelekomcloud_compute_bms_server_v2" "bms" {
  name            = "${var.instance_name_prefix}-01"
  image_id        = "${data.opentelekomcloud_images_image_v2.image_centos.id}"
  flavor_name     = "${var.flavor_name}"
  key_pair        = "${var.keypair_name}"
  security_groups = ["${var.secgrp_name}"]
  availability_zone = "eu-de-01"

  metadata = {
    "testkey" = "hugo"
  }

  network {
    uuid = "${var.network_id}"
  }
  block_device {
    uuid = "${data.opentelekomcloud_images_image_v2.image_centos.id}"
    source_type = "image"
    volume_type = "SATA"
    volume_size = 50
    boot_index = 0
    destination_type = "volume"
    delete_on_termination = true
    device_name = "/dev/sda"
  }
}
```

### Debug Output
```
curl --request GET \
  --url https://ecs.eu-de.otc.t-systems.com/v1/<project>/servers/<bms instance>/tags \
  --header 'content-type: application/json' \
  --header 'x-auth-token: <access token> 
```
response:
```
{
  "tags": []
}
```

### Expected Behavior
There is a reply expected like
```
{
  "tags": [
    {
      "key": "testkey",
      "value": "hugo"
    }
   ]
}
```

### Actual Behavior
Response of API Request (shown above):
```
{
  "tags": []
}
```

### Steps to Reproduce
`terraform apply` of the given code above

**Comment by niuzhenguo** [comment]
@thomaswetzler Sorry for the late reply, will dig more if we can reuse the tags ability from compute_instance.
