### ISSUE TITLE
Create an encrypted EVS Volume in a new OTC Project

### ISSUE THREAD

**Issue by r0b2g1t** [opentelekomcloud/terraform-provider-opentelekomcloud#415]
Hello,

I tried to create an encrypted EVS volume in a fresh created tenant project during a Terraform deployment. That isn't possible because it is necessary to create a "Xrole" by clicking a button in the frontend before:

![image](https://user-images.githubusercontent.com/5357541/68406999-13a2c780-0183-11ea-90b8-d498910f9aec.png)

I can't find any provider function to create the Xrole during my Terraform deployment. Because of this it is necessary to interrupt the deployment to manually create the role and restart the deployment.

Does anyone have a solution to this issue?

**Comment by Tom-Mann** [comment]
linking the xrole is a one off process, so it is now solved at least for that project.  I believe their is a crq to be able to configure that but as far as I know its currently a manual process.

**Comment by niuzhenguo** [comment]
Please try this https://www.terraform.io/docs/providers/opentelekomcloud/r/identity_agency_v3.html

**Comment by outcatcher** [comment]
@r0b2g1t Is this issue still relevant for you?

**Comment by lego963** [comment]
Сlosed due to inactivity
