### ISSUE TITLE
PostgreSQL Provider Version Bug

### ISSUE THREAD

**Issue by victorgetz** [opentelekomcloud/terraform-provider-opentelekomcloud#416]
Hi there,

so far the basics are working so great working !

But i have the following issue:
1. i create vpc etc. and a database with terraform
2. i try to connect to the database with terraform to create the initial user and database stuff (https://www.terraform.io/docs/providers/postgresql/index.html)
3. i get the following error:
Error initializing PostgreSQL client: error detecting capabilities: error PostgreSQL version: pq: unknown authentication response: 10

If i understand it correctly the open telekom service return that the current version is 10.
But first the right version is 10.8 (which is also displayed in the ui) and terraform accepts just this format:

 Major.Minor.Patch 

Which also make totally sense.

Could you please fix that?

this is my config:

provider "postgresql" {
  alias = "my_alias"
  database = "postgres"
  port = 5732
  host = "x.x.x.x"
  username = opentelekomcloud_rds_instance_v3.offer_db.db[0].user_name
  password = opentelekomcloud_rds_instance_v3.offer_db.db[0].password
  connect_timeout = 15
  expected_version = "10.8.0"
}

**Comment by tstrohmeier** [comment]
There was a change this week which also caused problems in our setup. The response for the PostgreSQL datastore version was changed from `10.0` to `10`. The minor version seems not to be accessible on RDS API v3 at all.

**Comment by victorgetz** [comment]
Any update?

**Comment by niuzhenguo** [comment]
@VictorGetz Sorry for the long delay in response. The reason of this is just as @tstrohmeier said above, the RDS API changed on the Server side for the minior version, so we can't handle that on Terraform side.

**Comment by outcatcher** [comment]
This seems to be not an issue of the provider.
@VictorGetz please reopen if you still need this issue
