### ISSUE TITLE
Terraform state saves wrong value for compute_instance image_id"Attempt to boot from volume - no image supplied"

### ISSUE THREAD

**Issue by LanceTheDev** [opentelekomcloud/terraform-provider-opentelekomcloud#417]
### Terraform Version
Terraform  v0.12.4

### Affected Resource(s)
- opentelekomcloud_compute_instance

### Terraform Configuration Files
resource "opentelekomcloud_compute_instance_v2" "instance" {
  count           = var.ecs_count
  name            = "${var.name}${format("%02d", count.index + 1)}"
  image_id        = var.image
  flavor_name     = var.flavor
  key_pair        = opentelekomcloud_compute_keypair_v2.keypair.name
  user_data       = var.user_data
  security_groups = var.security_groups

  block_device {
    uuid                  = var.image
    source_type           = "image"
    destination_type      = "volume"
    volume_size           = var.volume_size
    volume_type           = "SSD"
    boot_index            = 0
    delete_on_termination = true
  }

  network {
    uuid = var.network_id
  }
}

resource "opentelekomcloud_compute_floatingip_associate_v2" "instance_fip" {
  count       = var.attach_eip && true ? var.ecs_count : 0
  floating_ip = opentelekomcloud_networking_floatingip_v2.fip.*.address[count.index]
  instance_id = opentelekomcloud_compute_instance_v2.instance.*.id[count.index]
}

resource "opentelekomcloud_networking_floatingip_v2" "fip" {
  count = var.attach_eip && true ? var.ecs_count : 0
  pool  = var.ext_net_name
}

resource "opentelekomcloud_compute_keypair_v2" "keypair" {
  name       = "${var.name}-key"
  public_key = var.pubkey
}

### Debug Output
https://gist.github.com/LanceTheDev/43cd6a9badea9ecde9b56a6bcd567df3

### Expected Behavior
When applying again, terraform should not want to change anything

### Actual Behavior
# module.nginx-ecs.opentelekomcloud_compute_instance_v2.instance[0] must be replaced
-/+ resource "opentelekomcloud_compute_instance_v2" "instance" {
      ~ access_ip_v4        = "192.168.25.56" -> (known after apply)
      + access_ip_v6        = (known after apply)
      ~ all_metadata        = {} -> (known after apply)
      ~ auto_recovery       = true -> (known after apply)
      ~ availability_zone   = "eu-de-02" -> (known after apply)
      ~ flavor_id           = "s2.medium.4" -> (known after apply)
        flavor_name         = "s2.medium.4"
      ~ id                  = "b9a73ddf-fb74-4b66-9e5a-7279c6ad02a0" -> (known after apply)
      ~ image_id            = "**Attempt to boot from volume - no image supplied**" -> "e7cb3552-79ad-4f91-9041-7853fb73a457" # forces replacement
      + image_name          = (known after apply)
        key_pair            = "nginx-vm-key"
        name                = "nginx-vm01"
      ~ region              = "eu-de" -> (known after apply)
        security_groups     = [
            "default",
        ]
        stop_before_destroy = false
        user_data           = "da39a3ee5e6b4b0d3255bfef95601890afd80709"
      ~ volume_attached     = [
          - {
              - id = "68fe3445-fa2d-4c52-af83-2fdbbcd07206"
            },
        ] -> (known after apply)

      ~ block_device {
            boot_index            = 0
            delete_on_termination = true
            destination_type      = "volume"
            source_type           = "image"
            uuid                  = "e7cb3552-79ad-4f91-9041-7853fb73a457"
            volume_size           = 20
            volume_type           = "SSD"
        }

      ~ network {
            access_network = false
          ~ fixed_ip_v4    = "192.168.25.56" -> (known after apply)
          + fixed_ip_v6    = (known after apply)
          + floating_ip    = (known after apply)
          ~ mac            = "fa:16:3e:92:8d:05" -> (known after apply)
          ~ name           = "4dab71a3-e0f2-463d-92ed-9bb5c19a7796" -> (known after apply)
          + port           = (known after apply)
            uuid           = "96c01dc4-000e-49b2-9b5e-2facba4d66ba"
        }
    }

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by niuzhenguo** [comment]
image_id should be removed when booting from volume.

**Comment by LanceTheDev** [comment]
Great, that did it. Thanks.
