### ISSUE TITLE
[FEATURE] Log Tank Service + Log Tank Topic

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#429]
Please add the following Resources to the provider

### Affected Resource(s)
- opentelekomcloud_logtank_group_v2
- opentelekomcloud_logtank_topic_v2

#### Documentation
Log Tank Service - https://docs.otc.t-systems.com/en-us/api/lts/lts_02_0003.html

Log Tank Topic - https://docs.otc.t-systems.com/en-us/api/lts/lts_02_0007.html

**Comment by niuzhenguo** [comment]
closed by #435
