### ISSUE TITLE
Support for decsription field of the security group rule

### ISSUE THREAD

**Issue by ghost** [opentelekomcloud/terraform-provider-opentelekomcloud#431]
Hello,

the resource opentelekomcloud_networking_secgroup_rule_v2 does unfortunately not support the description field. Especially in security groups with large amount of rules the description is helpful to understand the impact of the security group, e.g. for a review by a security officer. 

I hope this information is sufficient, I am new here ...

Thank you!
Thomas Krohn

**Comment by niuzhenguo** [comment]
@ThomasKrohn-DTIT Thanks for raising this, will add that support soon!
