### ISSUE TITLE
Can't delete firewall rule(s)

### ISSUE THREAD

**Issue by nicinuse** [opentelekomcloud/terraform-provider-opentelekomcloud#436]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.12
+ provider.local v1.4.0
+ provider.opentelekomcloud v1.13.1
+ provider.template v2.1.2

### Affected Resource(s)
- opentelekomcloud_fw_rule_v2

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
  # opentelekomcloud_fw_rule_v2.default-ssh will be destroyed
  - resource "opentelekomcloud_fw_rule_v2" "default-ssh" {
      - action                 = "deny" -> null
      - destination_ip_address = "0.0.0.0/0" -> null
      - enabled                = true -> null
      - id                     = "3dcec8de-ff7a-4535-bbb3-d7f208752bdd" -> null
      - ip_version             = 4 -> null
      - protocol               = "tcp" -> null
      - region                 = "eu-de" -> null
      - source_ip_address      = "0.0.0.0/0" -> null
    }
```

### Debug Output
https://gist.github.com/nicinuse/79696b4223289011fd75144bf1296d25

### Expected Behavior
Firewall rule should be deleted, maybe disabled before.

### Actual Behavior
Firewall is not deleted, because it is enabled.

### Steps to Reproduce
`terraform apply`

**Comment by niuzhenguo** [comment]
@nicinuse Can you please try to disable it first before delete.

**Comment by sfhl** [comment]
@niuzhenguo Thanks for your reply! How should i do that? terraform seems not to modify a resource that is going to be destroyed. I have already tried things like setting enabled = "false" with when = "destroy" but that does not help.
Kind reagrds.

**Comment by niuzhenguo** [comment]
@nicinuse I mean you should update the `enabled` field first by changing the script and apply, then destroy.  I'm not sure how it works on GUI, but it's not allowed on API side.

**Comment by niuzhenguo** [comment]
@sfhl ^

**Comment by outcatcher** [comment]
@niuzhenguo Maybe it makes sense to implement disabling rules on `destroy`? It seems to be expected behaviour of `destroy` as opposite to `apply`. If it's okay from your point of view, I would like to handle implementation of this.

**Comment by niuzhenguo** [comment]
@outcatcher I'm OK with that :)

**Comment by outcatcher** [comment]
Can't reproduce the issue, can destroy the rule without disabling.

Terraform v0.12.12
\+ provider.opentelekomcloud v1.13.1

**Have tried following scenarios:**

1. Single rule — apply/destroy
2. Single rule + policy — apply/destroy
3. Two rules + policy — apply, remove single policy from config, apply
4. Single rule + policy — apply, than destroy only the rule

Used configuration: [gist](https://gist.github.com/outcatcher/3ef00fa819e7ccd858203c85f2301896)

In the provided log file there is mention about firewall rule being used, maybe the issue is not connected to `enabled` state

@nicinuse can you please provide more detailed resource configuration?
@sfhl do you have a stable way to reproduce this problem?

**Comment by sfhl** [comment]
Hi there,

now using 
Terraform v0.12.12
+ provider.opentelekomcloud v1.15.0

i still have the same problem. I am using the follwoing config and i am trying to remove the one single (last) rule

```
resource "opentelekomcloud_fw_rule_v2" "default-allow-all-ingress" {
  action                 = "allow"
  description            = "allow-all"
  protocol               = "any"
  source_ip_address      = "0.0.0.0/0"
  destination_ip_address = "0.0.0.0/0"
  source_port            = ""
  destination_port       = ""
  ip_version             = "4"
}

resource "opentelekomcloud_fw_rule_v2" "default-allow-all-egress" {
  action                 = "allow"
  description            = "allow-all"
  protocol               = "any"
  source_ip_address      = "0.0.0.0/0"
  destination_ip_address = "0.0.0.0/0"
  source_port            = ""
  destination_port       = ""
  ip_version             = "4"
}

resource "opentelekomcloud_fw_firewall_group_v2" "fw-dev-default" {
  name               = "fw-dev-default"
  ingress_policy_id  = "${opentelekomcloud_fw_policy_v2.fw-dev-default_ingress.id}"
  egress_policy_id   = "${opentelekomcloud_fw_policy_v2.fw-dev-default_egress.id}"

  depends_on = [opentelekomcloud_fw_policy_v2.fw-dev-default_ingress,opentelekomcloud_fw_policy_v2.fw-dev-default_egress]
}

resource "opentelekomcloud_fw_policy_v2" "fw-dev-default_ingress" {
  name   = "fw-dev-default_ingress"
  rules  = ["${opentelekomcloud_fw_rule_v2.default-allow-all-ingress.id}"]
}

resource "opentelekomcloud_fw_policy_v2" "fw-dev-default_egress" {
  name   = "fw-dev-default_egress"
  rules  = ["${opentelekomcloud_fw_rule_v2.default-allow-all-egress.id}"]
}
```

The error says:
```
Error: Expected HTTP response code [202 204] when accessing [DELETE https://vpc.eu-de.otc.t-systems.com/v2.0/fwaas/firewall_rules/a5d7af52-bbef-4f93-906a-950cf3517f3e], but got 409 instead
{"NeutronError": {"message": "Firewall Rule a5d7af52-bbef-4f93-906a-950cf3517f3e is being used.", "type": "FirewallRuleInUse", "detail": ""}}
```

Please let me know of more information is needed.

Thanks in advance!

**Comment by outcatcher** [comment]
@sfhl Issue reproduces, thanks! I will start my investigation :mag:

**Comment by nicinuse** [comment]
Hi there!
Some additional information, even if i think i mentioned it somewhere:
This happens only if i try to delete the last rule. So when creating policy, the "deny all" rule is created by default. 

If i create rules after that, if there are only 2 left (the default "deny all" and one custom rule) the error appears if i try to delete this last custom rule.

I hope that helps. Kind regards.

**Comment by outcatcher** [comment]
@nicinuse Thanks, I've already localized the problem. Fixing it now
