### ISSUE TITLE
opentelekomcloud_cce_node_v3: Pre-installation and Post-installation Script missing

### ISSUE THREAD

**Issue by ghost** [opentelekomcloud/terraform-provider-opentelekomcloud#438]
Hi there,

in our environment we are not allowed to directly access Internet. Instead we must use a proxy. To do so we must set proxy parameters within the CCE worker nodes. 
Today we discovered the (new?) Advanced Settings section in the Web UI when creating a worker node. Here I can enter script code that is executed before or after the installation of the K8s software. We have checked that, and it works as expected and fulfills our requirement.
Now we would like to add this to our automation scripts. In the documentation of the Terraform resource opentelekomcloud_cce_node_v3 there is no mention of script to be injected. Is this a documentation issue or is it really not supported?
If not (yet) supported: Can this be implemented?
Thank you!

Thomas

**Comment by niuzhenguo** [comment]
@ThomasKrohn-DTIT Need the new parameters support on API side first.
