### ISSUE TITLE
Unable to create as_configuration when using template with more than one disk

### ISSUE THREAD

**Issue by DeX77** [opentelekomcloud/terraform-provider-opentelekomcloud#444]
### Terraform Version

```
Terraform v0.12.18
+ provider.opentelekomcloud v1.14.0
+ provider.template v2.1.2
```

### Affected Resource(s)
- opentelekomcloud_as_configuration_v1

### Terraform Configuration Files
```hcl
resource "opentelekomcloud_as_configuration_v1" "as-config" {

  scaling_configuration_name = "prod"
  instance_config {
    key_name = "root-keypair"
    flavor   = "s2.large.2" #2 Cores 4Gb RAM
    image    = data.opentelekomcloud_images_image_v2.template.id
    disk {
      size        = 40
      volume_type = "SATA"
      disk_type   = "SYS"
    }
    disk {
      size        = 10
      volume_type = "SATA"
      disk_type   = "DATA"
    }
    disk {
      size        = 10
      volume_type = "SATA"
      disk_type   = "DATA"
    }

    user_data = data.template_cloudinit_config.var_and_opt.rendered
  }
}
```

### Debug Output
```
Error: Error creating ASConfiguration: Bad request with: [POST https://as.eu-de.otc.t-systems.com/autoscaling-api/v1/0b3e092cfd5b49e5848d121c44ffbc4c/scaling_configuration], error message: {"error":{"code":"AS.1065","message":"ECS resources specified in the AS configuration belong to different AZs."}}
```

### Expected Behavior
Autoscaling Configuration should be created

### Actual Behavior
See above error

### Steps to Reproduce
1. create some instance with more than one disk
2. create an image of that instance (CSBS backup)
3. try to the Id of that image to create an as_config

**Comment by niuzhenguo** [comment]
@DeX77 Is that error message "ECS resources specified in the AS configuration belong to different AZs" correct? If not, I suggest you create a ticket to Cloud side as it's an API response instead of errors on Terraform side.

**Comment by DeX77** [comment]
@niuzhenguo thx for your feedback. I tried to reproduce the terraform resource using openstack cli client. This should be the same command:

`openstack --debug as config create --image_id <uuid> --disk SYS,SATA,40 --disk DATA,SATA,10 --disk DATA,SATA,10 --flavor s2.large.2 --key root-keypair as-test`

And (after using the latest git HEAD from https://github.com/OpenTelekomCloud/python-otcextensions) I get:

`ECS resources specified in the AS configuration belong to different AZs.`

So I think you are right: this seems to be an API issue as I'm unaware how to even specify some AZ for an AS config.

Feel free to close the issue.
