### ISSUE TITLE
[RDSv3] RDS changing the param_group_id should not cause a recreation

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#445]
Hi there,

I just changed the paramgroup after I created the RDS.
When doing so within the OTC-Console I can change it and need to wait for a reboot.
If I do this using terraform, it will create a new RDS instance.
Is there a way around it?

### Terraform Version
```
/usr/local/bin/terraform -v
Terraform v0.11.14
+ provider.dns v2.2.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.openstack v1.23.0
+ provider.opentelekomcloud v1.14.0
+ provider.template v2.1.2
```

### Affected Resource(s)
- opentelekomcloud_rds_instance_v3
- opentelekomcloud_rds_parametergroup_v3

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Expected Behavior
Reboot instead recreate

### Actual Behavior
forces new resource

### Steps to Reproduce
1. `terraform apply`

**Comment by tstrohmeier** [comment]
I think recreation should be only the case, if we don't have any possibility to apply the updated config. 

@Moep90 Did you checked if API v3 is currently supporting this action?
@niuzhenguo If not we can maybe use API v1 as workaround like in #236 ?

**Comment by niuzhenguo** [comment]
@tstrohmeier seems we don't even have parameter group V1 API.

**Comment by outcatcher** [comment]
Passing `param_group_id` is not described in RDS instance creation in API spec: https://docs.otc.t-systems.com/api/rds/rds_01_0002.html

It seems that a legit way to apply a configuration template is using apply, not passing it during RDS creation.

TODO: 
* `param_group_id` to be deprecated
* `configuration_template_id` to be added, with configuration applying via `PUT https://{Endpoint}/v3/{project_id}/configurations/{config_id}/apply`
