### ISSUE TITLE
BUG: Error when query RDS tags

### ISSUE THREAD

**Issue by tstrohmeier** [opentelekomcloud/terraform-provider-opentelekomcloud#449]
Hi there,

### Terraform Version
v0.12.19

### Provider Version
v1.15.0

### Affected Resource(s)
Please list the resources as a list, for example:
- opentelekomcloud_rds_instance_v3

### Terraform Configuration Files
```hcl
resource "opentelekomcloud_rds_instance_v1" "instance" {
  name            = "basic"
  ...
  tag = {
    foo = "bar"
    key = "value"
  }
  ...
}
```

### Debug Output
```
Error: Error fetching OpenTelekomCloud rds instance tags: Expected HTTP response code [200] when accessing [GET https://rds.eu-de.otc.t-systems.com/v1/{{prj_id}}/rds/{{instance_id}}/tags], but got 415 instead
 {"errCode":"RDS.0004","externalMessage":"Invalid operation."}
```

### Expected Behavior
Create Plan with Tags

### Actual Behavior
Throw error

### Steps to Reproduce
1. `terraform plan`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #236

**Comment by tstrohmeier** [comment]
@niuzhenguo This is actually happening when the endpoint `https://rds.eu-de.otc.t-systems.com/v1/{{prj_id}}/rds/{{instance_id}}/tags` is called with the `instance_id` of `node_1`. Can you please make sure that the provider always use the `instance_id` of `node_0` for calling this endpoint?

**Comment by niuzhenguo** [comment]
@tstrohmeier Yes, we always use the instance_id of node_0.

**Comment by tstrohmeier** [comment]
@niuzhenguo I have one case where `node_1` was passed. 
https://github.com/terraform-providers/terraform-provider-opentelekomcloud/blob/master/opentelekomcloud/resource_opentelekomcloud_rds_instance_v3.go#L314-L320
Maybe the elements in the array are not sorted?

**Comment by tstrohmeier** [comment]
Thank you @niuzhenguo
