### ISSUE TITLE
Remote state implemented in Object Storage Service

### ISSUE THREAD

**Issue by MateuszStefek** [opentelekomcloud/terraform-provider-opentelekomcloud#454]
Feature request: native support for Object Storage Service as the backend for remote state.

Currently, it's possible to store the remote state in OSS with a little hack on the `s3` backend, like this:

```
terraform {
  backend "s3" {
    endpoint = "https://obs.eu-de.otc.t-systems.com"

    bucket = "<BUCKET NAME>"
    key    = "<OBJECT KEY>"

    access_key = var.access_key
    secret_key = var.secret_key

    region = "eu-de"

    skip_region_validation      = true
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    force_path_style            = true
  }
}
```

This solution is inconvenient, as the backend variables must be initialized during init: `terraform init  -backend-config=somefile.tfvars` and stored in `.terraform/`. The secrets remain on the filesystem longer than they should.

It would be nice for this backend to "inherit" credentials from `provider "opentelekomcloud" {`.

**Comment by niuzhenguo** [comment]
@ShiChangkuo please have a look at this ^

**Comment by ShiChangkuo** [comment]
@MateuszStefek the obs backend type is in developing, please reference
https://github.com/hashicorp/terraform/issues/23888

**Comment by outcatcher** [comment]
Hashicorp rejected hashicorp/terraform#23888.

Terraform doesn't support additional backends now: https://www.terraform.io/docs/configuration/blocks/backends/index.html#where-backends-come-from.

Should be reopened when Terraform will allow custom backends.
