### ISSUE TITLE
[Proposal] Change OBS to S3 in resources

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/terraform-provider-opentelekomcloud#464]
OBS uses S3 API, so it's clear why current naming is used:
`opentelekomcloud_s3_bucket`, `opentelekomcloud_s3_bucket_policy`, `opentelekomcloud_s3_bucket_object`

On the other hand,  `OBS` is used as a name of the service in documentation and in console

From T-Systems point of view, renaming resources (considering https://www.terraform.io/docs/extend/best-practices/deprecations.html#provider-data-source-or-resource-rename) would be a good idea

New names should be `opentelekomcloud_obs_bucket`, `opentelekomcloud_obs_bucket_policy`, `opentelekomcloud_obs_bucket_object`

Documentation to be changed accordingly

**Comment by niuzhenguo** [comment]
@outcatcher Instead of just renaming the s3 resources, I would suggest to switch to use OBS API which has some additional features.

**Comment by ShiChangkuo** [comment]
@outcatcher I have developed the `obs_bucket` and `obs_bucket_object` resources with OBS SDK， and will merge the PR in this week.

**Comment by outcatcher** [comment]
@ShiChangkuo @niuzhenguo 
Should I close this issue than?
