### ISSUE TITLE
Can't update VPC policy

### ISSUE THREAD

**Issue by sfhl** [opentelekomcloud/terraform-provider-opentelekomcloud#466]
Hi there,
i got a little problem with backups and the config as follows. There is a complaint about missing frequency attribute, even if it is set and not updated.

### Terraform Version
Terraform v0.12.12
+ provider.local v1.4.0
+ provider.opentelekomcloud v1.14.0
+ provider.template v2.1.2

### Affected Resource(s)
Please list the resources as a list, for example:
- opentelekomcloud_vbs_backup_policy_v2

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
...
  # opentelekomcloud_vbs_backup_policy_v2.ebp-prod-backup will be updated in-place
  ~ resource "opentelekomcloud_vbs_backup_policy_v2" "ebp-prod-backup" {
        frequency             = 1
        id                    = "c6ad5cde-55a9-4e74-a4de-63dde27f6771"
        name                  = "ebp-prod-backup"
        policy_resource_count = 1
      ~ rentention_num        = 2 -> 7
      ~ retain_first_backup   = "N" -> "Y"
      ~ start_time            = "00:00,01:00,02:00,03:00,04:00,05:00,06:00,07:00,08:00,09:00,10:00,11:00,12:00,13:00,14:00,15:00,16:00,17:00,18:00,19:00,20:00,21:00,22:00,23:00" -> "00:00,04:00,08:00,12:00,16:00,20:00"
        status                = "ON"
    }
...
```

### Debug Output
https://gist.github.com/sfhl/18e89a59afd2eb61eb4956c3943426b7

### Expected Behavior
Policy should be updated

### Actual Behavior
Policy can't be updated, because neither frequency nor week_frequency is selected, even if it is set.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by outcatcher** [comment]
I will handle this issue
