### ISSUE TITLE
OTC SAML ID provider support

### ISSUE THREAD

**Issue by deas** [opentelekomcloud/terraform-provider-opentelekomcloud#471]
Hi,

we aim at user lifecycle exclusively managed in Active Directory. Hence we created a SAML Identity provider. Browser based authentication works fine.

All `terraform` providers listed [in the documentation](https://www.terraform.io/docs/providers/opentelekomcloud/index.html) do not seem suitable for this scenario. I wrote a somewhat more detailed post up in the [forums](https://community.open-telekom-cloud.com/community?id=community_question&sys_id=2428b83c13ff8c50d15ac969a674417a)

Any suggestion how to get `terraform` to play with SAML-Auth/-Identities?

thanks and best regards
Andreas

**Comment by outcatcher** [comment]
Hi, it's not currently supported, as a workaround you can try to [generate token](https://docs.otc.t-systems.com/en-us/api/iam/iam_02_0001.html) and use it for authentication
