### ISSUE TITLE
"error finding the resources by list api" in opentelekomcloud_rds_instance_v3

### ISSUE THREAD

**Issue by MateuszStefek** [opentelekomcloud/terraform-provider-opentelekomcloud#476]
### Terraform Version
```
Terraform v0.12.24
+ provider.opentelekomcloud v1.16.0
```

### Affected Resource(s)
- opentelekomcloud_rds_instance_v3

### Description
When you create an RDS instance with Terraform and then delete the instance manually,
`terraform apply` crashes with message `error finding the resources by list api`.

I couldn't find any other related error message in the debug logs.

Terraform should detect that the database resource is gone and plan to recreate it.

**Comment by ShiChangkuo** [comment]
@MateuszStefek Thanks for raising, the provider should set the resource id to empty when the database was gone.
