### ISSUE TITLE
[SMN] unable to set subscription status to "1"

### ISSUE THREAD

**Issue by nicinuse** [opentelekomcloud/terraform-provider-opentelekomcloud#483]
Hi there,

i am trying to create a SMN subscription which is already confrmed, but the status is not set correctly, it is always set to "0".

### Terraform Version
```
Terraform v0.12.12
+ provider.local v1.4.0
+ provider.opentelekomcloud v1.16.0
+ provider.template v2.1.2
```

### Affected Resource(s)
- opentelekomcloud_smn_subscription_v2

### Terraform Configuration Files
```hcl
...
"subscription_prod_monitoring_scbcm_support_mms_support_de" {
      endpoint         = "scbcm-support@mms-support.de"
      id               = (known after apply)
      owner            = (known after apply)
      protocol         = "email"
      remark           = "O&M"
      status           = 1
      subscription_urn = (known after apply)
      topic_urn        = "urn:smn:eu-de:8be6992ea8904e17a7457a08a434f723:prod-monitoring"
    }
...
```

### Debug Output
https://gist.github.com/nicinuse/639e88929e672264a09ac1e241d557a1

### Expected Behavior
Status should be set correctly.

### Actual Behavior
Status is always set to "0".
Also terraform run ends in an error for getting subscriptionslist.

### Steps to Reproduce
1. `terraform apply`

**Comment by ShiChangkuo** [comment]
@nicinuse the `status` is an attribute of smn subscription resource which means we can't specify it. If the SMN subscription is already confrmed, using `terraform refresh` brfore `terraform plan`, then you can check whether the status is set correctly.

Maybe the website documents mislead you, I'll fix it this soon.
