### ISSUE TITLE
[Feature Request] add support for attribute rentention_day for opentelekomcloud_vbs_backup_policy_v2

### ISSUE THREAD

**Issue by nicinuse** [opentelekomcloud/terraform-provider-opentelekomcloud#487]
Hi there,

it would be great if we could use either "rentention_num" or "rentention_day" for this resource.

### Terraform Version
```
Terraform v0.12.12
+ provider.local v1.4.0
+ provider.opentelekomcloud v1.16.0
+ provider.template v2.1.2
```

### Affected Resource(s)
Please list the resources as a list, for example:
- opentelekomcloud_vbs_backup_policy_v2
If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

**Comment by ShiChangkuo** [comment]
opentelekomcloud_vbs_backup_policy_v2 has already supportted `rentention_num` which is mandatory.
Please refer to [the example usage](https://www.terraform.io/docs/providers/opentelekomcloud/r/vbs_backup_policy_v2.html#rentention_num)

**Comment by nicinuse** [comment]
Hi there,

yeah thats great, but sadly not enough. With rentention_num and backups created, for example every 4 hours, i only can retain backups of the last approx 2 days, because the max of rentention_num is 14.

**Comment by ShiChangkuo** [comment]
I got it!
In fact, the range of rentention_num is 2 ~ 99 via API or Terraform, you can enlarge it temporarily.
Also, I will add the `rentention_day` argument in the next version, please update in time.
