### ISSUE TITLE
[missing attribute] multiattach for opentelekomcloud_blockstorage_volume_v2

### ISSUE THREAD

**Issue by nicinuse** [opentelekomcloud/terraform-provider-opentelekomcloud#488]
Hi there,

for use with  k8s version v 1.13.x in OTC it is obviously needed to set multiattach to true for your EVS. Sadly opentelekomcloud_blockstorage_volume_v2 doenst have this attribute and opentelekomcloud_evs_volume_v3 (which has it) is lacking the attribute "policy" for attaching a backup policy. So at the moment it seems you can have either EVS with backup policy attached or with multiattach = True.

### Terraform Version
Terraform v0.12.12
+ provider.local v1.4.0
+ provider.opentelekomcloud v1.16.0
+ provider.template v2.1.2

### Affected Resource(s)
Please list the resources as a list, for example:
- opentelekomcloud_blockstorage_volume_v2
- opentelekomcloud_evs_volume_v3

**Comment by ShiChangkuo** [comment]
maybe you can associate evs volumes to opentelekomcloud_vbs_backup_policy_v2 with #478 
hope the PR can meet you need.

**Comment by nicinuse** [comment]
Oh ok, thats what i searched for but it is not documented, i guess.

https://www.terraform.io/docs/providers/opentelekomcloud/r/vbs_backup_policy_v2.html

**Comment by nicinuse** [comment]
maybe i am al little bit confused, but i get the message
`An argument named "resources" is not expected here.` with provider.opentelekomcloud v1.16.0

**Comment by ShiChangkuo** [comment]
as the lastest version is not released, you should [build the provider](https://github.com/terraform-providers/terraform-provider-opentelekomcloud#building-the-provider) or wait for the next version in a couple of days.
