### ISSUE TITLE
[RDSv3] Database root password should be declared as sensitive

### ISSUE THREAD

**Issue by lnobach** [opentelekomcloud/terraform-provider-opentelekomcloud#501]
Hi all,

regarding the following attribute:

https://github.com/terraform-providers/terraform-provider-opentelekomcloud/blob/96a74dce88d0eac6f10ad9506a5b91fae0a90381/opentelekomcloud/resource_opentelekomcloud_rds_instance_v3.go#L66-L70

The resource sub-schema of "db" here should carry the flag `Sensitive: true` for "password".
This way, the initial password is hidden from the terraform output.

See:
- https://www.terraform.io/docs/extend/best-practices/sensitive-state.html
- https://godoc.org/github.com/hashicorp/terraform-plugin-sdk/helper/schema#Schema.Sensitive

An example where this has been correctly done is the `identity_user_v3` password:

https://github.com/terraform-providers/terraform-provider-opentelekomcloud/blob/96a74dce88d0eac6f10ad9506a5b91fae0a90381/opentelekomcloud/resource_opentelekomcloud_identity_user_v3.go#L52-L56

### Terraform Version
\>= 0.12

### Affected Resource(s)
- opentelekomcloud_rds_instance_v3

### Expected Behavior
The RDS v3 root password is hidden from the console output.

### Actual Behavior
The password is passed to stdout and, if logged, is visible in the logs.

### Steps to Reproduce

1. Run `terraform plan` to create a new RDS v3 instance.
2. Observe stdout showing the password in cleartext.

**Comment by ShiChangkuo** [comment]
@lnobach Thanks for your effort, i will implement it as well as other resources.
