### ISSUE TITLE
Question: Security SGs .id vs .name

### ISSUE THREAD

**Issue by raypettersen** [opentelekomcloud/terraform-provider-opentelekomcloud#505]
We've encountered an issue with this provider, which is troublesome. Whenever we create SGs, we are accustomed to using the .id, so that we can in theory create SGs that have the same name, but have different IDs. In fact they are two separate entities.

However in OTC, when we use .id on an ECS instance for setting security-group, we end up with an "eternal plan", meaning we do not get a clean state. The id is always rewriting what seems to be the SG .name.

Is this a bug or is it how the provider is intended to work? We'd like to avoid using SG name if possible.

**Comment by niuzhenguo** [comment]
@raypettersen Seems only SG names accepted on the API side.

**Comment by raypettersen** [comment]
Then I'm a bit confused about behavior.

```resource "opentelekomcloud_compute_instance_v2" "compute" {
  count             = var.computecount
  availability_zone = data.openstack_compute_availability_zones_v2.available.names[count.index]
  name              = "${var.deployment_name}0${count.index + 1}.${var.dns_zone}"
  flavor_id         = var.flavor_id
  key_pair          = var.key_name
  security_groups   = [module.sglinux.secgroup.id, opentelekomcloud_networking_secgroup_v2.service_traffic.id]
  user_data         = data.template_file.userdata.rendered
  config_drive      = "true"
```

The above code example accepts .id as input for security_groups, but after apply we see continues changes in plan:

From plan:
```      ~ security_groups     = [
          + "90d96a1c-2f79-40a9-99f6-dda050a8ac95",
          + "af12d78c-be8a-4d6b-b09a-ba4b5e331e59",
          - "bastion",
          - "bastion_service_traffic",
```

Is this a bug or expected behavior?

**Comment by niuzhenguo** [comment]
@raypettersen Maybe you should create an issue on Cloud side as we just pass the security groups as the API described. I suppose it's not allowed there.

**Comment by raypettersen** [comment]
I can do that, but before closing. Is the recommendation (for now) to use .name for all security-groups and not use id's like we do in AWS as an example?

**Comment by niuzhenguo** [comment]
@raypettersen Yes, but we can keep this open and wait for your feedback from API side.

**Comment by Epimetheus89** [comment]
I have an issue with using the .name instead of .id. If I use the .id an ecs instance is created successfully. But then shows the issue with the eternal state with the difference between the name and the id. But if I change the usage to .name field, I am not able to create an ecs instance. It always fails with an error message, that the id of the security group is invalid.
According to the current docs, the endpoint expects ids of the security groups: https://docs.otc.t-systems.com/en-us/api/ecs/en-us_topic_0167957246.html#EN-US_TOPIC_0167957246__table1698566599

**Comment by outcatcher** [comment]
@Epimetheus89 can you please provide the configuration you use?

For me both name and ID works:

```hcl
resource "opentelekomcloud_compute_secgroup_v2" "sg" {
  description = "seggrp1"
  name        = "seggrp1"
}
resource "opentelekomcloud_compute_secgroup_v2" sg2 {
  description = "seggrp2"
  name        = "seggrp2"
}

resource opentelekomcloud_vpc_v1 vpc {
  cidr = "192.168.0.0/24"
  name = "vpc1"
}

resource "opentelekomcloud_vpc_subnet_v1" "sn1" {
  cidr       = "192.168.0.0/26"
  gateway_ip = "192.168.0.1"
  name       = "sn1"
  vpc_id     = opentelekomcloud_vpc_v1.vpc.id
}

resource "opentelekomcloud_compute_instance_v2" "instance" {
  name            = "inst"
  security_groups = [
    opentelekomcloud_compute_secgroup_v2.sg.name,
    opentelekomcloud_compute_secgroup_v2.sg2.id,
  ]
  flavor_name     = "s2.medium.2"
  image_name      = "Standard_Debian_9_latest"
  network {
    uuid = opentelekomcloud_vpc_subnet_v1.sn1.id
  }
}
```
The one set by ID leads to diff during refresh (and triggering change each apply)

I suppose, generally, setting dependencies by ID is better approach, so we can change it both in documentation and in implementation. It is still to be discussed in what form should it be done.

**Comment by Epimetheus89** [comment]
Ok.. I found the issue why it did not work for me.

I took the `opentelekomcloud_ecs_instance_v1` resource instead of `opentelekomcloud_compute_instance_v2`.

With this one, the api allows to use the name instead of the id.

**Comment by outcatcher** [comment]
@Epimetheus89 So you use id, but still, there is a diff?

**Comment by outcatcher** [comment]
Since `v1.21.3` both ID and name will work correctly in compute_instance_v2
For SG in other resources see #679

**Comment by outcatcher** [comment]
To be moved to [Q&A](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/discussions/categories/q-a)

**Comment by lego963** [comment]
We investigated that resource `opentelekomcloud_ecs_instance_v1` in `security_groups` field now requires `security_group_id`
