### ISSUE TITLE
Question: Is it possible to get a clean plan when using ASGs?

### ISSUE THREAD

**Issue by raypettersen** [opentelekomcloud/terraform-provider-opentelekomcloud#506]
We're testing the ASG feature in the opentelekom cloud, which is working great. However we never get a clean terraform state, as the state seems to include the ec2 instance-ids. These vary naturally in an ASG, and terraform removes them on each run only to find new instance-ids on the next run.

Is this a bug or is there a fix/workaround for getting a clean state meaning no output on plan?

**Comment by ShiChangkuo** [comment]
@raypettersen we will add `Computed` attribute in the schema, will release in the next version.

For now, you can add [lifecycle meta-argument](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) in the ASG resource:
```
resource "huaweicloud_as_group_v1" "asg1" {
  # ...

  lifecycle {
    ignore_changes = [ instances ]
  }
}
```
