### ISSUE TITLE
Rename WAF attributes to match current API

### ISSUE THREAD

**Issue by schrej** [opentelekomcloud/terraform-provider-opentelekomcloud#509]
### Affected Resource(s)
- waf_domain_v1

As discussed in #496 the attributes of the waf domain resource should be renamed from `front_protocol` to `client_protocol` and from `back_protocol` to `server_protocol`. There is a guide from terraform that explains how to do that properly by deprecating the old names [here](https://www.terraform.io/docs/extend/best-practices/deprecations.html#renaming-a-required-attribute).

### References
- #496 (initial PR)
- #507 (reverts the parameter renaming)

**Comment by outcatcher** [comment]
@schrej It seems to be implemented in #496. If you still need this issue, please reopen it

**Comment by schrej** [comment]
The renaming got reverted in #507, we still need to rename the parameters but using the deprecation methods of terraform. That's why this issue exists.
I can't reopen unfortunately.
