### ISSUE TITLE
[VPNaaSv2] Feature request for opentelekomcloud_vpnaas_service_v2 datasource

### ISSUE THREAD

**Issue by lnobach** [opentelekomcloud/terraform-provider-opentelekomcloud#516]
Hi,

this is a request to provide datasources for the VPNaaS components, especially the VPNaaS service.

### Reason
In many cases, you want to create the VPN service in a lower layer (TF, manually, whatever), so you can keep the VPN service's IP address constant and maintain a stable IPSec endpoint. Only this way you can safely recreate your IPSec connection.

If you want to keep your code clean (not juggle with UUIDs in it), you need to have a datasource to be able to query for the VPN service (e.g. by name and corresponding VPC) and to use it with your site connection.

### Provider Version
Current Git master

### Affected Resource(s)
- opentelekomcloud_vpnaas_service_v2
- (opentelekomcloud_vpnaas_*)

**Comment by outcatcher** [comment]
Will be closed after release 1.20.0

**Comment by outcatcher** [comment]
Done in release v1.19.5 
@lnobach please add a comment here if you still need the issue
