### ISSUE TITLE
Error when updating ASG.

### ISSUE THREAD

**Issue by raypettersen** [opentelekomcloud/terraform-provider-opentelekomcloud#519]
### Terraform Version
0.12.25

### Affected Resource(s)
Please list the resources as a list, for example:
- opentelekomcloud_as_group_v1
- opentelekomcloud_as_configuration_v1

### Terraform Configuration Files
```
# Proxy AS configuration
resource "opentelekomcloud_as_configuration_v1" "proxy" {
  scaling_configuration_name = "proxy-${random_id.ASG.id}"
  instance_config {
    flavor    = var.flavor_id
    image     = var.image_id
    key_name  = var.key_name
    user_data = data.template_file.proxy.rendered
    disk {
      size        = var.disk
      volume_type = "SATA"
      disk_type   = "SYS"
    }
    metadata = {
      environment  = var.puppet_environment
      generator    = "terraform"
      puppetmaster = var.puppetmaster_fqdn
      role         = var.puppet_role
      autoscaling  = "proxy_ASG"
    }
  }
}

resource "opentelekomcloud_as_group_v1" "proxy" {
  scaling_group_name           = "proxy-${random_id.ASG.id}"
  scaling_configuration_id     = opentelekomcloud_as_configuration_v1.proxy.id
  available_zones              = data.openstack_compute_availability_zones_v2.available.names
  desire_instance_number       = var.asg_desired
  min_instance_number          = var.asg_min
  max_instance_number          = var.asg_max
  vpc_id                       = var.vpc_id
  delete_publicip              = true
  delete_instances             = "yes"
  health_periodic_audit_method = "ELB_AUDIT"
  networks {
    id = var.subnet_id
  }
  security_groups {
    id = module.sglinux.secgroup.id
  }

  lifecycle {
    ignore_changes = [
      instances
    ]
  }
}
```

### Debug Output
```
2020/06/08 09:26:45 [DEBUG] module.proxy.opentelekomcloud_as_configuration_v1.proxy: apply errored, but we're indicating that via the Error pointer rather than returning it: Can not delete the configuration "08c54745-1d78-4afa-8b3f-5c4bb8afc23c", it is used by AS groups [c9c7880f-351f-40df-9b1a-c1c741c28d35].
2020/06/08 09:26:45 [ERROR] module.proxy: eval: *terraform.EvalApplyPost, err: Can not delete the configuration "08c54745-1d78-4afa-8b3f-5c4bb8afc23c", it is used by AS groups [c9c7880f-351f-40df-9b1a-c1c741c28d35].
2020/06/08 09:26:45 [ERROR] module.proxy: eval: *terraform.EvalSequence, err: Can not delete the configuration "08c54745-1d78-4afa-8b3f-5c4bb8afc23c", it is used by AS groups [c9c7880f-351f-40df-9b1a-c1c741c28d35].
2020/06/08 09:26:45 [ERROR] module.proxy: eval: *terraform.EvalOpFilter, err: Can not delete the configuration "08c54745-1d78-4afa-8b3f-5c4bb8afc23c", it is used by AS groups [c9c7880f-351f-40df-9b1a-c1c741c28d35].​
```

### Expected Behavior
ASG updates should go through without issues. Updating ECS image for instance and similar.

### Actual Behavior
Terraform errors, and is unable to delete/update the ASG configuration.
```
Error: Can not delete the configuration "08c54745-1d78-4afa-8b3f-5c4bb8afc23c", it is used by AS groups [c9c7880f-351f-40df-9b1a-c1c741c28d35].
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by ShiChangkuo** [comment]
@raypettersen can you provide the result of `terraform plan` ?

**Comment by tomfankhaenel** [comment]
I can also report the same issue on my end. It is impossible to perform any update on an existing autoscaling configuration with the terraform provider.

#### The expected behavior:
create a new configuration -> update the ASG Group to point to the new configuration -> delete the old configuration

Instead it is just trying to delete the current configuration. It seems like some logic issue here because you can perform these steps manually.

**Comment by kschu91** [comment]
I am experiencing exactly the same issue. When changing a `opentelekomcloud_as_configuration_v1` the provider tries to delete the `opentelekomcloud_as_configuration_v1` which it can´t because it is still used by the the mrespective `opentelekomcloud_as_group_v1`.
However, I would have expect the provider to:
1. Create a new `opentelekomcloud_as_configuration_v1`
2. Update the `opentelekomcloud_as_group_v1` to use the new  `opentelekomcloud_as_configuration_v1`
3. Delete the old  `opentelekomcloud_as_configuration_v1`

## Code to reproduce
```
resource "opentelekomcloud_as_configuration_v1" "xyz" {
  scaling_configuration_name = "xyz"
  instance_config {
    flavor = "s2.large.4"
    image = "320457b8-88c2-43b9-8920-***"
    disk {
      size = 40
      volume_type = "SATA"
      disk_type = "SYS"
    }
    key_name = opentelekomcloud_compute_keypair_v2.xyz.name
    user_data = file("user_data/init.sh")
  }
}

resource "opentelekomcloud_as_group_v1" "xyz" {
  scaling_group_name = "xyz"
  scaling_configuration_id = opentelekomcloud_as_configuration_v1.xyz.id
  desire_instance_number = 2
  min_instance_number = 0
  max_instance_number = 2
  networks {
    id = data.terraform_remote_state.network.outputs.network_id
  }
  security_groups {
    id = opentelekomcloud_compute_secgroup_v2.xyz.id
  }
  vpc_id = data.terraform_remote_state.network.outputs.vpc_id
  delete_publicip = true
  delete_instances = "yes"
}
```

## terraform plan
```
Resource actions are indicated with the following symbols:
  ~ update in-place
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # opentelekomcloud_as_configuration_v1.xyzmust be replaced
-/+ resource "opentelekomcloud_as_configuration_v1" "xyz" {
      ~ id                         = "2fe6b880-d741-4fac-b242-***" -> (known after apply)
      + region                     = (known after apply)
        scaling_configuration_name = "xyz"

      ~ instance_config {
            flavor    = "s2.large.4"
            image     = "320457b8-88c2-43b9-8920-***"
            key_name  = "ops"
          - metadata  = {} -> null
          ~ user_data = <<~EOT # forces replacement
              - #!/bin/bash
              ...
              + 2ba92ed0f4da7c58fa5c83c81ead4c8cb0373e3b
            EOT

          ~ disk {
                disk_type   = "SYS"
                size        = 40
                volume_type = "SATA"
            }

            public_ip {
                eip {
                    ip_type = "5_bgp"

                    bandwidth {
                        charging_mode = "traffic"
                        share_type    = "PER"
                        size          = 5
                    }
                }
            }
        }
    }

  # opentelekomcloud_as_group_v1.xyzwill be updated in-place
  ~ resource "opentelekomcloud_as_group_v1" "xyz" {
        cool_down_time               = 900
        current_instance_number      = 2
        delete_instances             = "yes"
        delete_publicip              = true
        desire_instance_number       = 2
        health_periodic_audit_method = "NOVA_AUDIT"
        health_periodic_audit_time   = 5
        id                           = "7241022d-51c6-4fcc-9754-***"
        instance_terminate_policy    = "OLD_CONFIG_OLD_INSTANCE"
        instances                    = [
            "164bf0f2-405a-4573-9edb-***",
            "a8699cd4-3dc1-4cca-9c8d-***",
        ]
        max_instance_number          = 2
        min_instance_number          = 0
        region                       = "eu-de"
      ~ scaling_configuration_id     = "2fe6b880-d741-4fac-b242-***" -> (known after apply)
        scaling_group_name           = "xyz"
        status                       = "INSERVICE"
        vpc_id                       = "ab2ca88f-53ca-4379-b08a-***"

        networks {
            id = "e3469248-24bf-43da-a7ad-***"
        }

        security_groups {
            id = "f1c5063d-6881-4b04-9118-***"
        }
    }

Plan: 1 to add, 1 to change, 1 to destroy.
```

## terraform apply
```
2020/06/25 16:12:31 [DEBUG] opentelekomcloud_as_configuration_v1.xyz: applying the planned Delete change
opentelekomcloud_as_configuration_v1.xyz: Destroying... [id=2fe6b880-d741-4fac-b242-***]
2020/06/25 16:12:31 [DEBUG] opentelekomcloud_as_configuration_v1.xyz: apply errored, but we're indicating that via the Error pointer rather than returning it: Can not delete the configuration "2fe6b880-d741-4fac-b242-***", it is used by AS groups [7241022d-51c6-4fcc-9754-***].
2020/06/25 16:12:31 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: Can not delete the configuration "2fe6b880-d741-4fac-b242-***", it is used by AS groups [7241022d-51c6-4fcc-9754-***].
2020/06/25 16:12:31 [ERROR] <root>: eval: *terraform.EvalSequence, err: Can not delete the configuration "2fe6b880-d741-4fac-b242-***", it is used by AS groups [7241022d-51c6-4fcc-9754-***].
2020/06/25 16:12:31 [ERROR] <root>: eval: *terraform.EvalOpFilter, err: Can not delete the configuration "2fe6b880-d741-4fac-b242-***", it is used by AS groups [7241022d-51c6-4fcc-9754-***].

Error: Can not delete the configuration "2fe6b880-d741-4fac-b242-***", it is used by AS groups [7241022d-51c6-4fcc-9754-***].
```

**Comment by outcatcher** [comment]
I've prepared a fix for this issue (#531), but I'm not sure if it should be merged.

Implementation is basically internally creating new AS config, changing config ID in ASGs assigned, and removing the old one, as there is no way to modify AS configuration (we can only create and delete them, this is API restrictions).
The problem ― it's impossible to make it consistent with the current Terraform approach, changes in one resource (AS config) implicitly changes another resource (ASG), breaking plan phase, which `terraform plan` can't predict.

More importantly, this change leads to errors when using consecutive `terrafrom plan` and `terraform apply` ― after version 0.12 Terraform is strict for the difference between `plan` and `apply`.

I've checked other cloud providers approach and found out, that OTC AS groups/configurations is pretty same as AS groups + launch configuration from AWS. And AWS provider behaves the same way as OTC provider currently, showing 400 error when trying to modify launch configuration assigned to AS group(s).

**Comment by lushanlushan** [comment]
> I've prepared a fix for this issue (#531), but I'm not sure if it should be merged.
> 
> Implementation is basically internally creating new AS config, changing config ID in ASGs assigned, and removing the old one, as there is no way to modify AS configuration (we can only create and delete them, this is API restrictions).
> The problem ― it's impossible to make it consistent with the current Terraform approach, changes in one resource (AS config) implicitly changes another resource (ASG), breaking plan phase, which `terraform plan` can't predict.
> 
> More importantly, this change leads to errors when using consecutive `terrafrom plan` and `terraform apply` ― after version 0.12 Terraform is strict for the difference between `plan` and `apply`.
> 
> I've checked other cloud providers approach and found out, that OTC AS groups/configurations is pretty same as AS groups + launch configuration from AWS. And AWS provider behaves the same way as OTC provider currently, showing 400 error when trying to modify launch configuration assigned to AS group(s).

Hi, thanks a lot for the clarification. 

Could you please also check @kschu91 's idea about create new AS configuration and replace the old AS config in ASG?
This is a quite reasonable operation and could be easily done in Console and via API.

**Comment by outcatcher** [comment]
After some more investigation, there is a total solution for this problem in this issue:

Add to the AS configuration the following:
```hcl2
  lifecycle  {
    create_before_destroy=true
  }
```

In this case, no second configuration required at all

https://www.hashicorp.com/blog/zero-downtime-updates-with-terraform/
https://www.terraform.io/docs/configuration/resources.html#lifecycle-lifecycle-customizations


Works for me like that:
```
$ tf apply -auto-approve

data.openstack_compute_availability_zones_v2.available: Refreshing state...
data.opentelekomcloud_vpc_v1.vpc: Refreshing state...
data.opentelekomcloud_vpc_subnet_v1.subnet: Refreshing state...
opentelekomcloud_compute_secgroup_v2.secgroup: Refreshing state... [id=85423398-34eb-4d1e-9a9b-e3b20c6010c0]
data.opentelekomcloud_images_image_v2.img: Refreshing state...
opentelekomcloud_as_configuration_v1.cfg1: Refreshing state... [id=165133f1-71d7-40f2-9f5f-ae18644b6a13]
opentelekomcloud_as_group_v1.grp: Refreshing state... [id=bf2f7181-d419-481e-bf2b-ccb4079c4208]
opentelekomcloud_as_configuration_v1.cfg1: Creating...
opentelekomcloud_as_configuration_v1.cfg1: Creation complete after 1s [id=6441dd26-e844-4af7-a23d-78960aefc650]
opentelekomcloud_as_group_v1.grp: Modifying... [id=bf2f7181-d419-481e-bf2b-ccb4079c4208]
opentelekomcloud_as_group_v1.grp: Modifications complete after 2s [id=bf2f7181-d419-481e-bf2b-ccb4079c4208]
opentelekomcloud_as_configuration_v1.cfg1: Destroying... [id=165133f1-71d7-40f2-9f5f-ae18644b6a13]
opentelekomcloud_as_configuration_v1.cfg1: Destruction complete after 1s
```

**Comment by lushanlushan** [comment]
Just tested, the lifecycle configuration works. Thanks.

**Comment by kschu91** [comment]
Just tested it as well and it works. Thanks!

But, OTC does not rotate instances created by an AS group when its AS configuration changes :(. This is very sad, but this is more an issue with the OTC itself rather than with the terraform provider I guess.

I would expected the OTC to rotate the instances when the configuration of the AS group change.

@outcatcher do you experience the same?

**Comment by outcatcher** [comment]
@kschu91 sadly, this is how it's described in documentation too:
>When the AS configuration of an AS group is changed, the existing instances created using the original AS configuration are not affected.


https://docs.otc.t-systems.com/api/as/en-us_topic_0043063036.html

**Comment by raypettersen** [comment]
We do scale-out and scale-ins for rotating the ASG after an update.

**Comment by outcatcher** [comment]
@raypettersen Is the issue resolved using `create_before_destroy=true`?

**Comment by raypettersen** [comment]
Seems to be the case. We were having some other issues as well, but they somehow resolved themselves without us having the opportunity to debug further so we're not sure this ticket was related. I think I'll close this for now though. Thanks for the help to everyone who was involved.
