### ISSUE TITLE
Shared SNAT enable on creation

### ISSUE THREAD

**Issue by mvasilenko** [opentelekomcloud/terraform-provider-opentelekomcloud#52]
Hi there,

I'm creating VPC with mix of instances with floating IP and without floating IP. 

After creation, instances which don't have floating IP, can't access Internet by default, unless Shared SNAT is enabled manually in OTC GUI console.

### Terraform Version
Terraform v0.11.3
+ provider.null v1.0.0
+ provider.opentelekomcloud (unversioned)

### Affected Resource(s)
opentelekomcloud_networking_router_v2

### Terraform Configuration Files
```hcl
resource "opentelekomcloud_networking_router_v2" "k8s" {
  name                = "${var.cluster_name}-router"
  admin_state_up      = "true"
  external_gateway = "${var.external_net}"
}
```

### Expected Behavior
Instances with floating IP can access Internet
Instances without floating IP can access Internet

### Actual Behavior
Instances with floating IP can access Internet
Instances without floating IP cannot access Internet

### Steps to Reproduce
Create router, interface, assign subnet, 
create instances with and without floating IP in the same subnet.

### Important Factoids
default security group allows all outbound traffic

**Comment by rkno82** [comment]
Hi @mvasilenko,

as a user I can provide you a workaround for that.
Atleast the compatibility to the Openstack provider is working.

```hcl
resource "openstack_networking_router_v2" "router" {
  name                = "vpc-router"
  admin_state_up      = true
  enable_snat         = true
  external_network_id = "${data.openstack_networking_network_v2.extnet.id}"
}
```

**Comment by niuzhenguo** [comment]
@rkno82 Thanks for the explanation!
@mvasilenko Please let us know if that works, opentelekomcloud_networking_router_v2 is indeed compatible with OpenStack provider, and a new opentelekomcloud_vpc_v1 resources will be added soon.

**Comment by mvasilenko** [comment]
@rkno82 thank you for hint

Mixing different providers in one config is not the best thing, but it's working.

I've tried to use terraform generic OpenStack provider with OTC cloud, hit another issue, 
terraform doesn't save to state file floating IP associations correctly,
no such issue with opentelekomcloud provider

https://github.com/terraform-providers/terraform-provider-openstack/issues/88

**Comment by niuzhenguo** [comment]
@mvasilenko Please try with this PR #53

**Comment by mvasilenko** [comment]
@niuzhenguo looks good, thank you for another solution, closing this
