### ISSUE TITLE
[Documentation] Wrong attribute name in opentelekomcloud_kms_key_v1 

### ISSUE THREAD

**Issue by bflugon** [opentelekomcloud/terraform-provider-opentelekomcloud#520]
### Affected Resource(s)
- opentelekomcloud_kms_key_v1 

### Expected Behavior
The attribute `key_id` should work.

### Actual Behavior
Using the attribute results in the following error:
```
This object has no argument, nested block, or exported attribute named "key_id".
```
However, using the attribute `id` seems to give the desired outcome

### Steps to Reproduce
1. Add a opentelekomcloud_kms_key_v1 resource
2. Try to refer to that resource by `key_id`
3. `terraform apply`

**Comment by niuzhenguo** [comment]
@bflugon Thanks for raising this, will update the documentation and please use `id` instead.
