### ISSUE TITLE
[Documentation] Mail-enabled EIP not documented

### ISSUE THREAD

**Issue by bflugon** [opentelekomcloud/terraform-provider-opentelekomcloud#524]
According to your documentation ( https://www.terraform.io/docs/providers/opentelekomcloud/r/vpc_eip_v1.html#type ) only `5_bgp` is supported as EIP type.

We have successfully deployed a `5_mailbgp` EIP with the resource, so the documentation should be updated to reflect that.

**Comment by ShiChangkuo** [comment]
The documentation is outdated as the API has updated, but it's hard to trace the supported values in API.

reference to the API documentation will be better.
