### ISSUE TITLE
Unexpected Volume Deletion

### ISSUE THREAD

**Issue by atamis** [opentelekomcloud/terraform-provider-opentelekomcloud#526]
Hey, I encountered an unexpected volume deletion issue while using the OpenTelekomCloud Terraform Provider. I created a volume in one AZ, then attempted to create a server in another AZ. This should and does fail, producing a "faulty" server in OTC and a tainted resource in Terraform's state. Repeated applications of the Terraform configuration do not cause any issues (nor do they resolve the problem, but I wouldn't expect them to.) Deleting the faulty server in Terraform works just fine, but deleting the server in OTC also deletes the volume, even though the server doesn't have `delete_on_termination` enabled nor is the volume attached to the faulty server.

This _looks_ like an API issue, but I made the faulty server using the Terraform provider, so I figured I'd ask here first.

### Terraform Version

```
Terraform v0.12.27
```

### Affected Resource(s)
- `opentelekomcloud_evs_volume_v3`
- `opentelekomcloud_compute_instance_v2`

### Terraform Configuration Files
```hcl
resource "opentelekomcloud_evs_volume_v3" "repro" {
  name              = "repro-boot"
  availability_zone = "eu-de-01"
  volume_type       = "SATA"
  size              = 10
  # Debian 10 latest
  image_id = "fb7b0c9c-8b20-4e3f-832c-ea38c981c282"
}

resource "opentelekomcloud_compute_instance_v2" "repro-server" {
  name      = "repro-server"
  flavor_id = "s2.medium.1"
  # Note that this is a different AZ than the volume
  availability_zone = "eu-de-02"

  block_device {
    uuid             = opentelekomcloud_evs_volume_v3.repro.id
    source_type      = "volume"
    volume_size      = 10
    boot_index       = 0
    destination_type = "volume"
    volume_type      = "SATA"
    # This defaults to false, but let's set it anyway
    delete_on_termination = false
  }

  network {
    # This can be whatever subnet
    uuid = "ddbf1226-0fac-40dc-9631-13a98cec437a"
  }
}
```

### Debug Output
[Log from server creation](https://gist.github.com/atamis/5921700540506ee96519d95e9c366cd1)

[Log from successful server deletion](https://gist.github.com/atamis/abb6c43d3cd4abf68f7087a3aa4d0dc4)

No log available from OTC web UI interaction.

### Panic Output

No panic

### Expected Behavior
The server should have been deleted.

### Actual Behavior
The volume, while detached, was also deleted.

### Steps to Reproduce
1. Create volume in AZ 1
```hcl
resource "opentelekomcloud_evs_volume_v3" "repro" {
  name              = "repro-boot"
  availability_zone = "eu-de-01"
  volume_type       = "SATA"
  size              = 10
  # Debian 10 Latest Public image
  image_id          = "fb7b0c9c-8b20-4e3f-832c-ea38c981c282"
}
```
2. Apply. Volume should be visible in UI
3. Create server in AZ 2 and attach drive
``` terraform
resource "opentelekomcloud_compute_instance_v2" "repro-server" {
  name              = "repro-server"
  flavor_id         = "s2.medium.1"
  availability_zone = "eu-de-02"

  block_device {
    uuid                  = opentelekomcloud_evs_volume_v3.repro.id
    source_type           = "volume"
    volume_size           = 10
    boot_index            = 0
    destination_type      = "volume"
    volume_type           = "SATA"
    delete_on_termination = false
  }

  network {
    uuid =  "ddbf1226-0fac-40dc-9631-13a98cec437a"
  }
}
```
4. Apply
5. Check OTC UI, server should be faulty. EVS volume should be "Available" and
   not attached to the faulty server
6. Delete faulty server, ensuring that "delete data disks" is not checked.
7. Expected outcome: the faulty server is deleted
8. Actual outcome: the faulty server and the unattached volume are both deleted.
   (The volume can take a while to get deleted)

### Important Factoids

Our account is largely typical.

### References

None.

**Comment by outcatcher** [comment]
Hi,

I can see in [docs](https://docs.otc.t-systems.com/en-us/api/ecs/en-us_topic_0068473331.html) there is following mention: `When you create an ECS with a specified disk, ensure that the disk and the ECS are in the same AZ`.
When you define `block_device` with  `boot_index            = 0` it is assumed a [system disk](https://www.terraform.io/docs/providers/opentelekomcloud/r/compute_instance_v2.html#boot-from-an-existing-volume) and got removed together with server via console

@gtema please correct me, if I'm wrong

**Comment by smilemusic** [comment]
> Hey, I encountered an unexpected volume deletion issue while using the OpenTelekomCloud Terraform Provider. I created a volume in one AZ, then attempted to create a server in another AZ. This should and does fail, producing a "faulty" server in OTC and a tainted resource in Terraform's state. Repeated applications of the Terraform configuration do not cause any issues (nor do they resolve the problem, but I wouldn't expect them to.) Deleting the faulty server in Terraform works just fine, but deleting the server in OTC also deletes the volume, even though the server doesn't have `delete_on_termination` enabled nor is the volume attached to the faulty server.
> 
> This _looks_ like an API issue, but I made the faulty server using the Terraform provider, so I figured I'd ask here first.
> 
> ### Terraform Version
> ```
> Terraform v0.12.27
> ```
> 
> ### Affected Resource(s)
> * `opentelekomcloud_evs_volume_v3`
> * `opentelekomcloud_compute_instance_v2`
> 
> ### Terraform Configuration Files
> ```terraform
> resource "opentelekomcloud_evs_volume_v3" "repro" {
>   name              = "repro-boot"
>   availability_zone = "eu-de-01"
>   volume_type       = "SATA"
>   size              = 10
>   # Debian 10 latest
>   image_id = "fb7b0c9c-8b20-4e3f-832c-ea38c981c282"
> }
> 
> resource "opentelekomcloud_compute_instance_v2" "repro-server" {
>   name      = "repro-server"
>   flavor_id = "s2.medium.1"
>   # Note that this is a different AZ than the volume
>   availability_zone = "eu-de-02"
> 
>   block_device {
>     uuid             = opentelekomcloud_evs_volume_v3.repro.id
>     source_type      = "volume"
>     volume_size      = 10
>     boot_index       = 0
>     destination_type = "volume"
>     volume_type      = "SATA"
>     # This defaults to false, but let's set it anyway
>     delete_on_termination = false
>   }
> 
>   network {
>     # This can be whatever subnet
>     uuid = "ddbf1226-0fac-40dc-9631-13a98cec437a"
>   }
> }
> ```
> 
> ### Debug Output
> [Log from server creation](https://gist.github.com/atamis/5921700540506ee96519d95e9c366cd1)
> 
> [Log from successful server deletion](https://gist.github.com/atamis/abb6c43d3cd4abf68f7087a3aa4d0dc4)
> 
> No log available from OTC web UI interaction.
> 
> ### Panic Output
> No panic
> 
> ### Expected Behavior
> The server should have been deleted.
> 
> ### Actual Behavior
> The volume, while detached, was also deleted.
> 
> ### Steps to Reproduce
> 1. Create volume in AZ 1
> 
> ```terraform
> resource "opentelekomcloud_evs_volume_v3" "repro" {
>   name              = "repro-boot"
>   availability_zone = "eu-de-01"
>   volume_type       = "SATA"
>   size              = 10
>   # Debian 10 Latest Public image
>   image_id          = "fb7b0c9c-8b20-4e3f-832c-ea38c981c282"
> }
> ```
> 
> 1. Apply. Volume should be visible in UI
> 2. Create server in AZ 2 and attach drive
> 
> ```terraform
> resource "opentelekomcloud_compute_instance_v2" "repro-server" {
>   name              = "repro-server"
>   flavor_id         = "s2.medium.1"
>   availability_zone = "eu-de-02"
> 
>   block_device {
>     uuid                  = opentelekomcloud_evs_volume_v3.repro.id
>     source_type           = "volume"
>     volume_size           = 10
>     boot_index            = 0
>     destination_type      = "volume"
>     volume_type           = "SATA"
>     delete_on_termination = false
>   }
> 
>   network {
>     uuid =  "ddbf1226-0fac-40dc-9631-13a98cec437a"
>   }
> }
> ```
> 
> 1. Apply
> 2. Check OTC UI, server should be faulty. EVS volume should be "Available" and
>    not attached to the faulty server
> 3. Delete faulty server, ensuring that "delete data disks" is not checked.
> 4. Expected outcome: the faulty server is deleted
> 5. Actual outcome: the faulty server and the unattached volume are both deleted.
>    (The volume can take a while to get deleted)
> 
> ### Important Factoids
> Our account is largely typical.
> 
> ### References
> None.

Hi,

Terraform supports the use of existing evs as a system disk to create vms. Because vm and evs are in different availability zones, vm creation fails. Please make sure the parameters are correct when creating vm.
Because the system disk in the console is created in the background, the system will automatically recycle it when deleting ecs. This problem is recommended to ecs service work order.
