### ISSUE TITLE
[Feature Request] CTS Tracker per project

### ISSUE THREAD

**Issue by martingbl** [opentelekomcloud/terraform-provider-opentelekomcloud#530]
Hi there,
please provide the possibility to set the project for a CTS tracker.

### Terraform Version
Terraform v0.12.26

### Affected Resource(s)
- resource_opentelekomcloud_cts_tracker_v1.go 
- and everything affected https://github.com/terraform-providers/terraform-provider-opentelekomcloud/pull/135/files

### Expected Behavior
I expect to be able to provide a project name to the tracker (one tracker named system can be set per project)

### Actual Behavior
Only adds a tracker to the base project. E.g. `eu-de`

### References
- GH-135

**Comment by outcatcher** [comment]
@TheTaka96 can you please clarify your use case? Do you want to create trackers for multiple child projects authorizing with credentials for the base project?

**Comment by martingbl** [comment]
@outcatcher okay so the project named after the region will be described as region in the following and all "subprojects" will be called projects:

E.g. we have a region named `eu-de` in which we want several projects. For example `production` and `preproduction`.
Now those projects need a tracker to log changes in the environment (e.g. ECS creation) using an OBS Bucket.

The tracker on region level does not display the according information for the individual problems but it is the default value right now in Terraform.

I hope this was clear enough. Just adding and using a project variable on resource creation for the request url should be enough to fulfill this usecase.
