### ISSUE TITLE
Feature Request - CCE Cluster

### ISSUE THREAD

**Issue by otc-fabo** [opentelekomcloud/terraform-provider-opentelekomcloud#536]
Feature Request to support Plugins for opentelekomcloud_cce_cluster_v3 
https://docs.otc.t-systems.com/en-us/usermanual2/cce/cce_01_0064.html

espacially auto_scaler plugin to scale in / out the cluster.

**Comment by outcatcher** [comment]
@gtema I can't find CCE/k8s add-ons mentions in API documentation. Do you know any details on this topic?

**Comment by gtema** [comment]
Heh? No idea, will raise request

**Comment by otc-fabo** [comment]
please see https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0322.html

**Comment by outcatcher** [comment]
API: https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0320.html

**Comment by outcatcher** [comment]
CCE addon API is not working right now, issue created for OTC.
This issue will be postponed until API issue resolution.

**Comment by outcatcher** [comment]
Done in #711
