### ISSUE TITLE
Feature request - CCE Cluster Data Source should provide cluster certificates

### ISSUE THREAD

**Issue by almo-ltoeroek** [opentelekomcloud/terraform-provider-opentelekomcloud#546]
It would greatly simplify working with the TF Kubernetes Provider, if we could retrieve the CCE cluster certificates via the **opentelekomcloud_cce_cluster_v3** data source.

This is possible with the **opentelekomcloud_cce_cluster_v3** resource on creation and it is certainly possible to get the certificates [via the OTC API](https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0248.html).

Given an CCE cluster created in a given TF stack, I should be able to reference it in separate stack and use the TF Kubernetes provider as follows:

```terraform
variable "cluster_name" { }
variable "cluster_id" { }
variable "vpc_id" { }

data "opentelekomcloud_cce_cluster_v3" "cluster" {
   name = var.cluster_name
   id= var.cluster_id
   status= "Available"
  }

provider "kubernetes" {
  host               = opentelekomcloud_cce_cluster_v3.cluster.certificate_clusters.1.server
  client_certificate = base64decode(opentelekomcloud_cce_cluster_certificates_v3.cluster.certificate_users.0.client_certificate_data)
  client_key         = base64decode(opentelekomcloud_cce_cluster_certificates_v3.cluster.certificate_users.0.client_key_data)
  version            = "~> 1.11"
}
```

Alternatively, we could provide a dedicated data source, e.g. **opentelekomcloud_cce_cluster_v3_certificates** but I do not see much utility in that.

If there is support for this extension and consensus on how it should work, I would be willing to contribute a patch.

**Comment by outcatcher** [comment]
@almo-ltoeroek Can you please check in `v.1.19.2` if it works as you expect

**Comment by almo-ltoeroek** [comment]
@outcatcher thanks, I will check sometime this week

**Comment by outcatcher** [comment]
@almo-ltoeroek have you checked, if existing implementation is what you need?

**Comment by almo-ltoeroek** [comment]
@outcatcher thanks, works like a charm
