### ISSUE TITLE
[BugFix] Tag attribute for ecs

### ISSUE THREAD

**Issue by martingbl** [opentelekomcloud/terraform-provider-opentelekomcloud#547]
Hi there,

Please consider renaming the `tag`-attribute for ECS creation to `tags` as used in other resources.

### Terraform Version
Terraform v0.12.26
+ provider.ignition v1.2.1
+ provider.opentelekomcloud v1.18.0
+ provider.random v2.2.1

### Affected Resource(s)
https://www.terraform.io/docs/providers/opentelekomcloud/r/compute_instance_v2.html

### Expected Behavior
I expect the attribute to be `tags` as seen in references below.

### Actual Behavior
Attribute to set tags is `tag`

### References
https://www.terraform.io/docs/providers/opentelekomcloud/r/obs_bucket.html
https://www.terraform.io/docs/providers/opentelekomcloud/r/vpc_subnet_v1.html

**Comment by outcatcher** [comment]
@TheTaka96 as far, as I can see, `tags` was deprecated in 2019 (though it should still work)
@niuzhenguo can you please clarify, why was it deprecated?

**Comment by niuzhenguo** [comment]
`tags` was added following openstack tag pattern like [red, blue] which is not consistent with the key/value tags on Console. So we deprecate it and add a new key/value `tag`. I'm OK with remove the old `tags` and renaming `tag` to `tags` as other resources.
