### ISSUE TITLE
Deleting ECS also always deletes attached network ports, and terraform isn't aware of this

### ISSUE THREAD

**Issue by houst0n** [opentelekomcloud/terraform-provider-opentelekomcloud#548]
Hi there,

When making a change which requires a recreation of an ECS resource, if that ecs has an associated port then the port is deleted in a way that terraform is unaware of, and then when the ECS is recreated, tf tries to attach a port that no longer exists.

The only way to clean the state is to comment out the whole instance and do an apply, then uncomment.
Terraform Version

````
neilhouston:~/src/terraform/dev-devops$ terraform -v
Terraform v0.12.28

    provider.opentelekomcloud v1.18.0
````

Affected Resource(s)

Please list the resources as a list, for example:

  *  opentelekomcloud_networking_port_v2
  *  opentelekomcloud_compute_instance_v2

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
Terraform Configuration Files

````
resource "opentelekomcloud_networking_port_v2" "net_ports" {
  for_each       = var.instances
  name           = each.value["name"]
  network_id     = each.value["network_id"]
  admin_state_up = "true"

  security_group_ids = [
    for sec in each.value["sec_groups"] :
    sec
  ]

  fixed_ip {
    subnet_id  = each.value["subnet_id"]
    ip_address = each.value["ip_address"]
  }
}

locals {
  port_map = {
    for port in opentelekomcloud_networking_port_v2.net_ports :
    port.name => port.id
  }
}

resource "opentelekomcloud_compute_instance_v2" "ecs_instances" {
  for_each          = var.instances
  name              = each.value["name"]
  key_pair          = each.value["keypair"]
  availability_zone = each.value["az"]

  flavor_name = each.value["flavour_name"]

  block_device {
    uuid                  = each.value["image_id"]
    source_type           = "image"
    volume_size           = each.value["sysdisk_size"]
    boot_index            = 0
    destination_type      = "volume"
    delete_on_termination = true
    volume_type           = each.value["voltype"]
  }

  network {
    port = local.port_map[each.value["name"]]
  }
  
}
````

### Expected Behavior

Deleting an ECS should have a flag (such as "delete_disks_on_termination" but maybe "delete_ports_on_termination") which allows us to choose if we want this to happen.

### Actual Behavior

Deleting an ECS always deletes these port objects. We don't care too much if they are deleted, however since terraform is unaware of the change it doesn't know to recreate them. So we constantly have to comment out instances, do an apply, and uncomment them...

**Comment by houst0n** [comment]
This appears to be related to: https://bugs.launchpad.net/nova/+bug/1158684 which was fixed upstream in openstack some years ago. Can you confirm if this fix is present on your cloud?

**Comment by outcatcher** [comment]
@gtema Can you please clarify this issue? This seems to be an issue of OTC itself. ~For now I will add port unassignment on instance removal~ I can't see a way to gracefully unassign port from an instance right now.

**Comment by gtema** [comment]
While checking, should say following:

- seems due to some reason this fix is really not present
- unassigning ports is dangerous, since it might leave orphans in case of simple destruction of servers 
- nova fix unassigs port by resetting device_id and device_owner
- what is actually the reason for allocating port on the first side? Everything should be also achieved passing IP and SG directly to the server creation (makes template also cleaner)

**Comment by outcatcher** [comment]
@gtema It is easy to define which port was assigned manually, but there is one more problem with unassigning ports via API: 
[OTC won't accept `device_id` change](https://docs.otc.t-systems.com/api/vpc/vpc_port02_0003.html)
![image](https://user-images.githubusercontent.com/8591561/90786123-dec7c180-e30b-11ea-8a8d-405afe638c8c.png)

@houst0n It seems, the only working way right now is not to create ports manually, but pass sec groups and fixed IPs directly to `network {...` block of `opentelekomcloud_compute_instance_v2`

**Comment by houst0n** [comment]
We have to create ports for a number of reasons, such as our use of opentelekomcloud_networking_floatingip_associate_v2, and allowed_address_pairs = 1.1.1.1/0 and a few other reasons, mostly down to that the loadbalancers available to us still don't support the proxy protocol. in 2020.. 👍

Oh and we need to do some additional networky stuff for our kubernetes nodes usually also.

We will just have to live with this then, I guess?

**Comment by outcatcher** [comment]
It seems so. At least, until patch is applied on service side.

**Comment by outcatcher** [comment]
Internal issue: https://jira.tsi-dev.otc-service.com/browse/OCS-2332

**Comment by outcatcher** [comment]
Internal incident fixed. Issue not reproducing now.
