### ISSUE TITLE
add identity auth scope

### ISSUE THREAD

**Issue by AllaeddineEL** [opentelekomcloud/terraform-provider-opentelekomcloud#553]
Hi, 

it will be very helpful if the OTC provider has a data provider similar to openstack https://www.terraform.io/docs/providers/openstack/d/identity_auth_scope_v3.html

**Comment by outcatcher** [comment]
@AllaeddineEL This will be implemented after migration to the new SDK. At the time being, please use `openstack_identity_auth_scope_v3` ― it seems to be working correctly for OTC.

**Comment by outcatcher** [comment]
Implemented in latest release
