### ISSUE TITLE
cts_tracker_v1 not supporting All operations

### ISSUE THREAD

**Issue by otc-fabo** [opentelekomcloud/terraform-provider-opentelekomcloud#556]
can you please check the resource: cts_tracker_v1
https://www.terraform.io/docs/providers/opentelekomcloud/r/cts_tracker_v1.html
the parameter:
 operations - (Required) Trigger conditions for sending a notification.

should only be required if:
 is_send_all_key_operation 
is set to false.

as soon as it is set to true, operations isnt supported anymore. Please refer to the help center:
https://docs.otc.t-systems.com/en-us/api/cts/en-us_topic_0168602251.html

**Comment by lego963** [comment]
@otc-fabo may you clarify please? Because `is_send_all_key_operation` in [helpcenter ](https://docs.otc.t-systems.com/en-us/api/cts/en-us_topic_0168602251.html) says that: 
```
You can select Typical or All for Trigger Condition.

When the value is false, operations cannot be left empty.
When the value is true, operations is not supported.
```

**Comment by otc-fabo** [comment]
sure, this must be a boolean:
when trying to set it to a string: 
"details":{"details":"Invalid message body. The is_send_all_key_operation parameter value must be a Boolean value. Smn Error filed:is_send_all_key_operation,type:string."
True = All (When the value is true, operations is not supported.)
False = Typical (When the value is false, operations cannot be left empty.)

**Comment by lego963** [comment]
Sorry for delay @otc-fabo 
We have bugs in our API and we need time to fix them. Doc in [helpcenter](https://docs.otc.t-systems.com/en-us/api/cts/en-us_topic_0168602251.html) is outdated.
I suggest that soon we will solve this situation.

**Comment by lego963** [comment]
Internal issue: https://jira.tsi-dev.otc-service.com/browse/XAAS-3857

**Comment by philippeckel** [comment]
Hey @lego963 @outcatcher is there any update on this? 

Using multiple combinations I've managed to apply successfully, but the "Key Event Notifications" page in CTS is OTC Console is still empty.

```hcl
resource "opentelekomcloud_cts_tracker_v1" "tracker" {
  for_each                  = var.projects
  bucket_name               = opentelekomcloud_obs_bucket.audit.id
  is_support_smn            = true
  is_send_all_key_operation = false
  operations                = ["delete", "create", "login"]
  topic_id                  = opentelekomcloud_smn_topic_v2.cts_tracker[each.key].id
  project_name              = join("_", [var.project_name], [each.key])
  region                    = var.project_name
}
```

I would want to enable all operations but this does not seem to work.

Thanks!

**Comment by lego963** [comment]
@philippeckel will fix it in the soonest release :)
