### ISSUE TITLE
[Feature Request] Set name and tags for floating IP

### ISSUE THREAD

**Issue by martingbl** [opentelekomcloud/terraform-provider-opentelekomcloud#557]
Hi there,
Need to set name and tags for a floating external ip.
### Terraform Version
Terraform v0.12.26
+ provider.opentelekomcloud v1.18.0

### Affected Resource(s)
Please list the resources as a list, for example:
- resource_opentelekomcloud_networking_floatingip_v2.go

### Expected Behavior
Would love to be able to set more specifications e.g. tags and bandwidth name.
https://www.terraform.io/docs/providers/opentelekomcloud/r/compute_floatingip_v2.html

### Actual Behavior
What actually happened?
This is unable to do currently and whenever I rerun `terraform apply` a new, individual IP gets created

**Comment by outcatcher** [comment]
You should be able to set bandwidth size and name when using [`opentelekomcloud_vpc_eip_v1`](https://www.terraform.io/docs/providers/opentelekomcloud/r/vpc_eip_v1.html). Also, as far as I can see, only `vpc/eip` supports tags on API level: https://docs.otc.t-systems.com/api/vpc/eip_tag_0001.html, but not `opentelekomcloud_networking_floatingip_v2` or `opentelekomcloud_compute_floatingip_v2`

**Comment by gtema** [comment]
btw - opentelekomcloud_compute_floatingip_v2 should be completely dropped. We don't have (afaik) network support on compute API (this was looooong time ago deprecated)

**Comment by outcatcher** [comment]
@TheTaka96 Can you please check the comments above? :slightly_smiling_face:

**Comment by martingbl** [comment]
@outcatcher sry for my late responce. [opentelekomcloud_vpc_eip_v1](https://www.terraform.io/docs/providers/opentelekomcloud/r/vpc_eip_v1.html) works fine but has no tagging support

**Comment by outcatcher** [comment]
Got it, tag support to be added
