### ISSUE TITLE
OTC provider crashes with networking_subnet_v2 module

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#56]
### Terraform Version
```
Terraform v0.11.7
+ provider.opentelekomcloud v1.0.0
```

### Affected Resource(s)
- opentelekomcloud_networking_subnet_v2

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
https://pastebin.com/h9vDPbVk

### Debug Output
https://gist.github.com/Moep90/1ed2154aa1fd1662d4d5f4e7a7301ade

### Expected Behavior
Terraform should be able to create all resources as described

### Actual Behavior
terraform crashes with:
```
Error: Error applying plan:

4 error(s) occurred:

* opentelekomcloud_networking_subnet_v2.public_subnet_zone2: 1 error(s) occurred:

* opentelekomcloud_networking_subnet_v2.public_subnet_zone2: Error creating OpenTelekomCloud networking client: No suitable endpoint could be found in the service catalog.
* opentelekomcloud_networking_subnet_v2.public_subnet_zone1: 1 error(s) occurred:

* opentelekomcloud_networking_subnet_v2.public_subnet_zone1: Error creating OpenTelekomCloud networking client: No suitable endpoint could be found in the service catalog.
* opentelekomcloud_networking_subnet_v2.private_subnet_zone1: 1 error(s) occurred:

2018-04-30T16:42:26.057+0200 [DEBUG] plugin: plugin process exited: path=/home/danny/git-repos/terraform-nexboard/.terraform/plugins/linux_amd64/terraform-provider-opentelekomcloud_v1.0.0_x4
* opentelekomcloud_networking_subnet_v2.private_subnet_zone1: Error creating OpenTelekomCloud networking client: No suitable endpoint could be found in the service catalog.
* opentelekomcloud_networking_subnet_v2.private_subnet_zone2: 1 error(s) occurred:

* opentelekomcloud_networking_subnet_v2.private_subnet_zone2: Error creating OpenTelekomCloud networking client: No suitable endpoint could be found in the service catalog.
```

### Steps to Reproduce
1. `terraform init`
2. `terraform apply`

**Comment by niuzhenguo** [comment]
@Moep90 I tested with your provided terraform and opentelekom provider version for creating networking_subnet_v2 resource, but not crashed as your issue described. Is there something wrong with your credentials?

**Comment by Moep90** [comment]
@niuzhenguo I dont think so. I can create VPC, Router, Subnets....and destroy them.

username: 8 digits and than a space with OTC-etc
password: which I created within console.otc.t-systems.com
domain_name: OTC-etc...
endpoint: "https://iam.eu-de.otc.t-systems.com:443/v3"

**Comment by niuzhenguo** [comment]
@Moep90 let me try with the pasted configuration files.

**Comment by niuzhenguo** [comment]
@Moep90 The root cause of this is because you specified a wrong region "eu-de-01" for the subnet resources. Please try with "eu-de" instead.

```
resource` "opentelekomcloud_networking_subnet_v2" "private_subnet_zone1" {
  network_id = "${opentelekomcloud_networking_network_v2.vpc.id}"
  cidr       = "${var.cidr_private_subnets[0]}"
  region     = "${var.region[0]}"
  no_gateway = true
}
```

**Comment by niuzhenguo** [comment]
"eu-de-01" is availability zone instead of region!

**Comment by niuzhenguo** [comment]
@Moep90 Can you please help to confirm it, if no questions, I will close this, thanks!

**Comment by Moep90** [comment]
@niuzhenguo Thank you for your response, you where right. With `eu-de` as region everything works fine.
I also encounter that on many resources the region seams to be required instead of optional (as on the documentation page).
Should I open a new ticket for that?

**Comment by niuzhenguo** [comment]
@Moep90 region should be optional for all resources but required for provider configuration. If it is required on documentation page, we should fix it.

Yes, I think we need a new issue to track that.

**Comment by Moep90** [comment]
All right, I think I can report more within the next few weeks.
@niuzhenguo Thank you so far.
