### ISSUE TITLE
[CCE] can't get cluster_version of recently created cce

### ISSUE THREAD

**Issue by sfhl** [opentelekomcloud/terraform-provider-opentelekomcloud#565]
Hi there,

i am trying to get back the cce cluster version right after this cluster is created. Since cluster_version is not within the returned attributes, i am trying to accomplish this by using implicit dependencies. Sadly this does not work by using the returned cluster id. If i am using the returned cluster name, the dependency is not resolved and terraform complains about empty response *before* the cluster is created.

### Terraform Version
```
Terraform v0.12.24
+ provider.local v1.4.0
+ provider.opentelekomcloud v1.19.0
+ provider.template v2.1.2
```

### Affected Resource(s)
- opentelekomcloud_cce_cluster_v3

### Terraform Configuration Files
```hcl
...
resource "opentelekomcloud_cce_cluster_v3" "cce-test-test-test01-cce" {
  name                   = "cce-test-test-test01-cce"
  cluster_type           = "VirtualMachine"
  flavor_id              = "cce.s1.small"
  vpc_id                 = opentelekomcloud_vpc_v1.test-test.id
  subnet_id              = opentelekomcloud_vpc_subnet_v1.test-test-test01.id
  container_network_type = "overlay_l2"
  authentication_mode    = "rbac"
  description            = "Create cluster"

}

output "cce-test-test-test01-cce_internal" {
  value = opentelekomcloud_cce_cluster_v3.cce-test-test-test01-cce.internal
}

output "cce-test-test-test01-cce_external" {
  value = opentelekomcloud_cce_cluster_v3.cce-test-test-test01-cce.external
}

data "opentelekomcloud_cce_cluster_v3" "cce-test-test-test01-cce" {
  id = opentelekomcloud_cce_cluster_v3.cce-test-test-test01-cce.id
}

output "cce-test-test-test01-cce_cluster_version" {
  value = data.opentelekomcloud_cce_cluster_v3.cce-test-test-test01-cce.cluster_version
}
...
```

### Debug Output
https://gist.github.com/sfhl/fc4a0e432ac4f99f96ff48efd95c80c2

### Expected Behavior
Get information about specified cluster by id.

### Actual Behavior
terraform crashing

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by outcatcher** [comment]
There are at least two issues: 
1. `cluster_version` is not set when reading `resources/opentelekomcloud_cce_cluster_v3`
2. `id` is missing in `data_source/opentelekomcloud_cce_cluster_v3`

Started fixing

**Comment by outcatcher** [comment]
@sfhl 
Following data source can't be used this way, it seems to be an issue in documentation
```hcl
data "opentelekomcloud_cce_cluster_v3" "cce-test-test-test01-cce" {
  id = opentelekomcloud_cce_cluster_v3.cce-test-test-test01-cce.id
}
```
You should directly use 
```hcl
output "cce-test-test-test01-cce_cluster_version" {
  value = opentelekomcloud_cce_cluster_v3.cce-test-test-test01-cce.cluster_version
}
```
Though, it's `cluster_version` is not set during `opentelekomcloud_cce_cluster_v3` read ― this is fixed in #568

**Comment by outcatcher** [comment]
Please try with provider version 1.19.2

**Comment by sfhl** [comment]
Hi there,
with provider version 1.19.2 cluster_version is working now. Thank you very much!
