### ISSUE TITLE
Add support for setting user email

### ISSUE THREAD

**Issue by gtema** [opentelekomcloud/terraform-provider-opentelekomcloud#566]
Customers need to have possibility to set user email (which will be in-sync with what UI shows. https://docs.openstack.org/api-ref/identity/v3/index.html?expanded=update-user-detail#update-user is tested to work

**Comment by outcatcher** [comment]
@gtema seems to be a duplicate of #551

**Comment by outcatcher** [comment]
Will be fixed together with #551
