### ISSUE TITLE
[OBS] bucket policy "blocks" configured bucket acl

### ISSUE THREAD

**Issue by sfhl** [opentelekomcloud/terraform-provider-opentelekomcloud#571]
Hi there,

creating a obs bucket, with static website hosting enabled and acl set to public-read, seems to be enough for making static webcontent available inside this bucket. Sadly there are two locations to configure access. Even if acs is set to public-read, there is a "bucket policy" pre-configured to **private** and i am not able to change this via terraform.

There is a hint in the web ui:

_Bucket policies provide centralized access control and take precedence over bucket ACLs in case of permission conflicts._

### Terraform Version
Terraform v0.12.12
+ provider.local v1.4.0
+ provider.opentelekomcloud v1.19.0
+ provider.template v2.1.2

### Affected Resource(s)
- opentelekomcloud_s3_bucket

### Terraform Configuration Files
```hcl
resource "opentelekomcloud_s3_bucket" "test" {
  bucket = "test"
  acl = "public-read"

  versioning {
    enabled = true
  }

  website {
    index_document = "index.html"
    error_document = "index.html"
  }
}
```

### Expected Behavior
If set so, static webiste content should be available for public read.

### Actual Behavior
Static webiste content is not available for public read.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by outcatcher** [comment]
Hello @sfhl, you can control bucket policies with [opentelekomcloud_s3_bucket_policy](https://www.terraform.io/docs/providers/opentelekomcloud/r/s3_bucket_policy.html)
For policy configuration please check [Bucket Policy](https://docs.otc.t-systems.com/api_obs/obs/en-us_topic_0125560422.html) doc page

**Comment by sfhl** [comment]
Oh ok, thanks for clarifying, this!
