### ISSUE TITLE
[RDSv3] Recommended approach to bind EIP to an opentelekomcloud_rds_instance_v3

### ISSUE THREAD

**Issue by prigotti** [opentelekomcloud/terraform-provider-opentelekomcloud#587]
Hi,

This is more of a question than an issue/request.

I have a multilayered Terraform project that provisions a CCE cluster and deploys a few software components with Terraform's Helm provider from the public network. One of this components requires a SQL database, which I'm provisioning and trying to configure under the same project, by relying on the PostgreSQL provider to grant permissions to the user, etc.

As the `opentelekomcloud_rds_instance_v3` resource has neither an argument to bind an EIP or an attribute for a port ID that I can associate with a floating IP, what would be the recommended approach to provide public access to the RDSv3 instance using resources from the OTC provider?

### Terraform Version
```
Terraform v0.12.29
+ provider.opentelekomcloud v1.19.0
```

### Affected Resource(s)
- `opentelekomcloud_rds_instance_v3`

**Comment by outcatcher** [comment]
@PRigotti I wasn't able to find the way to bind EIP to RDS instance via Terraform. I suppose, I will add parameter `public_ip` to the RDS instance resource.

**Comment by gtema** [comment]
The general way of doing this is to find a port ID used by the RDS instance and attach a FIP on in. In UI it works pretty much same. Unfortunately this is not something easy map-able into TF.
Simply adding FIP param to instance creation will lead to following problems: how to unbind it, how to add to existing instance, how to change it. We should rather investigate how to find a port used by the instance from TF to use it further (similar for FIP assignment for the compute instances).

Very sad is that it is not easy to find the proper port. In difference to server this port does not contain proper device_id device_owner info (device_id=empty, device_owner=neutron:VIP_PORT). So the only chance is to get private IP of the instance and from that find the port. From that you will be able to assign FIP to it

**Comment by outcatcher** [comment]
@gtema It's easy, fiding the port with IP = RDS local IP, and local IP is returned when RDS instance is created.
The real problem ― when I assign port to the floating IP (e.g. `openstack floating ip set ... --port ...`, from RDS point of view it doesn't count (it works, but RDS doesn't know about it, both API returning empty floating IP and empty EIP list on console).
And RDS itself doesn't provide port assign API ― at east, I wasn't able to find it.

I suppose, we should implement this assigning using floating IP + port workflow (that what I was mentioning by `adding floating_ip parameter` and create issue for RDS service for providing required API.

**Comment by gtema** [comment]
> @gtema It's easy, fiding the port with IP = RDS local IP, and local IP is returned when RDS instance is created.

That's clear, but in perfect world device_id must be rds.id. Please also ensure you take network_id into consideration, since otherwise you might assign IP not where you really want it;-)

> The real problem ― when I assign port to the floating IP (e.g. `openstack floating ip set ... --port ...`, from RDS point of view it doesn't count (it works, but RDS doesn't know about it, both API returning empty floating IP and empty EIP list on console).
> And RDS itself doesn't provide port assign API ― at east, I wasn't able to find it.
> 
> I suppose, we should implement this assigning using floating IP + port workflow and create issue for RDS service for providing required API.

Agree, perhaps also requesting port.device_owner and port.device_id to be properly set as well

**Comment by prigotti** [comment]
>The real problem ― when I assign port to the floating IP (e.g. openstack floating ip set ... --port ..., from RDS point of view it doesn't count (it works, but RDS doesn't know about it, both API returning empty floating IP and empty EIP list on console).
And RDS itself doesn't provide port assign API ― at east, I wasn't able to find it.

Exactly. I tried this after @gtema first comment and got the same result.
The RDS API doesn't seem to support this out-of-the-box. Trove's latest CLIs have a `--is-public` option to do this, so perhaps it is only a matter of exposing functionality? Eitherway, you seem to have sorted it out.

Should I assume that there's no workaround with Terraform, either with OTC's or OpenStack's provider? If that's so, do you think I can solve this with a RDSv1 instance?

**Comment by gtema** [comment]
> Should I assume that there's no workaround with Terraform, either with OTC's or OpenStack's provider? If that's so, do you think I can solve this with a RDSv1 instance?

few issues with that:
- OTC RDS is not trove, so OpenStack provider is of no help
- V1 API is deprecated and might disappear "any day". It, however, offers binding API, so - might work at least for the transition period (https://docs.otc.t-systems.com/api/rds/rds_09_0001.html), but there is no TF support for that.

**Comment by prigotti** [comment]
>OTC RDS is not trove, so OpenStack provider is of no help

I see.

I guess I have other options, so no worries.

@outcatcher do you want me to edit the original post with more information and keep this open for you to keep track?
If there's no need, feel free to close this.

Thank you both.

**Comment by gtema** [comment]
- internal ticket for improvement is opened
- we still might try to give a workaround of implementing at least v1 assignment (it should still be ok to use v3 for db provisioning, but v1 for assignment), thus I would suggest to leave it open for tracking purposes

**Comment by outcatcher** [comment]
@PRigotti I suppose there is enough information now

**Comment by outcatcher** [comment]
@PRigotti Setting public IP is implemented in v1.19.3. But please note that this public IP won't be shown on the console for RDS, as RDS doesn't know about it.

**Comment by prigotti** [comment]
> @PRigotti Setting public IP is implemented in v1.19.3. But please note that this public IP won't be shown on the console for RDS, as RDS doesn't know about it.

That won't be an issue.

Thank you!
