### ISSUE TITLE
[GNUMakefile] website-test

### ISSUE THREAD

**Issue by lego963** [opentelekomcloud/terraform-provider-opentelekomcloud#588]
Since https://github.com/hashicorp/terraform-website/commit/03518a8e7cf7efc724c46acfc617ebbb3a2c4593 we have to fix our makefile

**Comment by gtema** [comment]
I guess we need then to reprioritize https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/577.

The website job is not required at all
