### ISSUE TITLE
[compute v2] ECS personality doesn't work

### ISSUE THREAD

**Issue by lego963** [opentelekomcloud/terraform-provider-opentelekomcloud#591]
Test file: `resource_opentelekomcloud_compute_instance_v2_test.go`
Test func: `TestAccComputeV2Instance_personality()`
Test passes, but ... personality files wasn't created.

**Comment by lego963** [comment]
Out API doesn't have such option as `personality`
[helpcenter doc](https://docs.otc.t-systems.com/en-us/api/ecs/en-us_topic_0068473331.html#EN-US_TOPIC_0068473331__en-us_topic_0057972661_table64008488102639)

**Comment by outcatcher** [comment]
`personality` to be removed in `v1.23.0`
