### ISSUE TITLE
Please add VPC Endpoint (VPCEP) to the provider

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud/terraform-provider-opentelekomcloud#606]
Hi, would you please add this to the provider:

https://open-telekom-cloud.com/en/support/release-notes/vpc-endpoint-available

Thank you
Robert

**Comment by gtema** [comment]
A yet another service not properly registered in the service catalog.

**Comment by outcatcher** [comment]
Internal issue: https://jira.tsi-dev.otc-service.com/browse/ONS-2977

**Comment by Benjamin-Justice** [comment]
Can you please implement this?

It was reported in september 2020 and is still not implemented in october 2021.

**Comment by outcatcher** [comment]
@Benjamin-Justice there are still no changes on the service side since; we will check what can we do for now.
@gtema maybe you have any ideas?

**Comment by lego963** [comment]
@Benjamin-Justice we will implement this functionality in the nearest releases. We didn't forget about this issue, we were waiting for a responsible squad solution.

**Comment by outcatcher** [comment]
Resource and data sources for the VPCEP service will be a part of v1.26.0 release

Done in #1474 #1470 #1467 #1466
