### ISSUE TITLE
Creating opentelekomcloud_smn_topic_v2 resource fails due to incorrect ProjectID

### ISSUE THREAD

**Issue by almo-ltoeroek** [opentelekomcloud/terraform-provider-opentelekomcloud#607]
### Terraform Version
Terraform v0.13.1
+ provider registry.terraform.io/hashicorp/kubernetes v1.12.0
+ provider registry.terraform.io/hashicorp/random v2.3.0
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.19.4

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance

### Terraform Configuration Files
```hcl
resource "opentelekomcloud_smn_topic_v2" "alarms" {
  name         = "alarms"
  display_name = "Alarms"
}

# This fails currently, waiting to hear back from OTC support
# Update: its not OTC API issue, an invalid Project ID is used
resource "opentelekomcloud_smn_subscription_v2" "email" {
  topic_urn = opentelekomcloud_smn_topic_v2.alarms.id
  protocol  = "email"
  endpoint  = "alarms@mycompany.com"
}
```
See the following gist:
https://gist.github.com/almo-ltoeroek/118c082341fc04d21ec60b9e42e4ffdd

### Debug Output
See the following gist:
https://gist.github.com/almo-ltoeroek/118c082341fc04d21ec60b9e42e4ffdd

### Expected Behavior
Both resources (alarm, subscription) should have been created.

### Actual Behavior
Creating the subscription failed with an error. The error was traced to an incorrect ProjectID parameter. It appears that the ProjectID used in the request **is the ParentID**, not the actual project ID.
I checked the current TF state file if it somehow got corrupted, but I did not find the "parentID" in there, so I suspect it is a bug somewhere in the code.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Copy the small repro snippet from above into a TF file
1. `terraform apply`

**Comment by outcatcher** [comment]
@lego963 Please check if this is produced by #554

@almo-ltoeroek Can you please check if the issue reproduces when `project_name` argument of smn topic is set to actually used project (same as `tenant_name` in provider config)

**Comment by lego963** [comment]
@outcatcher I've just tried to reproduce and I didn't face any problem with creation of these resources. I used terraform 0.13.2 version, but I don't think that this is our problem and
```hcl
provider "opentelekomcloud" {
  cloud = "otc"
}
```
![image](https://user-images.githubusercontent.com/17201690/92155738-8545b380-ee30-11ea-9594-9c225fd29308.png)

**Comment by lego963** [comment]
@almo-ltoeroek you are right, we will fix it

**Comment by almo-ltoeroek** [comment]
@outcatcher , I tried setting project_name within smn topic to the same value as the tenant_name in the otc provider block. This time I got a different issue, the subscription was NOT created still. See the debug output here:

https://gist.github.com/almo-ltoeroek/f7efbb6944519424cabcc2f49a028550

**Comment by outcatcher** [comment]
@almo-ltoeroek Please check the original issue with new release: v1.19.5. The problem should be solved

**Comment by lego963** [comment]
@almo-ltoeroek try new release, now it sents right project_id

**Comment by almo-ltoeroek** [comment]
@outcatcher I just ran terraform apply with the same config, and fails with the following:

```console
Error: topic: Expected HTTP response code [202 204] when accessing [GET https://smn.eu-de.otc.t-systems.com/v2/d58b8f8249784340bc64129894778d0d/notifications/topics/urn:smn:eu-de:d58b8f8249784340bc64129894778d0d:alarms], but got 200 instead
{"update_time":"2020-09-04T12:28:52Z","push_policy":0,"create_time":"2020-09-04T12:28:52Z","name":"alarms","topic_urn":"urn:smn:eu-de:d58b8f8249784340bc64129894778d0d:alarms","display_name":"Alarms in Test2","request_id":"A8FD95CC806947DDB298660643E72A0F"}

  on main.tf line 44, in resource "opentelekomcloud_smn_topic_v2" "alarms":
  44: resource "opentelekomcloud_smn_topic_v2" "alarms" {
```

I think there is bug for the GET handler, as it should indeed expect a 200. Maybe a copy and paste error from the POST handler?

**Comment by almo-ltoeroek** [comment]
@outcatcher the issue above only occurs, if you have an "alarms" instance in the state file, but it needs replacement. It gets deleted, and then the issue above occurs when TF attempts to recreate it.

If I clear out the TF state and start from scratch, I do not experience any issues.

**Comment by outcatcher** [comment]
@almo-ltoeroek Got it, I can reproduce it now. I also get 200 on alarm re-creation. If you're okay, I will create a new issue for that and close this one.

**Comment by almo-ltoeroek** [comment]
@outcatcher fine with me!

**Comment by outcatcher** [comment]
Closing this issue than
