### ISSUE TITLE
DDS resources and data sources are missing

### ISSUE THREAD

**Issue by franzs** [opentelekomcloud/terraform-provider-opentelekomcloud#619]
### Terraform Version
Terraform v0.13.2
doesn't matter actually.

### Affected Resource(s)
To be defined, e. g
`opentelekomcloud_dds_*`

### Expected Behavior
Being able to manage DDS with terraform.

### Actual Behavior
DDS resources and data sources are implemented in `opentelekomcloud` provider. 

### Links
- [DDS API](https://docs.otc.t-systems.com/api/dds/dds_api_reference.html)
- [DDS in golang SDK](https://github.com/huaweicloud/golangsdk/blob/master/openstack/dds/v3/instances/requests.go)

**Comment by niuzhenguo** [comment]
@outcatcher DDS in huaweicloud provider:
https://github.com/huaweicloud/terraform-provider-huaweicloud/blob/master/huaweicloud/resource_huaweicloud_dds_instance_v3.go

**Comment by lego963** [comment]
@franzs currently we have known issues with DDS creation. Resource `dds_instance` and data-source `dds_flavor` will be released when these issues will be fixed. :)

**Comment by lego963** [comment]
@franzs do you need the possibility to get info about concrete `dds_instance`? I mean, should we implement `data_source_opentelekomcloud_dds_instance_v3`? We've just implemented `flavor` data_source and `dds_instance` resource.

**Comment by outcatcher** [comment]
Part of `v1.21.6` release

@franzs please leave a comment is something is missing in `v1.21.6`

**Comment by franzs** [comment]
Thanks for your efforts. I think it would be nice to have a data source for a concrete `dds_instance`, too.

**Comment by outcatcher** [comment]
Okay, this will be part of the next release :slightly_smiling_face:

**Comment by outcatcher** [comment]
`dds_instance_v3` data source is part of release `v1.22.0`

**Comment by franzs** [comment]
@outcatcher Thanks a lot.
