### ISSUE TITLE
Add Software Repository for Container (SWR)

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#623]
# Terraform Version
Terraform v0.13.x
doesn't matter actually.

# Affected Resource(s)
To be defined, e. g
opentelekomcloud_swr_*

# Expected Behavior
Being able to manage SWR with terraform.

# Actual Behavior
SWR resources and data sources are implemented in opentelekomcloud provider.

# Links
[SWR API](https://docs.otc.t-systems.com/en-us/api/swr/swr_02_0001.html)

**Comment by gtema** [comment]
For the moment there is blocker for this - OTC is not exposing endpoint in the catalog. Until this is fixed no TF support is possible

**Comment by Moep90** [comment]
> For the moment there is blocker for this - OTC is not exposing endpoint in the catalog. Until this is fixed no TF support is possible

:-/
This is a blocker for us as well, any expectations till this is resolved?

**Comment by philippeckel** [comment]
Hey @outcatcher is there any update on this? 

Thanks!

**Comment by outcatcher** [comment]
It seems, waiting for it to be fixed can take forever. We have to use some workaround in this case.
