### ISSUE TITLE
OBS bucket creation fails using Federated Auth : InvalidAccessKeyId

### ISSUE THREAD

**Issue by deas** [opentelekomcloud/terraform-provider-opentelekomcloud#625]
### Terraform Version
v0.13.2.

### Affected Resource(s)
`opentelekomcloud_obs_bucket`

### Terraform Configuration Files
```hcl
variable "token" {}
variable "access_key" {}
variable "secret_key" {}
variable "security_token" {}
variable "domain_name" {}
variable "tenant_name" {}

provider "opentelekomcloud" {
  version     = "~> 1.19.0"
  token = var.token
  access_key = var.access_key
  secret_key = var.secret_key
  security_token = var.security_token
  domain_name = var.domain_name

  tenant_name = var.tenant_name
  auth_url    = "https://iam.eu-de.otc.t-systems.com/v3"

}

terraform {
  required_providers {
    opentelekomcloud = {
      source = "terraform-providers/opentelekomcloud"
    }
  }
}

resource "opentelekomcloud_obs_bucket" "fail" {
  bucket = "my-tf-test-bucket"
  acl    = "private"
  region = "eu-de"
}
```

```
# Set proper values
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export AWS_SESSION_TOKEN=
export TF_VAR_access_key=$AWS_ACCESS_KEY_ID
export TF_VAR_secret_key=$AWS_SECRET_ACCESS_KEY
export TF_VAR_security_token=$AWS_SESSION_TOKEN
export TF_VAR_token=
export TF_VAR_domain_name=
export TF_VAR_tenant_name=eu-de
```

### Debug Output
n/a

### Expected Behavior
Bucket should be created

### Actual Behavior
Bucket creation fails
```
Error: Error creating bucket my-tf-test-bucket: InvalidAccessKeyId,
 Reason: The AWS Access Key Id you provided does not exist in our records.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Initialize proper environment variables
```
# Set proper values
export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export AWS_SESSION_TOKEN=
export TF_VAR_access_key=$AWS_ACCESS_KEY_ID
export TF_VAR_secret_key=$AWS_SECRET_ACCESS_KEY
export TF_VAR_security_token=$AWS_SESSION_TOKEN
export TF_VAR_token=
export TF_VAR_domain_name=
export TF_VAR_tenant_name=eu-de
```
2. `terraform apply`

### Important Factoids
Use environment variables from above and try
```
aws --endpoint-url https://obs.otc.t-systems.com --region eu-de s3 mb s3://my-tf-test-bucket
``` 

This works for me and creates the bucket. Hence, I conclude the issue is not with the endpoint but with the terraform provider.

**Comment by outcatcher** [comment]
@deas Please use `opentelekomcloud_s3_bucket` instead of `opentelekomcloud_obs_bucket`. The latter doesn't support temporary AK/SK auth yet.
The following setup works for me:
```hcl
provider "opentelekomcloud" {
  token          = "..."
  access_key     = "..."
  secret_key     = "..."
  domain_name    = "..."
  security_token = "..."

  tenant_name = "eu-de"
  auth_url    = "https://iam.eu-de.otc.t-systems.com/v3"
}


resource "opentelekomcloud_s3_bucket" "fail" {
  bucket = "otc-akachuri-test2"
  acl    = "private"
  region = "eu-de"
}
```

**Comment by deas** [comment]
@outcatcher Thanks, good to know! :wink: However, what's the reason for providing two flavors of buckets?

**Comment by outcatcher** [comment]
It's not two flavors of buckets, just two different resources. S3 was existing for a long time already and OBS was planned as a "genuine OTC replacement of S3 resource" :slightly_smiling_face:. It was done in #467 which reference #464 as a reason.

**Comment by outcatcher** [comment]
This issue should still be fixed for the `obs_bucket` resource

**Comment by outcatcher** [comment]
`obs.New` doesn't support `security_token` argument. Needs a change in SDK:
```go
func New(ak, sk, endpoint string, configurers ...configurer) (*ObsClient, error)
```

**Comment by outcatcher** [comment]
@niuzhenguo As far as I can see, `huaweicloud` provider should have the same issue

**Comment by outcatcher** [comment]
The provider supports security token access since v1.20.2
