### ISSUE TITLE
[IAM] Please add all available iam roles into documentation

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud/terraform-provider-opentelekomcloud#637]
In https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/data-sources/identity_role_v3 not all available roles are documented.

I found e.g. "system_all_8" role as "Cloud Container Engine Cluster admin" is not in terraform documenation.

More information on how to get the roles via API:
* https://docs.otc.t-systems.com/en-us/api/iam/en-us_topic_0057845591.html
* GET https://iam.eu-de.otc.t-systems.com/v3/roles

**Comment by outcatcher** [comment]
@gtema can you please provide the list of roles available by default?

**Comment by robert1x2** [comment]
@outcatcher I queried the list. Would you add this to the official docu?


readonly | Tenant Guest
tms_adm | TMS Administrator
cce_adm | CCE Administrator
dcs_admin | DCS Administrator
dis_adm | DIS Administrator
system_all_8 | CCE Admin
system_all_15 | DDS FullAccess
system_all_6 | VPC Viewer
rds_adm | RDS Administrator
system_all_1001 | Full Access
system_all_3 | EVS Viewer
te_agency | Agent Operator
dms_adm | DMS Administrator
ces_adm | CES Administrator
system_all_9 | EPS Viewer
rts_adm | RTS Administrator
obs_b_list | OBS Buckets
system_all_11 | RDS ManageAccess
system_all_5 | VPC Admin
dns_adm | DNS Administrator
system_all_12 | RDS FullAccess
server_adm | Server Administrator
system_all_10 | EPS Admin
sdrs_adm | SDRS Administrator
system_all_14 | DDS ManageAccess
system_all_0 | ECS Admin
wks_adm | Workspace Administrator
te_admin | Tenant Administrator
waf_adm | WAF Administrator
system_all_7 | CCE Viewer
system_all_17 | DAS FullAccess
sfs_adm | SFS Administrator
vpc_netadm | VPC Administrator
css_adm | CSS Administrator
as_adm | AutoScaling Administrator
system_all_16 | DDS ReadOnlyAccess
csbs_adm | CSBS Administrator
swr_adm | SWR Administrator
das_admin | DAS Administrator
system_all_13 | RDS ReadOnlyAccess
secu_admin | Security Administrator
system_all_2 | ECS Viewer
dws_adm | DWS Administrator
mobs_adm | MaaS OBS
vbs_adm | VBS Administrator
ddos_adm | Anti-DDoS Administrator
system_all_4 | EVS Admin
system_all_1 | ECS User
dws_db_acc | DWS Database
kms_adm | KMS Administrator
mrs_adm | MRS Administrator
nat_adm | NAT Gateway
dds_adm | DDS Administrator
ims_adm | IMS Administrator
smn_adm | SMN Administrator
plas_adm | Config Plas
elb_adm | ELB Administrator
vpcep_adm | VPCEndpoint Administrator

**Comment by outcatcher** [comment]
@robert1x2 thank you, will update the doc
