### ISSUE TITLE
Support for SFS, RDS (HA)

### ISSUE THREAD

**Issue by rkno82** [opentelekomcloud/terraform-provider-opentelekomcloud#64]
Hi there,

do you plan to provide terraform support for SFS, RDS (HA), DDS and block device encryption for RDS and DDS?

Thanks,
Robert

**Comment by niuzhenguo** [comment]
@rkno82 sorry for the late reply. 
* SFS is comming soon!
* RDS with HA seems already supported on master branch, we will make a release soon, then update the outdated provider website docs.
* Regarding DDS, will check with the team then reply here later.

Thanks,
Zhenguo

**Comment by niuzhenguo** [comment]
@freesky-edward can you please help to confirm the DDS support, thanks!

**Comment by freesky-edward** [comment]
@rkno82 @niuzhenguo DDS is not in our plan, please let us know if indeed need to support. thanks.

**Comment by Moep90** [comment]
@niuzhenguo Is there a timeline when the release will be out?

**Comment by niuzhenguo** [comment]
@Moep90 I already tagged the release on github, just need to notify terraform team to make it available on the release list.

**Comment by niuzhenguo** [comment]
@Moep90 The new release v1.1.0 is available now, please check it out!

**Comment by niuzhenguo** [comment]
closing this, please feel free to reopen if there are still issues here.
