### ISSUE TITLE
[VPN] Missing support for latest PFS groups

### ISSUE THREAD

**Issue by cul-bsi** [opentelekomcloud/terraform-provider-opentelekomcloud#640]
# Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform,
please upgrade because your issue may have already been fixed.

> Terraform v0.12.26
> + provider.opentelekomcloud v1.20.2 

# Affected Resource(s)
Please list the resources as a list, for example:
- opentelekomcloud_vpnaas_ipsec_policy_v2
- opentelekomcloud_vpnaas_ike_policy_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_vpnaas_ike_policy_v2" "vpn1" {
  ike_version = "v2"
  encryption_algorithm = "aes-256"
  auth_algorithm = "sha2-256"
  pfs = "group16"
  lifetime {
    value = 28800
    units = "seconds"
  }
}

resource "opentelekomcloud_vpnaas_ipsec_policy_v2" "vpn1" {
  encryption_algorithm = "aes-256"
  auth_algorithm = "sha2-256"
  pfs = "group16"
  lifetime {
    value = 3600
    units = "seconds"
  }
}
```

# Debug Output/Panic Output
N/A

# Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply`

# Expected Behavior
What should have happened?
> PFS Group16 is selected and used in the policies.
> Second run of `terraform apply` does not show any differences pending.

# Actual Behavior
What actually happened?
> PFS Group16 is selected but not used in the policies, it falls back to default group5.
> Second run of `terraform apply` does show the differences pending, e.g. group5 -> group16.

# Important Factoids
N/A

# References
Code: https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/v1.20.2/opentelekomcloud/resource_opentelekomcloud_vpnaas_ipsec_policy_v2.go#L349
Doc IPsec: https://docs.otc.t-systems.com/api/vpn/en_topic_0093011504.html
Doc IKE: https://docs.otc.t-systems.com/api/vpn/en_topic_0093011510.html
Switch statement is not supporting options:
- group15
- group16
- group19
- group20
- group21

**Comment by cul-bsi** [comment]
@lego963 Hi, thanks for fixing the IKE policy. But unfortunately the IPsec policy still falls back to group5 if you choose anything higher than group14.

**Comment by lego963** [comment]
@cul-bsi I will check it, thanks 😊
