### ISSUE TITLE
Device attribute on compute storage attachment not working

### ISSUE THREAD

**Issue by martingbl** [opentelekomcloud/terraform-provider-opentelekomcloud#652]
Hi there, thank you for reading this issue.

# Terraform Version
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/template v2.1.2
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.19.3
+ provider registry.terraform.io/terraform-providers/ignition v1.2.1

# Affected Resource(s)
- opentelekomcloud_compute_volume_attach_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_compute_volume_attach_v2" "attach_storages_vdb" {
  for_each    = local.storages_vdb
  device      = "/dev/vdb"
  volume_id   = lookup(opentelekomcloud_blockstorage_volume_v2.storages, each.key).id
  instance_id = lookup(opentelekomcloud_compute_instance_v2.instances, each.value.instance_name).id 
  depends_on = [
    opentelekomcloud_blockstorage_volume_v2.storages,
    opentelekomcloud_compute_instance_v2.instances
  ]
}
```

# Debug Output/Panic Output
https://gist.github.com/TheTaka96/ffab61775ac6e47679370e3daa7fa538

# Steps to Reproduce
`terraform apply`
# Expected Behavior
Every Device should be "/dev/vdb" 

# Actual Behavior
but the value inserted is kinda random. I assume the default value "auto" does not get overwritten

# Important Factoids
Nothing atypical

# References
None found

**Comment by anton-sidelnikov** [comment]
Sorry for late answer:
according docs
https://docs.otc.t-systems.com/api/ecs/en-us_topic_0031167350.html

If user defined device name is not in conflict with already occupied device name it will be set accordingly otherwise system will decide and assign next following available device name. Parallels jobs can affect device letter mapping.

Workaround: use opentelekomcloud_compute_volume_attach_v2 not in parallel, just split this job

```
//This will be vdb
resource "opentelekomcloud_compute_volume_attach_v2" "attach1" {
    instance_id = opentelekomcloud_compute_instance_v2.http[0].id
    volume_id   = opentelekomcloud_blockstorage_volume_v2.volumes[0].id
}

//This will be vdc
resource "opentelekomcloud_compute_volume_attach_v2" "attach2" {
  instance_id = opentelekomcloud_compute_instance_v2.http[0].id
  volume_id   = opentelekomcloud_blockstorage_volume_v2.volumes[1].id
  depends_on = [
    opentelekomcloud_compute_volume_attach_v2.attach1
  ]
}
```

**Comment by martingbl** [comment]
Hello @anton-sidelnikov, 
So I got 10+ ecs with 3+ evs each to attach to and because afterwards there will be mounting of the devices I HAVE to set the device correctly. 
You now want to tell me that I have to write 30+ times the resource declaration `opentelekomcloud_compute_volume_attach_v2` depending on the previous one because the otc terraform provider cannot handle it by itself or did I missunderstand you?

**Comment by anton-sidelnikov** [comment]
@TheTaka96 This is not a provider issue, this is how otc works by now. We can't change it from provider.

**Comment by martingbl** [comment]
@anton-sidelnikov As far as I understood the API returns the provider if the value was successfully attached or not. If the attached value != the requested value and the requested value is not set to `auto`, couldn't it be possible for the terraform provider to wait for this value to be available again?

**Comment by anton-sidelnikov** [comment]
@TheTaka96 I would suggest attaching devices in batches using count = N and depends_on = opentelekomcloud_compute_volume_attach_v2.attach[count.index]

```
Something like this:
resource "opentelekomcloud_compute_volume_attach_v2" "attach" {
  count       = length(opentelekomcloud_blockstorage_volume_v2.volumes)
  instance_id = opentelekomcloud_compute_instance_v2.http[0].id
  volume_id   = opentelekomcloud_blockstorage_volume_v2.volumes[count.index].id
  depends_on = [
    opentelekomcloud_compute_volume_attach_v2.attach_vol[count.index]
  ]
}
```

**Comment by outcatcher** [comment]
- This is not the provider issue, but the issue of OTC itself
- No more actions from our side is required

@TheTaka96 please comment if you still need this issue to be open

**Comment by martingbl** [comment]
all fine, if anyone else is facing this issue I recommend using the ` block_device` block from instance creation because the resource `attachment ` with `foreach ` is broken. Using dynamic blocks works totally fine

**Comment by pkorsch** [comment]
> Sorry for late answer: according docs https://docs.otc.t-systems.com/api/ecs/en-us_topic_0031167350.html
> 
> If user defined device name is not in conflict with already occupied device name it will be set accordingly otherwise system will decide and assign next following available device name. Parallels jobs can affect device letter mapping.
> 
> Workaround: use opentelekomcloud_compute_volume_attach_v2 not in parallel, just split this job
> 
> ```
> //This will be vdb
> resource "opentelekomcloud_compute_volume_attach_v2" "attach1" {
>     instance_id = opentelekomcloud_compute_instance_v2.http[0].id
>     volume_id   = opentelekomcloud_blockstorage_volume_v2.volumes[0].id
> }
> 
> //This will be vdc
> resource "opentelekomcloud_compute_volume_attach_v2" "attach2" {
>   instance_id = opentelekomcloud_compute_instance_v2.http[0].id
>   volume_id   = opentelekomcloud_blockstorage_volume_v2.volumes[1].id
>   depends_on = [
>     opentelekomcloud_compute_volume_attach_v2.attach1
>   ]
> }
> ```

Is OTC changing something on background? now disks are attached as sda, sdb, sdc ...
