### ISSUE TITLE
rds_instance_v3 assign public ip

### ISSUE THREAD

**Issue by lstadnik** [opentelekomcloud/terraform-provider-opentelekomcloud#653]
Hi there, thank you for opening an issue.

# Terraform Version
0.12.29

# Affected Resource(s)
resource "opentelekomcloud_compute_floatingip_v2" "ip" {
}

resource "opentelekomcloud_rds_instance_v3" "instance" {
 availability_zone = [ "eu-de-02" ]
 db {
    password = "Telekom"
    type = "MySQL"
    version = "8.0"
  }
  name = "terraform_test_rds_instance"
  security_group_id = "dxxxx"
  subnet_id = "fxxxxx"
  vpc_id = "1xxxxx"
  volume {
    type = "ULTRAHIGH"
    size = 40
  }
  flavor = "rds.mysql.c2.medium"
  backup_strategy {
    start_time = "08:00-09:00"
    keep_days = 0
  }
  public_ips = [opentelekomcloud_compute_floatingip_v2.ip.address]
  tag = {
    test = "test-automation"
  }
  depends_on = [opentelekomcloud_compute_floatingip_v2.ip]
}

# Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan -out planfile`
2. `terraform apply "planfile"

# Expected Behavior
What should have happened?

Floating IP should be attached to the RDS instance 

# Actual Behavior
What actually happened?

I have to rerun twice terraform and the Public IP is assigned.

# Important Factoids
terraform-provider-opentelekomcloud_v1.20.2

# References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
```
- GH-1234
- #2546
```

**Comment by outcatcher** [comment]
@lucap01 Currently this issue is being fixed on the SDK level.
Also, please use [triple quotes](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) for code, i.e. ` ```hcl` for Terraform configurations.

**Comment by outcatcher** [comment]
Fixed in v1.21.1
