### ISSUE TITLE
Verify used Flavors in Provider Samples

### ISSUE THREAD

**Issue by ghost** [opentelekomcloud/terraform-provider-opentelekomcloud#673]
Please check the used Flavors in the terraform provider sample

For example:
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cce_node_v3

Here is still used s1.medium (XEN-Flavor) which is no longer available.
The successor s2.medium is to small.

Use s2.large.2 instead which is the smallest Node-Flavor

**Comment by outcatcher** [comment]
Fixed via #684 and #689 in v1.12.3 (not yet released)
