### ISSUE TITLE
OBS bucket creation not possible with agency auth

### ISSUE THREAD

**Issue by cgroschupp** [opentelekomcloud/terraform-provider-opentelekomcloud#713]
# Terraform Version
```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.21.4
```

# Affected Resource(s)
* opentelekomcloud_obs_bucket

# Terraform Configuration Files
```hcl
provider "opentelekomcloud" {
  agency_name        = "myagency"
  agency_domain_name = "OTC-EU-DE-00000000000000000000"
  delegated_project  = "eu-de"
}

resource "random_string" "random" {
  length = 16
  special = false
}

resource "opentelekomcloud_obs_bucket" "mybucket" {
  bucket = random_string.random.result
  acl    = "private"
}

```

# Steps to Reproduce
```
export OS_AUTH_URL=https://iam.eu-de.otc.t-systems.com/v3
export OS_AUTH_TOKEN=<mytoken>
terraform apply
```

# Expected Behavior

Bucket should be created

# Actual Behavior

Bucket creation fails

```
Error: Error creating OpenTelekomCloud OBS client: missing credentials for OBS, need access_key and secret_key or security_token values for provider

  on providers.tf line 12, in resource "opentelekomcloud_obs_bucket" "mybucket":
  12: resource "opentelekomcloud_obs_bucket" "mybucket" {
```

# Important Factoids

I know that the OBS bucket creation requires aksk values, but how do I proceed when using the agency auth. I use multiple providers, it is not possible for me to set the aksk token before.

**Comment by outcatcher** [comment]
Having a token, it's possible to create AK/SK with `opentelekomcloud_identity_credential_v3` resource. Though you won't be able to use created AK/SK in the same config, as it's set to the provider configuration. I suppose it should be possible to make AK/SK settable only for obs inside the resource configuration. I will check whenever it can be implemented.

**Comment by outcatcher** [comment]
Sorry, my previous comment is not actually valid. I've got mistaken agency auth with a simple one. For solving the problem described in the issue, internal usage of [temporary AK/SK](https://docs.otc.t-systems.com/en-us/api/iam/en-us_topic_0097949518.html) should be done. This to be implemented on the provider side. PRs referred to this issue previously are not related to it actually.

**Comment by outcatcher** [comment]
@cgroschupp Please check if it works as you expect in `v1.22.0`.
