### ISSUE TITLE
FIP Bandwidth support

### ISSUE THREAD

**Issue by gtema** [opentelekomcloud/terraform-provider-opentelekomcloud#716]
Management of the FIP bandwidth is required. Sadly this is another example of a version mix (1 + 2)

https://docs.otc.t-systems.com/api/eip/eip_apisharedbandwidth_0000.html
and
https://docs.otc.t-systems.com/api/eip/eip_apiBandwidth_0000.html

**Comment by outcatcher** [comment]
@gtema 
[`opentelekomcloud_vpc_eip_v1`](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/vpc_eip_v1) provides bandwidth configuration for EIP. Do you need some other features?

**Comment by gtema** [comment]
oh cool, haven't noticed that.
Is size update supported?
That would be already fine. Perhaps we need then possibility to manage shared bandwidth (allocate/attach/detach) so that use of opentelekomcloud_networking_floatingip_v2 can remain if desired

**Comment by outcatcher** [comment]
Yes, there is `bandwidth.Update` on size and name update. Bandwidth v2 is not implemented. I suppose, were should implement `opentelekomcloud_network_bandwidth_v2` in this case (both `r/` and `d/`)

**Comment by niuzhenguo** [comment]
Do you mean shared bandwidth here? https://github.com/huaweicloud/terraform-provider-huaweicloud/blob/master/huaweicloud/resource_huaweicloud_vpc_bandwidth.go

**Comment by outcatcher** [comment]
Bandwidth v2 API is missing now, only data source will be implemented in this release

**Comment by outcatcher** [comment]
Jira reference: https://jira.tsi-dev.otc-service.com/browse/ONS-3912

**Comment by outcatcher** [comment]
Bandwidth API is available on PROD now

**Comment by outcatcher** [comment]
Move data source to the next milestone
