### ISSUE TITLE
Please add new service CBR into it

### ISSUE THREAD

**Issue by robert1x2** [opentelekomcloud/terraform-provider-opentelekomcloud#724]
Would you please add this service into the provider?

Release Notes: https://open-telekom-cloud.com/en/support/release-notes/cloud-server-backup-service/cbr-new-service

OTC Console View: https://console.otctest.t-systems.com/cbr/?region=eu-de#/cbr/manager/csbs/vaultList

Thank you
Robert

**Comment by outcatcher** [comment]
Documentation reference: 
https://docs.otctest.t-systems.com/api/cbr/cbr_04_0015.html

**Comment by outcatcher** [comment]
Requires SDK changes, so will be moved to the next milestone

**Comment by outcatcher** [comment]
SDK not ready yet. Milestone will be set when SDK will be ready

**Comment by outcatcher** [comment]
@robert1x2 CBR vault and policy resources are implemented. Is anything else needed?

**Comment by outcatcher** [comment]
Please leave a comment if something else is required.
