### ISSUE TITLE
Identity services use strange SDK client

### ISSUE THREAD

**Issue by lego963** [opentelekomcloud/terraform-provider-opentelekomcloud#750]
This sdk client is using `identity` with `domain` level, but we have `identityV30Client`. Can we use it?

## Affected resources:
`resource_opentelekomcloud_identity_role_v3`

## Affected client:
```go
client, err := config.sdkClient("", "identity", serviceDomainLevel)
```

**Comment by outcatcher** [comment]
Resolved via #767
