### ISSUE TITLE
Catch unsupported version during "terraform plan"

### ISSUE THREAD

**Issue by tasansga** [opentelekomcloud/terraform-provider-opentelekomcloud#760]
# Terraform Version
opentelekomcloud/opentelekomcloud v1.21.6

# Affected Resource(s)
opentelekomcloud_cce_cluster_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_cce_cluster_v3" "internal_cluster" {
  [...]
  cluster_version        = "v1.17.9-r999"
  [...]
}
```

# Debug Output/Panic Output
"plan" runs fine, but apply fails:
```
Error: Error creating opentelekomcloud Cluster: Bad request with: [POST https://cce.eu-de.otc.t-systems.com/api/v3/projects/xxxxxxxxxxx/clusters], error message: {"error_code":"CCE_CM.0402","error_msg":"Version is not support","errorCode":"E.CFE.4000402","reason":"Version is not support"}

  on .terraform/modules/cluster/main.tf line 30, in resource "opentelekomcloud_cce_cluster_v3" "exposed_cluster":
  30: resource "opentelekomcloud_cce_cluster_v3" "exposed_cluster" {
```

# Steps to Reproduce
- Use an invalid version string
- Run "terraform plan", won't fail.
- Run "terraform apply", will fail.

# Expected Behavior
According to terraform's documentation, "plan" is expected to validate input parameters:

> To verify configuration in the context of a particular run (a particular target workspace, input variable values, etc), use the terraform plan command instead, which includes an implied validation check.
(Quote from https://www.terraform.io/docs/commands/validate.html)

# Actual Behavior
The execution fails during apply.

**Comment by lego963** [comment]
@tasansga Sorry for the delay. The Terraform plan command checks the entered values for correctness. It should not validate them in the provider. The values you pass are valid for the provider. Refs: #762

**Comment by tasansga** [comment]
What you describe is "terraform validate" which only verifies the input syntactically, but "terraform plan" indeed contacts the provider to verify the input makes sense semantically too. My quote above outlines this difference for "terraform validate" and "terraform plan".

**Comment by gtema** [comment]
Unfortunately there is no "reasonable" way to evaluate all parameters (API doesn't support a form of dry_run). Additionally there is no way to get all supported cluster versions from API. Without it the only way would be hardcoding of the possible values, but that is not something anybody would be happy about, since the list is often changing.

**Comment by outcatcher** [comment]
@tasansga you do quote validate comment help, but there is the following there:
>The terraform validate command validates the configuration files in a directory, referring only to the configuration and not accessing any remote services such as remote state, provider APIs, etc.

**Comment by tasansga** [comment]
@outcatcher : Please reread my comment which is about "plan" and not "validate". The difference between the two is outlined on terraform's "validate" page. Your comment's quote only refers to the "validate" command.
- validate checks syntax, i.e. x is a string, this works okay.
- plan checks semantic, i.e. x is a string that refers to a valid cluster version, and this is not checked.

**Comment by outcatcher** [comment]
@tasansga Yes, you are talking about `plan`, but quoting `validate` doc:
![image](https://user-images.githubusercontent.com/8591561/102186822-3e9e3580-3ec4-11eb-8627-34750374ad80.png)
I can't find in `plan` doc that it check for existance of something. Can you please give any example of other providers implementing validations like that in `plan`?
https://www.terraform.io/docs/commands/plan.html

**Comment by tasansga** [comment]
Sure, check https://github.com/hashicorp/terraform-provider-aws - it's EKS resource fails plan when given invalid network settings, for example.
And yes, terraform's docs could be better in that regard. The difference between plan and validate should clearly be outlined on the plan page itself but isn't. But you can read more about their intent here for example: https://github.com/hashicorp/terraform/issues/15895 

> terraform plan does all of the above checks for validate, then checks that provided variables are valid, configures the providers, refreshes existing state, does any additional validation that requires network access, and produces a diff showing changes from current state.

**Comment by tasansga** [comment]
> Unfortunately there is no "reasonable" way to evaluate all parameters (API doesn't support a form of dry_run). Additionally there is no way to get all supported cluster versions from API. Without it the only way would be hardcoding of the possible values, but that is not something anybody would be happy about, since the list is often changing.

Good point @gtema. I'm not familiar with their API, do they accept feature requests to make this possible?

**Comment by outcatcher** [comment]
@tasansga What I can see in AWS AKS provider, make all possible static validations, but I can't find anything like online checks. During the plan you can basically read-only data sources or refresh existing resources. For EKS there is still something that can't be validated during the plan. The following is checked only in the `Create` response:
```go
		_, err := conn.CreateCluster(input)
		if err != nil {
			// InvalidParameterException: roleArn, arn:aws:iam::123456789012:role/XXX, does not exist
			if isAWSErr(err, eks.ErrCodeInvalidParameterException, "does not exist") {
				return resource.RetryableError(err)
			}
			// InvalidParameterException: Error in role params
			if isAWSErr(err, eks.ErrCodeInvalidParameterException, "Error in role params") {
				return resource.RetryableError(err)
			}
			if isAWSErr(err, eks.ErrCodeInvalidParameterException, "Role could not be assumed because the trusted entity is not correct") {
				return resource.RetryableError(err)
			}
			// InvalidParameterException: The provided role doesn't have the Amazon EKS Managed Policies associated with it. Please ensure the following policies [arn:aws:iam::aws:policy/AmazonEKSClusterPolicy, arn:aws:iam::aws:policy/AmazonEKSServicePolicy] are attached
			if isAWSErr(err, eks.ErrCodeInvalidParameterException, "The provided role doesn't have the Amazon EKS Managed Policies associated with it") {
				return resource.RetryableError(err)
			}
			// InvalidParameterException: IAM role's policy must include the `ec2:DescribeSubnets` action
			if isAWSErr(err, eks.ErrCodeInvalidParameterException, "IAM role's policy must include") {
				return resource.RetryableError(err)
			}
			return resource.NonRetryableError(err)
		}
		return nil
```

**Comment by gtema** [comment]
> Good point @gtema. I'm not familiar with their API, do they accept feature requests to make this possible?

No, you will not even find a source code.

**Comment by outcatcher** [comment]
No updates for some time already, list versions functionality not going to be supported by OTC.
