### ISSUE TITLE
Catch invalid names during "terraform plan"

### ISSUE THREAD

**Issue by tasansga** [opentelekomcloud/terraform-provider-opentelekomcloud#761]
# Terraform Version
opentelekomcloud/opentelekomcloud v1.21.6

# Affected Resource(s)
opentelekomcloud_cce_cluster_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_cce_cluster_v3" "internal_cluster" {
  [...]
  name        = "ab"
  [...]
}
```

# Debug Output/Panic Output
"plan" runs fine, but apply fails:
```
Error: Error creating opentelekomcloud Cluster: Bad request with: [POST https://cce.eu-de.otc.t-systems.com/api/v3/projects/xxxxxxxxxxxxxx/clusters], error message: {"error_code":"CCE_CM.0201","error_msg":"Request body invalid","message":"The cluster name's length is below min value or exceed max value","errorCode":"E.CFE.4000201","reason":"Request body invalid"}

  on .terraform/modules/cluster/main.tf line 30, in resource "opentelekomcloud_cce_cluster_v3" "exposed_cluster":
  30: resource "opentelekomcloud_cce_cluster_v3" "exposed_cluster" {
```

# Steps to Reproduce
- Use too short name
- Run "terraform plan", won't fail.
- Run "terraform apply", will fail.

# Expected Behavior
According to terraform's documentation, "plan" is expected to validate input parameters:

> To verify configuration in the context of a particular run (a particular target workspace, input variable values, etc), use the terraform plan command instead, which includes an implied validation check.
(Quote from https://www.terraform.io/docs/commands/validate.html)

# Actual Behavior
The execution fails during apply.

**Comment by lego963** [comment]
@tasansga Sorry for the delay. The Terraform plan command checks the entered values for correctness. It should not validate them in the provider. Only in this case we can implement validation.
