### ISSUE TITLE
Upgrade CCE clusters with terraform

### ISSUE THREAD

**Issue by otc-fabo** [opentelekomcloud/terraform-provider-opentelekomcloud#782]
It is possible to upgrade existing CCE clusters inside the OTC console. 
If upgrading it manually in the console and rerunning terraform apply, the cluster would be recreated due to different version.
is it possible to implement cce cluster upgrade in the terraform OTC provider?

**Comment by outcatcher** [comment]
Unfortunately, CCE API doesn't provide a method for updating k8s version of the cluster:
https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0240.html
Please create a feature request for this, if you need such functionality.

**Comment by outcatcher** [comment]
Internal issue: https://jira.tsi-dev.otc-service.com/browse/DM-1775

**Comment by lego963** [comment]
Rejected by R&D.
