### ISSUE TITLE
[RDS][Parameter template] change version failes

### ISSUE THREAD

**Issue by sfhl** [opentelekomcloud/terraform-provider-opentelekomcloud#783]
Hi there, if i try to update the version (for example mysql 5.7 -> 5.6) of a rds parameter template, the execution fails.

# Terraform Version
```
Terraform v0.12.29
+ provider.opentelekomcloud v1.22.3
```

# Affected Resource(s)
- opentelekomcloud_rds_parametergroup_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_rds_parametergroup_v3" "rds-param-template-test-mysql" {
  name        = "rds-param-template-test-mysql"
  description = ""

  values = {
    innodb_buffer_pool_size = "268435456"
    wait_timeout            = "5"
  }

  datastore {
    type    = "mysql"
    version = "5.6"
  }
}

```

# Debug Output/Panic Output
https://gist.github.com/sfhl/afb80d0d650b42f2e125761ff2a752f9

# Steps to Reproduce
1. `terraform apply`

# Expected Behavior
Either the version is updates directly, or the old parameter template is deleted and a new one is created.

# Actual Behavior
It is tried to change the version isntantly and this fails.

**Comment by lego963** [comment]
@sfhl according to the documentation we do not have the API to change the version of the configuration
https://docs.otc.t-systems.com/en-us/api/rds/rds_09_0303.html. We can implement recreation.

**Comment by sfhl** [comment]
i guess at least recreation would be great, so there is no error
