### ISSUE TITLE
Idempotency for dns_recordset_v2 and compute_keypair_v2 

### ISSUE THREAD

**Issue by varac** [opentelekomcloud/terraform-provider-opentelekomcloud#785]
# Terraform Version

Terraform v0.14.4

# Affected Resource(s)

* opentelekomcloud_dns_recordset_v2
* opentelekomcloud_compute_keypair_v2 

# Terraform Configuration Files
```hcl
plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"
```

# Debug Output/Panic Output

https://gist.github.com/varac/81634b8e1d620af410a07e6ce26241f7

# Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`
3. `terraform apply`

# Expected Behavior

TF should ignore an already existing keypair, or update it if on changes.

# Actual Behavior

TF apply fails with:

```
Error: Error creating OpenTelekomCloud DNS record set: Bad request with: [POST https://dns.eu-de.otc.t-systems.com/v2/zones/ff80808275f5fb9c0176fd67a14834ff/recordsets], error message: {"code":"DNS.0312","message":"Attribute 'name' conflicts with Record Set 'dev.coyotest.com.' type 'A' in line 'default_view'."}
  on ../../modules/infrastructure/dns/main.tf line 5, in resource "opentelekomcloud_dns_recordset_v2" "loadbalancer":
   5: resource "opentelekomcloud_dns_recordset_v2" "loadbalancer" {
Error: Error creating OpenTelekomCloud DNS record set: Bad request with: [POST https://dns.eu-de.otc.t-systems.com/v2/zones/ff80808275f5fb9c0176fd67a14834ff/recordsets], error message: {"code":"DNS.0312","message":"Attribute 'name' conflicts with Record Set '*.dev.coyotest.com.' type 'A' in line 'default_view'."}
  on ../../modules/infrastructure/dns/main.tf line 14, in resource "opentelekomcloud_dns_recordset_v2" "loadbalancer_wildcard":
  14: resource "opentelekomcloud_dns_recordset_v2" "loadbalancer_wildcard" {
Error: Error creating OpenTelekomCloud keypair: Expected HTTP response code [200] when accessing [POST https://ecs.eu-de.otc.t-systems.com/v2.1/1529f1a1de5d4fe98ac879a8f07e6154/os-keypairs], but got 409 instead
{"conflictingRequest": {"message": "Key pair 'dev-ssh-keypair' already exists.", "code": 409}}
  on ../../modules/infrastructure/ssh/main.tf line 1, in resource "opentelekomcloud_compute_keypair_v2" "default_ssh_keypair":
   1: resource "opentelekomcloud_compute_keypair_v2" "default_ssh_keypair" {
```

# Important Factoids

* terraform-provider-opentelekomcloud v1.22.3

# Etc

The OTC project gets created, the destroyed and recreated. Because dns and ssh keypairs are not project-bound (lets say they are "globally" defined), they are not removed on a tf destroy and therefore pre-existing on the second apply.
The terraform-provider-opentelekomcloud should handle this gracefully.

**Comment by outcatcher** [comment]
@varac 
Have you considered [importing](https://www.terraform.io/docs/import/index.html) existing resources?

**Comment by varac** [comment]
> Have you considered importing existing resources?

No I have not so far, I'm still undecided if this would be the right approach, ot if the `terraform-provider-opentelekomcloud` provider should simply override existing resources (maybe with a configurable flag ?).

By other means, the same happens as well with an existing VPC:

```
TestInfrastructure 2021-02-11T14:05:26Z logger.go:66: Error: Error creating OpenTelekomCloud VPC: Bad request with: [POST https://vpc.eu-de.otc.t-systems.com/v1/32bafdd49a84424ba588821b02b9954a/vpcs], error message: {"code":"VPC.0115","message":"{\"NeutronError\":{\"message\":\"The router name has exist\",\"type\":\"InvalidInput\",\"detail\":\"\"}}"}
```

@outcatcher What's your opinion on this ?

**Comment by outcatcher** [comment]
@varac generally, resources should be managed terraform exclusively. VPC is project-specific, so there should not be such conflicts as in the case of DNS and keypairs.

Can you describe, how are you using the terraform? Why do you need such overriding?

**Comment by varac** [comment]
For some reasons, there are still leftover resources in an OTC project which are not managed by the TF state. The above issue with an existing VPC is such a case. For us it would be ideal if we could use this provider in a way that it would just override existing resources instead of failing, but I don't know if the current state is like it is expected.

**Comment by outcatcher** [comment]
If resources are unmanaged, it's easier to just pass them as variables. If they are "leftover" and you want to manage them, for many resources there is a possibility to import resource instance, e.g. `terraform import opentelekomcloud_vpc_v1.vpc_1 my-vpc-uuid`. Also in some cases, data sources can be used to retrieve an exact resource based on its properties (this is also available for VPC resource).
