### ISSUE TITLE
Document configurable timeout for creation/deletion of resources

### ISSUE THREAD

**Issue by tasansga** [opentelekomcloud/terraform-provider-opentelekomcloud#786]
It happens now and then that opentelekomcloud_cce_node_v3 deletion times out.

Would it be possible to make timeouts configurable for creation and deletion, perhaps like it's done in the Azure terraform provider? -> https://github.com/terraform-providers/terraform-provider-azurerm/issues/171

```
resource "azurerm_resource_group" "test" {
  name     = "example-resources"
  location = "West Europe"
  
  timeouts {
    create = "60m"
    delete = "2h"
  }
}
```

**Comment by outcatcher** [comment]
@tasansga 
Both `opentelekomcloud_cce_cluster_v3` and `opentelekomcloud_cce_node_v3` resources support timeout configuration for create and delete operations (same as in the issue description). Have you tried using them?

For me following example apply fails after two seconds of cluster creation with error
```hcl
resource "opentelekomcloud_vpc_v1" "vpc" {
  cidr = "192.168.0.0/16"
  name = "tf-test"
}

resource "opentelekomcloud_vpc_subnet_v1" "subnet" {
  cidr       = "192.168.0.0/17"
  gateway_ip = "192.168.0.1"
  name       = "tf-test"
  vpc_id     = opentelekomcloud_vpc_v1.vpc.id
}

resource "opentelekomcloud_cce_cluster_v3" "cluster" {
  cluster_type           = "VirtualMachine"
  flavor_id              = "cce.s1.small"
  vpc_id                 = opentelekomcloud_vpc_v1.vpc.id
  subnet_id              = opentelekomcloud_vpc_subnet_v1.subnet.id
  container_network_type = "overlay_l2"
  name                   = "tf-test"

  timeouts {
    create = "2s"
  }
}
```
Result: `Error: error creating OpenTelekomCloud CCE cluster: timeout while waiting for state to become 'Available' (timeout: 2s)`

**Comment by tasansga** [comment]
That's awesome!
I didn't see it on https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cce_cluster_v3 - so it looks like I should just first try it out next time...
Issue solved for me... feel free to close!

**Comment by outcatcher** [comment]
If you're okay with that, I will use this issue for timeout documentation missing for the resource
