### ISSUE TITLE
[DNS] Error: Error fetching OpenTelekomCloud DNS zone tags: Resource not found

### ISSUE THREAD

**Issue by philippeckel** [opentelekomcloud/terraform-provider-opentelekomcloud#793]
# Terraform Version

Terraform v0.14.4
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.22.3

# Affected Resource(s)
opentelekomcloud_dns_zone_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_dns_zone_v2" "public_example_com" {
  name        = "ourdomain.com."
  email       = "public@ourdomain.com"
  description = "An example for public zone"
  ttl         = 300
  type        = "public"

  tags = {
    foo = "bar"
    key = "value"
  }
}
```

# Debug Output/Panic Output

https://gist.github.com/philippeckel/749b98a34b9d26d951e500d36bb3adad

# Steps to Reproduce

1. `terraform apply`

# Expected Behavior
Public DNS zone should be created and `terraform apply` should exit successfully.

# Actual Behavior

```shell
Error: Error fetching OpenTelekomCloud DNS zone tags: Resource not found: [GET https://dns.eu-de.otc.t-systems.com/v2//DNS-public_zone/ff80808275f5fb9c017716e43acd478a/tags], error message: {"message":"API not found","request_id":"7cd2bf939847d346fa7d8821addfaf6a"}
```

# Important Factoids

*The public zone actually is created*, but `terraform apply` does not finish as expected.

***There is no difference if not using tags at all.***

The URL looks suspicious with the double `/`:

`https://dns.eu-de.otc.t-systems.com/v2//DNS-public_zone/ff80808275f5fb9c017716e43acd478a/tags`

# References

**Comment by philippeckel** [comment]
This can be closed, as I found the issue.

`opentelekomcloud_dns_zone_v2` is a global service and therefore one needs to configure the OTC provider with the global project - old term: tenant - name which is `eu-de`.

```hcl
provider "opentelekomcloud" {
  access_key  = var.access_key
  secret_key  = var.secret_key
  domain_name = var.domain_name
  auth_url    = var.auth_url
  tenant_name = "eu-de"
}
```

**Comment by outcatcher** [comment]
@philippeckel It's not working for you with another project set (e.g. `eu-de_test`)?

**Comment by gtema** [comment]
Just for clarification: DNS is not a global service (zones are provisioned in the project context) and tenant_id is an obsolete term, while project_id is since years the correct one.

**Comment by outcatcher** [comment]
DNS service, as most of services, requires `tenant_name` set. Issue for missing validation created: #801.
