### ISSUE TITLE
Restructure resources

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/terraform-provider-opentelekomcloud#797]
Currently, resource layout is done the same way it's done in, e.g. `terraform-provider-openstack`, putting all resources and data sources to the same directory and package.

On the other hand, `terraform-provider-azurerm` has a more structured layout: https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/azurerm/internal/services

I propose to move from the first approach to the second one.

**Comment by outcatcher** [comment]
@anton-sidelnikov @lego963 please provide your feedback for this proposal.

**Comment by lego963** [comment]
@outcatcher this is an interesting idea. Our current state is a heap of files with resources/data sources/imports/tests. We should have something more structured.
