### ISSUE TITLE
Add a new lib of 'golangsdk'

### ISSUE THREAD

**Issue by zengchen1024** [opentelekomcloud/terraform-provider-opentelekomcloud#8]
golangsdk[1] is a lib like gophercloud, which is the go sdk for huawei cloud. This issue want to import it as a lib, which will be more suitable than gophercloud to develop the apps belonging to opentelekom cloud.

### Terraform Version
any(not request fix verison)

### Affected Resource(s)
All resources whose apis are different than the native openstack's should use the golangsdk instead.

### References
[1] https://github.com/huaweicloud/golangsdk

**Comment by niuzhenguo** [comment]
can we close this now?

**Comment by zengchen1024** [comment]
@niuzhenguo yes, thanks for your reminding!
