### ISSUE TITLE
Error: can't find VPC ``: Resource not found

### ISSUE THREAD

**Issue by rbange** [opentelekomcloud/terraform-provider-opentelekomcloud#803]
# Terraform Version
`Terraform v0.14.5`
`opentelekomcloud/opentelekomcloud v1.22.4`

# Affected Resource(s)
Probably:
- `opentelekomcloud_cce_cluster_v3.cce`
- `opentelekomcloud_vpc_v1`

# Terraform Configuration Files
Very basic setup
```
resource "opentelekomcloud_vpc_v1" "anyname" {
  name = "anyname"
 ...
}

resource "opentelekomcloud_vpc_subnet_v1" "anyname" {
  vpc_id        = opentelekomcloud_vpc_v1.anyname.id
  name          = opentelekomcloud_vpc_v1.anyname.name
  ...
}

resource "opentelekomcloud_cce_cluster_v3" "anycce" {
  ...
  vpc_id      = opentelekomcloud_vpc_v1.anyname.id
  subnet_id   = opentelekomcloud_vpc_subnet_v1.anyname.id
  ...
}
```

# Debug Output/Panic Output

`Error: can't find VPC ``: Resource not found: [GET https://vpc.eu-de.otc.t-systems.com/v1//vpcs/], error message: {"message":"API not found","request_id":""}`

# Steps to Reproduce
1. `terraform init`
1. `terraform plan -target opentelekomcloud_cce_cluster_v3.anycce`

# Expected Behavior
Terraform should connect the VPC and the CEE properly as it did in `opentelekomcloud/opentelekomcloud v1.22.3`

# Actual Behavior
VPC name/identifier is not transmitted?

# Important Factoids

# References

This PR introduces the new error message: https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/pull/787

**Comment by outcatcher** [comment]
Thanks for reporting the issue, it will be fixed ASAP
