### ISSUE TITLE
Error creating OpenTelekomCloud VPC: Resource not found

### ISSUE THREAD

**Issue by leitmedium** [opentelekomcloud/terraform-provider-opentelekomcloud#809]
# Terraform Version
Terraform v0.14.5
provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.22.5

# Affected Resource(s)
opentelekomcloud_vpc_v1

# Terraform Configuration Files
```hcl
variable "vpc_name" {
  default = "testvpc1"
}

variable "vpc_cidr" {
  default = "172.16.0.0/16"
}

resource "opentelekomcloud_vpc_v1" "vpc" {
  name = var.vpc_name
  cidr = var.vpc_cidr
}
```

# Debug Output/Panic Output
```
opentelekomcloud_vpc_v1.vpc: Creating...

Error: Error creating OpenTelekomCloud VPC: Resource not found: [POST https://vpc.eu-de.otc.t-systems.com/v1//vpcs], error message: {"message":"API not found","request_id":"8d5d97e7922979d99a632b0642c85bd3"}


  on provider.tf line 17, in resource "opentelekomcloud_vpc_v1" "vpc":
  17: resource "opentelekomcloud_vpc_v1" "vpc" {
```

# Steps to Reproduce
1. `terraform apply`

# Expected Behavior

Terraform should have created a VPC.

# Actual Behavior

Terraform run stops with above message.

# References

This is probably related to #803, but I am using the newer version 1.22.5.

**Comment by outcatcher** [comment]
@leitmedium It seems, you haven't provided `tenant_name` or `tenant_id` for the provider configuration. The error message is missing currently: #801

**Comment by leitmedium** [comment]
@outcatcher That seems to be right, yes! Thanks for explanation. We can close this thicket then for now.

**Comment by outcatcher** [comment]
Sorry for such inconvenience :) The problem will be fixed in the upcoming release.
