### ISSUE TITLE
OTC renaming missleading resource key's

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#83]
```
terraform -v
Terraform v0.11.7
+ provider.opentelekomcloud v1.1.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- opentelekomcloud_elb_loadbalancer
- opentelekomcloud_rds_instance_v1

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
**opentelekomcloud_rds_instance_v1**
**subnetID** is missleading here, since the **vpcID** is needed
Refer to: #80 
```hcl
 nics {
    subnetid = "b65f8d25-c533-47e2-8601-cfaa265a3e3e"
  }
```

```hcl
 nics {
    vpc_id = "${opentelekomcloud_networking_network_v2.vpc.id}"
  }
```

**opentelekomcloud_rds_instance_v1**
**vpcID** is missleading here, since the **router_id** is needed
Refer to: #81 
```hcl
resource "opentelekomcloud_elb_loadbalancer" "load_balancer" {
  name           = "some-elb"
  region         = "eu-de"
  description    = "changeme"
  type           = "External"
  vpc_id         = "${opentelekomcloud_networking_network_v2.vpc.id}"
  admin_state_up = "true"
  bandwidth      = 5
}
```

```hcl
resource "opentelekomcloud_elb_loadbalancer" "load_balancer" {
  name           = "some-elb"
  region         = "eu-de"
  description    = "changeme"
  type           = "External"
  vpc_id         = "${opentelekomcloud_networking_router_v2.router.id}"
  admin_state_up = "true"
  bandwidth      = 5
}
```

**Comment by niuzhenguo** [comment]
@Moep90 Thank you for raising this!
Regarding rds_instance, I checked the [api docs](https://docs.otc.t-systems.com/en-us/api/rds/en-us_topic_0032347785.html#en-us_topic_0032347785__table2179128), it's indeed subnet id but I understand your confusion as router, network, subnet are things within OpenStack API. But VPC and RDS are our owns, for such things we recommend to use vpc/subnet resources when it lands.

**Comment by niuzhenguo** [comment]
And for elb_loadbalancer, vpc id is equal to OpenStack's router id. You should not name a network resource to vpc like opentelekomcloud_networking_network_v2.vpc.id. Seems the name caused the confusion here?

**Comment by Moep90** [comment]
@niuzhenguo In both cases. I find myself misslead with the naming of both key's.
Now I know that the **vpc_id** represents the **router** in Openstack.

I'm not really familiar with OpenStack and this is why I chose to use TF.
From my understanding of Terraform and its providers, its like a wrapper for the API.
Therefore it should (at least in my opinion) named like what it needs as value.

**Comment by niuzhenguo** [comment]
@Moep90 In fact, we support two sets of APIs, one is OpenStack API and the other is OpenTelekom API.
RDS and VPC are not OpenStack resources but Routers, Networks are, so the combined parameters make confusion here. When VPC resource lands, you don't need to create router, network, subnet, router_interface anymore, only one vpc resource will be enough.

**Comment by Moep90** [comment]
> When VPC resource lands, you don't need to create router, network, subnet, router_interface anymore, only one vpc resource will be enough.

Does that land by OTC itself or within the `terraform-provider-opentelekomcloud`?

This issue can be closed in my opinion. As there is nothing more to do till we just wait for VPC to land, right?

**Comment by niuzhenguo** [comment]
@Moep90 OTC already support that with a non OpenStack API, just need to wrap that within opentelekomcloud provider.

**Comment by Moep90** [comment]
@niuzhenguo Feel free to close this or leave it open for the next release.
