### ISSUE TITLE
Add SFS Turbo

### ISSUE THREAD

**Issue by nickgraetsch** [opentelekomcloud/terraform-provider-opentelekomcloud#839]
Hi, could you maybe add the new sfs turbo into the provider?
<img width="956" alt="Screenshot 2021-02-09 at 20 19 12" src="https://user-images.githubusercontent.com/38107399/107415977-3fde8e00-6b14-11eb-8d2f-95125efa2b95.png">

Thank you :)

**Comment by outcatcher** [comment]
Will require SDK changes first.
Milestone will be set after implementation on the SDK side: https://github.com/opentelekomcloud/gophertelekomcloud/issues/96
