### ISSUE TITLE
documentation for dns_zone_v2 datasource missing required field

### ISSUE THREAD

**Issue by Lysholm** [opentelekomcloud/terraform-provider-opentelekomcloud#869]
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/data-sources/dns_zone_v2

`zone_type` is not optional, queries without it always error with: "your query returned no results.Please change your search criteria and try again". The example usage will lead to an error.

**Comment by outcatcher** [comment]
@Lysholm I wasn't able to reproduce it. Following configuration works just fine for me.
```hcl
data "opentelekomcloud_dns_zone_v2" "zone" {
	name = "var.zone_name"
}
```
Can you provide additional info about the used DNS zone? Is it public? Is it owned by the project you're using?

**Comment by outcatcher** [comment]
@Lysholm have you checked my previous comment?

**Comment by Lysholm** [comment]
@outcatcher : Sorry I missed your earlier comment.

Tested again, i seem to have misspelled the public name i tested.
It resolves just fine, but private zones do not. So the type attribute defaults to 'public' but is required for 'private'.

**Comment by outcatcher** [comment]
@Lysholm No problem :slightly_smiling_face: 
Yes, you need to specify it if you use a private zone, as API returns them only when `type=private` is set. Would you suggest changing data source behavior to search both public and private zones? I suppose we can do that.

**Comment by Lysholm** [comment]
@outcatcher: That would be a breaking change, and not a necessary one. Someone expecting a query return one today could find two tomorrow. I would just include a line in the documentation saying that the type attribute is required for private zones.
