### ISSUE TITLE
opentelekomcloud_cce_node_v3 setting max_pods results in permanent rebuild

### ISSUE THREAD

**Issue by david-slr** [opentelekomcloud/terraform-provider-opentelekomcloud#875]
Hi, 

if I change the `max_pods` from an `opentelekomcloud_cce_node_v3` the resource is rebuilding in every run after creation
The state file properties `"max_pods": 0,` do not change.
Is this behaviour expected? I would expect to not recreate the resource every time. 

greetings
david

# Terraform Version
Terraform v0.14.7
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.23.1

# Affected Resource(s)
opentelekomcloud_cce_node_v3

# Terraform Configuration Files

```
cce_compute_nodes = {
  "1" = { "flavor_id" = "s3.large.2", "az" = "eu-de-03", "max_pods" : "50" }
}
```

```
resource "opentelekomcloud_cce_node_v3" "nodes" {
  for_each          = var.cce_compute_nodes
  name              = "${var.environment}-${var.deployment}-${each.key}"
  cluster_id        = opentelekomcloud_cce_cluster_v3.cluster.id
  availability_zone = each.value.az
  flavor_id         = each.value.flavor_id
  key_pair          = "${var.tenant_name}_${var.environment}_${var.deployment}"
  max_pods          = each.value.max_pods
  root_volume {
    size       = 51
    volumetype = "SATA"
  }
  data_volumes {
    size       = 100
    volumetype = "SATA"
  }
  tags = var.custom_tags
  lifecycle {
    #  ignore_changes        = [max_pods]
    create_before_destroy = true
  }
  timeouts {
    create = "30m"
    delete = "30m"
  }
}
```

# Steps to Reproduce
1. `terraform plan`
2. `terraform apply`
3. `terraform plan`

# Expected Behavior
first Plan: 1 to add, 0 to change, 0 to destroy.
second Plan: 0 to add, 0 to change, 0 to destroy.

# Actual Behavior
first Plan: 1 to add, 0 to change, 0 to destroy.
second Plan: 1 to add, 0 to change, 1 to destroy.

**Comment by outcatcher** [comment]
Reason: `extendParam` is missing from node details response:
```json
{
  "kind": "Node",
  "apiVersion": "v3",
  "metadata": {
    "name": "test-node",
    "uid": "3a604112-7816-11eb-bb13-0255ac1017ab",
    "creationTimestamp": "2021-02-26 09:37:22.894237 +0000 UTC",
    "updateTimestamp": "2021-02-26 09:39:52.285347 +0000 UTC",
    "annotations": {
      "kubernetes.io/node-pool.id": "eu-de-03#s2.xlarge.2#EulerOS 2.5"
    }
  },
  "spec": {
    "flavor": "s2.xlarge.2",
    "az": "eu-de-03",
    "os": "EulerOS 2.5",
    "login": {
      "sshKey": "keypair-do-not-delete",
      "userPassword": {}
    },
    "rootVolume": {
      "volumetype": "SATA",
      "size": 40
    },
    "dataVolumes": [
      {
        "volumetype": "SATA",
        "size": 100
      }
    ],
    "publicIP": {
      "eip": {
        "bandwidth": {}
      }
    },
    "nodeNicSpec": {
      "primaryNic": {
        "subnetId": "0f9d5426-ab11-471f-b5a0-d7b413cd2cfa"
      }
    },
    "billingMode": 0
  },
  "status": {
    "phase": "Active",
    "serverId": "941fea1b-ca09-4c51-9e88-99bf368c63e1",
    "privateIP": "192.168.79.185"
  }
}
```

**Comment by outcatcher** [comment]
I will create an internal incident for that. The current issue will be fixed on the provider side.

**Comment by outcatcher** [comment]
Internal incident: https://jira.tsi-dev.otc-service.com/browse/OCS-3419

Reopening: will track internal incident status

**Comment by artem-lifshits** [comment]
Internal incident is fixed.
There was additional issue with CCE nodes: new default tag `CCE-Cluster-ID` was added by backend to the node which leaded to resource change after `terraform apply` or `terraform plan`.
Currently tag is ignored.
