### ISSUE TITLE
CSS Deployment errors (but deploys) / delete errors but does nothing

### ISSUE THREAD

**Issue by DanielHabenicht** [opentelekomcloud/terraform-provider-opentelekomcloud#878]
# Terraform Version
```
Terraform v0.14.7
+ provider registry.terraform.io/opentelekomcloud/opentelekomcloud v1.23.1
```
# Affected Resource(s)
 - opentelekomcloud_css_cluster_v1.css_cluster

# Terraform Configuration Files
```hcl
# env.tfvars
css_vpc_cidr          = "172.16.0.0/24"
css_subnet_cidr       = "172.16.0.0/24"
css_subnet_gateway_ip = "172.16.0.1"
css_node_number       = 1
css_flavor            = "css.medium.8"
css_volume_type       = "COMMON"
css_volume_size       = 40
css_availability_zone = "eu-de-01"

# main.tf
resource "opentelekomcloud_vpc_v1" "css_vpc" {
  name = "indicarus-css-vpc"
  cidr = var.css_vpc_cidr

  tags = {
    terraform = "true"
  }
}

resource "opentelekomcloud_vpc_subnet_v1" "css_subnet" {
  name       = "indicarus-css-subnet"
  cidr       = var.css_subnet_cidr
  vpc_id     = opentelekomcloud_vpc_v1.css_vpc.id

  gateway_ip = var.css_subnet_gateway_ip

  tags = {
    terraform = "true"
  }
}

resource "opentelekomcloud_networking_secgroup_v2" "css_sg" {
  name        = "indicarus-css-sg"
  description = "Security group for a CSS cluster."
}

resource "opentelekomcloud_networking_secgroup_rule_v2" "css_sg_rule" {
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
  port_range_min    = 9200
  port_range_max    = 9200
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = opentelekomcloud_networking_secgroup_v2.css_sg.id
}

resource "opentelekomcloud_css_cluster_v1" "css_cluster" {
  name            = "indicarus-css-cluster"
  expect_node_num = var.css_node_number
  node_config {
    flavor = var.css_flavor
    network_info {
      security_group_id = opentelekomcloud_networking_secgroup_v2.css_sg.id
      network_id        = opentelekomcloud_vpc_subnet_v1.css_subnet.id
      vpc_id            = opentelekomcloud_vpc_v1.css_vpc.id
    }
    volume {
      volume_type = var.css_volume_type
      size        = var.css_volume_size
    }

    availability_zone = var.css_availability_zone
  }
}
```

# Debug Output/Panic Output
Apply:
```
opentelekomcloud_networking_secgroup_v2.css_sg: Creating...
opentelekomcloud_vpc_v1.css_vpc: Creating...
opentelekomcloud_networking_secgroup_v2.css_sg: Creation complete after 1s [id=e8e57cff-0a78-4796-9970-9c3e0c657bfd]
opentelekomcloud_networking_secgroup_rule_v2.css_sg_rule: Creating...
opentelekomcloud_networking_secgroup_rule_v2.css_sg_rule: Creation complete after 0s [id=4f5fb1a5-7023-40d1-975c-308255791980]
opentelekomcloud_vpc_v1.css_vpc: Creation complete after 8s [id=2c64b030-24dd-4ac2-9047-75111b0bdde9]
opentelekomcloud_vpc_subnet_v1.css_subnet: Creating...
opentelekomcloud_vpc_subnet_v1.css_subnet: Creation complete after 9s [id=4a4d7100-a9cb-4139-9aac-3d43032d5214]
opentelekomcloud_css_cluster_v1.css_cluster: Creating...
opentelekomcloud_css_cluster_v1.css_cluster: Still creating... [10s elapsed]
opentelekomcloud_css_cluster_v1.css_cluster: Still creating... [14m20s elapsed]
Error: Error reading Cluster:node_config, err: Error reading Cluster:volume, err: Error reading Cluster:encryption_key, err: navigate value with index(read.cmkId): 'cmkId' may not exist

  on main.tf line 37, in resource "opentelekomcloud_css_cluster_v1" "css_cluster":
  37: resource "opentelekomcloud_css_cluster_v1" "css_cluster" {

```
Delete: 
```
opentelekomcloud_css_cluster_v1.css_cluster: Refreshing state... [id=4e5f0a46-2b4c-45fe-8a21-873d9ac23dfd]

Error: Error reading Cluster:node_config, err: Error reading Cluster:volume, err: Error reading Cluster:encryption_key, err: navigate value with index(read.cmkId): 'cmkId' may not exist
```

# Steps to Reproduce

```
terraform init
terraform plan -out=tfplan
terraform apply tfplan
```

# Expected Behavior
No Errors

# Actual Behavior
There is an error and the further execution is stopped. 

# Important Factoids
Not that I know of.

# References
Nope

**Comment by outcatcher** [comment]
Due to spec, `cmkId` should be a part of the response. Fix to be done in the provider. I will later create an internal incident for that issue.

**Comment by outcatcher** [comment]
The issue won't happen in CSS cluster operations were done in SDK, so #880

**Comment by DanielHabenicht** [comment]
Thanks for fixing, when will the next version be available? 
> Nevermind, I was mislead by the Milestone, but the new version was released an hour ago.

BTW: you might want to have a look at [automatic versioning](https://github.com/semantic-release/semantic-release), removing the need to make a release manually.

**Comment by lego963** [comment]
@DanielHabenicht You should have new version! We've already published new release [v1.23.2](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/releases/tag/v1.23.2)

**Comment by outcatcher** [comment]
@DanielHabenicht We have the release automation level most suitable for us right now :slightly_smiling_face:. We want to control what actually is put in the changelog (and how is it formatted) and when a release is done. It's easier to control release via tags as it is done now than use any approach mentioned in [semantic-release#how-does-it-work](https://github.com/semantic-release/semantic-release#how-does-it-work). Introducing `semantic-release` to the project seems to increase work done for release rather than decrease it.

**Comment by DanielHabenicht** [comment]
Ok, just do what works best for you :) 
With semantic release you control what is written in the Changelog via the commit format, e.g. for the fix you have done for this issue you would have written in the PR title `fix(css): set cmkId to empty if it is missing` and the body of the PR would have been automatically attached to the changelog upon release - thats all. 

The delete is still failing but with another error: 
```
opentelekomcloud_networking_secgroup_rule_v2.css_sg_rule: Destroying... [id=f10933a9-61b8-46e1-9d3f-547bb6868721]
opentelekomcloud_css_cluster_v1.css_cluster: Destroying... [id=97cd557f-0045-4de1-9cf6-8de1485079e6]
opentelekomcloud_css_cluster_v1.css_cluster: Destruction complete after 6s
opentelekomcloud_vpc_subnet_v1.css_subnet: Destroying... [id=80a0430f-86d6-4e11-9464-74cf5c2fa63a]
opentelekomcloud_networking_secgroup_rule_v2.css_sg_rule: Destruction complete after 9s
opentelekomcloud_networking_secgroup_v2.css_sg: Destroying... [id=e10bf6de-e17a-4239-8ba2-0dc1a0d9591f]
opentelekomcloud_networking_secgroup_v2.css_sg: Still destroying... [id=e10bf6de-e17a-4239-8ba2-0dc1a0d9591f, 10s elapsed]
opentelekomcloud_networking_secgroup_v2.css_sg: Still destroying... [id=e10bf6de-e17a-4239-8ba2-0dc1a0d9591f, 20s elapsed]
opentelekomcloud_networking_secgroup_v2.css_sg: Still destroying... [id=e10bf6de-e17a-4239-8ba2-0dc1a0d9591f, 30s elapsed]
opentelekomcloud_networking_secgroup_v2.css_sg: Still destroying... [id=e10bf6de-e17a-4239-8ba2-0dc1a0d9591f, 40s elapsed]
opentelekomcloud_networking_secgroup_v2.css_sg: Still destroying... [id=e10bf6de-e17a-4239-8ba2-0dc1a0d9591f, 50s elapsed]
opentelekomcloud_networking_secgroup_v2.css_sg: Still destroying... [id=e10bf6de-e17a-4239-8ba2-0dc1a0d9591f, 1m0s elapsed]
opentelekomcloud_networking_secgroup_v2.css_sg: Still destroying... [id=e10bf6de-e17a-4239-8ba2-0dc1a0d9591f, 1m10s elapsed]
opentelekomcloud_networking_secgroup_v2.css_sg: Still destroying... [id=e10bf6de-e17a-4239-8ba2-0dc1a0d9591f, 1m20s elapsed]
opentelekomcloud_networking_secgroup_v2.css_sg: Destruction complete after 1m30s

Error: Error deleting OpenTelekomCloud Subnet: Expected HTTP response code [202 204] when accessing [DELETE https://vpc.eu-de.otc.t-systems.com/v1/4c0825626d2c47e38c9e4b782e0f5a53/vpcs/9a64f12a-cf00-43af-a718-ace231a0a618/subnets/80a0430f-86d6-4e11-9464-74cf5c2fa63a], but got 409 instead
{"code":"VPC.0209","message":"subnet is still used ,such as computer,LB."}
```

I think that's because OTC is reporting the CSS Cluster as deleted, but it is still in the subnet when reporting the finished deletion. 
I tried it out manually before and got the same error.

**Comment by outcatcher** [comment]
@DanielHabenicht it seems, terraform fails to establish dependency between CSS and VPC. Can you please try to add `depends_on = [opentelekomcloud_vpc_subnet_v1.css_subnet]` to the `opentelekomcloud_css_cluster_v1` resource configuration

**Comment by outcatcher** [comment]
As for automatic changelog: terraform providers have changes split to sections `ENHANCEMENTS`, `BUG FIXES`, etc and have changes in different formats for new resources and changes in the existing ones. Also, PR commit message is configured by the `zuul` CI during the `gate` pipeline (we avoid manual PR merging) in our case and it differs for PRs with a single commit and multiple commits. I'm pretty sure it is possible to tune automatic release the way we need it (and maybe someday we will use it), but right now current approach seems to suit us better. And it's easier to control changelog text when it's modified in PR than verify that the commit message has the correct format and text.

**Comment by DanielHabenicht** [comment]
> As for automatic changelog: terraform providers have changes split to sections `ENHANCEMENTS`, `BUG FIXES`, etc and have changes in different formats for new resources and changes in the existing ones. Also, PR commit message is configured by the `zuul` CI during the `gate` pipeline (we avoid manual PR merging) in our case and it differs for PRs with a single commit and multiple commits. I'm pretty sure it is possible to tune automatic release the way we need it (and maybe someday we will use it), but right now current approach seems to suit us better. And it's easier to control changelog text when it's modified in PR than verify that the commit message has the correct format and text.

Nice, okay. I didn't know that terraform already comes with versioning build in - quite new here. For sure - automated processes come with their own problems like do one mistake and take ages to circumvent.

**Comment by DanielHabenicht** [comment]
> @DanielHabenicht it seems, terraform fails to establish dependency between CSS and VPC. Can you please try to add `depends_on = [opentelekomcloud_vpc_subnet_v1.css_subnet]` to the `opentelekomcloud_css_cluster_v1` resource configuration

trying it out now, by the way, how do you get or set the credentials for the cluster via terraform?

**Comment by DanielHabenicht** [comment]
> @DanielHabenicht it seems, terraform fails to establish dependency between CSS and VPC. Can you please try to add `depends_on = [opentelekomcloud_vpc_subnet_v1.css_subnet]` to the `opentelekomcloud_css_cluster_v1` resource configuration

Not working, but as I said I think it is because OTC is misbehaving not terraform. 
1. Terraform deletes the cluster first and gets almost immediate confirmation of it deletion. 
    ```
    opentelekomcloud_css_cluster_v1.css_cluster: Destroying... [id=2a8a3884-8749-45d2-b3cb-5945f59567b9]
    opentelekomcloud_css_cluster_v1.css_cluster: Destruction complete after 6s
    ```
2.  But the Cluster is not really deleted yet, it is still attached to the subnet. 

If you do the same manually (1) delete the cluster via UI and then (2) trying to delete the subnet you get the same error.

**Comment by outcatcher** [comment]
>Not working, but as I said I think it is because OTC is misbehaving not terraform.

**Comment by outcatcher** [comment]
>by the way, how do you get or set the credentials for the cluster via terraform?

As far as I can see, there is no `authorityEnable` and `adminPwd` support currently (though those fields are described in the doc). Can you please create a new issue for missing cluster credentials support?

**Comment by DanielHabenicht** [comment]
> > by the way, how do you get or set the credentials for the cluster via terraform?
> 
> As far as I can see, there is no `authorityEnable` and `adminPwd` support currently (though those fields are described in the doc). Can you please create a new issue for missing cluster credentials support?

Sure, here you go #889, can you link to the documentation you referred. I could not find the options.

**Comment by DanielHabenicht** [comment]
> The issue won't happen in CSS cluster operations were done in SDK, so #880

@outcatcher is CCE resource not using the SDK too? Because I get the same error again (but this time with CCE). 


```bash
Error: error deleting opentelekomcloud CCE Cluster: Action Forbidden
Error: Error deleting OpenTelekomCloud Subnet: Expected HTTP response code [202 204] when accessing [DELETE https://vpc.eu-de.otc.t-systems.com/v1/4c0825626d2c47e38c9e4b782e0f5a53/vpcs/aa97d391-222e-4672-8133-8b0068816442/subnets/88fe4472-76ef-41fd-8f46-e873364f17b2], but got 409 instead
{"code":"VPC.0209","message":"subnet is still used ,such as computer,LB."}
Cleaning up file based variables
00:01
ERROR: Job failed: exit code 1
```

**Comment by outcatcher** [comment]
@DanielHabenicht But it does :) please create an issue for that problem including terraform configuration. 
It seems quite strange because `error deleting opentelekomcloud CCE Cluster` should stop later processing, so VPC deletion should not be triggered at all.

**Comment by DanielHabenicht** [comment]
Seems like the error was a bad deployment before. (also it seems like it was still with the CSS Cluster)
I will make a new issue if it pops up again.

**Comment by DanielHabenicht** [comment]
Seems like it still is an issue ive opened an issue here #975
