### ISSUE TITLE
[keypair_v2] Destroy and create changed ssh key

### ISSUE THREAD

**Issue by m3bg** [opentelekomcloud/terraform-provider-opentelekomcloud#885]
# Terraform Version
Terraform v0.13.5
+ provider registry.terraform.io/terraform-providers/opentelekomcloud v1.23.1

# Affected Resource(s)
opentelekomcloud_compute_keypair_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_compute_keypair_v2" "dev_hitnet-keypair" {
  name       = "dev_hitnet-keypair"
  public_key = file("key_dev_hitnet.pub")
}
```

# Debug Output/Panic Output
```
Error: key dev_hitnet-keypair already exist with different public key

on main.tf line 22, in resource "opentelekomcloud_compute_keypair_v2" "dev_hitnet-keypair":
22: resource "opentelekomcloud_compute_keypair_v2" "dev_hitnet-keypair" {
```
# Steps to Reproduce
1. `terraform apply`

# Expected Behavior
Destroy and create new keypair resource
# Actual Behavior
Terraform fails with the error messsage above.

**Comment by outcatcher** [comment]
@m3bg Please check if the solution provided in #887 fits your needs (see the `Usage` section).

**Comment by m3bg** [comment]
@outcatcher to my mind this is not the solution. I like to let terraform change the key automatically. As workaround i delete the key with terraform destroy -target and let terraform create a new one in the next run.
If the effort for change is to mutch it's ok. This would be only a "nice to have" feature.
Rgds
Marcel

**Comment by outcatcher** [comment]
@m3bg 
The problem is ― if there was no resource in the state, it's impossible to tell terraform to delete the resource.
Though if it **is** existing in the state, but the public key differs from the key retrieved from API, `public_key` will be considered changed and the key pair will be recreated. An example of this case can be importing keypair or using key pair created with the Terraform and then re-created with other means (e.g. removed in _console_ and added back).

**Comment by outcatcher** [comment]
Still, showing the error was a bad solution and it is changed in #887 :slightly_smiling_face:

**Comment by m3bg** [comment]
@outcatcher i thought the key was in the state, i verify if it was my bad.

**Comment by m3bg** [comment]
Verifyed, the error message happends when the key is tracked in the state file and the pub key changes.

**Comment by outcatcher** [comment]
@m3bg Please check the setup you've used with the released version (`v1.23.2`)

**Comment by outcatcher** [comment]
I assume this is no more reproduced

**Comment by m3bg** [comment]
Sorry for the late respond. It is fixed.

**Comment by outcatcher** [comment]
No problem, we can reopen it anytime if needed :slightly_smiling_face:
