### ISSUE TITLE
Provide Modules for common use cases

### ISSUE THREAD

**Issue by DanielHabenicht** [opentelekomcloud/terraform-provider-opentelekomcloud#891]
For example AWS provides modules for eks (and everything that needs to be done to create it, including vpc's etc.) 
![image](https://user-images.githubusercontent.com/13590797/110104987-1e399500-7da8-11eb-81e8-9803ab779852.png)

It would be great if OTC would provide the same functionality, e.g. for CCE or CSS or a single VM deployment.

**Comment by outcatcher** [comment]
Currently in progress at https://github.com/terraform-opentelekomcloud-modules
