### ISSUE TITLE
Make examples more visible and only link to one documentation site

### ISSUE THREAD

**Issue by DanielHabenicht** [opentelekomcloud/terraform-provider-opentelekomcloud#892]
Currently the basic examples are tugged away in the [examples/basic-example/modules](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/tree/devel/examples/basic-examples/modules) folder and won't be found if you are using the documentation or if you just briefly look into the `examples` folder. 

I think they should be linked in documentation or made visible via the terraform website ([example](https://registry.terraform.io/modules/terraform-aws-modules/vpc/aws/latest)) to make finding them easier. 
![image](https://user-images.githubusercontent.com/13590797/110107865-be44ed80-7dab-11eb-9e94-1f32cb47b205.png)

Furthermore the [Readme](https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/blob/devel/README.md) doesn't link to the [documentation](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs)

Maybe I can provide a restructured Readme and you can decide if suits you. (but that's not really part of this issue)

**Comment by lego963** [comment]
Fixed in #894
