### ISSUE TITLE
Backport support for clouds.yaml

### ISSUE THREAD

**Issue by mcanevet** [opentelekomcloud/terraform-provider-opentelekomcloud#90]
Would it be possible to backport this patch : https://github.com/terraform-providers/terraform-provider-openstack/commit/ab4031cd68db790d845f1bc990675780a9767a32?

**Comment by niuzhenguo** [comment]
Please see reply here https://github.com/huawei-clouds/terraform-provider-huaweicloud/issues/35

**Comment by niuzhenguo** [comment]
closing this, please feel free to reopen if there are still questions here.
