### ISSUE TITLE
opentelekomcloud_ecs_instance_v2 - SecurityGroup name will not accepted

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#912]
Hi,

we want to adress this issue also in v2 as in:
https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/904

For v2 using names will lead to useless updates of server each time apply is running.
All v2 API is expecting to be used with security group names (though setting ID is working for both update and create operations), even security group structure in documentation describes this as "security group name or UUID":
https://docs.otc.t-systems.com/en-us/api/ecs/en-us_topic_0068473331.html#EN-US_TOPIC_0068473331__en-us_topic_0057972661_table16920677105453

The documentation and code needs to be updated.

E.g. following configuration with security group name creates the server successfully:
```hcl
resource "opentelekomcloud_networking_secgroup_v2" "sg" {
name = "sg-1"
}

resource "opentelekomcloud_vpc_v1" "vpc" {
cidr = "192.168.0.0/16"
name = "vpc-1"
}

resource "opentelekomcloud_vpc_subnet_v1" "sn" {
cidr = "192.168.0.0/24"
gateway_ip = "192.168.0.1"
name = "sn-1"
vpc_id = opentelekomcloud_vpc_v1.vpc.id
}

resource "opentelekomcloud_compute_instance_v2" "server" {
name = "server-1"

flavor_name = "Standard_Debian_10_latest"
image_name = "s2.large.2"

network {
uuid = opentelekomcloud_vpc_subnet_v1.sn.id
}
```
security_groups = [opentelekomcloud_networking_secgroup_v2.sg.name]
}

**Comment by lego963** [comment]
@CHS-OTC SG names only work if the names are unique. This is the current behavior. IDs always work, but they break backward compatibility. We think that changing the behavior on IDs is not worth it.

**Comment by lego963** [comment]
@CHS-OTC Current behavior is mostly due to how Nova API behaves (accepting both IDs and Names, but responding only with Names). We have added the note about that. As it's openstack resource we will follow openstack provider behaviour. OpenStack provider has the same issue: [#1173](https://github.com/terraform-provider-openstack/terraform-provider-openstack/issues/1173)
