### ISSUE TITLE
Documentation vor values in opentelekomcloud_cce_addon_v3

### ISSUE THREAD

**Issue by jendrikjoe** [opentelekomcloud/terraform-provider-opentelekomcloud#917]
I am currently trying to install the cluster autoscaler via the opentelekomcloud_cce_addon_v3 resource, but I cannot find any docs on what to set the values basic and values custom to.
It would be amazing, if a link to the configuration values or the options themselves could be listed. The only option I see currently is to install the autoscaler via the ui, read the values, add them to terraform, destroy it in the ui and then do terraform apply.

**Comment by outcatcher** [comment]
Unfortunately, it's not described in the API documentation either. There is an [API call](https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0321.html) for retrieving the addon template list, but I'm not sure how can this help. It seems exact configuration values of the addon can depend on the addon version.

Maybe we can create a data source for getting CCE addons. Or we can create an internal issue for missing addon parameters description in the doc.

**Comment by jendrikjoe** [comment]
Thanks for the quick feedback @outcatcher.
I personally would prefer having the parameters to be documented. When managing multiple clusters it is always easier to do everything as code. I can see how it can be complicated to keep the add-on parameters up-to-date in the description though.

**Comment by outcatcher** [comment]
@jendrikjoe I will create an internal issue for that in this case. Also, I suppose we can add documentation on the provider side based on latest addon templates.

**Comment by jendrikjoe** [comment]
Perfect, thanks 👍 I will try to get reading the API running on my side. If so, I will happily contribute the docs 😉

**Comment by outcatcher** [comment]
You're welcome to contribute, it would be a huge help to us :slightly_smiling_face:

**Comment by jendrikjoe** [comment]
A heads-up for everyone, stumbling over this. The linked api is currently not functional. As a workaround one can use https://<cluster_id>.cce.eu-de.otc.t-systems.com/api/v3/addontemplates, as long as one has a cluster up and running 😉

**Comment by jendrikjoe** [comment]
Thanks for the quick fix 🎉 👏
