### ISSUE TITLE
ELB monitor: field domain is missing

### ISSUE THREAD

**Issue by tsdicloud** [opentelekomcloud/terraform-provider-opentelekomcloud#920]
# Terraform Version

Terraform v0.14.8
opentelekomcloud v1.23.2

# Affected Resource(s)

opentelekomcloud_lb_monitor_v2

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_lb_monitor_v2" "lb_node_health_check" {
  name           = "${var.prefix}-node-health"
  pool_id        = opentelekomcloud_lb_pool_v2.lb_node_pool.id
  domain         = var.health_domain
  type           = "HTTP"
  delay          = 15
  timeout        = 10
  url_path       = "/status.php"
  max_retries    = 10
  expected_codes = "200,202"  # TODO: review NextCloud health check endpoint and protection 
}
```

# Debug Output/Panic Output

````
Error: Unsupported argument

  on ../modules/otc_node/otc_node.tf line 76, in resource "opentelekomcloud_lb_monitor_v2" "lb_node_health_check":
  76:   domain         = var.health_domain

An argument named "domain" is not expected here.
````

# Expected behavior
Automation worked with an older version of the provider.
Field is important for proper health checking if internet domain is registered or SNI is used.

# References

https://docs.otc.t-systems.com/api/elb/elb_zq_jk_0001.html
Field "domain_name"

**Comment by outcatcher** [comment]
@tsdicloud Are you sure it worked before? I don't see any `domain` field in any git revision.
