### ISSUE TITLE
[SFS] access_to multiple VPCs

### ISSUE THREAD

**Issue by Nemental** [opentelekomcloud/terraform-provider-opentelekomcloud#930]
**Resource**
opentelekomcloud_sfs_file_system_v2

**Idea**
Possibility to define and authorize several VPCs and not just add them. Once you've added a VPC you can't "manage" or remove it.

**Comment by lego963** [comment]
@Nemental hm, you should have the possibility to change/remove VPC. I will try to investigate

**Comment by lego963** [comment]
@Nemental can you paste your tf config? I can't reproduce issues with update. Please :)

**Comment by outcatcher** [comment]
As per internal discussion, a single VPC usage to remain as it's now (if the problem won't be reproducible). For assigning more VPCs new resource will be created: `opentelekomcloud_sfs_share_access_rule_v2`

**Comment by Nemental** [comment]
Perfect, that's what I needed :)
There is no bug or something, I just want to manage multiple VPC access rules for SFS.
