### ISSUE TITLE
CCE worker nodes creating with fixed IPs

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#932]
When creating a CCE worker node, it is not possible to set a fixed private IP address with terraform.
We checked it, it is possible in the OTC Console and via API (RestAPI).
It is also not documented in the OTC Helpcenter.
This works with API:
```
...
"nodeNicSpec": {
"primaryNic": {
"subnetId": "982a17dc-9343-4a04-b812-b80db19b56a5",
"fixedIps": ["172.16.10.4"]
}
...
```

When trying it with terraform, following errormessage occurs:
![image](https://user-images.githubusercontent.com/79697776/112288924-20e42780-8c8e-11eb-8318-42004b72027b.png)

**Comment by outcatcher** [comment]
@CHS-OTC is there an internal incident for this field missing in the doc?

**Comment by CHS-OTC** [comment]
Hi Anton,
there is only the SM9 ticket for this. We have updated it to fix the docu and routed it to Comp. squad. Maybe they will create the internal incident.
