### ISSUE TITLE
[RDSv3] Adding `param_group_id` to RDS instance does not seem to work

### ISSUE THREAD

**Issue by philippeckel** [opentelekomcloud/terraform-provider-opentelekomcloud#934]
# Terraform Version

# Affected Resource(s)
- opentelekomcloud_rds_instance_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_rds_instance_v3" "instance" {

  name              = var.rds_instance_name
  availability_zone = ["eu-de-02", "eu-de-01"]

  db {
    password = random_password.rds_root_password.result
    type     = "PostgreSQL"
    version  = var.rds_postgres_version
    port     = var.rds_postgres_port
  }
  security_group_id   = opentelekomcloud_networking_secgroup_v2.postgres.id
  subnet_id           = var.subnet_id
  vpc_id              = var.vpc_id
  flavor              = var.rds_flavor
  ha_replication_mode = "async"

  volume {
    type               = var.rds_volume_type
    size               = var.rds_disk_size
    disk_encryption_id = var.kms_key_rds_id
  }

  backup_strategy {
    start_time = "22:00-23:00"
    keep_days  = 14
  }

  param_group_id = opentelekomcloud_rds_parametergroup_v3.pg_1.id
}
```
# Steps to Reproduce

1. `terraform apply`

# Expected Behavior
The parameter group is added to the RDS instance properly.

# Actual Behavior
The parameter group is not added to the RDS instance via Terraform, but using the console one can apply them manually to the instance

# Important Factoids
The naming is misleading in general :-(

# References
https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/issues/445

This was apparently discussed earlier, but the outcome does not seem clear.

Is assigning the parameter group to an RDS instance working for anyone using Terraform?

**Comment by outcatcher** [comment]
@philippeckel
I'm checking this issue now. I can see that parameters from the template not applied to the instance, but haven't still checked whenever this is a provider or API problem.

Generally, the configuration template (`opentelekomcloud_rds_parametergroup_v3`) workflow seems quite broken for me :) I've created #939 for configuring instances without the template (not as a replacement, but as an addition). I suppose you can be interested in that issue too.

**Comment by outcatcher** [comment]
When tested with `max_connections` config parameter, the original issue reproduces for both console and API.
Internal incident created: https://jira.tsi-dev.otc-service.com/browse/XAAS-7220

**Comment by outcatcher** [comment]
@philippeckel 

Per response in the internal ticket, this is a "feature":

_Parameters `max_connections` together with `shared_buffers` parameters are related to the instance physical memory. Improperly setting them will make the PostgreSQL instance unable to startup. To avoid that from happening immediately after RDS's creation, RDS has a logic to reset the parameter of `shared_buffers` and `max_connections` according to the physical memory size. They can be changed in the instance parameters after the creation is finished._

We still need to make a decision what can we do on the provider side for such unexpected behavior.

**Comment by outcatcher** [comment]
To avoid failing RDS creation, the following values are set by default instead of using values from the template:

- `back_log`
- `innodb_io_capacity_max`
- `max_connections`
- `innodb_io_capacity`
- `innodb_buffer_pool_size`
- `innodb_buffer_pool_instances`

Proposed workaround: in the provider re-apply template after the creation and restart RDS instance
