### ISSUE TITLE
resource_opentelekomcloud_rds_instance_v3. No obvious way to enable TLS/SSL for DB access

### ISSUE THREAD

**Issue by tsdicloud** [opentelekomcloud/terraform-provider-opentelekomcloud#936]
# Terraform Version

Terraform v0.14.5

# Affected Resource(s)

resource_opentelekomcloud_rds_instance_v3

# Steps to Reproduce

![image](https://user-images.githubusercontent.com/31852409/112341488-c06edd80-8cc1-11eb-927f-6d0e4fa35ec8.png)

# Expected Behavior

There is a field like "enable_tls" in the provider. 

# Actual Behavior

- There is no obvious field to enable the feature.
- There is also no obvious field to change with resource_opentelekomcloud_rds_parametergroup_v3`
- There is even no hint in the API specification, e.g. https://docs.otc.t-systems.com/api/rds/rds_01_0002.html

**Comment by philippeckel** [comment]
@tsdicloud I think this is a good and probably intended practice to set this as default ...

**Comment by tsdicloud** [comment]
Yes it is if it would be this way 
But my picture shows the NEEDED configuration. Default is "SSL=OFF" - which is also good to get something initially to run.
Let´s find the switch in API, may involve Huawei.

**Comment by outcatcher** [comment]
@tsdicloud 
>There is even no hint in the API specification, e.g. https://docs.otc.t-systems.com/api/rds/rds_01_0002.html

Is there an internal issue for that? It seems API doesn't support this feature.

**Comment by outcatcher** [comment]
It seems this can be configured in the configuration template (at least, it is returned in [get configuration by instance](https://docs.otc.t-systems.com/api/rds/rds_09_0306.html) request:
```json
          "configuration_parameters": [
            ...
            {
              "name": "ssl",
              "value": "on",
              "restart_required": true,
              "readonly": true,
              "value_range": "on|off",
              "type": "boolean",
              "description": "Enables SSL connections."
            },
            {
              "name": "ssl_cert_file",
              "value": "/CA/server.pem",
              "restart_required": true,
              "readonly": true,
              "value_range": "",
              "type": "string",
              "description": "Location of the SSL server certificate file."
            },
            {
              "name": "ssl_ciphers",
              "value": "ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH",
              "restart_required": true,
              "readonly": true,
              "value_range": "",
              "type": "string",
              "description": "Specifies a list of SSL cipher suites that are allowed to be used on secure connections."
            },
            {
              "name": "ssl_key_file",
              "value": "/CA/server.key",
              "restart_required": true,
              "readonly": true,
              "value_range": "",
              "type": "string",
              "description": "Location of the SSL server private key file."
            },
            ...
```

**Comment by outcatcher** [comment]
We will add the SSL usage description to the doc after checking how this works.
Maybe additional resource change will be required for certificate download.

**Comment by tsdicloud** [comment]
Glad you found out 
I queried the coponfiguration parameters of MySQL via user interface and there are no ssl switches as far as I can see. Maybe they skipped the parameters because they built switches for it ... strange.

As far as I can see,, the cetificate xontains only the CA root und thus should be universal

**Comment by lego963** [comment]
Internal incident: https://jira.tsi-dev.otc-service.com/browse/XAAS-7471

**Comment by lego963** [comment]
UPD: For `PostgreSQL` we don't have SSL **switch**, but we have SSL configuration in `RDSv3 Configuration` templates. For `MySQL` we have **switch** (RDSv3 config lack SSL config params). For `MS SQL` we don't have **switch** and RDSv3 Configuration template for MS SQL lack SSL config params.

**Comment by lego963** [comment]
UPD: Demand Request: https://jira.tsi-dev.otc-service.com/browse/DM-2465

**Comment by artem-lifshits** [comment]
Hello @tsdicloud MySql SSL can be configured now, please check.
