### ISSUE TITLE
[CSS] How to set config parameters 

### ISSUE THREAD

**Issue by DanielHabenicht** [opentelekomcloud/terraform-provider-opentelekomcloud#937]
# Description of the new resource/data-source
Regarding:
 - opentelekomcloud_css_cluster_v1.css_cluster

Currenty there is no way to set config parameters via terraform. As you could via the UI: 

e.g. `http.cors.allow-credentials=true`

It would be great if all of those parameters (and custom ones) could be set via terraform.

**Comment by outcatcher** [comment]
I can't find it in the documentation of the API. I will create an internal issue regarding this case.

**Comment by outcatcher** [comment]
Internal incident: https://jira.tsi-dev.otc-service.com/browse/OTCBIGDAI-937

UPD: closed in favor of internal demand

**Comment by DanielHabenicht** [comment]
any updates?

**Comment by outcatcher** [comment]
The response was: "there is no such API currently".
It's stated that such API should be added, but there are yet no details about when it will be implemented.

**Comment by outcatcher** [comment]
Internal demand created: https://jira.tsi-dev.otc-service.com/browse/DM-2507

**Comment by DanielHabenicht** [comment]
any updates on this, if not I will have to search for a workaround :/

My Use case is that I need to configure Authentication via a proxy: https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/proxy/

By the way this also requires to set the elasticsearch `config.yml`, but it seems like this is off limits even in the UI: 
![image](https://user-images.githubusercontent.com/13590797/123692760-80d30700-d857-11eb-9099-6c105560604e.png)

**Comment by outcatcher** [comment]
Currently, there is no update on that issue, sorry.

**Comment by lego963** [comment]
Rejected by R&D.
R&D suggest to use console to modify parameter.

**Comment by k11h-de** [comment]
This is quite disappointing. Is there any chance to bring this up again?

Cheers Karsten
