### ISSUE TITLE
[SDRS] protected instance config missing?

### ISSUE THREAD

**Issue by sfhl** [opentelekomcloud/terraform-provider-opentelekomcloud#942]
Hi there,
sorry if i am simply blind, but i can't find the possibility to configure a protected instance to be protected by an sdrs protection group. How may one protect an instance in this way?

Thanks in advance!

# Terraform Version
```
Terraform v0.12.29
+ provider.local v2.0.0
+ provider.opentelekomcloud v1.21.2
+ provider.template v2.2.0
```

# Affected Resource(s)
- opentelekomcloud_sdrs_protectiongroup_v1

**Comment by outcatcher** [comment]
It seems, `opentelekomcloud_sdrs_instance_v1` (or `opentelekomcloud_sdrs_protected_instance_v1`) resource is required for that.
