### ISSUE TITLE
Add security group parameter to CCE cluster resource

### ISSUE THREAD

**Issue by pbckr** [opentelekomcloud/terraform-provider-opentelekomcloud#948]
According to the OTC API documentation it should be possible to set a security group when creating a CCE cluster. Unfortunately the security group parameter is not existing fo the OTC Terraform Provider's CCE cluster resource.

![image](https://user-images.githubusercontent.com/52598729/113188976-faf4ef00-925a-11eb-8359-50215f32266f.png)

**Comment by lego963** [comment]
@pbckr it can't be possible to set custom `security_group`. You pasted the screenshot from CCE create **response**.

**Comment by outcatcher** [comment]
For the note: CCE cluster creation automatically creates two corresponding security groups.
