### ISSUE TITLE
[S3] EncryptionConfiguration for buckets

### ISSUE THREAD

**Issue by tsdicloud** [opentelekomcloud/terraform-provider-opentelekomcloud#959]
# Description of the enhancement
OpenTelekomCloud OBS is compatible to S3. One of the most important features for a secure, german Cloud is bucket encryption.

There is a feature called "BucketKey encryption" on AWS S3:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/default-bucket-encryption.html
https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-key.html
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket

```hcl
resource "aws_s3_bucket" "mybucket" {
  bucket = "mybucket"

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        kms_master_key_id = aws_kms_key.mykey.arn
        sse_algorithm     = "aws:kms"
      }
    }
  }
}
```

The OTC provider for OBS is lacking this feature which makes it difficult to automate encryption configuration.

**Comment by lego963** [comment]
@tsdicloud as I can see we don't have the possibility to create "encrypted" buckets. We have only possibility to store files in bucket with encryption. 
https://docs.otc.t-systems.com/usermanual/obs/en-us_topic_0066036553.html

**Comment by tsdicloud** [comment]
I know that documentation of OpenTelekomCloud is lacking a hint on this feature, and obviously, there is no way to configure it via UI. But it is an (important) standard feature of S3 which is thus implicitly also implemented on OTC. We already use it extensively and it simply works. But we cannot configure it by Terraform.

If possible, a hint to HUawei from your side to at least extend API documentation is appreciated. I already communicated it via service management, but no answer so far.

If neccessary, we can write a proper test case for you.

**Comment by outcatcher** [comment]
@tsdicloud Okay, no need to make a proper test case, If it's really working we will follow AWS provider implementation. Is there any difference between how S3 and OBS work in this case?

I will create another internal incident :slightly_smiling_face:

**Comment by tsdicloud** [comment]
No, absolutely identical. There are some implication on the rights set at KMS (on OTC, it is difficult to restrict KMS access), but this has nothing to do with the configuration on bucket. A test case could a little bit tricky because the bucket key is only used on write without any reference, whereas you need a KMS AWS ARN pointing to your KMS key id on read from the buckets. Let me know if you need help on this.

**Comment by outcatcher** [comment]
@tsdicloud Can you please provide a working example of a request for creating such a bucket?

**Comment by lego963** [comment]
Internal incident: https://jira.tsi-dev.otc-service.com/browse/STO-4313

**Comment by Unichron** [comment]
Any update on this?

**Comment by outcatcher** [comment]
@Unichron I see an update just a few hours ago, mentioning this feature being released, though documentation is a bit late. We will wait for documentation updates and implement this feature on our side.

Internal for doc update:
https://jira.tsi-dev.otc-service.com/browse/RM-3968
