### ISSUE TITLE
Not able to select Agency type in provider

### ISSUE THREAD

**Issue by apurvdeodhar** [opentelekomcloud/terraform-provider-opentelekomcloud#962]
# Terraform Version

Terraform v0.14.7

# Affected Resource(s)

opentelekomcloud_identity_agency_v3

# Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
Create and place following content into respective files in a folder named `foo` or `test` or something

```
### versions.tf ###

terraform {
  required_providers {
    opentelekomcloud = {
      source  = "opentelekomcloud/opentelekomcloud"
      version = "1.23.4"
    }
  }
  required_version = "0.14.7"
}
```

```
### main.tf ###
terraform {
  backend "local" {
    path = "folder-created-above/terraform.tfstate"
  }
}

provider "opentelekomcloud" {
  access_key  = var.access_key
  secret_key  = var.secret_key
  domain_name = var.domain_name
  auth_url    = var.auth_url
  tenant_name = var.project_name
}

resource "opentelekomcloud_identity_agency_v3" "my_agency" {
  name                  = "my_agency"
  description           = "My Agency"
  delegated_domain_name = var.domain_name
  domain_roles          = ["Tenant Administrator", ]
}

```

```
### variables.tf ###
variable "access_key" {
  type        = string
  description = "Your OTC access key"
}

variable "secret_key" {
  description = "Your OTC secret key"
  type        = string
}

variable "domain_name" {
  description = "(User) Domain name, i.e. OTC-EU-DE-00000000000000000000"
  type        = string
}

variable "auth_url" {
  description = "Your OTC IAM auth url"
  type        = string
}

variable "project_name" {
  description = "Project name, something like 'eu-de'"
  type        = string
}

```

```
### outputs.tf ###
(Keep it empty)
```

# Debug Output/Panic Output

<img width="757" alt="Screen Shot 2021-04-07 at 02 30 57" src="https://user-images.githubusercontent.com/25170835/113796397-6f45fb80-974f-11eb-82e0-6126c5a85a76.png">

# Steps to Reproduce

1. `terraform apply` in the folder created above.

Terraform v0.14.7

# Expected Behavior

1. Looks like the provider is missing property `agency_type`. We should be able select either Account or a specific OTC service like ECS/BMS, CSS (same like when you would try to create an agency manually in UI 
<img width="1083" alt="Screen Shot 2021-04-07 at 03 22 41" src="https://user-images.githubusercontent.com/25170835/113796908-86391d80-9750-11eb-962f-622f15d0c140.png">

# Actual Behavior

1. This creates `agency_type = Account` by default.

# Important Factoids

# References

[1] https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/identity_agency_v3

**Comment by outcatcher** [comment]
This is missing from the API now:
https://docs.otc.t-systems.com/en-us/api/iam/en-us_topic_0079467617.html

Will create internal incident for that

**Comment by outcatcher** [comment]
Internal issue created:
https://jira.tsi-dev.otc-service.com/browse/OTCSEC-1814

**Comment by apurvdeodhar** [comment]
Thanks @outcatcher !!

**Comment by outcatcher** [comment]
New demand created:
https://jira.tsi-dev.otc-service.com/browse/DM-2520

**Comment by Aloento** [comment]
OTCSEC-1814 closed
DM-2520 is about to finish
If you have further questions, please reopen it.

**Comment by anton-sidelnikov** [comment]
DM-2520 still in progress, we need to wait implementation

**Comment by artem-lifshits** [comment]
Hello @apurvdeodhar while this is still in progress I've found a workaround on how to create ``cloud service agency`` with current ``opentelekomcloud_identity_agency_v3`` resource.

Looks like that every service agency relies on custom ``trusted_domain`` which, depending on the id, gives service cloud access for agency.

So if you know this id you can provide it in ``trust_domain_id`` field and agency will be of type ``Cloud service``.

To do that you can create a test cloud service agency with needed service type. After creation you can check its ``trusted_domain_id`` via API or by using google devtools, it will look like this:
![Screenshot 2022-09-07 at 14 11 56](https://user-images.githubusercontent.com/55093318/188864690-e88fddaa-025d-4523-8f87-68872c84a7cd.png)

Just copy ``trust_domain_id`` from here and paste into your config. The created agency will be ``Cloud service`` type.

**Comment by anton-sidelnikov** [comment]
Workaround found. We will Implement new resource when new API will be available
