### ISSUE TITLE
Filter and name_regex in datasource opentelekomcloud_images_image_v2

### ISSUE THREAD

**Issue by CHS-OTC** [opentelekomcloud/terraform-provider-opentelekomcloud#964]
is it possible to add the functions `filter` and `name_regex` to the `datasource opentelekomcloud_images_image_v2`?
Similar to the equivalent in AWS.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami
 
This would greatly simplify the handling.
To explain this, my request is not an acute problem, but a request to expand the functionality of the datasource `opentelekomcloud_images_image_v2` in the terraform provider for the OTC. A request for enhancement, so to speak.

**Comment by outcatcher** [comment]
`filter` is not implemented yet

**Comment by lego963** [comment]
`filter` is AWS specific :) It is used in `List` method
