### ISSUE TITLE
Set default DNS servers for the `vpc_subnet_v1`

### ISSUE THREAD

**Issue by outcatcher** [opentelekomcloud/terraform-provider-opentelekomcloud#965]
Currently, the subnet has an empty DNS list by default.

As #940 shows, this can lead to various unobvious problems.

**Comment by dombisza** [comment]
This is a really needed improvement, because the CCE installation process will fail if the worker node cannot resolve OBS addresses and the worker nodes inherit the DNS settings of the subnet.

**Comment by outcatcher** [comment]
I suppose, we can consider that accepted :)
