### ISSUE TITLE
Clarify the usage of network_id / subnet_id

### ISSUE THREAD

**Issue by shaderecker** [opentelekomcloud/terraform-provider-opentelekomcloud#967]
# Description of the enhancement
In `opentelekomcloud_cce_cluster_v3` there is the parameter [`subnet_id`](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cce_cluster_v3#subnet_id) which in reality is the network ID (in OpenStack terms).
The naming is really confusing and misleading.
Proposal: Rename this parameter to `network_id`  (see for example [opentelekomcloud_css_cluster_v1](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/css_cluster_v1#network_id), here it is named correctly).

Similarly in `opentelekomcloud_vpc_subnet_v1` it should be clearly stated that the [`id`](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/vpc_subnet_v1#id) attribute returns the ID of the network and not the ID of the subnet.

Same goes for the data source `opentelekomcloud_vpc_subnet_v1` and the [`id`](https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/data-sources/vpc_subnet_v1#id) attribute there. This also takes/returns the network ID and not a subnet ID.

**Comment by outcatcher** [comment]
That's a general problem of mixing OpenStack terminology with AWS-like one. In terms of VPC subnet has an `id`, `neutron_network_id` and `neutron_subnet_id`: https://docs.otc.t-systems.com/api/vpc/vpc_subnet01_0001.html#vpc_subnet01_0001__table54041329

I suppose we should switch to OpenStack-like terminology to avoid misunderstandings.

Renaming of resources should go through a special process:
https://www.terraform.io/docs/extend/best-practices/deprecations.html

I would not assign milestone to this issue, rather create a dedicated issue for each case and assign each of them to some milestone.
