### ISSUE TITLE
[CCE][NODE] Allow to modify auto generated security groups

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#970]
# Why?
The Enhanced ELB does not fulfil my requirements.
After several attempts, with tickets, calls with experts etc, I gave up on trying it with the ELB.
The only way for me now, is to expose my ingress-controller bare-metal using an EIP.

# How?
First I create CCE-Node with bandwidth 1000 so I get a node with an EIP.
Then I create my nginx-ingress with 80,443 ports.

# Issues?
1. I'm unable to access 80,443 via the EIP by default.
2. The auto generated security-group does not expose 80,443 from 0.0.0.0/0.
3. I dont have any control over the auto generated security group.
4. cce-node security groups need to be edited by hand. 
5. Doesn't "scale" work with autoscaling.
6. Access for 22, 3389, 30000-32767, 4789 and  30000-32767 is granted to 0.0.0.0/0.
7. SSH 22 is open to the world when providing a CCE-Node ith EIP **BY DEFAULT**!

# Solution?
I need the `opentelekomcloud_cce_node_v3` to be extende.

## First Idea
1. When `security_groups` is specified and not empty, don't automatically generate one.
2. Requires docs to be sure which ports (for cce) need to be opened and to whom and also point out that this is the responsibility of the user.
Like so:
```
  | Protocol & Port | Type | Source |
  | All | IPv4 | frontend-cce-cce-node-q6lti |
  | TCP : 22 | IPv4 | 0.0.0.0/0 |
  | TCP : 3389 | IPv4 | 0.0.0.0/0 |
  | TCP : 10250 | IPv4 | 172.16.0.123/32 | 
  | TCP : 10250 | IPv4 | 172.16.0.142/32 | 
  | TCP : 10250 | IPv4 | 172.16.0.199/32 | 
  | TCP : 30000-32767 | IPv4 | 0.0.0.0/0 |
  | UDP : 4789 | IPv4 | 0.0.0.0/0 |
  | UDP : 30000-32767 | IPv4 | 0.0.0.0/0 | 
```

```hcl
resource "opentelekomcloud_cce_node_v3" "node_1" {
  name              = "node1"
  cluster_id        = var.cluster_id
  availability_zone = var.availability_zone

  os        = "EulerOS 2.5"
  flavor_id = "s2.large.2"
  key_pair  = var.ssh_key

  bandwidth_size = 100
  
  security_groups   = [
    opentelekomcloud_compute_secgroup_v2.secgroup_1.id
  ]

  root_volume {
    size       = 40
    volumetype = "SATA"
  }

  data_volumes {
    size       = 100
    volumetype = "SATA"
  }
}
```

## Second Idea
Allow to specify additional `security_groups`. which then got assigned to the CCE-Nodes beside the auto generated one.
Requires the OpenTelekomCloud to be precise with its self provided security group entries.

Something like 22 on 0.0.0.0/0 then is a **NO-GO!**

```hcl
resource "opentelekomcloud_cce_node_v3" "node_1" {
  name              = "node1"
  cluster_id        = var.cluster_id
  availability_zone = var.availability_zone

  os        = "EulerOS 2.5"
  flavor_id = "s2.large.2"
  key_pair  = var.ssh_key

  bandwidth_size = 100
  
  additional_security_groups   = [
    opentelekomcloud_compute_secgroup_v2.secgroup_1.id
  ]

  root_volume {
    size       = 40
    volumetype = "SATA"
  }

  data_volumes {
    size       = 100
    volumetype = "SATA"
  }
}
```

**Comment by outcatcher** [comment]
I'm not sure that this can be implemented from the client side. Automatic assignment of the security group to the new nodes can be done only with support on the backend side.
API provides security group ID (one, not two for some reason) only for the cluster create/read operations (https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0236.html#cce_02_0236__table14385916163118). This one security group we can modify on our side. I suppose most we can do ― add `security_rules_override` (or something like this) field to the `opentelekomcloud_cce_cluster_v3` resource and create an internal issue stating your complaints about the existing CCE API and UI, as the console also doesn't provide a security group override during cluster creation. 

@Moep90 will it suffice for now?

**Comment by Moep90** [comment]
@outcatcher - is it possible to then create at least a data source for the `opentelekomcloud_networking_secgroup_v2` and
`opentelekomcloud_networking_secgroup_rule_v2`? I may can then update it to my needs.

**Comment by outcatcher** [comment]
Not sure how data source would help your case. We can add [`host_network`](https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0238.html#cce_02_0238__table1622013552507) attribute to the `cce_cluster_v3` resource, it contains security group ID. Is that what you want?

But still, what do you think about cluster `security_rules_override` argument overriding default SG rules?

**Comment by Moep90** [comment]
If I have the names and/or IDs of the `opentelekomcloud_networking_secgroup_v2` and the `opentelekomcloud_networking_secgroup_rule_v2`. I can simply update them. Sounds pretty straight forward to me.

> But still, what do you think about cluster security_rules_override argument overriding default SG rules?

@outcatcher Can you give an example?

**Comment by outcatcher** [comment]
Something like this:
```hcl


resource "opentelekomcloud_cce_cluster_v3" "node_1" {
  name              = "node1"
  ...
  
  security_rules_override = [
    {
      from_port   = 80
      to_port     = 80
      ip_protocol = "tcp"
      cidr        = "0.0.0.0/0"
    }
  ]

  ...
}
```
When I wrote it though, it doesn't seem to be such a great idea :)

I don't really get the part about data sources. At least `networking_secgroup_v2`(https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/data-sources/networking_secgroup_v2) data source actually exist. Can you provide an example configuration? I was thinking about just adding `opentelekomcloud_cce_cluster_v3.<name>.host_network.0.security_group_id` or `opentelekomcloud_cce_cluster_v3.<name>.security_group_id` attribute.

**Comment by Moep90** [comment]
I thought to have:
Fetching the auto generated secgroup based on the name of the cce-node.
```hcl
data "opentelekomcloud_networking_secgroup_v2" "secgroup" {
  name = module.cce_nodes.cce_node_name
}
```
Then using the ID to fetch some sort of a list of all sec_group_rules
```hcl
data "opentelekomcloud_networking_secgroup_rules_v2" "secgroup_rules" {
  security_group_id = opentelekomcloud_networking_secgroup_v2.secgroup.id
}
```
Now I have the ID's or Names or something at hand and can start updating them 1by1.
```hcl
resource "opentelekomcloud_networking_secgroup_rule_v2" "secgroup_rule_1" {
  direction         = "ingress"
  ethertype         = "IPv4"
  protocol          = "tcp"
  port_range_min    = 22
  port_range_max    = 22
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = opentelekomcloud_networking_secgroup_v2.secgroup_1.id
  security_group_rule_id = data.opentelekomcloud_networking_secgroup_rule_v2.secgroup_rules[0]
}
```
If no `security_group_rule_id` is specified, the `opentelekomcloud_networking_secgroup_rule_v2` works as usual.


Anyways I guess the simplest way is to change the Plattform to not "auto-create" stuff...

**Comment by outcatcher** [comment]
>Anyways I guess the simplest way is to change the Plattform to not "auto-create" stuff...

It will be the most correct way but unfortunately will have no time limit. I will create an internal incident for that.

Overwriting existing rules seems to be quite complex in terms of the resource workflow, basically, it's import+update (the behavior it's really nice to have in the terraform).

**Comment by outcatcher** [comment]
Internal issue created:
https://jira.tsi-dev.otc-service.com/browse/OCS-3676

**Comment by DanielHabenicht** [comment]
@outcatcher  any updates on that? 
I want to add my support as I am stuck with kind of the same problem: 

We are exposing UDP Ports to an ELB, but in order for the health check to work the Security Group needs to allow inbound traffic for ICMP on `100.125.0.0/16` but there is currently no way of changing the automatically created security group.

**Comment by outcatcher** [comment]
There is no update there since April. I suppose we will have to make a workaround for that. We will think about how can this be implemented on our side

**Comment by lego963** [comment]
@Moep90 will it be sufficient for you if we export IDs for both autogenerated SGs?

**Comment by Moep90** [comment]
@lego963 hm i need a way to change them after creation.
So you need to provide me a way so I can do that.

**Comment by lego963** [comment]
@Moep90
From the security design purposes, **WE MUSTN'T** modify secgroups [Risky Operations on Cluster Nodes](https://docs.otc.t-systems.com/en-us/usermanual2/cce/cce_01_0054.html).
For `80` and `443` you can use ELB with ingress controller which will expose necessary ports.

**Comment by lego963** [comment]
@DanielHabenicht you shouldn't modify secgroup for your needs, but we can create an internal ticket and to discuss how this can be done

**Comment by DanielHabenicht** [comment]
I already discussed that with the OTC Support but they thought that we will need to modify the SecGroup. I can forward you our communication. So you can add it to you ticket.

**Comment by lego963** [comment]
@DanielHabenicht share, please.

**Comment by Moep90** [comment]
If you provide a CCE with EIP ssh is already exposed to the world by default.

**Comment by outcatcher** [comment]
Needs further discussion, waining @lego963 to come back from the vacation.

**Comment by k11h-de** [comment]
First, I'd like to thank you guys for the good work you do and the improvements. the OTC Terraform provider is really a great one to work with! 

I would really love to see this improvement.
My use case is to have the CCE worker nodes and a RDS db in one security group.
So I would love to attach an additional sec group to the cce nodes (in my case created with opentelekomcloud_cce_node_pool_v3)

so I could do something like this:
```
resource "opentelekomcloud_cce_cluster_v3" "cluster_1" {
  name                   = "poc1-k8s-cl1"
  cluster_type           = "VirtualMachine"
  flavor_id              = "cce.s2.small"
  vpc_id                 = opentelekomcloud_vpc_v1.vpc_1.id
  subnet_id              = opentelekomcloud_vpc_subnet_v1.subnet_1.id
  ...
}

resource "opentelekomcloud_cce_node_pool_v3" "node_pool_az1" {
  cluster_id                = opentelekomcloud_cce_cluster_v3.cluster_1.id
  name                      = "poc1-k8s-cl1-ng1"
  os                        = "EulerOS 2.5"
  flavor                    = "s2.xlarge.2"
  initial_node_count        = 1
  availability_zone         = data.opentelekomcloud_compute_availability_zones_v2.zones.names[0]
  # this is a new argument
  additional_security_groups = [ opentelekomcloud_networking_secgroup_v2.rds_secgroup.id ]
  # ^^^^^^^^^^^^^^^^^^^^^^^
  key_pair                  = opentelekomcloud_compute_keypair_v2.admincs.name
  scale_enable              = true
  min_node_count            = 1
  max_node_count            = 4
  scale_down_cooldown_time  = 100
  priority                  = 1
  ...
}

resource "opentelekomcloud_networking_secgroup_v2" "rds_secgroup" {
  name        = "poc1-rds-secgr-1"
  description = "rds to ecc security group"
  ...
}

resource "opentelekomcloud_networking_secgroup_rule_v2" "rds_secgroup_port_3306" {
  direction         = "ingress"
  port_range_min    = 3306
  port_range_max    = 3306
  ethertype         = "IPv4"
  remote_group_id   = opentelekomcloud_networking_secgroup_v2.rds_secgroup.id
  security_group_id = opentelekomcloud_networking_secgroup_v2.rds_secgroup.id
  ...
}

resource "opentelekomcloud_rds_instance_v3" "instance" {
  name              = "poc1-ha-rds-1"
  security_group_id   = opentelekomcloud_networking_secgroup_v2.rds_secgroup.id
  vpc_id              = opentelekomcloud_vpc_v1.vpc_1.id
  subnet_id           = opentelekomcloud_vpc_subnet_v1.subnet_1.id
  flavor              = "rds.pg.s1.medium.ha"
  ...
}
```

I'd love to see this improvement - coming from AWS where this is possible too.

**Comment by anton-sidelnikov** [comment]
On discussion with R&D

**Comment by bbung** [comment]
Hey @anton-sidelnikov,
how is the discussion going? Any plans yet?

**Comment by anton-sidelnikov** [comment]
Hi, @bbung @Moep90, no changes from API side so far. 
But you can change nodes security group, by import it from cluster attributes:
```
      "mode": "managed",
      "type": "opentelekomcloud_cce_cluster_v3",
      "name": "cluster",
      "provider": "provider[\"registry.terraform.io/opentelekomcloud/opentelekomcloud\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "annotations": null,
            "authenticating_proxy": [],
            "authenticating_proxy_ca": null,
            "authentication_mode": "x509",
            "billing_mode": 0,
            "cluster_type": "VirtualMachine",
            "cluster_version": "v1.25",
            "container_network_cidr": "172.16.0.0/16",
            "container_network_type": "overlay_l2",
            "description": "",
            "eip": "",
            "eni_subnet_cidr": "",
            "eni_subnet_id": "",
            "extend_param": null,
            "external": "",
            "external_otc": "https://f6c69e54-48b0-11ee-aa7d-02550a100036.cce.eu-de.otc.t-systems.com",
            "flavor_id": "cce.s1.small",
            "highway_subnet_id": "",
            "id": "f6c69e54-48b0-11ee-aa7d-02550a100036",
            "ignore_addons": true,
            "ignore_certificate_clusters_data": null,
            "ignore_certificate_users_data": null,
            "installed_addons": [],
            "internal": "https://10.0.139.70:5443",
            "kube_proxy_mode": "ipvs",
            "kubernetes_svc_ip_range": "10.247.0.0/16",
            "labels": null,
            "multi_az": null,
            "name": "mycluster",
            "no_addons": null,
            "region": "eu-de",
----------------------------------------------------------------------------------------
            "security_group_control": "c54f11b1-627f-4c99-bf1b-a8d1af3bb61e",
            "security_group_node": "3655bfd8-c3da-417e-888f-3ca9a57c5d5e",
----------------------------------------------------------------------------------------
            "status": "Available",
            "subnet_id": "44ed75f0-65df-4865-b4d9-4565fc56e2f1",
            "timeouts": null,
        }
      ]
```

            "security_group_node": "3655bfd8-c3da-417e-888f-3ca9a57c5d5e"

That add necessary changes to security group:
```
resource "opentelekomcloud_networking_secgroup_rule_v2" "secgroup_rule_1" {
  description       = "http rule"
  direction         = "ingress"
  ethertype         = "IPv4"
  port_range_max    = 80
  port_range_min    = 80
  protocol          = "tcp"
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = "3655bfd8-c3da-417e-888f-3ca9a57c5d5e"
}

resource "opentelekomcloud_networking_secgroup_rule_v2" "secgroup_rule_2" {
  description       = "https rule"
  direction         = "ingress"
  ethertype         = "IPv4"
  port_range_max    = 443
  port_range_min    = 443
  protocol          = "tcp"
  remote_ip_prefix  = "0.0.0.0/0"
  security_group_id = "3655bfd8-c3da-417e-888f-3ca9a57c5d5e"
}

```

**Comment by anton-sidelnikov** [comment]
Also new demand created https://jira.tsi-dev.otc-service.com/browse/OTCPR-9230

**Comment by anton-sidelnikov** [comment]
Finally we have this feature in v1.36.22, please check.
