### ISSUE TITLE
[DOCS] Please use links to OpenTelekomCloud documentation

### ISSUE THREAD

**Issue by Moep90** [opentelekomcloud/terraform-provider-opentelekomcloud#971]
# Issue
1. On all/ mostly all resources/data sources there are attributes described but no valid parameter.
2. Every user need to search in terraform-registry + OTC-Docs

# Solution
Please always reference the respective OTC-Docs to the terraform-registry description for a particular resource/data source.

**Comment by outcatcher** [comment]
I suppose this should be added to contribution guidelines (missing now)

**Comment by artem-lifshits** [comment]
Links added in #2167.
