### ISSUE TITLE
Select Authorization Mode for CCE cluster

### ISSUE THREAD

**Issue by iitsBergenol** [opentelekomcloud/terraform-provider-opentelekomcloud#985]
# Description of the enhancement
In the documentation of manual cluster creation there is the possibility to select an authorization mode:
https://docs.otc.t-systems.com/en-us/usermanual2/cce/cce_01_0028.html

This is not possible in the ressource "opentelekomcloud_cce_cluster_v3".
The documentation of that resource in the terraform provider just mentions the authentication mode:
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cce_cluster_v3

The created cluster shows authorization mode: None in the GUI.

We need this feature to enable the RBAC mode in the cluster.

**Comment by outcatcher** [comment]
API don't provide such argument:
https://docs.otc.t-systems.com/en-us/api2/cce/cce_02_0236.html
Will create internal issue for that.

**Comment by outcatcher** [comment]
Internal issue creted:
https://jira.tsi-dev.otc-service.com/browse/OCS-3675

**Comment by artem-lifshits** [comment]
Hello @iitsBergenol ``RBAC`` mode can be seen now after providing parameters for ``authentication mode`` in provider:
![Screenshot 2022-09-07 at 15 52 53](https://user-images.githubusercontent.com/55093318/188883090-8615a7ad-3481-464d-9291-da3a369d823f.png)

Please check.
Closing the ticket, if the issue persists - please reopen it.
