### ISSUE TITLE
Add CSS HTTPS certificate to exported attributes

### ISSUE THREAD

**Issue by pbckr** [opentelekomcloud/terraform-provider-opentelekomcloud#986]
The HTTPS certificate can be exported using the OTC API and the OTC UI, but there is no exported attribute containing the Terraform CSS cluster resource. As the certificate is needed for using the CSS service it would be helpful to add it to the exported attributes of the CSS resource.

Terraform OTC provider CSS resource:
![image](https://user-images.githubusercontent.com/52598729/114860682-9b671980-9dec-11eb-8768-70957eaebe73.png)
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/css_cluster_v1

OTC UI:
![image](https://user-images.githubusercontent.com/52598729/114861253-4bd51d80-9ded-11eb-89bb-40ddf543e35f.png)

OTC API:
![image](https://user-images.githubusercontent.com/52598729/114860350-2bf12a00-9dec-11eb-8de3-b10594bd24ed.png)
https://docs.otc.t-systems.com/en-us/api/css/css_03_0050.html

**Comment by outcatcher** [comment]
Sorry for the wrong handling. This API is not implemented, an internal incident was created: https://jira.tsi-dev.otc-service.com/browse/OTCBIGDAI-842 (March, 10)

**Comment by Aloento** [comment]
OTCBIGDAI-842 closed and Won't Do

**Comment by anton-sidelnikov** [comment]
Please guys do retest @Aloento @artem-lifshits @vladimirvshivkov

**Comment by Aloento** [comment]
`/V1.0/{project_id}/cluster/sslCert`
`/v1.0/{project_id}/cluster/sslCert`
`/v1.0/{project_id}/cer/download`

```json
{
    "error_msg": "The API does not exist or has not been published in the environment",
    "error_code": "APIGW.0101",
    "request_id": "xxx"
}
```
