### ISSUE TITLE
[S3] opentelekomcloud_s3_bucket: Allow selection of storage class for bucket

### ISSUE THREAD

**Issue by philippeckel** [opentelekomcloud/terraform-provider-opentelekomcloud#992]
The provider currently is missing the option to choose a storage class for buckets. UI and the API has it.

```bash
openstack --os-cloud otc --os-project-name "eu-de" obs container create 
usage: openstack obs container create [-h] [-f {json,shell,table,value,yaml}] [-c COLUMN] [--noindent] [--prefix PREFIX]
                                      [--max-width <integer>] [--fit-width] [--print-empty]
                                      [--storage_class {STANDARD,STANDARD_IA,GLACIER}]
                                      <container-name>
```
So the provider is missing to choose `STANDARD`, `STANDARD_IA` and `GLACIER` option to choose between standard, warm and cold storage.

I assume `STANDARD_IA` stands for "Standard instance access" and `GLACIER` is obvious too.

Thanks!

**Comment by outcatcher** [comment]
There is `storage_class` in `opentelekomcloud_obs_bucket`. If there are no issues blocking its usage, we would recommend using `opentelekomcloud_obs_bucket` instead of `opentelekomcloud_s3_bucket`. We were planning to remove `s3` resources in the future.

**Comment by philippeckel** [comment]
@outcatcher thanks for your answer, the status of `opentelekomcloud_obs_bucket` vs `opentelekomcloud_s3_bucket` was not that clear ...

**Comment by philippeckel** [comment]
Closing the issue ...

**Comment by outcatcher** [comment]
Sorry for such inconvenience. I've tried to cover this topic in https://github.com/opentelekomcloud/terraform-provider-opentelekomcloud/discussions/776
