### ISSUE TITLE
[IAM] opentelekomcloud_identity_role_v3: usage of "display_name" instead of "name"

### ISSUE THREAD

**Issue by philippeckel** [opentelekomcloud/terraform-provider-opentelekomcloud#993]
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/identity_role_v3#display_name

Technically this is working but is there any specific to use `display_name` instead of standard `name` for the name of the role?

Thanks!

**Comment by outcatcher** [comment]
That's just a field name from the API specification:
https://docs.otc.t-systems.com/en-us/api/iam/iam_02_0013.html

Also, in the response, there are two fields: `name` and `display_name`.

I don't think that OTC API directly maps to the [OpenStack `role` API](https://docs.openstack.org/api-ref/identity/v3/index.html#create-role) in this case.

**Comment by philippeckel** [comment]
@outcatcher thanks, closing ...
