### ISSUE TITLE
Creating Subnet with opentelekomcloud_vpc_subnet_v1.subnet and parameter: dns_list

### ISSUE THREAD

**Issue by otc-fabo** [opentelekomcloud/terraform-provider-opentelekomcloud#994]
With the newest version and the change to a default DNS for opentelekomcloud_vpc_subnet_v1.subnet 
there is a problem when using dns_list: 

# Terraform Version
Terraform v0.12.28
+ provider.opentelekomcloud v1.23.7

# Affected Resource(s)
opentelekomcloud_vpc_subnet_v1.subnet

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_vpc_v1" "vpc" {
  name       = "vpc_name"
  cidr       = "192.168.0.0/16"
}

resource "opentelekomcloud_vpc_subnet_v1" "subnet" {
  name          = "subnet_name"
  vpc_id        = opentelekomcloud_vpc_v1.vpc.id
  cidr          = cidrsubnet(opentelekomcloud_vpc_v1.vpc.cidr, 8, 0)
  gateway_ip    = cidrhost(cidrsubnet(opentelekomcloud_vpc_v1.vpc.cidr, 8, 0), 1)
#  primary_dns   = "100.125.4.25"
#  secondary_dns = "8.8.8.8"
  dns_list = ["100.125.4.25", "8.8.8.8"]
}

```

# Debug Output/Panic Output
opentelekomcloud_vpc_subnet_v1.subnet: Creating...

Error: error creating OpenTelekomCloud VPC subnet: Bad request with: [POST https://vpc.eu-de.otc.t-systems.com/v1/d94574128d0d4540b768f9ade331b61b/subnets], error message: {"code":"VPC.0201","message":"dnsList is invalid"}

  on vpc.tf line 7, in resource "opentelekomcloud_vpc_subnet_v1" "subnet":
   7: resource "opentelekomcloud_vpc_subnet_v1" "subnet" {

problem is that the DNS are set by default now:
 # opentelekomcloud_vpc_subnet_v1.subnet will be created
  + resource "opentelekomcloud_vpc_subnet_v1" "subnet" {
      + availability_zone = (known after apply)
      + cidr              = "192.168.0.0/24"
      + dhcp_enable       = true
      + dns_list          = [
          + "100.125.4.25",
          + "8.8.8.8",
        ]
      + gateway_ip        = "192.168.0.1"
      + id                = (known after apply)
      + name              = "subnet_name"
      + primary_dns       = "100.125.4.25"
      + region            = (known after apply)
      + secondary_dns     = "1.1.1.1"
      + subnet_id         = (known after apply)
      + vpc_id            = (known after apply)
    }

with the old version (tested with  provider.opentelekomcloud v1.22.3 ):

  # opentelekomcloud_vpc_subnet_v1.subnet will be created
  + resource "opentelekomcloud_vpc_subnet_v1" "subnet" {
      + availability_zone = (known after apply)
      + cidr              = "192.168.0.0/24"
      + dhcp_enable       = true
      + dns_list          = [
          + "100.125.4.25",
          + "8.8.8.8",
        ]
      + gateway_ip        = "192.168.0.1"
      + id                = (known after apply)
      + name              = "subnet_name"
      + primary_dns       = (known after apply)
      + region            = (known after apply)
      + secondary_dns     = (known after apply)
      + subnet_id         = (known after apply)
      + vpc_id            = (known after apply)
    }

please check it

**Comment by outcatcher** [comment]
Follow-up of #977
