### ISSUE TITLE
CCE Cluster Creation fails on new accounts

### ISSUE THREAD

**Issue by DanielHabenicht** [opentelekomcloud/terraform-provider-opentelekomcloud#996]
# Affected Resource(s)
Please list the resources as a list, for example:
- opentelekomcloud_cce_cluster_v3

# Terraform Configuration Files
```hcl
resource "opentelekomcloud_cce_cluster_v3" "cce_cluster" {
  name        = "${var.root_name}-cce-cluster"
  description = "Kubernetes cluster to run containers."

  cluster_type           = "VirtualMachine"
  flavor_id              = var.cce_cluster_flavor
  cluster_version        = var.cce_cluster_version
  vpc_id                 = var.indicarus_vpc_id
  subnet_id              = opentelekomcloud_vpc_subnet_v1.cce_cluster_subnet.id
  container_network_type = "vpc-router"
  authentication_mode    = var.cce_cluster_authentication_mode
  eip                    = opentelekomcloud_vpc_eip_v1.cce_cluster_eip.publicip[0].ip_address
}
```

# Debug Output/Panic Output
```bash
Error: error creating opentelekomcloud Cluster: Bad request with: [POST https://cce.eu-de.otc.t-systems.com/api/v3/projects/dc6f1c54bde0489a9af906e0c921bbc9/clusters], error message: {"error_code":"CCE_CM.0201","error_msg":"Request body invalid","message":"Need authorize CCE to operate user resources","errorCode":"E.CFE.4000201","reason":"Request body invalid"}
  on modules/cce/main.tf line 47, in resource "opentelekomcloud_cce_cluster_v3" "cce_cluster":
  47: resource "opentelekomcloud_cce_cluster_v3" "cce_cluster" {
```

# Steps to Reproduce
1. Brand new OTC Account
2. `terraform apply`

To fix the error you have to login into the console and navigate to the CCE resource. Then you have to acknowledge this obvious popup: 

![image](https://user-images.githubusercontent.com/13590797/115436277-17a59680-a20b-11eb-9cad-c25d4f175067.png)

# Expected Behavior

- Don't have that popup to begin with. I am trying to automate!
- add an option/flag to automate this consent
- Display a more knowledgeable error
- Mention it in the documentation: https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cce_cluster_v3

# Actual Behavior

Errors

**Comment by outcatcher** [comment]
What should actually be in the message? It has a quite clear statement now: `Need authorize CCE to operate user resources`.

#### To do:
- Mention it in the documentation: https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cce_cluster_v3
- Create an internal incident to find out if there is a method to make this authorization via API

**Comment by outcatcher** [comment]
Internal demand created for authorizing CCE via API:
https://jira.tsi-dev.otc-service.com/browse/DM-2401

**Comment by DanielHabenicht** [comment]
> What should actually be in the message? It has a quite clear statement now: `Need authorize CCE to operate user resources`.

Well it fails to deliver an action that should be taken to resolve it. For those who now what to it is quite clear that they have to go to the UI. But for everybody else it is just saying something is failing. But where do I need to authorize? Maybe a link to a documentation site would help. As I was getting the error even googling did not result in any helpful link, but that should be taken care of by documenting it.

Thanks for asking internally.

**Comment by outcatcher** [comment]
@DanielHabenicht 
I failed to find proper documentation entry myself.

If there will be a message "CCE authorization via console required to perform CCE operations" instead of `Bad request ....` ― will it be more useful?

>Thanks for asking internally.

Thanks to @dombisza for directly creating a demand ticket :slightly_smiling_face: Though there is still no guarantee it will be implemented in the nearest future.

**Comment by ghost** [comment]
@DanielHabenicht 
By confirming CCE Service Authorization, which you need confirm for each project. I assume you are actualy working in the default-project "eu-de", the platform builds an IAM-agency for you- By confirming with yes, you allow the CCE service to access e.g. ELB, EVS ... 

You will find the agency in IAM | Agencies, for CCE it is called "cce_admin_trust"
![image](https://user-images.githubusercontent.com/73531539/115538396-1f614b80-a29c-11eb-8413-44164644b400.png)

With following resource you can create a agency by yourself.
https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/identity_agency_v3

A sample: 
```hcl
resource "opentelekomcloud_identity_agency_v3" "enable_cce_auto_creation" {
  name = "cce_admin_trust"
  description = "Created by Terraform to auto create cce"
  delegated_domain_name = "op_svc_cce"
  dynamic "project_role" {
    for_each = var.projects
    content {
      project = project_role.value
      roles = [
        "Tenant Administrator"
      ]
    }
  }
}
```

BUT: Keep in mind ... if you remove the Agency from your project and still have there e.g. another CCE running, this CCE will no longer work properly and wil get problems f.e. creating PVC (EVS-Disk) ... 

So you need to consider this. 
Hope this helps.

**Comment by outcatcher** [comment]
For easier planning #999 created

**Comment by victorgetz** [comment]
One Thing to mention.

I would update the documentation here 

https://registry.terraform.io/providers/opentelekomcloud/opentelekomcloud/latest/docs/resources/cce_cluster_v3

otherwise it indicates that this step can only be done manually

**Comment by DanielHabenicht** [comment]
@ulrschne I am working in a sub project but I hope your way works. I might try it with it the next time I encounter the problem. At the moment I don't have the bandwidth (and project) to try it. 

From my developer perspective I don't quite see why I need to create it. (e.g. Azure does allow creation of a cluster and dependent resources without creating an Service Authorization manually first) 
Also I don't get why you don't need to reference it during the creation of the cluster. It would make it way more obvious.

**Comment by outcatcher** [comment]
Also, it's quite interesting that a user without permission to create an agency is able to authorize CCE via console.

**Comment by Moep90** [comment]
Another funny fact here:

1. Getting a completely new tenant
2. ignore `eu-de` project
3. create project `eu-de_myproject`
4. create cce_cluster (with confirming) in `eu-de_myproject`
5. try to pull image from SWR into cce on `eu-de_myproject`
6. image pull fails with authorization errors

## WHY?
Because the serviceaccount to pull images from SWR is NOT aware of the project you're in.
It only lives in `eu-de` project. You can verify by extracting the base64 secret of it.

## How to resolve?
You've always to accept the CCE terms in `eu-de` project.


## Preventing
Can we extend the CCE-Documentation on TF for that? Like you did with the root issue here?
I requested to add a hint on OTC-Docs but I don't see that this will ever happen.

**Comment by dombisza** [comment]
This is a known issue(or maybe i should say we are aware of this). SWR is a region based service like OBS and it is not aware of sub-porjects. We are already discussing with the developers what we can do regarding this.
Most likely we will update our SWR documentation.

**Comment by anton-sidelnikov** [comment]
Seems that all clarified. Additional data sources created and documentation was changed
